### PR TITLE
Fix CleanRip reading Wii discs

### PR DESCRIPTION
**Pull request by JosJuice**
Yep, it actually works now! I've been able to rip a Wii game and get an ISO that's bit-for-bit identical to the original.

Most of the disc code in Dolphin seemed to use Read most of the time, only using RAWRead if Read didn't work, which isn't really correct. Read is the function that decrypts data, while RAWRead performs no encryption at all... but Read was being used for reading GC discs, despite them not having any encryption.

The first commit changes the DI command 0xA8 so that RAWRead is used. Because Read and RAWRead do the same thing for GC discs, there's no change with those. (VolumeDirectory didn't support RAWRead for GC discs before, but I fixed that.) Wii games don't use command 0xA8, so there's no change with them either. Only CleanRip (or theoretically other homebrew) reading Wii discs is affected.

The second commit changes the code to make it clearer whether decryption is being performed or not, so that there's a smaller chance of problems like this happening in the future. I had to update most calls to Read in order to do this, so there might be a risk that something is negatively affected.

### CODE REVIEW

**Comment by BigheadSMZ** [comment]
For some reason this revision causes Dolphin to search for the Xenoblade Japanese disc ID (SX4J01) and not the Europe version (SX4P01) that is patched with the 30 FPS patch when loading custom textures. The patch changes the region to Japan, but the disc ID remains SX4P01. Not sure if this is intended or a side effect of this PR.

**Comment by JosJuice** [comment]
This patch does change the way disc IDs are read. Before, it was done by reading from one of the partitions, and now it's done by reading the unencrypted data at the very beginning of the disc. Can you open the ISO in a hex editor and check what the game ID at the beginning is?

**Comment by BigheadSMZ** [comment]
Opened it up in a hex editor and It seems the 30 FPS patch does change the ID to SX4J01, but Dolphin UI still sees it as SX4P01. http://i.imgur.com/6Xu37Ez.png

Not sure what to do. If a work-around is impossible I can just inform users they need to convert the textures to SX4J01, but it might help if the UI reflects this change so when the ID is checked they see the Japan ID.

**Comment by JosJuice** [comment]
It would be possible to revert this behavior, but I don't see much of a reason to do it. I think real Wiis check disc data in this way, and discs aren't supposed to have two different IDs in different locations anyway, so it doesn't really affect anything other than this patch. The best solution would be to update the patch, although it would of course also be possible to manually edit the textures to SX4J01 or the ISO to SX4P01.

I couldn't reproduce the problem with the GUI. Editing the game ID at the beginning of the ISO makes it change in Dolphin. Maybe Dolphin has cached the old game ID for you or something like that?

**Comment by BigheadSMZ** [comment]
My bad, been sick so my judgement hasn't been so good lately. I accidentally loaded the wrong version of Dolphin for that screenshot. It is indeed correct in the GUI starting with this revision. And I agree its definitely not worth sacrificing accurate behavior for an unofficial patch for a specific game. 

I don't have the know-how to fix the patch, and I don't want to inconvenience a broad user base with having to use a hex editor (I think changing it to SX4J01 might be part of the reason as to why it works to begin with). This change is no big deal, I already have a batch renaming script specifically for Xenoblade to convert between regions, so users will just have to use it (or some other renaming method) if they apply the 30 FPS patch. Thanks for your time!

**Pull request merged**
