### PR TITLE
Image Optimizations.

### PR DESCRIPTION
**Pull request by aregowe**
Saved 180KB+ via image optimization.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3896)

### CODE REVIEW

**Comment by JosJuice** [comment]
In what way did you optimize them?

**Comment by aregowe** [comment]
Hi @JosJuice , I used https://tinypng.com/ to optimize the images. PNGs will retain their transparency, which I think is the most important thing with these images.

**Comment by JosJuice** [comment]
Doesn't that make the images 8-bit? From what I remember, @MaJoRoesch said we shouldn't make any lossy image optimizations. 200 kilobytes isn't really that much if it lets us have better images.

**Comment by aregowe** [comment]
Correct, that it does. It will convert any 24-bit PNG files to 8-bit. 

PNG-8 refers to palette variant, which supports only 256 colors, but is usually smaller in size.

PNG-24 refers to true color variant, which supports more colors, but might be bigger. PNG-24 can be used instead of JPEG, if lossless image format is needed.

Any modern web browser will support both variants. 

Visibly, I cannot discern the difference between the optimized images and unoptimized images. If we are unable to tell the difference, then I don't see the harm in using less space.

**Comment by JosJuice** [comment]
Okay, thanks for the copy-pasting. Web browser compatibility isn't really relevant here.

There are visible differences in your changes. For instance, compare the borders of gcpad_l_pressed.png or gcpad_r_pressed.png.

**Comment by CoolOppo** [comment]
If we're going to actually put the time into optimizing the images, it would be best to do it the right way.

**Comment by JosJuice** [comment]
They have already been optimized with zopflipng in PR #3682.

**Comment by CoolOppo** [comment]
> They have already been optimized with zopflipng in PR #3682.

Well there you have it.

**Comment by myownfriend** [comment]
Using PNGGauntlet on everything, I got a 300byte reduction but I'm not sure if anyone really cares about that kind of small savings.

**Comment by degasus** [comment]
Yeah, optimizing PNGs is usually worth it, but doing this again isn't: #3682 

This PR adds additional "optimizations" which affects the visual output, so I'm going to close it now.

**Comment by MaJoRoesch** [comment]
Thank you degasus. I was just about to freak out about TinyPNG. It extremely compromises image quality!

Also, all of the android buttons - where the optimization really matters! - are already optimized with optipng, which is truly lossless and retains the 24-bit quality of the images.

**Pull request closed without merging**
