### PR TITLE
Remove Global Declarations from Movie

### PR DESCRIPTION
**Pull request by RisingFog**
Removes all global declarations from Movie, and replaces them with getters and setters.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4088)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/Core/Movie.cpp, line 413 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4088#-KOLks9SDJ5ogO4TodeF:-KOLks9TeoEzKRg07EI2:-712387335) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ca3b6a72eae181222065bd493bb36dad2776e74d/Source/Core/Core/Movie.cpp#L413)):*
> ```cpp
> }
> 
> void SetClearSave(bool bEnabled)
> ```

the parameters can just be regularly snake-cased like `enabled`, `disc_changed`, etc.

---

*[Source/Core/Core/Movie.cpp, line 433 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4088#-KOLlDIoZpr-06o45IrR:-KOLlDIpo2wZYUiZIgh1:506853402) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ca3b6a72eae181222065bd493bb36dad2776e74d/Source/Core/Core/Movie.cpp#L433)):*
> ```cpp
> }
> 
> void SetDiscChange(std::string sDiscChange)
> ```

This should probably take the string by const reference.

The naming also seems somewhat ambiguous here (not like the variables weren't, really). Considering there's already a function named `SetChangedDisc`

You may want to combine these into one and make it just do something like

```cpp
void SignalDiscChange(const std::string& new_disc_filename)
{
  s_bDiscChange = true;
  s_discChange = new_disc_filename;
}
```

Since they're only ever used in conjunction with one another.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4088)*

**Comment by RisingFog** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[Source/Core/Core/Movie.cpp, line 413 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4088#-KOLks9SDJ5ogO4TodeF:-KOLzgLINAdrnzvDPrt4:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ca3b6a72eae181222065bd493bb36dad2776e74d/Source/Core/Core/Movie.cpp#L413)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> the parameters can just be regularly snake-cased like `enabled`, `disc_changed`, etc.
</details>
Done.

---

*[Source/Core/Core/Movie.cpp, line 433 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4088#-KOLlDIoZpr-06o45IrR:-KOLzwuBqYp9_XyMnu8-:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ca3b6a72eae181222065bd493bb36dad2776e74d/Source/Core/Core/Movie.cpp#L433)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> This should probably take the string by const reference.
> 
> The naming also seems somewhat ambiguous here (not like the variables weren't, really). Considering there's already a function named `SetChangedDisc`
> 
> You may want to combine these into one and make it just do something like
> 
> ```cpp
> void SignalDiscChange(const std::string& new_disc_filename)
> {
>   s_bDiscChange = true;
>   s_discChange = new_disc_filename;
> }
> ```
> 
> Since they're only ever used in conjunction with one another.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4088)*

**Comment by lioncash** [comment]
*[Source/Core/Core/Movie.cpp, line 421 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4088#-KOM-Duy17CtdU2NDmzg:-KOM-Duz_Wz4J5eIqMda:2019084009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/396fdafa9703e6bc831dd0c87b6c024202254a75/Source/Core/Core/Movie.cpp#L421)):*
> ```cpp
> {
> 	s_discChange = new_disc_filename;
> 	s_bDiscChange = true;
> ```

There's tabs instead of spaces here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4088)*

**Comment by RisingFog** [comment]
*[Source/Core/Core/Movie.cpp, line 421 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4088#-KOM-Duy17CtdU2NDmzg:-KOM03Afmay4yCYPlKEr:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/396fdafa9703e6bc831dd0c87b6c024202254a75/Source/Core/Core/Movie.cpp#L421)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> There's tabs instead of spaces here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4088)*

**Comment by lioncash** [comment]
Reviewed 7 of 10 files at r1, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4088)*

**Pull request merged**
