### PR TITLE
zlib: move to chromium's fork

### PR DESCRIPTION
**Pull request by shuffle2**
based on up-to-date upstream zlib
adds simd acceleration for various functions

crc32 is one of the most expensive functions when doing disc verify, this makes it much faster. it should also make things like the updater and any code using zlib in general faster.

here's perf overview of `DolphinTool verify -a crc32`:
image

note it's probably preferable to use zlib from Externals now for cmake platforms. I checked compile worked but haven't implemented it being the default.

### CODE REVIEW

**Comment by Pokechu22** [comment]
Would it be feasible to also convert zlib to a submodule with this change? Or is chromium's fork not as easily accessible?

**Comment by shuffle2** [comment]
I had to [apply some patches to it](https://github.com/dolphin-emu/dolphin/blob/fc741797ae880dff29929f0ed27bcade78974205/Externals/zlib/README.dolphin), so i dont think using it as a submodule is feasible at the moment.

**Comment by Pokechu22** [comment]
There's `git subtree` which does a similar thing as submodules, but it's not actually a submodule (instead it's mostly for splitting out commits that work in a subdirectory) to my understanding. It could theoretically be used to make a fork in the Dolphin org of the chromium zlib, but that's probably more work than it's worth.

**Comment by AdmiralCurtiss** [comment]
This doesn't build on Windows with CMake for me, because the mGBA target doesn't link against the zlib target (so it doesn't have the include path for the `#include <zlib.h>` in `mgba-util/crc32.h`). 5e3f1d62c0b8f82bd026b3311bca2021d2563e4b fixes it but raises the minimum CMake version to 3.13.

**Comment by shuffle2** [comment]
hm ok, i had only tried cmake 3.22 on linux (which worked). Is the PUBLIC required? seems not great?

**Comment by AdmiralCurtiss** [comment]
Hm not sure. PRIVATE compiles fine, but it does have the awkward side-effect that (since `HAVE_CRC32` is checked in a header), you get a declaration of a mGBA-internal `crc32` function that is incompatible with the zlib one if you include the `mgba-util/crc32.h`. I suppose it's okay if you never mix mGBA and zlib in the same compilation unit...?

**Comment by shuffle2** [comment]
Does PUBLIC mean the flag is only defined when the mgba PUBLIC headers are processed by dependents, or also when those dependents process other things? If the former, then it's fine.

**Comment by AdmiralCurtiss** [comment]
As far as I know PUBLIC just propagates into everything that links it -- it just sets the compile flags passed to the compiler. So all targets that link mGBA would also get the HAVE_CRC32 define across all compilation units.

**Review by AdmiralCurtiss — APPROVED** [review]
Seems good to me now.

**Comment by shuffle2** [comment]
Actually, I'll put this on hold for a bit - https://github.com/zlib-ng/zlib-ng is probably even better (when also considering zlib compression), and it's something we can make a submodule easily.

**Pull request closed without merging**
