### PR TITLE
Changed default freelook hotkey to match description

### PR DESCRIPTION
**Pull request by Stevoisiak**
Fixes issue #8019

### CODE REVIEW

**Comment by Buddybenj** [comment]
You didn't change the hotkey... The part you changed is commented out. :P
Change the 49 on increase speed to 50, and change the 50 on decrease speed to 49 (49 and 50 are the numbers that refer the the 1 and 2 keys respectively).

**Comment by Stevoisiak** [comment]
Now it should *actually* be fixed.

**Comment by Buddybenj** [comment]
LGTM

**Comment by MaJoRoesch** [comment]
Did anyone test this? It's still messed up in latest master. :(

**Comment by Stevoisiak** [comment]
@MaJoRoesch Just checked. You are right, it's still messed up, and I'm not sure why.

**Pull request merged**
