### PR TITLE
D3D: Remove the adapter selection dropdown.

### PR DESCRIPTION
**Pull request by magumagu**
It's mostly just a giant pain in the neck; handling all the edge cases is
hard, and our current implementation doesn't actually support any
interesting usecases anyway, as far as I can tell.  The only thing the
selection might be useful for at the moment is to support exclusive
fullscreen on the first monitor attached to a non-primary video adapter...
and I doubt that's useful considering that nobody has ever requested support
for exclusive fullscreen on non-primary monitors.

If this is too aggressive, I could make a smaller patch to just remove adapters with no outputs from the dropdown.

(I'll implement support for enabling WARP some other way.)

### CODE REVIEW

**Comment by mrgreywater** [comment]
This looks like a direct revert of the just merged https://github.com/dolphin-emu/dolphin/pull/1904

**Comment by JMC47** [comment]
I don't like this being removed; it makes selecting my Radeon when I'm running two graphics cards much easier.  On OpenGL, I have to switch which monitor my main monitor is.

I don't care enough to say no to this PR; it just slightly inconveniences one of my configurations with an issue that most people probably wouldn't run in into.

**Comment by degasus** [comment]
"On OpenGL, I have to switch which monitor my main monitor is." Isn't this the reason to remove it? iirc you've said that dolphin is much slower if not the GPU of the primary monitor is selected.

**Comment by magumagu** [comment]
@JMC47

**Comment by magumagu** [comment]
@JMC47 Wait, you actually use this?  Huh; then I guess adapter selection is actually usable for some purpose.  What does it do on master if you don't have a monitor attached to the card?

**Comment by JMC47** [comment]
It's a bit more complicated.  To get full speed on D3D with my radeon, I literally have to move the window onto the monitor that the GPU is connected to.  It doesn't matter which monitor is the main monitor.

@magumagu:  If no monitor is attached to the graphics card, I do not see that graphics card as selectable.

**Comment by magumagu** [comment]
(The reason I'm submitting this is that #1904 broke the error message for trying to select a secondary adapter on Optimus configurations; I can probably do something else to deal with that case, but I wanted to get some feedback about whether we actually want this feature in the first place.)

**Comment by magumagu** [comment]
@JMC47 It doesn't show up at all if a monitor isn't attached?  Oh, you're probably on Windows 7; we'd probably need to mess with adapter enumeration to get it to show up.

If adapter selection is useful for you, that's a good enough excuse to come up with a better solution. :)

**Comment by JMC47** [comment]
It's semi-useful?  I can just swap main monitors without any difficulties.  I think it's more confusing to Optimus users than it is useful for me.

**Comment by bb010g** [comment]
As long as the error message for Optimus is there, I don't see why this should be removed.

**Comment by magumagu** [comment]
Mmm... the problem is, how do we detect the situation where we need an error message.

I'm going to try and do some tests on JMC47's setup (which has multiple discrete GPUs) to figure out whether selecting an adapter without an output doesn't work at all, or just doesn't work on Optimus.

**Comment by CarlKenner** [comment]
I don't like the idea of removing this.

**Comment by magumagu** [comment]
I'm going to try and come up with a better solution for the remaining issues with the adapter dropdown.

**Pull request closed without merging**
