### PR TITLE
GMPE01, GP5E01, GP6E01, GP7E01, RM8E01: Code Updates

### PR DESCRIPTION
**Pull request by EndangeredNayla**

### CODE REVIEW

**Comment by EndangeredNayla** [comment]
crap line endings

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by AdmiralCurtiss** [comment]
Something went wrong here, please reopen with a fresh PR.

**Pull request closed without merging**
