### PR TITLE
[DO NOT MERGE] Qt: Misc improvements for JMC47

### PR DESCRIPTION
**Pull request by spycrab**
Here you go.

### CODE REVIEW

**Comment by MayImilae** [comment]
So um, regarding the IR spinbox... At over 30x native or so, most GPUs will just not work. Pascal and Volta are able to go up to about 50x native, and that's about it. When GPUs are at their absolute limit, it could crash the system, but in my experience only the emulator crashes.

Also there is the question of sane limitations. 8x Native is *already* beyond what anyone (outside of a titan v anyway :3 ) can run at full speed. It is an extremely sensible limit for the time being, and I don't see any reason to expand it.

Regardless, infinite resolution options is just not a good thing to expose to users. We can expand it if we want to, but we need to maintain limits in the GUI.

**Comment by MayImilae** [comment]
Also there is the issue of users being... users and raising the internal resolution option to obscene amounts expecting SSAA. This is terrible. We don't have the downscaling for that and even if we did SSAA would still perform and look better! The best situation is for users to set the Internal Resolution to their display resolution and then add SSAA on top of that. Having the Internal Resolution go up to insane amounts just encourages the bad behavior.

**Comment by stenzek** [comment]
I don't have a strong opinion on the spinbox vs dropdown issue, but you can prevent users from specifying IRs which will cause driver crashes by capping the IR at the result of this expression: 
`g_ActiveConfig.backend_info.MaxTextureSize / EFB_WIDTH`

Note; this does nothing to prevent the GPU from running out of VRAM in the first place. 51x will use roughly ~8.1GB of VRAM for the framebuffer alone. But there's no simple/reliable way of detecting VRAM without resorting to platform-specific code in the first place.

**Comment by spycrab** [comment]
I'll close this for now.

**Pull request closed without merging**
