### PR TITLE
Android: Set up Day/Night mode for system-compatible optional dark theme

### PR DESCRIPTION
**Pull request by TheRealPSV**
Updated Material Components dependency and implemented System-controlled Day/Night (Light/Dark) theming

Testing notes: Dark theme can be toggled through system settings in Android 10 (Q) and higher, or through an app like [Night Mode](https://f-droid.org/en/packages/io.github.subhamtyagi.nightmode/) for earlier Android versions.

Light Mode vs Dark Mode Screenshots:

### CODE REVIEW

**Comment by MayImilae** [comment]
Please provide some screenshots.

**Comment by TheRealPSV** [comment]
> Please provide some screenshots.

Done. I'm actually glad you asked, I found a bug I somehow missed with the Settings screen.

**Comment by Techjar** [comment]
Um, perhaps add ` | height=350` after the URL in the markdown to make the images easier to look at. They can still be clicked on for full size.

**Comment by TheRealPSV** [comment]
> 
> 
> Um, perhaps add ` | height=350` after the URL in the markdown to make the images easier to look at. They can still be clicked on for full size.

Github doesn't support that syntax anymore, see [here](https://gist.github.com/uupaa/f77d2bcf4dc7a294d109). I had to switch to an  tag, as mentioned in its comments.

**Comment by Techjar** [comment]
> Github doesn't support that syntax anymore, see here. I had to switch to an  tag, as mentioned in its comments.

Oooh, okay, well that's a bit annoying but I appreciate you going through the trouble.

**Comment by TheRealPSV** [comment]
> 
> 
> > Github doesn't support that syntax anymore, see here. I had to switch to an  tag, as mentioned in its comments.
> 
> Oooh, okay, well that's a bit annoying but I appreciate you going through the trouble.

Sure, I also went ahead and made the screenshots side-by-side comparisons, which I think is a better way to show the changes.

**Comment by Techjar** [comment]
> Sure, I also went ahead and made the screenshots side-by-side comparisons, which I think is a better way to show the changes.

Yeah that looks much nicer.

**Comment by TheRealPSV** [comment]
@Ebola16 

> Can you rebase this to the latest master? And in styles.xml, can you replace all `MaterialComponents` with `AppCompat` (see #8659)?

Done and done. I was going to remove the gradle dependency entirely, but it looks like its components are still used throughout the app elsewhere.

> Also note that the color of the "+" button has changed, but I don't mind that.

Apparently switching the MaterialComponents to AppCompat in styles fixed it.

**Comment by JosJuice** [comment]
This PR has had master merged into it instead of being rebased on top of master. Could you rebase the PR to get rid of the unrelated commits?

**Comment by TheRealPSV** [comment]
@JosJuice 
> This PR has had master merged into it instead of being rebased on top of master. Could you rebase the PR to get rid of the unrelated commits?

Sorry about that! Should be fixed now.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by Ebola16** [comment]
Can you squash those two commits?
If you don't know how see https://gist.github.com/patik/b8a9dc5cd356f9f6f980 and use "The hard(er) and less flexible way"

**Comment by TheRealPSV** [comment]
@Ebola16
> Can you squash those two commits?
> If you don't know how see https://gist.github.com/patik/b8a9dc5cd356f9f6f980 and use "The hard(er) and less flexible way"

Sure, does it look alright now?

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by Ebola16** [comment]
Settings submenu transition animations don't work properly in this PR. They appear to be fine in 5.0-11770.

Tested on:
Samsung Galaxy Note8 (SM-N950U)
Qualcomm Snapdragon 835
Octa-core (4x2.35 GHz Kryo & 4x1.9 GHz Kryo)
Adreno 540
6GB RAM (LPDDR4)
Android 9
OpenGL ES 3.2 V@331.0

**Comment by TheRealPSV** [comment]
@Ebola16 
> Settings submenu transition animations don't work properly in this PR. They appear to be fine in 5.0-11770.

I took a look and it turns out it's related to the hardcoded color value that was set in the settings recyclerview. I removed the color so the background would change along with the day/night theme, but it seems that the color is part of what makes the transition look the way it does. I replaced it with the default background color based on day/night.

This is the relevant line: https://github.com/dolphin-emu/dolphin/blob/5446e7b7d67bf6dab0e8da86c771a670e133737f/Source/Android/app/src/main/res/layout/fragment_settings.xml#L8

I tested it out and the transition works properly with both day and night mode now. Let me know if you encounter any more issues.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by leoetlino** [comment]
The contrast level for the purple text seems to be a bit low. Is it possible to use a less saturated colour for the dark theme?

**Comment by TheRealPSV** [comment]
@leoetlino 
> The contrast level for the purple text seems to be a bit low. Is it possible to use a less saturated colour for the dark theme?

Yeah, I see what you mean. How does this look? I can make the purple accent color lighter in dark mode, like this.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by TheRealPSV** [comment]
Anything more I can do to get this merged? Don't want it to sit around forever.

**Pull request merged**
