### PR TITLE
Edit error message

### PR DESCRIPTION
**Pull request by PEmu2**
Edit error message to be less sarcastic. I doubt many users appreciate this when Dolphin has just crashed on them.

### CODE REVIEW

**Comment by MayImilae** [comment]
Instead of just removing it, why not just replace it with something lighter, like "whoops", "oops", etc?

**Comment by PEmu2** [comment]
I don't see how that benefits anyone and as far as I know none of the other error messages in Dolphin are phrased like that.

**Comment by AdmiralCurtiss** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
LGTM, but wait with merging this until after the next beta release so that the translation for this string doesn't get reset.

**Pull request merged**
