### PR TITLE
Common: Handle trailing comments in INI parser, malformed GameIni resetting config values

### PR DESCRIPTION
**Pull request by stenzek**
This affected lines such as:
SomeBoolKey = True     # Comment here

Which would end up being parsed as false. The behavior now is to remove all characters afterwards, and including the #. 

Numerical values would still parse okay, since strtoul or stringstream would stop at the first non-digit, but failed for booleans, since we're comparing against 0/1/true/false.

I'm not sure if this is the best way to handle this, since from what I can tell, we're not following any formal INI file standard, so is permitting trailing comments after the best way to go? Or should we allow semicolon comments too?

Quickly searching, the closest thing I can find to a spec would suggest trailing comments should be a no, but that also uses semicolons, not hashes: http://stackoverflow.com/questions/1378219/do-standard-windows-ini-files-allow-comments (but some other applications that use ini-file configs permit hashes..)

The second commit stops this issue from happening in the first place. Currently, if a line fails to parse, the config value will get set to the default value according to the ini parser, instead of retaining its original value.

Example case where this causes issues: User sets bounding box enable to true, game ini has a malformed bbox enable line that doesn't parse correctly, bounding box enable gets set to false.

This affects some of our gameinis:

> $ egrep "^[^#]+#" *
> R64.ini:SyncGPU = True # Prevent CPU/GPU desync
> R8P.ini:EFBToTextureEnable = False # Fix transitions
> R8P.ini:BBoxEnable = True # Required for proper functionality
> RMC.ini:MSAA = 0 # Avoid overbloom
> RSP.ini:CPUThread = False # Display Mii faces correctly
> RZT.ini:EFBAccessEnable = True # Fix aiming

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3826)

### CODE REVIEW

**Comment by BhaaLseN** [comment]
We don't have any string values that contain a #, right? And, do we need to trim the remainder of the string so trailing whitespace doesn't affect the rest of the parsing (unless this is already taken care of elsewhere)?

**Comment by neico** [comment]
Space trimming is being taken care of inside of `IniFile::Section::Get(const std::string& key, std::vector<std::string>* out)`

**Comment by JosJuice** [comment]
Maybe we should just move all our game INI comments to separate lines instead of allowing trailing comments? Starting a comment in the middle of a line isn't a common practice in game INIs, and the few such ones we have would work fine on a separate line.

**Comment by BhaaLseN** [comment]
It would be the easier solution, given that @Sonicadvance1 has his new system in the pipeline. And after all, the best code is the one you don't have to write :)

**Comment by JosJuice** [comment]
As far as I know, the config system rewrite doesn't rewrite IniFile.

**Comment by JosJuice** [comment]
I made a PR that changes the game INIs: #3827

I would prefer to drop the first commit of this PR, so the INI format doesn't get more complicated than it needs to be. The second commit seems like a good idea, though.

**Comment by mimimi085181** [comment]
I'd be ok with dropping the 1st commit, if the 2nd would print an error on screen. But that would create a new string, so it's out of question for 5.0. Without the pr it's silently failing hard, disabling stuff that needs to be enabled. With the pr, it works correctly. With just the 2nd commit, it would fail silently, and depend on the user to have the right setting, which defeats the purpose of the ini system. So i'm against merging only the 2nd commit as it is right now.

**Comment by JosJuice** [comment]
The point of merging just the second commit would be that in case the user makes an error in an INI, that line will simply not work, unlike the way it is now where the error confusingly can override settings made elsewhere. That's a clear improvement in my opinion, regardless of whether there is an error message.

> With just the 2nd commit, it would fail silently, and depend on the user to have the right setting, which defeats the purpose of the ini system.

That's because INIs aren't supposed to contain invalid lines. Such lines have no purpose.

**Comment by mimimi085181** [comment]
Well, the blocker issue will be fixed as soon as pr https://github.com/dolphin-emu/dolphin/pull/3827 is merged, so i guess this pr could wait until after 5.0.

**Comment by degasus** [comment]
:lgtm:
please rebase

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3826#-:-KOodz0plgYIt9mjWkaV:b-fblutb)*

**Comment by JosJuice** [comment]
I still disagree with the first commit. All comments that start in the middle of lines have been removed now anyway.

**Comment by stenzek** [comment]
Rebased. I'm impartial either way as we're not following any sort of spec for inis, but if we drop the first change, it'd be good to document that trailing comments aren't supported (is this already written somewhere?)

**Comment by JosJuice** [comment]
I don't think we have any documentation about comments or our INI format at all.

**Comment by RisingFog** [comment]
Anything stopping this PR from being merged?

**Comment by stenzek** [comment]
I think the result here was to leave everything as-is?

**Pull request closed without merging**
