### PR TITLE
Logo refresh for android, windows, and linux

### PR DESCRIPTION
**Pull request by MayImilae**
Refreshed~

Thanks JosJuice for handling that Android Studio weirdness!

PNGs were optimized with oxipng. The filesizes are larger, but that's due to the increase in colour and the dithered gradients which reduce banding. The increase is expected. _No more optimization is needed._

UPDATE: I was so busy with the Android's modern vector adaptive icons that I didn't notice the padding for the old png ice_launchers! All fixed.

### CODE REVIEW

**Comment by MayImilae** [comment]
Tested Windows 11 and Android 14, both look great!

windows-1

windows-2

android

android-silohuette

**Comment by BreakPoints** [comment]
Windows still shows the old icon for Dolphin.exe at larger icon sizes, smaller sizes show the new icon. DolphinTool.exe doesn't exhibit this.

image

**Comment by MayImilae** [comment]
I did not see that in my testing on Windows 11. Did you build Dolphin yourself?

**Comment by BreakPoints** [comment]
I'm on the buildbot 2407-3 build, W11. If you can't reproduce I'm chalking it up to having a dolphin shortcut on my desktop and Windows just doesn't want to clear the cached icon (I've restarted and cleared thumbnail cache). Strange that it still applies to the exe as well as the shortcut.

**Comment by mbc07** [comment]
@BreakPoints if you rename Dolphin.exe to something else (e.g. Dolphin2.exe), does the new icon show up properly? If the answer is yes, then you didn't fully clear your icon and thumbnail cache. For reference, I'm on Windows 11 too and the new icon is showing correctly in all places (taskbar, Windows Explorer, start menu)...

**Comment by BreakPoints** [comment]
@mbc07 Yep, renaming updates the icon. Looks like Windows only clears dynamic thumbnails for videos and such with their cleanup function in settings. From past experience it should eventually tick over.

**Pull request merged**
