### PR TITLE
MachineContext: Fix USE_SIGACTION_ON_APPLE on arm64

### PR DESCRIPTION
**Pull request by merryhime**
n/t

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
The build failure on Android is because you based the PR on a commit that happened to be broken. Could you rebase?

**Comment by merryhime** [comment]
Rebased.

**Review by OatmealDome — APPROVED** [review]
Untested.

**Pull request merged**
