### PR TITLE
Update libpng to 1.6.29

### PR DESCRIPTION
**Pull request by TaoSc**
An update of #4584.

My first pull request to Dolphin ever!
I likely did at least one thing wrong

### CODE REVIEW

**Comment by spycrab** [comment]
@dolphin-emu-bot rebuild

**Comment by BhaaLseN** [comment]
You didn't update the CMake files, so it'll probably fail on non-Windows OS.

@dolphin-emu-bot rebuild

**Comment by TaoSc** [comment]
Sorry, my bad, completely overlooked that.
Should be fixed now

**Comment by ligfx** [comment]
@dolphin-emu-bot rebuild

**Comment by spycrab** [comment]
Please stash your changes into one commit, so it can be commited.

**Comment by TaoSc** [comment]
Done

**Comment by spycrab** [comment]
@dolphin-emu-bot rebuild

**Comment by BhaaLseN** [comment]
Android isn't just ARM, apparently we also support x86-64 - but I can't really comment too much on that. Some discussion on IRC brought up that this isn't fully correct at this point, and needs to be addressed in some way; so we probably shouldn't merge this just yet (unless someone from the more CMake-savvy folks looked at it - perhaps @Orphis? And/or someone from the Android side)

**Comment by TaoSc** [comment]
Oh yeah, you're absolutely right

I just looked at libpng's own CMakeLists and this is the condition they use to decide wether or not they should include the neon stuff:
`if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "^arm" OR
  ${CMAKE_SYSTEM_PROCESSOR} MATCHES "^aarch64")`

Judging by what you said, that might be more appropriate

**Comment by Orphis** [comment]
Do we need the assembly optimized part? I don't think that's too critical for us, so we could have a platform neutral one instead and a simpler build.

**Comment by TaoSc** [comment]
I guess we don't. I thought it would be worth it to have ever so slightly faster png decoding times on Android

So should I remove the Neon parts?

**Comment by Orphis** [comment]
Yes, do that, it's not performance critical.

**Comment by TaoSc** [comment]
Done, I think

**Comment by spycrab** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
