### PR TITLE
Add information about disc number in the netplay setup

### PR DESCRIPTION
**Pull request by mathieui**
Previously, two-disc games would appear exactly the same, and not
necessarily in disc order, which made it a pain.

Edit: And since netplay selects games based on title, this actually fixes the remote selection as well (previously it would select one at ~random)

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3793)

### CODE REVIEW

**Comment by Parlane** [comment]
Can you add a picture?

**Comment by mathieui** [comment]
Without the PR:
unnumbered discs

With the PR: 
discs!

**Comment by BhaaLseN** [comment]
Hm, would it be nicer to read if the first one had "Disc 1" too? Or even, perhaps, appending it inside the brackets (like "Revision 1" for Smash)...

**Comment by mathieui** [comment]
It’s a bit tricky to do if we don’t want to put "Disc 1" with nearly every game in existence.

**Comment by mathieui** [comment]
Parenthesis fixed:
looks better

**Comment by Helios747** [comment]
UI changes LGTM. I would like to see a "Disc 1" next to games that are multi-disc, but thinking about that, is it possible to tell which game has a disc 1 without it being a real pain in the butt?

**Comment by mathieui** [comment]
It would, by making the gamelist information available in that handler (e.g. by filtering on gameid)

**Comment by JosJuice** [comment]
I'm fine with not having a "Disc 1" text for now. The main game list has the exact same problem.

**Comment by mimimi085181** [comment]
You could tell which game has a disc 1, by checking which games have a disc 2. So if you have Tales of Symphonia disc 1 only, it does not show "disc 1", but if you have both discs, it can tell, that the 1st disc is the 1st disc of a 2 disc game.

**Comment by BhaaLseN** [comment]
I'm fine with just "Disc 2" in brackets tho, unless you can find an easy fix. Sorts nicer like that, so :lgtm:

**Comment by Helios747** [comment]
I want to post a crappy emoticon too

:lgtm:

**Comment by Parlane** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3793)*

**Pull request merged**
