### PR TITLE
Force Neo Geo games to use LLE Audio

### PR DESCRIPTION
**Pull request by RisingFog**
Another fix for [issue 9315](https://bugs.dolphin-emu.org/issues/9315).

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3841)

### CODE REVIEW

**Comment by RisingFog** [comment]
@Linktothepast feel free to review this

**Comment by JosJuice** [comment]
You should force DSP JIT too, otherwise people might end up with LLE interpreter depending on what their DSP JIT setting is.

**Comment by degasus** [comment]
DSP JIT is the default. I don't see why we should enfore it by game inis.

**Comment by JosJuice** [comment]
We used to force DSP JIT for all INIs that forced DSP LLE (until we stopped having any INIs with forced DSP LLE). I'm assuming it was because of something like it being possible to have DSPHLE = True, DSPJIT = False in the general config if LLE interpreter was selected before HLE. If that's not true, and DSPJIT always is True when HLE is enabled, then I do agree we shouldn't force DSP JIT.

**Comment by JMC47** [comment]
Using DSP-LLE on these games is a small performance hit (~10%) so this is fine with me.  Still over 300 FPS.

**Comment by JMC47** [comment]
Review status: 0 of 74 files reviewed at latest revision, 2 unresolved discussions.

---

*[Data/Sys/GameSettings/EA2.ini, line 9 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3841#-KHlnfVMSk6ULf0ouj9g:-KHlnfVMSk6ULf0ouj9h:-1592462843) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f1a8d52a22cd17f78e8b49e7e1f8daad9d2dcbf9/Data/Sys/GameSettings/EA2.ini#L9)):*
> ```INI
> [EmuState]
> # The Emulation State. 1 is worst, 5 is best, 0 is not set.
> EmulationStateId = 4
> ```

When DSP-LLE doesn't cause severe issues (like, making a game unreasonable demanding) I think the games that are tested should still be rated as Perfect.  This is kind of unrelated to the pull request but it just caught my eye.

---

*[Data/Sys/GameSettings/EA2.ini, line 21 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3841#-KHlnykGD9zW_JL3R-2c:-KHlnykH0iHAyozmBz2k:1007302546) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f1a8d52a22cd17f78e8b49e7e1f8daad9d2dcbf9/Data/Sys/GameSettings/EA2.ini#L21)):*
> ```INI
> # Add action replay cheats here.
> 
> [Video_Settings]
> ```

Is this lack of new line thing an issue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3841)*

**Comment by JMC47** [comment]
Reviewed 73 of 73 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3841)*

**Comment by JMC47** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Data/Sys/GameSettings/EA2.ini, line 9 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3841#-KHlnfVMSk6ULf0ouj9g:-KI3NCpSYoKRmDj3xGl0:-221022034) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f1a8d52a22cd17f78e8b49e7e1f8daad9d2dcbf9/Data/Sys/GameSettings/EA2.ini#L9)):*
<details><summary><i>Previously, JMC47 wrote…</i></summary>
> When DSP-LLE doesn't cause severe issues (like, making a game unreasonable demanding) I think the games that are tested should still be rated as Perfect.  This is kind of unrelated to the pull request but it just caught my eye.
</details>
This comment is really unrelated to the Pull Request and I regret making it.  I don't know how to delete it though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3841)*

**Comment by RisingFog** [comment]
*[Data/Sys/GameSettings/EA2.ini, line 21 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3841#-KHlnykGD9zW_JL3R-2c:-KI3OhVXr5-bg5zPmEgF:1052642571) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f1a8d52a22cd17f78e8b49e7e1f8daad9d2dcbf9/Data/Sys/GameSettings/EA2.ini#L21)):*
<details><summary><i>Previously, JMC47 wrote…</i></summary>
> Is this lack of new line thing an issue?
</details>
it shouldn't be

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3841)*

**Comment by JosJuice** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Data/Sys/GameSettings/EA2.ini, line 9 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3841#-KHlnfVMSk6ULf0ouj9g:-KI3OfLphCw_wrRX2uvo:1963503176) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f1a8d52a22cd17f78e8b49e7e1f8daad9d2dcbf9/Data/Sys/GameSettings/EA2.ini#L9)):*
<details><summary><i>Previously, JMC47 wrote…</i></summary>
> This comment is really unrelated to the Pull Request and I regret making it.  I don't know how to delete it though.
</details>
I don't think you can delete it, but what you can do is press the circle thing at the bottom-right corner of the comment field and change the status to Satisfied so it doesn't count as an unresolved discussion anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3841)*

**Comment by degasus** [comment]
:lgtm:

<details><summary><i>Previously, JMC47 wrote…</i></summary>
> Using DSP-LLE on these games is a small performance hit (~10%) so this is fine with me.  Still over 300 FPS.
</details>


---

Reviewed 74 of 74 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3841#-:-KI3dmuVEkVzQHSJ3EWn:1417088721)*

**Pull request merged**
