### PR TITLE
Remove Boot from DVD Backup

### PR DESCRIPTION
**Pull request by MayImilae**
This should be a fairly easy merge, assuming I didn’t mess anything up. TL:DR no one uses it and it’s not great.

Boot from DVD Backup is an ancient feature with origins in the Megacommit. Back then, GameCube and Wii games were quite large relative to drives of the time. For example, in 2008, the most common hard drive sizes were 320GB and 512GB. On the 320GB drive I personally had at the time, as little as 42 Wii ISOs could have filled it entirely! And that’s ignoring any other files one might want to put onto a drive. Backup DVDs allowed users to burn relatively cheap DVD media and store their GameCube and Wii dumps in a Dolphin accessible way that didn’t eat into their precious HDD space. It had compromises, even then, but in 2008… I mean honestly users probably wouldn’t even notice those compromises with how Dolphin barely even worked at all back then.

Obviously, today the storage space concerns are not as big of an issue. According to seagate the average hard drive it sells today is 8TB. For typical laptops purchased now, the -minimum- selection for storage is usually 1TB. You can even buy a name brand 4TB external hard drive for $100. GC and Wii ISOs are not as big as they once were, relatively anyway. Plus flash drives and SD cards are super cheap and way faster than disc drives ever were. For anyone that has limited drive space, removable flash media can fulfill this offloading role far better than backup DVD media ever could.

Also no one has DVD drives anymore. That’s kind of an important detail.

But to see if Booting from DVD Backup even still worked, I decided to give it a try. I have an ASUS BW-16D1HT, a badass Bluray XL reading and burning drive, connected to my Windows 11 Threadripper 5975WX machine. A super fast drive on a super fast machine is as good as it possibly can get for this feature. So I bought a spindle of DVD-Rs, burned a couple of discs and gave it a try. Surprisingly, it does still work. However, as expected, it introduces a lot of stuttering. Testing Prime 1 and Prime 3, in both games stuttering was introduced whenever the DVD Drive had to suddenly seek. Spikes of 50ms occurred constantly, but I observed 150ms and even over 1000ms stutters! The worst was a three second stutter, when loading Elysia in Prime 3. I could even hear the stutters - any time the drive suddenly made a harsh seeking noise, the game would have a hard stutter. It worked but, it has some serious compromises.

Boot from DVD Backup isn’t great, using removable flash media or external hard drives is a FAR better option for anyone with limited storage space today, and no one can even use this feature anymore because their computers don’t even have disc drives. It’s time for Boot from DVD Backup to go!

So I did my best on the cleanup but I’m bound to have left some bits. Especially in translation - I didn’t get any warnings or anything there that could help point me to where to clean that up. Please review!

### CODE REVIEW

**Comment by Zopolis4** [comment]
Note that https://github.com/LMauricius/EmuDiscer does use this functionality, but it hasn't been updated in a while and I don't know how many people are using it.

**Comment by BhaaLseN** [comment]
Since it built, you didn't _miss_ anything that needs to be removed at least. And from a quick glance, I _think_ you caught everything that can go away (which is mainly the `DriveBlob` and its usages).

What I'm not sure about is whether you should run the translation update script to get rid of the now obsolete resource, or if Transifex will take care of that. @JosJuice likely knows though.

**Comment by JosJuice** [comment]
> Since it built, you didn't *miss* anything that needs to be removed at least. And from a quick glance, I think you caught everything that can go away (which is mainly the `DriveBlob` and its usages).

I believe there's a function in Common for checking if something is a disc drive that's no longer used.

> What I'm not sure about is whether you should run the translation update script to get rid of the now obsolete resource

No, don't change the translation files in a pull request.

**Review by delroth — APPROVED** [review]

**Comment by mbc07** [comment]
We still have open issues in the bug tracker related to this feature (e.g. [issue 4564](https://dolp.in/i4564),unsure if there's more). They should probably be marked as "won't fix" now that this PR was merged...

**Comment by uVSthem** [comment]
I'm going to miss booting from the disc drive. I still have all my old DVD-R back ups and used this feature to anytime I played a game in Dolphin. I even have Gamecube games burnt onto mini DVD-Rs! I really hope this feature comes back at some point. If there is stuttering, I never noticed it during game play.

**Comment by LMauricius** [comment]
Was this feature causing problems for anyone? I loved using dvds for my games, so removing it seems like quite an aggresive move towards old-fashioned people. I personally never experienced stuttering and I know many people who are annoyed by having to buy an external drive for their old dvds. It makes sense for laptops, but a lot of custom desktop people do ask for a dvd drive to be added (me included).

**Comment by uVSthem** [comment]
> Was this feature causing problems for anyone? I loved using dvds for my games, so removing it seems like quite an aggresive move towards old-fashioned people. I personally never experienced stuttering and I know many people who are annoyed by having to buy an external drive for their old dvds. It makes sense for laptops, but a lot of custom desktop people do ask for a dvd drive to be added (me included).

This is exactly, how I feel. Was anyone complaining about the feature? Is having the option to boot off a disc drive taking away from other features or preventing new features from being added? I have all my old disc games burnt to CD-R and DVD-R. I like being able to pop the disc into a modded console and then use it in an emulator. Sega CD, PS 1 and 2, if there is an emulator that allows me to run games from disc, that is what I use. If at some point in the future, the stuttering from running off a disc can be removed, wonderful. If not, please let use few who run off a disc deal with it.

**Comment by nkeck720** [comment]
I second these motions. I use this feature daily. Was there really a good
reason to remove it besides "meh, screw those guys?" I have machines
dedicated to emulation that are diskless to prevent tying up a disk in them
where it's not needed.

Le mer. 18 janv. 2023 à 10:50 AM, uVSthem ***@***.***> a
écrit :

**Pull request merged**
