### PR TITLE
constexpr added to BitSet.h. conflicts solved

### PR DESCRIPTION
**Pull request by dhustkoder**
solved conflicts due to Reformatting

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3931)

### CODE REVIEW

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by Parlane** [comment]
Looks like you have some extra enters you don't need, see the output of lint here: https://buildbot.dolphin-emu.org/builders/lint/builds/1551/steps/shell/logs/stdio

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by Parlane** [comment]
You have trailing white-spaces still.

**Comment by dhustkoder** [comment]
@Parlane  Must've have used lint.sh before doing PR, sorry.

**Comment by Parlane** [comment]
@dolphin-emu-bot

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by Parlane** [comment]
You still have a space at the end of "constexpr int operator*() const { return m_bit; } "

**Comment by dhustkoder** [comment]
@Parlane just fine on lint here, thanks

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by Parlane** [comment]
@lioncash can you check this? I'm happy as long as you are.

**Comment by Parlane** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3931#-:-KL9__0xu5X0U8oh9sVa:1417088721)*

**Pull request merged**
