### PR TITLE
Qt/GCMemcardManager: Misc. improvements

### PR DESCRIPTION
**Pull request by spycrab**
**Before:**
Before
**After (Updated):**
After

### CODE REVIEW

**Comment by JMC47** [comment]
@MayImilae please review

**Comment by MayImilae** [comment]
It would probably be better for the buttons to be vertically centered in the space, imo. Since the UI can be scaled in all manner of ways, if the window is really tall, it would look rather odd with the buttons bunched up at the top! Otherwise, it's a definite improvement from the weirdly spaced out buttons of the past.

Oh um, I should mention... the memory card manager doesn't say memory card anywhere in it... If I didn't already know this is the memory card manager, I couldn't identify it since it doesn't say what it is anywhere! Can Memory Card Manager be the title of the sub window, or should it be like, memory card A and memory card B for each slot?

**Comment by JMC47** [comment]
Well, if you open the memory card manager, usually you already clicked Memory Card Manager, so it's not really *that* big of an issue.

**Comment by MayImilae** [comment]
True, but it's nice to have, especially if you have ADD or something and what you clicked a few seconds ago... (^～^;)ゞ

**Comment by spycrab** [comment]
@MayImilae All done (also removed the grid). See the updated screenshot (or take a look for yourself).

**Comment by spycrab** [comment]
Also fixed some string corruption bugs now.

**Comment by MayImilae** [comment]
Very nice!

I wish there was a way to remove columns or rearrange them, but that's something for later!

**Pull request merged**
