### PR TITLE
Disable Leaderboards Tab

### PR DESCRIPTION
**Pull request by LillyJadeKatrin**
Emergency PR to disable the leaderboards tab for launch if we are not satisfied with its testing yet.

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
Please explain yourself. What, why?

**Comment by LillyJadeKatrin** [comment]
I felt that our testing on the leaderboards was insufficient for the launch. We're testing things in staging currently but I don't know how safe this will be yet. I've told Jos that we should only merge this if we don't feel this is tested enough by the time we launch on Monday; that way we can start getting leaderboard data and I can verify this in branch before it goes in and potentially breaks the implementation.

**Comment by AdmiralCurtiss** [comment]
This is obsolete, right?

**Review by OatmealDome — APPROVED** [review]
Merging because there are an excessive amount of requests being made to the RA servers by the leaderboards tab, especially with some games having hundreds of leaderboards. We can see about fixing it in a later PR after further consultation with RA.

**Pull request merged**
