### PR TITLE
Jit64/JitArm64: Avoid churning range vectors in Jit()

### PR DESCRIPTION
**Pull request by lioncash**
We can just take these via const reference.

### CODE REVIEW

**Review by JosJuice — APPROVED** [review]

**Comment by JosJuice** [comment]
This is just an std::pair of two pointers, isn't it? But regardless, seems fine to merge.

**Comment by JosJuice** [comment]
One of the pitfalls of `auto` ;)

I'm leaning towards closing then, seeing as the commit title is misleading.

**Comment by lioncash** [comment]
Not necessarily auto (I just completely misread the function signature and thought it was much more heavyweight than it actually was)

But yeah, I'm fine with closing as well

**Comment by JosJuice** [comment]
> Not necessarily auto (I just completely misread the function signature and thought it was much more heavyweight than it actually was)

Sure, but my point is that if it hadn't been `auto`, you would have seen `std::pair<u8*, u8*>` written in the for loop, which would have made it clear. But I digress.

**Pull request closed without merging**
