### PR TITLE
Disable some Video settings for 1080° Snowboarding

### PR DESCRIPTION
**Pull request by ytrezq**
If enabled, in game virtual screens don’t works and camera might go below ground.
Also fix some graphical effects in menus.

Screenshots can be provided if needed.
All videos backends are affected if those settings are enabled.

### CODE REVIEW

**Comment by ytrezq** [comment]
@JMC47 : I recognize that’s only graphical glitches.
In the surfer selection menu the fire burns outside the fire place.

I also didn’t noticed any graphical performance impact. I can say that’s not even slowing graphical speed at all (though I can’t test on android).

**Comment by JMC47** [comment]
@dolphin-emu-bot rebuild

**Comment by JMC47** [comment]
Please use a 3 letter INI entry to cover all regions of the release.

**Comment by ytrezq** [comment]
@JMC47 : I don’t have ɪᴅs for other regions ? How should I rename ?

**Pull request closed without merging**
