### PR TITLE
Brexit

### PR DESCRIPTION
**Pull request by CarlKenner**
The European Union flag no longer represents Europe, let alone the PAL region, if it ever did. For example, I'm in Australia, and all my games are PAL region. The EU flag now symbolises a controversial political bureaucracy that half the Europeans are trying to distance themselves from.

I kept the colouring, but changed the stars to the text "PAL".

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3926)

### CODE REVIEW

**Comment by Helios747** [comment]
really

**Comment by CarlKenner** [comment]
really what?

**Comment by magcius** [comment]
This flag is for releases put out by Nintendo of Europe, which covers the UK. The terms "NTSC" / "PAL" for region releases has always been a misnomer, since they refer to broadcast signal technologies. Half of South America also uses PAL technology but they are not part of Europe.

**Comment by magcius** [comment]
Also, I echo Helios's sentiment. really?

**Comment by JosJuice** [comment]
It's true that the EU flag doesn't represent the P country code perfectly, but whether one country is in the EU or not doesn't affect that much, and your proposed new flag has problems like being unrecognizable.

@magcius It also covers Oceania in almost all cases, so it's not just Europe.

**Comment by CarlKenner** [comment]
Very few people are aware that they are put out by Nintendo of Europe (if that's even true). These games aren't made in Europe, they don't have the word Europe anywhere on the box, and they're sold outside Europe.

It's not a misnomer. They refer to broadcast signal technologies because the cartridge or disc is only programmed to output that broadcast signal, and will therefore only work on TVs that support that broadcast signal. A PAL game should work in half of South America, while a US game shouldn't.

And that was my point. This flag is for the PAL region, which is always referred to as the PAL region, and uses the code P in the GameID, while most of the PAL region is not part of the European Union. Using the European Union flag for it makes no sense.

For example, my copy of Twilight Princess has the word PAL on the front as the only indication of region, and on the back it says:
Distributed by Nintendo Australia PTY LTD
Scoresby Industrial Park, 804 Stud Road, Scoresby
Victoria 3179 Australia
http://www.nintendo.com.au

New Zealand Distributor
Softprint Interactive Ltd.
http://www.nintendo.co.nz

FOR USE WITH PAL VERSION Wii. Not compatible with Japanese, U.S. or other versions of Wii.

For sale and use in Australia and New Zealand only
Model No.: RVL-006(EUR)    Made in Japan
RVL-P-RZDP(AUS)    RVL-RZDP-AUS

**Comment by CarlKenner** [comment]
How is the new flag unrecognisable? That's exactly what it says on the front of *every* box and every disc. It's the old flag that is unrecognisable as a PAL region identifier.

**Comment by delroth** [comment]
Please do not phrase your PRs in the form of a political opinion.

**Comment by JosJuice** [comment]
@CarlKenner The *flag* is unrecognizable because it isn't used anywhere else. People might recognize the *word*, but even that isn't true of everyone. The PAL text on game boxes is very small and likely to be ignored or not understood by non-technical users.

**Comment by CarlKenner** [comment]
It's not a political opinion!!!!!

Brexit already happened. How any of us feel about it is now irrelevant. It's a historical event. And we have to adjust to it, because it changes our use of the flag from a representation of Europe to a controversial political statement. That's just the nature of historical events. It would be like using the USSR flag after the USSR fell. Before the event it just meant that region. After the event, it would be an unintended political statement in support of communism.

**Comment by refractionpcsx2** [comment]
I totally get your reasoning for this, it is a very valid reason, however we are still in the EU for at least another 2 years :p

**Comment by degasus** [comment]
I don't like the idea of using "PAL" within the logo, but need political correctness. Shall we drop one star from the EU flag?

**Pull request closed without merging**
