### PR TITLE
Various cleanups and updates in Android Gradle

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Update gradle wrapper to 6.3 using git bash

### 2nd commit
- Delete duplicated properties in gradle.properties

### 3rd commit
- Update Android Studio 3.5.3 -> 3.6.3

### 4th commit
- Remove unused dependencies exifinterface and constraintlayout

### 5th commit
- Fix some spacing
- Delete redundant semicolons in gradle

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
This pull request is relatively large, and the commits have no direct relation to each other. This would be easier to review if it was split into multiple pull requests.

**Comment by TacoTheDank** [comment]
Since the bulk of the changes are in the last 5 commits, I'll turn those into separate pull requests.

**Comment by TacoTheDank** [comment]
@JosJuice Did you see the updates? There was no new activity so I don't know if you got notified.

**Comment by JosJuice** [comment]
Ah, no, I missed it. Thanks for pointing it out. I believe GitHub does notify me when someone just pushes to a branch, but I've gotten into a habit of ignoring it because it usually is some change on some PR that doesn't concern me.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Pull request closed without merging**
