### PR TITLE
D3D: Fix multiple issues relating to MSAA

### PR DESCRIPTION
**Pull request by stenzek**
Trying to address this bug: https://bugs.dolphin-emu.org/issues/9107

It appears that whatever resolution had been rendered was being scaled up to the full XFB size when XFB was enabled on the D3D backend. The first commit changes this behavior to copy the entire framebuffer, instead of the source region, then presenting this region instead of the full texture, matching what the GL backend does. Also changes the linear to a point sampler since it's now a 1:1 copy. This should fix the aliasing issue mainly appearing with MSAA and XFB enabled on UI elements.
Before: http://i.imgur.com/l07AbhA.png
After: http://i.imgur.com/sVCI00H.png
GL (for reference): http://i.imgur.com/0rzolGv.png

The depth-of-field effect was broken as well in D3D (with MSAA enabled), from what I could tell is done by using a half sized copy of the framebuffer and blending this on top. A linear filter was used to downscale the image, however, when MSAA was enabled the filter had no effect, since the texture was not being sampled, rather the individual samples were being loaded, the downscaled image was not being filtered. The second commit solves this by resolving the MSAA buffer before copying. (this is a slower path compared to directly sampling the MSAA buffer, therefore it's only used when downscaling) From what I could tell, the GL backend also resolves before copying.
After changes: http://i.imgur.com/c8LmFPr.png
Matches the GL reference shot, apart from *very* slight differences I'm guessing are due to the backend or different sampling patterns?

Last part of the second commit fixes depth buffer copies when MSAA was enabled, this was completely broken before, since you can't resolve a MSAA depth buffer using ResolveSubresource, in fact it throws an error when running with the debug layer. This is achieved through loading all the samples for each pixel, and selecting the minimum depth value (not sure if this matches GL behavior, I didn't find any information on how glBlitFramebuffer resolves depth textures with a quick search)

I tested with a few titles and did not notice any regressions (in fact it fixed most DOF effects), but I'm not sure if this should be examined further.

### CODE REVIEW

**Comment by phire** [comment]
@dolphin-emu-bot rebuild

**Comment by JMC47** [comment]
@dolphin-emu-bot rebuild

**Comment by phire** [comment]
LGTM

Could we get some testing on various games JMC47? (special request for rogue squadron 2/3's intros)

**Comment by hrydgard** [comment]
Resolves of depth buffers are "normally" simply not done at all, although as it's needed in this case, a min() operation is indeed probably as good as any other function you could think of using.

**Comment by stenzek** [comment]
> Resolves of depth buffers are "normally" simply not done at all, although as it's needed in this case, a min() operation is indeed probably as good as any other function you could think of using.

Indeed. And using a box filter on depth values doesn't make sense either. The only other option I can think of is just taking the first sample from both colour and depth buffers, that way the game is getting values akin to not having multisampling enabled (though this would degrade visuals in regards to the colour buffer copy). But I'm not sure if any titles are this sensitive to very slight changes in depth/colour?

**Comment by JMC47** [comment]
I don't use msaa very often, so, my testing may not have been as good as it is in features I'm more familiar with.

I confirmed that Wind Waker looks much better with MSAA on than in master in this PR.  It's definitely a positive.

**Pull request merged**
