### PR TITLE
Convert Dolphin over to using libepoxy

### PR DESCRIPTION
**Pull request by Sonicadvance1**
Currently this still requires a bit of work to bring Windows support up.
But it should work everywhere.
This is basically a sanity check at the moment.

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
@dolphin-emu-bot rebuild

**Comment by shuffle2** [comment]
...

**Comment by Sonicadvance1** [comment]
what?

**Comment by delroth** [comment]
Is this still something we want @Sonicadvance1? Or should it be closed.

**Comment by Sonicadvance1** [comment]
It's something we want, but I hate developing on Windows so I can't care enough to continue it.

**Pull request closed without merging**
