### PR TITLE
VideoCommon: store the configuration used to create the AbstractPipeline

### PR DESCRIPTION
**Pull request by iwubcode**
This allows us to re-create the pipeline easily (with tweaked changes).  used in #11300

### CODE REVIEW

**Comment by iwubcode** [comment]
Noticed I missed some potential nullptr checks :x .  Will fix soon..

**Comment by phire** [comment]
It feels slightly sub-optimal to set the AbstractPipeline's config after it's created. 

1. It creates a potential foot-gun where a user of the CreatePipeline function forgets to set the config (and I kind of want to expose Abstract stuff via the scripting interface on my scripting branch) 
2. The memory needs to be written twice. First clearing to zero during initialisation and then copying the data into it a second time.

**Comment by iwubcode** [comment]
Thanks @phire for looking it over.  I considered doing this in `CreatePipeline()` originally, can't remember why I didn't go with that.  I will take another look.

**Comment by phire** [comment]
> can't remember why I didn't go with that. I will take another look.

Probably because it would have involved making the same change in 6 different files.

**Comment by iwubcode** [comment]
Ah yeah.  Then I considered doing an "impl" pattern but chickened out.  Guess I'll wait on your KillRenderer before making those changes.

**Review by phire — APPROVED** [review]

**Pull request merged**
