### PR TITLE
Netplay: check if all players have the game before starting

### PR DESCRIPTION
**Pull request by Aestek**
Fixes: https://bugs.dolphin-emu.org/issues/8885

* Display if players have the game next to the ping
* If not, print a confirm dialog

image

This is a WIP, to see if you guys would be ok with something like that. The code still needs some cleaning.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3858)

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/NetPlayClient.cpp, line 1187 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOM_-fDww4qC6bzL0G:-KIOM_-fDww4qC6bzL0H:-1023617847) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d4130d7b4ca50e17b498079823f31c7e4456f7d4/Source/Core/Core/NetPlayClient.cpp#L1187)):*
> ```cpp
> 	std::lock_guard<std::recursive_mutex> lkp(m_crit.players);
> 
> 	for (const auto& pair : m_players)
> ```

I think that one could be rewritten...as `std::any_of` or something like that

---

*[Source/Core/DolphinWX/NetPlay/NetWindow.cpp, line 311 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOMiRte6F8aXrqtJ-_:-KIOMiRte6F8aXrqtJ-a:-1356797480) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d4130d7b4ca50e17b498079823f31c7e4456f7d4/Source/Core/DolphinWX/NetPlay/NetWindow.cpp#L311)):*
> ```cpp
> void NetPlayDialog::OnStart(wxCommandEvent&)
> {
> 	if (!netplay_client->DoAllPlayersHaveGame()) {
> ```

Braces on next line, same for the `else`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by lioncash** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/NetPlayClient.h, line 41 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOtWHKR4vloZ098tqd:-KIOtWHKR4vloZ098tqe:862517212) ([raw file](https://github.com/dolphin-emu/dolphin/blob/e717b444c51ce0594617781ab6bfe99a77ca9bff/Source/Core/Core/NetPlayClient.h#L41)):*
> ```objc
> };
> 
> enum PlayerGameStatus
> ```

```cpp
enum class PlayerGameStatus
{
    Unknown,
    Ok,
    NotFound
};
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by BhaaLseN** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/NetPlayClient.h, line 41 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOtWHKR4vloZ098tqd:-KIOu0GzmCpGeTrj6d5C:-815028147) ([raw file](https://github.com/dolphin-emu/dolphin/blob/e717b444c51ce0594617781ab6bfe99a77ca9bff/Source/Core/Core/NetPlayClient.h#L41)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> ```cpp
> enum class PlayerGameStatus
> {
>     Unknown,
>     Ok,
>     NotFound
> };
> ```
</details>
Status is sent over the network in a packet, I don't know how that plays with `enum class`...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by lioncash** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/NetPlayClient.h, line 41 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOtWHKR4vloZ098tqd:-KIOuIOO8mKEqg1zPDGc:-1905841548) ([raw file](https://github.com/dolphin-emu/dolphin/blob/e717b444c51ce0594617781ab6bfe99a77ca9bff/Source/Core/Core/NetPlayClient.h#L41)):*
<details><summary><i>Previously, BhaaLseN (BhaaL) wrote…</i></summary>
> Status is sent over the network in a packet, I don't know how that plays with `enum class`...
</details>
`enum class` without a specified type is internally an int. A cast is fine, or you can overload operator<< and >> for sf::Packet. Don't pollute the global or containing namespace with constants when you don't have to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by Aestek** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/NetPlayClient.cpp, line 1187 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOM_-fDww4qC6bzL0G:-KIOycDAwCJMI1OSMX-K:-889666069) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d4130d7b4ca50e17b498079823f31c7e4456f7d4/Source/Core/Core/NetPlayClient.cpp#L1187)):*
<details><summary><i>Previously, BhaaLseN (BhaaL) wrote…</i></summary>
> I think that one could be rewritten...as `std::any_of` or something like that
</details>
does `std::any_of` removes the need for the lock ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by BhaaLseN** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/NetPlayClient.cpp, line 1187 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOM_-fDww4qC6bzL0G:-KIOytdwLYW0IQAzOQdd:-704584042) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d4130d7b4ca50e17b498079823f31c7e4456f7d4/Source/Core/Core/NetPlayClient.cpp#L1187)):*
<details><summary><i>Previously, Aestek wrote…</i></summary>
> does `std::any_of` removes the need for the lock ?
</details>
No, but it is nicer to read

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by Aestek** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/NetPlayClient.cpp, line 1187 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOM_-fDww4qC6bzL0G:-KIPMMa3gqEYK-MvbdMR:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d4130d7b4ca50e17b498079823f31c7e4456f7d4/Source/Core/Core/NetPlayClient.cpp#L1187)):*
<details><summary><i>Previously, BhaaLseN (BhaaL) wrote…</i></summary>
> No, but it is nicer to read
</details>
Done.

---

*[Source/Core/Core/NetPlayClient.h, line 41 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOtWHKR4vloZ098tqd:-KIPMIiZuRT0rNVLhIqa:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/e717b444c51ce0594617781ab6bfe99a77ca9bff/Source/Core/Core/NetPlayClient.h#L41)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> `enum class` without a specified type is internally an int. A cast is fine, or you can overload operator<< and >> for sf::Packet. Don't pollute the global or containing namespace with constants when you don't have to.
</details>
Done.

---

*[Source/Core/DolphinWX/NetPlay/NetWindow.cpp, line 311 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOMiRte6F8aXrqtJ-_:-KIPMNslW3H90vYTrWUC:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d4130d7b4ca50e17b498079823f31c7e4456f7d4/Source/Core/DolphinWX/NetPlay/NetWindow.cpp#L311)):*
<details><summary><i>Previously, BhaaLseN (BhaaL) wrote…</i></summary>
> Braces on next line, same for the `else`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by Helios747** [comment]
@dolphin-emu-bot rebuild

**Comment by lioncash** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/Core/NetPlayClient.h, line 41 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOtWHKR4vloZ098tqd:-KIPMug5a-_a9RCoSQZL:90602872) ([raw file](https://github.com/dolphin-emu/dolphin/blob/e717b444c51ce0594617781ab6bfe99a77ca9bff/Source/Core/Core/NetPlayClient.h#L41)):*
<details><summary><i>Previously, Aestek wrote…</i></summary>
> Done.
</details>
Enum class constants should be CamelCased like in the example I gave.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by Aestek** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/NetPlayClient.h, line 41 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOtWHKR4vloZ098tqd:-KIPUHtokWhtjFTOGC-a:116550092) ([raw file](https://github.com/dolphin-emu/dolphin/blob/e717b444c51ce0594617781ab6bfe99a77ca9bff/Source/Core/Core/NetPlayClient.h#L41)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> Enum class constants should be CamelCased like in the example I gave.
</details>
Done. Also note to self : do not try to `<<` into a packet without casting. Doesnt do anything good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by lioncash** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/NetPlayClient.cpp, line 1187 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOM_-fDww4qC6bzL0G:-KIQ6XLJVv2PIeOOxR97:-858048388) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d4130d7b4ca50e17b498079823f31c7e4456f7d4/Source/Core/Core/NetPlayClient.cpp#L1187)):*
<details><summary><i>Previously, Aestek wrote…</i></summary>
> Done.
</details>
```cpp
return std::all_of(std::begin(m_players), std::end(m_players), [](const auto& entry) {
    return entry.second.game_status == PlayerGameStatus::Ok;
});
```

---

*[Source/Core/Core/NetPlayClient.cpp, line 370 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIQ43Hd-jh0AKf2RaK8:-KIQ43Hd-jh0AKf2RaK9:1536643520) ([raw file](https://github.com/dolphin-emu/dolphin/blob/bc66a2b08c7eb0b60f38edcc1b2b774e81f6c768/Source/Core/Core/NetPlayClient.cpp#L370)):*
> ```cpp
> 
> 		sf::Packet spac;
> 		spac << (MessageId)NP_MSG_GAME_STATUS;
> ```

static_cast, same for below, and in the other case.

---

*[Source/Core/Core/NetPlayClient.cpp, line 635 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIQ4RGn4ONjQJGs1Ig5:-KIQ4RGn4ONjQJGs1Ig6:131642991) ([raw file](https://github.com/dolphin-emu/dolphin/blob/bc66a2b08c7eb0b60f38edcc1b2b774e81f6c768/Source/Core/Core/NetPlayClient.cpp#L635)):*
> ```cpp
> 		ss << "Has game: ";
> 
> 		switch (player.game_status) {
> ```

Brace on the next line. Also the case labels should be one indent less.

---

*[Source/Core/Core/NetPlayClient.cpp, line 645 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIQ55s5iKE4-SU-GmU9:-KIQ55s6PP_alKH_qYw6:1514911239) ([raw file](https://github.com/dolphin-emu/dolphin/blob/bc66a2b08c7eb0b60f38edcc1b2b774e81f6c768/Source/Core/Core/NetPlayClient.cpp#L645)):*
> ```cpp
> 
> 			default:
> 				ss << "unknown";
> ```

this should have a `break;` as well.

---

*[Source/Core/Core/NetPlayServer.cpp, line 325 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIQ4XmZ4VAvqazic3Ir:-KIQ4XmZ4VAvqazic3Is:-1036591025) ([raw file](https://github.com/dolphin-emu/dolphin/blob/bc66a2b08c7eb0b60f38edcc1b2b774e81f6c768/Source/Core/Core/NetPlayServer.cpp#L325)):*
> ```cpp
> 
> 		spac.clear();
> 		spac << (MessageId)NP_MSG_GAME_STATUS;
> ```

static_cast, same as below, and in the other case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by Aestek** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/NetPlayClient.cpp, line 1187 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIOM_-fDww4qC6bzL0G:-KIUZ_7dGmIqiP6S5rIm:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d4130d7b4ca50e17b498079823f31c7e4456f7d4/Source/Core/Core/NetPlayClient.cpp#L1187)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> ```cpp
> return std::all_of(std::begin(m_players), std::end(m_players), [](const auto& entry) {
>     return entry.second.game_status == PlayerGameStatus::Ok;
> });
> ```
</details>
Done.

---

*[Source/Core/Core/NetPlayClient.cpp, line 370 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIQ43Hd-jh0AKf2RaK8:-KIUZYHRHTM1sIt2lJhC:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/bc66a2b08c7eb0b60f38edcc1b2b774e81f6c768/Source/Core/Core/NetPlayClient.cpp#L370)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> static_cast, same for below, and in the other case.
</details>
Done.

---

*[Source/Core/Core/NetPlayClient.cpp, line 635 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIQ4RGn4ONjQJGs1Ig5:-KIUZZ55Zhn579i9ANrj:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/bc66a2b08c7eb0b60f38edcc1b2b774e81f6c768/Source/Core/Core/NetPlayClient.cpp#L635)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> Brace on the next line. Also the case labels should be one indent less.
</details>
Done.

---

*[Source/Core/Core/NetPlayClient.cpp, line 645 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIQ55s5iKE4-SU-GmU9:-KIUZZbeUXm-ebLLnv13:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/bc66a2b08c7eb0b60f38edcc1b2b774e81f6c768/Source/Core/Core/NetPlayClient.cpp#L645)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> this should have a `break;` as well.
</details>
Done.

---

*[Source/Core/Core/NetPlayServer.cpp, line 325 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIQ4XmZ4VAvqazic3Ir:-KIUZ_mRkLruffIUkGPF:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/bc66a2b08c7eb0b60f38edcc1b2b774e81f6c768/Source/Core/Core/NetPlayServer.cpp#L325)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> static_cast, same as below, and in the other case
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild ya socks thanks.

**Comment by mathieui** [comment]
Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[Source/Core/Core/NetPlayClient.cpp, line 376 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIUoeExOSL0KrHg88TF:-KIUoeEyQLyjPr6GRGs_:-896289522) ([raw file](https://github.com/dolphin-emu/dolphin/blob/b5b66d1356bb2bb96d839c5d62be15719f5b17e6/Source/Core/Core/NetPlayClient.cpp#L376)):*
> ```cpp
> 			: PlayerGameStatus::Ok;
> 
> 		spac << static_cast<int>(status);
> ```

I’m not sure what's the policy on this, but I feel like it would be better to use explicit-sized types (e.g. s32/u32/u8) for packing/unpacking values in netplay

---

*[Source/Core/DolphinWX/NetPlay/NetWindow.cpp, line 315 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIUnsEGl17Jl_F3M-9f:-KIUnsEGl17Jl_F3M-9g:31175128) ([raw file](https://github.com/dolphin-emu/dolphin/blob/b5b66d1356bb2bb96d839c5d62be15719f5b17e6/Source/Core/DolphinWX/NetPlay/NetWindow.cpp#L315)):*
> ```cpp
> 	{
> 		should_start = wxMessageBox(
> 			_("Not all players have the game. Do you really want to start ?"),
> ```

No space before "?"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by E2xD** [comment]
Quick question, will this also check to make sure all parties have emulation closed before launching?

**Comment by Aestek** [comment]
@E2xD no, it doesnt atm, this could be added in another PR

**Comment by E2xD** [comment]
Ah Okay. I misread the title for the longest time. That is a HUGE issue on Smashladder.

**Comment by Aestek** [comment]
This is an interesting feedback. Instead of a `Has game` label below the players, we could have a
`Status` :
* Playing
* Ready
* Game missing

And the confirm dialog would appear whenever some players are not ready

**Comment by JMC47** [comment]
That sounds good to me.

**Comment by E2xD** [comment]
Same

**Comment by Aestek** [comment]
Rebased. Also changed the texts to reflect our last discussion.

**Comment by E2xD** [comment]
I would love to test this :3

**Comment by mathieui** [comment]
@dolphin-emu-bot rebuild

**Comment by E2xD** [comment]
Ayy, this works as intended.

**Comment by clinchergt** [comment]
Worked just fine for me too

**Comment by JMC47** [comment]
What's with the failing builds?  Is the buildbot done?

**Comment by phire** [comment]
Ubuntu might have been a small hickup, I'm not sure.

**Comment by Aestek** [comment]
Re-tested it on my side, this is ready to merge AFAIC (:

**Comment by Helios747** [comment]
Reviewed 1 of 7 files at r6, 4 of 6 files at r7.
Review status: 5 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[Source/Core/Core/NetPlayServer.cpp, line 355 \[r7\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KM-QERjMFX1DCvnkUEZ:-KM-QERkXmgZswPp14ol:-1140750091) ([raw file](https://github.com/dolphin-emu/dolphin/blob/965b07ab9fdf0f0e96adfdc2b445a5bb6f4b8240/Source/Core/Core/NetPlayServer.cpp#L355)):*
> ```cpp
>         PanicAlertT("Client disconnect while game is running!! NetPlay is "
>                     "disabled. You must "
>                     "manually stop the game.");
> ```

Did clang-format format this funny?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by clinchergt** [comment]
@Aestek: could you review the comments from reviewable please? Thanks! :D

**Comment by delroth** [comment]
And rebase.

**Comment by Aestek** [comment]
Review status: 5 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/NetPlayClient.cpp, line 376 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIUoeExOSL0KrHg88TF:-KMIqdgtqMBqAbNpsx-r:391303028) ([raw file](https://github.com/dolphin-emu/dolphin/blob/b5b66d1356bb2bb96d839c5d62be15719f5b17e6/Source/Core/Core/NetPlayClient.cpp#L376)):*
<details><summary><i>Previously, mathieui (mathieui) wrote…</i></summary>
> I’m not sure what's the policy on this, but I feel like it would be better to use explicit-sized types (e.g. s32/u32/u8) for packing/unpacking values in netplay
</details>
You're right, I changed that.

---

*[Source/Core/Core/NetPlayServer.cpp, line 355 \[r7\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KM-QERjMFX1DCvnkUEZ:-KMIrnRd2aPnqvewBuwL:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/965b07ab9fdf0f0e96adfdc2b445a5bb6f4b8240/Source/Core/Core/NetPlayServer.cpp#L355)):*
<details><summary><i>Previously, Helios747 (Anthony Serna) wrote…</i></summary>
> Did clang-format format this funny?
</details>
Done.

---

*[Source/Core/DolphinWX/NetPlay/NetWindow.cpp, line 315 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858#-KIUnsEGl17Jl_F3M-9f:-KMIoNSSV1Ob7n5lrGU6:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/b5b66d1356bb2bb96d839c5d62be15719f5b17e6/Source/Core/DolphinWX/NetPlay/NetWindow.cpp#L315)):*
<details><summary><i>Previously, mathieui (mathieui) wrote…</i></summary>
> No space before "?"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3858)*

**Comment by clinchergt** [comment]
Test the most recent build and it works as expected. :+1:

**Pull request merged**
