### PR TITLE
JitArm64: Merge FP functions.

### PR DESCRIPTION
**Pull request by degasus**
This PR tries to merge some floating point instruction generators to share some common code.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3617)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, line 54 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617#-KAB4Rq8oR4qiZ_CKilJ:-KAB4Rq92HiSVC5vBLkD:855295845) ([raw file](https://github.com/dolphin-emu/dolphin/blob/c0b3ac12e33620adf9d85b8ad26f1f8494a73723/Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp#L54)):*
Bodies should be on a new line.

---

*[Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, line 71 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617#-KAB4Y1wxOonkKKMBrht:-KAB4Y1wxOonkKKMBrhu:855295845) ([raw file](https://github.com/dolphin-emu/dolphin/blob/c0b3ac12e33620adf9d85b8ad26f1f8494a73723/Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp#L71)):*
Bodies should be on a new line.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617)*

**Comment by BhaaLseN** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, line 64 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617#-KABD2ATyBluOWLO1p3-:-KABD2AUh-GND8uePCKq:-406752411) ([raw file](https://github.com/dolphin-emu/dolphin/blob/c0b3ac12e33620adf9d85b8ad26f1f8494a73723/Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp#L64)):*
Since we just had that discussion in #3613, `break;` at the end (of the `default` case) please.

---

*[Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp, line 84 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617#-KABDC2anj46lBK9hBxp:-KABDC2anj46lBK9hBxq:-1400911867) ([raw file](https://github.com/dolphin-emu/dolphin/blob/c0b3ac12e33620adf9d85b8ad26f1f8494a73723/Source/Core/Core/PowerPC/JitArm64/JitArm64_FloatingPoint.cpp#L84)):*
Same here for the `break;`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617)*

**Comment by Sonicadvance1** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617)*

**Comment by BhaaLseN** [comment]
Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp, line 103 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617#-KALHG06f_CQmDyIGqUv:-KALHG07LAyTuOSC8X85:2036815685) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3abe99e9dee358d167beb229d4213d4302bb117b/Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp#L103)):*
Is there any chance of this being hit with other, not handled values of `op5` (does a `default` case make sense here)?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617)*

**Comment by lioncash** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp, line 206 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617#-KALJpxBJ6J-FRIlN_t3:-KALJpxBJ6J-FRIlN_t4:1579836637) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3abe99e9dee358d167beb229d4213d4302bb117b/Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp#L206)):*
These ternaries can likely be stored to their own const variables to reduce duplication.  Also, is `upper ? VB : VA` intended to be the sequence of the FADD ternary for both branches (just double checking if one was supposed to be `upper ? VA: VB`)?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617)*

**Comment by degasus** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp, line 103 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617#-KALHG06f_CQmDyIGqUv:-KAM_lrh7owrL6_KcO-N:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3abe99e9dee358d167beb229d4213d4302bb117b/Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp#L103)):*
Done.

---

*[Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp, line 206 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617#-KALJpxBJ6J-FRIlN_t3:-KAM_KZ0UhkHWfB8Opxd:662642112) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3abe99e9dee358d167beb229d4213d4302bb117b/Source/Core/Core/PowerPC/JitArm64/JitArm64_Paired.cpp#L206)):*
Hm, not as easy. But I've checked the code right now, and the order is fine.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617)*

**Comment by BhaaLseN** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3617)*

**Pull request merged**
