### PR TITLE
Delete WPPJJF.ini

### PR DESCRIPTION
**Pull request by Buddybenj**

### CODE REVIEW

**Comment by Buddybenj** [comment]
@dolphin-emu-bot rebuild

**Comment by Buddybenj** [comment]
Ping @Linktothepast

**Comment by Linktothepast** [comment]
Lgtm https://github.com/dolphin-emu/dolphin/pull/2018 also had issues with this file and removed it.

**Comment by Stevoisiak** [comment]
GaneTDB says that this INI file would be used for [Okiraku Ping Pong](http://www.gametdb.com/Wii/WPPJ)

**Comment by Buddybenj** [comment]
Oh that's why I didn't see in GameTDB. Why is there a JF at the end of the INI in our database?

**Comment by Stevoisiak** [comment]
Because Dolphin includes the publisher ID as part of the GameID when most other sites omit it for WiiWare titles.

**Pull request closed without merging**
