### PR TITLE
fixed ArrayToString printing not paying attention to size

### PR DESCRIPTION
**Pull request by kamiyo**

### CODE REVIEW

**Comment by Tilka** [comment]
Please explain because I don't get it.

**Comment by kamiyo** [comment]
The ArrayToString is passed a size parameter, presumably to limit how much you print out. It does --size, but it never checks that size is > 0 (i.e. I was trying to print just xx amount of elements from an Array, but it was printing more than that). Hope that makes sense.

**Comment by delroth** [comment]
u32 is unsigned. Your patch does not change the behavior of this function, unless there is something really tricky I'm missing here.

**Comment by kamiyo** [comment]
Ah I get it now. Sorry, dumb me.

**Pull request closed without merging**
