### PR TITLE
Add cheat codes for Mario Golf: Toadstool Tour

### PR DESCRIPTION
**Pull request by chungy**

### CODE REVIEW

**Comment by JMC47** [comment]
You need a newline at the end of the file or else lint will complain.  Otherwise these codes look fine to me.

**Comment by chungy** [comment]
There is a newline at the end of the file, though ..?

**Comment by Techjar** [comment]
Yeah sorry, we checked again and there is. Carry on.

**Comment by JMC47** [comment]
I apparently suck at code review.

@dolphin-emu-bot rebuild

**Pull request merged**
