### PR TITLE
Fix test rumble feature in controller configuration

### PR DESCRIPTION
**Pull request by Connorapple**
This fixes the test rumble feature in controller configuration, which previously did not make the controller rumble at all. The rumble slider feature now controls the intensity of the motors, when it previously had no effect.

### CODE REVIEW

**Comment by Connorapple** [comment]
To clarify, in the dolphin issue tracker this is issue #10608 (https://bugs.dolphin-emu.org/issues/10608).

**Comment by jaylthegreat** [comment]
This adds a feature to sort the list of gecko codes alphabetically.  A sort button was added to the GUI in the Qt gecko cheat code menu. The codes are not permanently sorted, and will be returned to the natural ordering if you leave and re-open the menu.

**Comment by JosJuice** [comment]
Sorting Gecko codes isn't related to fixing the rumble test, so please put that in a separate PR.

**Comment by Connorapple** [comment]
@JosJuice Did that work to sort it out?

**Pull request merged**
