### PR TITLE
SSE-optimize UninitializeXFBMemory

### PR DESCRIPTION
**Pull request by hrydgard**
Just was curious how optimized Dolphin is these days. This was the lowest hanging fruit I could find with a profiler.

Not sure this "uninitialization" actually needs to be done, but assuming it is, why not do it quickly? 10x faster, goes from 1% CPU to 0.09% (lazy profiling using "Very Sleepy", don't take numbers too seriously).

### CODE REVIEW

**Comment by hrydgard** [comment]
So, that linter wants me to unindent a comment to the top level inside a function. This seems inconsistent with the surrounding code. Should I really do that?

**Comment by delroth** [comment]
Heh, interesting fail. Seems like it thinks your comment block applies to the ifdef and not to the body of the function. Tried adding a newline between the two?

**Comment by hrydgard** [comment]
Let's try that.

**Comment by delroth** [comment]
OK. We're overdue for a clang-format update at some point anyway, hopefully it will fix that and the rest (we're still on 3.8 or something old like that...). Let's just agree with it for now. If that doesn't get fixed by a clang-format update we can file a bug to LLVM folks.

All hail our robot overlords.

**Comment by hrydgard** [comment]
Darn. Wait, are you saying I should comply with it and actually do the wrong de-indent, or that we should ignore it?

**Comment by delroth** [comment]
I would do the "wrong thing", it's not destroying the readability too much and it won't cause issues when the next person edits the file. When we update clang-format I'll do a pass on everything to fix inconsistencies and hopefully it will be addressed then.

**Comment by hrydgard** [comment]
Finally.

**Comment by delroth** [comment]
LGTM. Mind squashing?

**Comment by hrydgard** [comment]
Done.

**Pull request merged**
