### PR TITLE
Disable wiimotes on game start if running in netplay

### PR DESCRIPTION
**Pull request by mathieui**
Trying to fix https://bugs.dolphin-emu.org/issues/9497

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3802)

### CODE REVIEW

**Comment by JMC47** [comment]
Netplay still doesn't boot if wiimotes are plugged in during a Wii game.

**Comment by JMC47** [comment]
Wiimotes get 0'd out even after the netplay session.  Netplay should not visibly change any settings past the netplay session.

**Comment by JMC47** [comment]
Working now as long as Dolphin doesn't crash (which is way too common on netplay.)

**Comment by aserna3** [comment]
Works on my machines. LGTM

**Comment by JMC47** [comment]
This seems like a @lioncash thing to review to make sure it's not doing anything insane with the wiimotes.

**Comment by mimimi085181** [comment]
To me it looks like the proper solution would be to create a wiimote counterpart to UpdateDevices.

Right now, the game sees all locally configured wiimotes. This is the reason for the problems, if one player has setup a local wiimote, even is no wiimote is mapped for netplay.

This also causes other issues for example, if you want to play with 3 players, all 3 players need to have set the 1st wiimote to what they want to use, and the 2nd and 3rd to at least emulated wiimote, or else it just fails.

I'm unable to write said proper mapping, i can't tell if this is good enough to be merged. But something should be done before 5.0.

**Comment by mathieui** [comment]
I made this with the assumption that we were keeping wiimotes disabled for 5.0, as they are right now. It is **not** a solution (well, it one to the issue that was created by disabling wiimotes), and I expect we will be coaxed into bringing it back right after release.

What this commit does is wipe the wiimote settings (the global vars) right upon starting a game, and restore them after stoping it, that’s all.

**Comment by RisingFog** [comment]
Anything remaining for this PR?

**Comment by degasus** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/NetPlayClient.cpp, line 730 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3802#-KICFXWEJgX1-7Ly-vbE:-KICFXWEJgX1-7Ly-vbF:270481775) ([raw file](https://github.com/dolphin-emu/dolphin/blob/59dad73b068862c69ef6b9bf3a73c505e61c992a/Source/Core/Core/NetPlayClient.cpp#L730)):*
> ```cpp
> 	m_dialog->BootGame(path);
> 
> 	if (SConfig::GetInstance().bWii)
> ```

Do you think there should a comment why you drop it? Maybe with a TODO: implement this in a better way. or TODO: remove this when wiimote netplay is implemented correcctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3802)*

**Comment by mathieui** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/NetPlayClient.cpp, line 730 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3802#-KICFXWEJgX1-7Ly-vbE:-KICcCvrrnK6CVYnT0mB:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/59dad73b068862c69ef6b9bf3a73c505e61c992a/Source/Core/Core/NetPlayClient.cpp#L730)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> Do you think there should a comment why you drop it? Maybe with a TODO: implement this in a better way. or TODO: remove this when wiimote netplay is implemented correcctly.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3802)*

**Comment by degasus** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3802)*

**Pull request merged**
