### PR TITLE
Fixed freelook description to match default hotkeys

### PR DESCRIPTION
**Pull request by Stevoisiak**

### CODE REVIEW

**Comment by Stevoisiak** [comment]
Fixes Issue #8019

**Comment by RachelBryk** [comment]
This should actually be fixed by fixing the default hotkeys, i didn't intend to change them.

**Comment by Stevoisiak** [comment]
@RachelBryk Should I submit this change instead?
https://github.com/Stevoisiak/dolphin/commit/9f9a9822591fb9e9e60559e4a1687b9b981200ae

**Comment by MaJoRoesch** [comment]
Shift+1 for slower and Shift+2 for faster makes sense, since it follows the left to right philosophy of western writing. I definitely think that alternate commit is a better solution.

**Comment by Stevoisiak** [comment]
Alright. Closing this, and opening the other one.

**Pull request closed without merging**
