### PR TITLE
clean up bounds checking for SIDEVICE_ENUM

### PR DESCRIPTION
**Pull request by meffij**
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4101)

### CODE REVIEW

**Comment by shuffle2** [comment]
should not need to cast the enum values to int...

**Comment by degasus** [comment]
Without the casts, it LGTM

**Comment by meffij** [comment]
Do you think we should switch the enum to uint to save the lower bounds check as well? Someone was saying that'd be better.

**Comment by lioncash** [comment]
Please squash your changes (see [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) for more on that, if you don't know how).

**Comment by leoetlino** [comment]
@dolphin-emu-bot rebuild

**Comment by phire** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4101#-:-KOfL8FZzJtlgyoOaBNs:bnfp4nl)*

**Pull request merged**
