### PR TITLE
DiscIO: Small VolumeDirectory simplifications

### PR DESCRIPTION
**Pull request by JosJuice**

### CODE REVIEW

**Comment by JosJuice** [comment]
Why doesn't this work on the FreeBSD and OS X buildbots?

**Comment by BhaaLseN** [comment]
```
Undefined symbols for architecture x86_64:
  "DiscIO::CVolumeDirectory::MAX_ID_LENGTH"
  "DiscIO::CVolumeDirectory::MAX_NAME_LENGTH"
```

Missing defines there, or perhaps missing includes.

**Comment by JosJuice** [comment]
They are defined in VolumeDirectory.h, which is included in VolumeDirectory.cpp.

**Comment by BhaaLseN** [comment]
Maybe their compilers don't quite understand ```static const size_t```? Just random guessing here, don't have either of them available at this point...

**Comment by delroth** [comment]
These should really be constexpr anyway, and that would solve any linkage issue (since constexpr are not present at link time).

**Comment by JosJuice** [comment]
constexpr didn't fix it, unfortunately.

**Comment by lioncash** [comment]
MAX_NAME_LENGTH and MAX_ID_LENGTH will need to be defined in the cpp file for VolumeDirectory like a normal static class member, because they're both used with std::min, which takes arguments by reference, therefore the constants need a definitive storage location in order to get an address for them.

**Comment by JosJuice** [comment]
So it's supposed to be like this?

**Pull request merged**
