### PR TITLE
Add a DISABLE_NLS option

### PR DESCRIPTION
**Pull request by martymac**
Add a DISABLE_NLS option

### CODE REVIEW

**Comment by Techjar** [comment]
Why?

**Comment by Techjar** [comment]
Wouldn't it make sense to also use an `#ifdef` to disable the language selection in the settings window when NLS is disabled?

**Comment by martymac** [comment]
Currently, Dolphin is able to fallback to system language if the selected language is not available. But you're right, this could be an improvement (though I am not sure how to do that exactly).

**Comment by Techjar** [comment]
It doesn't fallback to system language if no language files are present, it just falls back to English (the internal strings in the code). If the intention is to still support languages other than English, but without anything but system language, then this isn't the way to do it.

**Comment by lioncash** [comment]
The rationale should probably be included in the commit message, so it's easier to lookup from the git history if anyone ever looks up the reason for introducing it down the line from now

**Comment by riking** [comment]
I'm not sure that removing internationalization is really a good idea overall, especially if this is for packagers intending to distribute the compiled version (as opposed to personal use). Do packages built like this usually get distributed alongside a version that includes translations? (e.g. `dolphin-emu` normal + `dolphin-emu-en` english only)

**Comment by delroth** [comment]
I'm tempted to switch all the strings in our code to welsh and make english locales go through i18n just as a statement of how dumb I think disabling i18n is.

This is not a configuration we're interested in supporting, sorry.

**Comment by delroth** [comment]
As long as you understand that by doing so you're relying on an internal implementation detail which isn't guaranteed to hold true... ("strings that don't go through the i18n machinery are human readable english")

**Comment by martymac** [comment]
Yep. Thanks for the reminder!

**Pull request closed without merging**
