### PR TITLE
Force Real XFB and EFB2RAM for Story Hour: Adventures and Story Hour: Fairy Tales

### PR DESCRIPTION
**Pull request by RisingFog**
Works around issue 9597: https://bugs.dolphin-emu.org/issues/9597

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3901)

### CODE REVIEW

**Comment by Nebulous112** [comment]
Does this also address the other item reported in that issue? The issue mentions that "Store EFB Copies to Texture Only" needs to be turned off or the texture will fail to load when flipping the page.

**Comment by emko** [comment]
Yes that "Store EFB Copies to Texture Only" needs to be set to off or the game is not playable

**Comment by JMC47** [comment]
Ummm.  Please change the comment in the INI to say "EFB Copies to RAM".  It really confused me.

**Comment by JosJuice** [comment]
@JMC47 The setting itself needs to be changed too, right?

**Comment by JMC47** [comment]
I just woke up.  It's just, I assume we wouldn't be forcing on EFB2Tex as you know, that's the default.

**Comment by RisingFog** [comment]
@emko can you confirm that the INI changes work for you?

**Comment by emko** [comment]
@RisingFog yes sorry for taking so long, but yea both games now run correct with settings INI 

Thanks

**Pull request merged**
