### PR TITLE
MoltenVK: Update to Vulkan SDK version 1.1.108.0

### PR DESCRIPTION
**Pull request by stenzek**
Apparently this fixes a memory leak, see https://dolp.in/i11738/7

Untested, I just pulled the latest SDK.

### CODE REVIEW

**Comment by pizuz** [comment]
You might want to wait for the next version. 1.1.106.0 has two separate crashes with Dolphin. Both have been fixed, but those fixes haven‘t made it into LunarG‘s build, yet.

Issues:
https://github.com/KhronosGroup/MoltenVK/issues/573
https://github.com/KhronosGroup/MoltenVK/issues/584

**Comment by Degerz** [comment]
@stenzek An unrelated heads up for you but Khronos has just released their fragment shader interlock [extension](https://github.com/KhronosGroup/Vulkan-Docs/commit/619084d44a605285e39530a0810d323ad024f897#diff-fbe37dc7de672e09d9f2e0bc75370512) for Vulkan. Once MoltenVK supports the extension, you'll finally be able to add ROVs/interlocks for programmable blending thus being able to further improve the accuracy of GPU emulation!

**Comment by Dubai2014** [comment]
Cain anybody explain what i have to do to geht Dolphin with Vulkan Support to work on M.A. MacBook Pro?
I tried it with Version 5.0-10411. Thanks für your help

**Comment by MayImilae** [comment]
@Dubai2014 This is not a support forum. For help, please use our forums: https://forums.dolphin-emu.org/

**Comment by pizuz** [comment]
Vulkan SDK 1.1.108.0 is about to be released and the [MoltenVK build](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.0.35) shipped with it will come with the fixes I mentioned.

**Comment by stenzek** [comment]
Switched to 1.1.108.0. If someone could test/confirm this is working I'll go ahead and merge.

**Comment by pizuz** [comment]
I can confirm that the build from this branch works without crashing.

I can also confirm that the memory leak is no longer present.

**Comment by stenzek** [comment]
Thanks for confirming :)

**Pull request merged**
