### PR TITLE
Qt: Minor UI Enhancements

### PR DESCRIPTION
**Pull request by sonic2kk**
A number of changes have been made across the UI, to make it (hopefully) a tad more user friendly. There's a theme of stretching widgets to match their labels 😁

Here's an overall list of the changes:

**MainWindow**
- Change "FullScr" to "Fullscreen"
- Change "ScrShot" to "Screenshot"
- Change "Config" to "Settings"

**GameList**
- Add shortcut hints to context menu
- Fix context menu tag actions not being added to tag_menu
- Add ellipsis to context menu items, similar to the MenuBar items
- Add "Perform Wii System Update" to reflect MenuBar change

**PropertiesDialog**
- Add Sizing Policy to properly stretch dialog window. Now it no longer centers the Game-Specific Settings text when stretched out.
- Stretch Deterministic Dual Core combobox to match its label
- Stretch Stereoscopy depth slider and convergence box to match their labels

**MenuBar**
- Add shortcut hints to menu/submenu items. Only some of the menu had these hints, but now all of them should
- Add ellipsis to menu items appropriately. This would mean items which open additional information windows such as a file selection dialogs, or the likes of the Settings screen
- Move NetPlay items into separate submenu
- Change "Perform Online System Update" to "Perform Online Wii System Update" for more user clarity

**TASInput**
- Separate GameCube and Wii controller windows so that they don't completely overlap

**Settings**
- Change window title from "Configuration" to "Settings"
- Audio: Change boxes to have `QSizePolicy::Expanding, QSizePolicy::Fixed` to stop them filling the entire window. This matches the rest of the Settings UI more consistently
- GameCube: Device Settings comboboxes stretch to match position of their labels (Slot A, Slot B, SP1)
- Wii: Aspect Ratio, System Language comboboxes stretch to match position of their respective labels
- Wii: Fix USB Passthrough ListView displaying incorrectly when resized
- Advanced: Stretch combobox to match its label

**Configuration**
- Stretch Basic box combos to match size of their labels
- Stretch Enhancements box combos to match size of their labels
- Stretch Bitrate box to match size of its label

**Online System Update**
- Rename dialog title to "Confirm Wii System Update"
- Update dialog text to include "Wii", reflecting the theme of these changes

Phew. If there are any other parts of the UI that need changing which I happened to miss, just point them out to me!

### CODE REVIEW

**Comment by MayImilae** [comment]
Please split this up into multiple PRs based on what they affect, instead of having one giant PR like this. Having to review and debate on this many UI elements all at once is going to kill this PR!

**Comment by Techjar** [comment]
Also provide screenshots to make it easier to review the changes.

**Comment by sonic2kk** [comment]
@MayImilae Should all those PRs be submitted at the same time, or just one at a time until each one is reviewed?

@Techjar Once they're split up, I'll provide screenshots comparing the current master with the changes made.

**Comment by Techjar** [comment]
> Once they're split up, I'll provide screenshots comparing the current master with the changes made.

Right, that's what I meant.

**Comment by Techjar** [comment]
Splitting them up by each thing they affect (the bold text in your original description) is probably enough.

**Pull request closed without merging**
