### PR TITLE
Qt/Mapping: Implement indicators

### PR DESCRIPTION
**Pull request by spycrab**
**Outdated**
Stick Indicators
IR Indicators

Implements the fancy controller indicators from Wx, might require some overhauls before it can get merged.

### CODE REVIEW

**Comment by spycrab** [comment]
@MayImilae @JMC47

**Comment by MayImilae** [comment]
Where is the box around the joystick indicators, and the grey markings inside them too? The box indicates the range of the physical joysticks/whatever the user is using, while the grey octagon showed the gamecube joysticks range, which helped tune the radius to help match. It's a nice feature! The GameCube's joystick doesn't use its full range, so to make say, a 360 controller have it's full range translated to range of a gamecube controller, it requires a radius of 70% or so. This was shown by the box with a hexagon thing, and this current setup just gives none of that information at all. It's a definite reduction in functionality. Also note that the nunchuk's octagon was bigger inside of the square, reflecting that the octagon of the nunchuk constrains the joystick range far less than the gamecube controller. It's useful info!

Also the WX joystick boxes not only showed when and how far the hardware joystick was pressed, but also whether or not it was being picked up by the deadzone. Very handy and surprisingly intuitive for Dolphin's WX GUI.

The wii remote pointer box and its lines were also extremely useful for tuning the pointer's center, width, and height to match ones display, which is great for those that want to use a mouse. Also I think just not having a bounding box for so many options is kind of bad, to be honest.

Also this has completely lost the extremely useful indicator that showed when an analog trigger press switched from the gamecube's analog triggers to the digital clicks. That is EXTREMELY useful, since there is no hardware that quite matches the GameCube controller, and that would be sorely missed!

So, I really really want to see some those indicator features make a return! As it is this is a considerable reduction in functionality. :(

-

Also moving the button indicators to the buttons themselves is a pretty significant design change. In theory it makes more sense than separate light up boxes, but there are a lot of ramifications to this change that the older though clunky design handled fine. Like how it works fine across differing operating systems and OS versions, how it worked regardless of operating system themes, and how its simplicity made it color-blind friendly, and even friendly to those with visual disability. Also that indicator style does not work for joysticks, they are always lit up since the deadzone doesn't apply to them, and it's just kind of useful there. 

This new approach, while a lot cleaner, will need to be checked against all of those things, and make sure we're not losing anything in the process.

**Comment by spycrab** [comment]
@MayImilae Don't worry this isn't final in any way.

Things I changed:
* The Qt stick indicator should be as capable as the Wx one right now (you'll have to test it yourself to make sure)
* Added a trigger indicator
* Made the buttons only light up when there's not another indicator present (e.g. trigger indicator)
* Made the buttons not only change color but also bolden the text (should help with accessibility)

**Comment by spycrab** [comment]
@MayImilae 
> The wii remote pointer box and its lines were also extremely useful for tuning the pointer's center, width, and height to match ones display, which is great for those that want to use a mouse. 

I can't get the width, center and height options to do anything *at all* for me. Am I doing something wrong?

**Comment by MayImilae** [comment]
(It occurred to me that with different theme and operating system environments there could be some issues I'm seeing that you aren't so I'm going to include images from now on!)

The trigger indicators don't actually work properly... they just light up, they don't show the analog progression that WX does. That's a key part of how intuitive the trigger indicators are - you push down lightly, you see a little bit increase, and when you reach the threshold it snaps to full analog and a digital press - very intuitive! The threshold indicator mark works though, that's good. 

triggerindicator

Also it is totally impossible to see what the indicators even are until they are filled up with red, that's not ideal.

And to nitpick a bit, the L and R being at the absolute left of the indicators looks kind of tacky, it needs some padding! And a line or separation between the trigger indicators would be nice too.

-----

The joystick indicators are still rather basic compared to WX. Showing the box in addition to the octagon is a definite improvement! And the indicators constrain to the range settings very nicely. However the octagon's range is the same in every joystick indicator, ignoring the hardware variation. I mean, that's the purpose of the octagon after all, a reference to what the hardware range compared to a typical controller. Frankly I think design wise we really should automatically adjust for the hardware variation and bury such advanced controls into an advanced menu or something, but meh, that's well outside the scope of this PR.

Also the joystick indicators don't show the hardware joystick range and the range that Dolphin would use independently. It really helps explain what the range control is doing.

joystickrange

...and this is a nitpick but the black on white on red theme (as well as the outlines for the dots) for the joystick and trigger indicators is a bit too contrasty, imo.

-----

Finally, the button indicators themselves are a lot nicer than last time! The bold as well as red design solves a lot of color blindness issues, imo, since it's still visible even in greyscale (where it appears to go from black to grey, and boldens). I like it! It's much more intuitive this way!

buttonindicators

-----

Ack! I almost forgot! The wii remote pointer and tilt indicators still lack a bounding box. so I'm assuming you just haven't gotten to them yet.

wiimoteindicators

**Comment by MayImilae** [comment]
(Ok this post is going to be rambly. I'm jotting down things as i see them and doing very little editing, this is as good as it gets on an off day ok.)

So As for the Wii Remote Pointer indicator and options... I'm pretty sure the pointer indicator in WX is just hella broken right now. It skitters about wildly on my system. So I went back to 4.0, and the indicator doesn't flicker like it does currently, but also the Center Width and Height controls seem to do nothing there either?

So I went further back. 3.5 and 3.0's indicators also don't show anything different when I change those settings. Hmm.

So I went back to 2.0...

nope




So I'm just going to conclude that the wii remote pointer indicator has never actually shown any changes from those settings! 

-----

Now to see if those settings actually do anything.

Ok, on Dolphin master, the pointer jumps all over the place, just like the indicator shows. So I guess the indicator is reflecting what Dolphin sees correctly?

Now the settings definitely change what's going on though. Let's try 4.0...

Ok, 4.0 is way more stable, but I think my multiple displays are messing with things, so turning those off. Ok, so I have it working sort of well, and um, it doesn't match what the indicator is doing at all? Like, the pointer in game is at the top of the screen, and yet the indicator shows it only half way. Hmm, it seems that way on almost all axis, but not in a consistent manner.

Ooooh I get it. After changing one of the IR setting in WX, I need to click into something else for it to  take effect. That explains a lot.

Ok, here we go! If I set Width and Height to 0, the pointer just doesn't move. If I set Width to 0 and Height to 100 it only moves up and down, and if Width is 100 and Height is 0 it only moves side to side. Now we're getting somewhere.

...and Dolphin crashed. Great. Restarting...

Ok so center seems to move the pointer up and down when it is in what I'll dub side to side mode (Width is 100 and Height is 0). So where the up and down center point of the physical screen relates to the emulated screen changes depending on the center setting. Also for whatever reason 100 seems to be about 60% screen height and everything just goes down from there. No idea what that's about. 

Center does not seem to affect the horizonal center position at all.

Also none of this is reflected in the IR indicator in the menu, so um, yay.

-----

So um, there's some analysis for you spycrab! My conclusion is that the IR indicator is hella broken and always has been, it's just even worse currently. And why aren't their two centering options? There were in 2.0! Is that still in Dolphin's code?

**Comment by JosJuice** [comment]
For the reference, the IR cursor jumping around is because Dolphin detects the mouse cursor position relative to the current window control (e.g. a button or an entire window), at least when you're using Dinput, so it gets very jumpy in a window that has as many buttons as the input config window. This change was made sometime between 4.0-4xxx and 4.0-7xxx if I recall correctly.

**Comment by MayImilae** [comment]
Is this something that can be corrected? All of the jumping about makes the IR cursor indicator pretty useless!

**Comment by spycrab** [comment]
@MayImilae Updated the PR. I hope I addressed all your points!

**Comment by tony971** [comment]
The Christmas colors with grey and Dolphin blue aren't the prettiest palette. Any reason to use them over a matching set?

**Comment by spycrab** [comment]
@tony971 I fail to see where blue is used in this palette.

**Comment by tony971** [comment]
The panes in the OP screenshots. It's used for the highlighted devices and selection box of "relative input".

**Comment by spycrab** [comment]
Erm...that's just the theme I'm using. It has nothing to do with this PR.

**Comment by tony971** [comment]
Welp. Guess that's what I get for commenting on something before testing. Ignore me.

**Comment by MayImilae** [comment]
Alright, we got a lot of reviewing and tweaking done over IRC! The two dots are working correctly now! Trigger indicator is working great, the octogons in the joystick indicators for the gamecube tab are sized nicely, and the deadzone as a circle is nice. We even have bounds for the motion control indicators! So, I think we're good!

**Comment by mbc07** [comment]
I'm late to the party but there's some details in [issue 8673](https://bugs.dolphin-emu.org/issues/8673) regarding the emulated IR cursor behavior...

**Pull request merged**
