### PR TITLE
WX: Replace 'BIOS' with 'IPL' and 'Main Menu' in user-facing strings

### PR DESCRIPTION
**Pull request by leoetlino**
It's not really a BIOS.

### CODE REVIEW

**Comment by ligfx** [comment]
Gonna start the bikeshedding on this and say: how about replacing 'BIOS' with 'Main Menu' in user-visible portions? It matches the wiki, and is probably more well-known than 'IPL'.

**Comment by BhaaLseN** [comment]
Maybe tooltips and descriptions [sc]ould include that, to add some technical detail?

**Comment by MayImilae** [comment]
For reference, the wiki calls the GameCube IPL the "[GameCube's Main Menu](https://wiki.dolphin-emu.org/index.php?title=GameCube_Main_Menu)" because that is the term Nintendo used for it in the GameCube manual. Nintendo still has it online, so you can read the manual for yourself [HERE](http://www.nintendo.com/consumer/downloads/gcn101_manual_english.pdf).

**Comment by JosJuice** [comment]
It would be nice to make it say Main Menu, because IPL isn't recognizable.

**Comment by leoetlino** [comment]
I'll change it to 'GameCube Main Menu', then.

**Pull request merged**
