### PR TITLE
[Android] Implement support for real Wiimotes with the DolphinBar

### PR DESCRIPTION
**Pull request by Sonicadvance1**
This is the only way to get Wiimotes working under Android now.
This, just like the Wii U Gamecube Controller Adapter, completely goes around Android's limitations and talks with the device directly through USBManager.

Couple notes.
Continuous scanning must be enabled otherwise the Wiimotes won't be seen.
The UI doesn't expose support for this yet. One must change the Wiimote source and continuous scanning settings manually.

Testing up to two wiimotes in Taiko No Tatsujin, no reason to believe all four won't work.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3593)

### CODE REVIEW

**Comment by JMC47** [comment]
I have no way to test this, but, does this affect non-Android at all?

**Comment by Sonicadvance1** [comment]
No.

**Comment by JMC47** [comment]
Then +1 from me

**Comment by lioncash** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, line 18 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9isCA-aCRGPETAb5ba:-K9isCA-aCRGPETAb5bb:2134387582) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ae006d3a4e8f4663bfca3a28970c51804aa1d297/Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp#L18)):*
Doesn't look like this is used outside of this source file (unless I've misread anything)

---

*[Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, line 61 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9irwwuNBQvzkY-Mpao:-K9irwwvSlRvFL3Pp5UE:2008912598) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ae006d3a4e8f4663bfca3a28970c51804aa1d297/Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp#L61)):*
ampersands against type

---

*[Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, line 69 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9ireo0G35_EZDSSbnd:-K9ireo0G35_EZDSSbne:-305512373) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ae006d3a4e8f4663bfca3a28970c51804aa1d297/Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp#L69)):*
static_cast

---

*[Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, line 106 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9irbAtmVenGeWX1Yzq:-K9irbAuuUAd-Xnno1Q3:147674978) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ae006d3a4e8f4663bfca3a28970c51804aa1d297/Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp#L106)):*
nullptr

---

*[Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, line 148 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9irJuHHjgC9aRJ5GUb:-K9irJuHHjgC9aRJ5GUc:147674978) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ae006d3a4e8f4663bfca3a28970c51804aa1d297/Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp#L148)):*
nullptr

---

*[Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, line 159 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9irLhFfiuunEYwobzQ:-K9irLhFfiuunEYwobzR:147674978) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ae006d3a4e8f4663bfca3a28970c51804aa1d297/Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp#L159)):*
nullptr

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593)*

**Comment by Sonicadvance1** [comment]
*[Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, line 18 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9isCA-aCRGPETAb5ba:-K9iscWRQQZpSNp0VKBm:715471182) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ae006d3a4e8f4663bfca3a28970c51804aa1d297/Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp#L18)):*
You have misread. This variable isn't set inside of this source file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593)*

**Comment by Sonicadvance1** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, line 61 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9irwwuNBQvzkY-Mpao:-K9itQoWq6smePyZ3-zU:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ae006d3a4e8f4663bfca3a28970c51804aa1d297/Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp#L61)):*
Done.

---

*[Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, line 69 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9ireo0G35_EZDSSbnd:-K9itIFFnqgNCJeBkkaY:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ae006d3a4e8f4663bfca3a28970c51804aa1d297/Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp#L69)):*
Done.

---

*[Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, line 106 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9irbAtmVenGeWX1Yzq:-K9itGUnjIlz4sVTWAwT:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ae006d3a4e8f4663bfca3a28970c51804aa1d297/Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp#L106)):*
Done.

---

*[Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, line 148 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9irJuHHjgC9aRJ5GUb:-K9itGvsvWSQB1q4HiaN:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ae006d3a4e8f4663bfca3a28970c51804aa1d297/Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp#L148)):*
Done.

---

*[Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, line 159 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9irLhFfiuunEYwobzQ:-K9itHHeCsz8Tx-cKanN:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ae006d3a4e8f4663bfca3a28970c51804aa1d297/Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp#L159)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593)*

**Comment by degasus** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9ke3wSo9o90DI3JWSJ:-K9ke3wSo9o90DI3JWSK:-657778840) (no related file):*
> Continuous scanning must be enabled otherwise the Wiimotes won't be seen.
What about just enabling it by default on android?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593)*

**Comment by Sonicadvance1** [comment]
That will be what is done.

**Comment by Sonicadvance1** [comment]
*[Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp, line 18 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9isCA-aCRGPETAb5ba:-K9vS84Z3t1LOWFhMMqs:1977337546) ([raw file](https://github.com/dolphin-emu/dolphin/blob/ae006d3a4e8f4663bfca3a28970c51804aa1d297/Source/Core/Core/HW/WiimoteReal/IOAndroid.cpp#L18)):*
This global reference is going to get cleaned up along with the rest of the places in the source that does similar things in a couple of days.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593)*

**Comment by BhaaLseN** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java, line 23 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9vR2wD-XNH6SX3QwWw:-K9vR2wD-XNH6SX3QwWx:-1618362343) ([raw file](https://github.com/dolphin-emu/dolphin/blob/4a50deb4f5d55065051cc2b235de634154009d08/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java#L23)):*
Any reason not to make those `final` aswell?

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java, line 61 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9vRK3honnNCYdI7f27:-K9vRK3iPrUPskhBvNSD:1653317784) ([raw file](https://github.com/dolphin-emu/dolphin/blob/4a50deb4f5d55065051cc2b235de634154009d08/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java#L61)):*
I'd put braces here, since the inside of the statement is not a single line

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java, line 83 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9vRRYd2zxHwQ5PS0Rb:-K9vRRYeXqthTf8UbmSA:1141267322) ([raw file](https://github.com/dolphin-emu/dolphin/blob/4a50deb4f5d55065051cc2b235de634154009d08/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java#L83)):*
`final`?

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java, line 91 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9vRTEDdrqgfLFPVtQE:-K9vRTEDdrqgfLFPVtQF:-1182412286) ([raw file](https://github.com/dolphin-emu/dolphin/blob/4a50deb4f5d55065051cc2b235de634154009d08/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java#L91)):*
Some space between the pipes?

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java, line 114 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593#-K9vRbPJAoEZM-pYeo7q:-K9vRbPJAoEZM-pYeo7r:158545353) ([raw file](https://github.com/dolphin-emu/dolphin/blob/4a50deb4f5d55065051cc2b235de634154009d08/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/Java_WiimoteAdapter.java#L114)):*
Those two numbers appear multiple times throughout the code...maybe make them named constants too?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593)*

**Comment by BhaaLseN** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3593)*

**Pull request merged**
