### PR TITLE
Both Intel and Radeon Mesa geometry shader bugs are fixed in 11.1.2

### PR DESCRIPTION
**Pull request by Sonicadvance1**
[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3620)

### CODE REVIEW

**Comment by lioncash** [comment]
Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3620)*

**Comment by delroth** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3620)*

**Comment by sheepdestroyer** [comment]
in fact the patch for intel did not make it to final 11.1.2, only the radeon one.
The intel patch is still only in master as of now

**Comment by delroth** [comment]
That's what I thought but I figured HdkR was right :( sorry for not flagging that.

**Comment by sheepdestroyer** [comment]
Mesa 11.2 has been branched 4 days ago and includes the aforementioned fix : https://cgit.freedesktop.org/mesa/mesa/log/?h=11.2

**Comment by JosJuice** [comment]
@sheepdestroyer Please avoid commenting on lots of closed PRs. The issue tracker is a better place for things like this.

**Comment by sheepdestroyer** [comment]
Sorry, it's confusing as pr are not referenced on issue tracker

**Pull request merged**
