### PR TITLE
Remove the old Xlib backend

### PR DESCRIPTION
**Pull request by magcius**
Users have complained about the Xlib backend's poor performance -- this is because we do two round trips every frame to get the pointer's position. With background input, this is unfixable. Thankfully, XInput2 has a bit of a hack to let us know when the pointer moves at all, letting us only query it on frames where the pointer moved. We still do roundtrips on those frames, but hopefully the cursor isn't moving every frame.

Implement this, and then remove the old Xlib input backend. We now require XInput2, but this feature is five years old -- anybody with a modern enough machine to run Dolphin should have it.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4179)

### CODE REVIEW

**Comment by degasus** [comment]
Sounds like a good idea. Every distribution with gcc4.9 should also support xinput2.

---

Reviewed 7 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4179#-:-KQoErCHkLTMd3aVQxgB:b-x0ib3f)*

**Comment by davidbepo** [comment]
i think this commit could have broken hybrid wiimote on linux
i am commenting here because i dont know how to file a dolphin bug

**Comment by leoetlino** [comment]
No, it hasn't, and there's no way it could. You simply need to select the XInput2 input device.

**Comment by davidbepo** [comment]
@leoetlino i dont know if this was the bad commit but i already selected the xinput2 device and hybrid wiimote doesnt work (the wiimote shows as connected but it doesnt do anything) real wiimote works fine

**Comment by davidbepo** [comment]
@leoetlino also the movement of the mouse is correct in the config window so the broken thing must be related to hybrid wiimote itself and not this commit

**Comment by davidbepo** [comment]
does anyone know what could be causing the bug?

**Pull request merged**
