### PR TITLE
AR: invalidate JIT blocks after applying AR codes

### PR DESCRIPTION
**Pull request by FioraAeterna**
totally untested. On JMC47's request

### CODE REVIEW

**Comment by degasus** [comment]
Is there an easy way to only invalidate it if the memory was changed?

**Comment by magumagu** [comment]
We could always add more memory APIs. :)

**Comment by CarlKenner** [comment]
That's excellent. Thank you.

**Comment by FioraAeterna** [comment]
I'll leave this problem up to magumagu since he's going after that code.

**Pull request closed without merging**
