### PR TITLE
JitArm64: Faster block linking.

### PR DESCRIPTION
**Pull request by degasus**
This PR moves the shared assembly within the JIT code, so it's within the 128M range and can be called directly without BR(). Next optimization is to check for downcount on linking if possible, as condition jumps have a smaller range. So it skips the double B() B() combo.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3840)

### CODE REVIEW

**Comment by Helios747** [comment]
Tested on nvidia shield TV, stock 3.1 update. Tests done at 1x IR. I chose a "light" game and a "heavy" game.

Master:

Super Mario Bros Wii: 80 FPS at title screen
ZTP (GC): 35 FPS at title screen

PR:

Mario: 74 FPS at title screen
ZTP (GC): 35 FPS at title screen.


I double checked the NSMBW framerate to be sure, but yeah this makes it slower.

**Comment by degasus** [comment]
I've also done some very fast testing, with the opposite results.
PR - NSMBW Title screen 85 - 90 fps
master - NSMBW Title screen 80 - 82 fps
This was by compiling both builds myself in the same way, so also same settings.

**Comment by brujo5** [comment]
Thanks @degasus this PR speed up many games in my  galaxy S6

**Comment by degasus** [comment]
Hint: This optimization is also missing on the desktop ;)

**Comment by Helios747** [comment]
@brujo5 Are you sure? The SGS6 isn't exactly CPU thread bottlenecked.

**Comment by brujo5** [comment]
I don't know but Zelda twilight Princes is 3fps more faster.
I'm very happy 3fps + are welcome specially in worse areas.

**Comment by phire** [comment]
I've checked the few parts of this PR which touch desktop versions of dolphin. It's perfectly fine for this to be merged without affected the 5.0 release.

<details><summary><i>Previously, brujo5 wrote…</i></summary>
> I don't know but Zelda twilight Princes is 3fps more faster.
> 
> I'm very happy 3fps + are welcome specially in worse areas.</details>


---

Reviewed 4 of 18 files at r1.
Review status: 4 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3840#-:-KHuzISVvhAVh2bvf6T6:1152015502)*

**Comment by degasus** [comment]
@Sonicadvance1 also said LGTM on IRC.

Ready to merge?

**Comment by Helios747** [comment]
SGTM. I'm not sure why my device slowed down but I can't see any other reason than I had a configuration problem... Somehow. This code should be faster for CPU.

**Pull request merged**
