### PR TITLE
[Hotkeys] Added wireframe toggle

### PR DESCRIPTION
**Pull request by Helios747**
User requested it. @MaJoRoesch says some users have asked for it before. Harmless addition.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3586)

### CODE REVIEW

**Comment by JosJuice** [comment]
*[Source/Core/DolphinWX/Frame.cpp, line 1393 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3586#-K9ScfJmQIce6WeJXAHH:-K9ScfJmQIce6WeJXAHI:-842350530) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d198694779ad45f052e6396f1760676d38415933/Source/Core/DolphinWX/Frame.cpp#L1393)):*
The OSD message should be implemented in the same way as other toggles. Here's an example of how to implement it:

https://github.com/dolphin-emu/dolphin/pull/3356/files#diff-787b2e3acf0ac01f4d800a6d7c4327cfR1424
https://github.com/dolphin-emu/dolphin/pull/3356/files#diff-3e2b32720071bf345fd0cee518814102R382

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3586)*

**Comment by lioncash** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/DolphinWX/Frame.cpp, line 1393 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3586#-K9ScfJmQIce6WeJXAHH:-K9SdM-Tt79xx1FGFXkR:-2046514952) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d198694779ad45f052e6396f1760676d38415933/Source/Core/DolphinWX/Frame.cpp#L1393)):*
re: those links

Note to self to kill off the magic number usage with OSDChoice

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3586)*

**Comment by aserna3** [comment]
Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3586)*

**Comment by degasus** [comment]
Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Source/Core/VideoCommon/RenderBase.cpp, line 387 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3586#-K9SkVtHdt4y7Yttas5S:-K9SkVtHdt4y7Yttas5T:-1013040763) ([raw file](https://github.com/dolphin-emu/dolphin/blob/5e2e2272b24ed23f2f7df8fc980e8c2ba6296873/Source/Core/VideoCommon/RenderBase.cpp#L387)):*
Patch looks fine, but I doubt this shall have an OSD entry. It's a very rarely used feature, so I don't see a reason for showing this flag on changing eg the IR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3586)*

**Comment by Helios747** [comment]
I forgot about this branch lol.

I'll rebase this after 5.0

**Comment by RisingFog** [comment]
5.0 has now passed, and this will need a rebase.

**Pull request closed without merging**
