### PR TITLE
Disable some OpenGL 4.5 functions until AMD fixes their trash driver.

### PR DESCRIPTION
**Pull request by Sonicadvance1**
[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3640)

### CODE REVIEW

**Comment by delroth** [comment]
I don't really like this (I think we should fallback to 4.4, not 2.0), but let's fix the breakage for now.

**Comment by tapcio** [comment]
I don't think they (AMD) care, because of today's Vulkan 1.0 "premiere". Vulkan was designed from their Mantle API so I think they will be fully going into it. 
Drivers are available for AMD (Windows only - http://support.amd.com/en-us/kb-articles/Pages/radeon-vulkan-beta.aspx ) and Nvidia (Windows / Linux - https://developer.nvidia.com/vulkan-driver ), Intel driver will be soon available.
Maybe time to start writing Vulkan renderer as it will be supported on mobile devices too in future.

**Comment by MaJoRoesch** [comment]
Note that this error that this fixed also occurred on working GPUs with older drivers that didn't support OpenGL 4.5 yet. It happened to me!

**Comment by delroth** [comment]
@tapcio please keep the off-topic wishful thinking for our forums please.

**Comment by tapcio** [comment]
I checked AMD OpenGL driver (64bit one, atio6axx.dll) for those strings, and there are in the driver binary but with ARB extension (even in old 15.7.1). I think AMD implement those function only with GL_ARB_robustness.

**Pull request merged**
