### PR TITLE
VertexShaderGen: Correct for negative viewport dimensions.

### PR DESCRIPTION
**Pull request by Armada651**
Fixes Jimmie Johnson's Anything with an Engine.

I'm not completely sure yet whether the pixel correction should also be inverted or not.

### CODE REVIEW

**Comment by JMC47** [comment]
@degasus said that it should be before in IRC, and I can confirm it fixes the game.

**Comment by BhaaLseN** [comment]
Is `o.pos.xy` the "height", or is it everything _but_ "height"? If the former, the comment might be wrong (thinking along the lines of "We need _not_ negate the height here [since already negated]"). Then again, I have no idea what this does, so I could just be confused by the wording of the comment :)

**Comment by Armada651** [comment]
@BhaaLseN `o.pos.xy` is both is not the dimensions of the viewport, it's the horizontal and vertical position of the vertex. `" I_PIXELCENTERCORRECTION ".xy` is the width/height of the viewport and either of these could be negative and thus the vertices would need to be flipped along the corresponding axis.

However, since the viewport height is almost always negative we actually inverted the height already in the render backend. Thus we need to flip the vertices vertically only if the height is positive instead of negative. To do that we negate the height before we call `sign`.

**Comment by JMC47** [comment]
Considering that Jimmie Johnson's Anything with an Engine is a generational game, can you review/merge this degasus?  I don't think billions of fans can wait much longer.

**Comment by JMC47** [comment]
@Armada651 quick question: This should be considered a game bug that we weren't handling right, correct?  A game shouldn't be using a positive viewport.

**Comment by Armada651** [comment]
@JMC47 Not really, this is allowed by the console apparently, so we should emulate it. And as you can see, it's pretty trivial to emulate.

**Comment by degasus** [comment]
I'm pretty sure our rasterization is wrong, especially what shall happen if we hit the center of a pixel exactly. AFAIK GPUs tends to a left-lower rule here, and a flipped viewport may change this behavior. But as we're not close to this kind of accuracy, I'm fine with this :D

**Pull request merged**
