### PR TITLE
[WIP] Android: Update Shader Compilation descriptions

### PR DESCRIPTION
**Pull request by Ebola16**
@stenzek @MayImilae 
The old descriptions used the old naming system. Please check my wording to make sure I understand how these options changed in #6443.

Also, I am able to use Skip ubershaders on my Samsung Galaxy Note8. I also have "Compile Shaders Before Starting" checked and I didn't notice any message for compiling shaders. Is that intended?

screenshot_20180326-151407

### CODE REVIEW

**Comment by leoetlino** [comment]
>Also, I am able to use Skip ubershaders on my Samsung Galaxy Note8. I also have "Compile Shaders Before Starting" checked and I didn't notice any message for compiling shaders. Is that intended?

It's likely because the Android UI doesn't handle the "progress dialog" host messages.

**Comment by stenzek** [comment]
Sounds fine to me. And yep, no popup because android hasn't implemented the progress dialog host message.

**Comment by mbc07** [comment]
The description text looks overly long in the "Shader Compilation Mode" item. Couldn't you make it display the description of the chosen mode only and update it accordingly on user change? I've seen a lot of apps using that approach, even some from Google.

E.g. user clicks "Shader Compilation Mode" and chooses "Synchronous", the item description changes to "Synchronous - never use ubershaders, lowest performance impact but stutters during shader compilation". Then user changes its mind, click on "Shader Compilation Mode" and now chooses "Asynchronous (Ubershaders)", the item description then changes to "Asynchronous (Ubershaders) - Use ubershaders while compiling specialized shaders, balances performance and stutter reduction", and so on with the other options...

**Comment by MayImilae** [comment]
Can you make shader compilation a submenu? This is kiiind of ridiculously long. It will also give you the room to use the precise wording of the desktop descriptions (seriously, use it word for word, it was highly debated and turned out very good).

**Comment by Ebola16** [comment]
Created [Android: Handle "progress dialog" host messages](https://bugs.dolphin-emu.org/issues/10971) issue for later.

I like the shader compilation submenu over the spinner idea since spinners aren't used elsewhere in the graphics options. Once #6499 is merged I'll return to this since that PR will be the template for future submenu-related PRs.

**Comment by leoetlino** [comment]
This PR needs a rebase.

**Comment by Ebola16** [comment]
I looked at this further. The current method for loading menu descriptions calls an `int` for the `descriptionID`, which is usually a `R.string.somestring` reference to a string. `%s` doesn't work here for the description. Is there a way to introduce dynamic descriptions to the current setup? I'm trying to avoid creating a new `listpreference` class with a non-int way of referencing the description.

**Comment by Ebola16** [comment]
Radio buttons and ButtonGroups are probably the way to go with this. A new radio button class should be created. It'll pretty much be the same as `SingleChoiceSetting` except it'll have a dynamic summary. Ideally these should be combined into one but I don't know if that's possible.

**Comment by Ebola16** [comment]
Included as part of #7121

**Pull request closed without merging**
