### PR TITLE
Fix lens flares in Mario Kart Wii.

### PR DESCRIPTION
**Pull request by phire**
Cleans up a lot of the efb2tex/efb2ram behavior, might fix other bugs too.

### CODE REVIEW

**Comment by JMC47** [comment]
Fixes the Lenses Flare showing through walls in Mario Kart: Double Dash.

**Comment by degasus** [comment]
LGTM

**Comment by DonelBueno** [comment]
Does this make Lens Flare in Mario Kart Wii work with "EFB Copies to Texture Only" enabled? Or does this fix the crashes in D3D?

**Comment by shuffle2** [comment]
hi.
great branch name.
a+.

**Comment by aserna3** [comment]
a+

**Comment by phire** [comment]
@DonelBueno The crashes were fixed a while back in #3046

This effect can never work in pure efb2tex, as the CPU is reading the depth value out of the copied texture to calculate if the sun is visible or not.

**Pull request merged**
