### PR TITLE
Add builtin graphics mods

### PR DESCRIPTION
**Pull request by iwubcode**
This adds the builtin graphics mods from my dummy repo:

* Bloom Removal
* Bloom at Native Resolution
* HUD removal

This renames a few games that were spelled or titled incorrectly when compared with their official boxart name.  And this adds Wii Play / Skwyard Sword to the list of games that support bloom correction.  This also adds Monster Hunter Tri support in addition to the demo disc that was already present.

I also have a DOF at Native Resolution graphics mod for Skyward Sword but not sure how crazy we should be with game mods in the repo.  Open to thoughts.

### CODE REVIEW

**Comment by JMC47** [comment]
Tested a few of these and they seem to work.

**Comment by JMC47** [comment]
Another name adjustment - Apparently the Mario Striker's Wii game does not have the super - they dropped it.  So it should be Mario Strikers Charged.

**Comment by iwubcode** [comment]
@JMC47  - just checked my case. Wow you're right!  All this time I had it wrong..

**Review by Pokechu22 — APPROVED** [review]
Untested (beyond the testing I did with the main graphics mod PR), but looks good to me.

**Pull request merged**
