### PR TITLE
[Android] Fix crash when we don't have access to a folder.

### PR DESCRIPTION
**Pull request by Sonicadvance1**
[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3596)

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
sigmabeta has some code to fix this coming up.

**Comment by degasus** [comment]
This crash now happens on Android 6 when trying to access /storage/sdcard
@sigmabeta Is your code done?

**Comment by sigmabeta** [comment]
It won't be for a while as I'm on holiday for a week. The fix is going to be the same, so I'm OK with just merging this instead.

**Comment by degasus** [comment]
Patch LGTM

**Comment by degasus** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3596)*

**Pull request merged**
