### PR TITLE
Game INI - Fix flickering cutscenes in Castlevania - The Adventure ReBirth

### PR DESCRIPTION
**Pull request by CharlesCorrin**
According to the wiki:
https://wiki.dolphin-emu.org/index.php?title=Castlevania:_The_Adventure_ReBirth

Disabling "Store EFB Copies to Texture Only" in the INI file (WD9) will fix the flickering cutscene problem.

I also tidied some of my previous sloppiness. :3 Apologies.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4045)

### CODE REVIEW

**Comment by JosJuice** [comment]
The result of the commit looks good, but right now there is a merge conflict with your previous commit. You need to base this PR's commit on the most recent version of master, not an older one.

**Comment by CharlesCorrin** [comment]
Working on it... I think. Two commits, though. Not looking good. :(

**Comment by JosJuice** [comment]
That does get rid of the conflict, but it's the wrong approach. You need to rebase.

**Comment by CharlesCorrin** [comment]
I can't find the option to rebase. Safe to say I'm doing poorly. I've tried though, I suppose. :S Sorry for being such a bother.

**Comment by JMC47** [comment]
You're doing better than me when I first started using git.  We'll be happy to help you, especially on IRC where we can answer your questions live :)

**Comment by JosJuice** [comment]
> I can't find the option to rebase. Safe to say I'm doing poorly. I've tried though, I suppose. :S Sorry for being such a bother.

If you're doing it on GitHub, it's not strange that you can't find an option for it, because there is none. A proper git client is needed for most contributions to Dolphin.

**Comment by CharlesCorrin** [comment]
I give my thanks for everyone's assistance. Unfortunately, I don't have any more time to spend on this. I tried the git client and only became frustrated. It doesn't seem worth it when I only have one edit to make. It would have been much faster if I had just deleted and re-submitted like I did last time.

So, thanks again. It's all on me that this was so messed up and I'm sorry for that. I'm the one who can't understand any of this and doesn't have time to do any more research when I can't understand a word of what I'm trying to research. :|

**Pull request closed without merging**
