### PR TITLE
JitArm64: dcbx loop detection for improved performance when invalidating large memory regions

### PR DESCRIPTION
**Pull request by JosJuice**
Follow-up to PR #10007.

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
In the commit message of the last commit you say `bits 5-10`, but I think it's only `bits 5-9` that are actually relevant here.

x64 changes look reasonable to me, can't say much about the ARM code...

**Comment by JosJuice** [comment]
I meant 5 inclusive, 10 exclusive. I'm not sure if that's really clear from how I wrote it, though.

**Comment by AdmiralCurtiss** [comment]
Yeah that's not clear, maybe write `[5-10[` or `[5-10)` then.

**Comment by JosJuice** [comment]
Changed it to 5-9.

**Review by leoetlino — APPROVED** [review]

**Pull request merged**
