### PR TITLE
Fix 8 and 16 bit writes in codehandler

### PR DESCRIPTION
**Pull request by gamemasterplc**
The codes would both overwrite where it should and 16400 bytes after where it should. The bug was caused by a usage of an incorrect register. A test case is below. It should do absolutely nothing when enabled.

$16 Bit Writes Test Case (GZLE01)
0234E4AA 0000008F

### CODE REVIEW

**Comment by JMC47** [comment]
@dolphin-emu-bot rebuild

Do you know of any recent issues that were caused by this?

**Comment by gamemasterplc** [comment]
not as far as I know in public codes. I do have a in-development code that would have noticeable glitches caused by this

**Comment by leoetlino** [comment]
Was there also a source code change?

**Comment by gamemasterplc** [comment]
change all instances of r20 after line 107 to r21

**Pull request merged**
