### PR TITLE
Shadergen: Use real_ocol0 workaround for shader logic ops

### PR DESCRIPTION
**Pull request by JosJuice**
Previously we were using this workaround when using framebuffer fetch to emulate dual source blending, but it seems like we also need to use it when using framebuffer fetch to emulate logic ops, otherwise some Adreno devices get a crash when compiling OpenGL ES ubershaders.

Using the workaround in specialized shaders doesn't seem to be necessary, but I've made the same change there for consistency.

This gets us closer to fixing https://bugs.dolphin-emu.org/issues/12791 but doesn't actually fix it.

### CODE REVIEW

**Comment by JosJuice** [comment]
Doesn't actually seem to fix the issue. Will have to investigate further.

**Comment by JosJuice** [comment]
It seems like there are two different problems which are causing the shader compiler to crash. The first one is fixed by this PR. The second one can be fixed by removing all uses of `fb_value` in the `if (logic_op_enable)` part of the ubershader, but this makes it impossible to emulate logic ops in the ubershader. Since I don't see any way forward regarding this second problem, I'm giving up trying to find a workaround for it.

@OatmealDome Do you think it would be worth merging this even though it only fixes one out of two parts of the issue? My changes in this PR don't make the code any more complicated in my opinion.

**Review by OatmealDome — CHANGES_REQUESTED** [review]
Shaders fail to compile on my M1 machine. Here's a log for a specialized shader: https://pastebin.com/qd1TtZGk

**Comment by JosJuice** [comment]
The MoltenVK code was indeed broken. Could you retest?

**Review by OatmealDome — APPROVED** [review]
Works for me and the code looks OK.

**Comment by brujo5** [comment]
Driver v502 safe
Drivers affected started from v530, v604, v611, v615
Aldo vulkan failed to submit command Buffer

Screenshot_20220301-113431_Dolphin Emulator
Screenshot_20220301-113304_Dolphin Emulator

**Comment by OatmealDome** [comment]
@brujo5 Could you send the ``bad_p_OGL_0.txt`` file inside the ``Dump`` folder if possible? I'm not sure how feasible this is considering the recent SAF changes, but if you're able to get the file that would be great.

**Comment by brujo5** [comment]
@OatmealDome 

Here Is https://www77.zippyshare.com/v/T4CxzDVk/file.html

**Comment by JMC47** [comment]
@OatmealDome everyone can copy files out, it's just that some users cannot copy files in.

**Comment by brujo5** [comment]
Turnip mesa lto drivers with vulkan v1.2.204 is safe but a bit slow compared to blow driver because shader cashing not suported by now maybe they add with vulkan 1.3 update.

**Comment by 71knight** [comment]
Vulkan hybrid ubershaders have corruption on Android 11.  Transparent pieces of after images can be seen on screen.  Opengl crashes when attempting to use hybrid Ubershaders.  My phone is snapdragon 855+ adreno 640.

**Comment by JosJuice** [comment]
And you bisected it to this specific commit?

**Pull request merged**
