### PR TITLE
Crusade against kilobyte, megabyte, and gigabyte

### PR DESCRIPTION
**Pull request by Minty-Meeo**
Where appropriate, replace kilobyte (KB) with kibibyte (KiB), megabyte (MB) with mebibyte (MiB), and gigabyte (GB) with gibibyte (GiB).

### CODE REVIEW

**Comment by Minty-Meeo** [comment]
This is sort of a silly PR but I was wondering if anybody else thought this was necessary to do.

If this PR is taken seriously, I'd like someone more qualified to double check the following changes:
Core/Common/CompatPatches.cpp : line 201
 - I'm unqualified to say
Core/Common/LinearDiskCache.h : line 43
 - I'm unqualified to say
Core/Core/PowerPC/Jit64/Jit.cpp : line 144, 145, 147
 - I'm unqualified to say
Core/Core/PowerPC/MMU.h : line 204
 - Is not 218 KB nor 128 KiB, but 32KiB??
Core/VideoBackends/D3D12/DX12Texture.cpp : line 209
 - 99% sure this is intended to be MiB (see line 213), but I thought I'd ask.
Core/VideoBackends/OGL/OGLVertexManager.cpp : line 64, 66
 - I cannot decipher what this is trying to say or do.  65KB sounds weirdly specific enough that I think it really means kilobytes.  I cannot find the values "1MB" or "32MB" in this function.  On my PC, GL_MAX_TEXTURE_BUFFER_SIZE makes max_buffer_size set to 128MiB.  TEXEL_STREAM_BUFFER_SIZE is 16MiB.
Core/VideoBackends/Vulkan/Constants.h : line 86
 - Same as DX12Texture.cpp, see line 90.
Core/VideoBackends/Vulkan/VKVertexManager.cpp : line 87
 - Similar confusion as to OGLVertexManager, I have no clue what is going on here.
Core/VideoCommon/TMEM.cpp : line 49
 - Yeah it's hardware so it's pretty safe to assume, but I still am unqualified to say.
Core/VideoCommon/VertexManagerBase.h : line 89
 - DAMN THESE CONSTANTS, I JUST DON'T GET THEM!

**Comment by MayImilae** [comment]
Thank you.

**Comment by lioncash** [comment]
the .po files can be excluded from the PR since these are automatically synchronized from Transifex

**Comment by JosJuice** [comment]
I don't know about OGLVertexManager.cpp, but the rest LGTM.

About MMU.h: The number of entries is 32768, but each entry is 4 bytes, so in total it's 128 KiB.

**Comment by Tilka** [comment]
The "65 KB" refers to 65536, i.e. 64 KiB.

**Pull request closed without merging**
