### PR TITLE
Reduce usage of ppcState global.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
I stopped before I got to the JIT because that was looking like it needed a bit more refactoring and this was already getting gigantic...

Right now `system.GetPPCState()` is just a reference to the `ppcState` global, but I'm aiming to completely eliminate that and to have it actually just have a `PowerPCState` instance in `System` instead.

Every commit should compile as-is, which may be useful for bisecting in case I made an error somewhere.

### CODE REVIEW

**Comment by delroth** [comment]
Why the intermediate PowerPCManager class? Couldn't we just have system.GetPPCState() returning a PowerPCState instance instead?

**Comment by AdmiralCurtiss** [comment]
Yes, I suppose so, I was just following the way I have refactored the other global state files so far where at the end everything of a given file ended up in a single class. But given the way `ppcState` is used maybe this is indeed not ideal here and it would be better to just have the `PowerPCState` struct returned directly from `System`.

**Comment by AdmiralCurtiss** [comment]
Like this, I assume?

**Review by lioncash — COMMENTED** [review]
Just two small nits

**Pull request merged**
