### PR TITLE
VideoCommon: Fix ubershaders on MoltenVK Intel

### PR DESCRIPTION
**Pull request by tellowkrinkle**
Intel's Metal driver seems to have issues with dynamic sampler indexing

Also includes a small performance fix for Intel on MoltenVK

### CODE REVIEW

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by MayImilae** [comment]
What happens on an Intel Mac if this issue is encountered?

**Comment by OatmealDome** [comment]
I generally find that the GPU driver crashes, the system becomes temporarily unresponsive, and Dolphin locks up whenever you try to use Ubershaders. (MBP 16" 2019, Intel UHD Graphics 630)

**Comment by OatmealDome** [comment]
@tellowkrinkle Is the second commit related to this PR? Seems to just be a performance fix

**Comment by tellowkrinkle** [comment]
Only as related as it's also targeting Ubershaders on Metal+Intel

Should I move it to a separate PR?

**Comment by OatmealDome** [comment]
Eh, if it's Intel and Ubershaders, good enough for me.

**Review by OatmealDome — APPROVED** [review]

**Pull request merged**
