### PR TITLE
Add more languages, and remove Hebrew because it's very incomplete

### PR DESCRIPTION
**Pull request by JosJuice**
For https://bugs.dolphin-emu.org/issues/9556

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3857)

### CODE REVIEW

**Comment by JosJuice** [comment]
I can't get Asturian, Galician and Welsh to work, apparently because Windows doesn't support them. Can someone else get them to work, possibly on another OS? Other than that, everything seems to be working.

The buildbot will need to be cleaned if we want to completely get rid of Hebrew, but the file is just one kilobyte and doesn't affect anything negatively, so it's not important.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by shellashock** [comment]
FYI, I tried getting those three languages to work on my Windows 10 Home (x64) with the appropriate language packs installed from the "Region and language" tab; but I am also unable to get it to launch with the languages. This only occurs for Asturian, Galician, and Welsh.

**Comment by RisingFog** [comment]
@dolphin-emu-bot rebuild

**Comment by delroth** [comment]
Ignore the OS X build failing, it's likely some weird issue caused by encoding.

**Comment by JosJuice** [comment]
Apparently wxWidgets doesn't have "winlang"s defined for Asturian, Galician and Welsh, so I don't think it's going to work on Windows regardless of what the user has installed: https://github.com/dolphin-emu/dolphin/blob/3ff56aa192f952cb6ad2e9c662d4a368efd21e6f/Externals/wxWidgets3/src/common/languageinfo.cpp#L550

It's not any better in the latest git version of wxWidgets: https://github.com/wxWidgets/wxWidgets/blob/d96a25be1230b91f3431bfc3b85b4e1f55bf62e6/src/common/languageinfo.cpp#L556

**Comment by JosJuice** [comment]
If those three languages don't work on any OSes, I'll remove them from this PR. Otherwise, I suggest that we merge this PR and leave the Windows issue for a potential future PR without it being a 5.0 blocker. I don't want to be messing too much with wxWidgets this close to release, and we shouldn't delay the release because of a few incomplete translations that weren't in older versions of Dolphin.

**Comment by leoetlino** [comment]
Based on the diff, here's a list of which locales work and which don't, on an up-to-date Debian sid with the locales-all package installed:

ast: broken (1) (2) (3)
cy: broken (1) (2) (3)
da_DK: working
gl: working, but with (2)
hr: working, but with (2)
ms_MY: working
ro_RO: working

(1) Dolphin error: "The selected language is not supported by your system. Falling back to system default."
(2) Dolphin error: "Cannot set locale to language "Language name"."
(3) Dolphin error: "locale 'locale_name' cannot be set."

---

Also, it seems to leave behind some files that are untracked in the repo:
../Languages/po/ast.po
../Languages/po/cy.po
and so on for every language that was added.

**Comment by JosJuice** [comment]
Ugh. Sounds like we're better off dropping the three problematic languages for now, then... Thank you for testing.

How do files like Languages/po/ast.po manage to get untracked? They're explicitly added by this PR.

**Comment by leoetlino** [comment]
Oops, I just looked again and the language files were in fact *not* untracked. Rather, they appear as modified files with changes that can be staged, like this:

```
On branch update-language-list
Changes not staged for commit:
[...]
	modified:   ../Languages/po/ast.po
	modified:   ../Languages/po/cy.po
	modified:   ../Languages/po/da_DK.po
	modified:   ../Languages/po/gl.po
	modified:   ../Languages/po/hr.po
	modified:   ../Languages/po/ms_MY.po
	modified:   ../Languages/po/ro_RO.po
```

**Comment by JosJuice** [comment]
That would probably be because the build process is changing the files somehow. I just downloaded the files directly from Transifex's website without doing anything extra to them afterwards, so this doesn't sound too surprising. I think me running `make translations` (and `cmake` first?) before committing would help, but I don't know how that would work on Windows. I wonder why it would be needed, though... This is my first time dealing directly with language files, so it's not all clear to me.

**Comment by JosJuice** [comment]
Removed Asturian, Galician and Welsh from this PR. Maybe we can try again with them at some point in time after 5.0.

**Comment by JosJuice** [comment]
@leoetlino Do the files only get modified the first time you build Dolphin after applying this PR, or do they get modified in different ways each time you build? If it's the former, could you upload the modified files, either as a commit or as plain files somewhere? I'm hoping that including those modified files in the PR will fix the problem, but I can't get them on Windows as far as I know.

**Comment by leoetlino** [comment]
They are only modified the first time after switching to this PR branch. (Tested that by committing the changes, then rebuilding and noticing there's no more change)

Here's a patch for the files: https://dolphin.leolam.fr/language.patch


As you can see, most differences seem to be new lines and some lines are being reordered. I have no idea why it's making these changes either :/

```
+"Language-Team: Asturian (http://www.transifex.com/delroth/dolphin-emu/"
+"language/ast/)\n"
+"Language: ast\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
-"Language: ast\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
 
 #: Source/Core/DolphinWX/AboutDolphin.cpp:37
@@ -51,7 +52,9 @@ msgstr "! NOT"
 msgid ""
 "\"%s\" does not exist.\n"
 " Create a new 16MB Memcard?"
-msgstr "\"%s\" nun esiste.\n¿Crear una memoria de 16M nueva?"
+msgstr ""
+"\"%s\" nun esiste.\n"
+"¿Crear una memoria de 16M nueva?"
```

**Comment by JosJuice** [comment]
Thanks. I'll have to look into things more so I know how to handle the problem if I'm going to add more languages in future PRs, but this will help for now. Could you test that the new version of this PR works as intended?

**Comment by leoetlino** [comment]
There's no change to the language files anymore. :)

**Pull request merged**
