### PR TITLE
GameINI: Fix Transformers: Dark of the Moon hang on opening logos

### PR DESCRIPTION
**Pull request by AGuy27**
Fixes hang on opening logos by turning off dual core. This game is also included in Transformers: Ultimate Battle Edition, where the same issue occurs, so dual core is disabled there too.

### CODE REVIEW

**Comment by JMC47** [comment]
@dolphin-emu-bot rebuild

**Comment by JMC47** [comment]
Can you please add a newline to the bottom of these INIs.  Once that's done I can merge this.

**Comment by JosJuice** [comment]
There is already a newline at the bottom of each INI file.

**Comment by JMC47** [comment]
My bad.

**Pull request merged**
