### PR TITLE
Real Wiimote: Don't delay speaker data.

### PR DESCRIPTION
**Pull request by degasus**

### CODE REVIEW

**Comment by JMC47** [comment]
This allows Wiimote audio to function correctly on -TR wiimotes.

Standard Wiimotes' audio is still broken.

**Comment by degasus** [comment]
@jloehr review please ;)

**Comment by jloehr** [comment]
I have no clue why the delay was implemented in the first place. And i was not able to retrieve the answer from the git history.

So as long as there is no regression, it looks good to me.

**Comment by psennermann** [comment]
For curiosity, when you say "this allows Wiimote audio to function correctly", exactly what do you mean? (I tested with the previous 4.0-8329 and Wiimote audio seemed  good to me...)

**Comment by Mullin** [comment]
Why standard Wiimote still broken ? Bluetooth latency ?

**Comment by JMC47** [comment]
This allows it to be much more stable and have less latency.  Things are less likely to break on weaker bluetooths.

**Comment by Mullin** [comment]
@JMC47 Ok just tested on my standard Wiimote, it's a little better into Super Mario Galaxy but the sound still choppy. Tested with my intel bluetooth card under Windows 10.

**Pull request merged**
