### PR TITLE
Add style chooser in settings, refactor user style code

### PR DESCRIPTION
**Pull request by ewancg**
image
image
image
image

User style combo box is invisible when user styles are not in use.

### CODE REVIEW

**Comment by mbc07** [comment]
If we go that route and implement a dark/light style toggle, I think it would be more sensible to get rid of the separate User Style combo box and just merge both into this new "Style" combo box. For example, "System", "Light" and "Dark" would always be there (maybe add a "built-in" or similar indicator to the default light/dark styles), followed by any custom user style the end-user might have.

User doesn't have any custom style? "Style" combo box would display only "System", "Light" and "Dark". User has installed a custom installer named "foo" and another named "bar", the "Style" combo box would now display "System", "Light", "Dark", "foo" and "bar", and so on...

**Comment by mbc07** [comment]
@dolphin-emu-bot rebuild

**Comment by ewancg** [comment]
Left my comments on merging the combo boxes in the Discord. Currently considering making the Style combobox act as a QStyle selector on Linux, and add explicit light/dark support for macOS (looks very possible at a glance)

Just to get it to pass CI runs, the following has to be done:
- Fix lint errors
- Add LoadLightStyle as a ref capture in LoadDarkStyle (maybe only if not Windows? errors on unused vars, maybe captures too)

Someone else can do this between now and later this afternoon, or I can do it then

**Comment by mbc07** [comment]
@dolphin-emu-bot rebuild

**Comment by mbc07** [comment]
@dolphin-emu-bot rebuild

**Comment by t895** [comment]
@dolphin-emu-bot rebuild

**Comment by AdmiralCurtiss** [comment]
Closing this because #12272 was merged.

**Pull request closed without merging**
