### PR TITLE
Core/Memmap: Memory mapping logic fixes.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
This fixes two potential (if unlikely to be relevant in practice) bugs:

- Remember which regions are mapped instead of re-checking via the flags each time. This fixes a potential issue where a memory region would not be unmapped when booting in Wii mode and then switching to GC mode by eg. using the Disc channel and a GC disc. (first commit)
- We didn't check which regions are active in `UpdateLogicalMemory()`, leading to an odd BAT config potentially attempting to map memory regions that haven't been allocated. (second commit)

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
Oh, I also removed the branch for 32 bit builds, since I don't think we can build on those anymore anyway. I can readd if that's not the case.

**Comment by JosJuice** [comment]
Dolphin still is supposed to build and run correctly on 32-bit systems. (32-bit performance isn't worth caring about, though.)

**Comment by AdmiralCurtiss** [comment]
Fair enough then!

**Comment by JMC47** [comment]
Is this good to go then?

**Review by leoetlino — APPROVED** [review]

**Pull request merged**
