### PR TITLE
[WIP] OpenSSL logger

### PR DESCRIPTION
**Pull request by sepalani**
This PR is based on:
- https://github.com/dolphin-emu/dolphin/pull/6075
- https://github.com/dolphin-emu/dolphin/pull/6176

It adds another logger that HLE hooks with OpenSSL functions to log SSL traffic. This method should work with any other functions as long as we know the parameters. It has to be enabled with the config's option "OpenSSLDumpPCAP".

I tested it with a small homebrew and still is WIP as it needs to be tested on other games. It also requires reverse engineering skills to find these functions and add them to the symbol map in order to use HLE hooks. I might provide a OpenSSL signature database file soon if it's reliable.

I still have to figure out the SSL structure used if I want to retrieve the socket fd that's used.

**DISCLAIMER:** Keep in mind that logging SSL traffic will most likely log sensitive information. That's why you should be careful if you plan to share these network dumps.

Need to be tested on:
- [ ] Amazon Instant Video
- [ ] Crunchyroll
- [ ] Hulu PLUS
- [ ] Netflix
- [ ] Youtube (?) *does it still work if we bypass the error code 20110?*
- [ ] Dragon Quest X (?) *does it use openssl.rso?*

### CODE REVIEW

**Comment by JMC47** [comment]
I'm almost certain that Dragon Quest X doesn't use the standard OpenSSL stuff.  Someone else would have to confirm, though.

**Comment by sepalani** [comment]
@JMC47, I haven't completed the offline mode but so far, I haven't seen any SSL traffic beside Nintendo servers. I've also seen the game server IP in plain text but I got kicked soon after that for not using a Japanese VPN yet.

Anyway, if said encryption and decryption is found, I can still add another hook to log its content. I'm also convinced that you're probably right since I can't find any Japanese text in the pcap file, for the moment.

**Comment by JMC47** [comment]
Most of the stuff that needed to be tested here is now shut down or shutting down.  Is there still interest in finishing this and getting it merged?

**Comment by sepalani** [comment]
The PCAP part is still interesting to have since it's a better way to dump the network traffic than raw binary files. Regarding the OpenSSL hook I doubt that it's still worth keeping around as you said. I'll probably rebase those PRs as soon as possible.

**Comment by sepalani** [comment]
Closing this as most PCAP/SSL features were merged and I don't think there is a game/project benefiting this feature anymore.

**Pull request closed without merging**
