### PR TITLE
MainAndroid: Fix size logging

### PR DESCRIPTION
**Pull request by JosJuice**
Untested.

### CODE REVIEW

**Comment by degasus** [comment]
code LGTM

**Comment by JosJuice** [comment]
Rebased to fix the merge conflict. PR 3320 removed the commented-out broken code, so now this PR re-adds the code in addition to fixing it.

**Comment by BhaaLseN** [comment]
If the "bug" was the fact that it didn't log the actual size, then LGTM.

**Comment by JosJuice** [comment]
The reason that it was commented out was that it used `"%lu"` instead of `"%" PRIu64`.

**Pull request merged**
