### PR TITLE
[WIP] HW: Begin work on fixing GBA linking

### PR DESCRIPTION
**Pull request by endrift**
Early WIP of my cleanup work for mGBA linking. Will push more stuff as time goes on, but testing before I'm done is probably a good idea. Requires mGBA on the [feature/sio-dolphin](https://github.com/mgba-emu/mgba/tree/feature/sio-dolphin) branch to work.

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3022)

### CODE REVIEW

**Comment by shuffle2** [comment]
Nice that you're interested! I think investigating using shared memory would be worth your time...

**Comment by autofire372** [comment]
Is it me, or is FifoCI crying wolf a little too often?

**Comment by waddlesplash** [comment]
Nope, not just you. That exact failure list is pretty common now...

**Comment by phire** [comment]
The directx version of FifoCi got broken when we updated to Visual Studio 2015, so it marked a whole lot of releases as "Everything failed".

This should go away as people base their PRs on more recent commits in master that are not in the broken period.

**Comment by JMC47** [comment]
Ping.  Can I be provided with a build for mGBA because I'm dumb and lazy.

**Comment by vgturtle127** [comment]
@JMC47 :laughing: 

Does this require a custom build of both mGBA and Dolphin in order to work, and do we have to compile it ourselves, or will it be available in the buildbot?

**Comment by JMC47** [comment]
I can build Dolphin, but, I haven't setup to build mGBA.  Also, Dolphin hosts all PR builds.

https://dl.dolphin-emu.org/prs/

**Comment by endrift** [comment]
WIP mGBA build is here: https://s3.amazonaws.com/mgba/sio-dolphin-2015-09-23-win32-d5ab752d18936e1320d43dcd58d2553bc479cc42.7z (this revision: https://github.com/mgba-emu/mgba/tree/d5ab752d18936e1320d43dcd58d2553bc479cc42)

**Comment by JMC47** [comment]
Bugs:

Slow - It's really, really, really, really slow.  Never can reach full speed even with a GBA selected at all.
Controller lock - on games that use a GameCube controller alongside a GBA, if you have a GBA set to any port (even without mGBA connected) controller input will be ignored until you set the GBA to NONE and then set it back to normal.  The game then proceeds correctly.

So far working:

Four Swords Adventures
Mega Man X: Command Mission

Confirmed to not work:

Pokemon Colosseum Bonus Disc (corrupt savedata + locks up Dolphin)

**Comment by vgturtle127** [comment]
Huh, it seems to work pretty well actually. Let me see if I can do some testing, but so far it seems at least a step in the right direction.

**Comment by degasus** [comment]
@endrift Is there an update for this PR?

**Comment by endrift** [comment]
Haven't been working on it lately

**Pull request closed without merging**
