### PR TITLE
Replace the XPM desktop icon with an SVG

### PR DESCRIPTION
**Pull request by jcowgill**
This PR installs an SVG icon to use as the main icon for dolphin in Linux desktop environments (through the .desktop file) and removes the currently used XPM icon. I've also added a 48x48 PNG for any desktops which don't support SVG icons.

This has been the recommended way to ship application icons since forever according to the Icon Theme Spec:
https://www.freedesktop.org/wiki/Specifications/icon-theme-spec/

This is also a prerequisite for dolphin appearing in the GNOME Software Centre which does not support XPM icons.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3653)

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Ping @MaJoRoesch for the SVG, is this our original one?

**Comment by jcowgill** [comment]
I got it from here: https://commons.wikimedia.org/wiki/File:Dolphin-logo.svg

**Comment by BhaaLseN** [comment]
That was my first guess, but I don't know if thats the actual authoratative copy made by us.

**Comment by MaJoRoesch** [comment]
I uploaded it, so yes, that is ours!

To be clear, Windows (.ico) and OS X (.icns) aren't affected by this, right?

**Comment by BhaaLseN** [comment]
Thanks for confirming. And no, they aren't changed by this PR, only the XPM is removed and replaced by the SVG (and a 48x48 PNG) on Linux.

**Comment by linkmauve** [comment]
Hi, I cleaned up the SVG logo long ago, to make the code more readable and remove the crap successive editors added, you can find it here: https://linkmauve.fr/files/dolphin.svg

I’ll update the version on Wikipedia shortly.

**Comment by jcowgill** [comment]
@linkmauve Looks good. I've updated the PR to use the cleaned up logo.

**Comment by linkmauve** [comment]
@dolphin-emu-bot rebuild

**Comment by linkmauve** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3653)*

**Pull request merged**
