### PR TITLE
CMake: don't look for shared Google Test

### PR DESCRIPTION
**Pull request by ligfx**
Google Test [recommends against using a pre-compiled system copy](https://github.com/google/googletest/blob/master/googletest/docs/FAQ.md#why-is-it-not-recommended-to-install-a-pre-compiled-copy-of-google-test-for-example-into-usrlocal) and Debian and Ubuntu no longer distribute compiled packages.

This removes an unhelpful line from the CMake log: "Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)."

### CODE REVIEW

**Comment by ligfx** [comment]
@Orphis

**Comment by Orphis** [comment]
Can you fix their CMake file to propagate the include directories with the target too? Otherwise this is good.

**Comment by ligfx** [comment]
Do we want to start modifying their CMake stuff? I could add the include directories to the target inside Dolphin's CMakeLists.txt, what do you think?

**Comment by Orphis** [comment]
I think it's fine to modify it, gtest or gmock are one file each to compile. We could rewrite it in minutes.

**Comment by ligfx** [comment]
Looks like gtest already propagates include directories 🤣

**Pull request merged**
