### PR TITLE
Android TV: Allow the app to be launched from an Android TV launcher.

### PR DESCRIPTION
**Pull request by sigmabeta**
Pending a nice looking Android TV banner. Right now it just has the icon and then "Dolphin <ABI>" next to it.

Either way, this should let the app be launched without having to dig into system options.

### CODE REVIEW

**Comment by sigmabeta** [comment]
Looks p. good

img_20150603_192610

**Comment by Sonicadvance1** [comment]
I like how all the other emulators are considered games while Dolphin is under apps.

**Comment by sigmabeta** [comment]
That's because we're serious business. 

...for serious though,  I could fix that.

**Comment by Pringo** [comment]
Well technically Dolphin in and of itself isn't a game. It could be argued that it makes more sense to call it one for the purposes of app categorization though.

**Pull request merged**
