### PR TITLE
MemcardManager: Remove explicit delete and new

### PR DESCRIPTION
**Pull request by lioncash**
Also gets rid of pointer casting.

### CODE REVIEW

**Comment by phire** [comment]
I think I would prefer unique pointers instead of those fixed sized vectors.

**Comment by lioncash** [comment]
I would not. There is no generic advantage to use one over the other.  I'd rather use sequence containers for sequences, and unique_ptr's for storing objects, as they are primarily intended to (with the exception being storing data that's passed into a C API).

**Comment by phire** [comment]
Yes there is, std::vector does a whole lot of extra stuff that isn't really needed in this use case, like bounds checking and dynamic re-sizing of the array.

See the generated code: https://goo.gl/xzgdCY

While most of those things get optimized out by the compiler in this example, there are still one or two weird things, like the vector example calling memset. 

If you want to create a variable sized array that gets automatically deleted at the end of the scope, unique_ptr better describes what you want.

**Comment by lioncash** [comment]
Well, you literally described one of the reasons I used vector (bounds checking, at least with the second one). memset is not an issue in the first one, it did that anyway, and most certainly nothing to care about in the second one. Sorry, but I still disagree with using a unique_ptr for that purpose (explicitly calling get in a non-pointer-based/non-legacy API).

Just so you know though, your examples you provided have undefined behavior in them (which are unrelated)

**Comment by phire** [comment]
Oh, if you want the bounds checking then vector is better than unquie_ptr.

But I feel like there is a gap in the standard library and a vector that can only have it's size set during construction is needed, throwing an assert if there is an out of bounds access.

**Pull request merged**
