### PR TITLE
DolphinQt/HacksWidget: Convert accuracy slider to ConfigSlider

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
See https://github.com/dolphin-emu/dolphin/pull/13234#issuecomment-2561573588

We have to extend the ConfigSlider class a little bit for this use case, but it's pretty straightforward.

Less code and makes it work with the per-game config system. Seems like the obvious way to go to me?

### CODE REVIEW

**Comment by TryTwo** [comment]
Thanks! This is all I needed, I just couldn't think of how to code it well.

**Comment by TryTwo** [comment]
I did a quick test and it works. Properly enables/disables. Works with both game and normal gfx windows. Correct values are written and all that. 

Only note I see about the code is that I think there's a general preference for optional.value()[i] over (*optional)[i].

**Comment by AdmiralCurtiss** [comment]
> Only note I see about the code is that I think there's a general preference for optional.value()[i] over (*optional)[i].

Those two are different use cases. `x.value()` throws if there is no value, `*x` is UB if there is no value. Or in other words, `*x` is if you have already checked if there is a value, and `x.value()` is if you have not checked.

Anyway, I realized this doesn't even need to be optional, since we can just use an empty vector for the standard identity mapping case.

**Comment by TryTwo** [comment]
Tested again. It works. I didn't notice any issues in the code.

**Pull request merged**
