### PR TITLE
Android: improve app design + theme changer

### PR DESCRIPTION
**Pull request by Bankaimaster999**
Initial Port of MMJR2 Theme changer and Design Update to Dolphin-Android.

Feel free to edit it if you want (I didn't have much time to properly validate everything's in order; however it works as intended without issues).
Let me know your thoughts on this especially the game cover presentation and country/disc tags for quick info.

Also, hope all is well @JosJuice ~

### CODE REVIEW

**Comment by OatmealDome** [comment]
Any screenshots?

This will likely conflict with #10361, since that is also intended to update the app's design. Maybe it might be best to pick one or the other or perhaps combine the two in some way?

I'm also not sure it would be a good idea to include an MMJR branded theme in Dolphin mainline.

**Comment by Simonx22** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
> This will likely conflict with #10361, since that is also intended to update the app's design. Maybe it might be best to pick one or the other or perhaps combine the two in some way?

I will merge that PR before doing anything with this one.

> I'm also not sure it would be a good idea to include an MMJR branded theme in Dolphin mainline.

Yes, it would be a bit strange.

**Comment by mbc07** [comment]
That's not exactly what I expected when I read the PR title, thought it allowed selecting between the dark/light themes manually (which in general is a good thing to have, especially on Android 9 and older which lacks a system-wide toggle). 

With that out of the way, I'm not sure if adding a bunch of pre-defined themes is a good approach, especially when they only seem to change the accent color. I would rather keep the current theme as default and add an option for the user to provide a custom accent color if they wishes to customize the look...

**Comment by JosJuice** [comment]
> Let me know your thoughts on this especially the game cover presentation and country/disc tags for quick info.

Those changes sound like something that should be in a separate PR from the "theme changer" feature. I'm not sure if we want to accept the latter into Dolphin as it is (for the reasons mentioned by OatmealDome and mbc07), but none of those concerns apply to the game list changes.

**Comment by Bankaimaster999** [comment]
Alright, I'll look into changing things around and treat each part separately and then repost as 2 individual PR's

**Comment by lynxnb** [comment]
I know this PR has been closed already, but maybe some credits to the original author of this code (me) would have been very appreciated...

**Comment by Bankaimaster999** [comment]
> I know this PR has been closed already, but maybe some credits to the original author of this code (me) would have been very appreciated...

My apologies; This is theme changer is 100% @lynxnb  creation

**Pull request closed without merging**
