### PR TITLE
[Android] Reduce code redundancy and catch a leak

### PR DESCRIPTION
**Pull request by Tsunamical**
Essentially the previous cleanup PRs without the dependency update or stylistic changes. Because Android Studio 2.1.0 is out, we can shift the gradle plugin to it as it is in the stable line.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3849)

### CODE REVIEW

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by degasus** [comment]
Sounds like a nice cleanup. @sigmabeta ?

<details><summary><i>Previously, Parlane (Matthew Parlane) wrote…</i></summary>
> @dolphin-emu-bot rebuild
</details>


---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3849#-:-KI7AKKYDAsu4y8rAnl9:-720919208)*

**Comment by Parlane** [comment]
Reviewed 13 of 13 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3849)*

**Comment by JosJuice** [comment]
@Tsunamical A regression was reported. Could you look into it? https://bugs.dolphin-emu.org/issues/9560

**Comment by Tsunamical** [comment]
@JosJuice #3855

**Pull request merged**
