### PR TITLE
Update Dolphin Icon

### PR DESCRIPTION
**Pull request by Pringo**
Update the Dolphin icon to fix icon distortion issues on Windows. Discussed previously in #3725.

Versions Added:

- 32 x 32 @ 32 bit
- 48 x 48 @ 8 bit

Versions Removed:

- 64 x 64 @ 8 bit
- 64 x 64 @ 32 bit

New icon is 14.3 KB smaller than the original.

Should hopefully fix [Issue #8890](https://bugs.dolphin-emu.org/issues/8890). Edit: Nope. See following posts for details. I'm going to continue working on this.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3726)

### CODE REVIEW

**Comment by Pringo** [comment]
Hmm strange, I don't think this 100% fixes Issue #8890 after all. It's a net benefit for sure but the icons still look a bit different.

Dolphin Icons

Does anyone have any idea why would this happen? 

For reference the old behaviour is:

Dolphin Icons

**Comment by MaJoRoesch** [comment]
We made several attempts to fix this back when the icon was first created. We thought we had, but some complaints have popped up since. No one really knows what's going on. :/

Btw, it is always going to look awful in 8bit. I absolutely think windows is falling back to 8bit stupidly in some way and that it is the problem, not our icon. Try removing the 8bit versions and see what happens?

**Comment by Pringo** [comment]
@MaJoRoesch I actually just figured out what is going wrong a minute ago! Dolphin by default is loading Sys/Resources/Dolphin.png for its 32 x 32 icon on the taskbar. However in certain circumstances like opening a second window or pinning/unpinning Dolphin it is loading the 32 x 32 version of Dolphin.ico instead. As we previously didn't have a 32 bit 32 x 32 version in the .ico file we ended up with the poor looking 8 bit version. In this PR I added a 32 bit 32 x 32 version however it does not look identical to Dolphin.png which is causing the continued issue in my previous post.

Do you have any idea why it works this way? It should be somewhat easy to make a decent looking fix now that I know what is going on.

**Comment by Pringo** [comment]
Continued in #3727.

**Pull request closed without merging**
