### PR TITLE
GameSettings: Enable perf queries to fix sun in Need for Speed: Most Wanted.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
Rebase of #9380 with proper commit message. Mostly because I genuinely smiled at the PR name of 'turn on the sun'.

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
Note that I haven't actually tested this, but since this exact fix is suggested on the wiki I assume it's correct: https://wiki.dolphin-emu.org/index.php?title=Need_for_Speed%3A_Most_Wanted#Sun_Halo

**Comment by iwubcode** [comment]
@JMC47 do you have this game to confirm working behavior?

**Comment by JMC47** [comment]
I can confirm that Perf Queries produces the correct effect, however I am worried about the potential performance impact on weaker devices.

**Comment by JMC47** [comment]
Let us turn on the sun.

**Pull request merged**
