### PR TITLE
Char type error  

### PR DESCRIPTION
**Pull request by 0xlax**
Fixed a type error occured during linux installation posting char type to variable length char type

*first PR in here, apologies if I messed up anything*

### CODE REVIEW

**Comment by JosJuice** [comment]
Is this a fix for the same problem as PR #5065?

**Comment by AdmiralCurtiss** [comment]
You based this on an almost six year old commit...

**Comment by 0xlax** [comment]
But wasnt working and now it is ...

**Comment by JosJuice** [comment]
Did you test the latest version of master?

**Comment by AdmiralCurtiss** [comment]
I'm closing this because it's a fix for an issue that is already fixed in master -- and thus can't even be merged, because it conflicts with that fix.

I'm guessing what happened here is that you tried to build 5.0 (an almost 6 year old version!) and it failed, prompting you to make this fix, but your PR targets master, not 5.0. Though even if it did, I don't think it would be merged, since we don't want people to use 5.0 anymore at this point.

Thanks anyway, though.

**Pull request closed without merging**
