### PR TITLE
Android: Properly set default Internal Resolution

### PR DESCRIPTION
**Pull request by Ebola16**
~~The default value for Internal Resolution should be 0.~~ Also, Android studio also wanted me to use … instead of ...

### CODE REVIEW

**Comment by JosJuice** [comment]
No, it shouldn't. 0 means Auto, not 1x.

**Comment by Ebola16** [comment]
Then should I change the default value for IR to 1? Auto isn't an option for Android yet.

**Comment by Ebola16** [comment]
Updated @JosJuice

**Comment by JosJuice** [comment]
Changing the default IR to 1 LGTM.

I'm less sure about the ellipsis. It's not something we normally use on Dolphin, but maybe things are different on Android...?

**Comment by Ebola16** [comment]
I just did what Android Studio suggested. If someone wants it reverted that's fine.

**Comment by Ebola16** [comment]
@JosJuice I compared the ellipsis to the three dots on Android. On Android the three dots were more spaced out and easier to see than the ellipsis character. I reverted that part.

**Pull request merged**
