### PR TITLE
D3D11: Support texture dumping of non-zero mipmap levels

### PR DESCRIPTION
**Pull request by stenzek**
Relatively straightforward change.

This will bring D3D11 to feature parity with D3D12 and GL for texture dumping.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3861)

### CODE REVIEW

**Comment by degasus** [comment]
LGTM, but I fear this will be after 5.0.

<details><summary><i>Previously, stenzek (Stenzek) wrote…</i></summary>
> #### D3D11: Support texture dumping of non\-zero mipmap levels
> 
> Relatively straightforward change.
> 
> 
> 
> This will bring D3D11 to feature parity with D3D12 and GL for texture dumping.
> 
> 
> 
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3861#-:-KImxQu75VKGfHVi7x7B:-1465471553)*

**Comment by Fallcrest** [comment]
This should be allowed to merge now, but should there a later PR to move the handling of texture dumping to VideoCommons?

**Comment by degasus** [comment]
It just need a rebase.

**Comment by degasus** [comment]
rebase please?

**Comment by degasus** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3861)*

**Pull request merged**
