### PR TITLE
[Android] Update to Android Studio 2.0 + Cleanup

### PR DESCRIPTION
**Pull request by Tsunamical**
Now that Android Studio 2.0 stable is out we can finally upgrade! This commit also brings in other various improvements and enhancements.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3781)

### CODE REVIEW

**Comment by sigmabeta** [comment]
@dolphin-emu-bot rebuild

**Comment by Tsunamical** [comment]
We could roll back to 23.0.2 build tools and 23.1.1 support libraries if you would rather have this pushed first, otherwise build bot needs to be updated in order to properly build.

**Comment by BhaaLseN** [comment]
I'm rather impartial on the generic inference changes, and on pretty much most of the others too, but I guess its a good start. Some other reviews wouldn't be bad too.

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/MotionAlertDialog.java, line 106 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-KFemQh6LSGjgSVWpQcd:-KFemQh74neeN1ev4rBb:1013177305) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3bd259b04390213942f398130cf0a1dada8b1a98/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/MotionAlertDialog.java#L106)):*
I believe our code style still says "brace on next line", even for java.
+/-0 on the single-line merge, I'm fine either way.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java, line 70 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-KFem_vt8oNDVuRZ2j05:-KFem_vuLn36PDhuIGsU:1467075385) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3bd259b04390213942f398130cf0a1dada8b1a98/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java#L70)):*
If you make them non-members, please remove the `m` prefix to avoid confusion. The same down there

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/LoadStateFragment.java, line 23 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-KFemdk2HtPqVsD0J5vi:-KFemdk2HtPqVsD0J5vj:-141309294) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7e832c472697daa86c94992940b2fdb2981f7646/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/LoadStateFragment.java#L23)):*
Even if you can simplify this, it is meant as a factory method that potentially sets members to initialize state before returning the instance. So I'd rather preferring to leave the old part, but I won't object if everyone else thinks differently.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/SaveStateFragment.java, line 23 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-KFemxCMOqqZjRlEj3a5:-KFemxCMOqqZjRlEj3a6:100931966) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7e832c472697daa86c94992940b2fdb2981f7646/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/SaveStateFragment.java#L23)):*
Same here. Or, if you do want to look into this, you could check whether those factory methods are even needed.

---

*[Source/Android/app/src/main/res/layout/dialog_game_details.xml, line 22 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-KFenKNuKHzOJTQlBtgR:-KFenKNvTxd17CaK9Rd8:1520573809) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3bd259b04390213942f398130cf0a1dada8b1a98/Source/Android/app/src/main/res/layout/dialog_game_details.xml#L22)):*
Is this correct? Not terribly certain if that prefix is meant to be there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-:-KFenTVD1L9zAl1FBCa_:803803199)*

**Comment by Tsunamical** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/MotionAlertDialog.java, line 106 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-KFemQh6LSGjgSVWpQcd:-KFfd0ziISNWFf2-5Qw5:-374863561) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3bd259b04390213942f398130cf0a1dada8b1a98/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/MotionAlertDialog.java#L106)):*
Fixing momentarily.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java, line 70 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-KFem_vt8oNDVuRZ2j05:-KFfcvMqudqRJepCjEhm:-159990153) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3bd259b04390213942f398130cf0a1dada8b1a98/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/EmulationFragment.java#L70)):*
I forgot to remove that - thank you for the catch!

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/LoadStateFragment.java, line 23 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-KFemdk2HtPqVsD0J5vi:-KFfdIG3jlXcv0QK-aQV:369925113) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7e832c472697daa86c94992940b2fdb2981f7646/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/LoadStateFragment.java#L23)):*
Okay, will revert to old logic here.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/SaveStateFragment.java, line 23 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-KFemxCMOqqZjRlEj3a5:-KFfdMesj8kWnu1zlULF:1237380578) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7e832c472697daa86c94992940b2fdb2981f7646/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/fragments/SaveStateFragment.java#L23)):*
Same applies to here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781)*

**Comment by BhaaLseN** [comment]
Reviewed 2 of 14 files at r2, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/EGLHelper.java, line 123 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-KFjCsN1eB1JfHap1gSw:-KFjCsN1eB1JfHap1gSx:-2035653390) ([raw file](https://github.com/dolphin-emu/dolphin/blob/902db30fd4eab6561a2586c103ae9382ca46abd6/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/EGLHelper.java#L123)):*
Does this even compile?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781)*

**Comment by Tsunamical** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/EGLHelper.java, line 123 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-KFjCsN1eB1JfHap1gSw:-KFjFWFbv78LL08kwjQS:537215446) ([raw file](https://github.com/dolphin-emu/dolphin/blob/902db30fd4eab6561a2586c103ae9382ca46abd6/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/EGLHelper.java#L123)):*
Another good catch - my bad. info should be removed. Fixing :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781)*

**Comment by Tsunamical** [comment]
Review status: 16 of 18 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/EGLHelper.java, line 123 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-KFjCsN1eB1JfHap1gSw:-KFsx-wKCgQorawtJNqS:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/902db30fd4eab6561a2586c103ae9382ca46abd6/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/EGLHelper.java#L123)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781)*

**Comment by BhaaLseN** [comment]
Style-wise I guess I'm happy now I guess. Someone else should probably comment on the gradle/sdk-related changes before this gets merged tho.

---

Reviewed 1 of 2 files at r4.
Review status: 17 of 18 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3781#-:-KFtbM8FJ59aj5s3zJeg:-507138160)*

**Comment by Tsunamical** [comment]
Gradle changes are fine, built bot needs to be updated before it can be merged. Any comments @sigmabeta? I can always split the commit if we want to hold on the dependency update.

**Comment by sigmabeta** [comment]
I'd roll those back unless there's something specific being added that depends on them.

We should have our CI server use a script to automatically update tools; something like [this](https://github.com/tadfisher/android-sdk-updater). Until then, we shouldn't upgrade gradle dependencies without a good reason.

@Parlane is probably the person to talk to about getting that CI script going.

**Comment by Tsunamical** [comment]
I highly recommend bumping up to gradle 2.0.0 - now that it's in the stable line. What would you prefer be rolled back? Gradle/support libraries/build tools or all? Support library updates are primarily just bug fixes.

**Comment by sigmabeta** [comment]
Using the Gradle 2.0 plugin is probably fine and doesn't require CI maintainer intervention. I think its the support libraries and such that held up the last build attempt. Those require a manual update and I'm pretty sure our maintainer doesn't want to do that manually anymore, so you''ll need to help him get a script going to do it if you want those updates.

**Comment by Tsunamical** [comment]
I would be interested in assisting. I'll roll back the support libraries and such for now.

**Pull request closed without merging**
