### PR TITLE
[Android] Block profiling JNI interface

### PR DESCRIPTION
**Pull request by Sonicadvance1**
Add an interface for enabling block profiling and writing the results out to file.

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
Most likely need to prod @sigmabeta to see the best way to expose this interface to Java.
Might be able to return an array of structures to Java instead of just writing to file?
Would require even more changes to our Profiler namespace in that case.

**Comment by sigmabeta** [comment]
What's the format of the data saved to the file? If it's some common serialization format (JSON would be ideal) then I'd say no question, just let me read it out of the file.

Even if it's not common and I'd have to write some parsing logic, I'd still say if the writing code is already in place, it makes the most sense to just read out of the file. Passing an array of structs through a JNI interface could get ugly pretty quick.

**Comment by Sonicadvance1** [comment]
The format is just a tab separated format. First line is headers for each column and then follows the data.
Here is the first few lines of a file being output.
http://hastebin.com/vakogarimu.hs

**Comment by sigmabeta** [comment]
Oh, that's not bad at all. Unless someone really knows JNI a lot better than I do and can think of a dead simple way to read a struct into Java, I'm down for just reading the file.

**Pull request merged**
