### PR TITLE
Core: Fix booting titles from NAND.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
Not sure how I managed to invert that one...

https://github.com/dolphin-emu/dolphin/commit/9a3e770c23312f61848adefc7202cb1b800cadff#diff-6444f2b6020682322bcf590eed60eaf5cd0179c07ab419599e0e208540957596L305

### CODE REVIEW

**Review by Pokechu22 — APPROVED** [review]
Looks good to me. Not sure what's going on with the linux builders. For reference this fixes https://dolp.in/i13472.

**Comment by AdmiralCurtiss** [comment]
The build failures were from https://bugs.dolphin-emu.org/issues/13470. I've merged #12514 to fix them.

**Comment by denny4-user** [comment]
[Pokechu22](https://github.com/Pokechu22) WDL 1.18.2 pls!(

**Comment by Pokechu22** [comment]
@denny4-user Unlikely to happen any time soon due to being busy + changes with the game, sorry. Check the README for suggestions for other tools (though I haven't actually tried any myself).

**Comment by denny4-user** [comment]
@Pokechu22 Okay... I understand you perfectly.

I checked both mods and they can't compare with yours. You have a very cool mod. I'm waiting for a possible release... I would be very grateful :^

**Pull request merged**
