### PR TITLE
Android: Allow disabling cover downloading

### PR DESCRIPTION
**Pull request by JosJuice**
In case someone wants to be very careful with how much bandwidth they use or with what data GameTDB.com collects on you. This is already an option in DolphinQt (though in DolphinQt it will switch entirely from using covers to banners when turned off).

### CODE REVIEW

**Review by Ebola16 — APPROVED** [review]
There's probably no need to split off the first commit since this PR seems pretty straightforward.

**Comment by Ebola16** [comment]
At some point `InputOverlay` will need access to `Settings` so settings can be saved there instead of using `SharedPreferences`. Do you think that should be accomplished by using the method you removed from `EmulationActivity` in this PR or something more global?

**Comment by JosJuice** [comment]
I believe it would make most sense to re-add the method I removed from EmulationActivity. (Unless we put the Settings object directly in InputOverlay?)

**Comment by Ebola16** [comment]
I think I'll go with the method removed in this PR then. I just wanted to make sure I wouldn't conflict with your planned changes.
One other question, does ` mSettings.close` need to be called in `onDestroy` if used in `InputOverlay`? I wouldn't expect `mSettings` to survive after `InputOverlay`'s destruction but I might be misunderstanding something.

**Comment by Ebola16** [comment]
Oh `mSettings.close` is called in `EmulationActivity`, never mind.

**Review by Ebola16 — CHANGES_REQUESTED** [review]
While working on the `SharedPreferences` to INI PRs, I found that `SharedPreferences` are set in `EmulationActivity.toggleControls`. When converted to INI settings, I'll need access to `Settings` to set those values. Please revert the change that removes `mSettings` in `EmulationActivity`.

**Comment by JosJuice** [comment]
Done.

**Review by Ebola16 — APPROVED** [review]
Reminder to self to update #8894 after this PR is merged.

**Comment by JosJuice** [comment]
I'll need to update PR #9148 too. (Or this PR, if that PR gets merged first.)

**Review by leoetlino — APPROVED** [review]

**Pull request merged**
