### PR TITLE
Core/WiiRoot: Fix NetPlay full Wii save sync not copying all the saves back to main NAND

### PR DESCRIPTION
**Pull request by Techjar**
It only saved the current title ID, which means any other saves modified would not be written to main NAND.

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Why is everything commented out inside that loop?

**Comment by Techjar** [comment]
That would be more leftover crap from testing, whoops!

**Comment by Roadhog360** [comment]
Wait so is this why whenever something changes on Netplay, that wouldn't be written to the save? Will it actually write to my save?

**Comment by JMC47** [comment]
Unless you're changing multiple title IDs, it should be fine.  Maybe the case of using ProjectM is one of the few where this is broken though.

**Comment by Roadhog360** [comment]
Yeah I was using Gecko to change title IDs. I thought the save not being written was intentional.

**Comment by JMC47** [comment]
You can still disable save writing if that's what you want, but saves made on netplay should be kept at the end when save writing is enabled.

**Comment by Roadhog360** [comment]
No no, I'm glad it wasn't intentional because I really did kind of wish it wrote to the save. (Maybe I should have requested it.)

**Pull request merged**
