### PR TITLE
Add New Dolphin Icon

### PR DESCRIPTION
**Pull request by Pringo**
There are some scenarios where the Dolphin icon looks distorted in Windows but there didn't appear to be much interest so far in trying to fix it for 5.0 so I thought I would take a crack at it myself. I don't know a whole lot about how icon files work so bear with me here.

Looking at the Dolphin icon in IconsExtract shows that there were seven variants of the icon.

Dolphin Icons

For some reason there are three 8 bit icons in there which look noticeably worse than the 32 bit versions. Also of note is that the 32 x 32 icon only has an 8 bit version. I suspect that these 8 bit icons are the source of the distorted Windows icon issues.

So in order to fix this I deleted the three 8 bit icon variants and generated a new 32 bit 32 x 32 icon. Replacing the Dolphin icon locally with this new version seems to have fixed the distorted icon issues I experienced. I would still like to test the PR build to see if this actually solves the issue.

@delroth could you take a look at this as you uploaded the current Dolphin.ico file?

@MaJoRoesch could I get you input too? I'm not really a graphics expert.

Hopefully fixes [#8890](https://bugs.dolphin-emu.org/issues/8890).

Edit: This is probably still a work in progress. Please don't merge.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3725)

### CODE REVIEW

**Comment by mbc07** [comment]
I would suggest just adding a 32 bit version of the 32x32 icon on top of what we already have instead of completely purging the 8 bit variants...

**Comment by Pringo** [comment]
Okay reading up on this a bit more it seems like the standard application icon sizes for Windows are:

256 x 256 pixels  – 32bit (24bit colour, 8bit transparency)
48 x 48 pixels  – 32bit (24bit colour, 8bit transparency)
32 x 32 pixels  – 32bit (24bit colour, 8bit transparency)
16 x 16 pixels  – 32bit (24bit colour, 8bit transparency)

https://www.creativefreedom.co.uk/icon-designers-blog/windows-7-icon-sizes/

For some reason we are missing the 32 bit 32 x 32 icon which I'm assuming results in Windows falling back to the 8 bit version. I think I was wrong initially and 8 bit versions are good to include for backwards compatibility reasons or if the user can't display 32 bit colours. I still don't know why in certain scenarios Windows appears to switch between using the 32 and 8 bit versions however.

We also include a 64 x 64 variant of the icon which isn't used by Windows. Is this for OS X? Also looking at this page: http://www.visualpharm.com/articles/icon_sizes.html Macs can use up to 1024 x 1024 icons for Retina displays I'm assuming. Do we include a large high quality icon for Retina? Should an even larger version be added?

Finally what sizes do we use for Linux? I see GNOME uses 48 x 48 and 24 x 24 but I don't know what we are supposed to support.

**Comment by JosJuice** [comment]
If you're running Dolphin on a computer with 8-bit color, you're going to have bigger problems than the icon's colors. Based on the guide, it seems like the reason to include icons with fewer colors is compatibility with older versions of Windows, which is irrelevant for Dolphin since Vista and up support modern icons just fine.

Only Windows uses the .ico file as far as I know.

**Comment by Pringo** [comment]
@JosJuice okay so you think it is fine to omit the 8 bit versions then? Also if .ico is only used by Windows do you know why the 64 x 64 icon versions are there? Am I safe to remove those as well?

**Comment by JosJuice** [comment]
According to the Microsoft documentation that the guide links to, "For Classic Mode, the full set is 16x16, 24x24, 32x32, 48x48 and 64x64." It doesn't seem like we actually need 64x64, though, because the ".ico file sizes (standard)" diagram further down doesn't include that size.

Also, the same documentation says that 8-bit and 4-bit icons can be needed for Remote Desktop, which is new to me. Running Dolphin like that is probably not going to work well, but maybe people want to be able to see the icon in the program list correctly even if they're not going to run it. Are the 8-bit icons are small enough that we can keep them?

**Comment by Alcaro** [comment]
Judging by Pringo's screenshot, they're about nine kilobytes.

But on the other hand, I think RDP can generate downsampled icons automatically.

Might as well include them. Nine kilobytes more or less makes no difference. Do what's easier for you.

**Comment by JosJuice** [comment]
Yeah, we might as well include them. You should replace the 64x64 8-bit icon with a 48x48 one, though.

**Comment by delroth** [comment]
Microsoft recommends an 8 bit version, see
https://msdn.microsoft.com/en-us/library/windows/desktop/dn742485(v=vs.85).aspx

"*Icon files require 8-bit and 4-bit palette versions as well,* to support
the default setting in a remote desktop. These files can be created through
a batch process, but they should be reviewed, as some will require
retouching for better readability."

**Comment by Pringo** [comment]
@JosJuice @delroth 

Okay right now my plan is to add a 32 bit 32 x 32 icon and an 8 bit 48 x 48 icon to the original. Does that sound fine? I tried looking at some default Windows icons and I don't think they typically include an 8 bit variant of the 256 x 256 icon.

Also I'm assuming we don't need the 4 bit icons as we never had those in the first place or do we want to include them now?

**Comment by JosJuice** [comment]
That sounds good, and you can also delete the 64x64 icons. Not including an 8-bit 256x256 is the right way to go.

**Comment by Pringo** [comment]
Continued in #3726

**Pull request closed without merging**
