### PR TITLE
VideoConfigDiag: Rename EFB Copies to RAM option

### PR DESCRIPTION
**Pull request by Stevoisiak**

### CODE REVIEW

**Comment by lioncash** [comment]
Looks good to me (assuming the terminology is correct).

**Comment by MaJoRoesch** [comment]
This is a continuation of pull 2128, after much bikeshedding. It would be best if this could be merged before the progress report! It's the best way to train the users on the change.

**Comment by Stevoisiak** [comment]
Should I close #2128 then?

**Comment by MaJoRoesch** [comment]
Mhmm. It started the conversation, which is what it was for! :)

**Pull request merged**
