### PR TITLE
Disable some Video settings for 1080° Snowboarding

### PR DESCRIPTION
**Pull request by ytrezq**
If enabled, in game virtual screens don’t works and camera might go below ground.
Also fix some graphical effects in menus.

Screenshots can be provided if needed.
All videos backends are affected if those settings are enabled.

### CODE REVIEW

**Comment by JMC47** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
Is there really a NAOK01? The Korean version of this game should be using E or W, not K.

**Comment by JMC47** [comment]
I'm not 100% sure with the Korean VC, but, if it doesn't exist then it's not the worst INI mistake currently in Dolphin.  That belongs to 1000s of others.

**Comment by ytrezq** [comment]
I’m not even sure other game régions are conerned by this problem.
As I don’t have any ideas about other game ɪᴅ I took the reference [here](https://wiki.dolphin-emu.org/index.php?title=1080%C2%B0_Snowboarding).

**Review by becanh0712-bit — COMMENTED** [review]
> ``

**Pull request merged**
