### PR TITLE
Sync the "enable cheat" setting over netplay

### PR DESCRIPTION
**Pull request by mathieui**
---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3878)

### CODE REVIEW

**Comment by Helios747** [comment]
lol

**Comment by E2xD** [comment]
Is there any update on this/anything we can test for you?

**Comment by mathieui** [comment]
I opened it on a whim during the freeze and I need to rebase it, but it should work

**Comment by JMC47** [comment]
Is there anything holding this up now?

**Comment by E2xD** [comment]
So this is interesting. If lets say I'm hosting with Enable Cheats selected, it forces the other user's enable cheat on even after emulation has ended. And vice versa, if I'm hosting with Enable Cheats deselected, it forces the toggle off on the other user after emulation. I don't know if this is intentional. This does work even with up to 4 people (been testing it.)

**Comment by JMC47** [comment]
It shouldn't actually permanently set the setting.  That's a bug.

**Comment by clinchergt** [comment]
@mathieui: I fixed the bug mentioned by @E2xD here: https://github.com/mathieui/dolphin/pull/1

Could you guys review it?

**Comment by mathieui** [comment]
@dolphin-emu-bot rebuild

@clinchergt thanks, merged in the branch (that’s a bigger patch than the original PR :smile: )

**Comment by JMC47** [comment]
Can this be retested now? @E2xD

**Comment by phire** [comment]
ConfigCache is a huge hack....

But :lgtm: assuming nothing shows up in testing.

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3878#-:-KLuO2ddA7o6cIYGAPjw:1483676153)*

**Comment by JMC47** [comment]
LGTM, the bug I found was unrelated to this PR.

**Comment by E2xD** [comment]
Working as intended. LGTM

**Pull request merged**
