### PR TITLE
CMake: Fix building against macOS framework builds of SDL

### PR DESCRIPTION
**Pull request by TellowKrinkle**
Our find script wasn't compatible with SDL's framework builds.  SDL has shipped with a CMake find script since 2.0.10, and hopefully no one is trying to use an SDL older than that, so I just removed the find script.

In addition, the framework build's find script supplies its link arguments with `INTERFACE_LINK_OPTIONS`, which didn't propagate across private dependencies until CMake 3.17 with CMP0099 enabled.

Note: An alternative to manually enabling these policies would be to mass enable all policies introduced up to 3.26 (when supported) with `cmake_minimum_required(VERSION 3.13...3.26)`.  Preferences?

### CODE REVIEW

**Comment by OatmealDome** [comment]
@dolphin-emu-bot rebuild

**Comment by OatmealDome** [comment]
Could you drop the CI test commit now that the build machine has been fixed?

**Comment by OatmealDome** [comment]
@dolphin-emu-bot rebuild

**Comment by OatmealDome** [comment]
These changes LGTM, though I'd like someone more familiar with CMake to comment on the note.

**Comment by AdmiralCurtiss** [comment]
I'm not *super* familiar with CMake either, but enabling all policies seems like an easy way to subtly change behavior in an unnoticeable way, so probably not ideal. Someone would probably need to go through them one by one and see if any could be problematic, and only if they're confirmed not to be enable them.

**Comment by delroth** [comment]
@dolphin-emu-bot rebuild

(testing new buildbot config before merging)

**Pull request merged**
