### PR TITLE
D3D Optimizations/Audio Optimizations

### PR DESCRIPTION
**Pull request by Loggan08**
Using c++ casts instead of C casts
And other minor optimizations + cleanup

Mainly the c++ casts should perform better over the C style casts

### CODE REVIEW

**Comment by degasus** [comment]
Please don't create new PRs for small updates, just force-push to your last one.

**Comment by Loggan08** [comment]
Besides that, looking fine?

**Comment by lioncash** [comment]
The changes to AudioCommon are not optimizations. Please correctly detail what you've done in the commit.

**Comment by lioncash** [comment]
Sure, however, you refer to them as optimizations, which they are not.

**Comment by degasus** [comment]
Half of those static_casts aren't static_cast. And this PR seems to be inactive for a long time already.

**Pull request closed without merging**
