### PR TITLE
Mario Party Netplay Community Settings: remove widescreen on community code

### PR DESCRIPTION
**Pull request by CrankySupertoon**
this PR removes the widescreen on the community codes i commited a few months back

### CODE REVIEW

**Comment by Starmann** [comment]
Any particular reason?

**Comment by CrankySupertoon** [comment]
Netplay widescreen codes shouldnt be forced

**Comment by Starmann** [comment]
Ah I misinterpreted this as meaning that you were removing the widescreen codes entirely from the file.

**Comment by JMC47** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
