### PR TITLE
OGL: Post-processing suite

### PR DESCRIPTION
**Pull request by Asmodean-**
It was requested by a few people, that I make a PR for this. It Includes;

---

FXAA 3.11

Bilinear Filtering
Bicubic Interpolation Scaling
Lanzcos Interpolation Scaling

Blended Bloom /w 5 different bloom types.
Scene Tone mapping /w optional filmic operators
Colour Correction
Filmic Cross Processing
Gamma Correction Curve
Texture Unsharp Mask
Pixel Vibrance Adjustment
Local Contrast Enhancement
PX Cel Shading

Scan line Emulation
Film Grain
Vignette
Subpixel Dithering

---

Each effect can be enabled, & disabled independently, and various options which can be configured in real-time, via the post-processing GUI.

### CODE REVIEW

**Comment by ADormant** [comment]
That wxWidgets bug has been fixed so are there still any reasons why it can't be reopened and merged ?

**Comment by neobrain** [comment]
Yes, specifically all of my comments in that PR.

**Comment by neobrain** [comment]
Btw, that's just my opinion. Feel free to convince the rest of the team if you think it's worthwhile to have the suite included regardless.

**Comment by ADormant** [comment]
Well Dolphin's translation system isn't really relevant to users however if it won't be merged then no one will have incentive to improve it anyway.

**Pull request closed without merging**
