### PR TITLE
WX: Custom Load Path

### PR DESCRIPTION
**Pull request by GradyMoran**
implements https://bugs.dolphin-emu.org/issues/9970

Only on WX. 

This is my first contribution to dolphin, so criticism is welcome.

### CODE REVIEW

**Comment by spycrab** [comment]
@dolphin-emu-bot rebuild

**Comment by ZexaronS** [comment]
Run this for lint problems
`git diff --cached --name-only | egrep '[.](cpp|h|mm)$' | xargs clang-format-380 -i`
you run after you stage (add .) the modified files, once it's done you stage them again, then proceed to commit, etc

**Comment by GradyMoran** [comment]
Thanks Zexaron. I installed it with apt :). There's also Tools/lint.sh. 

Once everything else is good to go I would like some help squashing/cleaning up these commits.

**Comment by JosJuice** [comment]
> There's really no consensus on lint

Please stop spreading misinformation. The consensus is that all PRs have to pass the lint buildbot. Yes, there are problems with people using different versions of clang-format that format slightly differently, which is annoying when trying to make a PR, but it does not mean that we don't have a consensus on how to format code.

**Comment by JosJuice** [comment]
@ZexaronS If you keep this up, we may block you from this repo.

**Comment by spycrab** [comment]
@dolphin-emu-bot rebuild

**Comment by ligfx** [comment]
@GradyMoran Normally I would recommend using interactive rebase to squash those commits, but I'm not sure how to get it to work correctly with merge commits...

What you can try is something like this: `git reset 194b95d~`, tells git to go back before all of the commits listed in this PR, but leaves the file changes alone, and then you can make another, single commit with all of the changes.

**Comment by GradyMoran** [comment]
Fouled up and fixed git issues.

**Comment by Zexaron** [comment]
Close and reimplement in Qt since Wx is gone?

**Comment by JosJuice** [comment]
Closing because DolphinWX has been removed.

**Pull request closed without merging**
