### PR TITLE
Replace SOIL with libpng

### PR DESCRIPTION
**Pull request by linkmauve**
This removes a direct dependency on libGL, to reuse a library already present in Dolphin.

According to a comment in the hires texture path, the removal of lock done to work around SOIL’s absence of thread-safety should improve performances of cache lookups.

nogui is now able to link when it’s built with `-DUSE_EGL=ON` or with #4553’s new backend.

Note that this currently drops support for DDS textures, reimplementing that should be done before this PR gets merged.

Also missing is Visual Studio support, I have no way to test that. :x

### CODE REVIEW

**Comment by nbohr1more** [comment]
Compare to: https://github.com/dolphin-emu/dolphin/pull/2163

**Comment by PEmu1** [comment]
It also might be worth updating libpng. This was attempted in #3374 but that PR ended up getting abandoned. The latest release is 1.6.26 and Dolphin is still on 1.2.50.

**Comment by BigheadSMZ** [comment]
It's good to see texture loading for DDS is planned, but what about JPG? As far as I know there are still some packs that use them such as hypatia's wind waker. But that's the only one I know of, so if support is dropped I doubt there will be many who oppose.

For DDS, this should be taken into consideration when choosing the implementation.
https://bugs.dolphin-emu.org/issues/9254

**Comment by JosJuice** [comment]
Hypatia's Wind Waker pack used to use JPEG for some textures, but the newest version (released in September 2016) only uses DDS as far as I know. So that's not a problem anymore. Other than that, I can't think of any texture packs that use JPEG.

**Comment by Tinob** [comment]
be carefull when testing this because when i implemented it on ishiiruka i have a ton of reports of png images failed loading and even some hangs.

**Comment by ZephyrSurfer** [comment]
Could you remove references to SOIL from the visual studio solution. Search string "B441CC62-877E-4B3F-93E0-0DE80544F705"

**Comment by shuffle2** [comment]
why did everyone really want to get rid of SOIL in 2 PRs and then give up?

**Comment by JosJuice** [comment]
Replacing with the updated PR #6291.

**Pull request closed without merging**
