### PR TITLE
DriverDetails: Disable primitive restart on Adreno

### PR DESCRIPTION
**Pull request by JosJuice**
Turning off primitive restart increases performance a lot on Adreno for some reason. We're talking numbers like 50%-100% faster in situations which are bottlenecked by rendering.

### CODE REVIEW

**Comment by JMC47** [comment]
Confirmed on my Pixel 3, disabling Primitive Restart is Stonks

**Review by Simonx22 — APPROVED** [review]

**Comment by Gozen0410** [comment]
How disable that thing I can't find🥲

**Comment by Gamemulatorer** [comment]
What adreno gpu series? 5xx or 6xx?

**Comment by JMC47** [comment]
You don't need to change anything, Primitive Restart is disabled automatically in the newest builds.

**Comment by Gamemulatorer** [comment]
> You don't need to change anything, Primitive Restart is disabled automatically in the newest builds.

Disable automatically in all adreno gpus?

**Comment by JMC47** [comment]
That's what this does, yep.  It automatically disables it on Adreno.

**Comment by Gozen0410** [comment]
It's adreno 619

**Pull request merged**
