### PR TITLE
WX: ISOProperties: Add notice when cheats are disabled (Issue 9690)

### PR DESCRIPTION
**Pull request by EmptyChaos**
cheatnotice
Message only appears when triggered by the user turning a code on/off or adding a new code. Button is disabled if the emulator is running. Also displays "Changing cheats will only take effect when the game is restarted" without the button if cheats are enabled but the game is currently running.

Includes a refactor of the Action Replay tabs in ISOProperties and Cheat Manager into a unified class like the Gecko codes panel.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4048)

### CODE REVIEW

**Comment by EmptyChaos** [comment]
@dolphin-emu-bot rebuild

**Comment by EmptyChaos** [comment]
@MaJoRoesch Would you like to review this?

**Comment by Starsam80** [comment]
["Cheat Engine" is an actual thing](http://www.cheatengine.org/), so I would suggest changing the text to something simple like "Cheats are currently disabled"

**Comment by EmptyChaos** [comment]
I've changed it to "cheat system" instead.

I'm not convinced that was actually a problem. "Cheat Engine" is named in an overly literal way, like if Linux was called "Unix-compatible Operating System" instead of "Linux".

**Comment by MaJoRoesch** [comment]
Hmmmmmm. By having an enable cheats checkbox here, what if a user wants to *disable* cheats later? They'll have no idea where it is! I hate having doubling up but, if cheats can be enabled here, they should be disable-able here too. Either that, or make that button to be a shortcut to the configuration space where the enable cheats option resides?

**Comment by EmptyChaos** [comment]
I can change the button to "Configure Dolphin" and make it open the normal configuration window, although that doesn't really explain how to find the configuration window afterwards (though I'd like to think the toolbar button is obvious).

Could you explain how you would want the disable functionality to work?

**Comment by EmptyChaos** [comment]
cheatnotice

**Comment by EmptyChaos** [comment]
@dolphin-emu-bot rebuild

**Comment by lioncash** [comment]
I realize some of the review comments may be applying to code that was pre-existing, since files were moved, but reviewable/git didn't track it as a file move, since multiple other changes were made. Feel free to ignore those if you want.

---

Review status: 0 of 21 files reviewed at latest revision, 18 unresolved discussions.

---

*[Source/Core/Core/ARDecrypt.cpp, line 484 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNHwIrsVh8Zc-Dqk7YT:-KNHwIrsVh8Zc-Dqk7YU:1043048850) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/Core/ARDecrypt.cpp#L484)):*
> ```cpp
>     for (size_t i = 0; i < (vCodes.size() << 1); i += 2)
>     {
>       ops->emplace_back(AREntry{uCodes[i], uCodes[i + 1]});
> ```

```cpp
ops->emplace_back(uCodes[i], uCodes[i + 1]);
```

---

*[Source/Core/Core/ARDecrypt.cpp, line 494 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNHwOVLozF_lFtRD0CX:-KNHwOVLozF_lFtRD0CY:1219818639) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/Core/ARDecrypt.cpp#L494)):*
> ```cpp
>     for (size_t i = 2; i < (vCodes.size() << 1); i += 2)
>     {
>       ops->emplace_back(AREntry{uCodes[i], uCodes[i + 1]});
> ```

```cpp
ops->emplace_back(uCodes[i], uCodes[i + 1])
```

---

*[Source/Core/DolphinWX/FrameTools.cpp, line 606 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNHwdwOuvmownouAMzT:-KNHwdwP05_T_3JFZtPF:-943017903) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/FrameTools.cpp#L606)):*
> ```cpp
>   if (tab > -1)
>     config_main.SetSelectedTab(tab);
>   HotkeyManagerEmu::Enable(false);
> ```

Might want to consider adding a newline before this line and after the following call to this function that re-enables it to make them stand out more.

---

*[Source/Core/DolphinWX/ISOProperties.cpp, line 82 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNHx4K7xqOiKSnfSgIh:-KNHx4K7xqOiKSnfSgIi:-1380773058) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/ISOProperties.cpp#L82)):*
> ```cpp
> // Also displays a different warning when the game is currently running to explain
> // that toggling codes has no effect while the game is already running.
> class CheatWarningMessage : public wxPanel
> ```

```cpp
class CheatWarningMessage final : public wxPanel
```

---

*[Source/Core/DolphinWX/ISOProperties.cpp, line 90 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI0q8He44KIbbhgqys:-KNI0q8Imdo6Iy8RlEYT:-568510206) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/ISOProperties.cpp#L90)):*
> ```cpp
>     SetExtraStyle(GetExtraStyle() | wxWS_EX_BLOCK_EVENTS);
> 
>     wxStaticBitmap* icon =
> ```

Most of this UI creation code should likely be in its own CreateUI/CreateGUI function.

---

*[Source/Core/DolphinWX/ISOProperties.cpp, line 122 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNHxBPWGxWzSwuyJDdr:-KNHxBPWGxWzSwuyJDds:-1904223521) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/ISOProperties.cpp#L122)):*
> ```cpp
> 
> private:
>   enum class States
> ```

This should just be named `State`.

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.cpp, line 23 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI-RXdpCF4dyo1q1tY:-KNI-RXdpCF4dyo1q1tZ:-853120239) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.cpp#L23)):*
> ```cpp
>   SetExtraStyle(GetExtraStyle() | wxWS_EX_BLOCK_EVENTS);
> 
>   m_checklist_cheats = new wxCheckListBox(this, wxID_ANY);
> ```

Ditto about UI creation.

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.cpp, line 41 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNHxoHQzz5rV0nqJ_pt:-KNHxoHQzz5rV0nqJ_pu:506929133) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.cpp#L41)):*
> ```cpp
>   }
> 
>   int space5 = FromDIP(5);
> ```

This should probably be `const`

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h, line 28 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI1xwVKW-bRmgxI0s7:-KNI1xwVKW-bRmgxI0s8:1740396047) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h#L28)):*
> ```objc
> {
> public:
>   enum Styles
> ```

This should just be named `Style`

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h, line 34 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI2KfTgS7YMHUUrvBE:-KNI2KfTgS7YMHUUrvBF:-1243318884) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h#L34)):*
> ```objc
>   };
> 
>   ActionReplayCodesPanel(wxWindow* parent, int styles = 0);
> ```

This should use the Style enum as the type of `styles`. `0` should also be a defined style constant.

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h, line 44 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI2hkIAVCOahomUlR1:-KNI2hkIAVCOahomUlR2:-1787267775) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h#L44)):*
> ```objc
> 
>   bool IsModified() const { return m_was_modified; }
>   int GetCodePanelStyle() const { return m_styles; }
> ```

This should return as the Style enum type.

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h, line 45 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI25qDYGpPLgPw1Lkv:-KNI25qEj20ZfPlQOVvf:-632400218) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h#L45)):*
> ```objc
>   bool IsModified() const { return m_was_modified; }
>   int GetCodePanelStyle() const { return m_styles; }
>   void SetCodePanelStyle(int style);
> ```

This parameter should use the Style enum as the type.

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h, line 73 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI2dbCwrAbAkBcpXS7:-KNI2dbCwrAbAkBcpXS8:1750180776) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h#L73)):*
> ```objc
> 
>   bool m_was_modified = false;
>   int m_styles = 0;
> ```

This should likely be the `Style` enum type

---

*[Source/Core/DolphinWX/Cheats/ARCodeAddEdit.cpp, line 29 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI3oV0qDKBHRhy0CsX:-KNI3oV0qDKBHRhy0CsY:-351888853) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ARCodeAddEdit.cpp#L29)):*
> ```cpp
>     : wxDialog(parent, id, title, position, size, style), m_code(std::move(code))
> {
>   int space10 = FromDIP(10);
> ```

These should probably be made const.

---

*[Source/Core/DolphinWX/Cheats/ARCodeAddEdit.cpp, line 32 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI3n7EVN5J_2QOHiKn:-KNI3n7FfbYYxzQa3YrI:-853120239) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ARCodeAddEdit.cpp#L32)):*
> ```cpp
>   int space5 = FromDIP(5);
> 
>   wxBoxSizer* sEditCheat = new wxBoxSizer(wxVERTICAL);
> ```

Ditto about UI creation.

---

*[Source/Core/DolphinWX/Cheats/ARCodeAddEdit.cpp, line 44 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI3vfTlnAsZEjFk3N0:-KNI3vfTlnAsZEjFk3N1:-271224081) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ARCodeAddEdit.cpp#L44)):*
> ```cpp
>   EditCheatCode = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition,
>                                  wxDLG_UNIT(this, wxSize(240, 128)), wxTE_MULTILINE);
>   for (auto& op : m_code.ops)
> ```

this can be a const reference.

---

*[Source/Core/DolphinWX/Cheats/ARCodeAddEdit.h, line 13 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI1p3nM5rk1UxfYWI6:-KNI1p3nM5rk1UxfYWI7:-1813155575) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ARCodeAddEdit.h#L13)):*
> ```objc
> class wxTextCtrl;
> 
> class ARCodeAddEdit : public wxDialog
> ```

```cpp
class ARCodeAddEdit final : public wxDialog
```

---

*[Source/Core/DolphinWX/Cheats/ARCodeAddEdit.h, line 21 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI1Vfi8Y3buy9nYXu-:-KNI1VfkwzRuuEGmmiO9:251220491) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ARCodeAddEdit.h#L21)):*
> ```objc
>                 long style = wxDEFAULT_DIALOG_STYLE);
> 
>   const ActionReplay::ARCode GetCode() const { return m_code; }
> ```

A newline should follow after this line.

Also, was this intended to return by const reference? If not, then the first `const` isn't necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-:-KNI7OGToZ1-yzp8sf9b:1131936673)*

**Comment by EmptyChaos** [comment]
Review status: 0 of 21 files reviewed at latest revision, 18 unresolved discussions.

---

*[Source/Core/Core/ARDecrypt.cpp, line 484 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNHwIrsVh8Zc-Dqk7YT:-KNKHcDn8Mom-YBOxI5C:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/Core/ARDecrypt.cpp#L484)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> ```cpp
> ops->emplace_back(uCodes[i], uCodes[i + 1]);
> ```
> 
</details>
Done.

---

*[Source/Core/Core/ARDecrypt.cpp, line 494 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNHwOVLozF_lFtRD0CX:-KNKHckt9unmfeLTlmXd:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/Core/ARDecrypt.cpp#L494)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> ```cpp
> ops->emplace_back(uCodes[i], uCodes[i + 1])
> ```
</details>
Done.

---

*[Source/Core/DolphinWX/FrameTools.cpp, line 606 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNHwdwOuvmownouAMzT:-KNKHeYW5_K-dP2M5JUT:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/FrameTools.cpp#L606)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> Might want to consider adding a newline before this line and after the following call to this function that re-enables it to make them stand out more.
</details>
Done.

---

*[Source/Core/DolphinWX/ISOProperties.cpp, line 82 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNHx4K7xqOiKSnfSgIh:-KNKHfnbYD16Smg2GJxN:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/ISOProperties.cpp#L82)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> ```cpp
> class CheatWarningMessage final : public wxPanel
> ```
</details>
Done.

---

*[Source/Core/DolphinWX/ISOProperties.cpp, line 90 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI0q8He44KIbbhgqys:-KNKHhT9AlL0ocKRzdRT:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/ISOProperties.cpp#L90)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> Most of this UI creation code should likely be in its own CreateUI/CreateGUI function.
</details>
Done.

---

*[Source/Core/DolphinWX/ISOProperties.cpp, line 122 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNHxBPWGxWzSwuyJDdr:-KNKHie-LeOH9VAbHeVM:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/ISOProperties.cpp#L122)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> This should just be named `State`.
</details>
Done.

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.cpp, line 23 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI-RXdpCF4dyo1q1tY:-KNKHqq-Hc260NArxRey:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.cpp#L23)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> Ditto about UI creation.
</details>
Done.

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.cpp, line 41 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNHxoHQzz5rV0nqJ_pt:-KNKHrhZZc28CPkXVaBz:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.cpp#L41)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> This should probably be `const`
</details>
Done.

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h, line 28 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI1xwVKW-bRmgxI0s7:-KNKHuFBPf-5vsKy6i8R:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h#L28)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> This should just be named `Style`
</details>
Done.

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h, line 34 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI2KfTgS7YMHUUrvBE:-KNKHxCZWuxw3W00XRyA:616514560) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h#L34)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> This should use the Style enum as the type of `styles`. `0` should also be a defined style constant.
</details>
It's a bitset so I had to add bitwise operator overloads to make this work.

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h, line 44 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI2hkIAVCOahomUlR1:-KNKI5UzBUudVkw6DL1p:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h#L44)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> This should return as the Style enum type.
</details>
Done.

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h, line 45 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI25qDYGpPLgPw1Lkv:-KNKI5rV3D7Xv4fqXWt3:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h#L45)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> This parameter should use the Style enum as the type.
</details>
Done.

---

*[Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h, line 73 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI2dbCwrAbAkBcpXS7:-KNKI7RNAUzV_FjGLVvX:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ActionReplayCodesPanel.h#L73)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> This should likely be the `Style` enum type
</details>
Done.

---

*[Source/Core/DolphinWX/Cheats/ARCodeAddEdit.cpp, line 29 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI3oV0qDKBHRhy0CsX:-KNKI8M1QWctUctDhiSM:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ARCodeAddEdit.cpp#L29)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> These should probably be made const.
</details>
Done.

---

*[Source/Core/DolphinWX/Cheats/ARCodeAddEdit.cpp, line 32 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI3n7EVN5J_2QOHiKn:-KNKI9WM_9sPWPjx5MZR:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ARCodeAddEdit.cpp#L32)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> Ditto about UI creation.
</details>
Done.

---

*[Source/Core/DolphinWX/Cheats/ARCodeAddEdit.cpp, line 44 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI3vfTlnAsZEjFk3N0:-KNKIA_QzezJS9RzJsjN:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ARCodeAddEdit.cpp#L44)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> this can be a const reference.
</details>
Done.

---

*[Source/Core/DolphinWX/Cheats/ARCodeAddEdit.h, line 13 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI1p3nM5rk1UxfYWI6:-KNKIBdA3Z-f1xQQFOIf:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ARCodeAddEdit.h#L13)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> ```cpp
> class ARCodeAddEdit final : public wxDialog
> ```
</details>
Done.

---

*[Source/Core/DolphinWX/Cheats/ARCodeAddEdit.h, line 21 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048#-KNI1Vfi8Y3buy9nYXu-:-KNKICgq46VW1M4xTG10:366218494) ([raw file](https://github.com/dolphin-emu/dolphin/blob/729149d676c5a36206f856eda4b0059533b91b16/Source/Core/DolphinWX/Cheats/ARCodeAddEdit.h#L21)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> A newline should follow after this line.
> 
> Also, was this intended to return by const reference? If not, then the first `const` isn't necessary.
</details>
It was supposed to be a reference, I dropped the ampersand apparently (fixed).

I can't add a new line, clang-format keeps eating it (it aggressively removes white space around single line functions for some reason).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4048)*

**Comment by MaJoRoesch** [comment]
> Could you explain how you would want the disable functionality to work?

How you have it now with Configure Dolphin seems fine to me! Assuming it routes users to the configuration tab where Enable Cheats is?

**Comment by EmptyChaos** [comment]
@MaJoRoesch It opens the general configuration window on the first tab which is where the "Enable Cheats" checkbox is, yes.

**Comment by i30817** [comment]
Why not a checkbox instead of a shortcut to options?

**Comment by JosJuice** [comment]
@i30817 Like MaJoR says:

> By having an enable cheats checkbox here, what if a user wants to *disable* cheats later? They'll have no idea where it is!

Opening the properties window again won't let the user disable cheats, since the warning only shows up when cheats are disabled.

**Comment by RisingFog** [comment]
Any updates for this PR?

**Comment by EmptyChaos** [comment]
I believe this is done unless there are more review comments. It's been partially reviewed but needs to be finalized.

**Comment by shuffle2** [comment]
Good idea!

**Pull request merged**
