### PR TITLE
ActionReplay: Fix ISOProperties corrupting active code set

### PR DESCRIPTION
**Pull request by EmptyChaos**
Steps to reproduce:

1. Enable Cheats and start a game
2. Right-click a different game and click properties, look at the AR Codes tab
3. Open Tools > Cheat Manager. Note that the active codes are those of the second game, not the one that's actually running. [Alternatively, pause Dolphin under a debugger and inspect the "arCodes" and "activeCodes" globals in ActionReplay.cpp]

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3776)

### CODE REVIEW

**Comment by delroth** [comment]
@dolphin-emu-bot rebuild

**Comment by EmptyChaos** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
This change looks like it should work fine, but I would like someone to test that ISOProperties and Cheat Manager still handle AR codes properly, because parts of their code aren't especially nice and have led to problems in the past.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/Core/ActionReplay.cpp, line 107 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFUPNbUItd07z7j0Cua:-KFUPNbUItd07z7j0Cub:-1999383092) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d054e5fe03424e62361324a17bb2642cfef7c120/Source/Core/Core/ActionReplay.cpp#L107)):*
It feels odd to have this comment in LoadAndApplyCodes instead of LoadCodes, since this function doesn't actually parse anything on its own.

---

*[Source/Core/Core/ActionReplay.h, line 35 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFUPFKtE_F2hCPrgWu-:-KFUPFKumE6vaRVibhzS:-495247699) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d054e5fe03424e62361324a17bb2642cfef7c120/Source/Core/Core/ActionReplay.h#L35)):*
Both of these should use the name `globalIni` instead of `globalini` (capital I).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-:-KFUQ5S84NvJVWPISP5m:1497548862)*

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by BhaaLseN** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/Core/ActionReplay.h, line 35 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFUPFKtE_F2hCPrgWu-:-KFUbCeJXpFINRQZS_E8:-1826610348) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d054e5fe03424e62361324a17bb2642cfef7c120/Source/Core/Core/ActionReplay.h#L35)):*
And while you're at renaming things, could you look at `arCodes` (and perhaps the other statics; defined in `ActionReplay.cpp` at the top) to include the `s_` prefix? Your change helps a little wrt to the previous confusion (the local/parameter `_arCodes` assigning to a static variable called `arCodes`), but discoverability of what `arCodes` still needs more love; and we might aswell do it here in one go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776)*

**Comment by JosJuice** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/ActionReplay.h, line 35 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFUPFKtE_F2hCPrgWu-:-KFUcdOzAocLxbXOSbvr:-1530771663) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d054e5fe03424e62361324a17bb2642cfef7c120/Source/Core/Core/ActionReplay.h#L35)):*
Agreed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776)*

**Comment by EmptyChaos** [comment]
I need to ask how exactly this code is supposed to work from the user perspective? The current design seems confused; my current understanding is:

- ISOProperties modifies the INI to set AR codes that are in effect when a game is booted but does not alter the active codes of the game if it is currently running. (This is buggy, it resets codes when opened but not when closed)
- Cheat Manager modifies the active/inactive state of AR codes in the running game immediately when checking/unchecking boxes but does not modify the INI (Apply button does nothing).
 - Cheat Search is a singular exception which does add new codes to the INI.

Gecko Codes work differently:
- Turning on codes in ISOProperties only modifies the INI.
- Turning on codes in Cheat Manager modifies both the active state and the INI but only when you press Apply.

**Comment by skidau** [comment]
The AR codes should be changed to work in the same way as Gecko codes.  Runtime enabling of AR codes could make the game act strangely depending on the code and isn't possible with a real AR.

**Comment by EmptyChaos** [comment]
This got a little out of hand but I think I've fixed everything.

AR Codes now behave identically to Gecko Codes. Ticking/Unticking in Cheat Manager does nothing, pressing Apply saves them to the INI and updates the global state. ISOProperties modifies the INI but does not alter the global state.

As a new feature, ISOProperties will now track Cheat Manager. Changes made in Cheat Manager and Applied will cause the ARCode list in ISOProperties to refresh and update to reflect it.

---

Review status: 1 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/Core/ActionReplay.cpp, line 107 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFUPNbUItd07z7j0Cua:-KFbkhLi1nTK5Dv1aQAx:1758359711) ([raw file](https://github.com/dolphin-emu/dolphin/blob/48742d73a68686188683e82f6c264c9d33d8e4e7/Source/Core/Core/ActionReplay.cpp#L107)):*
Fixed.

---

*[Source/Core/Core/ActionReplay.h, line 35 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFUPFKtE_F2hCPrgWu-:-KFbkog83C2bLSJCWhb0:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/48742d73a68686188683e82f6c264c9d33d8e4e7/Source/Core/Core/ActionReplay.h#L35)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-:-KFbkswT8CYM9TAqenD_:-1351312654)*

**Comment by lioncash** [comment]
Review status: 1 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/Core/Core/ActionReplay.cpp, line 80 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFbmA8IIK5jUDW9Z0ow:-KFbmA8JLnvHb5Z0DiGJ:754319734) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a1c543e2129a35f54cc6fbe2aa030f82a2499002/Source/Core/Core/ActionReplay.cpp#L80)):*
Is a recursive mutex strictly necessary for this, and any other usages in the pull request?

Your commit that targets the thread issues doesn't actually *document* what was particularly fixed with regards to thread safety, and doesn't really elaborate on what was done/why you chose these to fix the issues found.

---

*[Source/Core/Core/ActionReplay.h, line 38 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFbqROfhb_9_kJt6UOe:-KFbqROhPWPTEncy8iq3:-1269731233) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a1c543e2129a35f54cc6fbe2aa030f82a2499002/Source/Core/Core/ActionReplay.h#L38)):*
There should be documentation as to what token's use is (and any other relevant information)

---

*[Source/Core/DolphinWX/Cheats/CheatsWindow.cpp, line 45 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFbmuNSnxjCaf7HcLEt:-KFbmuNTEWDsk_wz4Q_s:-825230202) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a1c543e2129a35f54cc6fbe2aa030f82a2499002/Source/Core/DolphinWX/Cheats/CheatsWindow.cpp#L45)):*
These should be fully uppercased (and `dol` can be extended to `DOLPHIN`)

---

*[Source/Core/DolphinWX/Cheats/CheatsWindow.cpp, line 267 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFbnGwE8SOO_yjjp2Yx:-KFbnGwFdm0zFV-l4TIE:1107162673) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a1c543e2129a35f54cc6fbe2aa030f82a2499002/Source/Core/DolphinWX/Cheats/CheatsWindow.cpp#L267)):*
You can just use the `m_checklistbox_cheats_list->GetCount()` call directly instead of using a separate variable, this is negligible in practice. 

---

*[Source/Core/DolphinWX/Cheats/CheatsWindow.h, line 71 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFbo0RnJyC0x0QNKV2m:-KFbo0RoKTqudBYt6nhG:-127743297) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a1c543e2129a35f54cc6fbe2aa030f82a2499002/Source/Core/DolphinWX/Cheats/CheatsWindow.h#L71)):*
Documentation of what the token specifically does would be beneficial for future readers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776)*

**Comment by EmptyChaos** [comment]
Review status: 1 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/Core/Core/ActionReplay.cpp, line 80 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFbmA8IIK5jUDW9Z0ow:-KFbrlB6wLJjpmmYey2Y:719690280) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a1c543e2129a35f54cc6fbe2aa030f82a2499002/Source/Core/Core/ActionReplay.cpp#L80)):*
The fact that both `RunAllActive` and `RunCode` are public and `RunAllActive` calls `RunCode` is why that needs to be recursive. I can rename `RunCode` to `RunCodeLocked` and create a new `RunCode` to lock the mutex then change the mutex to not be recursive. Or I could just remove RunCode from the public interface since there are currently no external consumers. I didn't know what to do with that so I went middle of the road with recursive_mutex, I do not think it's the best solution.

The commits don't have separate messages as I intend to squash most of them. The thread issue is that `RunAllActive` runs on the CPU Thread as a CoreTiming callback while all the access functions like `ApplyCodes`, `AddCode`, `GetCodeList` run on the Host Thread. Mutating a vector on one thread while it's being used in another can cause a reallocation and a dangling pointer dereference. Also `ARCode` contains a string and a vector so this problem applies to the elements in the vector which can be destructed or move constructed while in use as well.

---

*[Source/Core/Core/ActionReplay.h, line 38 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFbqROfhb_9_kJt6UOe:-KFbtB_QxJYQuj0KDS7d:635470490) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a1c543e2129a35f54cc6fbe2aa030f82a2499002/Source/Core/Core/ActionReplay.h#L38)):*
It's a `HANDLE`. Do you want me to typedef it or just put a comment?

I can also just move all that code into a `class CallbackList` since it's a generic pattern.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776)*

**Comment by EmptyChaos** [comment]
I went back to the drawing board on this and redid the architecture changes. Everything is simpler now.

---

Review status: 1 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/Core/Core/ActionReplay.cpp, line 80 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFbmA8IIK5jUDW9Z0ow:-KFn9dIUJnA0eBJOnrvK:864740165) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a1c543e2129a35f54cc6fbe2aa030f82a2499002/Source/Core/Core/ActionReplay.cpp#L80)):*
I've made RunCode private. I was originally thinking it could have been used to create a UnitTest or a Code Simulator for cheat developers but it would require a significant refactoring for that to work.

---

*[Source/Core/Core/ActionReplay.h, line 38 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFbqROfhb_9_kJt6UOe:-KFnA-7Fi83qjqELis6b:686018520) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a1c543e2129a35f54cc6fbe2aa030f82a2499002/Source/Core/Core/ActionReplay.h#L38)):*
I've eliminated this API entirely.

---

*[Source/Core/DolphinWX/Cheats/CheatsWindow.cpp, line 45 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFbmuNSnxjCaf7HcLEt:-KFc3ck-yzcDVE2YJIBQ:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a1c543e2129a35f54cc6fbe2aa030f82a2499002/Source/Core/DolphinWX/Cheats/CheatsWindow.cpp#L45)):*
Done.

---

*[Source/Core/DolphinWX/Cheats/CheatsWindow.cpp, line 267 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFbnGwE8SOO_yjjp2Yx:-KFc3_0Gb9Ccve4AedqJ:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a1c543e2129a35f54cc6fbe2aa030f82a2499002/Source/Core/DolphinWX/Cheats/CheatsWindow.cpp#L267)):*
Done.

---

*[Source/Core/DolphinWX/Cheats/CheatsWindow.h, line 71 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFbo0RnJyC0x0QNKV2m:-KFnA6mq9UXwRPW63onf:66021619) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a1c543e2129a35f54cc6fbe2aa030f82a2499002/Source/Core/DolphinWX/Cheats/CheatsWindow.h#L71)):*
I've eliminated it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-:-KFnAO0jWFfFYuvA1Nut:1283295325)*

**Comment by lioncash** [comment]
Review status: 1 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/ActionReplay.cpp, line 118 \[r6\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFw5qsof4YEpWIswKYn:-KFw5qspq3nHbi3S7SC6:-1394693237) ([raw file](https://github.com/dolphin-emu/dolphin/blob/19a58c9db7879cd33b1d56d8595845952a1acf38/Source/Core/Core/ActionReplay.cpp#L118)):*
```cpp
std::copy_if(codes.begin(), codes.end(), std::back_inserter(s_active_codes), [](const auto& code) {
    return code.active;
});
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776)*

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by EmptyChaos** [comment]
Review status: 1 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/ActionReplay.cpp, line 118 \[r6\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KFw5qsof4YEpWIswKYn:-KG0VH5KqzD3CHZGtSfI:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/19a58c9db7879cd33b1d56d8595845952a1acf38/Source/Core/Core/ActionReplay.cpp#L118)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776)*

**Comment by bb010g** [comment]
On the 5.0 milestone bump. Is something blocking this?

**Comment by EmptyChaos** [comment]
@bb010g I don't think this is going to be merged into Dolphin 5 at this point. I believe there's a string freeze in effect and this has a couple of string changes in it.

[Someone should probably remove the milestone tag]

**Comment by JosJuice** [comment]
I couldn't find anything that's affected by the string freeze in this PR. The only added or changed translated string seems to be the newly added "Number of Codes: ", but there is already another string saying the exact same thing, so it won't count as a new string for translation purposes. If there are any other changes to translated strings, please point them out.

**Comment by EmptyChaos** [comment]
@JosJuice There are 2 changes, I changed the capitalization "Number **Of** Codes" to "Number **of** Codes" which I believe gettext will treat as separate strings for localization, and I added a "Clear" button to the GUI. The clear button is probably covered by other occurrences elsewhere but I probably need to undo the capitalization change.

**Comment by JosJuice** [comment]
Thanks. I must've missed those two. There is indeed already a "Clear" string, so you should just need to change the capitalization of "Of" back (which seems to already be done in this version of the PR).

**Comment by delroth** [comment]
What's the status here? Has the string change been reverted? It's a fairly large change but I think it makes sense to have in 5.0.

**Comment by EmptyChaos** [comment]
@delroth I don't know of any changes that are needed currently. There should not be any string changes left in the code.

**Comment by delroth** [comment]
OK, if nobody has any objection I'll merge this in. If there are nits to tweak we can fix that in followup PRs.

**Comment by JosJuice** [comment]
Reviewed 2 of 14 files at r5.
Review status: 3 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/DolphinWX/ISOFile.cpp, line 185 \[r8\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KIwra8sIToczM1y-Ggp:-KIwra8sIToczM1y-Ggq:756330424) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f1dcc510900e65481ae9039588f858a7123a9c2f/Source/Core/DolphinWX/ISOFile.cpp#L185)):*
> ```cpp
> 	IniFile ini = SConfig::LoadGameIni(m_UniqueID, m_Revision);
> 	ini.GetIfExists("EmuState", "EmulationStateId", &m_emu_state, 0);
> 	ini.GetIfExists("EmuState", "EmulationIssues",  &m_issues,    std::string());
> ```

Aligning with spaces like this is kinda unnecessary, but it doesn't matter a lot.

---

*[Source/Core/DolphinWX/ISOFile.h, line 92 \[r8\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KIwqo-q6042nqigQAlb:-KIwqo-q6042nqigQAlc:893423081) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f1dcc510900e65481ae9039588f858a7123a9c2f/Source/Core/DolphinWX/ISOFile.h#L92)):*
> ```objc
> 	u8 m_disc_number;
> 
> 	std::string m_custom_name_db; // Custom title from title database
> ```

I would suggest writing something like "from titles.txt" instead of "from title database". It's usually not called a title database, so the comment can be unclear. Maybe the `_db` should be changed too, but I'm not sure to what...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776)*

**Comment by JosJuice** [comment]
Reviewed 2 of 6 files at r10.
Review status: 3 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/DolphinWX/ISOFile.cpp, line 185 \[r8\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KIwra8sIToczM1y-Ggp:-KIwyirS-b18ztpONTlK:-854268668) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f1dcc510900e65481ae9039588f858a7123a9c2f/Source/Core/DolphinWX/ISOFile.cpp#L185)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary>
> Aligning with spaces like this is kinda unnecessary, but it doesn't matter a lot.
</details>
There's still one extra space before `&m_issues`. (Now I'm really just nitpicking, though.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776)*

**Comment by Helios747** [comment]
Nitpicking is what keeps code clean

ish

**Comment by delroth** [comment]
@Helios747 no, automating the nitpicking is what keeps code clean, nitpicking manually is just wasting time and attention that could be spent on the code's logic if we had better automated tooling. :)

**Comment by JosJuice** [comment]
Reviewed 1 of 1 files at r11.
Review status: 3 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776)*

**Comment by RisingFog** [comment]
Anything remaining for this PR?

**Comment by BhaaLseN** [comment]
Review status: 3 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/DolphinWX/GameListCtrl.cpp, line 252 \[r11\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KJLjU9oz7IaDj-dtjXS:-KJLjU9oz7IaDj-dtjXT:1220012736) ([raw file](https://github.com/dolphin-emu/dolphin/blob/309d0e59f4697fdfc2763c7d3ee0075c514abe9b/Source/Core/DolphinWX/GameListCtrl.cpp#L252)):*
> ```cpp
> 	ScanForISOs();
> 
> 	Freeze();
> ```

It looks a bit odd to me that we _first_ `Freeze` and _then_ `Thaw`. In other frameworks (like WPF), you start unfrozen and freeze to prevent further changes (and in various cases, enable optimizations that couldn't be done while it was still unfrozen and thus mutable).
But maybe its just me wanting a comment here, dunno :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776)*

**Comment by lioncash** [comment]
*[Source/Core/DolphinWX/GameListCtrl.cpp, line 252 \[r11\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KJLjU9oz7IaDj-dtjXS:-KJLm1a-Wpg34M7Zn3mi:-893752673) ([raw file](https://github.com/dolphin-emu/dolphin/blob/309d0e59f4697fdfc2763c7d3ee0075c514abe9b/Source/Core/DolphinWX/GameListCtrl.cpp#L252)):*
<details><summary><i>Previously, BhaaLseN (BhaaL) wrote…</i></summary>
> It looks a bit odd to me that we _first_ `Freeze` and _then_ `Thaw`. In other frameworks (like WPF), you start unfrozen and freeze to prevent further changes (and in various cases, enable optimizations that couldn't be done while it was still unfrozen and thus mutable).
> But maybe its just me wanting a comment here, dunno :)
</details>
It's a hint for platform implementations of wx that allow halting display updates during potentially large insertions into a control (since technically every individual insert triggers a UI update). Documentation for it can be found [here](http://docs.wxwidgets.org/trunk/classwx_window.html#a15c678314cfc1d807196bc298b713ed3).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776)*

**Comment by BhaaLseN** [comment]
Review status: 3 of 17 files reviewed at latest revision, all discussions resolved.

---

*[Source/Core/DolphinWX/GameListCtrl.cpp, line 252 \[r11\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776#-KJLjU9oz7IaDj-dtjXS:-KJLnfw6Ifv3NmF2He2A:-1508501811) ([raw file](https://github.com/dolphin-emu/dolphin/blob/309d0e59f4697fdfc2763c7d3ee0075c514abe9b/Source/Core/DolphinWX/GameListCtrl.cpp#L252)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> It's a hint for platform implementations of wx that allow halting display updates during potentially large insertions into a control (since technically every individual insert triggers a UI update). Documentation for it can be found [here](http://docs.wxwidgets.org/trunk/classwx_window.html#a15c678314cfc1d807196bc298b713ed3).
</details>
Ok, so it's the other way around here (or rather, different use case). Disregard this then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3776)*

**Pull request merged**
