### PR TITLE
Properly check for missing netplay session name/region

### PR DESCRIPTION
**Pull request by JosJuice**

### CODE REVIEW

**Comment by BParks21** [comment]
@JosJuice This update is failing and not being applied correctly.

**Comment by JosJuice** [comment]
What do you mean?

**Comment by BParks21** [comment]
It ends with a fatal error using the updater.

**Comment by Mizoxman** [comment]
same issue, when this update tried to apply it downloaded over 2000 files and then had a fatal error. it installed just fine when I downloaded it manually though

**Comment by BParks21** [comment]
It also download 2000 files for me. Where did it store these?

**Comment by nf6429** [comment]
Same issue here, gets stuck on verify part of updater and then fatal error occurs.

**Pull request merged**
