### PR TITLE
Hotkeys fixes 2

### PR DESCRIPTION
**Pull request by degasus**
Fixes the double pressed buttons (eg fullscreen is broken)
Uses the new hotkey framework by default.

### CODE REVIEW

**Comment by ZephyrSurfer** [comment]
Fullscreen still isn't working :(

**Comment by degasus** [comment]
@ZephyrSurfer Are you sure you haven't the same key combination in both hotkey guis? So it will be triggered twice.

**Comment by Tilka** [comment]
Works for me after I loaded the default hotkeys and cleared the key shortcut for fullscreen.

**Comment by ZephyrSurfer** [comment]
Yes, Doesn't work If you are using absolutely default settings.

**Comment by ZephyrSurfer** [comment]
@degasus I figured it out.  
In the default setting in hotkey for Fullscreen It reads "Return" when it should read "RETURN"

**Comment by JMC47** [comment]
Once I replace that hotkey it works fine for me.

**Comment by ZephyrSurfer** [comment]
@JMC47 It's because we're using Windows. On other OSs it needs to be "Return"

**Comment by Jofzar** [comment]
Windows - with settings loaded from past builds, escape will still crash dolphin and make it freak out, same with pressing x on it within the bottom bar (star bar?) when its expanded.

Windows - With settings set to portable.txt (fresh) the escape button no longer does anything, but by click the x on the bottom bar expanded it works, there is then no crash.

**Comment by degasus** [comment]
Does all keys works now?
But you should reset all settings (eg portable.xt)

**Comment by Jofzar** [comment]
Only checked escape, but it now works on fresh settings seems fine to me.

On old settings still the same experience as shown before.

**Comment by DonelBueno** [comment]
Alt+Enter now works for entering full screen mode, but it doesn't work to go back to windowed mode once you go full screen.

**Pull request merged**
