### PR TITLE
Git Ignore: Add VisualStudio .APS and .LOG

### PR DESCRIPTION
**Pull request by Zexaron**
Generated a DolphinQt2.aps file. It's used by VS for performance.

Update: In some circumstances, Visual Studio may create .log files in some Externals, even if there is no errors.

### CODE REVIEW

**Comment by shuffle2** [comment]
when/where are the log files created?

**Comment by Zexaron** [comment]
They were generated in Externals/ed25519 and I think Externals/cubeb - But had no errors in them it seemed.

I was unloading DolphinWx and trying to compile without it, but there were some other errors at the time - that's what I remember distinctly, it was a lot of thing going on at once so I kinda brushed off the issue and then rolled back and re-enabled DolphinWx project and simply added those logs to the ignore.
 This was his was in the time when there was somewhat after the 15.7 updates and when some build errors were fixed by upstream already but some remained. I've since forgotten which branch I was working on that first made those appear. I have also then seen an option "make .log files" in the VS setting somewhere, but this long was after the fact, I never touched those settings before, and this was a clean install, it's not more than two weeks old.

But there's no log files now in any of the included repo directories, seems like it was a rare thing.

.log files get created normally with default setting in the Build directory, but these were since I navigated there my self, since it appeared to be standard output with no errors, I didn't keep them.

**Comment by Zexaron** [comment]
Didn't happen ever since.

**Comment by Zexaron** [comment]
I've seen the DolphinQt2.aps file appear while fiddling around with modifying the vxcproj and base.props, but I'm again not sure what exactly causes it.

**Pull request closed without merging**
