### PR TITLE
Metal Graphics Backend

### PR DESCRIPTION
**Pull request by stenzek**
**Off topic comments not related to testing and feedback will be strictly moderated.**

This branch introduces (yet another) backend to Dolphin: Metal. It is largely a work-in-progress, and several features are missing. The main motivation of developing this backend was to ensure the new videocommon interface design provided sufficient capabilities to move the majority of logic currently in the backends to common code.

Thus, the Metal backend has the abstract framebuffer and pipeline branches as prerequisites. All functionality is built using these primitives, avoiding any Metal-specific code where possible, outside of the derived abstract classes themselves.

Rather than mixing Objective C and C++, I used a C++ metal wrapper library (mtlpp). This in my opinion improves code clarity, and also has the benefit of handling object lifetimes, removing the need to sprinkle release and retain calls all over the source.

These two reasons are why the diff line count is huge. The backend itself is only around 5k lines. I'm not expecting anyone to review it just yet, at least not until the prerequisites are merged.

The changes to shadergen are rather intrusive, in some ways the code we were generating did not fit well with the Metal shading language. Perhaps there is a better way to support all the languages, aside from using an external translator.

Also, being a heavier language (C++-based), shader compilation "stutter" is likely worse than OpenGL, ubershaders and UID caches will be the solution here. But these will be implemented in common rather than the backend, so until that happens the backend will not support ubershaders.

Rough TODO list is as follows:
- [x] Support emitting MSL texture conversion shaders
- [x] Support emitting MSL vertex/pixel shaders
- [x] Basic rendering support in Metal backend
- [x] Abstract object implementations (texture/framebuffer/pipeline/staging texture)
- [x] Stream buffer implementation
- [x] State tracking
- [x] EFB to texture and RAM
- [ ] Design a solution to render lines/points without geometry shaders (VS instancing perhaps?)
- [x] Figure out a way to get uncapped framerates (present skipping based on notifications from display link?)
- [ ] Multisampling support
- [ ] Bounding box/SSBO support
- [x] Ubershader/async pipeline compilation - this will be implemented in common
- [ ] CPU EFB access (efb "peeks"/"pokes") - this will be implemented in common
- [ ] Post processing - this will be implemented in common
- [ ] Improve and optimize performance
- [ ] Bug fixes

### CODE REVIEW

**Comment by MayImilae** [comment]
So I was looking forward to getting some wonky early backend screenshots with Metal, but then...

aawww

Awww.... This is a mid-2012 MacBook Pro with Intel HD4000, which is the oldest GPU which supports Metal, but it supports it! But whenever I try to use this PR it just fails. :(

**Comment by microbug** [comment]
A more-or-less drop-in solution (as far as I know) has just become available: https://www.anandtech.com/show/12465/khronos-group-extends-vulkan-portability-with-opensource.

**Comment by stenzek** [comment]
Line count has grown even further due to now depending on 6 related branches. The actual backend itself is only +5000 lines.

I've also switched from generating MSL directly to generating GLSL, then SPIR-V, and using SPIRV-Cross to translate these shaders to MSL. This means that we don't need to significantly modify shadergen, as the changes there were quite intrusive.

This means the Metal backend now supports ubershaders, although performance could be terrible, I haven't really benchmarked it.

**Comment by stenzek** [comment]
@microbug I suspect that going via MoltenVK will be slower than this backend, as there is a considerable difference in the API versus Vulkan, which requires translation. But feel free to make a PR integrating MoltenVK and prove me wrong ;)

I did try for laughs a while back, and I couldn't get the swap chain functioning. Entirely possible I did something wrong though. Also you won't be able to get a higher frame rate than the screen refresh with MoltenVK.

**Comment by microbug** [comment]
@stenzek I'm nowhere near experienced enough to make a PR integrating MoltenVK. Just thought it might be useful, but a (faster) native Metal backend is of course preferable.

**Comment by christ776** [comment]
Hi @stenzek I'm following this PR and was wondering if this PR is going to be merged? Is it under active development? thanks!

**Comment by pizuz** [comment]
Just gave this build a spin. Looks quite stable.

Twilight Princess fails to render the mini-map and therefore runs at full speed. Also glitches galore (water overlay effects being opaque, sense mode producing a black screen).
Mario Galaxy runs quite well, aside lots of flickering and glitching textures.
Wind Waker runs well aside a few depth issues.

**Comment by MrGcGamer** [comment]
When will we see the metal backend get implemented in Dolphin? Or is something like a beta already out? (I have a MakBookPro mid2010 so Wind Waker runs terribly with opengl and I don’t know how to improve the performance and than I heard a Metal backend is in work)

**Comment by 8times9** [comment]
This pull request has been indefinitely delayed, but stenzek is working on a Vulkan backend for macOS using MoltenVK that should offer much improved performance compared to OpenGL.

**Comment by MrGcGamer** [comment]
Do you know how long it’s probably going to take until it’s finished?

**Comment by 8times9** [comment]
@MrGcGamer It's making good progress, you can follow it here: https://github.com/dolphin-emu/dolphin/pull/7039

**Comment by MrGcGamer** [comment]
One little question left is my mac supported for moltenvk (geforce 320m)?

**Comment by 8times9** [comment]
@MrGcGamer After some searching it seems your MacBook doesn't support Metal. Per this [article](https://www.macobserver.com/tmo/article/which-macs-support-os-x-el-capitans-metal) the cutoff for Metal support is the NVIDIA GTX 400 series GPUs. Your GPU is one generation too old. 

No Metal means no MoltenVK either (because that essentially wraps Vulkan to be run under Metal). 

So whether a native Metal backend or a MoltenVK backend were to be implemented, either way your computer would not support it.

I'm sorry. There's nothing the Dolphin developers can do about it.

**Comment by moda20** [comment]
This is probably not the best place to ask, but I am running dolphin on high Sierra (hackintosh) and i have a huge lag even with native resolution and minimum graphics. will the metal graphics backend help fix this ? and I still can't see it when choosing backends on config.

**Comment by cesar18pena** [comment]
@stenzek do you have an idea about how much time is PR is gonna by postponed? I try using this PR version with Metal backend, I tested the games Wind Waker and Metroid Prime 2 and I could see a big improvement(really big) in Mac OS X. 

This work is amazing, I hope you could complete this PR, even after Vulcan for MacOS to improve greatly gameplay in MAC.

PD: Are there specifics trainings or documentations that you recommend to understand and use C++ and Metal. To help and create a better dolphin for Mac users.

**Comment by stenzek** [comment]
MoltenVK is the solution for now. I simply don't have the time to maintain another backend, even if I did complete the missing features.

At some point in the future I may resurrect this branch, but for now it's dead. If someone does want to pick it up, there's an untested/rebased version in stenzek/metal.

**Pull request closed without merging**
