### PR TITLE
Fix Dolphin Icon

### PR DESCRIPTION
**Pull request by Pringo**
Okay, this should be the last time I do this. Update the Dolphin icon to fix icon distortion issues on Windows. Discussed previously in #3725 and #3726.

Versions Added:

- 32 x 32 @ 32 bit (this version taken directly from Sys/Resources/Dolphin.png this time)
- 48 x 48 @ 8 bit

Versions Removed:

- 64 x 64 @ 8 bit
- 64 x 64 @ 32 bit

New icon is 14.3 KB smaller than the original.

Should fix [Issue #8890](https://bugs.dolphin-emu.org/issues/8890).

Dolphin by default is loading Sys/Resources/Dolphin.png for its 32 x 32 icon on the taskbar. However in certain circumstances like opening a second window or pinning/unpinning Dolphin it is loading the 32 x 32 version of Dolphin.ico instead. As we previously didn't have a 32 bit 32 x 32 version in the .ico file we ended up with the poor looking 8 bit version. This new version of 32 bit 32 x 32 Dolphin.ico should be identical to the .png which should hopefully solve the issue once and for all.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3727)

### CODE REVIEW

**Comment by mathieui** [comment]
Please don't close and reopen pull requests each time; you can actually update the pull request by force-pushing to your git repository in the same branch after amending the commit (or making another one after removing the other). And it creates noise for people getting notified both by mail and in the irc channel.

**Comment by delroth** [comment]
And it makes it harder to track the status of PRs, it loses discussion history, and even more reasons. Don't do it.

**Comment by Pringo** [comment]
@mathieui @delroth Yes sorry I was being lazy and doing this through the web client and I don't think it has a way of letting me update files after the PR is made, hence making more PRs. I will try not to spam the repo in the future.

@JosJuice @MaJoRoesch Can you review this icon change? I tested it out and I think it should solve the previous issues that were happening although I don't know if this is the most elegant way of doing it.

**Comment by Alcaro** [comment]
> I don't think it has a way of letting me update files after the PR is made

It does. Go to https://github.com/Pringo/dolphin/ and edit whatever.

You can find the correct repo by going to the Commits tap on the PR, clicking one of your commits, and clicking the branch name (usually master or patch-1) below the commit message.

**Comment by JosJuice** [comment]
You can't update a PR using the web client unless you make additional commits, which we usually won't accept. That's one of the reasons you should be using a real git client.

I haven't tested that the issue is fixed, but the .ico file looks good. However, you should use the commit description to describe what/why you changed (with a force push, please :))

**Comment by JosJuice** [comment]
Don't put merge commits in your PRs.

**Comment by Pringo** [comment]
@JosJuice Sorry I'm trying to learn git right now and I don't know what I'm doing yet. If someone wants to take over this PR from me feel free.

**Comment by Alcaro** [comment]
You can use `git rebase` to get rid of that commit, then `git push -f` to upload it here.

It will [blow up](https://xkcd.com/1597/) if someone else changed the same files as you, but nobody did; if they did, this PR would show a merge conflict.

**Comment by Alcaro** [comment]
...you tried.

You can't rebase or force push from the web interface. You must clone the repo and use a desktop client.

**Comment by MaJoRoesch** [comment]
Minor whine - can you change the title of this PR to "Fix Dolphin Icon" or something? The name as is implies a new icon, and I keep doing double takes! >_<

**Comment by Pringo** [comment]
@MaJoRoesch Fixed.

I will try to correct the rest of this PR when I have some time.

**Comment by JosJuice** [comment]
Are you making progress, or do you want me to take over?

**Comment by JosJuice** [comment]
I will make a new PR if there's no response in a week.

**Comment by Pringo** [comment]
@JosJuice Go for it. I was trying to go through some git tutorials but got busy with other work. At this point it would probably be easier to hand this PR off to someone who knows what they're doing.

**Comment by JosJuice** [comment]
The new PR is #3754.

**Pull request closed without merging**
