### PR TITLE
Externals: Update libusb to version 1.0.20

### PR DESCRIPTION
**Pull request by Pringo**
Trying to update libusb but not 100% sure what I'm doing here. Let me know if I need to change anything.

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4150)

### CODE REVIEW

**Comment by Pringo** [comment]
Doesn't seem to be compiling on Windows. Is https://github.com/dolphin-emu/dolphin/commit/00afa2a3287c2c418ac8ac7739712e8d0b7e66c9 still required?

**Comment by lioncash** [comment]
Shouldn't be. VS2015 compatibility was added a few months after shuffle2 opened the the referenced pull request on libusb's github page ([relevant commit adding support](https://github.com/libusb/libusb/commit/a34ba28b40d901afeeca084e6b7043fcf95cd935))

You may want to also indicate why you're updating the library in the commit message.

**Comment by Pringo** [comment]
This is mostly just to see if updating libusb helps with Wii U adapter ghost inputs or not. I tried reverting the patch but now it says its not compiling on Windows again...

**Comment by ZephyrSurfer** [comment]
The patches for compiling this with VS 2015 were included after 1.0.20.

You could see try against libusb master for testing out if the issue is resolved there.

**Comment by clinchergt** [comment]
You could probably just delete the last two commits and force push to make this branch look prettier.

Also, it's entirely possible that 1.0.21 gets released soon, otherwise maybe update to 1.0.21-rc3?

**Comment by Pringo** [comment]
Okay I deleted the revert commits. Can someone take a look at this to see if everything is right?

**Comment by JMC47** [comment]
Oddly enough, this fixes I-SPY Spooky Mansion's crash for me.  Which was broken by the last LibUSB update... so I guess this makes sense.

**Comment by phire** [comment]
LGTM

**Comment by Pringo** [comment]
Could someone review this? I accidentally pushed this to my master branch so I would like to get it dealt with.

**Comment by shuffle2** [comment]
unfortunately this is a bit of a pain in the ass to review on the web.
@Pringo do you know how it interacts with https://github.com/dolphin-emu/dolphin/pull/4195 and the recent changes to build this code on OSX (might need to rebase for that...)?

**Comment by leoetlino** [comment]
This seems to only touch Externals so there shouldn't be any conflicts with other PRs

#4195 simply adds a define for `__LIBUSB__` for Windows builds and does not touch Externals, so it should be fine too.

**Comment by mimimi085181** [comment]
I think it might be nice to be able to compare the different libusb versions with the passthrough bluetooth feature, to see if the libusb update fixes or breaks things. So maybe merge the passthrough 1st?

**Comment by Pringo** [comment]
@shuffle2 I have no idea how this PR interacts with those changes. If this one needs further work could someone take it over for me?

**Pull request merged**
