### PR TITLE
CMake: glslang cleanups

### PR DESCRIPTION
**Pull request by ligfx**

### CODE REVIEW

**Comment by ligfx** [comment]
@Orphis

**Comment by stenzek** [comment]
I believe #5019 covers some of these.

**Comment by Orphis** [comment]
Have you tried updating gslang and using their current CMake files?

**Comment by ligfx** [comment]
@Orphis yeah I looked into it, it still lacks a few things: glslang#876

**Comment by Orphis** [comment]
Probably best to wait for you to fix your patch and wait for feedback on it then.

**Comment by ligfx** [comment]
That sounds fine to me, I'll see what they say.

**Pull request closed without merging**
