### PR TITLE
Improved gecko codehandler

### PR DESCRIPTION
**Pull request by gamemasterplc**
Source code for codehandler is in docs folder of repository. The codehandler is based off codehandleronly.bin The improved codehandler has improved button activator support due to cache invalidation. Also has the ability to use more lines before Dolphin crashes/freezes.

### CODE REVIEW

**Comment by mimimi085181** [comment]
This seems to work better with button activated codes than the regular codehandleronly.bin. I have tested it with a jump code from Wind Waker PAL:
Super Roll Jump (Press R) [Ralf]
041125A4 41820014
2C3F501E FF000030
041125A4 60000000
E2000001 80008000

Which works well with the codehandler.bin from this repository and doesn't work at all with odehandleronly.bin(taken from NeoGamma).

If you want more test results, i suggest to get somebody to build your pr, and then post about it on the forums in the general section.

**Comment by mimimi085181** [comment]
About the pr itself, can you squash all source related commits into one? Other than that, it should probalby state in its source file that it's based on the codehandleronly.s file from Gecko OS, so exchanges the debugger function for more code lines. I would like that comment if i were to come across this file.

**Comment by JMC47** [comment]
I tested this and a bunch of Gecko Codes that previously didn't work now work, especially button based ones.

I was given a list of codes to test, and they all worked except the reverse lap counter on Mario Kart Double Dash, which, I didn't understand exactly what it did anyway...

**Comment by gamemasterplc** [comment]
that one just flips the direction the lap counter moves when crossing the finish line

**Comment by JMC47** [comment]
I got it working.  All the codes you gave me work.

LGTM!

**Comment by JMC47** [comment]
@dolphin-emu-bot rebuild

**Comment by valcheeky** [comment]
Hello, this PR introduces stutter in Zelda Wind Waker with the Widescreen Gecko hack from the wiki enabled.
Framerate drops to the low 20s for less than 1 second, it happens randomly when walking around or when just idling.
PR #5715 works perfectly.

**Comment by blubberdiblub** [comment]
@valcheeky you may want to report that on the issue tracker:
https://bugs.dolphin-emu.org/projects/emulator/issues

**Comment by retrobenny** [comment]
Here is the actual code I was talking about in the forums,got it confused with replacement codes.
Its the Seagull Size Mod code for PAL Wind Waker which is claimed to not work in Dolphin.
Wished I had an NTSC port of the code to test out.

Used GCNcrypt for you to save on the trouble and properly removed the first 020454E2 18000000  line.
Code gotten from the thread on Gamehacking DOT org in this link.

http://gamehacking.org/vb/threads/10755-GCN-tLoZ-The-Wind-Waker-PAL-AR-codes-by-CosmoCortney

Seagull Size modifier (all) [CosmoCortney]
8A3F5018 00000001
04E4B900 40000000
04E49E60 40000000
04E4B080 40000000
00000000 40000000
8A3F5018 00000002
04E4B900 40400000
04E49E60 40400000
04E4B080 40400000
00000000 40000000
8A3F5018 00000004
04E4B900 40800000
04E49E60 40800000
04E4B080 40800000
00000000 40000000
8A3F5018 00000008
04E4B900 3F800000
04E49E60 3F800000
04E4B080 3F800000
00000000 40000000
* dPad left: big
* dPad right: bigger
* dPad down: biggest
* dPad up: default
* does not work with dolphin <-"bold red text"
"broken image"

Please test this code,honestly not sure if it works instantly on the same area,try it immediately first then try changing the size and go between areas via Grandma or any other home at Offset Island then look up at the usual place they appear up high near the lookout.

**Comment by Jrascon** [comment]
I'm having the same issue as valcheeky, but it's in Zelda Twilight Princess. PR #5715 works perfectly and this change "apparently" caused the issue.

**Pull request merged**
