### PR TITLE
Cleanup usage of atomic/threadsafe functions

### PR DESCRIPTION
**Pull request by magumagu**
We shouldn't use atomic/threadsafe functions when they aren't necessary; it's misleading at best.

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
Why was PowerPCState::Exceptions using atomics anyway?

**Comment by magumagu** [comment]
Looks like 8d6f98439e9ce3c245e18fe5a61605264cbe63fd changed PowerPCState::Exceptions... some sort of misguided attempt to fix dual-core.  These days, we use ScheduleEvent_Threadsafe when the GPU thread needs to asynchronously cause an interrupt.

**Comment by magumagu** [comment]
Thanks for spotting that; fixed.

**Comment by Mullin** [comment]
You're welcome

**Comment by magumagu** [comment]
Ping.

**Comment by lioncash** [comment]
Looks good to me.

**Comment by jonaand** [comment]
i've used  program CPU-Control to force dolphin use my 4 cores of cpu, and now use 4 core :)

**Comment by Linktothepast** [comment]
I am getting this issue every time i close a game in dolphin after this merge:
http://prntscr.com/644wsy
Should i write an issue report?

**Comment by magumagu** [comment]
Yes, please; include your full configuration, and assign it to me.

**Comment by psennermann** [comment]
On my system this merge has caused a 10% speed slowdown

**Comment by magumagu** [comment]
Does PR #2038 help the regression any?

**Comment by psennermann** [comment]
Since it's not merged and there's no build to try, at the moment I am not able tell...

**Comment by psennermann** [comment]
Unfortunately it doesn't help...

**Comment by magumagu** [comment]
Okay, then I'm not sure what's going on.  Please file an issue report.

**Pull request merged**
