### PR TITLE
Move "Background Input" out of individual controller configurations

### PR DESCRIPTION
**Pull request by ligfx**
Right now it's confusing that the setting is available on each individual configuration. 

This patch moves it to the main Controller Config dialog to make it obvious that it's a global setting:

screen shot 2017-02-07 at 6 32 37 pm

### CODE REVIEW

**Comment by degasus** [comment]
Oh, I wonder why this PR wasn't merged. It is a streight forward improvement. But with a few conflicts now...

**Comment by ligfx** [comment]
@degasus Glad you like it! I've rebased on current master and fixed the conflicts.

**Comment by Helios747** [comment]
Sounds fine to me. Sorry this fell through the cracks.

@MayImilae Do you have any concerns with adding more options to the main input UI? I'm all for anything that simplifies the already dense controller config UI

**Comment by ligfx** [comment]
Bump

**Pull request merged**
