### PR TITLE
D3D: Use the correct format when resolving the EFB depth texture.

### PR DESCRIPTION
**Pull request by Armada651**

### CODE REVIEW

**Comment by delroth** [comment]
What does this fix? Why?

**Comment by Armada651** [comment]
@delroth It should fix [Issue 8247](https://code.google.com/p/dolphin-emu/issues/detail?id=8247).

The reason this issue exists is because `GetResolvedDepthTexture()` was incorrectly implemented at first where it returned the color texture instead. This was not a problem since the function was never called. When I discovered the flaw I change it to return the depth texture, but I forgot to change the format.

PR #2023 is the first PR to actually call this function.

**Comment by delroth** [comment]
OK. If user testing reports that this is fixed, feel free to merge.

@dolphin-emu-bot allowmerge

**Comment by mrgreywater** [comment]
Shouldn't it be DXGI_FORMAT_R24_UNORM_X8_TYPELESS?

**Comment by Xcedf** [comment]
Not working, started a new game and can't scan anything in AA mode

**Comment by Armada651** [comment]
@mrgreywater I don't know why you deleted your comment, but yes it should've been `DXGI_FORMAT_R24_UNORM_X8_TYPELESS`.

**Comment by mrgreywater** [comment]
@Armada651 I removed it because the depth texture itself uses R24G8, and It was more like a guess. Also the depth isn't correct anyways in the D3D renderer, I compared it to the software renderer and it was quite different in some occassions, both the current and inverted version.

**Comment by Armada651** [comment]
@delroth I'll make another PR to fix Issue 8247, but I think this one should be merged regardless since the type is incorrect any way you look at it.

**Pull request merged**
