### PR TITLE
Android: Long press a setting to reset it

### PR DESCRIPTION
**Pull request by JosJuice**
This is particularly important for game INIs, where a setting being unset is not the same as it being set to the default value.

### CODE REVIEW

**Review by Ebola16 — COMMENTED** [review]
- What do you think about adding a confirmation dialog after long pressing a setting to clear it? We don't want users to accidentally clear a setting when attempting to scroll.
- "Reset Paths to Default Settings" is probably unnecessary with this PR.

**Comment by JosJuice** [comment]
> What do you think about adding a confirmation dialog after long pressing a setting to clear it? We don't want users to accidentally clear a setting when attempting to scroll.

I was hoping that setting the setting back to what it was would be quick and easy, but I suppose it's not so easy if you don't remember what you have it set to. I'll add a confirmation dialog.

> "Reset Paths to Default Settings" is probably unnecessary with this PR.

I would be pretty sure about removing it if it wasn't for the low discoverability of this new feature, but the way things are, I'm not. But then again, if someone really wants to reset a path and there isn't a visible reset button, I guess long pressing might be one of the first things they try...? The ability to reset paths was added by request from me, so I'm not sure how often people actually want to use it. With this in mind, what do you think?

**Comment by Ebola16** [comment]
> I would be pretty sure about removing it if it wasn't for the low discoverability of this new feature, but the way things are, I'm not. But then again, if someone really wants to reset a path and there isn't a visible reset button, I guess long pressing might be one of the first things they try...? The ability to reset paths was added by request from me, so I'm not sure how often people actually want to use it. With this in mind, what do you think?

How about adding "Long press a setting to reset it." as the first line of the GameTDB.com thanks header and removing "Reset Paths to Default Settings"? That header is very visible.

**Comment by JosJuice** [comment]
Sounds fair. (Though maybe I should expose the cover downloading setting first like I've been planning to so that I can move the GameTDB.com acknowledgement out of the main screen... So it might take a little while before I continue with this PR.)

**Comment by Ebola16** [comment]
> Sounds fair. (Though maybe I should expose the cover downloading setting first like I've been planning to so that I can move the GameTDB.com acknowledgement out of the main screen... So it might take a little while before I continue with this PR.)

Adding a string above the GameTDB.com thanks message shouldn't need to block this PR but if you want to wait that's fine too.

**Comment by JosJuice** [comment]
Yeah, I just figured that this PR wasn't important enough that I can't wait until later in order to make things a bit cleaner.

**Comment by leoetlino** [comment]
This seems to conflict with a PR that was recently merged (#9154).

**Comment by JosJuice** [comment]
Rebased. But I'm still waiting for PR #9146.

**Comment by JosJuice** [comment]
This PR should be good to go now.

**Comment by Ebola16** [comment]
Are you still going to remove "Reset Paths to Default Settings" in the paths settings?

**Comment by JosJuice** [comment]
Oh, oops, I totally forgot about that. I've done it now.

**Comment by Ebola16** [comment]
There's some strange behavior going on with wiimote extensions, probably because they're a legacy setting. Clearing the setting defaults the extension to "None" but it should be "Nunchuk" after saving.

Also, change the extension to something else, back out of that extensions' submenu, then clear the extension. It now displays the new value as the initial extension but always saves as "None".

And custom game setting Wiimote extensions do not change after saving.

**Comment by JosJuice** [comment]
The Wii Remote extension setting is a terrible hack... Are all of those problems new for this PR, or do some of them also exist in master?

**Comment by Ebola16** [comment]
Ah, they're not due to this PR but they weren't exposed since settings couldn't be deleted from the UI. GameCube Input settings have these problems too. Perhaps it would be a good idea to disable this feature with legacy settings?

**Comment by JosJuice** [comment]
This feature should work fine with normal legacy settings, it's just that the extension setting is particularly messed up. Maybe I should try and see if it's possible to make a PR that makes the extension setting work sensibly...

**Comment by Ebola16** [comment]
Both `gcPadSetting` and and `wiimoteSetting` appear to have problems and are legacy settings.

With `gcPadSetting` for GameCube Controller 1 set to default value of "Emulated", clearing the setting visually disables it. After saving and returning to the setting, it now displays as "Emulated" again.

**Comment by JosJuice** [comment]
The latest commit should fix those two (but not the extension setting).

**Review by Ebola16 — APPROVED** [review]
Although that does fix those problems, I still think the now-exposed extension issue is annoying enough to warrant disabling it for that setting and adding a TODO. If people are using the wrong extension, controller input would partially work (Nunchuck overlay without Nunchuck extension) or move in the wrong direction (horizontal vs vertical Wiimote). A bug that can have varying symptoms will confuse users.

But then again a bug that is somewhat obscure and can be fixed by changing the controller isn't the worst thing in the world. If you feel strongly about not disabling this feature for the extensions feel free to merge.

**Comment by JosJuice** [comment]
I'd rather wait with merging this and try to fix the extension issue properly in a separate PR.

**Comment by Ebola16** [comment]
If that's the case having the Wii Overlay PR merged before fixing the extension issue may help too. Although it uses some hacks to work around the extension problems, it also fixes some bugs that can mimic an incorrect extension (especially overlay vs controller mismatches). I'll be reabasing it soon.

**Comment by JosJuice** [comment]
I've created the extension fix as PR #9170. I don't believe I need anything from the Wii overlay PR for what I'm doing.

**Comment by JosJuice** [comment]
That PR is now merged, so this should be ready to go now. (I've rebased this on latest master for easier testing.)

**Comment by Ebola16** [comment]
@dolphin-emu-bot rebuild

**Review by Ebola16 — CHANGES_REQUESTED** [review]
On startup the latest version of this PR:
```
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=500, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {org.dolphinemu.dolphinemu.debug/org.dolphinemu.dolphinemu.ui.main.MainActivity}: java.lang.IllegalStateException: DirectoryInitialization has to run at least once!
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4633)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4675)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.IllegalStateException: DirectoryInitialization has to run at least once!
        at org.dolphinemu.dolphinemu.utils.DirectoryInitialization.getUserDirectory(DirectoryInitialization.java:234)
        at org.dolphinemu.dolphinemu.features.settings.utils.SettingsFile.getSettingsFile(SettingsFile.java:293)
        at org.dolphinemu.dolphinemu.activities.EmulationActivity.updateWiimoteNewController(EmulationActivity.java:199)
        at org.dolphinemu.dolphinemu.activities.EmulationActivity.updateWiimoteNewIniPreferences(EmulationActivity.java:192)
        at org.dolphinemu.dolphinemu.utils.DirectoryInitialization.init(DirectoryInitialization.java:81)
        at org.dolphinemu.dolphinemu.utils.DirectoryInitialization.lambda$start$0(DirectoryInitialization.java:61)
        at org.dolphinemu.dolphinemu.utils.-$$Lambda$DirectoryInitialization$4OznpFpwaL6xHX0CXMVAakC3Y5Q.run(Unknown Source:2)
        at org.dolphinemu.dolphinemu.utils.DirectoryInitialization.start(DirectoryInitialization.java:61)
        at org.dolphinemu.dolphinemu.ui.main.MainActivity.onRequestPermissionsResult(MainActivity.java:228)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7941)
        at android.app.Activity.dispatchActivityResult(Activity.java:7763)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4626)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4675) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7073) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
```

I won't be able to look at further changes until late today / tomorrow.

**Comment by JosJuice** [comment]
Looks like an issue in master caused by the merge of PR #9193.

**Comment by Ebola16** [comment]
Ah, good catch.

**Comment by JosJuice** [comment]
Should be fixed in #9266 (once I get master to compile again...)

**Comment by Ebola16** [comment]
When installing Dolphin, the "Wii Remote 1" extension is initially set to "Nunchuk". The default value is "None". In custom game settings, "Wii Remote 1" extension is initially set to the default "None". I think most games don't care about having a Nunchuk connected so what do you think about changing the default extension to "Nunchuk"?

**Comment by JosJuice** [comment]
I'm only matching the behavior of how the C++ code works. If an INI does not specify an extension, the extension is parsed as None. Besides, if this was changed recently, I believe it was done by PR #9170 and not this PR.

The proper behavior for game settings would probably be to not show the default value for things that are not set in the game INI, but rather the value which is set in the global INI, but... well, I believe I've gotten that working for settings that use the new config system, but the input config is not hooked up to that at all on either the C++ side or the Java side. So I'm not sure if there's any good way to accomplish that.

**Review by Ebola16 — APPROVED** [review]
I'm ok with revisiting this low importance issue in a future PR.

**Review by leoetlino — APPROVED** [review]

**Pull request merged**
