### PR TITLE
[Android] Add UI support for newly-implemented DolphinBar support

### PR DESCRIPTION
**Pull request by sigmabeta**
Builds on top of #3593 to allow manipulation of necessary settings through the UI.

"Continuous scanning" will be removed once a non-hacky method of always-enabling it is put in.
"Wiimote Speaker" will be moved to the Wiimote menu once #3583 is merged.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3603)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java, line 58 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603#-K9t4gVZbuhFKaNQcUYY:-K9t4gV_bgdazje6Mnli:-1864350142) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3bb1adaf29afd5da514e60817a00203de9ab43f/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java#L58)):*
Is the fallthrough here intentional?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603)*

**Comment by sigmabeta** [comment]
Review status: 0 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java, line 58 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603#-K9t4gVZbuhFKaNQcUYY:-K9tMIWHQEXVaAx7otxE:1653304921) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3bb1adaf29afd5da514e60817a00203de9ab43f/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/main/MainPresenter.java#L58)):*
Nope, I'm just shitty

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603)*

**Comment by BhaaLseN** [comment]
Reviewed 8 of 9 files at r1, 18 of 19 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsActivityView.java, line 83 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603#-K9vP4yYiEuxetm0R7ET:-K9vP4yZmo5eAlErnuId:221107276) ([raw file](https://github.com/dolphin-emu/dolphin/blob/eabd71df69a93d41e9664d28a371c504c340662b/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsActivityView.java#L83)):*
"by a containing Fragment tell"? Some words are missing (or extra) here, this line doesn't make sense right now o_O
The one in SettingsFragmentView.java makes more sense (which I believe should be related to this one)

---

*[Source/Android/app/src/main/res/values/arrays.xml, line 165 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603#-K9vQFcwNGYFWq_28tDN:-K9vQFcxZWvSH9F9cmDX:1037815291) ([raw file](https://github.com/dolphin-emu/dolphin/blob/eabd71df69a93d41e9664d28a371c504c340662b/Source/Android/app/src/main/res/values/arrays.xml#L165)):*
Is this quoted on purpose?

---

*[Source/Android/app/src/main/res/values/strings.xml, line 99 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603#-K9vQKSFXKrjLfiEoXhb:-K9vQKSFXKrjLfiEoXhc:-1450504182) ([raw file](https://github.com/dolphin-emu/dolphin/blob/eabd71df69a93d41e9664d28a371c504c340662b/Source/Android/app/src/main/res/values/strings.xml#L99)):*
Might help to provide a reason why they shouldn't be moved.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603)*

**Comment by Sonicadvance1** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603)*

**Comment by Sonicadvance1** [comment]
Reviewed 15 of 19 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603)*

**Comment by sigmabeta** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsActivityView.java, line 83 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603#-K9vP4yYiEuxetm0R7ET:-KA1oBxaLqIiBJFQbBsd:506265426) ([raw file](https://github.com/dolphin-emu/dolphin/blob/eabd71df69a93d41e9664d28a371c504c340662b/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsActivityView.java#L83)):*
Will fix this

---

*[Source/Android/app/src/main/res/values/arrays.xml, line 165 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603#-K9vQFcwNGYFWq_28tDN:-KA1oFEn5JP-qPOFemyo:-897735808) ([raw file](https://github.com/dolphin-emu/dolphin/blob/eabd71df69a93d41e9664d28a371c504c340662b/Source/Android/app/src/main/res/values/arrays.xml#L165)):*
Will fix this, but oddly the quotes don't show up at runtime.

---

*[Source/Android/app/src/main/res/values/strings.xml, line 99 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603#-K9vQKSFXKrjLfiEoXhb:-KA1oHmSPWSi_ulOCspD:-1485640932) ([raw file](https://github.com/dolphin-emu/dolphin/blob/eabd71df69a93d41e9664d28a371c504c340662b/Source/Android/app/src/main/res/values/strings.xml#L99)):*
Will fix this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603)*

**Comment by Sonicadvance1** [comment]
Reviewed 1 of 19 files at r2, 1 of 4 files at r4.
Review status: 24 of 27 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603)*

**Comment by Sonicadvance1** [comment]
Reviewed 2 of 4 files at r4.
Review status: 26 of 27 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603)*

**Comment by Sonicadvance1** [comment]
Merge conflict. Can't merge.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603#-:-KA2WtcEDkRQQ6YsodiM:-643585238)*

**Comment by Sonicadvance1** [comment]
Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603)*

**Comment by Sonicadvance1** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3603)*

**Pull request merged**
