### PR TITLE
Common: asterisks go against the type name

### PR DESCRIPTION
**Pull request by mathieui**
not the variable name

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3544)

### CODE REVIEW

**Comment by delroth** [comment]
Please be more consistent in applying this so we can avoid followup commits. I've seen some missing and I've only looked at the few lines surrounding each of your changes.

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/Core/Common/Arm64Emitter.h, line 101 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3544#-K8_jQyKBXZISe6yB7mc:-K8_jQyL2PTgoGC3nwQQ:8994859) ([raw file](https://github.com/dolphin-emu/dolphin/blob/78aa398e7c09adc4fb9318a4c497e8fd1bcd58ba/Source/Core/Common/Arm64Emitter.h#L101)):*
What about these ones?

---

*[Source/Core/Common/StringUtil.cpp, line 191 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3544#-K8_jkqwLRooassECoJZ:-K8_jkqwLRooassECoJ_:604761958) ([raw file](https://github.com/dolphin-emu/dolphin/blob/78aa398e7c09adc4fb9318a4c497e8fd1bcd58ba/Source/Core/Common/StringUtil.cpp#L191)):*
What about these?

---

*[Source/Core/Common/SymbolDB.h, line 98 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3544#-K8_joxf2x90hXH1Dp-5:-K8_joxf2x90hXH1Dp-6:604761958) ([raw file](https://github.com/dolphin-emu/dolphin/blob/78aa398e7c09adc4fb9318a4c497e8fd1bcd58ba/Source/Core/Common/SymbolDB.h#L98)):*
What about these?

---

*[Source/Core/Common/x64Analyzer.cpp, line 7 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3544#-K8_jubPMvwznexRI1hw:-K8_jubPMvwznexRI1hx:1107368439) ([raw file](https://github.com/dolphin-emu/dolphin/blob/78aa398e7c09adc4fb9318a4c497e8fd1bcd58ba/Source/Core/Common/x64Analyzer.cpp#L7)):*
You're missing one of two.

---

*[Source/Core/Common/x64Analyzer.h, line 44 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3544#-K8_jxfLh7WVdTzSvZBo:-K8_jxfLh7WVdTzSvZBp:1352270674) ([raw file](https://github.com/dolphin-emu/dolphin/blob/78aa398e7c09adc4fb9318a4c497e8fd1bcd58ba/Source/Core/Common/x64Analyzer.h#L44)):*
Missing one of two.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3544#-:-K8_k--_kYkrRaSR0N9p:2022021814)*

**Comment by mathieui** [comment]
It should be a bit more complete now, I’m doing ampersands in the next commit

**Comment by delroth** [comment]
Reviewed 19 of 33 files at r2, 17 of 17 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Source/Core/Common/Arm64Emitter.h, line 736 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3544#-K8_wxuZAbloIQ0bp2OK:-K8_wxu_sDMlFl63FEgd:-285509438) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f15ffda5a7518cb87a09f301deaeffab0723ec27/Source/Core/Common/Arm64Emitter.h#L736)):*
This still has a space.

---

*[Source/Core/Common/Hash.cpp, line 235 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3544#-K8_xwVkn2gZJe4mWHho:-K8_xwVlAD2BBKb3dnzJ:-1764899718) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f15ffda5a7518cb87a09f301deaeffab0723ec27/Source/Core/Common/Hash.cpp#L235)):*
Extra space within the cast.

---

*[Source/Core/Common/ucrtFreadWorkaround.cpp, line 38 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3544#-K8_xL4eYyTVnJTtQj6n:-K8_xL4ffjpojfzuvtA0:1629167140) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f15ffda5a7518cb87a09f301deaeffab0723ec27/Source/Core/Common/ucrtFreadWorkaround.cpp#L38)):*
Extra space in the cast here too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3544)*

**Comment by delroth** [comment]
LGTM

---

Reviewed 5 of 6 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3544#-:-K8aE81iUIMLvmzr73eV:676834233)*

**Pull request merged**
