### PR TITLE
Externals: Update MoltenVK to SDK version 1.1.101.0

### PR DESCRIPTION
**Pull request by stenzek**
What the title says. The changelog would suggest that the new version may improve performance, as well as introduce some missing features (e.g. multisampled 2D texture arrays, needed for our MSAA implementation).

Note, the mac builder is currently down, so builds won't be available for testing. If you want to manually test it yourself, you can download the latest SDK from https://vulkan.lunarg.com/sdk/home#mac, and replace `Dolphin.app/Contents/Frameworks/libvulkan.dylib` with `vulkansdk-macos-1.1.97.0/MoltenVK/macOS/dynamic/libMoltenVK.dylib`

### CODE REVIEW

**Comment by cesar18pena** [comment]
I tested the new version `1.1.97.0` with multiples games of Wii and games and everything seen to work fine. I place the list of the games that I used to test.

- Gamecubes: 
Super Smash Bros Melee
Legend of Zelda Wind Waker 
Metroid Prime 2
Super Monkey Ball 2
Star Fox Adventures

- Wii:
Legend of Zelda Twilight Princess
Super Mario Galaxy

Image of playing Wind Waker
screen shot 2019-02-06 at 10 38 33 pm

**Comment by stenzek** [comment]
Our mac buildbot's been down for a little while, so this won't have any effect anyway. Once it's back up I'll merge.

**Comment by tgcordell** [comment]
Any ideas when mac buildbot will be back up for this?

**Comment by 8times9** [comment]
The Mac buildbot is back up now

**Comment by cesar18pena** [comment]
Can you merge this? @stenzek

**Comment by stenzek** [comment]
Updated to the latest release from a few days ago.

**Pull request merged**
