### PR TITLE
Pad cleanup 1

### PR DESCRIPTION
**Pull request by magcius**
This is the first of many input cleanups. This one is still WIP and I just want to see if it builds across all platforms.

### CODE REVIEW

**Comment by Armada651** [comment]
@magcius @Sonicadvance1 @skidau @lioncash Stable will be released in a few weeks, I take it we don't want this in there when we do. Can someone figure out exactly what needs to be reverted?

**Comment by magcius** [comment]
I think most of the breakage has been fixed up by now. Is that not the case?

**Comment by Armada651** [comment]
Not according to this issue: https://bugs.dolphin-emu.org/issues/8955

**Comment by costersall** [comment]
Any update on this? Thanks.

**Pull request merged**
