### PR TITLE
[UI] Remove experimental tag from Vulkan

### PR DESCRIPTION
**Pull request by Helios747**
**Do not use this thread as a means to report bugs. Report them here.** [https://bugs.dolphin-emu.org](https://bugs.dolphin-emu.org
)
\<JMC47> Helios747: can you make a PR to remove experimental from teh vulkan backend
\<JMC47> people are talking shit about it being experimental on reddit and how it's not done
\<Helios747> Stenzek, are you cool with removing experimental from the Vulkan backend?
\<Helios747> It's primarily your work
\<Stenzek> Helios747: Sure, I guess

### CODE REVIEW

**Comment by stenzek** [comment]
LGTM. I think it'd probably be worth starting a discussion about this before merging though, if anyone has objections to the change.

The only issues still present that I am aware of are the depth test fail issues (Mega Man X fifolog) that occur on NVIDIA, and GPU timeout/reset on AMD Polaris cards (https://bugs.dolphin-emu.org/issues/9879, but this isn't unique to the Vulkan backend). The other issues on the bug tracker are reported on anv/radv, which are still under heavy development, and not necessarily a bug on our end.

**Comment by cammelspit** [comment]
I hate to be a user clown getting into a GitHub discussion here but that frame dropping problem with the Vulkan back end still exists. I had reported it in the original PR for the Vulkan back end (https://github.com/dolphin-emu/dolphin/pull/3935). In fact, it is now, more consistent than it was before. I would find it a hard swallow not calling it experimental until this one issue, at least, is sorted. I know it MAY be a driver issue but there have been workarounds made for stuff that is less important than usability for an entire back end on cards that a third of all PC users have. You can all ignore me, I am fine with that but this is still a problem and it still makes Vulkan unusable and little more than a novelty. If I can spark this conversation, experimental is, sadly, all this back end can be if it loses the lions share of frames before they ever get to the display.

Please, don't misunderstand. I LOVE Dolphin and the Vulkan back end is truly an amazing piece of work but this really does limit it's capability of truly surpassing D3D11 or OGL which, in my humble opinion, it truly deserves to be able to do, whole heatedly.

**Comment by JMC47** [comment]
You mean the fact that Vulkan doesn't support Exclusive fullscreen?  Like, the API limitation?  I don't see how that's our responsibility.

**Comment by cammelspit** [comment]
Well, I know not as much about it as I probably should to actually say anything but... The other back ends with borderless on, seem to work fine under nearly all cases so there surely must be something that can be done to make Vulkan work properly in the same way. Besides, there have been many a limitation or even outright bugs in drivers, even recently, that have been worked around to make it work until a proper fix was made so why is this not something that is necessary here? I get, and was getting, a hugely massive benefit by using the Vulkan back end but it just can't be used right now. I would expect that usability is one of Dolphin's primary goals.

Again, ignore me if you feel I am out of line but what really is the point if no one can use it properly? Also, at least with the experimental tag still there, the assumption to a user is that there is still some things that can cause problems so the user will avoid it. This way, they won't be miffed at the fact that Dolphin "doesn't work right" when it is something beyond control, especially assuming that Vulkan is supposed to be 100%. Am I making sense here? I might not be but I am trying to be as concise as I can be.

**Comment by JMC47** [comment]
No no no; if there's a separate issue outside of Vulkan not working in exclusive fullscreen, I definitely would like to know about it.  I've been using Vulkan for a while now, and I honestly haven't noticed any big differences.  If you could give me a test case to look at it, I'll gladly do some more research on it!

**Comment by cammelspit** [comment]
Thank you very much for at least hearing me out. I will see what I can do but the last time I tried to make a video off of Dolphin when running in Vulkan OBS wouldn't pick it up. I will see what I can to here this weekend. I try and be as respectful as I can be. I LOVE Dolphin and I wholly appreciate the work Stenzek has put into this but it is hard to explain if I can't directly show you. If you were sitting next to me right now I could just say "Hey, see this is what is happening, SEE?" but without that luxury, it makes things a little more difficult to articulate. Either way, I will do what I can to see if I can capture what is happening and pass it along. I was just dubious about the removal of the experimental tag because of the possibility of user confusion if it didn't work smoothly as expected. I believe exclusive is ONE way to remedy the situation but but not the only way since a borderless side by side comparison yielded similar results. Thank you for hearing me out tho, I do appreciate it.

**Comment by stenzek** [comment]
@cammelspit What you've described kinda sounds like we're regularly missing the host system's vsync. Usually we can mitigate that through disabling vsync and tearing instead. However, if my understanding is correct, due to modern operating systems all using compositors, this doesn't happen, instead when we "flip/swap" our buffers, the image is copied to the compositor (or the compositor renders the "front buffer" of the application). We can't change the buffer that is being scanned out mid-way through (since it's the compositor's buffer, not ours), so the last image gets displayed instead.

The easiest workaround for this is using exclusive fullscreen. On recent NVIDIA drivers at least, this works the same way in Vulkan as it does in OpenGL (set some flags on the window), and you get tearing (and no overlays, e.g. volume control) show up.

However, it doesn't appear to be working on AMD's Vulkan driver (interestingly, it does work on their GL driver). I'm not sure there's anything we can do on our end to change this behavior, given the Vulkan WSI (at least in its current form) doesn't facilitate exclusive fullscreen in any way.

**Comment by JMC47** [comment]
@cammelspit I have some good news and some bad news.  NVIDIA's latest drivers do add exclusive fullscreen support and it does resolve this issue.  The bad news is that the other drivers/manufacturers do not seem to provide this functionality.

Because the latest NVIDIA drivers resolve the issue, we can surmise that this is a defect within either the drivers or vulkan itself or something.

**Comment by pepedopolous** [comment]
I have a Skull Canyon NUC (i7 Skylake) and run Dolphin on Arch Linux. Vulkan seems to improve the frame rate and reduce shader stuttering for certain games (F-Zero GX, Mario Kart Wii). However, for others there are regressions compared to OpenGL: in Metroid Prime the scanning visor doesn't work- all the information is invisible. Also Super Mario Galaxy 1 and 2 are 60 FPS on OpenGL but stuttering 30-60 FPS on Vulkan.

**Comment by tabnk** [comment]
Vulkan seems to cause Beach Spikers (GameCube) to have black textures on background and floor. 

On Nvidia GPU (Latest Driver)

**Comment by stenzek** [comment]
**Please do not use this thread as a venue for reporting bugs.** If you have an issue with the Vulkan backend, report it on the bug tracker, it will likely get more attention that way and you can provide the required information.

@pepedopolous I believe this is fixed by PR #4462.
@tabnk There is a issue on the bug tracker for this (https://bugs.dolphin-emu.org/issues/9882), I'm not sure what's happening on that one, if you could provide a fifolog that would be very helpful.

**Comment by cammelspit** [comment]
@JMC47 @stenzek Well for one, thanks for looking into it and explaining it more completely. I guess all we can do is wait for Intel/AMD to either provide exclusive FS support like nVidia has or to remedy missing vSync. Vulkan is still rather new so it does make sense that it could be either the driver or Vulkan itself. In this case I understand that it is likely beyond Dolphin's control. I guess time, waiting for the API or the drivers to mature is the only way to get past this. Though, that still begs the question, is Vulkan ready for losing the experimental tag since there still remains a good portion of users that may run into this while expecting a result more in parody with D3D and OGL? There should be a way to report it to AMD and Intel, at least make them aware of it so there is a higher likelihood that it could be fixed sooner rather than later.

Ok, I will bow out of the conversation now. Keep up the great work and thank you for humoring me. 👍

**Comment by iwubcode** [comment]
Probably veering a little offtopic but that is surprising that Vulkan doesn't provide exclusive fullscreen.  I wondered if FreeSync was really working with Dolphin and since I've only been using Vulkan that might explain why.

@stenzek - do you think you can open an issue with [the Vulkan Spec](https://github.com/KhronosGroup/Vulkan-Docs/issues).  I'd do it but I haven't worked with a graphics-api in like 7 years and only scanned the Vulkan API docs so I don't really know what I'm talking about if they get technical :)

**Comment by stenzek** [comment]
@cammelspit @iwubcode The Vulkan API itself isn't really the issue here, it doesn't actually have anything to do with getting the image out to the screen. The WSI (window system integration) which is an extension to Vulkan handles this. In its current form, it doesn't actually specify anything to do with fullscreen or how it's handled, so it's entirely up to the vendor (whether they support tearing or not, etc). The only support that is mandated is FIFO mode, which is vsync.

As JMC47 said, the **latest NVIDIA drivers support something akin to exclusive fullscreen in the same way that OpenGL does**, and you'll get **direct scanout/tearing** this way (assuming no overlays/windows are on top). The method we're using to get this to work interestingly does seem to work on the AMD OpenGL driver though, so hopefully in the future this behavior can be applied to their Vulkan driver as well. It's only a recent change on NV, I'm guessing introduced in the 370 or 375 series, but I didn't bother bisecting drivers to find the exact version it was introduced.

I did a quick test on the Mesa Vulkan driver (anv), and it behaves in the same way as NVIDIA's driver. The AMD Mesa driver likely behaves the same way, given they share the WSI implementation, I just couldn't test it because my AMD system is GCN1.2, which is poorly supported at the moment.

Therefore, the only desktop driver with this issue is the AMD binary driver. I'm not sure it's worth holding back the state of the backend for this alone, given it's an intermittent issue, and it's not like this driver doesn't have issues with OpenGL either (it's quite slow in comparison to the other APIs). Furthermore, there's not really anything we can change on our end, so if this is the only reason we're leaving it as experimental, it may be experimental for an unknown time until the driver is "fixed". I'm happy to be convinced otherwise, though. :)

**Comment by iwubcode** [comment]
@stenzek - No that's fair, I agree we shouldn't keep experimental around just for a driver issue!

I'm still wondering if we should report this though.  The VulkanDocs issue tracker has a number of issues flagged with "WSI".  I find it odd as Mantle apparently did support exclusive mode in their WSI and I thought that was what Vulkan was based off of.

Anywho, all good here.  Thanks for all your hard work @stenzek !

**Comment by JMC47** [comment]
I'm still concerned about removing the experimental tag.  Simply updating my NVIDIA drivers broke Vulkan (not in Dolphin, completely).  Not a Dolphin issue... but troubling none the less.

**Comment by JMC47** [comment]
Vulkan randomly seems to hang when launching certain games from the interpreter...

**Pull request merged**
