### PR TITLE
Android: Update dependencies and small cleaning

### PR DESCRIPTION
**Pull request by Tsunamical**
- Update Gradle plugin to -beta4

beta 4 is newer (see https://bintray.com/android/android-tools/com.android.tools.build.gradle/2.0.0-beta4/view) and it is a better idea to stay in the beta channel than alpha channel for stability reasons
- Update Gradle wrapper to 2.11 and clean Gradle files

We deprecated armeabi-v7a a while ago, no need to include handling for it in gradle script
- Update circleimageview to 2.0.0

See changes at the GH repo
- Update target SDK to 23

We ask for permissions and follow Google's guidelines for API level 23, only thing stopping us would be compilation issues or incompatibility issues

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3630)

### CODE REVIEW

**Comment by sigmabeta** [comment]
-Gradle version upgrades are fine

-What's the deal with the changes to `gradlew`?

-CircleImageView upgrade is fine, the screens where that is used are in need of attention anyway (trying to strike a balance between making things work and making things pretty)

-Don't upgrade to SDK 23; there's no obvious benefit to doing so (we're not particularly interested in fingerprint security, for example) and supporting the new permission model is a large task. If you're interested in adding this support, please add it to the PR (or a new one, which the API 23 change as part of it), but otherwise there's much more immediate work that must be done.

**Comment by sigmabeta** [comment]
FWIW, I think you may have misinterpreted the GC Adapter / Dolphinbar permission request dialog as being part of the API 23 permission model. It's completely unrelated; we have no code whatsoever in the codebase to handle the new model.

**Comment by Tsunamical** [comment]
-In the past we've just bumped the gradle number and build date, but I replaced the batch and gradlew file with the generated ones from 2.11
-Ah, my bad for the API. I had just skimmed the commit history. I'll rebase and yank it out.

**Comment by sigmabeta** [comment]
Cool, should be fine to merge once that's done.

**Comment by maximu** [comment]
x86_64 android version It has come to work before? Compile fine but

Freeze when search any iso no responsive button (black screen) 

Some Crash when I push up to top folder level and return to main GUI.

Maybe it's related with some permissions changed in Android 6.0 ( i can't tested if success in armv8 version too)

**Comment by degasus** [comment]
@maximu Android requires PIE, so try to revert this PR #2706

**Comment by Shadicbypass** [comment]
The crash with the going up a folder also happens on armv8 android marshamallow. I have the lg g4 running androod marshamllow. The same crash happens.

**Comment by Tsunamical** [comment]
Going to rebase and change a few things

**Pull request closed without merging**
