### PR TITLE
Android/GCAdapter: Don't join current thread

### PR DESCRIPTION
**Pull request by JosJuice**
The read thread could call Reset, which in turn tried to join the read thread, leading to a SIGABRT. This manifested as Dolphin consistently crashing when disconnecting a GC adapter and having a chance of crashing a few seconds after connecting a GC adapter.

### CODE REVIEW

**Review by jordan-woyak — APPROVED** [review]
LGTM. I've not personally tested it on Android.

**Comment by Dentomologist** [comment]
Is there anything preventing the following sequence of events?

1) Setup() checks the first part of the condition on lines 526-527 `s_read_adapter_thread_needs_joining.TestAndClear() ||
      s_read_adapter_thread_running.TestAndClear())`. s_read_adapter_thread_needs_joining hasn't been set yet, so TestAndClear() returns false.
2) Reset() is called on the read thread and executes `s_read_adapter_thread_needs_joining.Set();` and 
    `s_read_adapter_thread_running.Clear();` on lines 729 and 730.
3) Setup() checks the second part of the condition on 527. Since s_read_adapter_thread_running just got cleared, that TestAndClear() also returns false.
4) Since both parts of the conditional were false, Setup() doesn't join s_read_adapter_thread.
5) `s_read_adapter_thread = std::thread(ReadThreadFunc);` on line 533. According to https://en.cppreference.com/w/cpp/thread/thread/operator%3D, if the read thread is still running this will call std::terminate.

**Comment by JosJuice** [comment]
You're right, that sequence of events should be possible (albeit very unlikely). I'm going to try to think of a better design. For the time being, I'd prefer to keep this merged as it is rather than reverting it, since the current code has problems in a lot less cases than the previous code.

**Comment by JosJuice** [comment]
Addressed in PR #13260.

**Pull request merged**
