### PR TITLE
InputCommon: move Setting classes out of ControlGroup

### PR DESCRIPTION
**Pull request by ligfx**
@lioncash pinging you because you've been working on this stuff.

### CODE REVIEW

**Comment by lioncash** [comment]
`SettingType` should probably not be in a header named `SettingType.h`. Having a header dedicated to a two-entry enum seems kind of overboard

**Comment by ligfx** [comment]
@lioncash I thought about leaving it in `ControlGroup.h`, but that seemed weird to me because it's almost a cyclical dependency (settings depend on ControlGroup, ControlGroup forward-declares settings). What do you think?

**Comment by ligfx** [comment]
@dolphin-emu-bot rebuild clean

**Comment by gamemasterplc** [comment]
I wonder why Windows is failing here

**Comment by ligfx** [comment]
@dolphin-emu-bot build clean

**Comment by ligfx** [comment]
@gamemasterplc might need a clean rebuild? I tried asking @dolphin-emu-bot, but either I don't remember the command or I don't have permissions.

**Comment by lioncash** [comment]
@ligfx Just a more general name for the header file containing the enum would be sufficient

**Comment by ligfx** [comment]
@lioncash How about `Setting/Setting.h`? If there's any other general code that gets written in the future, it can go in there too.

**Comment by lioncash** [comment]
That sounds fine =)

**Comment by ligfx** [comment]
Fixed Windows build issues.

**Pull request merged**
