### PR TITLE
Qt mocless

### PR DESCRIPTION
**Pull request by shuffle2**
Verdigris is not compatible with msvc yet, however I want to submit this to:

- See what people think of the style imposed by verdigris (it can become quite cumbersome and ugly imo, and we'd need to decide how to format it).
- Have someone else do the cmake magic and confirm it works with non-msvc compilers dolphin targets.

### CODE REVIEW

**Comment by ligfx** [comment]
CMake only needs the include directories to be added. No `Q_OBJECT` macros, no automoc!

Other build issues I ran into:
- A couple files rely on signals automatically being public, and those signals need to be placed in a `public:` block: DoubleClickEventFilter.h, GameList.h, and WindowActivationEventFilter.h
- Signal parameters need names which get passed to `W_SIGNAL`. Settings.h was missing a few of these (even though names got added to the macro invocation? I wonder where those came from?). This was a pretty confusing error, though once you've encountered it I'd think it's pretty easy to recognize.
- Non-primitive, non-Qt types have to be registered with `W_REGISTER_ARGTYPE` before use in a signal. The only offender I saw was MenuBar.h, which needs to register `std::string`, but wow, what a complicated, unhelpful error message (they've got some sort of huge tree structure built up internally that spams the error log).

**Comment by shuffle2** [comment]
Thanks @ligfx , should have taken care of those issues. Also made separate commit showing what linter likes...do we like it too? :p

Btw, can I assume the produced build still works as intended, and compile time is shorter?

**Comment by shuffle2** [comment]
btw, why doesn't this cause non-windows buildbots to rebuild DolphinQt2?

**Comment by JosJuice** [comment]
Last time I checked, we weren't building DolphinQt2 on non-Windows buildbots at all.

**Comment by ligfx** [comment]
@shuffle2 The produced build seems to work, the only thing I'd be worried about is dynamic slots (we still have some of the old-style syntax laying around, which isn't checked at compile-time). Everything else should be fine.

Compile times for me are 1.5x **longer** with verdigris than with moc. On my computer, building DolphinQt2 from scratch (either by touching all source files, or removing the outputs) with moc takes ~30 seconds, but with verdigris it takes ~45 seconds.

**Comment by Orphis** [comment]
@ligfx Curious, compile times for Verdigris were reported to be lower than a moc version. This could be investigated.
But since you remove the use for a bunch of macros (slots) in some other PR, the compilation time might get better now.

**Comment by ligfx** [comment]
@orphis Maybe it's because I'm building with multiple processes by default (with ninja)? The original blog post says that Verdigris was faster than Moc when building with `make -j1`.

After removing all of the W_SLOT macros, it does run faster—closer to 1.25x master.

@shuffle2 If it helps, those are non-cached build times: when using ccache the difference is negligible.

**Pull request closed without merging**
