### PR TITLE
Fix unsafe netplay code in SI_DeviceGCController

### PR DESCRIPTION
**Pull request by MaverickAmon02**
By misusing Config, this netplay-related code opened up a race condition between Config::OnConfigChanged() and SerialInterface::SerialInterfaceManager::UpdateDevices() that could cause iterator invalidation.

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by AdmiralCurtiss** [comment]
This sounds reasonable to me. Is there ever a situation where the config value and the SI value should be different?

**Comment by MaverickAmon02** [comment]
At first I was going to say yes, the one second delay while changing to a different device, but I was unaware until now that you can't change devices while on Netplay.  Even if you could, I think this would be an improvement, since it would line up with what device is actually currently being used.
I have tested with a Netplay session on my localhost, and rumble is still being re-routed as expected, so I think this change is all good.

**Comment by AdmiralCurtiss** [comment]
Well, let's just try it and see if any issues pop up.

**Pull request merged**
