### PR TITLE
Android: Remove Leanback and use Bottom Navigation and Navigation Rail

### PR DESCRIPTION
**Pull request by t895**
I finally stripped away the TV components from the app and got to work on a combination of the BottomNavigationView and NavigationRailView to replace our MainActivity layout.

Before (TV Only) - 
layoutdemotv

Before (Tablets/Large Displays) - 
image

New Layout Demo - 
newlayoutdemo

Additionally, I'm still exploring ways to improve ways to improve inflation performance because the first transaction on any home fragment is a little slower than I'd like.

And of course, I'm always open to design comments (@MayImilae) and I'm unsure as to what I should put in place of the now missing top app bar menu buttons. I would consider a search bar, but that sounds like something to do in a later PR.

NOTE - The large ripple animation in the navigation bar is removed in a newer version of Google's Material Components. I'll be doing that as soon as possible, but we're stuck on an older version of the Android Gradle Plugin because incremental builds are broken in later versions that the new material components version depends on.
(And sorry for the large PR. I figured that if I was gonna remove leanback, it would be best if I replaced the functionality so there would be no downtime)

### CODE REVIEW

**Comment by mbc07** [comment]
I'll be direct: I think this is actually a downgrade. 

I understand dropping Leanback seems to simplify quite a bit of the UI-specific code, however it's also replacing a layout made specifically for big screens with a slightly tweaked version of the "phone" UI we currently have: it looks decent on smaller screens (especially in portrait) but it looks awful on bigger, landscape screens (e.g. TVs, tablets, Chromebooks), as it just moves the nav bar from the bottom to the left and stretches everything else to fill up the empty spaces, instead of actually taking advantage of the extra screen real estate.

Yes, the current Leanback UI also has its issues, like taking care only of the main activity (and to some extent the emulation activity, which was borrowed from the TV UI), dropping the user to the regular phone UI (stretched to landscape) when accessing anything else (e.g. settings) but I would rather try to improve that than going all the way in with the stretched phone UI bandwagon...

**Comment by K0bin** [comment]
I don't know what it looks like on Android TV but I really love the phone UI.

**Comment by MayImilae** [comment]
How is the new TV layout with a controller? So far all that you've shown is with mouse/touch input, but users on TVs will be using gamepad exclusively.

...to be honest I should probably throw this onto our Nvidia Shield to try it out myself but it's been so long since I've sideloaded anything I don't even remember how.

**Comment by t895** [comment]
> How is the new TV layout with a controller? So far all that you've shown is with mouse/touch input, but users on TVs will be using gamepad exclusively.

I've tried it with a gamepad on my phone and the arrow keys on my computer before, but please try it on the Shield itself to make sure. It is the only TV platform we support after all...

**Comment by JosJuice** [comment]
The way your first commit currently is implemented, it's effectively dropping all Android TV support. Is that really your intention? I was assuming that you were just going to replace TvMainActivity with MainActivity, while maintaining support for features like launching Dolphin from the TV home screen.

**Comment by t895** [comment]
> The way your first commit currently is implemented, it's effectively dropping all Android TV support. Is that really your intention? I was assuming that you were just going to replace TvMainActivity with MainActivity, while maintaining support for features like launching Dolphin from the TV home screen.

Oh right, I forgot about that. I'll get the launcher visibility back.

**Comment by t895** [comment]
Closing for now. I'm going to continue working on the home layout and once I think it's appropriate for large screens, I'll propose removing leanback again.

**Pull request closed without merging**
