### PR TITLE
VideoCommon: Change free-look's middle-mouse action to roll the camera.

### PR DESCRIPTION
**Pull request by jordan-woyak**
PR requested by @MayImilae.

I had to add an additional rotation float so I removed some unnecessary free-look matrix state while I was there.

### CODE REVIEW

**Comment by MayImilae** [comment]
Hmm, it has a bit of a problem - the angle of the roll is locked to the original camera position/rotation, not the new camera position/rotation. This is a little hard to describe so I'll use screenshots!

So here is the start before using free camera. At this position, roll rotates around like the arrows I added. It's great!

roll1

So now I'll WASDQE to move the camera to the edge of the platform on the right, and turn it toward samus with right mouse.

roll2

Notice the weird angle? That's why we need roll, that's more or less as good as I could get before and I'd have to fix it in photoshop! Anyway, so now I want to use roll to fix this right? Except, this is the angle of rotation!

roll3
(forgive how weird the arrows look, I didn't want to bother going into actual 3D. Also it is precisely up and down, to be clear)

So with this, I cannot use roll to correct for the random angles that build up during camera movement. It's locked to whatever the original camera position/rotation was.

...I'm hoping this is easy to solve?

**Comment by jordan-woyak** [comment]
@MayImilae I changed the rotation order so roll occurs after pitch/yaw. Things can still feel weird when pan/tilting after rolling because of the order of rotations. If that is unacceptable I'll have to maintain a rotation matrix instead of the Euler angles.

**Comment by MayImilae** [comment]
Hmm... So roll itself works fine now, but all of the other commands ignore it as though those movements never happened. I'm better with images so, visual aids!

After rotating, I'd expect that the movements would still match relative to the frame. So like, holding right mouse and pushing my mouse up would still tilt the window up relative to the frame. Basically I'd expect it to be aware of the roll and factor that into the new position and orientation to start from.

expectation

But instead, it ignores the roll, so tilt (holding right mouse) and pan up/down (Shift Q and Shift E) remain at the same orientations they were before the roll. It makes combined camera repositionings for tricky shots a real chore!

reality

Curiously though, Pan left and right (shift A and shift D) DO seem to take the roll into account, and follow the roll of the camera. Very curious!

To be fair, this is still way better than what we've had, and I can genuinely do a lot more shots with this than before. I'd just, need to make sure to do roll changes *LAST*. It would be nice if that could be addressed though!

**Comment by fluffapparition** [comment]
You need to add some kind of equation while Free-look is active that makes the 3D vector translation/rotation performed by the mouse will be relative to the Z-Axis (roll) rotation. Basically, one axis will have a certain amount removed and then added to another specific axis, depending on some factors.

I can't suggest any edits to your code yet since I haven't actually looked at it, however, **I think we can try using something similar to what's shown in this snippet from a 3D walking script I wrote in C# for Unity's Freelook cam a while back:**


	if (facing > -90 && facing <= 90){ //facing forward
		if(facing >= 0){
			DistanceFromNeutral = (90 - facing);
		}else{
			if(facing < 0){
				DistanceFromNeutral = (90 + facing);
			};
		};
		
		
		transformX = (1 / 90) * (DistanceFromNeutral);
		transformZ = (90 - transformX);
	};

What I'm doing here is I'm taking the distance from the default roll position (in this case it is zero, so hopefully no offsets are needed) from -90 to 90 degrees, and it uses that to figure out by what amount in the X and Z axis it should transform by spreading them out across the two. It does the same thing with strafing, but the X and Z are swapped. 

If you know C# feel free to inspect this to get a good idea of how the math works.

In YOUR case, you need to implement this same logic in your C++ code but you'll have to do it a bit differently. You may even need to write a totally different equation all together, since this logic was designed for a totally different scenario. 

No matter what though, the solution I'm trying to bring to the table here is that **we should move a certain amount of the rotation on the Y axis over to the X axis and vice-versa, using some mult./divis. with the rotation on the Z axis, so that it will add an offset making it relative to the Z rotation.** 

I'll leave it up to you for now to work on it since I'm a bit too busy to try fixing it myself at the moment, I just wanted to present this idea since I ran into a similar problem in my own software before in Unity and figured I'd share what I had.

Go ahead and present your solution once you think you've got it going this time 👍 or ask for help

**Comment by Techjar** [comment]
I think you overcomplicating it, all you need is a matrix. :)

**Comment by MayImilae** [comment]
Gave it a try, and this is great! I can get any shot at any angle and it move to another shot at another angle seamlessly. No more weird angles that I can't adjust for, and no worrying about resetting between shots. I'm super happy with this!

**Comment by fluffapparition** [comment]
> 
> 
> Gave it a try, and this is great! I can get any shot at any angle and it move to another shot at another angle seamlessly. No more weird angles that I can't adjust for, and no worrying about resetting between shots. I'm super happy with this!

As they say, Dolphin does what Nintendon't.

**Pull request merged**
