### PR TITLE
Android: Fix ATV on API 28+

### PR DESCRIPTION
**Pull request by webgeek1234**
This should fix #11944. But as I cannot get the gradle config in the project to cooperate with the android-sdk on my dev machine, I'm going to have to rely on the pr builder to test.

### CODE REVIEW

**Comment by webgeek1234** [comment]
Or... apparently I can't even do that. Can someone manually trigger the build or am I between a rock and a hard place here?

**Comment by webgeek1234** [comment]
Nope, this isn't enough. It gives a different error, but still appcompat related. Asking around to see if I can find someone that understands this stuff.

**Comment by webgeek1234** [comment]
So, this is getting more fun. Looks like the analytics alert dialog usage fails on atv because it uses appcompat, which isn't normally usable on leanback.

**Comment by webgeek1234** [comment]
This revision is verified working on a SHIELD Android TV running Android 9.0.

**Comment by javelinanddart** [comment]
Since there's no CLA of any kind, just wanted to put this here:

I accept the use of this code in this project and the licensing that comes with it.

**Comment by JosJuice** [comment]
Ah, so the problem is when showing the alert... I see. I was assuming that it happened on activity launch all this time.

I'll do a quick merge of this and then amend PR #8718 to make the analytics alert use the theme defined in that PR (which also is an AppCompat theme). Thanks for fixing the issue!

**Pull request merged**
