### PR TITLE
windows: update to qt 6.5.1

### PR DESCRIPTION
**Pull request by shuffle2**

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
Someone needs to install the Qt Svg component on the Linux and Mac buildbots.

**Comment by OatmealDome** [comment]
All the builders have been updated.

**Comment by AdmiralCurtiss** [comment]
Trying to use this with CMake on Windows now generates the following error, which makes me think that our Qt Windows build is misconfigured somewhere:

```
1> [CMake] CMake Error at Externals/Qt/Qt6.5.1/x64/lib/cmake/Qt6Gui/Qt6QICNSPluginTargets.cmake:86 (message):
1> [CMake]   The imported target "Qt6::QICNSPlugin" references the file
1> [CMake] 
1> [CMake]      "Externals/Qt/Qt6.5.1/x64/./plugins/imageformats/qicnsd.dll"
1> [CMake] 
1> [CMake]   but this file does not exist.  Possible reasons include:
1> [CMake] 
1> [CMake]   * The file was deleted, renamed, or moved to another location.
1> [CMake] 
1> [CMake]   * An install or uninstall procedure did not complete successfully.
1> [CMake] 
1> [CMake]   * The installation package was faulty and contained
1> [CMake] 
1> [CMake]      "Externals/Qt/Qt6.5.1/x64/lib/cmake/Qt6Gui/Qt6QICNSPluginTargets.cmake"
1> [CMake] 
1> [CMake]   but not all the files it references.
1> [CMake] 
1> [CMake] Call Stack (most recent call first):
1> [CMake]   Externals/Qt/Qt6.5.1/x64/lib/cmake/Qt6Gui/Qt6QICNSPluginConfig.cmake:51 (include)
1> [CMake]   Externals/Qt/Qt6.5.1/x64/lib/cmake/Qt6/QtPublicPluginHelpers.cmake:518 (include)
1> [CMake]   Externals/Qt/Qt6.5.1/x64/lib/cmake/Qt6Gui/Qt6GuiPlugins.cmake:5 (__qt_internal_include_plugin_packages)
1> [CMake]   Externals/Qt/Qt6.5.1/x64/lib/cmake/Qt6Gui/Qt6GuiConfig.cmake:123 (include)
1> [CMake]   Externals/Qt/Qt6.5.1/x64/lib/cmake/Qt6/Qt6Config.cmake:157 (find_package)
1> [CMake]   Source/Core/DolphinQt/CMakeLists.txt:16 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
```

I traced this and it just enumerates all `*PluginConfig.cmake` files in `Externals/Qt/Qt6.5.1/x64/lib/cmake/Qt6Gui/` so maybe we just need to delete the ones we don't ship dlls for.

**Comment by AdmiralCurtiss** [comment]
The `mkspecs` directory is also missing again, see https://github.com/dolphin-emu/ext-win-qt/pull/19

**Comment by AdmiralCurtiss** [comment]
With those two things is works fine with CMake too, or seems to anyway.

**Comment by AdmiralCurtiss** [comment]
It does build even without the `mkspecs` files, but it seems a bit suspect to me that this works... If you grep the Qt headers you do find `#include "qplatformdefs.h"` statements in a few of them. So maybe this only happens to work due to the subset of Qt we `#include` at the moment? No idea. I'd rather have them then not, to be honest.

**Comment by AdmiralCurtiss** [comment]
If you have the files lying around please make a PR, I'd have to go get the Qt sources.

**Comment by AdmiralCurtiss** [comment]
Seems to work.

**Comment by AdmiralCurtiss** [comment]
@shuffle2 Next step is using svgs for our icons, right? Do you have those, or does @MayImilae have them, or do we still need to create them?

After that we can update the scaling mode again.

**Comment by MayImilae** [comment]
> Next step is using svgs for our icons, right? Do you have those, or does @MayImilae have them, or do we still need to create them?

I'm planning to make the move to SVGs in the near future. I built the originals as vectors, but they are _Adobe_ vectors, and built for raster output. It will require "refactoring" to work in SVG, plus style changes to work within the limits of SVG. I need to do it for Big Porpoise anyway so I'll be doing it in soonish.

**Comment by AdmiralCurtiss** [comment]
@shuffle2 Have you tested the ARM build in some way? We've gotten a report that Dolphin doesn't start on ARM Windows anymore.

**Comment by AdmiralCurtiss** [comment]
Okay so probably user error then, if the Qt UI opens that's further than what was reported. (they said they got an error message about the Qt platform plugin)

**Pull request merged**
