### PR TITLE
Replaced with rc24 nwc24msg.cfg (becose wc24 shutdown)

### PR DESCRIPTION
**Pull request by Fun4TubeGr**
Hi @AwesomeMarioFan said we be working on mail system and we be iniclude on dolphin so i patched nwc24.msg with the rc24 server

### CODE REVIEW

**Comment by AwesomeMarioFan** [comment]
To completely patch the mail server addresses, they would also need to be patched in the source code as well as nwc24msg.cfg: https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Core/IOS/Network/KD/NWC24Config.cpp#L60

Just to clarify, the mail system I was referring to was a Python script that would run alongside the emulated Wii menu in Dolphin which would provide WC24 functionality, so it would be helpful for the URLs in Dolphin to be patched but not required since the script will run separately from Dolphin and can override them.

**Comment by MayImilae** [comment]
Is this really something we want in Dolphin's source code?

IMO, the goal of Dolphin should be for Dolphin to emulate a Wii as shipped. A new-old-stock Wii, when powered on today, would not have WC24, and it would be up to the user to add custom server functionality if they want to. Dolphin should behave the same way. That way, what happens with the custom server scene won't matter to us, as we'll just support whatever comes along by default (since they are aimed at Wiis).

**Comment by sepalani** [comment]
TBH, I don't think these URLs should be "patched" per se. Usually, you only need to redirect the domain name and that's all. You can do that using a DNS server or by editing the hosts file.

**Comment by JosJuice** [comment]
> That way, what happens with the custom server scene won't matter to us, as we'll just support whatever comes along by default (since they are aimed at Wiis).

I agree – I don't want to put us in a position where we more or less try to decide for users which third-party reimplementation is the best (if there turn out to be multiple ones in the future).

**Comment by larsenv** [comment]
Not only that, but the version Fun4TubeGr added has his password and "mail check ID" in the nwc24msg.cfg, which can be a security risk in the future (we plan to make our mail scripts have password-authentication).

**Comment by AwesomeMarioFan** [comment]
The script will run independently from Dolphin and will not need any changes to the codebase in order to work. In the future if WC24 is properly implemented into Dolphin maybe an option to configure the URLs would be nice but right now it is not needed.

**Comment by MayImilae** [comment]
> The script will run independently from Dolphin and will not need any changes to the codebase in order to work.

That doesn't answer the question of why it belongs in Dolphin, though, or why it needs to be our responsibility to maintain it whenever the custom server scene changes.

**Comment by AwesomeMarioFan** [comment]
I understand that it isn't the Dolphin team's responsibility to maintain or support custom servers and that Dolphin is meant to exactly replicate the user experience of a real Wii. Just like this project's goal is to be like a new old stock Wii that was just booted up, RC24's goal is to be an exact WC24 replacement just as if the channels were to be opened 10 years ago, so I agree with you that it doesn't belong in the codebase. When I said that it would run independently from Dolphin, I meant that no changes, implementation, or maintenance would be required from Dolphin.

**Comment by Helios747** [comment]
Against this. Dolphin's goal is to emulate a Wii, just like @MayImilae said. Warts, now broken functionality and all.

It's up to the community to set up dolphin to replace non-functional features that were made non-functional by Nintendo. It does not have a place in Dolphin's codebase in my opinion. Not even as a one liner. AFAIK we aim to preserve the hardware and it's default setup.

Also, what should happen if/when your server goes down? Do we accept another PR to the next person to claim they'll keep it online?

**Comment by bb010g** [comment]
What might be nice would be a way to make the mail server addresses customizable (from the UI or hidden in a config file) so that this can just be handled by a normal user. I don't think wanting to set up custom WC24 is that niche of a desire, and it fits in with our other usability enhancements.

**Comment by sepalani** [comment]
@bb010g TBH, I still think that solution to be overkill. IMO, accessing online services on an emulator is niche regarding the steps required like dumping stuff from the NAND which requires a softmodded Wii. Moreover, custom servers have to be transparent as much as possible and reproduce the original servers behaviours to be usable.

Actually, the simplest way to use custom servers is by using proper DNS servers (usually these are made available by the people hosting private servers) or alternatively by adding entries to the hosts file for PC users. It works on Wii and Dolphin that's why I don't see the need to make the code more complex and less accurate/more error prone (pick the one that suits best) by introducing custom behaviours. Indeed, they just redirect trafics from given domain names to custom server transparently.

However, when SSL/TLS is used it can be an issue that still can be circumvented by patching the in-game certificated and/or URLs making the need for DNS servers sometimes optional. SSL stripping sometimes works as well not to deal with SSL/TLS.

The only concession where I would think such a configuration file is unavoidable would be cases like SSL trust chains, RSA keys and other properties like patching IOSes to add/remove features that shouldn't be normally modified. Even though, to be user friendly I would suggest them to build their own fork of Dolphin with the appropriate modifications and share it instead to prevent issues between Dolphin builds manually patched by users.

**Pull request closed without merging**
