### PR TITLE
GameINI: Update Cheats for GMPE01, GP5E01, GP6E01, GP7E01

### PR DESCRIPTION
**Pull request by UnicorNora**

### CODE REVIEW

**Comment by autofire372** [comment]
Please spell out Mario Party. I checked this PR expecting to find **M**etroid **P**rime cheats and was very disappointed...

**Comment by leoetlino** [comment]
Yeah, please put "GameINI: " in the commit message and write out Mario Party to make the commit title clearer.

**Comment by Rumi-Larry** [comment]
I suggest the title: "GameINI: Add more cheats as well as restore proper credit of them for some Mario Party games"

**Comment by JosJuice** [comment]
That is very long, though. "Add more cheats as well as restore proper credit of them" would be appropriate to shorten to "Update cheats".

**Comment by dreamsyntax** [comment]
> 
> 
> What do you mean?

I was under the impression Data/Sys/GameSettings inis were only for Dolphin related patches. 
User/GameSettings (user external added) would have cheats.

Was this changed or was it always like this? What determines if cheats can be included within Dolphin Source?

**Comment by JosJuice** [comment]
It's been like this for at least 7 years and probably even longer. (I joined the project 7 years ago.) I don't think we have any proper criteria for which cheats should be included, though.

**Comment by dreamsyntax** [comment]
> 
> 
> Any chance for a merge

Not a reviewer, but based on my past experience you will need to rebase on master instead of having another merge commit in your PR.
There should only be one commit.

PR merges are typically in cycles from what I've seen so if its good to go expect it sometime this week/next week.

**Review by leoetlino — APPROVED** [review]

**Pull request merged**
