### PR TITLE
Fix building with PCH disabled.

### PR DESCRIPTION
**Pull request by rohit-n**

### CODE REVIEW

**Comment by lioncash** [comment]
@dolphin-emu-bot rebuild

**Comment by jimbo1qaz** [comment]
This is like the, tenth? time you merged a PR with the exact same title.

What is it with you and fixing PCH-disabled build?

**Comment by lioncash** [comment]
Nothin' wrong with keeping pch-less alive :p

**Comment by degasus** [comment]
What's wrong with us to still don't have a PCH-disabled buildbot...

**Comment by Icekhaos** [comment]
I agree with @degasus here. I think @rohit-n himself proposed this a while ago, or someone else did.

**Pull request merged**
