### PR TITLE
StreamADPCM: Convert into a namespace

### PR DESCRIPTION
**Pull request by lioncash**
No need to have a class with only static member functions

### CODE REVIEW

**Comment by phire** [comment]
@dolphin-emu-bot rebuild

**Comment by degasus** [comment]
I don't see a difference between class and a namespace, but whatever, LGTM

**Comment by lioncash** [comment]
@degasus If no actual instance of a class is created, then it has no meaningful mutable state. It's essentially using a class to simulate the behavior of a namespace.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
