### PR TITLE
Fix disc image conversion button not being clear

### PR DESCRIPTION
**Pull request by Filoppi**
It wasn't clear whether the conversion would create a new file or replace the old one

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by jordan-woyak** [comment]
I agree that it's not clear but I don't like the suggested wording for some reason.
Perhaps the to-be-generated filename should be shown directly above the "Convert" button to make things even more clear?

**Comment by Filoppi** [comment]
> I agree that it's not clear but I don't like the suggested wording for some reason.
> Perhaps the to-be-generated filename should be shown directly above the "Convert" button to make things even more clear?

@JosJuice gave me the exact words

**Comment by JosJuice** [comment]
No, I gave you the exact capitalization and punctuation to use given the words that you suggested. I don't know if this is the best way to word it or if there's a better way.

@jordan-woyak The user will select the location and filename after pressing the convert button.

**Comment by jordan-woyak** [comment]
Ah. If the path is chosen after clicking the button maybe it should just say "Convert...".
Like with "File->Open..." the ellipsis can show that an additional dialog will be shown on press.

**Comment by Rumi-Larry** [comment]
IMO, there should be two options "save as new file" and "replace original file". with the later being the default, since that's what most users want to do, to save space.

**Comment by jordan-woyak** [comment]
> IMO, there should be two options "save as new file" and "replace original file". with the later being the default, since that's what most users want to do, to save space.

I'd suggest a "Remove original file after successful conversion" checkbox for this feature.

**Comment by Filoppi** [comment]
I don't mind, but that is different PR. Unless it will be implemented soon, just let me know if "Convert..." is final so I can amend the commit.

**Comment by JosJuice** [comment]
"Convert..." is no doubt an improvement over "Convert", and I would be fine with merging that change. The question is whether there could be an even better way to word it, but if you're fine with changing it to "Convert...", then let's do that.

**Comment by Filoppi** [comment]
https://github.com/dolphin-emu/dolphin/pull/8973

**Comment by Filoppi** [comment]
This can be squashed on merge as all commits have the same text as the PR title.
Or close/merge https://github.com/dolphin-emu/dolphin/pull/8974

**Comment by JosJuice** [comment]
We do not use squash on merge, as explained on IRC. Closing in favor of the other PR.

**Pull request closed without merging**
