### PR TITLE
Lighting Attenuation Fixes

### PR DESCRIPTION
**Pull request by NanoByte011**
Fixes a lot of Specular Highlight issues such as Issue 6398, 6169, 7693 and possibly more!

Would like to find a real game case for the Spot Light Attenuation and test if that's ok too.

### CODE REVIEW

**Comment by magumagu** [comment]
@NanoByte011 are you seriously having trouble finding a game that uses LIGHTATTN_SPOT?  I tried a few games, and every one of them used it somewhere...

**Comment by Linktothepast** [comment]
It seems to fix car reflections in the need for speed series too, issue 8072.

**Comment by NanoByte011** [comment]
The FifoCI thing is cool... is there a threshold setting?  Because some of these look like they don't have a diff, even though it thinks there is.

**Comment by Sonicadvance1** [comment]
Yea, the threshold is if there is a different pixel value anywhere in the image then it is different.

**Comment by JMC47** [comment]
@Nanobyte011 Did you notice some of the lighting stuff in Mario tennis isn't fixed?  Like the scores and whatnot?  Are those _another_ lighting glitch?

**Comment by NanoByte011** [comment]
@JMC47 Yeah, I did notice, those seem to be a different issue, the preview court before you start the match is dark too. :(
@magumagu yeah, that code is hit in different games for spot, but I'm looking for a good test case were you can tell it's a spot light and there is an issue or if it works ok... I just want to verify the results are correct! :)
@Sonicadvance1 well there may be slight pixel differences because the lighting calc was off, but on my laptop here I can't see which pixel is different on some, does the "Bright" feature work?  Could be hard to see on my laptop... just want to make sure the diff is working correctly.

**Comment by JMC47** [comment]
@Nanobyte011:  Figures on the Mario Tennis thing.  Dolphin's Lighting tends to be bad at doing stuff.

**Comment by magumagu** [comment]
Hmm... the Wind Waker title screen seems like a decent example?

**Comment by NanoByte011** [comment]
@magumagu hmmm... it's more like a game where it's a spotlight and there is incorrect specular highlights... ie a flash light and then there is no shine on a door knob for example... maybe Luigi's Mansion might have lighting like this.  But yeah any ideas on a game with lighting that, where we can check to determine if Dolphin is doing it right would be good.

**Comment by JMC47** [comment]
This also seems to finish off the remaining lighting quirks in MegaMan Network Transmission.

**Comment by NanoByte011** [comment]
Good stuff, feeling pretty good about killing multiple bugs in one shot! lol
magumagu did show me that in SMG, the Mii faces on the file select screen do show up brighter with this PR, so not sure what's up with that... Mii rendering seems to be problematic at any rate... I wonder if the data coming in for them is correct or if they have some special stuff to them that we aren't doing right.

**Comment by NanoByte011** [comment]
All should be good now, let me know if anyone finds any lighting issues this PR causes

**Comment by degasus** [comment]
Wow, how could it be that our lighting code was just /so/ wrong...

**Comment by FioraAeterna** [comment]
Yeah, wow, that's /embarrassing/ levels of bad. Awesome work!

**Comment by neobrain** [comment]
Did you happen to take a quick look into the software renderer and check, if that one has similar issues? At least the mario tennis fifolog looks suspiciously similar.

**Comment by NanoByte011** [comment]
Thanks all, there are still some lighting issues to solve (ie Mario Tennis preview court and the Score are still dark and confirmation that spot light specular is working in any games).  

@neobrain yeah I did briefly see the same problems in the SW Renderer with Mario Tennis in a test... so I assume it's broken as well.  I can have a look at it for more future fixes on lighting.

**Pull request merged**
