### PR TITLE
aldlist.cpp fix 

### PR DESCRIPTION
**Pull request by Karaulov**
aldlist.cpp fix crash and optimize ? :)

### CODE REVIEW

**Comment by lioncash** [comment]
Your commit messages are pretty vague. Please expand it to also include an explanation on what the crash you're fixing was caused by. I know what it is by looking at the code, but I shouldn't have to look at the modified code just to understand what in particular is being fixed.

Also I'd like to request that you please stop using what looks like Github's web editor in order to update files. Use an actual git client to stage and make your changes. Any further PRs that contain an `"Update \<file name\>"` will just be closed.

Closing this, as you've previously stated that you don't know how to rebase or amend commits properly in a previous PR, which leads me to believe this one won't be amended either.

**Comment by Karaulov** [comment]
strcmp(nullptr) == crash

**Comment by Karaulov** [comment]
web editor can't used for create pull request? :(

**Comment by lioncash** [comment]
That is, indeed, what I had stated.

**Comment by Karaulov** [comment]
ok i now download github windows client... ))

**Pull request closed without merging**
