### PR TITLE
Implement full occlusion queries for the Nexus 9.

### PR DESCRIPTION
**Pull request by Sonicadvance1**
GLES3 spec is worthless and only returns a boolean result for occlusion queries. This is fine for simple cellular games but we need more than a boolean result.
Thankfully Nvidia exposes GL_NV_occlusion_query_samples under a OpenGL ES extension, which allows us to get full samples rendered.
The only device this change affects is the Nexus 9, since it is an Nvidia K1 crippled to only support OpenGL ES.
No other OpenGL ES device that I know of supports this extension.

### CODE REVIEW

**Comment by tueidj** [comment]
Older tegra devices support it (but they don't have GLES3) and the MI PAD which is another K1 tablet.

**Comment by Sonicadvance1** [comment]
Other K1 devices that expose full OpenGL don't count towards my thought process of "other devices"

**Comment by Mullin** [comment]
@Sonicadvance1 : I don't think MiPad have full OpenGL context.

**Comment by Sonicadvance1** [comment]
Should do. GLBench claims it does at least.

**Comment by Mullin** [comment]
Confirmed, Even if it should, Mipad doesn't support full OpenGL context. Anyway good work :)

**Pull request merged**
