### PR TITLE
Android: Configurable Control Placement

### PR DESCRIPTION
**Pull request by Ironthighs**
-Implemented ability to configure game controls by moving them around individually. Controls save locations once they are placed.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4040)

### CODE REVIEW

**Comment by lioncash** [comment]
Brace placement is a little inconsistent for some functions. Also we put spaces after `if`, `while`, etc before the opening parenthesis

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4040#-:-KNB-uZ7HFCzEeMOZw40:415682056)*

**Comment by degasus** [comment]
@sigmabeta Do you have an opinion on this PR?

**Comment by sigmabeta** [comment]
Haven't tried it on a device yet, but the code looks like it should be right & this is a clever UX solution.

**Comment by Ironthighs** [comment]
Finished making @lioncash 's suggested changes.

**Comment by degasus** [comment]
please rebase your WIP branches instead of merges, and you're free to also just squash such fixup commits together.

**Comment by Ironthighs** [comment]
@degasus Should be up to date now.

**Comment by degasus** [comment]
If sigmabeta is happy, and no one else complains, I'm merging it now.

**Comment by eddiebrook** [comment]
buildbot broken for android since this PR.

**Comment by sigmabeta** [comment]
Doesn't appear to be the case. No build failed or anything like that. It looks more like buildbot isn't scheduling `release-android` to run a new build.

**Comment by eddiebrook** [comment]
Oh i see ,sorry for the confusion. I hope it is resolved soon. Thx

**Comment by degasus** [comment]
Likely a regression on android-tv: https://forums.dolphin-emu.org/Thread-dolphin-crashed-at-start-games-nvidia-shield-tv

**Pull request merged**
