### PR TITLE
Re-implement D3D12 video backend

### PR DESCRIPTION
**Pull request by stenzek**
Now that we have most of the logic in VideoCommon, this is much simpler and less error-prone. I did say in the videocommon PR that I'd be okay with it if it was around 5k lines of code, and here we are. Not bad for a day and a bit's work.

Very little of the original D3D12 code is left. To be honest, my original plan was to rebase it to the new interfaces, and then delete what wasn't needed, but I felt it was messy and ended up keeping less than I didn't.

### CODE REVIEW

**Comment by JMC47** [comment]
EFB Access doesn't appear to be working properly in Super Mario Galaxy.  Missing Lenses Flare

**Comment by Degerz** [comment]
Soon, you too will be able to use D3D12 ROVs and Vulkan will also introduce OpenGL style fragment shader interlocks as well ... :) 

Programmable blending all the things!

**Comment by Sunderland93** [comment]
One question: why? If Dolphin already have Vulkan renderer

**Comment by Narugakuruga** [comment]
It seems that vulkan support of Intel driver is not as good as D3D12. That may be the reason.

**Comment by stenzek** [comment]
Better drivers for some vendors (Intel), some features not available in Vulkan (e.g. rovs), windows-on-arm devices

**Comment by psennermann** [comment]
Quick benchmark: at the very beginning of "The Last Story" I get 133 fps with Dx12 and 127 fps with Dx11
(Win10, GTX1060 3gb, i7 7700 )

**Comment by stenzek** [comment]
All features have been implemented in the backend now.

@psennermann The Last Story tends to be CPU-bound in my experience, it pushes a *lot* of vertices. So it may not see a large improvement from DX12.

**Comment by psennermann** [comment]
There's no more a Windows build in the builbot list?

**Comment by psennermann** [comment]
I suggest to check Xenoblade Chronicles (SX4P01): it is ultra slow using dx12 (20 fps instead of 105 - dx11) and also has some graphical glitches...

**Comment by JMC47** [comment]
Provide a fifolog of it if you want it to be looked at more quickly.  Sometimes developers don't have the games, and screenshots + fifologs are their only way to investigate it.

**Comment by psennermann** [comment]
Here's the screenshot:

image


and here's the fifolog:

https://www.dropbox.com/s/6xjcemfihuoi3yr/Xenoblade_fifolog.zip?dl=0

**Comment by JMC47** [comment]
Thanks!

**Comment by Helios747** [comment]
> One question: why? If Dolphin already have Vulkan renderer

A non trivial number of our users are on Intel iGPUs on Windows that have D3D12 support but not Vulkan.

For them D3D12 is a significant boon.

And since the biggest reason we got rid of D3D12 in the first place is resolved, this is a much easier sell.

**Comment by AdmiralCurtiss** [comment]
I can confirm that this runs some games very poorly (performance-wise) compared to D3D11 or Vulkan, F-Zero GX for example. The CPU usage is significantly higher on D3D12. Even uncapping the framerate in something like Melee's menu only gives about half the FPS on D3D12 compared to D3D11. This is on a GTX 1070.

**Comment by JMC47** [comment]
Performance issues appear to be fixed.

**Comment by psennermann** [comment]
Yes, Xenoblade Chronicles graphical issue and bad performance are fixed (105 fps Dx12 vs 98 fps Dx11)

**Comment by Narugakuruga** [comment]
I tested Monster Hunter 3, D3D12 is around 69 fps while vulkan is around 64 fps.

**Comment by Miksel12** [comment]
When I try to boot a game I get the warning: DX12::DXPipeline::Create failed in \d3d12\dxpipeline.cpp at line 208. After continuing, dolphin crashes.

**Comment by Miksel12** [comment]
With the latest changes, I don't have the warning mentioned above. 
Though using custom textures (dds format) crashes dolphin.

**Comment by JMC47** [comment]
Yeah, the previous bug was with per pixel lighting.

**Comment by stenzek** [comment]
Custom .dds textures should be fixed now.

**Comment by Miksel12** [comment]
Can confirm that .dds textures are fixed

**Comment by RinMaru** [comment]
well it froze my entire computer in Metroid Echoes

**Comment by Haliinen** [comment]
Hi,

I just tested D3D 12 with Mario Sunshine using Ubershaders (Synchronous) with all hacks disabled and bounding box also disabled and get the following errors when entering "Pinna Park" after selecting a shine, using custom textures pre-loaded to RAM.

"DX12::DXContext::ExecuteCommandList failed in c:\buildbot\release-win-x64\build\source\core\videobackends\d3d12\dxcontext.cpp at line 472: Close command list"

and

"DX12::PerfQuery::ReadbackQueries failed in c:\buildbot\release-win-x64\build\source\core\videobackends\d3d12\perfquery.cpp at line 194: Failed to map query readback buffer"

Never had issues with D3D 11 so far, but it has been around much longer too.

Tested on GTX 1080 with 419.67 drivers.

**Comment by JMC47** [comment]
Super Mario Sunshine is the only game that uses Perf Queries, and while we tested it once it appears that something broke after a rewrite.  I'll verify and we'll try to fix it ASAP.  Thanks for the heads up.

**Comment by JMC47** [comment]
Can you please try https://dl.dolphin-emu.org/prs/pr-7953-dolphin-latest-x64.7z

Fixes the issue for me.

**Comment by Haliinen** [comment]
Are you sure? I just ran around in Delfino Plaza and in less than a minute or so, with the build you uploaded, I got this error message,

"DX12::PerfQuery::AccumulateQueriesFromBuffer failed in c:\buildbot\pr-win-x64\build\source\core\videobackends\d3d12\perfquery.cpp at line 205: Failed to map query readback buffer"

I have no clue what is going on tbh. Again, in the "hacks" tab of the GFX configuration, I have all hacks turned off and bounding box disabled, using the safest option for EFB to RAM texturing etc. Using the .dds Mario Sunshine HD textures pre-loaded to RAM as well. I also run Dolphin with the latest installed Visual C++ 2017 redist (the very latest version of it) and Windows 10 Home 64-bit 1809 if it matters.

I'll play around more to see what kind of other errors I may encounter. Hopefully we can narrow this down.

**Comment by stenzek** [comment]
@Haliinen could re-download and try again? I pushed another update a few minutes after @JMC47 posted.

**Comment by JMC47** [comment]
There's probably still an issue, try redownloading it as a second bug was fixed.

**Comment by Haliinen** [comment]
Hey you two,

Thanks for the heads up and I re-downloaded the build again. I can confirm that I encountered no errors at all while using D3D 12 this time, running the same settings with .dds textures enabled as well. I played for around 5 to 10 minutes with no problem whatsoever.

I did not do extensive testing since this was a test build, if the changes are pushed the master I will continue on my save file later and report back after I have done some extensive testing with the backend, but so far so good. 

Thanks for your hard work and that you could provide a fix rather quickly on this one.

**Comment by JMC47** [comment]
It'll probably get merged soon, once stenzek sees your message.

**Comment by stenzek** [comment]
@Haliinen thanks for checking and reporting back :)

**Comment by Haliinen** [comment]
I tested this on the master build for 40 mins now with no crash at all and completed at least five shines or so, great work man! 

I want to point this out, the transition when opening the scoreboard in Mario Sunshine (using the Z-button by default) is not smooth and FPS drops occasionally, this does not happen running D3D 11 from what I recall, I assume EFB's are not handled optimally on D3D 12 right now? The effect works as expected, it's on the slower end unfortunately and wish I could give details on this somehow. 

Stopping emulation force closes Dolphin as well for some reason, but that does not belong here and is not caused by the D3D 12 backend, since it also happened on D3D 11. It does not do it everytime, but sometimes... I know this does not tell you much, but the UI is being weird somewhere certainly? Just a heads up, that is all.

**Comment by Techjar** [comment]
The map effect in SMS is notoriously awful on all backends because it makes tons of EFB copies per frame.

**Comment by JMC47** [comment]
You can try turning on defer invalidating EFB peek cache in the advanced section of backend settings.  It should be at the bottom and I know it's named something similar but not quite.

**Comment by Haliinen** [comment]
> The map effect in SMS is notoriously awful on all backends because it makes tons of EFB copies per frame.

But somehow D3D 11 **always** handled it gracefully, in my case? D3D 12 is a different one for now, I will test this issue later using D3D 11 just to make sure and report back. I have a moderately powerful PC. The map transition effect is not always smooth on D3D 12 but was always smooth on D3D 11.

> You can try turning on defer invalidating EFB peek cache in the advanced section of backend settings. It should be at the bottom and I know it's named something similar but not quite.

Thanks for the suggestion, JMC. I could give it a shot too perhaps, I have never turned this setting on before, since I never saw a need of it. D3D 11 was always smooth as silk for me anywhere w/o it.

**Comment by JMC47** [comment]
If you have any further questions, please take it to the forums.  This is more or less a development thread, and while it's okay to post a bug, I think support would be better suited for the forums.  https://forums.dolphin-emu.org/

But, if you read the article that did come with this merge, we did observe that GPU syncs are slower on D3D12, but draw calls are faster, which is what you're saying.  That's why that effect is slower.

**Comment by RinMaru** [comment]
Tried the lastest and games still lock up the entire computer with DX12

**Comment by Pik-a-boo** [comment]
I think GPU Texture Decoding is not working correctly and the textures got weird colors all over them.
I am using an AMD GPU that's inside my laptop.

**Comment by shuffle2** [comment]
Maybe it would be better to direct people to the issues page, and ask them to make meaningful reports so people can actually look into the problems.

**Pull request merged**
