### PR TITLE
[WIP] Resample dumped audio to 48khz

### PR DESCRIPTION
**Pull request by RisingFog**
A slight re-working of audio re-sampling code from now unnecessary avsync hack (which was used to properly sync audio and video together when dumped). This should resample 32khz audio to 48khz audio if it works properly.

Marking as WIP as it's currently untested, but also looking for feedback.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3542)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 137 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8_FMVJPXgPfd_gDy4N:-K8_FMVJPXgPfd_gDy4O:-218433512) ([raw file](https://github.com/dolphin-emu/dolphin/blob/fa61d3fca23edc9e09bc2ad6e523006025bd4734/Source/Core/AudioCommon/WaveFile.cpp#L137)):*
Don't use static state for things like this. This makes things unnecessarily fragile and error-prone (as well as thread-unsafe).

This can also be made a vector.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 146 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8_Frt2MSzi3WbCu5-n:-K8_Frt2MSzi3WbCu5-o:1611690137) ([raw file](https://github.com/dolphin-emu/dolphin/blob/fa61d3fca23edc9e09bc2ad6e523006025bd4734/Source/Core/AudioCommon/WaveFile.cpp#L146)):*
`count  * 3 / 2` should be its own variable with a name explaining what it means. This is duplicated in the realloc call (which can be tossed out with the use of std::vector)

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 135 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8_H5CN6t89WeTtU-t6:-K8_H5CN6t89WeTtU-t7:-128925534) ([raw file](https://github.com/dolphin-emu/dolphin/blob/438ae9629180a9f7723b298723730ed2e84c42fb/Source/Core/AudioCommon/WaveFile.cpp#L135)):*
This whole if statement body should be its own function. This has nothing to do with the `addition` of samples, only the resampling of them.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 140 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8_HWjsIuMj-uSXMuag:-K8_HWjtLr6aNsR-9U76:-1882854821) ([raw file](https://github.com/dolphin-emu/dolphin/blob/438ae9629180a9f7723b298723730ed2e84c42fb/Source/Core/AudioCommon/WaveFile.cpp#L140)):*
std::array

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 154 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8_Gih9vPCTRJnO0Y83:-K8_Gih9vPCTRJnO0Y84:2066816721) ([raw file](https://github.com/dolphin-emu/dolphin/blob/438ae9629180a9f7723b298723730ed2e84c42fb/Source/Core/AudioCommon/WaveFile.cpp#L154)):*
`i` can be a u32 and have the cast removed here.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 156 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8_GwnR6wB8uq6S54NK:-K8_GwnR6wB8uq6S54NL:-635953408) ([raw file](https://github.com/dolphin-emu/dolphin/blob/438ae9629180a9f7723b298723730ed2e84c42fb/Source/Core/AudioCommon/WaveFile.cpp#L156)):*
static_cast<int>

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542)*

**Comment by lioncash** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 137 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8_FMVJPXgPfd_gDy4N:-K8_HnexNUJxAewxuK5f:1079212119) ([raw file](https://github.com/dolphin-emu/dolphin/blob/fa61d3fca23edc9e09bc2ad6e523006025bd4734/Source/Core/AudioCommon/WaveFile.cpp#L137)):*
this applies to all of the static variables here, just to clarify.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 138 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8_HstHF_SOIGut_bb9:-K8_HstHF_SOIGut_bbA:617305515) ([raw file](https://github.com/dolphin-emu/dolphin/blob/438ae9629180a9f7723b298723730ed2e84c42fb/Source/Core/AudioCommon/WaveFile.cpp#L138)):*
This is assigned to but never actually used.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542)*

**Comment by JosJuice** [comment]
This will make getting synced audio for 48 KHz simpler (assuming it works), but do we want to drop the ability to get non-resampled audio for the majority of games? Is this worth having an option for?

**Comment by RisingFog** [comment]
@JosJuice it's replacing an assumption that all games are 32khz (which is not the case)

**Comment by JosJuice** [comment]
Yes, and that's good, but it's also removing the ability to get the unaltered audio data for 32 KHz games if I'm not misunderstanding it. Is that acceptable?

**Comment by JMC47** [comment]
Yes because the unaltered audio is stupid and broken.

**Comment by BhaaLseN** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 154 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8_PYDNS86Paa1Nqwa4:-K8_PYDNS86Paa1Nqwa5:1945958615) ([raw file](https://github.com/dolphin-emu/dolphin/blob/438ae9629180a9f7723b298723730ed2e84c42fb/Source/Core/AudioCommon/WaveFile.cpp#L154)):*
Does this resampling algorithm have a name or smth? That pattern sounds familiar, but I can't recall why or where I've seen it before...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542)*

**Comment by RisingFog** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 139 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8a-DEYVh_yixSol30a:-K8a-DEYVh_yixSol30b:-531244694) ([raw file](https://github.com/dolphin-emu/dolphin/blob/404d1af36eadc77fd18db60f87a5ad470abc27b2/Source/Core/AudioCommon/WaveFile.cpp#L139)):*
Will be making this an std::array in the next revision, marking here as a reminder.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542)*

**Comment by RisingFog** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 137 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8a-Xmk2TMEtskeprGQ:-K8a-Xmk2TMEtskeprGR:1014192150) ([raw file](https://github.com/dolphin-emu/dolphin/blob/404d1af36eadc77fd18db60f87a5ad470abc27b2/Source/Core/AudioCommon/WaveFile.cpp#L137)):*
Will be making this an std::vector in the next revision, marking here as a reminder.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542)*

**Comment by RisingFog** [comment]
Just tested this, current code results in lots of static audio. Looking to rectify this

**Comment by delroth** [comment]
This will be post 5.0. I don't think there is any good reason to tempt the fate and have this in 5.0.

**Comment by RisingFog** [comment]
@delroth no big deal, but would be nice to get implemented for usability sake.

**Comment by degasus** [comment]
Reviewed 1 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[Source/Core/AudioCommon/Mixer.cpp, line 178 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8sHG1kzXwtnDbtQ_lH:-K8sHG1lMX1qhwiXxa9S:-1445099621) ([raw file](https://github.com/dolphin-emu/dolphin/blob/404d1af36eadc77fd18db60f87a5ad470abc27b2/Source/Core/AudioCommon/Mixer.cpp#L178)):*
aiD is wrong here, you'll need the aiS sample rate. But try to fetch m_input_sample_rate instead....
To be honest, fetching the samplerate is likely better within the caller, so the mixer would know less about the emulation.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 135 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8sQs7xErWnTEAlTEhX:-K8sQs7xErWnTEAlTEhY:-880611011) ([raw file](https://github.com/dolphin-emu/dolphin/blob/404d1af36eadc77fd18db60f87a5ad470abc27b2/Source/Core/AudioCommon/WaveFile.cpp#L135)):*
Please also check if the destination sample rate is 48khz.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 143 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8sRsRKTNrSMLeVFG90:-K8sRsRKTNrSMLeVFG91:-1466763189) ([raw file](https://github.com/dolphin-emu/dolphin/blob/404d1af36eadc77fd18db60f87a5ad470abc27b2/Source/Core/AudioCommon/WaveFile.cpp#L143)):*
This case may happen, so it's not allowed to just skip the resampling here.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 147 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8sS9zybRElWE1Eey_w:-K8sS9zybRElWE1Eey_x:566642615) ([raw file](https://github.com/dolphin-emu/dolphin/blob/404d1af36eadc77fd18db60f87a5ad470abc27b2/Source/Core/AudioCommon/WaveFile.cpp#L147)):*
This condition is always true. I think you want to check if count_resampled > count_resampled_last_run?

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 149 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8sRbNKov8hU9G9os4V:-K8sRbNKov8hU9G9os4W:-438577927) ([raw file](https://github.com/dolphin-emu/dolphin/blob/404d1af36eadc77fd18db60f87a5ad470abc27b2/Source/Core/AudioCommon/WaveFile.cpp#L149)):*
Please use a std::vector instead, it calls realloc internally.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 154 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8sSjTYzezYKdBI6ZKB:-K8sSjTYzezYKdBI6ZKC:-1342676846) ([raw file](https://github.com/dolphin-emu/dolphin/blob/404d1af36eadc77fd18db60f87a5ad470abc27b2/Source/Core/AudioCommon/WaveFile.cpp#L154)):*
Please add a comment which resample way you've choosen. It's linear resampling, implemented as fixed ratio. Linear resampling is quite easy to implement, especially for fractional ratios. But for fixed ratios, there are by far better ones. As far as I know, the best and simplest one for 2->3 is to just upsample to 96khz by adding every sample for three times, then apply some kind of low pass filter, then skip ever second sample.

---

*[Source/Core/AudioCommon/WaveFile.h, line 34 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8sQhWSt5gEcTtrXpu6:-K8sQhWSt5gEcTtrXpu7:-1722793858) ([raw file](https://github.com/dolphin-emu/dolphin/blob/404d1af36eadc77fd18db60f87a5ad470abc27b2/Source/Core/AudioCommon/WaveFile.h#L34)):*
Should there also be the sample_rate for this function?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542)*

**Comment by degasus** [comment]
Review status: 2 of 3 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[Source/Core/AudioCommon/WaveFile.cpp, line 159 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542#-K8sUVO11U7PhA4yCCDT:-K8sUVO11U7PhA4yCCDU:1849377885) ([raw file](https://github.com/dolphin-emu/dolphin/blob/404d1af36eadc77fd18db60f87a5ad470abc27b2/Source/Core/AudioCommon/WaveFile.cpp#L159)):*
Please use an explicit size, we require at least 32bit here, "s32" instead of "int"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3542)*

**Comment by kamiyo** [comment]
I'm about to submit a PR soon for that FIR resampling of audio for the mixer, which will have a configurable filter, so the resampler object could be used here quite easily I think.

**Comment by RisingFog** [comment]
Closing this in favour of PR 3891.

**Pull request closed without merging**
