### PR TITLE
Add Nearest Neighbor Scaling

### PR DESCRIPTION
**Pull request by Sam-Belliveau**

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
I think we're better off reviving #9860 if we want this. I stopped working on it at the time IIRC because @iwubcode said they would overhaul the postprocessing shader system, but since that hasn't happened yet maybe we should just merge that in the meantime...

**Comment by iwubcode** [comment]
Yeah, sorry about that.  My "Please wait just a little longer" became a lot longer as my plans changed.

I'd still like to be selective on the types of post processing shaders we accept into the emulator (keeping things rather high quality with a focus on usability) but I'm happy to convert any of the shaders we need to the new system when it is available.  

#10722 might be worthwhile as I know that has come up a handful of times.

**Comment by MayImilae** [comment]
You may want to change the title of this PR to "Add Nearest Neighbor Scaling **GLSL Shader**".

If someone was wanting to put this as an option in the GUI I was going to have words, but this is good as a shader imo.

**Comment by AdmiralCurtiss** [comment]
If no one has any objections I think I'll just merge #10722 and #9860. Not sure if this one is still useful after that?

**Comment by iwubcode** [comment]
@AdmiralCurtiss - no objection from me!

**Comment by iwubcode** [comment]
> Not sure if this one is still useful after that?

Is anyone asking for this?  If not, I'd suggest closing this until someone requests it.  As mentioned, I'd rather add shaders that are heavily desired (and opt for standard ones if applicable).  It's a rather easy shader to provide on the forums/discord too.

**Pull request closed without merging**
