### PR TITLE
VideoBackends:Vulkan: Increase VMA Vulkan Version to 1.2

### PR DESCRIPTION
**Pull request by TellowKrinkle**
Fixes assertion failures people were getting in vk_mem_alloc after #13050

### CODE REVIEW

**Comment by iwubcode** [comment]
I did not get an assertion.  Though I am curious why we need to define `VMA_VULKAN_VERSION`?

**Comment by mackal** [comment]
Can confirm it's working here.

**Comment by TellowKrinkle** [comment]
> I did not get an assertion. Though I am curious why we need to define `VMA_VULKAN_VERSION`? It seems like it'll be easy to forget if we update Vulkan again.

Seems like a good idea, I don't see any reason we need to define it either

**Comment by TellowKrinkle** [comment]
...never mind
Apparently we undef `VK_NO_PROTOTYPES` so that vma will try to use the globally defined vulkan functions, but the source of those is not the vulkan headers, but our loader, so the only symbols defined are the ones we load.  So if we removed the define, a Vulkan header update could make VMA suddenly want more symbols that we don't load and fail to compile.

**Review by iwubcode — APPROVED** [review]

**Pull request merged**
