### PR TITLE
Pulseaudio: Support 5-channel surround, optional in UI

### PR DESCRIPTION
**Pull request by adamdmoss**
Adds ability - if DPL2 option set in Audio prefs - to decode DPL2 and send PulseAudio a 5-channel output.  (n.b. asking Pulse for 6-channel output gives 6.0 surround rather than 5.1, so 5.0 is it.)  Tested as doing a convincing job of working with Eternal Darkness and a 5.0/5.1 physical setup.
Stereo path left unchanged.

### CODE REVIEW

**Comment by MaJoRoesch** [comment]
@skidau ^

Does anyone have a 5.1 system on linux to test this with?

**Comment by magumagu** [comment]
Some quick web searching shows that pa_stream_new takes a pa_channel_map pointer... I think that lets you specify a true 5.1 setup.

**Comment by adamdmoss** [comment]
You're right, that's cool - didn't find that info on first search - I'll do it that way.

**Comment by adamdmoss** [comment]
Done - fork updated.  Now submits audio in 5.1.  LFE channel seems very quiet but I guess that's for the DPL2 decoder and the PA mixer levels to sort out between them. :)

**Comment by waddlesplash** [comment]
@dolphin-emu-bot rebuild

**Comment by adamdmoss** [comment]
space removed.

**Comment by skidau** [comment]
Thanks, would you squash the four commits into one?

**Comment by adamdmoss** [comment]
Ugh, squash fail.  Will try again or submit a new pull request from a different branch.

**Comment by adamdmoss** [comment]
Okay, squashed.  Looks like I didn't freak github out.

**Comment by skidau** [comment]
@dolphin-emu-bot rebuild

**Comment by skidau** [comment]
The bot says there are trailing whitespaces in this commit.  Would you please remove them?

**Comment by adamdmoss** [comment]
done, and resquashed.

**Comment by skidau** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
