### PR TITLE
GameINI: Enable fast disc speed for Dragon Quest X

### PR DESCRIPTION
**Pull request by leoetlino**
Speeds up the installer a lot (~20 minutes -> ~5).

### CODE REVIEW

**Comment by JMC47** [comment]
Note: this doesn't affect the main game, only the installer.

**Comment by JosJuice** [comment]
I understand why you would want to make the installer complete faster, but... It is a hack, and if we enable this hack by default for this title, what reason do we have to not enable this hack by default in titles where we simply would like to have shorter loading times?

I really should get started with my planned replacement of SUDTR with a setting that's adjustable and that the user can configure without using game INIs, so that it would be easier for users to choose whether they want to speed up the disc reading...

**Comment by JMC47** [comment]
This is just to make easier on the few devs that are testing this game lol.

**Comment by leoetlino** [comment]
Imo, the difference is that the installer is known to handle SUDTR absolutely fine, it's a net improvement in terms of install speed (unlike other titles where it just reduces loading times by a tiny amount), and it doesn't actually have any effect on the main game, since it doesn't use DI at all once installed.

**Comment by JosJuice** [comment]
It's just that I'm afraid that this will make it too hard for users to use the more accurate install speed if they want to, or that they'll be misled and think that the SUDTR is the speed that hardware actually ran at (because Dolphin does use accurate disc speed emulation for all other titles, after all).

**Comment by JMC47** [comment]
I'm in agreement with JosJuice's logic here to be honest.  The people developing it have already manually enabled it...

**Comment by leoetlino** [comment]
Hmm, true. I'll just enable it locally then

**Comment by delroth** [comment]
```
@delroth | I disagree on the DQX gameini thing, I was planning to do the same thing
@delroth | unlike most games here the disc timing change is critical
@delroth | for most games it's a tiny QoL improvement, here it's a 5x install time reduction
@delroth | and there is no bad effects possible on gameplay since the disc is only an install disc
@delroth | I think that warrants an exception to our usual policies.
```

**Pull request closed without merging**
