### PR TITLE
Remove remnants of old fake opcodes.

### PR DESCRIPTION
**Pull request by magumagu**
These are illegal opcodes, and should be treated as such.

### CODE REVIEW

**Comment by comex** [comment]
You're sure this doesn't break the various modes of HLEing functions?

**Comment by magumagu** [comment]
Yes, I'm sure; the current HLE mechanism never modifies emulated memory.

**Comment by Sonicadvance1** [comment]
I was talking about this last week actually. So awesome.

**Comment by lioncash** [comment]
Looks good to me.

**Pull request merged**
