### PR TITLE
Fix Frame Advance Hold Delay Changes

### PR DESCRIPTION
**Pull request by RisingFog**
Fixes cases of frame advance speed increase/decrease hotkey not actually doing anything.

### CODE REVIEW

**Comment by JosJuice** [comment]
LGTM. I've tested that this PR fixes the issue. It's essentially a revert of my suggestion here: https://github.com/dolphin-emu/dolphin/pull/2704#discussion-diff-40494017

**Comment by DwainiumB** [comment]
This seemed to work for a while, then it reverted back to the way it was.

**Comment by RisingFog** [comment]
Is that continuous holding? Or pressing and unpressing?

**Comment by DwainiumB** [comment]
Oh, it's continious holding and when you press/unpress, it does the same thing.

**Pull request merged**
