### PR TITLE
DolphinQt2 Builds on Visual Studio

### PR DESCRIPTION
**Pull request by rukai**
Adds build files for dolphinQt2 on visual Studio.
Copied from Waddlesplash's original build files and updated to account for changes in dolphin and to build dolphinQt2 instead.

I had to remove constexpr because the compiler gave error C2127: illegal initialization of 'constexpr' entity with a non-constant expression

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3571)

### CODE REVIEW

**Comment by lioncash** [comment]
Putting this here just for reference on [constexpr](https://github.com/qtproject/qtbase/blob/cfe891eeb8163f70cedda5099f76a42a5f7332d1/src/corelib/global/qcompilerdetection.h#L909) which apparently isn't enabled for trivial cases in MSVC

**Comment by spxtr** [comment]
Thanks for doing this.

Pity about the constexpr thing, but it's not the end of the world.

**Comment by Parlane** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3571)*

**Comment by Parlane** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3571)*

**Comment by MarcoEstevez** [comment]
Will it be eventually Qt versions on oficial builds?

**Comment by Parlane** [comment]
@MarcoEstevez Maybe :)

**Comment by MarcoEstevez** [comment]
Thanks

**Pull request merged**
