### PR TITLE
D3D: Move exclusive mode switching to UI thread.

### PR DESCRIPTION
**Pull request by Armada651**
This PR cleans up the implementation of exclusive fullscreen significantly by putting the UI thread in control of exclusive fullscreen switching. This eliminates all fullscreen switching code from `SwapImpl()` and moves it to `DoFullscreen()` and `OnActive()` where it can be implemented with significantly less code.

This should also take care of exclusive mode loops some people were encountering. And it allows you to enter/exit exclusive fullscreen even while paused.

To prevent concurrency errors with the backbuffer swap, this PR takes advantage of the deadlock fixes in PR #4439 by calling `PauseAndLock()` around exclusive fullscreen switching calls.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4443)

### CODE REVIEW

**Comment by lioncash** [comment]
*[Source/Core/DolphinWX/Frame.cpp, line 523 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWJzEhg-bnlJNesfTTP:-KWJzEhg-bnlJNesfTTQ:b-cwm2lx) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aab6b70868b5d785886b9d54f7d49848463e002e/Source/Core/DolphinWX/Frame.cpp#L523)):*
> ```cpp
>       if (SConfig::GetInstance().bRenderToMain)
>         m_RenderParent->SetFocus();
>       else if (RendererIsFullscreen() && g_ActiveConfig.ExclusiveFullscreenEnabled())
> ```

The `if` body should be braced if the `else if` body is.

You should probably extract this kind of thing to a helper function or something, this is pasted almost verbatim in two other places.

Something like:

```cpp
// Name condition to something more applicable
void DoThing(bool condition, bool set_fullscreen)
{
  if (!condition)
    return;

  const bool was_unpaused = Core::PauseAndLock(true);
  g_renderer->SetFullscreen(set_fullscreen);
  Core::PauseAndLock(false, was_unpaused);
}
```

or whatever would keep it reasonably self-contained.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443)*

**Comment by lioncash** [comment]
*[Source/Core/VideoCommon/RenderBase.h, line 76 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK0E3_VnS0X9NDE-EI:-KWK0E3a12frKt2AhQ_S:b-j8h39v) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aab6b70868b5d785886b9d54f7d49848463e002e/Source/Core/VideoCommon/RenderBase.h#L76)):*
> ```objc
>   virtual void SetViewport() {}
>   virtual void SetFullscreen(bool enable_fullscreen) {}
>   virtual bool IsFullscreen() { return false; }
> ```

`IsFullscreen()` should likely be a const function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443)*

**Comment by Armada651** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/DolphinWX/Frame.cpp, line 523 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWJzEhg-bnlJNesfTTP:-KWK0Yk5y33Y7HYKMDSQ:bwuynky) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aab6b70868b5d785886b9d54f7d49848463e002e/Source/Core/DolphinWX/Frame.cpp#L523)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> The `if` body should be braced if the `else if` body is.
> 
> You should probably extract this kind of thing to a helper function or something, this is pasted almost verbatim in two other places.
> 
> Something like:
> 
> ```cpp
> // Name condition to something more applicable
> void DoThing(bool condition, bool set_fullscreen)
> {
>   if (!condition)
>     return;
> 
>   const bool was_unpaused = Core::PauseAndLock(true);
>   g_renderer->SetFullscreen(set_fullscreen);
>   Core::PauseAndLock(false, was_unpaused);
> }
> ```
> 
> or whatever would keep it reasonably self-contained.
</details>
I agree, will move it to a function.

---

*[Source/Core/VideoCommon/RenderBase.h, line 76 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK0E3_VnS0X9NDE-EI:-KWK1GBJl_HMPg--muNw:b-kdnwho) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aab6b70868b5d785886b9d54f7d49848463e002e/Source/Core/VideoCommon/RenderBase.h#L76)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> `IsFullscreen()` should likely be a const function.
</details>
That would imply the overrides of this function should also be const. That's not a qualifier I can give to the overrides in D3D which call a DXGI function to check the state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443)*

**Comment by lioncash** [comment]
*[Source/Core/VideoCommon/RenderBase.h, line 76 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK0E3_VnS0X9NDE-EI:-KWKB-BmWq_F00B1ULPD:bg2ejdv) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aab6b70868b5d785886b9d54f7d49848463e002e/Source/Core/VideoCommon/RenderBase.h#L76)):*
<details><summary><i>Previously, Armada651 (Jules Blok) wrote…</i></summary>
> That would imply the overrides of this function should also be const. That's not a qualifier I can give to the overrides in D3D which call a DXGI function to check the state.
</details>
Not sure I follow why that would even matter.`D3D::GetFullscreenState();` is part of a namespace. const would be OK in this instance since it's not modifying anything in the class itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443)*

**Comment by lioncash** [comment]
Review status: 0 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/DolphinWX/Frame.cpp, line 1183 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK9afBJlKlbo4O90sL:-KWK9afBJlKlbo4O90sM:bfms2pi) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aa0e4472c0ff0091ff6e699894b5ef674e6c7647/Source/Core/DolphinWX/Frame.cpp#L1183)):*
> ```cpp
> void CFrame::DoExclusiveFullscreen(bool enable_fullscreen)
> {
>   if (g_renderer && g_renderer->IsFullscreen() != enable_fullscreen)
> ```

You can just do

```cpp
if (!g_renderer || g_renderer->IsFullscreen() == enable_fullscreen)
    return;
```

which moves the main body back an indentation level.

---

*[Source/Core/DolphinWX/Frame.h, line 109 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK9Rg1s7Ir3BGIAk3g:-KWK9Rg2ZD3125evaG0Y:b-f8lbmk) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aa0e4472c0ff0091ff6e699894b5ef674e6c7647/Source/Core/DolphinWX/Frame.h#L109)):*
> ```objc
>   bool RendererIsFullscreen();
>   void DoFullscreen(bool bF);
>   void DoExclusiveFullscreen(bool bF);
> ```

`bool enable_fullscreen`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443)*

**Comment by Armada651** [comment]
Review status: 0 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/VideoCommon/RenderBase.h, line 76 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK0E3_VnS0X9NDE-EI:-KWKCitaozsTEue_l8PY:b-3jj6te) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aab6b70868b5d785886b9d54f7d49848463e002e/Source/Core/VideoCommon/RenderBase.h#L76)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> Not sure I follow why that would even matter.`D3D::GetFullscreenState();` is part of a namespace. const would be OK in this instance since it's not modifying anything in the class itself.
</details>
But I think that's a bit disingenuous, you'd expect a const function to be safe to call and not make any changes to any state whatsoever. That's not a guarantee that's given by GetFullscreenState(), in fact with a different parameter it'll actually increment a reference counter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443)*

**Comment by lioncash** [comment]
*[Source/Core/VideoCommon/RenderBase.h, line 76 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK0E3_VnS0X9NDE-EI:-KWKDsCTa9-pbeDZqHoS:b-mznub1) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aab6b70868b5d785886b9d54f7d49848463e002e/Source/Core/VideoCommon/RenderBase.h#L76)):*
<details><summary><i>Previously, Armada651 (Jules Blok) wrote…</i></summary>
> But I think that's a bit disingenuous, you'd expect a const function to be safe to call and not make any changes to any state whatsoever. That's not a guarantee that's given by GetFullscreenState(), in fact with a different parameter it'll actually increment a reference counter.
</details>
`const` on a class function applies specifically to the class it's implemented in (hence why they're called const *member*-functions),  not global state. It indicates class state is not modified, which it isn't. const is correct here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443)*

**Comment by Armada651** [comment]
Review status: 0 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/DolphinWX/Frame.h, line 109 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK9Rg1s7Ir3BGIAk3g:-KWKG-98_81yWW4AV6oj:b-je7i97) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aa0e4472c0ff0091ff6e699894b5ef674e6c7647/Source/Core/DolphinWX/Frame.h#L109)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> `bool enable_fullscreen`
</details>
Should I change the other one too?

---

*[Source/Core/VideoCommon/RenderBase.h, line 76 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK0E3_VnS0X9NDE-EI:-KWKG3YUGvQqTDBLbB2B:bwp5t02) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aab6b70868b5d785886b9d54f7d49848463e002e/Source/Core/VideoCommon/RenderBase.h#L76)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> `const` on a class function applies specifically to the class it's implemented in (hence why they're called const *member*-functions),  not global state. It indicates class state is not modified, which it isn't. const is correct here.
</details>
By that logic I could make SetFullscreen() const.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443)*

**Comment by lioncash** [comment]
*[Source/Core/VideoCommon/RenderBase.h, line 76 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK0E3_VnS0X9NDE-EI:-KWKG902kt4OQ0rNWOaF:brgyjgs) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aab6b70868b5d785886b9d54f7d49848463e002e/Source/Core/VideoCommon/RenderBase.h#L76)):*
<details><summary><i>Previously, Armada651 (Jules Blok) wrote…</i></summary>
> By that logic I could make SetFullscreen() const.
</details>
That doesn't really refute anything I said, but OK? Do that if you *really* want to, but does that make sense in terms of the immediate class interface itself, especially if used in other backends? One queries for information, one has the literal written indication of modifying. A different implementation of a renderer may set a class variable in `SetFullscreen()`. It's why the other setters aren't const either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443)*

**Comment by Armada651** [comment]
Review status: 0 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/VideoCommon/RenderBase.h, line 76 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK0E3_VnS0X9NDE-EI:-KWKavxuUs-7q5wC7Ay8:b-7eug6b) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aab6b70868b5d785886b9d54f7d49848463e002e/Source/Core/VideoCommon/RenderBase.h#L76)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> That doesn't really refute anything I said, but OK? Do that if you *really* want to, but does that make sense in terms of the immediate class interface itself, especially if used in other backends? One queries for information, one has the literal written indication of modifying. A different implementation of a renderer may set a class variable in `SetFullscreen()`. It's why the other setters aren't const either.
</details>
I'll make the change, just wanted to clarify the reasoning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443)*

**Comment by Armada651** [comment]
Review status: 0 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/DolphinWX/Frame.cpp, line 1183 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK9afBJlKlbo4O90sL:-KWUYTsMkUr3rz0KXQAa:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aa0e4472c0ff0091ff6e699894b5ef674e6c7647/Source/Core/DolphinWX/Frame.cpp#L1183)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> You can just do
> 
> ```cpp
> if (!g_renderer || g_renderer->IsFullscreen() == enable_fullscreen)
>     return;
> ```
> 
> which moves the main body back an indentation level.
</details>
Done.

---

*[Source/Core/DolphinWX/Frame.h, line 109 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK9Rg1s7Ir3BGIAk3g:-KWUYXU6QGvAqoxI-fny:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aa0e4472c0ff0091ff6e699894b5ef674e6c7647/Source/Core/DolphinWX/Frame.h#L109)):*
<details><summary><i>Previously, Armada651 (Jules Blok) wrote…</i></summary>
> Should I change the other one too?
</details>
Done.

---

*[Source/Core/VideoCommon/RenderBase.h, line 76 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK0E3_VnS0X9NDE-EI:-KWUYX619GTMe_JLlUqw:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aab6b70868b5d785886b9d54f7d49848463e002e/Source/Core/VideoCommon/RenderBase.h#L76)):*
<details><summary><i>Previously, Armada651 (Jules Blok) wrote…</i></summary>
> I'll make the change, just wanted to clarify the reasoning.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443)*

**Comment by lioncash** [comment]
Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---

*[Source/Core/DolphinWX/Frame.h, line 109 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443#-KWK9Rg1s7Ir3BGIAk3g:-KWVCgmiT3bpHjqNPUDL:b5aw5gg) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aa0e4472c0ff0091ff6e699894b5ef674e6c7647/Source/Core/DolphinWX/Frame.h#L109)):*
<details><summary><i>Previously, Armada651 (Jules Blok) wrote…</i></summary>
> Done.
</details>
ah, sorry about not answering this question. I never got the notification for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4443)*

**Pull request merged**
