### PR TITLE
Reword "Toggle Frame Limit" to better explain function

### PR DESCRIPTION
**Pull request by ASSympt0te**
This addresses [Issue #9337](https://bugs.dolphin-emu.org/issues/9337) by more clearly labeling the function of the "Toggle Frame Limit" hotkey to "Disable Frame Limit".

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3637)

### CODE REVIEW

**Comment by JosJuice** [comment]
The .po files shouldn't be updated manually. They're handled by Transifex and the internationalization bot.

**Comment by ASSympt0te** [comment]
Well darn, I really screwed this one up. Is simply changing the _trans enough to apply the change?

**Comment by lioncash** [comment]
Yep

**Comment by degasus** [comment]
I agree with "disable", but could you please also change "frame limit" to something better? We call it "emulation speed" now.

**Pull request closed without merging**
