### PR TITLE
Android: Modernize theming system

### PR DESCRIPTION
**Pull request by t895**
themes.xml now contains a collection of colors, attributes, and styles. No visuals have changed, but this will allow for a more flexible theming system in the future for custom day/night/etc themes. This also removes a bunch of redundant code that is now written as global styles and inherited themes.

### CODE REVIEW

**Comment by Simonx22** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
You are effectively reverting PR #8718 here. Have you tested that this doesn't break TvMainActivity?

**Comment by t895** [comment]
I have not, I've actually had trouble getting dolphin working on an android tv emulator (even before this commit). Would you mind sharing a way to test that so I'm not creating a regression?

**Comment by JosJuice** [comment]
What I do is I run TvMainActivity on my phone. In Android Studio, go to Edit Configurations, set Launch to the option Specified Activity, and enter org.dolphinemu.dolphinemu.TvMainActivity as the activity name.

**Comment by t895** [comment]
OH, that's really cool. It does crash, but I found a fix.

**Comment by JosJuice** [comment]
Ah, nice to see that there's a simpler solution than what I went with! But is there a particular reason why it's using FilePickerAlertDialogTheme? I suppose FilePickerAlertDialogTheme and DolphinDialogBase are very similar, but just naming-wise it feels weird... If you want to go with FilePickerAlertDialogTheme, maybe rename it to DolphinDialogBase and remove the old DolphinDialogBase?

**Comment by t895** [comment]
I could actually just get rid of the FilePickerAlertDialogTheme by extending the definition for DolphinDialogBase with colorPrimaryDark and colorAccent. Then everything could use DolphinDialogBase and work the same.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Review by JosJuice — APPROVED** [review]
Seems reasonable. But I'd say let's wait with merging this until after the next beta, just in case there are other surprises like that Android TV crash.

By the way, I've sent you an invite that will let your pull requests get built automatically. It should be in your emails by now.

**Comment by t895** [comment]
Oh wow, thank you. I just accepted it.

I'll squash my commits and wait until after the upcoming beta for a merge.

**Pull request merged**
