### PR TITLE
CheatSearchTab: Check Core state instead of checking a memory pointer.

### PR DESCRIPTION
**Pull request by Armada651**
Fixes [issue 8714](https://code.google.com/p/dolphin-emu/issues/detail?id=8714).

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
Should be changed a few lines down in `FilterCheatSearchResults()` too.

Frankly I'm more curious why the memory pointer doesn't get null'd after emulation ends but this probably works.

**Comment by Armada651** [comment]
@AdmiralCurtiss I think that's the kind of behaviour no one should rely on, especially not for something as important as state checking.

**Comment by phire** [comment]
I think you actually want Core::IsRunning()

Otherwise you will be unable to use Cheat Search while dolphin is paused, which is kind of necessary at times.

**Comment by Armada651** [comment]
@phire `IsRunningAndStarted()` checks if the CPU thread has started, it is unrelated to whether it is paused.

**Pull request merged**
