### PR TITLE
NetPlay: Reuse WiiSave code for save syncing

### PR DESCRIPTION
**Pull request by leoetlino**
It's simpler to just reuse the existing WiiSave serialization
and deserialization code and treat the saves as binary blobs,
especially when netplay doesn't actually look at any of the information
in the WiiSave structures.

To ensure save blobs can be compressed well, this adds an option to
WiiSave to disable encryption.

Bonus: we don't need to hold every single save file in memory at the
same time, and compressing entire save blobs will probably result in
smaller sizes compared to compressing each file separately.

### CODE REVIEW

**Comment by JMC47** [comment]
I can confirm that Sync All Wii Saves functions as *currently* expected with this build.

**Comment by Techjar** [comment]
Doesn't this break writing the Mii data to the temporary FS?

**Comment by leoetlino** [comment]
I don't think so -- the Mii data syncing code is separate and this PR doesn't touch it at all

**Comment by Techjar** [comment]
Oh yeah, up where it says `// Read the Mii data`, forgot about that. All good then.

**Comment by leoetlino** [comment]
Forget this PR, I'm going to use another approach for save syncing.

**Pull request closed without merging**
