### PR TITLE
mbedtls: port aesni implementation to intrinsics

### PR DESCRIPTION
**Pull request by shuffle2**
this makes the fast path available to msvc

it is just a mechanical conversion of the inline asm, no real improvements on top of existing code.

the gcm impl is removed for now (dolphin does not use it).

see https://github.com/Mbed-TLS/mbedtls/pull/5969 (I kind of don't expect it to go anywhere on mainline tbh)

dolphin also uses a decent amount of sha1 (at least based on # of references to `mbedtls_sha*`), so maybe that would be worth porting to "sha-ni" as well. it would probably make sense to investigate both for armv8 as well (considering mbedtls is owned by arm, you'd hope mbedtls 3.x just improved the situation on arm processors, at least...).

i looked for a bit for some library to replace mbedtls with, but didn't really find anything great.

### CODE REVIEW

**Comment by shuffle2** [comment]
any thoughts about this?

i think it would be nice to implement our own aes/sha1/sha2 in dolphin (then we can optimize for the archs we care about), and stop using mbedtls for those primitives...but it could be done after merging this :)

**Comment by AdmiralCurtiss** [comment]
I think it's a bit weird to have modified code in externals, but optimization is always nice. What do we even use this for?

**Comment by shuffle2** [comment]
dolphin uses mbedtls for any aes, md5, and sha (try grepping `mbedtls_aes`). We mainly use aes when reading wii discs and handling some ios commands (`IOSC::DecryptEncrypt`). Accelerating the digest algos could help improve disc verification time (or actually doing the hashtree check on the fly).

otherwise we only really use mbedtls for ios' SSL emulation, which i'm imagining we'd probably just keep using.

**Comment by iwubcode** [comment]
@shuffle2  - just curious, why was the upstream fix closed?  Looks like they put it into their queue for implementation (?) but then when you closed it, it was marked "Done".  Were they expecting you to do the work?

**Comment by shuffle2** [comment]
i only have the same information you can see on the thread

**Comment by shuffle2** [comment]
here's an example (i guess `verify` operates on the plaintext)

```
PS C:\src\dolphin\Binary\x64> Measure-Command { .\DolphinTool_aesni.exe verify -i 'E:\Games\Nintendo Wii\Mario Kart Wii NTSC-U.iso' }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 11
Milliseconds      : 64
Ticks             : 110640790
TotalDays         : 0.000128056469907407
TotalHours        : 0.00307335527777778
TotalMinutes      : 0.184401316666667
TotalSeconds      : 11.064079
TotalMilliseconds : 11064.079



PS C:\src\dolphin\Binary\x64> Measure-Command { .\DolphinTool.exe verify -i 'E:\Games\Nintendo Wii\Mario Kart Wii NTSC-U.iso' }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 34
Milliseconds      : 328
Ticks             : 343288220
TotalDays         : 0.000397324328703704
TotalHours        : 0.00953578388888889
TotalMinutes      : 0.572147033333333
TotalSeconds      : 34.328822
TotalMilliseconds : 34328.822
```

obviously the speedup is more interesting for on-demand reads during emulation, but this demonstrates the speed difference is easy to see.

**Comment by iwubcode** [comment]
@shuffle2 - well, I guess was more curious why *you* closed the review.

From an implementation standpoint, seems like a huge win.  Haven't actually looked at the code yet.

**Comment by shuffle2** [comment]
I'm working on a different version of this, which implements AES fully in dolphin and doesn't use mbedtls. It is faster than mbedtls and has other advantages; I'll open a different PR when it's ready.

**Comment by AdmiralCurtiss** [comment]
Yeah, that's probably the better way anyway. I admit I kinda forgot about this PR...

**Pull request closed without merging**
