### PR TITLE
Remove AM Baseboard

### PR DESCRIPTION
**Pull request by JosJuice**
Let's stop pretending that we support Triforce emulation. Keeping this code around just in case someone will make major improvements in the future isn't really worth it.

I'm keeping the Triforce game INIs so users will know that the compatibility rating for Triforce games is 1 star (broken).

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4109)

### CODE REVIEW

**Comment by RisingFog** [comment]
This needs a rebase.

**Comment by JMC47** [comment]
I think this is a needed step in actually getting TriForce emulation going someday, rather than providing the false pretense that Dolphin actively targets the TriForce.

**Comment by JosJuice** [comment]
Rebased.

All mentions of Triforce in Readme.md have been removed in this PR already. I've searched through the repository, and the word "Triforce" is no longer anywhere other than in game INIs (both to denote Triforce games and to describe some Zelda cheats).

**Comment by Fallcrest** [comment]
Well, I honestly expected that this was coming. Kind of sad, but expected. Maybe one day...

**Comment by JMC47** [comment]
This is a good day for TriForce emulation; hopefully someone else will come along and see this.  I'll put a feature in the progress report to let everyone know that Dolphin is no longer actively pursuing TriForce emulation.

**Comment by legend800** [comment]
Sad day. (1) We're stripping out functional code that just needs TLC (I use one of the older Triforce builds that has excellent playability) and (2) we're saying that even the pursuit of Triforce emulation is dead. I can understand the former but not the latter. Why are we no longer pursuing this. For me, and my 50+ Wii/GC games, that's all I need - Triforce emulation. Everything well works almost perfectly. If the ONLY progress ever made on Dolphin from here on out is on Triforce support, than I would be 100% content. Really hope someone picks up this component and finally provides us (approved) emulation of these amazing arcade games.

**Comment by shuffle2** [comment]
WTFFFFFFFFFF!!!!

**Comment by delroth** [comment]
@legend800 to clarify, Triforce emulation in Dolphin is definitely something we'd integrate. But the current implementation serves ~no purpose and confuses people that think Dolphin can play Triforce games. We just need to find someone interested in Triforce emulation that can also work with the rest of the project towards a proper implementation (unlike the old Triforce branch from crediar which was basically a code drop of an unreviewable mess).

**Comment by shuffle2** [comment]
The preexisting triforce code would at least successfully emulate some soccer game, i remember. it was also capable of running the triforce bootloader/game loader. I hardly consider that ~no purpose, considering it was working quite fine - afaik the main limitations were around the fact that most triforce games required additional dedicated peripherals to be emulated (such as save cards, steering wheels, etc) - it seems misguided to remove.

I will be interested to see how much more amazing the SI/EXI code gets, now that the functioning triforce support is removed...

**Comment by waddlesplash** [comment]
FWIW, I had an almost-working rebased `triforce` branch here: https://github.com/waddlesplash/dolphin/tree/triforce_merge

Ironically, it probably needed @JosJuice' DVDInterface expertise, because I'm 80% sure that it was hanging somewhere in there (I think I borked that upgrade, not knowing much about that code)...

**Comment by waddlesplash** [comment]
(And if you got that merged, virtually all Triforce games would at least boot; even if controls didn't work.)

**Comment by JMC47** [comment]
Then why don't you make a Pull Request for it?  Having the code out there for review would help find bugs, even if it's WIP/RFC or whatever and not ready for merge.

**Comment by waddlesplash** [comment]
>  Having the code out there for review would help find bugs, even if it's WIP/RFC or whatever and not ready for merge.

Because it needed a bunch of debugging that was totally beyond my skill level, and I've been so swamped that I haven't had a chance to actually talk to Jos about looking at it to see what I screwed up.

**Comment by Fallcrest** [comment]
Where was/is the Triforce Branch source code? The download page never had any links to code. Was it on the old Dolphin Google Code page and never moved to GitHub?

**Comment by JosJuice** [comment]
@waddlesplash The way the code is calling `DVDRead` from `AMBaseboard.cpp` isn't thread-safe. If you want a quick and dirty solution, call `DVDThread::WaitUntilIdle()` right before `DVDRead`. A more proper solution would be to do the disc read in `DVDInterface` the same way as other disc reads.

**Comment by waddlesplash** [comment]
> Where was/is the Triforce Branch source code? The download page never had any links to code. Was it on the old Dolphin Google Code page and never moved to GitHub?

The branch was lost, but the repository was apparently never GC'ed, so all the objects were still there. The "triforce" branch on my fork restores the branch as it was before.

>EDIT: Though now that I think about it, that's probably not the problem... If disc reads are being done using AMBaseboard, there wouldn't be any disc reads done the "usual" way, right? So there wouldn't be any conflicts from DVDThread trying to access the volume.

Yes, I believe that's the case. I suppose we should move this discussion to IRC, though.

**Comment by HyperScorpio** [comment]
So sad, never ever a change to play Virtua Striker 4 on a PC. The 2002 is very bad on the first branch versions. 😞 😢

**Pull request merged**
