### PR TITLE
Remove explicit subwoofer/LFE channel from Pulseaudio and OpenAL

### PR DESCRIPTION
**Pull request by adamdmoss**
DPL2Decoder leaves the bass in all surround channels, so it's not appropriate to use its LFE output - too bassy.

### CODE REVIEW

**Comment by skidau** [comment]
@dolphin-emu-bot rebuild

**Comment by adamdmoss** [comment]
@dolphin-emu-bot Not likely caused by this change...

**Comment by adamdmoss** [comment]
squashed-in the whitespace change.

**Comment by skidau** [comment]
@dolphin-emu-bot rebuild

**Comment by delroth** [comment]
Ignore the -nv errors, I need to work on its stability.

**Comment by skidau** [comment]
Star Wars Force Unleashed II's intro still sounds thunderous to me after this patch... oh well.

**Pull request merged**
