### PR TITLE
Externals: Add a stripped down version of minizip

### PR DESCRIPTION
**Pull request by Zexaron**
Cherry-picked https://github.com/dolphin-emu/dolphin/pull/6178/commits/34707e9c2e825196134d5d62f6ca9874cf64593b - I was told that PR will probably never get finished. 

It will be needed for an auto-updater for #7110 in the future and possibly other things.

### CODE REVIEW

**Comment by Zexaron** [comment]
It may be a bit premature, I don't mind leaving it until later, except if someone else needs it before that happens, they'd need it in the code beforehand, otherwise they'd have to manually get it first for themsefls.

I guess it's a time saver then, for those that are quite busy it may come handy.

**Comment by ryao** [comment]
This broke compilation on Gentoo Linux. I have filed a downstream bug report regarding this:

https://bugs.gentoo.org/671900

```
CMake Error at CMakeLists.txt:565 (add_subdirectory):             
  add_subdirectory given source "Externals/minizip" which is not an existing
  directory. 
```

The failure occurs because Gentoo removes bundled libraries unless they are explicitly whitelisted. If it is not too much trouble, it would be appreciated if people would ping the Gentoo maintainer about new bundled libraries.

**Comment by delroth** [comment]
I'm sorry, are you complaining that Dolphin doesn't build when you randomly go and delete directories from our source code? Yeah, that tends to happen.

Whoever maintains the package for your distro is relying on assumptions that we never claimed to guarantee. We can't go and increase our workload for every single distro that goes and unilaterally decides to rely on implementation details. Especially not in our git master branch.

**Comment by riking** [comment]
@ryao - The Gentoo code is also assuming that any library that Dolphin adds will never be the same as the name of a folder in the repository root: https://gitweb.gentoo.org/repo/gentoo.git/tree/games-emulation/dolphin/dolphin-9999.ebuild?id=2f26b496e55dddef5d8fce650becb4c3db4cc450#n95

This seems like a similarly bad assumption.

**Pull request merged**
