### PR TITLE
GZLE01 & GZLP01 – Add Cheatcode to Remove Distance Blur

### PR DESCRIPTION
**Pull request by KAMiKAZOW**
Remove Distance Blur – Useful for HD resolutions. Code obtained from https://wiki.dolphin-emu.org/index.php?title=The_Legend_of_Zelda:_The_Wind_Waker#Removing_Distance_Blur

### CODE REVIEW

**Comment by JMC47** [comment]
Looks fine to me.  I'd prefer you change the name of the Pull Request before it's merged as not to confuse users on the download page.

Maybe "GZLP01 - Add Cheatcode to Remove Distance Blur" or something along those lines.

**Comment by KAMiKAZOW** [comment]
OK, done

**Comment by JosJuice** [comment]
The commit name looks nice, but JMC was actually asking you to change the pull request name (since that's what shows up on the download page). It's the name that can be edited with the Edit button at the top of this page.

**Comment by gamemasterplc** [comment]
you might want to add the NTSC version while you are at it

**Comment by KAMiKAZOW** [comment]
Done NTSC now as well

**Pull request merged**
