### PR TITLE
Remove geckocodes.org downloading because the site shut down

### PR DESCRIPTION
**Pull request by JosJuice**

### CODE REVIEW

**Comment by Miksel12** [comment]
I reckon `#include "Common/HttpRequest.h"` should also be removed.

**Comment by iwubcode** [comment]
Do we have an alternative in mind?  I only used it a bit but this was really nice to quickly pull up codes.  Maybe it's time to add resource packs that contain a list of searchable codes...

**Comment by cobalt2727** [comment]
http://web.archive.org/web/20200824101754/https://geckocodes.org
How feasible would it be to host a mirror on Dolphin's website?

**Comment by SirMangler** [comment]
Geckocodes is now directing people to https://gamehacking.org/ which still hosts a lot of codes, both AR and Gecko. Perhaps that would be a decent alternative. It appears to be missing codes on various games, but some more popular games still have more than enough codes to make it worthwhile. As a plus the site also appears to offer pages for individual game versions, which I believe geckocodes didn't do.

Here's the page for Metroid Prime as an example: https://gamehacking.org/game/54210

**Comment by cobalt2727** [comment]
https://codes.rc24.xyz/
Got something you guys might be interested in - the RiiConnect24 team has apparently mirrored the entire geckocodes.org site.

**Comment by JosJuice** [comment]
@cobalt2727 Opened as PR #9133. (I was actually contacted about this by someone who does RC24 stuff at around the same time you posted this, as it happens.) It seems to work perfectly with just a simple URL replace.

**Comment by jordan-woyak** [comment]
Closing in favor of #9133.

**Pull request closed without merging**
