### PR TITLE
update sdl

### PR DESCRIPTION
**Pull request by shuffle2**
maybe related issues (current open SDL bugs):
https://bugs.dolphin-emu.org/issues/13045
https://bugs.dolphin-emu.org/issues/13117
https://bugs.dolphin-emu.org/issues/13125

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
sure

**Comment by TellowKrinkle** [comment]
Is there a reason this commit was chosen for the update?  It's missing the fix for https://bugs.dolphin-emu.org/issues/13155 (https://github.com/libsdl-org/SDL/commit/2c6995778e941524a4857b55d4e35745313c924a)

**Comment by TellowKrinkle** [comment]
Ahh, I assumed it listed the most recent on top (like it does in other commit list views), saw the top being "last month", and was like "???"

Yay for them swapping the commit display order with a view that looks otherwise identical

**Comment by tvoracek** [comment]
Latest experimental/canary crashes during update because of outdated C++ resdistributable. Why this is not handled in installer?

**Comment by TellowKrinkle** [comment]
Was that caused by an SDL update?  If not, you should post that on (https://bugs.dolphin-emu.org)

**Pull request merged**
