### PR TITLE
Qt/Settings: Add Cancel button to USB passthrough device dialog

### PR DESCRIPTION
**Pull request by Z1ni**
https://bugs.dolphin-emu.org/issues/11125

Dialog with dismiss button

### CODE REVIEW

**Comment by MayImilae** [comment]
This is fairly straightforward but, screenshot please!

**Comment by Z1ni** [comment]
I noticed that I wrote Close on the button 😄 
I'll change it to Cancel, as it should be.

**Comment by Helios747** [comment]
@dolphin-emu-bot rebuild

**Comment by Helios747** [comment]
Please setup and run clang-format (Which can be installed by installing LLVM) as documented here

https://github.com/dolphin-emu/dolphin/blob/master/Contributing.md#intro-aims

Once you pass linter I see no reason to keep this PR waiting

**Comment by Zexaron** [comment]
Actually I was just about to mention, forgot whole day, including @BhaaLseN also raised this today, if that button should say "Close" rather than "Cancel". It's been 5 months since I created the bug ticket and I'm not sure I really meant "Cancel", if I did then I forgot the thought process for that specific reason.

**Comment by Z1ni** [comment]
"Cancels" seems good to me, as the user cancels the addition of a new USB device. "Close" does not necessarily imply that.
But that's just my two cents.

**Comment by Zexaron** [comment]
Yes that's indeed correct in a way, I was just about to say, it may not be that of a big deal ofcourse, just raising the consistency thing.

However here's a stronger point after I did more thinking, "Cancel" would have to actually remove any of those devices from the whitelist (which isn't visible on this dialog, this list is showing all the available ones to select - @BhaaLseN) added while the dialog was open, IMHO.

**Comment by Tilka** [comment]
I like how it is now.

**Pull request merged**
