### PR TITLE
VideoConfig: Use "GFX.ini" for both D3D and OGL.

### PR DESCRIPTION
**Pull request by degasus**
They share the same format, so there is no need to separate their configs.

### CODE REVIEW

**Comment by degasus** [comment]
Do we want to have fallbacks? In my opinion, it might be better to just use the default configuration. Else there will be some users still using the separate config files....

**Comment by JosJuice** [comment]
I think the Android code needs to be updated? It contains references to gfx_opengl. https://github.com/dolphin-emu/dolphin/blob/6425ddcbe7b533224adf204a7f1c968a73a470a7/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/UserPreferences.java

**Comment by degasus** [comment]
@JosJuice done

**Comment by degasus** [comment]
I've changed it in a way that the first used configuration will be stored as GFX.ini now. So everyone will upgrade to the shared ini, but the first used is copied.

**Comment by JosJuice** [comment]
LGTM.

**Comment by skidau** [comment]
Would putting the video settings in dolphin.ini be simpler to manage than in a new gfx.ini file?

**Comment by degasus** [comment]
@skidau I'm not sure. It would be harder to detect if we still need to load the old file.

**Pull request merged**
