### PR TITLE
Updated and added new Action replay Codes

### PR DESCRIPTION
**Pull request by raziel23x**
Went on AR Code Website and Added codes to Selected Games and minor
changes to ini files.

Also I had so do some deep searching to find some of these codes. the codes that was created that was not on the Codejunkies website I ran the games on the emulator and tested the codes

### CODE REVIEW

**Comment by JosJuice** [comment]
The codes for PZLE01 - The Legend of Zelda: Collector's Edition should indicate which of the games on the disc they are for. (I assume all are for Zelda 1?)

**Comment by raziel23x** [comment]
Sorry for that I believe so but I need to retest the codes to be sure

**Comment by raziel23x** [comment]
I Am going to remove PZLE01.ini from the pull request for now until i can organize the cheats and make it more cleaner before I add it back I also have to fix the English translations of the Chapter names for GFEJ01 - FIRE EMBLEM GC JAP but taht will be in another Pull request if this gets merged Before i play through the game and correct the name changes

**Comment by JosJuice** [comment]
Can't you use an existing list of chapter names? This one, for instance: http://fireemblem.wikia.com/wiki/List_of_chapters_in_Fire_Emblem:_Path_of_Radiance
Another option is to simply type the names in Japanese, because it's reasonable to assume that people playing the Japanese version of the game prefer Japanese. I don't know if Dolphin is able to handle that correctly, though. Only ASCII has been used in cheat code names in the past.

And thanks for contributing to Dolphin :)

**Comment by raziel23x** [comment]
The codes for PZLE01 - The Legend of Zelda: Collector's Edition Have been Corrected the AR codes are now labeled with a fake code to allow you to know which game in the collection the codes work for

**Comment by raziel23x** [comment]
Well with the GFEJ01 - FIRE EMBLEM GC JAP I am working on translating that game into English because of the jap version of the game has a mode that is not found in the English one and many who have used my patch are English speaking users like me.

I had to use Google Translate to translate the AR codes listed for that game titles into English and thanks to that link above you listed I am using them to translate the chapters names and now updating the AR codes but I am not sure if it can handle it as well so adspect another revision shortly i just updated the Zelda games codes and now working on fire emblem

**Comment by raziel23x** [comment]
Updated GFEJ01 - FIRE EMBLEM GC JAP
Okay Completed the Translations of the chapter names into there english counter parts thanks to that link provided by josjuice

**Comment by raziel23x** [comment]
Okay I did some more work on the PZLE01 - The Legend of Zelda: Collector's Edition
and added support for all the games inside the collectors edition hopefully This will fix everything and sorry for all the pull request inside this PR trying to fix any issues

**Comment by raziel23x** [comment]
It seems this PR became more work then i wanted originally to be but I think i am finally done with all the changes

**Comment by lioncash** [comment]
Can you squash all the changes into one commit please?

**Comment by raziel23x** [comment]
I do not know how to do this with github for windows

**Comment by lioncash** [comment]
Consider using the command line and read http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by raziel23x** [comment]
i broke something going to rework this completely

**Pull request closed without merging**
