### PR TITLE
[WIP] FileUtil: IOFile should use the WinAPI on Windows

### PR DESCRIPTION
**Pull request by Warepire**
This is based on delroth's IOFile PR #3524).
Work around the need for the CRT on file operations in Windows as the CRT is broken in this regard. Use more stable APIs by default.

TODO:
- [x]  Currently hangs if PerfMap is enabled.
- [ ] Test support with files > 4GB

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3661)

### CODE REVIEW

**Comment by Warepire** [comment]
I think this covers everything that the previous PR didn't finish. Except for the testing part.

**Comment by JosJuice** [comment]
There are merge conflicts right now. Could you rebase on master and fix them?

**Comment by Warepire** [comment]
Rebased.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by RisingFog** [comment]
Compressing files greater than 4GB does not work.

**Comment by Warepire** [comment]
Not too sure about solving the crash @RisingFog mentioned by enabling `FILE_SHARE_READ` and `FILE_SHARE_WRITE` is the correct way to do it. Please advice.

**Comment by lioncash** [comment]
@Warepire It's been uncovered (thanks @shuffle2 !) that the fread bug has been fixed in an update. @shuffle2's comment [here](https://github.com/dolphin-emu/dolphin/pull/3760#issuecomment-204787298) provides more detail.

**Comment by Warepire** [comment]
@lioncash I saw, I'll close this PR. The IOFile RFC is probably still wanted, but then the PR by @delroth should be re-opened instead.

**Pull request closed without merging**
