### PR TITLE
Rename "Cheats Manager" to "Cheat Manager"

### PR DESCRIPTION
**Pull request by Stevoisiak**

### CODE REVIEW

**Comment by lioncash** [comment]
There's no need to edit the po files. They'll automatically adjust whenever transifex translations are updated.

**Comment by Stevoisiak** [comment]
I thought that syncing with transifex has been broken for a while now.

**Comment by Stevoisiak** [comment]
@dolphin-emu-bot rebuild

**Comment by lioncash** [comment]
Either way, you aren't supposed to modify generated files.

**Comment by Stevoisiak** [comment]
*shrugs* Fair enough. Will update.

**Pull request merged**
