### PR TITLE
MenuBar: Add action which opens the user folder

### PR DESCRIPTION
**Pull request by OatmealDome**
Here's how it looks:

image

### CODE REVIEW

**Comment by delroth** [comment]
+1, seems like a job for QDesktopServices::openUrl

**Comment by OatmealDome** [comment]
🤦‍♂️ I didn't know that existed, thanks.

**Comment by MayImilae** [comment]
I'll give it a test and a screenshot if the Windows builder can build. :/

**Comment by MayImilae** [comment]
Tested on macOS. Works fine! Also quite handy actually as going to the library is a bit of a pain there.

Tested on Windows 11 and it also works fine. Here's a screenshot!

dolphindir

The worst part of this PR is that it messes with my muscle memory for exiting Dolphin. Fortunately I'll be fixing that problem shortly~

**Review by MayImilae — APPROVED** [review]

**Pull request merged**
