### PR TITLE
Add clang-tidy config and apply automated fixes globally.

### PR DESCRIPTION
**Pull request by delroth**
There are still issues that cannot be fixed automatically (e.g. logic problems in our code, but that's a good start).

@lioncash  please let me know if the config works. I don't want to be manually fixing issues in this change -- just make it adhere to the config.

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3932)

### CODE REVIEW

**Comment by delroth** [comment]
By the way, the arguments renaming is because the name provided in .h and .cpp were not matching. clang-format replaced the ones in .h with the ones in .cpp in this scenario. As I said, I don't want to be manually fixing stuff here, this can be done later if our parameters names suck :)

**Comment by lioncash** [comment]
Reviewed 198 of 198 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp, line 99 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3932#-KL_Oqw77fBUVKmAs_7V:-KL_Oqw77fBUVKmAs_7W:1728091348) ([raw file](https://github.com/dolphin-emu/dolphin/blob/afa202738e54652e98e8388a5c6a1541d750e3e6/Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp#L99)):*
> ```cpp
>     // INFO_LOG(WIIMOTE, "WM IR Clock: 0x%02x", sr->data[0]);
>     // m_ir_clock = sr->enable;
>     if (false == sr->ack)
> ```

these can just be `sr->ack == 0` to get rid of explicit casting.

---

*[Source/Core/Core/PowerPC/PPCAnalyst.cpp, line 511 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3932#-KL_PSyOd7-XYn3jAs0d:-KL_PSyOd7-XYn3jAs0e:-1394359115) ([raw file](https://github.com/dolphin-emu/dolphin/blob/afa202738e54652e98e8388a5c6a1541d750e3e6/Source/Core/Core/PowerPC/PPCAnalyst.cpp#L511)):*
> ```cpp
>     code->outputCR0 = true;
>   else
>     code->outputCR0 = (opinfo->flags & FL_SET_CR0) ? true : false;
> ```

These can just have a `!= 0` after the parentheses instead of a cast.

---

*[Source/Core/Core/PowerPC/Jit64IL/IR_X86.cpp, line 794 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3932#-KL_PujIqDpBLnHKrF9U:-KL_PujIqDpBLnHKrF9V:875337064) ([raw file](https://github.com/dolphin-emu/dolphin/blob/9ca13fa67292a3c3c72407dbb5533e68103748e9/Source/Core/Core/PowerPC/Jit64IL/IR_X86.cpp#L794)):*
> ```cpp
>     InstLoc I = ibuild->ReadBackward();
>     unsigned int op = getOpcode(*I);
>     bool thisUsed = static_cast<bool>(regReadUse(RI, I));
> ```

These can just have `!= 0` after the function call instead of a cast.

---

*[Source/Core/InputCommon/GCAdapter.cpp, line 358 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3932#-KL_QT_79Wq77ShGMPki:-KL_QT_8lEHnlUL-pdS7:1635926518) ([raw file](https://github.com/dolphin-emu/dolphin/blob/9ca13fa67292a3c3c72407dbb5533e68103748e9/Source/Core/InputCommon/GCAdapter.cpp#L358)):*
> ```cpp
>   }
> 
>   for (unsigned char& i : s_controller_type)
> ```

This can actually be a `std::fill`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3932)*

**Comment by lioncash** [comment]
Looks good other than the bool casts (the fill comment is more of a note-to-self than anything)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3932#-:-KL_RfBx3gANqA9XSFYI:1886193359)*

**Comment by RisingFog** [comment]
This PR needs to be rebased, and the build issues resolved.

**Comment by JosJuice** [comment]
Closing due to inactivity and merge conflicts. The idea of the PR is good, though.

**Pull request closed without merging**
