### PR TITLE
Headless without EGL

### PR DESCRIPTION
**Pull request by vladfi1**
Enable building headless without opengl. This allows dolphin to run on platforms that don't support opengl.

### CODE REVIEW

**Comment by ligfx** [comment]
@dolphin-emu-bot rebuild

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by degasus** [comment]
Do you think there is a good generic way for video software to present the bipmap? I don't like to disable this backend just because opengl is missing :/

**Comment by waddlesplash** [comment]
SDL?

**Comment by vladfi1** [comment]
On further inspection this is isn't necessary. The error is at runtime and can be avoided by choosing a different backend (Null) in the ini.

**Pull request closed without merging**
