### PR TITLE
Reverts pull request #2362, fixes issue 8542.

### PR DESCRIPTION
**Pull request by joewestcott**
See issue 8542.

### CODE REVIEW

**Comment by lioncash** [comment]
At least link to the [issue](https://code.google.com/p/dolphin-emu/issues/detail?id=8542) for easier accessibility

**Comment by comex** [comment]
Also for reference: #2362

**Comment by jdieter** [comment]
FWIW, commit #2362 was tested on Linux (gcc-4.9.2) with up to three 'Real' wiimotes.  The real problem is in line 154 (or 155 depending on whether #2362 has been applied) where we attempt to lock the mutex m_csCpuOccupied.  Before #2362, the attempt spins forever because (I assume) the PowerPC emulator is paused and has the lock.  That's why I changed it so we get the lock before we pause the emulator.

Having said all that, obviously my assumptions are at least partially incorrect.  My next question would be, why do we need to lock the mutex when we PauseAndLock()?  What is it protecting?

**Comment by MaJoRoesch** [comment]
I reproduced the hangs in Windows. Crash after crash after crash! Playing wii games 4.0-6169 is horribly  unstable.

**Comment by jdieter** [comment]
Ok, I've just done quite a bit of debugging, and I'm pretty sure I've tracked down the original problem that #2362 was supposed to fix, and my fix was wrong, so please do revert #2362.

The deadlock we're hitting in #2362 is that the CPU thread is blocking in WiimoteReal::Update, waiting for the g_refresh_lock mutex to be released, which is held by the main thread, while the main thread is blocking in CCPU::PauseAndLock, waiting for the m_csCpuOccupied mutex to be released, which, oddly enough, is being held by the CPU thread.

Unfortunately, I don't know enough about the code to know how to fix this.  My inclination would be to try_lock() in WiimoteReal::Update and return if we don't get it, but I don't know how vital it is that  WiimoteReal::Update actually run every single time it's called.

**Comment by jdieter** [comment]
I've gone ahead and created a pull request (#2373) that combines this request with the potential fix described [a couple of comments back](https://github.com/dolphin-emu/dolphin/pull/2371#issuecomment-99567567).  I have tested this fix and it does work on my system, but I'd appreciate it if anyone who had trouble with #2362 would try this.

**Pull request merged**
