### PR TITLE
Warning fixes

### PR DESCRIPTION
**Pull request by leoetlino**
Fairly straightforward warning fixes.

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4376)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/DolphinWX/Frame.cpp, line 296 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4376#-KUiRjVFhPp2SD7VdaDH:-KUiRjVGC2Vm-_2MLZ8l:b3eunss) ([raw file](https://github.com/dolphin-emu/dolphin/blob/42f201cb13a8dd494a300ab60f5ba447ae1069a1/Source/Core/DolphinWX/Frame.cpp#L296)):*
> ```cpp
> static void SignalHandler(int)
> {
>   char message[] = "A signal was received. A second signal will force Dolphin to stop.\n";
> ```

this should  probably be a `const char` array (literals are const char arrays by default, so this is tossing away the const qualifier)

---

*[Source/Core/DolphinWX/Frame.cpp, line 298 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4376#-KUiRxSd_4FRgMGSngzT:-KUiRxSedPm2l0jy5Wv_:bssu7kz) ([raw file](https://github.com/dolphin-emu/dolphin/blob/42f201cb13a8dd494a300ab60f5ba447ae1069a1/Source/Core/DolphinWX/Frame.cpp#L298)):*
> ```cpp
>   char message[] = "A signal was received. A second signal will force Dolphin to stop.\n";
>   if (write(STDERR_FILENO, message, sizeof(message)) < 0)
>   {
> ```

Can these just be stylized as `(void)write(STDERR_FILENO, message, sizeof(message));`?

Adding dead if statement bodies isn't really a good idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4376)*

**Comment by leoetlino** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/DolphinWX/Frame.cpp, line 296 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4376#-KUiRjVFhPp2SD7VdaDH:-KUiYftR7yWqRJab4K4M:bsri1ed) ([raw file](https://github.com/dolphin-emu/dolphin/blob/42f201cb13a8dd494a300ab60f5ba447ae1069a1/Source/Core/DolphinWX/Frame.cpp#L296)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> this should  probably be a `const char` array (literals are const char arrays by default, so this is tossing away the const qualifier)
</details>
I've fixed this locally and will push this when the other comment is resolved.

---

*[Source/Core/DolphinWX/Frame.cpp, line 298 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4376#-KUiRxSd_4FRgMGSngzT:-KUiWHwCBaikfmdWbkXL:bwt16qm) ([raw file](https://github.com/dolphin-emu/dolphin/blob/42f201cb13a8dd494a300ab60f5ba447ae1069a1/Source/Core/DolphinWX/Frame.cpp#L298)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> Can these just be stylized as `(void)write(STDERR_FILENO, message, sizeof(message));`?
> 
> Adding dead if statement bodies isn't really a good idea.
</details>
That does look better and I prefer that to adding a useless if, but it seems that [gcc ignores the cast](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425) and will still print a warning :/
(whereas clang does the correct thing)

Do you know if there's something less ugly that works with gcc?

(other than pragmas, [which are still ugly](https://github.com/dolphin-emu/dolphin/pull/4243#discussion_r80432599))

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4376)*

**Comment by lioncash** [comment]
*[Source/Core/DolphinWX/Frame.cpp, line 298 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4376#-KUiRxSd_4FRgMGSngzT:-KUjPP45UcHNUVo3kd0M:b-avqoh2) ([raw file](https://github.com/dolphin-emu/dolphin/blob/42f201cb13a8dd494a300ab60f5ba447ae1069a1/Source/Core/DolphinWX/Frame.cpp#L298)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> That does look better and I prefer that to adding a useless if, but it seems that [gcc ignores the cast](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425) and will still print a warning :/
> (whereas clang does the correct thing)
> 
> Do you know if there's something less ugly that works with gcc?
> 
> (other than pragmas, [which are still ugly](https://github.com/dolphin-emu/dolphin/pull/4243#discussion_r80432599))
</details>
I guess there isn't a less ugly way. I can't think of one, anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4376)*

**Comment by endrift** [comment]
Is adding `-Wno-unused-result` not desirable so as to catch actual unused results?

**Comment by leoetlino** [comment]
I guess so. Here however, the unused result warnings are completely useless.

**Pull request merged**
