### PR TITLE
Ignore capabilities reported by an XInput device

### PR DESCRIPTION
**Pull request by ToadKing**
```c++
  // XInputGetCaps seems to always claim all capabilities are supported
  // but I will leave all this stuff in, incase m$ fixes xinput up a bit
```

In actuality, the capabilities reported depend on the device and what it returns for certain reports. All conformant devices report correct values but not all devices behave correctly. I've found that the 8bitdo SNES30/SFC30 in XInput mode return weird and corrupted capabilities from XInputGetCaps. Same with the [ViGEm Bus Driver](https://github.com/nefarius/ViGEm). These are obviously bugs in the devices/drivers and should be fixed, but it appears Dolphin is one of the only apps that actually checks XInput capabilities.

This PR ignores all the capabilities from a device and assumes everything is supported, which fixes the broken devices.

### CODE REVIEW

**Comment by ToadKing** [comment]
Looking through the bug tracker this could also fix these bugs:

https://bugs.dolphin-emu.org/issues/9589
https://bugs.dolphin-emu.org/issues/10285

**Comment by BPaden** [comment]
This patch does work for me, but I've noticed a couple of issues:

The red indicators don't work when pressing buttons, so while I can assign all of the buttons I can't for example I can't see offhand if the analog triggers are actually analog.

The test button for rumble doesn't work, though rumble does appear to work ingame.

**Comment by ToadKing** [comment]
I'm not sure what would make them work fine in game but not in the input configuration window. Are you using the new Qt UI or the old one?

**Comment by JosJuice** [comment]
Inputs not being visible in the input configuration window is an unrelated problem. See PR #5731.

**Comment by JosJuice** [comment]
@ToadKing Sorry for not starting the buildbot for this PR until now, but there's a small lint failure. Could you fix it?

**Comment by ToadKing** [comment]
Attempted to fix it from my phone, if it's not right I'll fix it later tonight.

**Comment by sepalani** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
The code is correct now, but you'll need to squash the two commits into one.

**Comment by ToadKing** [comment]
squashed

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JMC47** [comment]
@JosJuice is this good to go now?

**Comment by JosJuice** [comment]
I don't know anything about the XInput API, so I'm not really the right person to review this. I can't see anything blocking merging this, though...

**Comment by RedDawn17** [comment]
Sadly, the Bloom OFF patch (RMHP08, Monster Hunter Tri PAL) is not working with this built, did the address for the patch change? Would really like to have both working

**Pull request merged**
