### PR TITLE
Emulate Skylanders Portal

### PR DESCRIPTION
**Pull request by deReeperJosh**
The Skylanders Wii games require external hardware in order to play, and while they are relatively easy to source not all the portals work with every game, and MacOS users have variable success due to the USB device being claimed by the kernel without providing root access to Dolphin.

Using the Trap Team version of the Portal that I own, I have been able to successfully track the requests and responses, and have been able to Emulate the physical portal within Dolphin, a feature requested [here](https://bugs.dolphin-emu.org/issues/12935).

This requires a new thread to track and respond to Control and Interrupt Messages, a new Class to extend as a device with descriptors defined, checking to see if there is already a portal plugged in, new fields on existing structs to define the fake response time and length, a new struct to define Fake Skylander toys, and a new tool within the UI (heavily inspired by RPCS3's Skylander Portal Window) to create, clear and load Fake Skylanders to the Emulated portal.

C++ certainly isn't my strongest language, and this will be my first ever contribution to any open source project, so there is bound to be many improvements to be made, any feedback will be much appreciated.

### CODE REVIEW

**Comment by JMC47** [comment]
I can't really review the code, but I can test this once it is building on all the builders.

I can say at a glance that the commit history will need to be cleaned up quite a bit before it can be considered for merge.

**Comment by JMC47** [comment]
Will this work with all of the Skylanders games, or just Trap Team?  I have at least two real portals for the Wii.  One for Giants and one for Trap Team.

**Comment by deReeperJosh** [comment]
> Will this work with all of the Skylanders games, or just Trap Team? I have at least two real portals for the Wii. One for Giants and one for Trap Team.

It will work for all the games! The trap team portal is just the only portal known to be compatible across all games, which is why I based the responses off of it

**Comment by JMC47** [comment]
I'm guessing something in the Trap Team figures changed that the older portals can't read then.

**Comment by JMC47** [comment]
I assume there's some kind of way to dump the figure data on PC using a portal or something?

**Comment by deReeperJosh** [comment]
> I assume there's some kind of way to dump the figure data on PC using a portal or something?

Yup! There’s some handy tools out there already that have reverse engineered the portal tech to read and dump data from Skylanders, however the changes I’m making include a create window which will also create blank figure data for you, and will make a file you can load back in later on, same as how RPCS3 has done it as well

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by deReeperJosh** [comment]
Closing this PR off and will create a tidier one with less commit history

**Comment by mandar1jn** [comment]
> I'm guessing something in the Trap Team figures changed that the older portals can't read then.

I’m aware you closed this PR, but it’s not that the figure changed. It’s that the game requires a portal with a trap slot, 2 sided lights and a speaker.

**Comment by JMC47** [comment]
Yeah, there's a new PR with a clean commit history where it was explained to me.

**Comment by deReeperJosh** [comment]
> > I'm guessing something in the Trap Team figures changed that the older portals can't read then.
> 
> 
> 
> I’m aware you closed this PR, but it’s not that the figure changed. It’s that the game requires a portal with a trap slot, 2 sided lights and a speaker. 

Yeah, I made a new PR here :) https://github.com/dolphin-emu/dolphin/pull/11331

**Pull request closed without merging**
