### PR TITLE
Android: Create adaptive icon and refactor old icon usage

### PR DESCRIPTION
**Pull request by t895**
The icon now has a foreground and a background which move in certain situations. The old icon was kept in the files because of dependencies elsewhere related to the TV app I believe.

I'm using the same logo size as the original as well. (The gif makes the colors appear de-saturated)

Demo - 
Demo

Note: One disadvantage of this is losing the standalone icon look in Android Lollipop (5.0) and Marshmallow (6.0).

New - 
image

Old - 
image

### CODE REVIEW

**Comment by Simonx22** [comment]
@dolphin-emu-bot

**Comment by Simonx22** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
Can't we keep the old behavior in 5.0 and 6.0 by not baking a background into the `ic-launcher.png` files?

Also, it doesn't seem like `ic_launcher_round` is used anywhere.

**Comment by t895** [comment]
I'll look into it. This is just what the default adaptive icon wizard provides.

**Comment by t895** [comment]
I got the icons back on < API 26!

image

**Comment by MayImilae** [comment]
I'm alright with this. I designed the Dolphin logo to be able to stand alone against any background, but a white background like that is fine.

Are you able to adjust the centered-ness of the icon in an adaptive icon? One quirk of the Dolphin logo is that centering is a little weird - the whole optical centering verses weight centering thing. The centering in this PR is not bad as is but it could be made a little better. If you can adjust it, I can give you centering values based on the images you provided.

**Comment by t895** [comment]
I can adjust it, what values should I follow?

**Comment by t895** [comment]
Also @MayImilae, your bio says that you use IRC for contact. Is that still a good way to contact you besides github messages?

**Comment by MayImilae** [comment]
Ok so, I did some measurements and things, and let me start with a demonstration. So with the Dolphin logo optically aligned (aligned automatically by photoshop), if I take the outer circle and shrink it to the same size as the Dolphin logo, you get this.

visualaid

Everything in the above is perfectly centered with Photoshop's centering tools, but it doesn't look like it!

So to make it look centered, I need to nudge the Dolphin logo to the left a bit.

nudged

So this is a 256x256 frame with the Dolphin at 60% scale, and from center, I moved the Dolphin logo 6 pixels to the left to . I don't know how the Android tools are presented, but is that enough for you to work with?

**Comment by t895** [comment]
That should be enough, the built-in adaptive icon wizard doesn't provide that level of granularity but I can use the image you provided as reference in photoshop for some manual edits

**Comment by t895** [comment]
icon

It should be fixed now

**Comment by jordan-woyak** [comment]
I think it looked better with the body centered and the tail dangling off to the right.
Also, the dolphin seems very small. Is that following android guidelines or something?

**Comment by MayImilae** [comment]
> It should be fixed now

(*＾-‘) 乃

**Comment by t895** [comment]
@JosJuice I'm not sure who else to ping to say this is ready to go

**Review by MayImilae — APPROVED** [review]

**Comment by JosJuice** [comment]
@jordan-woyak

> Also, the dolphin seems very small. Is that following android guidelines or something?

These are the recommended keylines for Android adaptive icons:



We could probably make the logo a little bigger if we wanted to, though not too much. The size that this PR is using for the adaptive icons was chosen simply because it's the scaling applied by Android by default when the app only has a non-adaptive icon. I'm assuming that this scaling is a little conservative with how big it makes the icon, since some icons have important elements all the way out in the corners, unlike the Dolphin logo.

@t895 You will need to squash the commits into one before this pull request can be merged.

**Comment by JosJuice** [comment]
@jordan-woyak Here's a comparison to other apps, if you want to see. I would say the Dolphin logo is a bit smaller than other logos in the same style (shape on single-color background). This PR is the left Dolphin, and master is the right Dolphin.

**Comment by t895** [comment]
@JosJuice Well there isn't a default scaling provided by the icon tool. To prevent much conflict, I just did my best to match the scaling as seen in the current icon.

Also, I should have the commits squashed soon.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Review by JosJuice — APPROVED** [review]
Let's get this merged so as to not bikeshed over the size. The size is effectively the same as before this PR, and can be adjusted in a later PR if needed.

**Comment by t895** [comment]
@JosJuice Sorry I wasn't worried about the size. I messed up and made a duplicate commit so I had to fiddle with git for a while.

**Comment by JosJuice** [comment]
It was less of a note to you, and more a note to everyone else that the discussion I started about the size isn't something I think needs to block this PR. I'll merge it once it's been built.

**Comment by t895** [comment]
Accidentally labelled the commit as "Android: Inherit from Material3 themes and round corners on box art" when it should have been "Android: Create adaptive icon and refactor old icon usage"

**Pull request merged**
