### PR TITLE
[Android/DNM] Dependency Upgrade

### PR DESCRIPTION
**Pull request by Tsunamical**
Dependent on updated dependencies on buildbot, do not merge until then.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3850)

### CODE REVIEW

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild for lulz.

**Comment by Parlane** [comment]
Android build failed as expected.

**Comment by Tsunamical** [comment]
Of course. I can help with writing a script though to auto-update dependencies though, let me know if you're interested :)

**Comment by RisingFog** [comment]
Is this still dependent on the Android build bot being updated?

**Comment by Tsunamical** [comment]
Should be. Gradle plugin can be bumped from 2.1.0 to 2.1.3 as well, but 2.2.0 is really close to coming out as well (-rc2 came out on the 8th, -rc1 on the 2nd).

**Comment by degasus** [comment]
As 2.2 is released, this PR is obsolete by PR #4252

Feel free to help me to fix our android project, as I'm not very familiar with the android toolchain.

**Pull request closed without merging**
