### PR TITLE
GameSettings: Don't ship speedhack which are enabled by default.

### PR DESCRIPTION
**Pull request by degasus**
This may slow down a few games, but we don't want to support this kind of mess.

### CODE REVIEW

**Comment by JMC47** [comment]
LGTM

**Comment by degasus** [comment]
Feel free to ask me to fixup the loading of those speedhacks instead, so that it won't break because of inlining, conditional_continue, or whatever we've already done.

**Comment by psennermann** [comment]
No more Heroes drops from 75/60 to 45/60 fps but no problem, I re-enabled the speedhack by myself ;-)

**Comment by JMC47** [comment]
The solution to this long term would be to implement these hacks in a way that they aren't on by default and causing problems.  If you want, make an issue report so this isn't completely forgotten!

**Comment by psennermann** [comment]
isn't there a way to put them disabled in the patch section of game properties?

**Comment by SHartwick** [comment]
@psennermann How is the performance of No More Heroes impacted by commit #4735 ?

**Comment by degasus** [comment]
If anyone of you uses this speedhacks, may you please try them again on PR #4774 to see if they still works fine?

**Comment by psennermann** [comment]
Yesterday I must have had something running in the background, because after further testing the situation is not as bad as it seemed, in fact No more Heroes drops from 85/60 to 70/60 fps and Paper Mario from 135/60 to 110/60 (well it's still a lot of fps but not as many)
PR #4735 doesn't seem to impact very much these two games and as of PR #4774 if there's a build available I could check it too...

**Comment by JMC47** [comment]
The leafing PR isn't expected to affect these games.  But, 4774 should allow the speedhacks to work again.  https://dl.dolphin-emu.org/prs for the pull.

**Comment by psennermann** [comment]
From what I see speedhack work with 4774, but why are you saying "work again"? I didn't notice they were broken...

**Comment by degasus** [comment]
eg the fire emblem code broke in my inlining PR.

**Comment by psennermann** [comment]
No more Heroes and Paper Mario seem to work

**Pull request merged**
