### PR TITLE
JIT Instruction Tables: Eliminate JIT global usages

### PR DESCRIPTION
**Pull request by lioncash**

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Those `CompileInstruction` methods look the same except for the variable type of `jit`, this looks a little suspicious to me. Do you think we could generalize this in some way, or would that be too convoluted compared to duplicating a little code?

**Comment by lioncash** [comment]
Since the specific JIT type needs to be kept around so the member function can be executed, the function could just be made a member function of each JIT. The code that follows the execution is just code for statistics/profiling, so that can be factored out since it only needs a `GekkoOpInfo*`  instance.

so this could be done like so:

```cpp
void SomeJITImplementation::CompileInstruction(PPCAnalyst::CodeOp& op)
{
  (this->*dynaOpTable[op.inst.OPCD])(op.inst);
  UpdateOpInfo(js.compilerPC, op);
}

// ... somewhere else

void UpdateOpInfo(const u32 pc, PPCAnalyst::CodeOp& op)
{
  GekkoOpInfo* const info = op.opinfo;
  if (!info)
  {
    PanicAlert("Tried to compile illegal (or unknown) instruction %08x, at %08x", op.inst.hex, pc);
    return;
  }

#ifdef OPLOG
  if (!strcmp(info->opname, OP_TO_LOG))  // "mcrfs"
  {
    rsplocations.push_back(pc);
  }
#endif
  info->compileCount++;
  info->lastUse = pc;
}
```

**Comment by BhaaLseN** [comment]
That looks a little nicer, and its not like we don't already have member implementations of `JitXX` inside `JitXX_Tables.cpp`. Do you think making such a change would be worth it?

**Comment by degasus** [comment]
IMO all functions of one JIT should be in the same class. The current split between block cache helpers, assembly, and the JIT itself makes no sense.

**Comment by Parlane** [comment]
@degasus Is your comment above for or against this PR ?

**Comment by degasus** [comment]
@Parlane I suggested another method, but I prefer this one here over master, too.

**Comment by lioncash** [comment]
@degasus Yeah, I like your method (all compilation functions should be bound to their relevant JIT instance), I'll change it over to that sometime today.

**Pull request merged**
