### PR TITLE
DolphinQt2: Startup Warning

### PR DESCRIPTION
**Pull request by EmptyChaos**
In PR #3981 Phire suggested adding a warning prompt to DolphinQt so that users don't accidentally try to use it instead of DolphinWX if both binaries are included in the packages produced by the buildbot. [The other option is to produce a separate build package for DolphinQt so the binaries don't end up mixed together.] This needs someone to supply the text for whatever it should say.

experimental

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4006)

### CODE REVIEW

**Comment by phire** [comment]
Looks good.

**Comment by MaJoRoesch** [comment]
Ooooh ok, um, I need to give some pointers here!

The Dolphin is not vertically centered in the text block (all three paragraphs) it is in. It is also *very* tight, and needs much more padding around the logo!

Black and yellow stripes just looks... severe. And it seems rather excessive I think. Isn't it attention grabbing enough by presenting an unknown pop up in front of them?

There's like a sea of unused space on the bottom left! The buttons really should be placed in a row horizontally along the bottom, and not stacked vertically. It would be a much more efficient use of space in this design.

Windows XP arrows. Please no. PLEASE.

**Comment by EmptyChaos** [comment]
@MaJoRoesch The icons are decided by the Qt theme. I use Windows Classic on Windows 7 so it uses Windows XP style icons. Here's how it looks using Aero:
experimentalaero

The use of hazard tape is intended to be intimidating so the user will opt not to proceed. I can remove it if you prefer it to be less extreme.

I can lay out the buttons horizontally instead but I think it reads better vertically since it leads the user to just click the top one. It's less obvious when laid out the other way. Windows UX prefers vertical layout for this type of button as well, I could remove the logo from the design to compensate for the wasted space or center the buttons under both the logo and paragraphs instead of just the text.

How much spacing do you want around the logo?

**Comment by lioncash** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/DolphinQt2/InDevelopmentWarning.h, line 7 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4006#-KMWtXChmgKl3XwRqagH:-KMWtXChmgKl3XwRqagI:1080280073) ([raw file](https://github.com/dolphin-emu/dolphin/blob/12e24ef586ed64673210a823ac1fa3b1ad26b3c9/Source/Core/DolphinQt2/InDevelopmentWarning.h#L7)):*
> ```objc
> #pragma once
> 
> #include <QBrush>
> ```

QBrush can be a forward declaration.

---

*[Source/Core/DolphinQt2/InDevelopmentWarning.h, line 10 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4006#-KMWtc_REa7s2MSCblDc:-KMWtc_REa7s2MSCblDd:-1105563688) ([raw file](https://github.com/dolphin-emu/dolphin/blob/12e24ef586ed64673210a823ac1fa3b1ad26b3c9/Source/Core/DolphinQt2/InDevelopmentWarning.h#L10)):*
> ```objc
> #include <QDialog>
> 
> class InDevelopmentWarning : public QDialog
> ```

```cpp
class InDevelopmentWarning final : public QDialog
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4006)*

**Comment by lioncash** [comment]
*[Source/Core/DolphinQt2/InDevelopmentWarning.h, line 18 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4006#-KMWv9FSfurjMQxiM_S9:-KMWv9FToHZwqziijuft:121116741) ([raw file](https://github.com/dolphin-emu/dolphin/blob/12e24ef586ed64673210a823ac1fa3b1ad26b3c9/Source/Core/DolphinQt2/InDevelopmentWarning.h#L18)):*
> ```objc
>   ~InDevelopmentWarning();
> 
>   static QBrush MakeConstructionBrush();
> ```

These two static functions should also likely be private if possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4006)*

**Comment by Parlane** [comment]
Yellow banner LGTM.

**Comment by Parlane** [comment]
I don't think we need the Dolphin logo here TBH. Would make the window smaller without.

**Comment by lioncash** [comment]
*[Source/Core/DolphinQt2/InDevelopmentWarning.h, line 18 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4006#-KMWv9FSfurjMQxiM_S9:-KMWw0XIYJEpDHVA0gDW:-1755987800) ([raw file](https://github.com/dolphin-emu/dolphin/blob/12e24ef586ed64673210a823ac1fa3b1ad26b3c9/Source/Core/DolphinQt2/InDevelopmentWarning.h#L18)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> These two static functions should also likely be private if possible.
</details>
That or simply get rid of them in the class declaration and make them static free functions in the cpp file, since they're technically implementation details that aren't necessary in the visible interface at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4006)*

**Comment by EmptyChaos** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/DolphinQt2/InDevelopmentWarning.h, line 7 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4006#-KMWtXChmgKl3XwRqagH:-KMWzFWYql-9U_V6Zw9H:1740281843) ([raw file](https://github.com/dolphin-emu/dolphin/blob/12e24ef586ed64673210a823ac1fa3b1ad26b3c9/Source/Core/DolphinQt2/InDevelopmentWarning.h#L7)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> QBrush can be a forward declaration.
</details>
Removed.

---

*[Source/Core/DolphinQt2/InDevelopmentWarning.h, line 10 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4006#-KMWtc_REa7s2MSCblDc:-KMWz7kBnHQGt4xI7L4S:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/12e24ef586ed64673210a823ac1fa3b1ad26b3c9/Source/Core/DolphinQt2/InDevelopmentWarning.h#L10)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> ```cpp
> class InDevelopmentWarning final : public QDialog
> ```
</details>
Done.

---

*[Source/Core/DolphinQt2/InDevelopmentWarning.h, line 18 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4006#-KMWv9FSfurjMQxiM_S9:-KMWz9iP9wsjTjxap-6i:196765834) ([raw file](https://github.com/dolphin-emu/dolphin/blob/12e24ef586ed64673210a823ac1fa3b1ad26b3c9/Source/Core/DolphinQt2/InDevelopmentWarning.h#L18)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> That or simply get rid of them in the class declaration and make them static free functions in the cpp file, since they're technically implementation details that aren't necessary in the visible interface at all.
</details>
Moved to free statics.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4006)*

**Comment by EmptyChaos** [comment]
Without the logo:
experimentalnologo

**Comment by Parlane** [comment]
Something weird about the buttons due to the button size being far wider than the text it causes the text to be more left than it should.

**Comment by EmptyChaos** [comment]
I changed the proportions on the stretch factor:
experimentalaero2

The buttons naturally align their content to the left because they're modeled on bullet points ([Windows 7 Copy Dialog](http://i.stack.imgur.com/GeQG7.png)).

**Comment by Parlane** [comment]
Yes I understand the alignment, but the button border should shrink to the size of the button text of the largest width. The shrunk version looks 10x better.

**Comment by Helios747** [comment]
I really dislike that yellow stripe image at the top. As @MaJoRoesch said, it is way too severe.

It's a UI for a video game console emulator, not a nuclear missile control system. 

@Parlane is a troll. :P

**Comment by slx7R4GDZM** [comment]
It'd probably look way better with some sort of red background instead of the yellow/black stripes.

**Comment by Pringo** [comment]
I think a more standard looking warning dialog would be a better choice. I also agree the yellow stripe is too over the top.

Something like this might be good:

DolphinQt Warning

**Comment by Parlane** [comment]
OK @Pringo's design is definitely better IMO.

**Comment by EmptyChaos** [comment]
@Helios747 I was thinking "construction site" rather than "nuclear silo".

@slx7R4GDZM The pattern and colors were based on hazard stripes, e.g. [Barricade Tape](https://en.wikipedia.org/wiki/Barricade_tape)

@Pringo I assume that was a mockup? I couldn't figure out how to extend QMessageBox sanely so I just reimplemented the design manually.

experimentalaero2

**Comment by mimimi085181** [comment]
What about a checkbox: "I know what i'm doing, stop asking", that appears after you launched QT for a few times, and which prevents showing the screen in the future?

**Comment by phire** [comment]
There is a ini file setting you can set to make the warning go away. I'm not sure we want to expose that setting to a GUI just yet, maybe when DolphinQt gets to a less experimental state.

**Comment by Parlane** [comment]
LGTM.

**Comment by phire** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r1, 1 of 9 files at r2, 6 of 8 files at r3, 1 of 2 files at r4, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4006#-:-KMXuKZYIj6A0YXvNzGH:1417088721)*

**Comment by MaJoRoesch** [comment]
Much better! LGTM

**Comment by Pringo** [comment]
@EmptyChaos Yeah it was just a mockup.

**Comment by mbc07** [comment]
I think it's worth mentioning the dialog seems to not play nice with high DPI settings, the last lines of text are cropped on those scenarios:
capturar

**Comment by Pringo** [comment]
@mbc07 is that from before or after #3737 was merged?

**Comment by Nucleoprotein** [comment]
@Pringo 
That dialog uses QT5 so has nothing to do with #3737.

**Pull request merged**
