### PR TITLE
HiresTexture: Correct texture hashes

### PR DESCRIPTION
**Pull request by lioncash**
Fixes a regression introduced in 2da8d98b2f94a33e337d37dc7153e5ba445961f3

### CODE REVIEW

**Comment by lioncash** [comment]
@BigheadSMZ Can you test this out and see if the issue is corrected.

**Comment by lioncash** [comment]
@BigheadSMZ Alright, give this one a shot and see if the issue is still present.

**Comment by BigheadSMZ** [comment]
Everything seems to be okay now. 👍

**Comment by lioncash** [comment]
Alright, cool. Thanks for testing!

**Pull request merged**
