### PR TITLE
Android: fix software renderer settings string

### PR DESCRIPTION
**Pull request by Tilka**
Untested, should fix the second part of [issue 9916](https://dolp.in/i9916).

### CODE REVIEW

**Comment by degasus** [comment]
Yeah, looks good.

**Comment by zxcvbad** [comment]
Correctly sets GFXBackend = Software Renderer. Though Android UI backend menu still does not display "Software" being chosen even when it was. UI is showing whatever previous backend being used

**Comment by degasus** [comment]
Likely because of this one: https://github.com/dolphin-emu/dolphin/blob/master/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/ui/settings/SettingsFragmentPresenter.java#L801

**Comment by Tilka** [comment]
lol

**Pull request merged**
