### PR TITLE
GetCRC32: Fix the hash for the last byte(s)

### PR DESCRIPTION
**Pull request by mimimi085181**
This fixes issue 8227
https://code.google.com/p/dolphin-emu/issues/detail?id=8227

### CODE REVIEW

**Comment by phire** [comment]
@dolphin-emu-bot rebuild

**Comment by FioraAeterna** [comment]
Can't you just do some appropriate pointer math to make sure we're accessing the correct 8 bytes (i.e. the last 8 bytes of the input)? Then you don't have to have a fancy switch statement.

**Comment by mimimi085181** [comment]
Can somebody help me with this?
I can only come up with:

if (len % 8 != 0)
		h[0] = _mm_crc32_u64(h[0], end[0] >> ((8 - len & 7) * 8) );

which just looks as bad, and i'm not even sure if it's correct.

**Comment by magumagu** [comment]
Why not just declare that len is required to be a multiple of 32 bytes; then we don't need any of this extra code.

**Comment by mimimi085181** [comment]
That would solve the problem, but it would change how safe texture cache accuracy is supposed to work. There might be no hashes calculated where len is not a multiple of 8, but i'd like the code to be future-proof, in case that changes or if the hash function is used for something else.

**Comment by phire** [comment]
Hang on, textures are guaranteed to be a multiple of 512 bytes (or was it 1kb?)

**Comment by FioraAeterna** [comment]
I thought the idea here was to make sure the last few bytes of any texture got hashed.

**Comment by delroth** [comment]
I'd agree with an assert to make sure len % 8 == 0.

**Comment by degasus** [comment]
Through the len is always a multiple of 8 here, all other shared hash function does care well about this case. So shall we try to standardize them?

**Comment by degasus** [comment]
@dolphin-emu-bot rebuild

**Comment by mimimi085181** [comment]
This is just a bug fix. If somebody wants to change all hash functions to ignore odd ends, that belongs into another PR. Some of the hash functions could be removed anyways, like the functions for x86_32.

**Comment by degasus** [comment]
@dolphin-emu-bot rebuild

**Comment by degasus** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
