### PR TITLE
Savestate keep compatibility with different mmu setting

### PR DESCRIPTION
**Pull request by weihuoya**
dolphin can't load savestate with different mmu setting, fix it.

### CODE REVIEW

**Comment by riking** [comment]
Wouldn't a `.Skip(FAKEVMEM_SIZE)` be better than looping?

**Comment by weihuoya** [comment]
`PointerWrap` don't has `Skip` method.

**Comment by JosJuice** [comment]
Are you sure this works? The FakeVMEM data is just going to be gone when loading a savestate...

**Comment by JMC47** [comment]
Most games don't use ARAM so it'd actually work pretty decently for some titles assuming no bugs.

**Comment by weihuoya** [comment]
there is a default setting in code. MMU enabled on pc and disabled on phone.
This changes will break all saved state on phone, but can share saved state with pc.
```c++
#ifdef _M_X86_64
  bMMU = true;
#else
  bMMU = false;
#endif
```

**Pull request closed without merging**
