### PR TITLE
replace libpng with libspng

### PR DESCRIPTION
**Pull request by shuffle2**
This only replaces the png library dolphin itself uses (mgba and Qt use their own).
It also allows getting rid of the gross C support code needed for libpng and make the External a submodule.

oof, i had a bug that made me think the speedup was a lot more than it really is. There is about 10% speedup for smaller png writes, for larger ones it's actually a bit slower (but still faster overall than current master, thanks to zlib-ng).

On the read path, I tested by comparing time taken for prefetching the hypatia wind waker hires texture set to load: 
this PR: 66 seconds 
zlib-ng branch: 95 seconds
master (zlib and libpng): 130 seconds

Not sure how to make it work with cmake.

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
The reason you can't get CMake to work is because spng's CMakeLists.txt does not set any include directory on the spng/spng_static target. So they don't get set when linking to it. It also unconditionally installs the spng headers, which we probably don't want.

Since its compilation steps are very simple I think we can just make a custom replacement for it instead of trying to make it behave. Replace the entirety of our spng CMakeLists.txt (the one outside the submodule) with:

```
cmake_minimum_required(VERSION 3.0)

project(spng C)

add_library(spng STATIC ${CMAKE_CURRENT_LIST_DIR}/libspng/spng/spng.c)
target_compile_definitions(spng PUBLIC SPNG_STATIC)
target_link_libraries(spng PUBLIC ZLIB::ZLIB)
target_include_directories(spng PUBLIC ${CMAKE_CURRENT_LIST_DIR}/libspng/spng/)
dolphin_disable_warnings_msvc(spng)
```

**Comment by shuffle2** [comment]
Thanks!

**Review by iwubcode — APPROVED** [review]
Code wise this LGTM (just looked at the png changes).  I tested Dynamic Input Textures, loading a texture pack, and dumping some textures.  All seemed to work fine

**Comment by shuffle2** [comment]
i don't think this PR should have made fifoci complain, nor the zlib-ng change, so idk what's up with that :(

**Comment by shuffle2** [comment]
a bug with libspng or with libpng 🤔 they seem like valid pngs to software on my system (and also github/browser, which displays them fine...)

**Comment by shuffle2** [comment]
@dvessel actually i took a look using the pngcheck tool of libpng and think this will fix it, can you check: https://github.com/dolphin-emu/dolphin/pull/10907

**Comment by Rumi-Larry** [comment]
Since this PR was made the file at "dolphin/Source/PCH/nopch/pch.h" is no longer necessary.

**Pull request merged**
