### PR TITLE
Qt: Re-enable Dark Mode support

### PR DESCRIPTION
**Pull request by spycrab**
The Qt version we use now should support Dark Mode properly.

### CODE REVIEW

**Comment by 8times9** [comment]
image
The toolbar text now displays correctly in dark mode

**Comment by spycrab** [comment]
@8times9 Does the rest of the interface look okay too? (Especially TAS and the Controller config Windows for Wiimotes / Gamecube Controllers)

**Comment by JosJuice** [comment]
This only affects macOS, right?

**Comment by spycrab** [comment]
Yes

**Comment by MayImilae** [comment]
Here are a bunch of screenshots!

[pr8640-Screenshots.zip](https://github.com/dolphin-emu/dolphin/files/4241170/pr8640-Screenshots.zip)

So two main issues I spotted. The C stick is black against dark grey, with only a little tiny bit of yellow peeking through. That's not great. For all other joysticks, the calibration bounds for the joystick, the dashed lines, are black against dark grey as well, and nearly invisible. Other than those two things, everything seems good. 

Screen Shot 2020-02-23 at 03 43 49

**Comment by spycrab** [comment]
@MayImilae It seems like that code already uses palettes instead of hard coded colors, so fixing this will be a bit more difficult. Would you prefer this PR be on hold until we fix that or should we go ahead and merge it anyway?

**Comment by MayImilae** [comment]
I believe billiard is already looking into the indicators? Maybe ask him, he may already have it fixed in a pr.

**Comment by spycrab** [comment]
I checked myself on Catalina. Contrast looks good now.

**Pull request merged**
