### PR TITLE
DiscordPresence: Add popular games to artwork list

### PR DESCRIPTION
**Pull request by Techjar**
I've added a bunch of popular games based on our statistics. I included full GameIDs as it's easier for reference purposes, with differing publisher codes and whatnot. I also alphabetized them by the name cause it looks nice.

Here's the images which @delroth will need to upload to our app configuration:
https://owncloud.techjargaming.com/index.php/s/a6u1fBGJgkfutGM

### CODE REVIEW

**Comment by JosJuice** [comment]
This isn't going to work – you need to use the three-character IDs. You can put a full game ID in comments next to each game if you want to, though.

**Comment by Techjar** [comment]
@JosJuice If you look below, the code grabs just the first 3 characters.

**Comment by JosJuice** [comment]
It grabs the first three characters from the game ID that's passed as a parameter, but it doesn't strip any characters from what it reads from `REGISTERED_GAMES`, so it's not going to match.

**Comment by Techjar** [comment]
Ah right, well that's a bit silly. Hmm...

**Comment by Techjar** [comment]
Alright that should do.

**Comment by delroth** [comment]
Assets have been uploaded. Can you do some quick testing to make sure it works?

**Comment by Techjar** [comment]
LGTM

**Pull request merged**
