### PR TITLE
Revert "Undo the addition of a translatable string during the string freeze"

### PR DESCRIPTION
**Pull request by Parlane**
Reverts dolphin-emu/dolphin#3873

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3874)

### CODE REVIEW

**Comment by Fallcrest** [comment]
@Parlane? This should be merged, right? Not to bug you, but it just bothers me to have that one extra branch that we don't need open because of this.

**Comment by RisingFog** [comment]
@Parlane This PR needs to be rebased

**Comment by phire** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3874#-:-KLuQTehmKNYyLfxSrTv:1417088721)*

**Comment by JosJuice** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3874)*

**Pull request merged**
