### PR TITLE
CMake: remove references to D3D12

### PR DESCRIPTION
**Pull request by ligfx**
It's gone!

### CODE REVIEW

**Comment by leoetlino** [comment]
Not sure if this is out of scope, but would it be worth removing Externals/d3dx12/ too?

**Comment by BhaaLseN** [comment]
Noticed this too the other day, might be worthwhile since this looks like a cleanup PR :P

**Comment by ligfx** [comment]
@leoetlino @BhaaLseN sounds good to me!

**Comment by degasus** [comment]
LGTM

**Comment by Rounak5075sadhukhan** [comment]
add NETPLAY on android& optimize VULKAN backend

**Pull request merged**
