### PR TITLE
Android: Fix and enable input device sensor input

### PR DESCRIPTION
**Pull request by JosJuice**
This reverts commit 75fb1a7edfb12f490b08ab0b76a8e2f1536d2d9b and fixes the bugs that that commit was a workaround for.

### CODE REVIEW

**Review by dreamsyntax — APPROVED** [review]

**Comment by JosJuice** [comment]
Hold off with merging this for now - I haven't gotten any testing results from users yet.

**Comment by dreamsyntax** [comment]
Able to reproduce
```
```
type: crash
osVersion: google/oriole/oriole:14/AP2A.240605.024/2024061400:user/release-keys
package: org.dolphinemu.dolphinemu.debug:19991
process: org.dolphinemu.dolphinemu.debug
processUptime: 8557 + 90 ms
installer: com.android.packageinstaller

java.lang.NullPointerException
	at org.dolphinemu.dolphinemu.features.input.model.DolphinSensorEventListener.onSensorChanged(DolphinSensorEventListener.kt:258)
	at android.hardware.input.InputDeviceSensorManager$InputSensorEventListenerDelegate.handleMessage(InputDeviceSensorManager.java:368)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```
```

**Comment by dreamsyntax** [comment]
Tested the newest changes.

Tried with two dualsense controllers on Android 14.

Opening config while emulation is running, minimizing via android as I write this comment, etc. No crashing and no odd behavior with the sensors on resume. Everything working as expected.

**Review by dreamsyntax — APPROVED** [review]
Code looks good to me

**Comment by chrisleigh-stack** [comment]
How about ps4 controller? Is this working

**Pull request merged**
