### PR TITLE
BBA/BuiltIn: Fix matchmaking with more than 2 consoles

### PR DESCRIPTION
**Pull request by sepalani**
By combining https://github.com/dolphin-emu/dolphin/pull/10928 and https://github.com/dolphin-emu/dolphin/pull/10920, I don't have these matchmaking instability. Without this PR, I had to start searching for players at nearly the same time for the matchmaking to be successful.

Seems to work for me with Mario Kart Double Dash and Kirby Air Ride using Windows+Linux+Android.

Ready to be reviewed & tested.

### CODE REVIEW

**Comment by JMC47** [comment]
Had absolutely zero hesitation getting consoles to connect with Dolphin in this build.  Was able to get some more interesting testing in because of it.

1080 Avalanche - Connected 3 consoles fine, but they desynced ~3 seconds.  I tried everything to work around this, but it seems like a fatal error that cannot be worked around.  One dolphin + one console is enough to desync.  I wonder if this is a physics issue?  The game has a replay system, so I will investigate further.  We do know that Mario Smash Football Wii also has physics desyncs.

Another issue is that sometimes the two Dolphin instances don't want to see each other, but other times they connect fine.

image

I had Dolphin -> Console -> Dolphin in this image, and the *first* Dolphin couldn't see the second one.  I tried again and they connected fine with Console -> Dolphin -> Dolphin.  I tried Dolphin -> Console -> Dolphin again and it worked so whatever.  Might just be a random error.

Because this is taking longer than I thought, I'll do the rest of my testing in separate posts.

**Comment by sepalani** [comment]
@JMC47
Overall, is it better or worse than https://github.com/dolphin-emu/dolphin/pull/10920 alone?

There shouldn't be any performance boost since we're doing more things than before. I rebased the multicast PR on the same base as this PR. I suspect the hw accelerated SHA1 PR to be the one improving the performance. Do you mind retesting the multicast PR to confirm this?

The only thing (afaict) that is implemented properly is IGMP. I'll see if I can sort this out.

**Comment by JMC47** [comment]
Overall this is more consistently, especially when using just Dolphin instances.

Regarding the performance issues in Kirby - the problem was something to do with the network.  So I think whatever was happening that costs it to be inconsistent was fixed throughout one of the changes.

**Comment by sepalani** [comment]
IGMP doesn't seem to be the issue, I'll have a look at the UPnP protocol, there is also no TCP connect error log in case of failure which sounds suspicious.

**Comment by sepalani** [comment]
Superseded by https://github.com/dolphin-emu/dolphin/pull/10920.

**Pull request closed without merging**
