### PR TITLE
TextureCache: Fix crash for invalid textures.

### PR DESCRIPTION
**Pull request by degasus**

### CODE REVIEW

**Comment by delroth** [comment]
Please update the description to make it more clear the crash only happens when recording fifo logs. Otherwise, LGTM.

**Comment by JMC47** [comment]
Fixes our longstanding medabots infinity crash.

**Comment by phire** [comment]
Does it only crash when recording fifologs?

Perhaps we should be adding more error checking to FIfoRecorder.

**Comment by JMC47** [comment]
No, it crashes in game normally in D3D and OpenGL (but not SW renderer.)  The original fix that @degasus posted only fixed the video-backend part, not the fifoplayer part, which is why he had to add a second fix to the fifoplayer.

**Comment by delroth** [comment]
OK, I misread that. LGTM then.

**Comment by degasus** [comment]
Oh, no, this fixes both, the videocommon part *and* the fiforecorder, as are broken in the same way here. But my bigger issue with this crash is that it does not happen on videosw. Sounds like the game configures an invalid texture, but don't sample from it. I'm going to verify it if @JMC47 provides me a fifolog.

**Pull request merged**
