### PR TITLE
VideoCommon: add constant value for maximum number of pixel samplers

### PR DESCRIPTION
**Pull request by iwubcode**

### CODE REVIEW

**Comment by Rumi-Larry** [comment]
Are there other good candidate constant that can make the new file more useful? It looks very silly otherwise.

**Comment by iwubcode** [comment]
@Rumi-Larry - maybe in the future I'll move some of the other constants over.  This is for another feature I'm working on.  So no plans at this time, keeping it simple.

**Comment by AdmiralCurtiss** [comment]
Code wise this looks fine, I cannot tell whether the constants are appropriate in every location they're used though.

**Review by phire — APPROVED** [review]
I have some performance related reservations about actually increasing this constant, especially when using vulkan on mobile phone GPUs.

But this change itself is great.

**Pull request merged**
