### PR TITLE
Be more clear on formatting styles for single-line conditionals.

### PR DESCRIPTION
**Pull request by Zopolis4**
Right now in Contributing.md we are inconsistent with our formatting styles for single-line conditionals. While I personally think  having braces merges better with Dolphin's codebase and C++ style, we should be consistent whatever we decide in the end. Depending on what we decide, I or someone else can make a PR updating our codebase to account for that.

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
Against. This change is just incorrect with regards to how we actually write and review code here. If you change anything here, remove the 'Acceptable' so that the single-line-on-both-branches no-brace style is under 'Yes' too.

**Comment by Zopolis4** [comment]
Are you saying that it is incorrect because it does not reflect what is currently happening or are you saying that it is incorrect because you believe that we should not change from the current dual standard?

**Comment by AdmiralCurtiss** [comment]
We currently use the 'Acceptable' style regularly.

**Comment by Zopolis4** [comment]
I'm having a little trouble understanding what you mean, I know we use both styles regularly, I'm saying we should decide on one and then modify the codebase to reflect that.

**Comment by AdmiralCurtiss** [comment]
Why, what's wrong with how we currently do things? You couldn't even consistently do the non-brace style because what would you do with code that spans more than a single statement then?

**Comment by Zopolis4** [comment]
I think the problem with how we currently do things is that it is wildly inconsistent. Not sure what you mean about the non-brace style, the only time the non-brace style is used is when there is only a single line (if the statement is split across two lines then it is used with braces) under the if statement. Right now, the current style is to use braces for everything that is over one line of code, and then only for if/else statements are non-braces sometimes used.

Current style for single-line conditionals:
```c++
if ()
{
  foo;
}
```
OR
```c++
if ()
  foo;
```

Current style for everything else:
```c++
void ()
{
  bar;
}

if ()
{
  foo;
  bar:
}

else ()
{
  foo;
  bar:
}
```

**Comment by JosJuice** [comment]
It is inconsistent in the sense that it gives you two options for how to do things, but it's something that's common in various projects, not something that's "wildly" inconsistent, and I think having these two options is justified. Forcing braces everywhere would just lead to lots of nearly lines.

**Pull request closed without merging**
