### PR TITLE
DolphinWX: Fix branch information display in the about dialog.

### PR DESCRIPTION
**Pull request by lioncash**
How it looks now:

### CODE REVIEW

**Comment by MaJoRoesch** [comment]
Can someone who codes sign off on this so we can merge it before the progress report?

**Comment by Pringo** [comment]
Is it possible to have the background colour in that branch box match the rest of the window instead of showing up as white?

**Comment by lioncash** [comment]
If you're on OSX or a Linux distribution, then no, since it matches the look and feel of your OS.

**Comment by Pringo** [comment]
@lioncash I am on Windows. I just think the white box looks awkward compared to the original implementation.

**Comment by MaJoRoesch** [comment]
It does look kind of bad...

**Comment by RisingFog** [comment]
I was suggesting before in the other PR to make both the version and branch info clickable which copies the information to the clipboard

**Comment by illuminatedgeek** [comment]
Here is what it looks like as a wxStaticText control
wxStaticText

The problem is it's not selectable (for pasting in forum threads etc). RisingFog has an interesting idea but it may not be practical.

**Comment by MaJoRoesch** [comment]
Make a PR? The progress report will be going up with a picture of whatever the about dialog is at the time it is published, so time is of the essence!

**Comment by Pringo** [comment]
@illuminatedgeek Can you add a space between the Compiled line and the Check for updates line so it looks like @RisingFog's final version here: https://github.com/dolphin-emu/dolphin/pull/2016#issuecomment-88280738

**Comment by Pringo** [comment]
@MaJoRoesch I agree that having the text as selectable is not essential and it would be fine without it. I have never seen a single case in practice of a user wanting the text in the about window to be selectable. If it causes problems I say remove it.

@BhaaLseN suggested suggested that feature so maybe he might want to have a say in it.

**Comment by MaJoRoesch** [comment]
Remember that the progress report is going to go up in a few hours with a picture of whatever the about dialog is when it's published, so time is of the essence!

**Comment by illuminatedgeek** [comment]
I'm adding a "copy to clipboard" button for the static text right now. Best of both worlds hopefully. I'll send a PR with screenshots when it's ready.

**Comment by Pringo** [comment]
@illuminatedgeek imo an additional button is over complicating the UI for a feature that honestly barely matters. I think it is fine without.

**Comment by lioncash** [comment]
I agree with @Pringo on this one.

**Pull request merged**
