### PR TITLE
Vulkan: Cleanup and implement XFB support

### PR DESCRIPTION
**Pull request by stenzek**
The cleanups here are mostly just removing references to some of the singletons, and making the texture cache entry class re-usable for the XFB implementation (but also generally useful).

The XFB part is a single commit, so it can easily be reverted after texturecache-based-XFB is finished. I don't think an additional ~400 lines isn't too bad, for bringing Vulkan to feature parity with the other backends. RealXFB also seems to be significantly faster than GL for triangle.dol, probably helped by the fact that it's not doing byte order swapping when reading back.

Could anyone with realxfb-required games please confirm there's no obvious visual errors?

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4374)

### CODE REVIEW

**Comment by RisingFog** [comment]
THPS3 seems to play fine, don't notice any issues with it,

**Comment by JMC47** [comment]
I can try some RealXFB limited games sometime and see; I haven't run into it in a while.

**Comment by lioncash** [comment]
Review status: 0 of 21 files reviewed at latest revision, 7 unresolved discussions.

---

*[Source/Core/VideoBackends/Vulkan/FramebufferManager.cpp, line 1380 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4374#-KUjIEsL6YlyFW7wFUG0:-KUjIEsMfiukpfClkOAg:b-t4ptu9) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d790601213e032920ba82851804453a2887603d9/Source/Core/VideoBackends/Vulkan/FramebufferManager.cpp#L1380)):*
> ```cpp
>   config.rendertarget = true;
>   TextureCacheBase::TCacheEntryBase* base_texture = g_texture_cache->CreateTexture(config);
>   TextureCache::TCacheEntry* texture = static_cast<TextureCache::TCacheEntry*>(base_texture);
> ```

this and base_texture can just be `auto*`.

---

*[Source/Core/VideoBackends/Vulkan/FramebufferManager.h, line 172 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4374#-KUjLHCoMutGOKnqi1fQ:-KUjLHCp8vG3hbraIvzX:bpzfzty) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d790601213e032920ba82851804453a2887603d9/Source/Core/VideoBackends/Vulkan/FramebufferManager.h#L172)):*
> ```objc
> // The XFB source class simply wraps a texture cache entry.
> // All the required functionality is provided by TextureCache.
> class XFBSource : public XFBSourceBase
> ```

`class XFBSource final` if it's not intended to be inherited from.

---

*[Source/Core/VideoBackends/Vulkan/FramebufferManager.h, line 175 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4374#-KUjJPY_gPZj8BRNlf0h:-KUjJPYabbOpBPYULNJs:b-izfb0e) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d790601213e032920ba82851804453a2887603d9/Source/Core/VideoBackends/Vulkan/FramebufferManager.h#L175)):*
> ```objc
> {
> public:
>   XFBSource(std::unique_ptr<TextureCache::TCacheEntry> texture);
> ```

`explicit XFBSource`

---

*[Source/Core/VideoBackends/Vulkan/Renderer.cpp, line 558 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4374#-KUjLhTQUBfxKyHjfV87:-KUjLhTQUBfxKyHjfV88:bl7bop1) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d790601213e032920ba82851804453a2887603d9/Source/Core/VideoBackends/Vulkan/Renderer.cpp#L558)):*
> ```cpp
> 
>   // No-XFB case.
>   if (!g_ActiveConfig.bUseXFB)
> ```

The No-XFB and XFB-enabled cases should likely be different functions that are called through this function.

---

*[Source/Core/VideoBackends/Vulkan/StateTracker.h, line 195 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4374#-KUjJsGWhNIeJVk6LBL1:-KUjJsGXPbrDt-AAKbcv:bedai0x) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d790601213e032920ba82851804453a2887603d9/Source/Core/VideoBackends/Vulkan/StateTracker.h#L195)):*
> ```objc
> };
> 
> extern std::unique_ptr<StateTracker> g_state_tracker;
> ```

Note that this makes it more annoying to get rid of global state that plagues the video code (which in particular, is something I'm working on).

---

*[Source/Core/VideoBackends/Vulkan/TextureCache.cpp, line 138 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4374#-KUjMZliMcXKAXSiVY-r:-KUjMZljL04FdqwuO8hG:bn3rtkj) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d790601213e032920ba82851804453a2887603d9/Source/Core/VideoBackends/Vulkan/TextureCache.cpp#L138)):*
> ```cpp
>                       static_cast<u32>(scaled_src_rect.GetHeight())}};
>   Texture2D* src_texture;
>   if (src_format == PEControl::Z24)
> ```

This should likely be its own function.

---

*[Source/Core/VideoBackends/Vulkan/TextureCache.cpp, line 170 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4374#-KUjMuGHMa7hQOn6aoDI:-KUjMuGI48lOQbQWctZh:b6pdroq) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d790601213e032920ba82851804453a2887603d9/Source/Core/VideoBackends/Vulkan/TextureCache.cpp#L170)):*
> ```cpp
> 
>   // Fast path when not scaling the image.
>   if (src_rect.GetWidth() == dst_rect.GetWidth() && src_rect.GetHeight() == dst_rect.GetHeight())
> ```

This fast path should likely be its own function, which is then called through this function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4374)*

**Comment by stenzek** [comment]
@dolphin-emu-bot rebuild

**Comment by JMC47** [comment]
I didn't notice any issues in some quick tests yesterday.  I couldn't find any RealXFB limited games though.

**Comment by Tinob** [comment]
tested on nvidia gtx 750 ,amd r9 290, amd rx 480 and get only a black screen when using real xfb, with virtual xfb or no xfb it works perfectly.

**Comment by JMC47** [comment]
Can anyone else reproduce RealXFB not working on Vulkan?  I can't reproduce it.

**Comment by ichttt** [comment]
RealXFB isn't working for me, too, I'm only getting black screen. Using AMD r9 390 with latest driver(16.10.3).

**Comment by stenzek** [comment]
Seems to be working fine for me on my AMD box (16.9.2 driver).

@ichttt are you testing with this PR? If so, can you try enabling the validation layers (under Advanced), checking Host GPU and Video Backend in the log, and seeing it reports anything useful.

**Comment by ichttt** [comment]
Nevermind, the error was on my end. I forgot to restart Windows after installing the latest driver. It is working perfectly now. Sorry

**Comment by degasus** [comment]
:lgtm:

---

Reviewed 7 of 21 files at r1, 12 of 14 files at r2, 1 of 2 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/VideoBackends/Vulkan/Renderer.cpp, line 494 at r4](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4374#-KVZqDexaS1LW_giwFg8:-KVZqDexaS1LW_giwFg9:bqu02wl) ([raw file](https://github.com/dolphin-emu/dolphin/blob/05ecbce3e44a02d44fc705def305cb0252220ef5/Source/Core/VideoBackends/Vulkan/Renderer.cpp#L494)):*
> ```cpp
> 
>   // Draw to the screenshot buffer if needed.
>   if (IsFrameDumping() &&
> ```

Was it on purpose to dump the screenshot first, and render later on?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4374#-:-KVZrHwWw6HUT_Aur-Jh:bnfp4nl)*

**Comment by stenzek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/VideoBackends/Vulkan/Renderer.cpp, line 494 at r4](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4374#-KVZqDexaS1LW_giwFg8:-KV_T7k9Hi-2Aw0r3oi9:b1uhpk5) ([raw file](https://github.com/dolphin-emu/dolphin/blob/05ecbce3e44a02d44fc705def305cb0252220ef5/Source/Core/VideoBackends/Vulkan/Renderer.cpp#L494)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> Was it on purpose to dump the screenshot first, and render later on?
</details>
Not really on purpose. There isn't any technical reason we couldn't submit the screen blit+present and the readback all in one command buffer though, sounds like a decent small optimization for when framedumping is on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4374)*

**Comment by degasus** [comment]
Looks very good

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4374#-:-KViVvHSLjL4sjGPzPqo:b-iyjphm)*

**Comment by psennermann** [comment]
I tried Batman Vengeance (wich requires Real XFB), but with the Vulkan backend it doesn't work, it only shows a black screen.
Windows 10, Nvidia Gtx950, Intel e8600

**Comment by JMC47** [comment]
Works fine here, Vulkan backend, GTX 1070.

**Comment by JMC47** [comment]
It actually works better than OpenGL; if I turn on realXFB during the videos they start displaying immediately instead of being a black screen until gameplay starts.

**Comment by psennermann** [comment]
Also notice that if I enable Real XFB with the Vulkan backend, every game shows a black screen (but in the background the game is running, because you can hear the audio playing)
Gtx950 Driver 375.70

**Comment by psennermann** [comment]
I have the same problem of Tinob, cause virtual XFB works fine...

**Comment by stenzek** [comment]
Given myself and @JMC47 aren't experiencing this issue I'm going to assume it's not widespread and perhaps specific to some particular hardware or config? @psennermann please open a bug on the issue tracker, and attach your config files if possible.

**Pull request merged**
