### PR TITLE
MemoryPatches: Fix instruction patches

### PR DESCRIPTION
**Pull request by JoshuaMKW**
For a long while, multiple patched instructions at a time could only be restored in reverse order of patching. This PR fixes the oversight, allowing users to restore patched instructions in any order they like.

### CODE REVIEW

**Comment by dreamsyntax** [comment]
Can you please squash these commits to one?

Looks great btw, I've personally been affected by this issue

**Comment by dreamsyntax** [comment]
@dolphin-emu-bot rebuild

**Comment by JoshuaMKW** [comment]
Sure. It'a pretty funny too because I intentionaly split up my changes based on context thinking that was more favored :P

**Comment by AdmiralCurtiss** [comment]
Separate commits are fine, actually, but we don't like merge commits or 'fixup'-style commits. If you can have separate commits that actually make sensible changes per-commit feel free to leave them.

**Comment by dreamsyntax** [comment]
> Separate commits are fine, actually, but we don't like merge commits or 'fixup'-style commits. If you can have separate commits that actually make sensible changes per-commit feel free to leave them.

I was referring to these:
[Merge branch 'master' of](https://github.com/dolphin-emu/dolphin/pull/11201/commits/7e7e6270dc71bb70c0a75cae47ed5167f36db893) https://github.com/JoshuaMKW/dolphin

But I was under the impression Dolphin PRs were 1 commit only.
Good to know that is not the case 👍

**Comment by JoshuaMKW** [comment]
Alright, I figured out squashing and it's been cleaned up!

On another note, what would have me become auto-trusted? It's of course not that important but seeing the "All checks have failed" messes with my head lol.

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by Pokechu22** [comment]
> On another note, what would have me become auto-trusted?

People who have been around for a while can get added once they've submitted a few PRs. Otherwise someone just needs to manually trigger the CI build. I wouldn't worry about it too much for now.

**Review by dreamsyntax — APPROVED** [review]

**Review by Pokechu22 — APPROVED** [review]
Tested by enabling "boot to pause", then launching super mario sunshine and nopping out the first 2 function calls, and then restoring the first one. Before restoring would do nothing, now it works. Code looks good to me too.

**Pull request merged**
