### PR TITLE
Add EditorConfig

### PR DESCRIPTION
**Pull request by bb010g**
Details at http://editorconfig.org/.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3671)

### CODE REVIEW

**Comment by lioncash** [comment]
Enforcing a max line length is kind of unnecessary (our style guide says `Try to limit` to 100 characters max, however there's no hard limit on it because there's stylistic formatting that can potentially exceed this for visual purposes (see our interpreter tables for instance)); the intention is to let common sense dictate that.

**Comment by oldmud0** [comment]
I think I'll just put this here... and fade back into darkness...
xkcd

**Comment by bb010g** [comment]
Fixed. FWIW, there's not really any competing standards, just editor-specific configs. If anyone knows of a more widely supported, cleaner way to do this, please let me know at least.

**Comment by lioncash** [comment]
@delroth recently pushed a reformatting that utilizes [clang-format](http://clang.llvm.org/docs/ClangFormat.html), so I'm not quite sure how relevant this still is.

**Comment by bb010g** [comment]
@lioncash This isn't really serving the same purpose. It's not for setting up a separate step, but rather for common editor variables when editing live. IIRC the more C/C++ specific formatting options (e.g. braces) aren't that well supported. It's mostly so you don't have to set up tabs, trailing whitepace, and end of file new line for your project manually.

**Comment by leoetlino** [comment]
Well, since code must now pass clang-format, you'll probably run clang-format on your code before opening a PR anyway (or setting up git to do it automatically), so configuring the editor is not really an issue anymore.

(also, we have switched to 2 spaces instead of tabs.)

**Comment by RisingFog** [comment]
I also doubt if this PR is still relevant with clang-format now being used.

**Comment by JosJuice** [comment]
It's still nice to get the right indents and such at once instead of only getting them right after running clang-format, so I would say that this PR still is relevant. It does however need to be updated, because we're not using tabs anymore.

**Comment by bb010g** [comment]
Fixed and rebased.

**Comment by Armada651** [comment]
According to a [user feedback ticket](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/6146845-support-editorconfig) the EditorConfig format will be natively supported in next version of Visual Studio.

So it's definitely useful to merge this to prevent incorrect code styling instead of fixing it afterwards using clang.

**Comment by bb010g** [comment]
Rebased with @JosJuice's suggestion put in. I also looked through the most common source file types and tried to make it a bit more thorough. (Using `charset = utf-8` for all source files could potentially be a problem if #5330 is merged, but it looks like that's leaning towards staying UTF-8 only. I didn't find any non–UTF-8 files with an `enca -L none Source/**/*` scan.)

**Comment by JosJuice** [comment]
The question in PR #5330 is whether we should use UTF-8 or ASCII, so either way, it will be compatible with UTF-8.

**Comment by shuffle2** [comment]
Thanks! I think VS being able to properly auto-format as one edits is a necessary feature (which was broken since the draconian formatting change took effect...grumble grumble)!

**Comment by oldmud0** [comment]
"One year later..."

**Comment by shuffle2** [comment]
It seems the editorconfig utf8 setting causes the utf8 BOM to be inserted in source files.

AFAICT this is nonstandard for dolphin sources. It was previously worked around (for windows at least), by passing a flag to cl to tell it to treat all sources as utf8 regardless of what sniff-testing the file might indicate. See #5330 .

The linter doesn't seem to care either way (but maybe it's broken atm?).

**Comment by oldmud0** [comment]
Oh, I forgot about that... Yeah, pretty much every Microsoft program tends to add the BOM by default when the encoding is set to any Unicode-related. I didn't know that that "feature" would creep into the new EditorConfig addition of Visual Studio.

Looks like the bug has [already been fixed by VS devs](https://developercommunity.visualstudio.com/content/problem/22922/editorconfig-support-interprets-charset-utf-8-as-u.html) and is "pending release." Might want to revert the merge until this is fixed for good.

**Comment by shuffle2** [comment]
@oldmud0 Just dropping the utf-8 setting seems fine for us, since we are using `/utf-8` to cl anyways.(?)

**Pull request merged**
