### PR TITLE
Epic change is epic.

### PR DESCRIPTION
**Pull request by neobrain**
Just for getting the build bot to build a test build for JMC.

### CODE REVIEW

**Comment by neobrain** [comment]
For future reference,
```
< neobrain> the point of this patch is that Dolphin currently gets it wrong what kind of things should actually be stretched - before, it would upscale the
                  bottom-right-most pixel coordinate. e.g. for 3xIR and for a "full" scissor rect, it would multiply 639 by 3, which is 1917, such that it would use a viewport
                  width of 1918 instead of 1920
< neobrain> [...] the top-left-most corner of the scissor rect is inclusive, though, hence it is indeed the proper coordinate to use for upscaling
```

**Comment by neobrain** [comment]
Pushed a slightly different change, which transfers the fix to all users of ConvertEFBRectangle. That makes this change more unpredictable than I'd like to, but I think it may not work properly without consistently changing all violators of this kind of issue.

**Comment by delroth** [comment]
I'm surprised that FifoCI shows no changes. Is that expected?

**Comment by phire** [comment]
Probably because it only affects rendering at higher IRs, and FifoCI is at 1xIR

**Comment by neobrain** [comment]
@delroth I was surprised too, but... what @phire said.

**Comment by delroth** [comment]
Hmmm... I should fix that at some point :)

**Comment by neobrain** [comment]
Not so epic after all, since BPFunctions::SetScissor already converts the scissor coordinates to what Render::SetScissorRect expects. I still think something fishy is going on, though.

**Pull request closed without merging**
