### PR TITLE
Fix the pause/play toolbar button not updating when reaching a breakp…

### PR DESCRIPTION
**Pull request by aldelaro5**
…oint or a memory check

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4126)

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by aldelaro5** [comment]
Bump (even though i am aware of the bug on master, this button starts to get me crazy lol )

**Comment by Helios747** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4126)*

**Comment by Helios747** [comment]
Nice catch. LGTM.

**Pull request merged**
