### PR TITLE
Memmap: Remove pointer casts

### PR DESCRIPTION
**Pull request by lioncash**
Gets rid of ugly casts, and also silences some ubsan asserts

### CODE REVIEW

**Comment by degasus** [comment]
I'm not sure, will this generate an as good assembly? This function is called quite often :/

**Comment by lioncash** [comment]
Yes it will (https://goo.gl/50jAT7). memcpy is typically implemented as an intrinsic in compilers. Also, the previous code is technically undefined behavior (misaligned pointer dereferencing)

**Comment by comex** [comment]
For the record, I just verified using that site that both gcc and clang do the right thing even at -O0 (which is fairly important - when I develop I build at -O0, for example).  Does anyone want to check MSVC?

**Comment by degasus** [comment]
@comex Are you looking for a correct implementation, or a fast one? Personally, I don't care about the optimizations done at -O0

**Comment by comex** [comment]
A fast one, though I guess a real call to memcpy probably wouldn't show up anyway among all the other unoptimized crap.  Never mind me.

**Comment by phire** [comment]
I don't really like compiling at -O0. Would rather read the -O2 assembly.

**Pull request merged**
