### PR TITLE
DriverDetails: Add broken discard with early-Z bug on Apple Silicon GPUs

### PR DESCRIPTION
**Pull request by OatmealDome**
The drivers for newer Apple Silicon GPUs appear to have some sort of issue with ``discard`` when early-Z testing is enabled. Fragments that are discarded can appear corrupted (glitchy textures, being rendered as all black, completely invisible, etc).

I workaround this issue by emulating ``discard`` using framebuffer fetch. Instead of using the built-in ``discard``, I read in the value of the framebuffer and use that as the fragment output. Unfortunately, I couldn't figure out a good solution that works with hardware blending (what do I write out to ``ocol1``?), so shader blending is enforced. This may decrease performance a bit.

I also solve a pre-existing bug with OpenGL where using shader blending along with ubershaders may result in double blending due to the fact that the [OpenGL backend uses a different check for shader blending](https://github.com/dolphin-emu/dolphin/blob/6f4bbac528682389e34a1a4985820ee5137619c7/Source/Core/VideoBackends/OGL/OGLRender.cpp#L1169) versus the [Ubershader generator](https://github.com/dolphin-emu/dolphin/blob/b1f79d9ecf87070c78789acdf5bc329637bc5812/Source/Core/VideoCommon/UberShaderPixel.cpp#L57).

Fixes [Super Mario Sunshine](https://cdn.discordapp.com/attachments/653998925107429386/861712011657347082/image0.png), [Sonic Adventure 2: Battle](https://bugs.dolphin-emu.org/issues/12523), [Phantasy Star Online Episodes 1 & 2](https://bugs.dolphin-emu.org/issues/12705), [Chibi Robo](https://user-images.githubusercontent.com/11504941/147392700-24958863-f663-4a93-bc12-2605796d09c1.png), and probably a bunch more.

### CODE REVIEW

**Comment by OatmealDome** [comment]
@dolphin-emu-bot rebuild

**Comment by andevode68** [comment]
Hi @OatmealDome ,

Is there a certain build that this is already fixed in? Or is it not implemented into a build yet? I'm running build dev version 5.0-15801 on an M1 Mac mini and having the black textures issue with Vulcan backend. Thanks!

**Comment by OatmealDome** [comment]
@andevode68 There is no beta or development build with this fix in it at this time. Before that happens, core Dolphin developers must review this pull request to ensure the code quality is acceptable, then choose to "merge" it. Once that happens, a new development build will be automatically made with this fix.

That being said, you can download a testing version of this pull request [here](https://dl.dolphin-emu.org/prs/42/88/pr-10290-dolphin-latest-universal.dmg). However, I don't recommend staying on a pull request build for very long, as you may miss other fixes and improvements that get added over time to the development / beta builds.

**Comment by andevode68** [comment]
@OatmealDome FANTASTIC! Thank you for the quick response! That definitely fixed it, and after applying 16:9 codes, it looks just as good as the Steam version! Now I just wish the frame times were consistent, but I guess this game is just hard to emulate. But I'm not going to complain because now the game is playable! This is the only game I couldn't play, and now I can! Thank you again!!

**Comment by JosJuice** [comment]
Please squash the lint fix.

**Comment by OatmealDome** [comment]
Squashed.

**Comment by OatmealDome** [comment]
@dolphin-emu-bot rebuild

**Comment by OatmealDome** [comment]
@dolphin-emu-bot rebuild

**Comment by dvessel** [comment]
This also fixes Ikaruga. The only way to make it render correctly was to enable exclusive ubershaders before this fix.

**Comment by Neirene** [comment]
With this build PSO isn't even starting anymore as I'm getting these errors while trying to get into the game. The video output completely freezes (but the audio continues playing) and I have no choice but to close the emulator.

image
image

Macbook Air M1 16/8GPU
Big Sur 11.6.5 (20G527)

**Comment by OatmealDome** [comment]
@Neirene This might just be a dual core bug. Try turning off dual core (uncheck Config -> General -> Enable Dual Core).

**Comment by Neirene** [comment]
@OatmealDome It was indeed a dual core bug, by disabling it I was able to proceed to the game as usual.

Now i'm posting here 2 short clips with the results and can confirm it fixes the graphics rendering issues on M1 for Phantasy Star Online Episode 1 & 2 Plus (GPOJ8P)

Before:
https://user-images.githubusercontent.com/5244595/163893892-519589fd-08dd-4f54-ba14-f05f8ed633a7.mov

After:
https://user-images.githubusercontent.com/5244595/163893780-1388498c-f60e-4cb3-accd-d83495322c5e.mov

Macbook Air M1 16/8GPU
Big Sur 11.6.5 (20G527)

**Comment by dvessel** [comment]
Something changed after the rebase. I get flickering textures in F-zero, a game that didn’t have problems before these changes. Ikaruga which was affected now has it worse. What bypassed the problem before _enabling exclusive ubershaders_ prevented the problem for the two I just tested.

Screen Shot 2022-04-19 at 11 55 55 AM
Screen Shot 2022-04-19 at 11 57 19 AM

I also got a ton of these dumps before I trashed the shader cache.

[bad_ps_Vulkan_348.txt](https://github.com/dolphin-emu/dolphin/files/8514618/bad_ps_Vulkan_348.txt)

**Comment by OatmealDome** [comment]
@dvessel Please try again - I made a mistake while rebasing.

**Comment by dvessel** [comment]
It’s not as severe but I still get broken textures. I got a bunch of render time logs from dev but I stopped after running f-zero from this pull.

Disabled audio, native resolution and emulation speed set to 5x which it never hits.

f-zero single attract loop, average frame time:
- master: 7.2256
- 10290: 7.4069

**Comment by OatmealDome** [comment]
@dvessel Would it be possible to send a FIFO log of the flickering textures? I wrote instructions here: https://bugs.dolphin-emu.org/issues/12705#note-1

Also, this change only really affects the GPU side of things, so increasing IR slowly and seeing when performance starts to dip is what I think would be the best way to benchmark this.

**Comment by dvessel** [comment]
Okay, I’ll get to it later today. I thought I was looking for performance regressions due to instructions normally done on the GPU being done in the CPU instead due to the bug.

**Comment by nolrinale** [comment]
Running a similar test, whatever was changed, it really got broken.... the menus included

image

image

Fifo Menu
[fifopsomenu.dff.zip](https://github.com/dolphin-emu/dolphin/files/8524363/fifopsomenu.dff.zip)


Pioneer 2
image

Fifo Pioneer 2

[fifopioneer2.dff.zip](https://github.com/dolphin-emu/dolphin/files/8524366/fifopioneer2.dff.zip)


Central Control Area (The area shown in the previous reply)
image

Fifo CCA
[fifocca.dff.zip](https://github.com/dolphin-emu/dolphin/files/8524392/fifocca.dff.zip)

I've increased the IR to up to 4x and the performance and FPSs are not affected only the graphics

**Comment by dvessel** [comment]
[f-zero-10290.zip](https://github.com/dolphin-emu/dolphin/files/8524467/f-zero-10290.zip)

**Comment by OatmealDome** [comment]
@dvessel I fixed another issue with the rebase, please try again.

**Comment by nolrinale** [comment]
Testing once again with the latest build after the push, seems to be the issues are fixed again.


image

image

image

image

**Comment by dvessel** [comment]
- hybrid ubershaders.
- 1x anistrophic filtering.
- fast texture cache accuracy.
- efb and xfb copies to texture only.
- fast depth calculation.
- disable bounding box.
- backend multithreading.
- defer efb cache invalidation.

```
fzero 1x 10290	frames: 11133	 average: 7.4198149645198956 ms
fzero 1x master	frames: 11443	 average: 7.2256925631390372 ms
fzero 2x 10290	frames: 11133	 average: 7.2740411389562558 ms
fzero 2x master	frames: 16300	 average: 7 ms
fzero 3x 10290	frames: 11131	 average: 7.4293953822657448 ms
fzero 3x master	frames: 11181	 average: 7.4691172524818885 ms
fzero 4x 10290	frames: 11158	 average: 7.4325327119555471 ms
fzero 4x master	frames: 11160	 average: 7.455313620071685 ms
fzero 5x 10290	frames: 11133	 average: 7.601464115692087 ms
fzero 5x master	frames: 11142	 average: 7.6092802010411065 ms
fzero 6x 10290	frames: 11159	 average: 7.7873734205573975 ms
fzero 6x master	frames: 11205	 average: 7.7745292280232041 ms
fzero 7x 10290	frames: 11132	 average: 7.9130614444843692 ms
fzero 7x master	frames: 11127	 average: 8.3176597465624162 ms
fzero 8x 10290	frames: 11152	 average: 8.1549049497847914 ms
fzero 8x master	frames: 11127	 average: 8.6827626494113428 ms
```

My usual settings (includes the other settings):

- 16x anistrophic filtering.
- FXAA post-processing.
- 4x upscaled DDS textures loaded.

```
fzero 6x 10290	frames: 11197	 average: 7.86904527998571 ms
fzero 6x master	frames: 11200	 average: 8.6192232142857144 ms
```

What’s odd here is that my usual settings perform faster than master. ¯\_(ツ)_/¯ 

@OatmealDome mentioned to me that this was held up because of the potential performance regression for games that weren’t affected. I could test Ikaruga but there’s no point. Using dedicated ubershaders to work around the bug was a massive performance drain and this fixes it.

**Comment by dvessel** [comment]
Oh, and here is Ikaruga. No more texture problems.
Screen Shot 2022-04-20 at 4 16 12 PM

**Comment by dvessel** [comment]
Quick Rogue Squadron test.. Removed 3 frame spikes (in excess of 1k ms) for each run. They are pretty much the same.

```
rs 1x 10290	frames: 6609	average: 8.1331971553941607 ms
rs 1x master	frames: 6610	average: 7.9330711043872917 ms
rs 3x 10290	frames: 6612	average: 8.4785541439806416 ms
rs 3x master	frames: 6600	average: 8.3203181818181822 ms
rs 6x 10290	frames: 6606	average: 9.0858764759309718 ms
rs 6x master	frames: 6604	average: 8.7511053906723202 ms
rs 8x 10290	frames: 6609	average: 9.8672870328340139 ms
rs 8x master	frames: 6625	average: 9.9530867924528295 ms
```

**Comment by dvessel** [comment]
I’ve been keeping this up to date locally and it works great. What else is needed to get this merged? Please don’t let it go stale, thanks!

**Pull request merged**
