### PR TITLE
[Android] Add the missing Stereoscopic options

### PR DESCRIPTION
**Pull request by mahdihijazi**

### CODE REVIEW

**Comment by degasus** [comment]
Sounds good

**Comment by mahdihijazi** [comment]
@degasus I don't have any 3d screen or VR glasses but I do see the side-by-side effect on my normal screen. I hope is it working fine.

**Comment by brujo5** [comment]
Yeah it work very well

**Comment by Sarkie** [comment]
screenshot_20170503-223858
img_20170504_123009
img_20170504_123221

Works very well and adds cool depth. Thanks!

**Comment by mahdihijazi** [comment]
@Sarkie glad it works, which phone you used to test this out?

**Pull request merged**
