### PR TITLE
DolReader: treat overly large data segment as bss

### PR DESCRIPTION
**Pull request by shuffle2**
some homebrew sets `dataOffset[i]+dataSize[i]` larger than file size

### CODE REVIEW

**Comment by Helios747** [comment]
why is shuffle2 not auto trusted

@dolphin-emu-bot rebuild

**Comment by lioncash** [comment]
Good question. Sent an invite to be added to the trusted devs

**Comment by shuffle2** [comment]
tbh i don't really want to feel like i have responsibilities to the dolphin project. I've removed myself from everything related a while ago. considering the extremely low amount of patches I submit now, I think that's fine.

**Comment by lioncash** [comment]
Trusted devs doesn't really have any responsibilities (other than, y'know, not being malicious with the build system). It's just for people that are trustworthy enough that the buildbot can automatically proceed for them.

Either way, I respect the decision

**Comment by shuffle2** [comment]
However, someone could still merge it at some point. 😑

**Comment by sepalani** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
