### PR TITLE
Enforce UTF-8 now that VS handles it sanely

### PR DESCRIPTION
**Pull request by bb010g**
Follow up to #5541. [Fixed in 15.3](https://developercommunity.visualstudio.com/solutions/93089/view.html).

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/6152)

### CODE REVIEW

**Comment by JosJuice** [comment]
Let's wait with merging this until we don't support the versions of VS where it gives BOMs. LGTM other than that.

**Comment by leoetlino** [comment]
Let's get this merged once #8087 is merged (which will bump the version requirement to VS2019 AFAICT).

**Comment by bb010g** [comment]
Bump since that's merged?

**Comment by JosJuice** [comment]
You can still build Dolphin with VS2017, actually. It's currently possible to build with either CMake or MSBuild, and only the former requires VS2019.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
Dolphin no longer builds on VS2017, so it's merge time. (The build failures are just because this PR is based on an old version of master.)

**Pull request merged**
