### PR TITLE
[Android] Update build tools + support libraries

### PR DESCRIPTION
**Pull request by sigmabeta**
Support library updates should get us some minor UI bugfixes; don't really know what those are, but either way, it's good to keep up with the latest versions of those.

Build tools updates bring drastically improved build speeds, and support for the "Instant Run" feature that allows testing/deploying builds without uninstall/reinstall/relaunch of the app, if deployed from Android Studio.

### CODE REVIEW

**Comment by sigmabeta** [comment]
@dolphin-emu-bot rebuild

**Comment by sigmabeta** [comment]
@dolphin-emu-bot rebuild

**Comment by sigmabeta** [comment]
@dolphin-emu-bot rebuild

**Comment by sigmabeta** [comment]
This PR depends on https://github.com/dolphin-emu/sadm/pull/56 to successfully build. That PR was merged, but for some reason Buildbot is still running `gradle` instead of `gradlew`.

@delroth @Parlane What needs to be done for that merge to take effect?

**Comment by delroth** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
