### PR TITLE
Qt: Introduce simplified mode

### PR DESCRIPTION
**Pull request by spycrab**
# Simplified Mode

**Obviously highly WIP!**

This PR introduces simplified mode
which aims to help new and inexperienced users
by hiding settings that may confuse them.

**Simplified mode will be enabled by default.**

## Things hidden by simplifed mode
(and why they are hidden)

 * Menubar (not on macOS): Has many entries that are also accessible using the toolbar.
 * Config
	* Advanced tab
	* Interface/"Show debugging UI": Can't be used while simplified mode is enabled
 * Graphics Window
    * Hacks tab: Contains settings that are mostly confusing to users
	* Advanced tab
	
## Open Questions

 * This needs to be enabled by default but should not be forced upon existing users. How can we ensure this?
 * What else needs to be disabled?
 * Graphics: Do we need a "Safe"/"Fast" slider for all settings?

### CODE REVIEW

**Comment by irishmapping** [comment]
Interesting, but i feel like i could add something. Maybe you (or a dev) could make the hotkey settings better as well. Maybe remove things like freelook, some of the savestate options (e.g only have save and load states 1-3), and maybe even remove the speed options.
I personally had a lot of trouble with these when I was younger and used an emulator for my SNES because it stopped working, i just couldnt figure out things like that. Just a suggestion!
Also, maybe disable the cheats. That would be pretty good for people who can't use them (me included!)

**Comment by legoj15** [comment]
I agree with what @irishmapping said, except for the part about disabling/hiding cheats. I feel like users expect to find cheats as an option for any popular emulator, and hiding that setting from users under a setting that toggles the simplistic UI would actually cause confusion; there is a game on Steam called [Space Engineers](https://store.steampowered.com/app/244850), and the developers had a similar idea to add a simplified menu as an option and to make it the default. This menu hid a lot of features that were expected of the game, and users who happened to purchase the game after this update were very confused as to why they couldn't make a custom world or enable mods and it tanked their reviews. So IMO two features that shouldn't be hidden are cheats and netplay (the netplay menu might benefit from simplification though).

Sorry for the block of text, just my stance on that idea and want to prevent new user confusion. I might give more feedback if I feel it's warranted.

**Comment by jordan-woyak** [comment]
I don't think a simple mode should be the default. Ask the user on first run if they are simple.

**Comment by Zexaron** [comment]
> I don't think a simple mode should be the default. Ask the user on first run if they are simple.

The statistics reporting and this could share the same dialog on first boot, to save 2 dialogs from appearing.

But if more things get added, then I'd rather have it multi-paged, like a wizard. That's not unusual for programs. There's probably more things that could be added there that I can think of but that's for another discussion.

**Comment by irishmapping** [comment]
Yeah, maybe not the cheats, and i agree with a dialogue box on first run. However, one thing I hav *always* noticed, is that macOS and Windows (Specifically, Windows Vista-8.1, partially 10) handle these dialogue boxes very differently from each other, which actually lead to lots of confusion on my extremely old Python project on my old account. I had a message box popup for when it looked like the user was using it first time or hadn't used it in a very long time (a month,) but I coded the program mainly for macOS. The dialog box for Windows and Linux users (And people running Mac OS X Mavericks or older,) did not look right. "Umm... Why does the message box look like you drew it in MS Paint?" -some person. Basically, dialog boxes don't work well cross-platform. But keep in mind this is in Python, and dolphin uses C or something. It might be fine on C but idk? 
PS: Android users. might have some problems with this. I know for a fact Android is definitely not great with pop up boxes (mayhave been fixed, they were bad as of Android O) and could cause issues for some users. 
And keep in mind I'm not an expert in coding, after all I only use python and web languages.

**Comment by mbc07** [comment]
This PR introduces the simplified mode to Qt only, Android won't be affected at all, at least not by the (current) scope of this PR...

**Comment by irishmapping** [comment]
Dammit, i was tryna get to sleep!
Personal issues aside tho....
Aight. Then that shouldnt be a problem.

**Comment by mimimi085181** [comment]
"Do we need a "Safe"/"Fast" slider for all settings?"
I would say yes. If you switch between simple and advanced mode, it shouldn't apply settings from advanced mode that are not visible in simple mode, at least not without clear indication. If you do the sliders, you could add a custom setting, if the actual settings don't match the fast/balanced/safe/safe+ presets. With that, it would be a clear indication that Dolphin is not really using simple mode, without just resetting your settings by clicking on the simple mode button.

**Comment by irishmapping** [comment]
^
Also, can you explain that a bit better? I'm like 13 and my english sucks...

**Comment by spycrab** [comment]
Currently not sure what direction to take this in. Might integrate this into another PR later on.

**Pull request closed without merging**
