### PR TITLE
Unicode correctness

### PR DESCRIPTION
**Pull request by Armada651**
This PR address some unicode issues when building or running Dolphin on systems with non-Latin codepages.

Instead of changing the source files I added the `/utf-8` to the compiler options that ensures all source are parsed with UTF-8 and all strings are encoded with UTF-8 by default.

### CODE REVIEW

**Comment by lioncash** [comment]
Note that you don't need to use a BOM when compiling on MSVC, you can simply set the [/utf-8 or /source-charset:utf-8](https://msdn.microsoft.com/en-us/library/mt708821.aspx) flag in your user property page (or just put it in the build commands directly). I used to run into this with the JP locale set on my Windows PC, but it worked once I specified the source charset.

**Comment by Armada651** [comment]
@lioncash Yeah I got that tip from Stenzek on IRC. Still, it would be nice to have a permanent solution in place. We just need to discuss that that permanent solution should be. Should we add `/utf-8` to the compiler flags or fix it in the source code?

**Comment by lioncash** [comment]
Setting the source charset is probably a better solution, as well as less error prone (no one needs to worry about forgetting to add a BOM in any new files where necessary). It also keeps platform/compiler specific encoding handling 'quirks' (for some definition of quirk. In this case, MSVC being MSVC) out of the source files.

**Comment by Armada651** [comment]
@lioncash It could potentially also affect GCC, according to the documentation it could also be affected by the system code page. So @Orphis suggested that the most reliable fix would be to just fix the source code.

But no one likes BOMs, so fixing the source code would imply adding a bunch of `\u` and `u8` where necessary.

I'm fine with either solution, though I prefer the compiler flag option.

**Comment by BhaaLseN** [comment]
I wouldn't want UTF-16 source files; they don't seem to play well with most Diff tools. YMMV, but at least one of the SQL Scripts we got under version control at work (which, when directly exported from the SQL tool that dev uses, defaults to UTF-16) is treated like a binary and fails pretty much on every minor concurrent change.

IMO we should just slap on that compiler switch for MSVC.

**Comment by Armada651** [comment]
@BhaaLseN There's an encoding of UTF-8 with BOM, so that doesn't imply UTF-16.

**Comment by Orphis** [comment]
Just removing the UTF-8 characters should be enough for our code.
I don't like adding compiler flags when there is another solution.

Externals are fine to compile with that flag (ex libusb), ffmpeg header's should be fixed as it is propagating the UTF-8 requirement to all sources including it (and I'm sure 99% of users are unaware). It seems that it's only a unicode "Q" in that file actually.

**Comment by BhaaLseN** [comment]
I know, and thats what we use (plus, IMO should keep); I just wanted to make my point about UTF-16 encoded files.

**Comment by lioncash** [comment]
I've no real hard preference either (though I lean towards the switch). Feel free to tiebreak it however you wish.

**Pull request merged**
