### PR TITLE
Android: Make DSP setting work with custom GameSettings

### PR DESCRIPTION
**Pull request by Ebola16**
This is a special case since DSP is actually two settings.

### CODE REVIEW

**Comment by JosJuice** [comment]
This is also fixed by PR #8975, for the reference. Though I dunno, I guess adding a workaround in the meantime isn't *too* bad since it's relatively easy to remove...

**Comment by Ebola16** [comment]
I plan on looking at #8975 once #8941 is merged. If you think it will be a while before #8975 is merged it's probably worth merging this.

**Comment by Ebola16** [comment]
@dolphin-emu-bot rebuild

**Comment by Ebola16** [comment]
Closing in favor of #8975.

**Pull request closed without merging**
