### PR TITLE
Replace indirection operator with arrow operator

### PR DESCRIPTION
**Pull request by tygyh**

### CODE REVIEW

**Review by JosJuice — APPROVED** [review]
The commit title isn't quite correct, as there's the same amount of dereferencing before and after, but whatever. LGTM.

**Review by BhaaLseN — APPROVED** [review]
Yeah its just a syntax simplication, not a difference in what happens. But good enough for me 👍

**Comment by tygyh** [comment]
> The commit title isn't quite correct

What would be a more correct title?

**Comment by JosJuice** [comment]
Maybe "Replace indirection operator with arrow operator"?

**Pull request merged**
