### PR TITLE
Enhanced Gecko Codehandler

### PR DESCRIPTION
**Pull request by gamemasterplc**
Based off codehandleronly.bin and includes enhanced code support. Also allows you to use more codes before Dolphin hangs at startup. Specifically it includes cache invalidation on stores. The cache invalidation allows a wider range of button activated codes to work.

### CODE REVIEW

**Comment by sepalani** [comment]
Whitespaces are inconsistent in the assembly code. Could you replace them either by spaces or tabs? I don't have a strong opinion between both but I'd rather suggest spaces as the output should be same and won't depend on your text editor.

**Comment by gamemasterplc** [comment]
that was the original source code's fault. I just edited it to my needs

**Comment by MayImilae** [comment]
What was the license on the original source code?

**Comment by mimimi085181** [comment]
The license of the codehandler was discussed months/years ago, and i think it was inconclusive. On the other hand, i'm pretty sure the source of Gecko OS 1.3.x was released under GPL v2, and the codehandler is a part of that.

**Comment by gamemasterplc** [comment]
it was from gecko os 1.9.3.1 and that license is unsure

**Comment by MayImilae** [comment]
Hmm... I downloaded the gecko os 1.9.3.1 source code, and there wasn't a single license file to be found! That... complicates things.

[As stated by the gnu...](https://www.gnu.org/licenses/license-list.en.html#NoLicense)

>If source code does not carry a license to give users the four essential freedoms, then unless it has been explicitly and validly placed in the public domain, it is not free software.
>
>Some developers think that code with no license is automatically in the public domain. That is not true under today's copyright law; rather, all copyrightable works are copyrighted by default. This includes programs. Absent a license to grant users freedom, they don't have any. In some countries, users that download code with no license may infringe copyright merely by compiling it or running it.

The simplest solution to this would be to simply find one of the devs and ask them about it. If they say it's public domain, we should be fine using it. If we can't find them though, it gets a bit messy...

**Comment by lioncash** [comment]
Requested to be closed on IRC

**Pull request closed without merging**
