### PR TITLE
GeometryShaderGen: Don't use `centroid in` for input variables.

### PR DESCRIPTION
**Pull request by Armada651**

### CODE REVIEW

**Comment by JosJuice** [comment]
This fixes shader compilation errors on my Intel GPU. Dolphin still freezes around the point where the shader error was before, but I don't know if that's a related problem or not, because it also happens on games that didn't have any shader errors before this PR.

**Comment by Armada651** [comment]
@degasus Please review.

**Comment by degasus** [comment]
LGTM

**Comment by phire** [comment]
However, It creates shader compilation errors on my AMD gpu. 

See [Issue 8643](https://code.google.com/p/dolphin-emu/issues/detail?id=8676)

**Comment by Sonicadvance1** [comment]
Causes issues under catalyst in Linux, and the Nvidia proprietary driver as well.

**Comment by Armada651** [comment]
@JosJuice Do you still have that shader dump from Intel?

**Comment by JosJuice** [comment]
http://pastebin.com/bd5nkRdw

**Comment by Armada651** [comment]
Clearly fixing this on both Intel and other GPUs would require the vertex
shader to have knowledge about the presence of the geometry shader.

We will have to look up if the OpenGL spec really disallows the `centroid
in` qualifier in the geometry shader. If it allows those qualifiers then
I'll revert this change and disable the geometry shader on the affected
Intel drivers.

**Comment by Armada651** [comment]
> For these inputs, "centroid in", "sample in", and interpolation
qualifiers are allowed, but are equivalent to "in".
https://www.khronos.org/registry/gles/extensions/EXT/EXT_geometry_shader.txt

Intel is not conforming to the spec.

**Comment by Armada651** [comment]
Perhaps this behaviour is only due to interface blocks, I'll try to disable
those on Intel first.

**Pull request merged**
