### PR TITLE
IOS/ES: Return IPC_EINVAL for unknown ioctlvs

### PR DESCRIPTION
**Pull request by leoetlino**
Instead of allowing unknown ioctlvs and faking success for both unknown and unimplemented ioctlvs, which can possibly result in nasty, hard to debug bugs (if the emulated software behaves unexpectedly), we should reject unknown ioctlvs and log known, but unimplemented ioctlvs.

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Is there any particular reason why you didn't just change the `default` case to dump the values (other than some Clang warning about missing cases)? IMO the result should be the same, just to make sure we don't miss any ioctls that didn't show up in the enum to this point. If there were an ioctl `0x46` for example, it wouldn't log but just return `EINVAL` - I'd say it should still log it anyways.

**Comment by leoetlino** [comment]
I removed the logging for the default case because those are 100% known to be invalid requests. There are only 0x45 at most in all versions of IOS.

**Comment by BhaaLseN** [comment]
Are there really any games that spam invalid ioctls? Or is this mostly homebrew?
LGTM in that case.

**Comment by leoetlino** [comment]
There was a bug in libogc where it would send invalid ioctlvs to /dev/es in some cases. I don't think there's any game that does this, since they are not supposed to know about ES :P

**Pull request merged**
