### PR TITLE
DolphinFX shader pack, working

### PR DESCRIPTION
**Pull request by TryTwo**
It works again. Don't think there's a reason not to merge it.

### CODE REVIEW

**Comment by BhaaLseN** [comment]
So, thats one big shader? You should probably rename that PR, and possibly even clean up the commit history (unless it makes sense to keep them separate, even squash them into one commit; ```git rebase -i origin/master``` where origin is the name of the Dolphin remote, then change ```pick``` to ```squash``` for all but the first line).

**Comment by TryTwo** [comment]
It can be squashed. I'm a bit new to git and am figuring it out. Thanks.

**Comment by ADormant** [comment]
Could someone offer more advice on squashing commits ?

**Comment by ADormant** [comment]
Could someone offer more advice on squashing commits from another fork ?

**Comment by ADormant** [comment]
Could someone offer more advice on squashing commits from another fork ?

**Comment by BhaaLseN** [comment]
You don't, you'd have to create your own fork first. But since its not your fork, your code, your work, you should refrain from doing that unless you talked to the original author (which is why this PR was closed for now).

**Comment by neobrain** [comment]
Cf.  #1535 as for "Don't think there's a reason not to merge it".

**Pull request closed without merging**
