### PR TITLE
VideoCommon: move TCacheEntry to its own file, so it can be forward declared

### PR DESCRIPTION
**Pull request by iwubcode**
I also moved functions that were header only to be in the cpp and tried to forward declare what I could.

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
What exactly do you need this for? I'm kinda hesitant on making anything in the texture cache code more public, because the code itself is extremely overcomplicated and really should be rewritten at some point, so ideally not much should rely on the details.

**Comment by iwubcode** [comment]
@AdmiralCurtiss - agree completely on `TextureCacheBase` needing a rewrite.

The code might be fine with how it is in master.

I want to expose some details from `TCacheEntry` (whether the texture is hi-res, whether it has arbitrary mipmaps, possibly the raw data, etc) to the graphics mods.  I *think* I only need it in `VertexManagerBase.cpp` which already pulls in that header but I was contemplating just passing `TCacheEntry` down to `VertexShaderManager.cpp` in case any of those details were useful for projection effects.  However when doing that, I realized I'd have to have everything pulling in `VertexShaderManager` to know about `TextureCacheBase` which wasn't ideal.  Hence this PR.

I suppose I could alternatively introduce a new structure (if needed).

There's a lot to do and I'm trying to be better about pushing stuff in smaller chunks.  But it's difficult because I don't know all the details until I get further along.

This PR might have been a little hasty.  I'll mark it as WIP until I have a better idea.

**Comment by iwubcode** [comment]
Ok, looking at this a bit more.  The main driver is more so one of potential performance.  Rather than creating a `std::vector<std::string_view>` to pass to `VertexShaderManager`, I just opted to pass the `std::vector<VideoCommon::TextureCache::CacheEntry*>` which was needed for the "draw_started" action.

That probably doesn't make a lot of sense just seeing the words.  We can revisit when that PR goes live (could be a few weeks, not sure).

**Comment by iwubcode** [comment]
@phire already has something else planned.  Closing

**Pull request closed without merging**
