### PR TITLE
WiimoteReal: Fix device handles not being closed

### PR DESCRIPTION
**Pull request by leoetlino**
fail, my bad.

I have no idea how this didn't cause issues for more people.

### CODE REVIEW

**Comment by slottedpig** [comment]
Leoetlino...I am also having issue with the real wiimote setting in the dolphin emulator....If it is turned on it slowly degrades the emulator till it crashes out after about 45 minutes.

**Comment by JMC47** [comment]
I think this was designed to fix that?

**Comment by slottedpig** [comment]
It didnt occur in the 5.0 official build only after build .867 does this start to occur.  If I turn it off in the newest version the emulator runs fine.  I bisected to pinpoint this...it took sooooo long because it takes 45 mins everytime for it to occur.

**Comment by shuffle2** [comment]
@slottedpig you should try the build  generated by this commit

**Comment by JMC47** [comment]
https://dl.dolphin-emu.org/prs/pr-5972-dolphin-latest-x64.7z this if you're on windows

**Comment by leoetlino** [comment]
Merging as the user reported this fixed their pretty severe issue. Still, I'm not sure how this didn't end up breaking for more users... Unless most people have continuous scanning disabled?

**Comment by Wowfunhappy** [comment]
Dumb user commenting here, but I definitely experienced this problem when I had continuous scanning enabled.

At the time, figured it was a weird system specific issue, disabled continuous scanning, and moved on. (Not sure why I thought to disable continuous scanning, I think I had it turned off originally and then the problems began when I turned it on.)

**Pull request merged**
