### PR TITLE
Use .manifest file for apps on Windows

### PR DESCRIPTION
**Pull request by ligfx**
Works with CMake, and also adds DPI awareness to DolphinQt2 (which wasn't enabled before).

### CODE REVIEW

**Comment by ligfx** [comment]
@Orphis

**Comment by BhaaLseN** [comment]
Should we set the [`<supportedOS>`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa374191.aspx#supportedos) values too while we're at it?

**Comment by Orphis** [comment]
Which value would we set then? The untested and unsupported Vista or Win7?

**Comment by BhaaLseN** [comment]
All which we do support? Win7, Win8, Win8.1 and Win10?
I'm not too familiar with those either; just recently found out they existed and wanted to put it in here for consideration.

**Comment by ligfx** [comment]
@BhaaLseN what's the effect of specifying those/not specifying those? I don't really know anything about windows application manifests (only how to extract them and what @Orphis taught me yesterday!).

**Comment by BhaaLseN** [comment]
As I said, I'm not really familiar with them either...I was hoping you were :D

**Comment by Orphis** [comment]
We don't set any minimum required version at all on the binary on the MSVC side.
It would be interesting to do so, but maybe in another commit?

**Comment by ligfx** [comment]
@BhaaLseN let's leave that for another commit, once someone figures out what it actually does xD

**Pull request merged**
