### PR TITLE
Force Slow Depth on Suzumiya Haruhi no Heiretsu

### PR DESCRIPTION
**Pull request by RisingFog**
Fixes issue 9369: https://bugs.dolphin-emu.org/issues/9369

If we can find a real fix before 5.0 release, that should be made into a separate PR.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3674)

### CODE REVIEW

**Comment by JMC47** [comment]
-1; the whole point of removing slowdepth was to draw out bugs like this.

**Comment by aserna3** [comment]
+1: Which we can then fix with GameINIs until the underlying issue gets fixed. The point of GameINIs is to fix games after issues are known. Fixing fast depth is going to take a lot, unless we are fine with delaying 5.0 more.

**Comment by JMC47** [comment]
We're not going to set a bunch of invisible switches for a ton of games because fast-depth is broken in a few situations.  This is how we end up forgetting about it and then our depth will be bugged forever.  Either remove the slow-depth "removal" or fix the fucking issues.

**Comment by Armada651** [comment]
I think the best way to handle these situation is to first diagnose and document the issue before applying a workaround. Some issues can be fixed as soon as the problem is found, others like DKCR or Sonic Adventures are not easily fixed and can use a workaround for the time being.

I'm currently diagnosing this problem, and I will document the issue on the issue tracker. If I can't easily fix the problem, then I will merge this PR.

**Comment by Armada651** [comment]
I can confirm that this is the same issue as DKCR, it is fixed in PR #3587 but not without side-effects yet. I'll merge this PR for now and submit PR #3587 as a potential fix in the issue tracker.

**Pull request merged**
