### PR TITLE
[RFC] Add LuaJIT to externals.

### PR DESCRIPTION
**Pull request by phire**
There is a reason why I picked LuaJIT instead of plain Lua (or another scripting language, like python)

I'm planning to allow registering of hooks to call a lua function every time dolphin flushes the vertices (or potentially more often than that) to allow custom scripts to run when BPmem/XFmem/CPmem matches certain states, which requires a scripting language which generates fast code.

Also, other scripting languages are bloated.

TODO: CMakeFiles for building on *nix

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3251)

### CODE REVIEW

**Comment by degasus** [comment]
Do you think there is a way to not hard code such an API to use lua? I'd like to not know anything about using lua within dolphin itself and just register some functions for a generic scripting language. So we could support different binding on different plattforms easily.

**Comment by phire** [comment]
@degasus, yes. The function exported with "extern "C" __declspec(dllexport)" is a pure C function which LuaJIT calls directly with it's [FFI](http://luajit.org/ext_ffi.html) library. Unlike normal lua api functions (where you have to read arguments off the stack with lua_* functions and push your return argument back on the stack) LuaJIT can inline FFI calls directly into it's jitted code. LuaJIT can even pass in C function callbacks which C/C++ code can directly call later (though apparently it a little slow)

I'm hoping to export most of the extension API with that method, so anything can link to dolphin as long as it can call our exported C functions (or someone provides an adapter)

**Comment by degasus** [comment]
@phire I'm more talking about a way to register this functions. I guess you still need a way to query the list of all functions within lua. Hopefully, we'll be able to do the same with the type declarations....

**Comment by ds84182** [comment]
For CMake, minilua should be built in the host's architecture. Any reason why CMake can't invoke the original Makefile?

**Comment by phire** [comment]
It is technically possible to call the original makefile, but I'm not a big fan of the original Makefile. It's better than the .bat scripts used on windows but it still builds things in-tree.

Was easier just to re-write it in CMake.

**Comment by phire** [comment]
Ok, we now have a CMake build configuration that works for the android build.

Which was not easy, because CMake isn't exactly sane about cross compilation, especially when it comes to compiling tools on the host then running them (which luajit needs)

**Comment by phire** [comment]
Currently this has run into some issues with OSX and our lack of proper low-memory management there.

**Comment by RisingFog** [comment]
Any progress with this PR now that 5.0 has been released?

**Comment by delroth** [comment]
This PR hasn't been updated in more than a year, has many conflicts, etc. Closing it, feel free to reopen if you think it's still relevant and likely to get worked on.

**Pull request closed without merging**
