### PR TITLE
Update to fmt 8.1.1

### PR DESCRIPTION
**Pull request by Pokechu22**
Fixes [issue 12798](https://bugs.dolphin-emu.org/issues/12798).  Fmt 8.1.1 uses compile-time format string checking by default if `consteval` is supported (i.e. C++20 is in use), which is the case for MSVC (since we don't restrict the C++ version on MSVC for some reason, though we do on other compilers).  There are a large number of changes needed to fix compile errors for that.  Otherwise, the main source of errors is `enum class`es no longer being implicitly converted to `int`s; in most cases I've added a cast (but I created an `EnumFormatter` for WD's command enums because it seemed useful there).

Note that the last time I updated a library (#10188), the windows builds broke due to a bad build cache.  I don't think that applies here (as fmt doesn't actually have any cpp files; we built it as a header-only library), but it's something to look out for.

### CODE REVIEW

**Comment by Pokechu22** [comment]
I'm not sure what's going on with the debian builders failing to find `fmt::runtime`; maybe they're using an older system fmt instead of the updated local one in Externals?

**Comment by Scrumplex** [comment]
> maybe they're using an older system fmt instead of the updated local one in Externals?

Yep. If you look at line 40 (when expanding the log for shell_1) you can see this in the cmake output:
```
Using shared fmt 7.1.3
```

**Comment by BhaaLseN** [comment]
> [...] which is the case for MSVC (since we don't restrict the C++ version on MSVC for some reason, though we do on other compilers).

This was a longer discussion in various PRs (with the most documenting one being #8856 I guess) with the conclusion that we want at least one compiler to tell us about potential standard issues in advance; and MSVC just happened to fit the bill (IIRC because the earliest ones where we wanted to use C++14 or C++17 didn't have a formal switch for it, and we just said "use latest" instead)

**Comment by Pokechu22** [comment]
I've updated the minimum fmt version in CMakeLists.txt to 8.0, which has resulted in the debian builder using the fmt in Externals.

**Review by jordan-woyak — APPROVED** [review]
Changes look good.

**Pull request merged**
