### PR TITLE
Qt/WatchWidget: Don't update if not paused.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
This is a workaround for https://bugs.dolphin-emu.org/issues/13190.

There's definitely a better way to solve this but I'm really unsure what the proper way to deal with it is, so this should at least resolve the pseudo-infinite-loop in the meantime.

### CODE REVIEW

**Comment by JosJuice** [comment]
Is it fine to leave the table as it is when not paused, or should we clear it or something to make it clear to the user that the values are not up to date?

LGTM other than that.

**Comment by AdmiralCurtiss** [comment]
Probably better like this?

**Comment by JosJuice** [comment]
I just hope this won't make people think their watches have been deleted... I don't know, though. I'll leave the decision to someone who uses the debugging UI more than me.

**Comment by Pokechu22** [comment]
I don't think clearing the table is a good approach. It'd be better to gray out the values (perhaps using `setDisabled`) but leave the addresses and labels visible.

This also introduces a minor inconsistency: when the watch widget first appears, it has 0 rows, but after starting and then pausing a game, it gains 1 blank row (which is usable for creating new watches). Before, the 1 blank row was always visible (even when emulation hadn't started - though also you can use that blank row to create new watches when emulation hasn't started even though the menu options are disabled... it's fairly jank).

**Comment by AdmiralCurtiss** [comment]
Yes, this entire watch widget is super janky... feel free to fix it, but that wasn't my goal, I just wanted to stop Dolphin freezing and/or lagging when it's open.

**Comment by Pokechu22** [comment]
Now before the game starts, it looks like this:

image

which is _really_ jank looking. That can probably be solved by moving the `setHorizontalHeaderLabels` call into `CreateWidgets`, and using `clearContents()` instead of `clear()`. (The empty row could also be created in `CreateWidgets` by [duplicating this code](https://github.com/dolphin-emu/dolphin/blob/0461fae99e72dfcbd2d2bcb8088084ca90dc4ee2/Source/Core/DolphinQt/Debugger/WatchWidget.cpp#L214-L224) there.)

**Comment by AdmiralCurtiss** [comment]
There, yeah that's definitely better.

**Comment by AdmiralCurtiss** [comment]
> The watch table doesn't get cleared when stopping emulation.

Honestly it probably should actually remain saved across sessions (at least for the same game)! But yeah, that's probably a more significant change.

**Pull request merged**
