### PR TITLE
Remove Frameskip

### PR DESCRIPTION
**Pull request by Helios747**
Frameskip is really broken in Dolphin and graphics / JIT devs say fixing it would be a nightmare. So I'm removing it to protect the user. We don't even save the setting to disk anyways.

It's broken in that it's very inconsistent in what it even does to games. Sometimes it does nothing at all. Sometimes it just renders black frames in place of the frames it drops. Sometimes it entirely breaks the game. JMC says it doesn't often do what it's supposed to.

Can somebody who knows frame advance code look over this to make sure I didn't delete something important, whoever did the frame advance stuff named some functions and configmanager stuff "Frameskip" for some reason.

@degasus, please review the fifo stuff. I had no idea what I was doing.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4322)

### CODE REVIEW

**Comment by degasus** [comment]
The VideoCommon changes LGTM

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/DolphinWX/Frame.cpp, line 310 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4322#-KTYNVYPP5xSW_8zgTG6:-KTYNVYPP5xSW_8zgTG7:b-osym) ([raw file](https://github.com/dolphin-emu/dolphin/blob/4ba1100f3191c80e58f89c78d1e8965e126da8f3/Source/Core/DolphinWX/Frame.cpp#L310)):*
> ```cpp
> EVT_MENU_RANGE(IDM_SAVE_SLOT_1, IDM_SAVE_SLOT_10, CFrame::OnSaveState)
> EVT_MENU_RANGE(IDM_SELECT_SLOT_1, IDM_SELECT_SLOT_10, CFrame::OnSelectSlot)
> EVT_MENU_RANGE(IDM_FRAME_SKIP_0, IDM_FRAME_SKIP_9, CFrame::OnFrameSkip)
> ```

May you also drop the globals IDM_FRAME_SKIP_ ?

---

*[Source/Core/VideoCommon/Fifo.cpp, line 89 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4322#-KTYMpDwyXZdgV2beE8x:-KTYMpDwyXZdgV2beE8y:b-q2qq1z) ([raw file](https://github.com/dolphin-emu/dolphin/blob/4ba1100f3191c80e58f89c78d1e8965e126da8f3/Source/Core/VideoCommon/Fifo.cpp#L89)):*
> ```cpp
>   }
> 
>   p.Do(s_skip_current_frame);
> ```

Did you increase the savestate version?

---

*[Source/Core/VideoCommon/Fifo.h, line 47 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4322#-KTYMfse3cTddkWRvyiC:-KTYMfsfALLrnDAj-TL_:b-4qkc1p) ([raw file](https://github.com/dolphin-emu/dolphin/blob/4ba1100f3191c80e58f89c78d1e8965e126da8f3/Source/Core/VideoCommon/Fifo.h#L47)):*
> ```objc
> bool AtBreakpoint();
> void ResetVideoBuffer();
> void SetRendering(bool bEnabled);
> ```

Please also remove the header of SetRendering

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4322#-:-KTYO-90DVaz23Mrk1ib:bss60m7)*

**Comment by Helios747** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/DolphinWX/Frame.cpp, line 310 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4322#-KTYNVYPP5xSW_8zgTG6:-KT_C76fbvUuNqLqXGKY:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/4ba1100f3191c80e58f89c78d1e8965e126da8f3/Source/Core/DolphinWX/Frame.cpp#L310)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> May you also drop the globals IDM_FRAME_SKIP_ ?
</details>
Done.

---

*[Source/Core/VideoCommon/Fifo.cpp, line 89 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4322#-KTYMpDwyXZdgV2beE8x:-KT_C8NgWIbwv7fd4DBo:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/4ba1100f3191c80e58f89c78d1e8965e126da8f3/Source/Core/VideoCommon/Fifo.cpp#L89)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> Did you increase the savestate version?
</details>
Done.

---

*[Source/Core/VideoCommon/Fifo.h, line 47 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4322#-KTYMfse3cTddkWRvyiC:-KT_C96rOhcjtBgmeETr:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/4ba1100f3191c80e58f89c78d1e8965e126da8f3/Source/Core/VideoCommon/Fifo.h#L47)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> Please also remove the header of SetRendering
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4322)*

**Comment by degasus** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4322#-:-KT_o6Yi-w7KJEs5OqbE:bnfp4nl)*

**Comment by DPersonalized** [comment]
And just like the codes that increase frame-rate, it should be possible to make frame-rate reduction codes. I made an experimental one for Burnout 2, for instance. Should be far less annoying than frame-skip and more flexible.

**Pull request merged**
