### PR TITLE
Update to soundtouch 2.3.1

### PR DESCRIPTION
**Pull request by Mystro256**
Soundtouch is out of date, so this just updates the external lib code to the latest.

This is another attempt at updating this (see #8725), and is motivated by some CVE's present in the current bundled version (1.9.2). It's a good idea to keep this up to date to avoid security concerns.

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
I think you need to keep the existing `SoundTouch.vcxproj`.

**Comment by AdmiralCurtiss** [comment]
Also I think your config header didn't quite work as intended, the android builder is complaining about thrown exceptions.

**Comment by Mystro256** [comment]
> I think you need to keep the existing `SoundTouch.vcxproj`.

I don't have a Windows system, so someone will need to help here.

**Comment by AdmiralCurtiss** [comment]
-> #11706

**Pull request closed without merging**
