### PR TITLE
DVDInterface: Simplify calling ChangeDisc from CPU thread

### PR DESCRIPTION
**Pull request by JosJuice**
When Movie was calling ChangeDisc, it was moving execution to the host thread just to then make the host thread the CPU thread. We can simply run the code directly on the CPU thread instead.

This works as far as I could see during my testing, but I'm not completely sure about the correctness. Since PR #3794 was the last major edit to this, @EmptyChaos, do you want to comment?

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3980)

### CODE REVIEW

**Comment by magumagu** [comment]
This looks right in terms of synchronization.  (It isn't really right in the sense that the disc change doesn't happen at the right time if you record a movie without using frame advance, but that's an existing issue.)

**Comment by phire** [comment]
Yeah, this looks right

**Comment by EmptyChaos** [comment]
@JosJuice I believe this should be correct.

**Comment by Parlane** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3980)*

**Pull request merged**
