### PR TITLE
OSREPORT: Fix out-of-bounds string access.

### PR DESCRIPTION
**Pull request by magumagu**

### CODE REVIEW

**Comment by BhaaLseN** [comment]
```string[i-2]``` is still checked when ```string[i-1]``` equals ```l```; so technically the out-of-bounds access is still possible (altho a lot less likely).
Not sure how OSREPORTs usually use this, so we might aswell ignore that fact and keep the code as-is?

**Comment by magumagu** [comment]
No, the out-of-bounds access is not possible; the only way to reach this point with `i` equal to one is if the string starts with `%`.

**Comment by BhaaLseN** [comment]
Diff context fail, my bad :|

**Comment by ZephyrSurfer** [comment]
This fixes True Crime: New York City in Interpreter

**Pull request merged**
