### PR TITLE
Fix All wiitdb-ja

### PR DESCRIPTION
**Pull request by nassau-tk**
@JosJuice
 
Hello.
I'm finished my work that I would translate & fix on Japanese titles for all wiitdb-ja.txt.

・Wii
・Wii ware
・NGC
・VC/NES
・VC/SNES
・VC/N64
・VC/PCE
・VC/MD
・VC/SMS
・VC/MSX
・VC/Arcade

Please merge it.
Thank you.

### CODE REVIEW

**Review by JosJuice — APPROVED** [review]

**Comment by nassau-tk** [comment]
@JosJuice

Oops!!
My friends reported to my misstake.
I will remake the PR again.

**Comment by nassau-tk** [comment]
I'm fixed few my misstake.
Thank you.

**Comment by JosJuice** [comment]
Please squash the two commits into one.

**Comment by nassau-tk** [comment]
image

I can’ｔ choose squash merge.
How can I do it?

**Comment by JosJuice** [comment]
This page describes how to do it: https://www.freecodecamp.org/news/git-squash-commits/

Keep in mind that after squashing the commits, you'll have to force push your branch to GitHub. A regular push won't work.

**Comment by nassau-tk** [comment]
Oh... sorry.

I can't do it.
And, Re-make PR.
Thank you.

**Pull request closed without merging**
