### PR TITLE
[WIP] [Not for Merge] Vertex Ubershaders

### PR DESCRIPTION
**Pull request by phire**
This is a second PR for tracking the Vertex Ubershaders, so we can get fifoci runs without pixel ubershaders enabled.

This PR is more or less the same as #3163 but with ShaderGen for pixel shaders.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3185)

### CODE REVIEW

**Comment by mbc07** [comment]
I know it's not ready for public consumption but I would like to thank you anyway phire, Tatsunoko Vs Capcom stuttering is hugely improved, it still have a little stutter here and there with this PR but compared to master where every single action you do in the game would cause various shader compilation stuttering it's thousands of times better...

**Comment by JMC47** [comment]
Someone's reports about that game made it a testing candidate for the ubershaders.  If you were the one who reported the severe shader generation issues in the game, I thank you for bringing it to our attention.

**Comment by phire** [comment]
I hope you tested the other PR. This one currently has no ubershaders at all enabled.

**Comment by JMC47** [comment]
Yeah, a majority of the stuttering in TvC is actually pixel shaders.  The comment by @mbc07 points toward them using the other PR, as i have the same experience.

**Comment by mbc07** [comment]
I tested the main Ubershaders PR as well, it also improves TvC (despite some funny colors in some character's faces probably because it's no finished)...

**Comment by JMC47** [comment]
The funny characters on faces should be fixed.  I tried a few random characters and it was working.  The rest of the stuttering is vertex shaders being generates, so once it's done the game should NEVER stutter!

**Comment by Helios747** [comment]
Closed in favor of https://github.com/dolphin-emu/dolphin/pull/5702

**Pull request closed without merging**
