### PR TITLE
Fix Japanese NGC Titles.

### PR DESCRIPTION
**Pull request by nassau-tk**
I'm fix NGC Japanese titles on the gametdb.com and Push it.

### CODE REVIEW

**Comment by JosJuice** [comment]
If you want to update Dolphin's copy of the GameTDB title lists, please do it by running `Tools/update-wiitdb.sh` instead of doing it manually. This script is written to ensure that files for languages other than English only contain titles that differ from the English titles.

**Comment by nassau-tk** [comment]
Very sorry. Could you please tell me where I can find instructions on how to use this tool?

**Comment by JosJuice** [comment]
You run it from the terminal, like this: `./Tools/update-wiitdb.sh`

If you're not sure how to do that, just let me know and I can do it instead.

**Comment by nassau-tk** [comment]
I want learn the way.

I'm put on the Data/sys my fixed wiitdb-ja.txt(All inclued En/Ja/Ko).
And, I ran the script on my local.
image
But,It only created empty wiitdb-en.txt (0kb).

Please teach me!

**Comment by JosJuice** [comment]
That looks like you're doing it correctly.

I wonder if maybe `curl` isn't available? The script uses it for downloading the files. Try running `which curl` and see what the output is

**Comment by nassau-tk** [comment]
Is this?
image

**Comment by JosJuice** [comment]
Yes. I have the same output, and it works for me, so `curl` probably isn't the problem... But then what could the problem be?

**Comment by nassau-tk** [comment]
um....
Sorry, I don't have any idea.
Cuz, I don't have a knowledge.　(^o^ ;)ゞ
But, I understand a thing that It was cause on my specification.
So, I will check my specification and about curl.
And, If solve the my isseu then remake a PR.
I'm grad for your kindness!!

**Comment by nassau-tk** [comment]
@JosJuice 

Yes, I got solved my problem.
※I think it's quite forced.※

I tested curl command like a below.
$ curl https://www.gametdb.com/
image

And it's fail and appeared error code (35).
I'm searched by the Google "curl error (35)" .
I opened the this blog.
https://kntmr.hatenablog.com/entry/2020/03/19/183000
He say "Unable to check SSL certificate revocation with curl on Windows".
And he says to force it by using the -k option.
So, I opened update-wiitdb.sh and added it like below.
image

And, I start update-wiitdb.sh.
image

I got wiitdb files corectlly!!

It may not be the correct method, but I was able to obtain the desired file.
We will report it.

**Pull request closed without merging**
