### PR TITLE
GameList: Adjust width of size column

### PR DESCRIPTION
**Pull request by Craftyawesome**
This increases the width of the size column if needed to fit the file size.

1080p 125%
Master
image

PR
image

### CODE REVIEW

**Comment by Craftyawesome** [comment]
Huh, this is actually a scaling problem. On my 1080p screen on windows it happens at 125% scale but not 100%. So this is probably only useful as a workaround or if we don't want 4 non-decimal digits regardless.

**Review by MayImilae — COMMENTED** [review]
So this is kind of a weird solution to this problem? Like, the width of the size column is fixed, but [it is set by us](https://github.com/dolphin-emu/dolphin/blob/d62838a2f41f7ece5e804bbf86ec167255077212/Source/Core/DolphinQt/GameList/GameList.cpp#L215). I think a better solution would be to just make the column a little wider. 

EDIT: Even better, rather than setting the Size column to a slightly larger fixed size, try ::ResizeToContents instead of ::Fixed. Theoretically that will just handle this case optimally forever. https://doc.qt.io/qt-6/qheaderview.html#ResizeMode-enum

-----

Also trying out this PR, it wasn't able to stop all ...s from appearing. It just reduced their quantity a bit.

Screen Shot 2023-03-28 at 02 51 14

**Comment by Craftyawesome** [comment]
When I initially wrote this I assumed that gui was expecting less characters. I didn't realize it was dependent on scaling or that it could happen on sizes outside of 1000-1024

::ResizeToContents seems to have some odd problems. It works if you resize one of the other columns, but if you just started dolphin or do something like maximize the window it likes to be cut off/not reach the edge. It also visibly shifts a little while resizing a different column. I don't think I'm familiar enough with Qt to fix this.

I think I got something else that actually works though.

**Comment by MayImilae** [comment]
Gave it and there is not a single ... in my library size column. 

Interestingly, it's quite a bit larger than I expected - a full 200 pixels on my hidpi laptop here (including padding). And it maintains that even if there is a lot of games or only a couple of games in my library. It's always 200 pixels wide. I'm guessing your code is just making it take the maximum possible size and just setting it to that permanently. Which I guess does the trick? It's a little big though. Current master is 168 pixels wide (including padding).

It's fine though. If you're happy with it I think this is good to merge.

**Comment by MayImilae** [comment]
> I think it's a bit odd that certain columns are not resizable

It's set up so that only the title expands when increasing the size of the window. Finer details on how that works are Qt things.

**Comment by Craftyawesome** [comment]
Hooked it up to resize after refresh. But apparently adding your first path is not a refresh? Couldn't find an easy way to fix this, so I set a hard minimum of the old value.

**Comment by Craftyawesome** [comment]
> it's quite a bit larger than I expected

There seems to be some sort of separate scaling problem with Dolphin or Qt (or Windows?). On 1080p 125% this pr gets just barely gets wide enough to fit (edited initial comment). But for 4k 150% master and this pr act the same and have a decent bit of space to spare.

image

I would think hidpi scaling would increase both the width and the font size in a way this shouldn't happen?

**Comment by Craftyawesome** [comment]
Changes since this PR was made (likely QT6 or changes for it) have seemingly fixed the text scaling differently than the column width. And master already has a wide enough column to handle seemingly any reasonable situation, so I'm closing this.

**Pull request closed without merging**
