### PR TITLE
Fix typo in VideoInterface code

### PR DESCRIPTION
**Pull request by Sintendo**
Yeah.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3663)

### CODE REVIEW

**Comment by BhaaLseN** [comment]
lol.

**Comment by aserna3** [comment]
Sorry this PR dropped my FPS in Melee by 40 FPS. Please fix this.

**Comment by bb010g** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3663)*

**Comment by lioncash** [comment]
Commit message should indicate where the typo was fixed (e.g. `VideoInterface: Fix typo` or something`)

**Comment by phire** [comment]
@dolphin-emu-bot rebuild

But... the spellchecker said it was correct.

**Pull request merged**
