### PR TITLE
DolphinQt: Fix whitelisting USB devices

### PR DESCRIPTION
**Pull request by JosJuice**
Revert of https://github.com/dolphin-emu/dolphin/pull/8233#discussion_r306223322

### CODE REVIEW

**Comment by Hacsev** [comment]
@JosJuice @stenzek @ismail @arthurc @lpereira 
On the recent version of Dolphin on Windows, I cannot get Rock Band 3 Wireless USB dongles to appear on the Whitelist menu. I replaced their drivers to libusbK and WinUSB and it did not work. Can anyone verify this and let us know?

**Comment by JosJuice** [comment]
Please ask on the forums instead: https://forums.dolphin-emu.org/

**Comment by Hacsev** [comment]
@JosJuice 
Already did a week ago. No response. That's why I am asking here.

**Comment by Hacsev** [comment]
@JMC47 
I haven't heard from you yet in the forums and I see you are actively developing Dolphin so I am tagging you here, since I can't send PMs on the Forums. I know that these things take time to fix, but I just want the developers to acknowledge and verify this issue.

**Comment by JosJuice** [comment]
Please stop tagging people about this. This kind of support is not what we use this GitHub repo for, so if you aren't getting any replies on the forums, I'm afraid I don't think you're going to get any replies here either.

**Comment by Hacsev** [comment]
Alright, I understand and this will be my last comment here. The fact that I got you to respond here and not through the forums proves my point though. I am just trying to make the emulator better by notifying you of this issue (which as you can tell is very dear to me as I almost exclusively use Dolphin for Rock Band). As far as I am aware there is no Discord server for Dolphin, that is why I resorted to commenting here, which I understand might be considered rude, but it was the only way of getting your attention.

**Pull request merged**
