### PR TITLE
Texcache cleanup 2

### PR DESCRIPTION
**Pull request by degasus**
This PR tries to pick some patches of #384 which are only cleanup. So this PR should have no impact on neither performance nor compatibility.

### CODE REVIEW

**Comment by BigheadSMZ** [comment]
I gave this a pretty thorough testing with 6 different texture packs, and everything seems fine except Xenoblade. When loading a save, or just trying to get to the "main game" in general, Dolphin crashes at the loading screen. This crash only happens when custom textures are enabled. If trying to enable custom textures while in-game, Dolphin will crash. This is not happening with the latest master. Not sure why other games work fine, maybe it's the million paletted textures? http://i.imgur.com/gs7kAhC.jpg

**Comment by degasus** [comment]
@BigheadSMZ D3D, OGL or both?

**Comment by degasus** [comment]
Updated with a better texlevel check and some sensibly checks for the ogl backend.

**Comment by BigheadSMZ** [comment]
Oops forgot to test OpenGL, that seems to work. D3D is crashing.

**Comment by degasus** [comment]
Still with my new commits?

**Comment by BigheadSMZ** [comment]
Just tried it out, works perfect in both D3D and OGL!

**Comment by Sonicadvance1** [comment]
LGTM. Just need some a bit more testing?

**Comment by JMC47** [comment]
I did test this out as per degasus's demand.  I can do more if given some direction though.

**Comment by BigheadSMZ** [comment]
I've been using this build for the past 2 days for all my dumping and loading needs in the off chance I'd find a bug/crash. As far as dumping and loading custom textures goes, it seems to work fine.

**Comment by degasus** [comment]
@BigheadSMZ We have discussed on IRC how we could fix the tlut issue in a better way: At the moment we hash all 16k texels all the times. But we could generate the min/max and only hash the used range. I guess this would remove lots of the double paletted texture hashes, it it will change /all/ hashes of paletted textures in an incompatible way. And it's not that easy to write a converter for such a change, so what do you think?

**Comment by BigheadSMZ** [comment]
So if I'm understanding correctly, all other textures could be preserved, and only paletted textures would have to be redumped? If losing the hashes/dumps of paletted textures was the most of my worries then please, fix away!

Honestly, I would jump on any wagon that fixes the duplicates even if it meant redumping/renaming everything from scratch (been prepared for months anyway), anything is better than this: http://i.imgur.com/YaDUUvL.jpg So I might be the wrong person to ask :P, others might not be so willing to rework their packs if all textures could not be converted, even though this being fixed would be best in the end.

**Comment by sateliter** [comment]
JustDance4 better works on 4.0-4881

**Comment by JosJuice** [comment]
@sateliter If it's a problem, bisect to the version that introduced the problem and make a proper issue report on Google Code.

**Pull request merged**
