### PR TITLE
D3D12: Multiple fixes (texture cache, fences, MSAA, CPU EFB access)

### PR DESCRIPTION
**Pull request by stenzek**
Bunch of fixes for D3D12:
 - Fix black textures appearing periodically
 - Fix EFB copies being corrupt after restart
 - Random crashes should be significantly reduced, if not occurring at all
 - Bunch of debug runtime errors fixed (nvidia still throws random errors about invalid offsets, but doesn't occur on other vendors? debug layer bug?)
 - Nonblocking CPU access to EFB when the contents hasn't been modified (similar to the D3D11 PR, but in theory, slightly more efficient. CPU EFB access was broken prior to the PR)
 - Fixes for MSAA
 - Some general code cleanup
 - Fixed texture dumping (also implemented for lods != 0)

Issue references:
https://bugs.dolphin-emu.org/issues/9362
https://bugs.dolphin-emu.org/issues/9352
https://bugs.dolphin-emu.org/issues/9346
https://bugs.dolphin-emu.org/issues/9347
https://bugs.dolphin-emu.org/issues/9350
https://bugs.dolphin-emu.org/issues/9344
https://bugs.dolphin-emu.org/issues/9348

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3647)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/VideoBackends/D3D12/D3DCommandListManager.cpp, line 192 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647#-KAf-9M7YZAZgxTC7Qjt:-KAf-9M7YZAZgxTC7Qju:1697003597) ([raw file](https://github.com/dolphin-emu/dolphin/blob/cbac5f64eb58e0fcfa5e2fc8529b8a8e3f0d2627/Source/Core/VideoBackends/D3D12/D3DCommandListManager.cpp#L192)):*
Should be its own function. `ResetCommandAllocators`

---

*[Source/Core/VideoBackends/D3D12/D3DCommandListManager.cpp, line 324 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647#-KAf-TYPs6tpL1sRrWcz:-KAf-TYPs6tpL1sRrWd-:-696088544) ([raw file](https://github.com/dolphin-emu/dolphin/blob/cbac5f64eb58e0fcfa5e2fc8529b8a8e3f0d2627/Source/Core/VideoBackends/D3D12/D3DCommandListManager.cpp#L324)):*
```cpp
if (fence->GetCompletedValue() >= fence_value)
    return;
```

---

*[Source/Core/VideoBackends/D3D12/D3DStreamBuffer.cpp, line 316 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647#-KAezlvvRELwwGA9HLL4:-KAezlvwxZv2lSxW-Dt3:1142580158) ([raw file](https://github.com/dolphin-emu/dolphin/blob/cbac5f64eb58e0fcfa5e2fc8529b8a8e3f0d2627/Source/Core/VideoBackends/D3D12/D3DStreamBuffer.cpp#L316)):*
This should be its own function, `HasFenceOffsetChanged` or some other appropriate name. It's not directly involved with queueing the fence.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647)*

**Comment by hdcmeta** [comment]
First two commits are very safe, good fixes.

Third commit is obviously more complex, but from code inspection looks good. Nice finding more places to (safely) free up resources/reset allocations. Small bit of feedback on some of the naming. Going to run it a bit just to give it some extra testing.

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[Source/Core/VideoBackends/D3D12/D3DCommandListManager.cpp, line 156 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647#-KAh-mU9oOYIo8HgCL9O:-KAh-mU9oOYIo8HgCL9P:-1543007804) ([raw file](https://github.com/dolphin-emu/dolphin/blob/cbac5f64eb58e0fcfa5e2fc8529b8a8e3f0d2627/Source/Core/VideoBackends/D3D12/D3DCommandListManager.cpp#L156)):*
While we're here we might as well make this variable follow style guidelines.. slipped by earlier

---

*[Source/Core/VideoBackends/D3D12/D3DCommandListManager.cpp, line 167 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647#-KAh47dKCFleuyrJKQ33:-KAh-v4btc8OL4GC7S5y:-1497407192) ([raw file](https://github.com/dolphin-emu/dolphin/blob/cbac5f64eb58e0fcfa5e2fc8529b8a8e3f0d2627/Source/Core/VideoBackends/D3D12/D3DCommandListManager.cpp#L167)):*
Consider "this may mean switching command allocator lists", the first time I read this as switching command lists

---

*[Source/Core/VideoBackends/D3D12/D3DCommandListManager.cpp, line 248 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647#-KAh-Z1q6DLYAPlaSuGB:-KAh-Z1q6DLYAPlaSuGC:-1622944643) ([raw file](https://github.com/dolphin-emu/dolphin/blob/cbac5f64eb58e0fcfa5e2fc8529b8a8e3f0d2627/Source/Core/VideoBackends/D3D12/D3DCommandListManager.cpp#L248)):*
Consider naming MoveToNextCommandAllocator, or something of the sort. There is only one ID3D12GraphicsCommandList object in the app, it is just cycled between different ID3D12CommandAllocators..

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647#-:-KAh4Ukn2fT8yzdnopu8:-1509838003)*

**Comment by JMC47** [comment]
Fixes my issues with D3D12

**Comment by lioncash** [comment]
Review status: 0 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[Source/Core/VideoBackends/D3D12/D3DStreamBuffer.h, line 43 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647#-KAjXIiPbYddoNSWr31Q:-KAjXIiPbYddoNSWr31R:-1889571407) ([raw file](https://github.com/dolphin-emu/dolphin/blob/60f7f7aa89c42036556e45a322e3db6e577b6b6a/Source/Core/VideoBackends/D3D12/D3DStreamBuffer.h#L43)):*
```cpp
bool HasBufferOffsetChangedSinceLastFence() const;
```

---

*[Source/Core/VideoBackends/D3D12/D3DUtil.h, line 53 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647#-KAjXSMbZsLmcE6YGaQT:-KAjXSMbZsLmcE6YGaQU:-1809197968) ([raw file](https://github.com/dolphin-emu/dolphin/blob/60f7f7aa89c42036556e45a322e3db6e577b6b6a/Source/Core/VideoBackends/D3D12/D3DUtil.h#L53)):*
`= nullptr` isn't necessary. unique_ptr will automatically initialize to nullptr.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647)*

**Comment by lioncash** [comment]
Review status: 0 of 17 files reviewed at latest revision, 9 unresolved discussions.

---

*[Source/Core/VideoBackends/D3D12/FramebufferManager.cpp, line 214 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647#-KB28SaCmz1zmAYU7mat:-KB28SaCmz1zmAYU7mau:-311265725) ([raw file](https://github.com/dolphin-emu/dolphin/blob/abc2bc689d7034edb89ed36ffbadb5d7b9e93d0a/Source/Core/VideoBackends/D3D12/FramebufferManager.cpp#L214)):*
Should probably convert the `* 4` into `* sizeof(u32)` to get rid of a magic constant (variable should also be changed to size_t`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647)*

**Comment by lioncash** [comment]
Review status: 0 of 17 files reviewed at latest revision, 9 unresolved discussions.

---

*[Source/Core/VideoBackends/D3D12/FramebufferManager.cpp, line 214 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647#-KB28SaCmz1zmAYU7mat:-KB2ljZp-jhnS8nPWUBW:-909164217) ([raw file](https://github.com/dolphin-emu/dolphin/blob/abc2bc689d7034edb89ed36ffbadb5d7b9e93d0a/Source/Core/VideoBackends/D3D12/FramebufferManager.cpp#L214)):*
Still missing the variable type change to `size_t`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647)*

**Comment by JMC47** [comment]
Can we get this reviewed please?  Would make a nice addition to the progress report.

**Comment by delroth** [comment]
Reviewed 1 of 5 files at r2, 3 of 8 files at r3, 1 of 2 files at r4, 4 of 11 files at r5, 1 of 5 files at r6, 10 of 10 files at r7.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3647)*

**Pull request merged**
