### PR TITLE
Null: Initial release of null video backend

### PR DESCRIPTION
**Pull request by degasus**
Through there could be a smaller Null backend, this is the smallest way to trigger all VideoCommon stuff. So this backend is designed to profile everything but the video backend.

There are still many ways to shrink it by merging stuff into VideoCommon, but this progress has stalled in the last month. So I'm opening this PR now.

Tested:
- Linux nogui + wx + qt2. Emulated input works on all of them.

Untested:
- Windows + OSX.

Missing: Visual Studio project file....

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3813)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 17 files reviewed at latest revision, 41 unresolved discussions, some commit checks failed.

---

*[Source/Core/VideoBackends/Null/FramebufferManager.h, line 9 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxS3OFUSMuE-Dpfxwz:-KGxS3OFUSMuE-Dpfxx-:-1051843972) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/FramebufferManager.h#L9)):*
`u32 xfb_addr, u32 fb_width, u32 fb_height`

---

*[Source/Core/VideoBackends/Null/FramebufferManager.h, line 10 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxS1y-3S4TbCdmRbeO:-KGxS1y0rEUANK7sKI1L:196584788) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/FramebufferManager.h#L10)):*
`gamma`

---

*[Source/Core/VideoBackends/Null/FramebufferManager.h, line 17 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxSBRZKijPX4E2IvCj:-KGxSBRZKijPX4E2IvCk:1048447438) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/FramebufferManager.h#L17)):*
`u32 xfb_addr, u32 fb_stride, u32 fb_height, const EFBRectangle& source_rc, float gamma = 1.0f`

---

*[Source/Core/VideoBackends/Null/main.cpp, line 7 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxSO7vAI4TZpt0VRk2:-KGxSO8028nAfuVzKKq_:-1050673567) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/main.cpp#L7)):*
Single line comments.

---

*[Source/Core/VideoBackends/Null/main.cpp, line 57 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxSU1Fidga2RukaXSU:-KGxSU1GU0sPbX4Hm96x:1495996369) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/main.cpp#L57)):*
`void* parent`

---

*[Source/Core/VideoBackends/Null/main.cpp, line 63 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxSX4AJw9P9AoCFWgq:-KGxSX4FPgD25lzKaN6x:1517073064) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/main.cpp#L63)):*
void* window_handle

---

*[Source/Core/VideoBackends/Null/main.cpp, line 115 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxUvREEGQh1xhxyeRc:-KGxUvRFjX5DVJ7Q8BJn:-539529565) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/main.cpp#L115)):*
Brace on new line

---

*[Source/Core/VideoBackends/Null/main.h, line 7 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxUcZ_3UC6nqzGS9aL:-KGxUcZaTTZTEqEik-c7:500169923) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/main.h#L7)):*
Unnecessary header?

---

*[Source/Core/VideoBackends/Null/PerfQuery.h, line 20 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxUqNAwoszpgXuzsyv:-KGxUqNAwoszpgXuzsyw:-581649022) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/PerfQuery.h#L20)):*
semicolon after the brace isn't necessary.

---

*[Source/Core/VideoBackends/Null/PerfQuery.h, line 22 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxUm8E66ThyzNNXpOS:-KGxUm8F90oR4O9MbglR:858709525) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/PerfQuery.h#L22)):*
missing spaces, and the semicolon after the brace isn't necessary.

---

*[Source/Core/VideoBackends/Null/Render.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxScGacSjxHPOg2F5L:-KGxScGbVYiFXnQOwcKj:-325274780) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/Render.cpp#L46)):*
Just a suggestion:

Unused parameters can just have their name not specified in the implementation (the names can stay in the header though)

e.g.

The header can be

```cpp
void SwapImpl(u32 xfb_addr, u32 fb_width, u32 fb_stride, u32 fb_height, const EFBRectangle& rc, float gamma = 1.0f)
```

but the implementation can be

```cpp
void Renderer::SwapImpl(u32, u32, u32, u32, const EFBRectangle&, float)
{
    UpdateActiveConfig();
}
```

---

*[Source/Core/VideoBackends/Null/Render.h, line 23 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxUzaT-_kemgqcK5_M:-KGxUzaT-_kemgqcK5_N:-257025630) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/Render.h#L23)):*
Semicolon after the brace isn't necessary.

---

*[Source/Core/VideoBackends/Null/Render.h, line 25 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxV3tNnIpr_-zvY1Js:-KGxV3tNnIpr_-zvY1Jt:-257025630) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/Render.h#L25)):*
Semicolon after the brace isn't necessary.

---

*[Source/Core/VideoBackends/Null/Render.h, line 26 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxV97vooVb7GHgXI8p:-KGxV97vooVb7GHgXI8q:-257025630) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/Render.h#L26)):*
Semicolon after the brace isn't necessary.

---

*[Source/Core/VideoBackends/Null/Render.h, line 28 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxV7bAHG87mLfd7STy:-KGxV7bAHG87mLfd7STz:-257025630) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/Render.h#L28)):*
Semicolon after the brace isn't necessary.

---

*[Source/Core/VideoBackends/Null/Render.h, line 32 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxU9I2f1vGE0K1qLJb:-KGxU9I4B_2iNttUDpei:-451524817) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/Render.h#L32)):*
`u32 xfb_addr, u32 fb_width, u32 fb_stride, u32 fb_height, const EFBRectangle& rc, float gamma`

---

*[Source/Core/VideoBackends/Null/Render.h, line 38 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxTPG2Xf17UsmWXmUm:-KGxTPG3IjlVE7K9Fj6f:-1124599898) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/Render.h#L38)):*
ampersands against te types

---

*[Source/Core/VideoBackends/Null/ShaderCache.h, line 26 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxTcSp_T0-t6NK-th9:-KGxTcSvdJBoniIgQ9Gt:-1785805085) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/ShaderCache.h#L26)):*
dst_alpha_mode

---

*[Source/Core/VideoBackends/Null/ShaderCache.h, line 29 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxTfCp7qh_aPJY8Jz4:-KGxTfCuDqpGHjyFW39A:-1785805085) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/ShaderCache.h#L29)):*
dst_alpha_mode

---

*[Source/Core/VideoBackends/Null/ShaderCache.h, line 30 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxTh9o-Va0isM_U4p8:-KGxTh9o-Va0isM_U4p9:-1785805085) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/ShaderCache.h#L30)):*
dst_alpha_mode

---

*[Source/Core/VideoBackends/Null/ShaderCache.h, line 33 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxRMoRtGm66MuZf9Zp:-KGxRMoRtGm66MuZf9Zq:-1322173385) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/ShaderCache.h#L33)):*
Just write the type directly? I mean, this is basically having a thing inside ShaderCache called ShaderCache, but with a shorter name.

---

*[Source/Core/VideoBackends/Null/ShaderCache.h, line 38 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxRD9vzJ1X236zliLb:-KGxRD9vzJ1X236zliLc:-1614876196) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/ShaderCache.h#L38)):*
```cpp
SCache m_shaders
const std:string* m_last_entry = nullptr;
Uid m_last_uid;
UidChecker<Uid, ShaderCode> m_uid_checker;
```

---

*[Source/Core/VideoBackends/Null/ShaderCache.h, line 48 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxRAMxLyt8loWct9AO:-KGxRAMxLyt8loWct9AP:-1785805085) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/ShaderCache.h#L48)):*
dst_alpha_mode

---

*[Source/Core/VideoBackends/Null/ShaderCache.h, line 52 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxR9--qwd6c2zs_kBc:-KGxR9--qwd6c2zs_kBd:-1785805085) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/ShaderCache.h#L52)):*
dst_alpha_mode

---

*[Source/Core/VideoBackends/Null/ShaderCache.h, line 65 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxR6JQEdDOLSie8XgP:-KGxR6JQEdDOLSie8XgQ:-1785805085) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/ShaderCache.h#L65)):*
dst_alpha_mode

---

*[Source/Core/VideoBackends/Null/ShaderCache.h, line 69 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxR4blQK2Q9b6SXqMt:-KGxR4bmAl6zQj0ZwiNv:-1785805085) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/ShaderCache.h#L69)):*
dst_alpha_mode

---

*[Source/Core/VideoBackends/Null/ShaderCache.h, line 82 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxR2lI9Kyqo4eHh-jn:-KGxR2lI9Kyqo4eHh-jo:-1785805085) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/ShaderCache.h#L82)):*
dst_alpha_mode

---

*[Source/Core/VideoBackends/Null/ShaderCache.h, line 86 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxR1CYJV0lS3T8JR7t:-KGxR1CZTm1ioHOdJ61x:-1785805085) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/ShaderCache.h#L86)):*
dst_alpha_mode

---

*[Source/Core/VideoBackends/Null/TextureCache.h, line 18 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxVF3aILvyPvuVQ8H1:-KGxVF3bmxt52ra-cjvW:-257025630) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/TextureCache.h#L18)):*
Semicolon after the brace isn't necessary.

---

*[Source/Core/VideoBackends/Null/TextureCache.h, line 19 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxVG0X8xAIa4Ed_Ays:-KGxVG0X8xAIa4Ed_Ayt:-257025630) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/TextureCache.h#L19)):*
Semicolon after the brace isn't necessary.

---

*[Source/Core/VideoBackends/Null/TextureCache.h, line 20 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxVHDDAXNkZdOSBLlD:-KGxVHDDAXNkZdOSBLlE:-257025630) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/TextureCache.h#L20)):*
Semicolon after the brace isn't necessary.

---

*[Source/Core/VideoBackends/Null/TextureCache.h, line 23 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxTlzPOS2oJ92p5_kv:-KGxTlzV5c4vS89LSKWS:-1862228726) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/TextureCache.h#L23)):*
src_format, src_rect, is_intensity, scale_by_half 

---

*[Source/Core/VideoBackends/Null/TextureCache.h, line 24 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxVJVJCbW-CwySj5nJ:-KGxVJVJCbW-CwySj5nK:-257025630) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/TextureCache.h#L24)):*
Semicolon after the brace isn't necessary.

---

*[Source/Core/VideoBackends/Null/TextureCache.h, line 35 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxTzLHmKAG5HLOpmYS:-KGxTzLHmKAG5HLOpmYT:1779586408) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/TextureCache.h#L35)):*
src_format, src_rect, scale_by_half

---

*[Source/Core/VideoBackends/Null/TextureCache.h, line 36 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxQuF-sxRMvqm_DEhy:-KGxQuF0t7cqzoHYl7_n:-22542302) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/TextureCache.h#L36)):*
Asterisk against type

---

*[Source/Core/VideoBackends/Null/TextureCache.h, line 41 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxQqRDR1eNDiFIXH7d:-KGxQqRDR1eNDiFIXH7e:-859360475) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/TextureCache.h#L41)):*
ampersands against the type

---

*[Source/Core/VideoBackends/Null/VertexManager.cpp, line 28 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxQNJdGl5yX1Iyh0SQ:-KGxQNJdGl5yX1Iyh0SR:-1224353511) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/VertexManager.cpp#L28)):*
```cpp
VertexManager:VertexManager()
    : m_local_v_buffer(MAXVBUFFERSIZE)
    , m_local_i_buffer(MAXIBUFFERSIZE)
{
}
```

---

*[Source/Core/VideoBackends/Null/VertexManager.cpp, line 45 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxVPs0leA2H6WTety3:-KGxVPs1bp2GUT7M3GU_:-1411043129) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/VertexManager.cpp#L45)):*
use_dst_alpha

---

*[Source/Core/VideoBackends/Null/VertexManager.h, line 24 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxQFgEJsHq29z9_XFa:-KGxQFgFiFU9G7mXnuaA:1093366144) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/VertexManager.h#L24)):*
```cpp
use_dst_alpha
```

---

*[Source/Core/VideoBackends/Null/VertexManager.h, line 25 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxQ7tDu3Ct6-I7c59t:-KGxQ7tE2kCw-TVt1iaX:-1106364437) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/VertexManager.h#L25)):*
```cpp
m_local_v_buffer
m_local_i_buffer
```

---

*[Source/Core/VideoBackends/Null/VideoBackend.h, line 14 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxQlfqKf4iVxso1FBe:-KGxQlfrHGyjii1oYpd8:-1849247678) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/VideoBackend.h#L14)):*
asterisk against type

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813)*

**Comment by lioncash** [comment]
Review status: 0 of 17 files reviewed at latest revision, 43 unresolved discussions, some commit checks failed.

---

*[Source/Core/VideoBackends/Null/ShaderCache.cpp, line 54 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxWSFCMnmbO7l9At8x:-KGxWSFD2YAipzTnhagE:-196949409) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/ShaderCache.cpp#L54)):*
`auto iter = m_shaders.find(uid)`

---

*[Source/Core/VideoBackends/Null/ShaderCache.cpp, line 66 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KGxWZ8Hg8BAX6fJycv7:-KGxWZ8Ik8xwkmFkhsh_:-1493128478) ([raw file](https://github.com/dolphin-emu/dolphin/blob/91a434438659d8df4bcb77f358bc4cda87fffba8/Source/Core/VideoBackends/Null/ShaderCache.cpp#L66)):*
```cpp
m_shaders.emplace(uid, code.GetBuffer())
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813)*

**Comment by degasus** [comment]
JMC47> I WON A MATCH IN MELEE

Sounds like windows is working now, dropping WIP. Hopefully this will be the first PR after 5.0, so we can use it for performance testing on the next release ;)

**Comment by delroth** [comment]
Review status: 0 of 20 files reviewed at latest revision, 50 unresolved discussions.

---

*[Source/Core/VideoBackends/Null/FramebufferManager.h, line 9 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KL5GYaC8JYpGiD_mTeG:-KL5GYaC8JYpGiD_mTeH:1859467970) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3e3151b736418d04ab8ade0f07278f9c3afa075f/Source/Core/VideoBackends/Null/FramebufferManager.h#L9)):*
> ```objc
> class XFBSource : public XFBSourceBase
> {
>   void DecodeToTexture(u32 xfb_addr, u32 fb_width, u32 fb_height) override {}
> ```

Please explicitly indicate methods visibility (public/protected/private).

---

*[Source/Core/VideoBackends/Null/FramebufferManager.h, line 14 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KL5GbYOexalvS5evTCS:-KL5GbYOexalvS5evTCT:1638826728) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3e3151b736418d04ab8ade0f07278f9c3afa075f/Source/Core/VideoBackends/Null/FramebufferManager.h#L14)):*
> ```objc
> 
> class FramebufferManager : public FramebufferManagerBase
> {
> ```

Same here re: visibility.

---

*[Source/Core/VideoBackends/Null/FramebufferManager.h, line 21 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KL5Gdijb8QBIeuEoPgj:-KL5Gdijb8QBIeuEoPgk:1836647839) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3e3151b736418d04ab8ade0f07278f9c3afa075f/Source/Core/VideoBackends/Null/FramebufferManager.h#L21)):*
> ```objc
>     return std::make_unique<XFBSource>();
>   }
>   void GetTargetSize(unsigned int* width, unsigned int* height) override{};
> ```

No ; after a method implementation.

---

*[Source/Core/VideoBackends/Null/NullBackend.cpp, line 49 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KL5GnX80s8T1AQNdTzo:-KL5GnX80s8T1AQNdTzp:-1900988131) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3e3151b736418d04ab8ade0f07278f9c3afa075f/Source/Core/VideoBackends/Null/NullBackend.cpp#L49)):*
> ```cpp
>   g_Config.backend_info.bSupportsClipControl = true;
> 
>   // aamodes
> ```

Comment on what the "1" means.

---

*[Source/Core/VideoBackends/Null/PerfQuery.h, line 15 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KL5Gz85DJfC99_1TeIP:-KL5Gz85DJfC99_1TeIQ:-120744834) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3e3151b736418d04ab8ade0f07278f9c3afa075f/Source/Core/VideoBackends/Null/PerfQuery.h#L15)):*
> ```objc
> public:
>   PerfQuery() {}
>   ~PerfQuery() {}
> ```

That's not override?  It really should be virtual in the base class.

---

*[Source/Core/VideoBackends/Null/Render.cpp, line 28 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KL5H8frjuAgESzFViKO:-KL5H8frjuAgESzFViKP:-23984573) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3e3151b736418d04ab8ade0f07278f9c3afa075f/Source/Core/VideoBackends/Null/Render.cpp#L28)):*
> ```cpp
> void Renderer::RenderText(const std::string& text, int left, int top, u32 color)
> {
>   printf("RenderText: %s\n", text.c_str());
> ```

Use our logging framework.

---

*[Source/Core/VideoBackends/Null/ShaderCache.cpp, line 37 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KL5HSHj9DYRxeAErN7L:-KL5HSHj9DYRxeAErN7M:-1940957201) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3e3151b736418d04ab8ade0f07278f9c3afa075f/Source/Core/VideoBackends/Null/ShaderCache.cpp#L37)):*
> ```cpp
> bool ShaderCache<Uid>::SetShader(DSTALPHA_MODE dst_alpha_mode, u32 primitive_type)
> {
>   Uid uid = GetUid(dst_alpha_mode, primitive_type, API_OPENGL);
> ```

Why is all this being emulated? We should be able to do without it -- in fact we're never even running these shaders.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813)*

**Comment by degasus** [comment]
Review status: 0 of 20 files reviewed at latest revision, 50 unresolved discussions.

---

*[Source/Core/VideoBackends/Null/ShaderCache.cpp, line 37 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KL5HSHj9DYRxeAErN7L:-KL8GPV_ND_pofFkGLik:1724068974) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3e3151b736418d04ab8ade0f07278f9c3afa075f/Source/Core/VideoBackends/Null/ShaderCache.cpp#L37)):*
<details><summary><i>Previously, delroth (Pierre Bourdon) wrote…</i></summary>
> Why is all this being emulated? We should be able to do without it -- in fact we're never even running these shaders.
</details>
I want to hit as many videocommon parts as possible. Indeed, this is not required for a null backend, but it's useful for both debugging and for performance analysis.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813)*

**Comment by delroth** [comment]
LGTM, I'll let @lioncash have the last word.

**Comment by phire** [comment]
:lgtm:

---

Reviewed 1 of 18 files at r1, 5 of 19 files at r2, 10 of 15 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 50 unresolved discussions.

---

*[Source/Core/VideoBackends/Null/ShaderCache.cpp, line 37 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-KL5HSHj9DYRxeAErN7L:-KL907bXli3s87rN_Zdb:-1772663735) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3e3151b736418d04ab8ade0f07278f9c3afa075f/Source/Core/VideoBackends/Null/ShaderCache.cpp#L37)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> I want to hit as many videocommon parts as possible. Indeed, this is not required for a null backend, but it's useful for both debugging and for performance analysis.
</details>
BTW, later we might want to add configuration options that disable various individual parts of video common.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813#-:-KL91A8xBgBbzEa4Bdfz:1417088721)*

**Comment by lioncash** [comment]
Reviewed 1 of 18 files at r1, 5 of 19 files at r2, 10 of 15 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 50 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3813)*

**Pull request merged**
