### PR TITLE
(WIP) Opportunistic resend

### PR DESCRIPTION
**Pull request by comex**
Currently based on top of #1556 - just look at the two latest commits.

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/2477)

### CODE REVIEW

**Comment by Jofzar** [comment]
Is this the same thing as 1556 or is it different and should be retested?

**Comment by Jofzar** [comment]
Played for like 2 hours last night, seemed fine, didn't see any regressions / problems. After 2 1/2 hours of playing with someone he crashed, the error was "memory out of range or something" might be relevant might not be. 

Ill post in a couple of days of other peoples reports and performances from the aus netplay group.

**Comment by RisingFog** [comment]
What's the status of this PR?

**Comment by delroth** [comment]
Looks like this is abandoned. Closing, please sync this PR and comment if you think it should be re-opened.

**Pull request closed without merging**
