### PR TITLE
DolphinQt: Display game list compressed file sizes in blue

### PR DESCRIPTION
**Pull request by jordan-woyak**
This was the behavior in DolphinWx.

### CODE REVIEW

**Comment by shuffle2** [comment]
I think it was actually removed from wx version at some point (people said it was too obscure)...?

**Comment by Techjar** [comment]
This could also make the text hard to see on dark UI themes.

**Comment by MayImilae** [comment]
Yes we deliberately removed this from WX, because Windows dropped that convention years ago and no one knew what it meant anymore. I'm having some trouble finding exactly when it was removed though, I'll update this post when I find it.

**Comment by Helios747** [comment]
I do feel like we should have **some** indication of when a file is compressed, even if it isn't text color.

**Comment by JosJuice** [comment]
It was removed in PR #4941, a while ago after I made formats like WBFS and CISO also turn up as blue (rather than just GCZ) and people were making posts asking why their games are blue. If we're going to have an indicator, it would be better to indicate the actual file format rather than just "compressed".

**Comment by jordan-woyak** [comment]
I would like to have some indication of being compressed. And I'd rather not have to add another column. What about an asterisk appended to the file size?

**Comment by JosJuice** [comment]
That sounds reasonable to me. But I would prefer to do it with `game.GetFileSize() != game.GetVolumeSize()` rather than `game.GetBlobType() != DiscIO::BlobType::PLAIN`.

**Comment by JosJuice** [comment]
Or hm, I guess `game.GetFileSize() != game.GetVolumeSize()` would be confusing in the case that a disc image compressed badly and happens to get the exact same size as the original disc image...

**Comment by MayImilae** [comment]
An asterisk is fine with me!

**Comment by jordan-woyak** [comment]
> 
> 
> Or hm, I guess `game.GetFileSize() != game.GetVolumeSize()` would be confusing in the case that a disc image compressed badly and happens to get the exact same size as the original disc image...

True, but I think it still makes sense in the asterisk situation. (asterisk meaning this is not the true game file size)

**Pull request closed without merging**
