### PR TITLE
Qt/Windows: Don't open console window on startup

### PR DESCRIPTION
**Pull request by spycrab**

### CODE REVIEW

**Comment by shuffle2** [comment]
`char* lpCmdLine, int nCmdShow` are not equivalent to `argv, argc`.  
It probably is better overall to force this with the linker flag.  
This does not account for the unicode and/or debug log issues raised here  https://goo.gl/gGk2Ln

**Comment by spycrab** [comment]
@shuffle2 
Could we just use ```wWinMain`` and ``StringUtils`` to convert it from UTF-16 to UTF-8?

**Comment by ligfx** [comment]
It's not included in Externals right now, but would this work http://doc.qt.io/qt-5/qtmain.html ?

**Comment by shuffle2** [comment]
it sounds possibly good, do you have pointer to the source or docs or something more than a license file?
Would it be this? https://code.woboq.org/qt5/qtbase/src/winmain/qtmain_win.cpp.html

**Comment by spycrab** [comment]
Superseded by #5668.

**Pull request closed without merging**
