### PR TITLE
Android: Remove support for the old config system

### PR DESCRIPTION
**Pull request by JosJuice**
All settings that we care about from an Android perspective are now supported by the new config system, so we can remove all the Android code for the old config system. This should have no impact on users.

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
Now that I think about it, I think this should fix the issue where we crash when EmulationActivity is recreated after the process was killed. The problem was that we were trying to load the settings before directory initialization finished, but with this PR the call to `loadSettings` does almost nothing (unless we're loading game settings, which is not the case here).

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Review by t895 — APPROVED** [review]
LGTM

**Review by lioncash — APPROVED** [review]

**Pull request merged**
