### PR TITLE
CustomTexturesPath options (used by the batocera project)

### PR DESCRIPTION
**Pull request by nadenislamarre**
Signed-off-by: Nicolas Adenis-Lamarre <nicolas.adenis.lamarre@gmail.com>

### CODE REVIEW

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by nadenislamarre** [comment]
Hi,

thanks for considering my pr.
let me explain my usecase. However, if you think it is too specific, just close the pr. i can apply the .patch automatically when building for my use case.

This is for the batocera distribution.
About lightguns.
In case a gun is plugged to play dolphin, we want to apply some textures from the project https://github.com/ProfgLX/Sinden-Dolphin-Accuracy-Inis/tree/main/DolphinCrosshairsPack
to remove the gun crosshairs. But we want to do that without modifying the user files who can have some other textures for other games. So, the time of the gun games, if the user choose the option, we use the system directory for textures.

**Comment by iwubcode** [comment]
Thanks for your explanation.  So essentially you have a texture pack where you don't want to break the textures from other texture packs by using the same gameid folder?

You should be able to get the same effect by doing:

* Instead of individual game id folders, make a folder called "SidenCrosshairsPack".
* Then create individual <gameid>.txt files in that folder.  Put all your textures (for every game) in that folder as well (they can be split out into individual folders if you want).

It'd look something like:

~~~~
SidenCrosshairsPack
  / R2VE01.txt
  / R74E20.txt
  /  Arcade Shooting Gallery
    / <texture1>
    / <texture2>
  /  Sin and Punishment 2
    / <texture1>
    / <texture2>
~~~~


Now if the user has a separate pack, Dolphin will load *its* textures and it will load your crosshair pack as well.  If there are any texture clashes, they will be resolved alphabetically.

**Comment by nadenislamarre** [comment]
Hum,
i've not understood your example, but not sure the aim you propose is the one i want to archive.
Let me resay:

Current user dolphin path for texture is :
/userdata/saves/dolphin-emu/Load/Textures

It is empty by default.
If a user want to add textures he add them here.

Now, there is this gun pack.
On the system, it is available on the non user part.
precisely : /usr/share/DolphinCrosshairsPack

When a user launch a gun game,
the system run dolphin,
ideally it would run something like:
dolphin-emu --texturePath=/usr/share/DolphinCrosshairsPack
I've not done the modification at command line level, but at the config file level.
In batocera, we allow the system to modify some user emulator config files.
But we won't modify userdata textures for example, nor ask to the user to copy the texture in his folder (all must be automatic and work in case of system update).

I don't undertand where you suggest to create the folder SidenCrosshairsPack.
But it must not be in the /userdata folder.
But if not, i fear that dolphin cannot find it.

**Comment by mbc07** [comment]
AFAIK you should be able to use the "Sys" directory, next to the Dolphin binary...

**Comment by JosJuice** [comment]
@nadenislamarre Yes, I think iwubcode misunderstood slightly in their latest comment. But their original point about setting the `Load` path makes sense to me. Let me try to explain it.

What you're suggesting with this PR is:

Put the texture files in: `/usr/share/DolphinCrosshairsPack`
Launch Dolphin with: `dolphin-emu -C Dolphin.General.CustomTexturesPath=/usr/share/DolphinCrosshairsPack`

What you can already do in Dolphin is:

Put the texture files in: `/usr/share/DolphinCrosshairsPack‌/Textures`
Launch Dolphin with: `dolphin-emu -C Dolphin.General.LoadPath=/usr/share/DolphinCrosshairsPack`

Is there a reason why this wouldn't work?

@mbc07 No, it isn't set up for that.

**Comment by nadenislamarre** [comment]
on linux, only the user directory seems to be read.

[root@BATOCERA /userdata/system]# strace dolphin-emu
...
newfstatat(AT_FDCWD, "/userdata/system/.local/share/dolphin-emu/Dump/Textures/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/userdata/system/.local/share/dolphin-emu/Load/Textures/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/userdata/system/.local/share/dolphin-emu/Load/Textures/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/userdata/system/.local/share/dolphin-emu/Dump/Textures/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/userdata/system/.local/share/dolphin-emu/Load/Textures/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/userdata/system/.local/share/dolphin-emu/Dump/Textures/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
...

**Comment by nadenislamarre** [comment]
>>What you can already do in Dolphin is:
>>
>>Put the texture files in: /usr/share/DolphinCrosshairsPack‌/Textures
>>Launch Dolphin with: dolphin-emu -C Dolphin.General.LoadPath=/usr/share/DolphinCrosshairsPack
>>
>>Is there a reason why this wouldn't work?

it seems a good way.

however, i did it at the textures directory level to be more precise, less intrusive. Maybe i'm wrong.
i don't know what other things can be put in the load folder. overriding the loadpath, will override everything inside.

**Comment by JosJuice** [comment]
It's mostly other ways of modifying graphics, namely resource packs and graphics mods. (The raw Wii SD card is also in there nowadays for some reason, but you can set a custom path for that one separately if needed.)

**Comment by nadenislamarre** [comment]
so, adding CustomTexturesPath is the bad idea ?

**Comment by JosJuice** [comment]
I don't think we should merge this pull request, no.

**Pull request closed without merging**
