### PR TITLE
Sort DiscIO into subfolders

### PR DESCRIPTION
**Pull request by Stevoisiak**
[Rearranges DiscIO's folder structure](https://github.com/Stevoisiak/dolphin/tree/2641798ef220053216393624c19717a44aabe54b/Source) to more closely match the [layout used in Visual Studio](http://i.imgur.com/br2YRNG.png).

### CODE REVIEW

**Comment by shuffle2** [comment]
...why?

**Comment by Stevoisiak** [comment]
I think this helps organize DiscIO a bit. As it is now, the DiscIO consists of various files grouped together. I thought it might help if it were split up into distinct parts.

**Comment by Stevoisiak** [comment]
Is it worth rebasing this?

**Comment by kkkllleee** [comment]
You tell me, you don't even sound convinced yourself.

**Comment by Stevoisiak** [comment]
I think this is a good improvement, but not sure if anyone else does.

**Comment by Stevoisiak** [comment]
Obsoleted by #2268

**Pull request closed without merging**
