### PR TITLE
VideoCommon: Workaround Intel OS X bug again

### PR DESCRIPTION
**Pull request by endrift**
This time without the behavior change of the last patch. Reverts the last patch. Thanks, Apple. Thapple.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3796)

### CODE REVIEW

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by degasus** [comment]
Restores the old behavior + simplifys the code.

LGTM

**Comment by mimimi085181** [comment]
So this would reintroduce the bugs that pr https://github.com/dolphin-emu/dolphin/pull/3570 fixed? I take it, you tried to find a solution that works for all drivers? What about combing this revert with: pr https://github.com/dolphin-emu/dolphin/pull/3784 ? (just a random guess)

If this reintroduces bugs that were fixed, would it be justified to add specific driver workarounds for 5.0?

**Comment by RisingFog** [comment]
@mimimi085181 it fixes the bug in a different way if I recall correctly

**Comment by RisingFog** [comment]
@dolphin-emu-bot rebuild

**Comment by endrift** [comment]
@mimimi085181 This does not reintroduce the old bug. It looks like the original bug had something to do with sequence points or order of operations in the code getting done wrong (?????), which would imply 100% that it's a driver bug in Intel. Regardless, this reverts a behavior change that wasn't shown to be 100% necessary while fixing the bug, so it's much nicer in that regard, and may fix the AMD bug as well (yet to be shown).

**Comment by RisingFog** [comment]
@dolphin-emu-bot rebuild

**Comment by endrift** [comment]
I've just confirmed that this fixes the dff in https://bugs.dolphin-emu.org/issues/9468

**Comment by mimimi085181** [comment]
Nice, now maybe some other systems should be tested as well. Like the ones that were broken before the orignal pr.

**Comment by endrift** [comment]
It doesn't affect the ea-vp6.dff on any platform I tested it on, I don't think.

**Comment by endrift** [comment]
Anything holding this up now?

**Comment by degasus** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3796)*

**Comment by degasus** [comment]
Nope. @delroth ready to merge.

**Comment by phire** [comment]
We still need to do hardware tests in the future, but LGTM

**Comment by RisingFog** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
