### PR TITLE
Android: Fix jobject/jclass warnings

### PR DESCRIPTION
**Pull request by JosJuice**
Static methods use jclass, and non-static methods use jobject.

### CODE REVIEW

**Review by Ebola16 — COMMENTED** [review]
- Android Studio wants `jclass obj` for `onGamePadMoveEvent`
- Should we suppress the unused local variable warnings for `MainAndroid.cpp`? There's a lot of them.

**Comment by JosJuice** [comment]
I've fixed `onGamePadMoveEvent`. Not sure about the unused local variable warnings.

**Comment by Ebola16** [comment]
I'd like something to be done about the large amounts of unused `obj` warnings if not suppression.

**Comment by JosJuice** [comment]
The latest commit should address it.

**Review by Ebola16 — APPROVED** [review]
That works too.

**Review by lioncash — APPROVED** [review]

**Pull request merged**
