### PR TITLE
Android: show setting value as desc

### PR DESCRIPTION
**Pull request by weihuoya**

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by zackhow** [comment]
LGTM. And just to let everyone else know. These values will only show if the setting doesn't have a description. If a description is passed then it is shown instead of the current value.

**Pull request merged**
