### PR TITLE
Lossless image compression

### PR DESCRIPTION
**Pull request by Masterfireheart**
After a couple of passes I managed to shave off 654,586 bytes from most of the PNG images, and 16,998 bytes from the main installer ICO (I didn't bother compressing the other icons because they were for wxWidgets).

Unlike #3896, I used an actual encoder chain and genetic processing, not just some website, so the savings are _actually_ lossless :)

### CODE REVIEW

**Comment by GrieverV** [comment]
You should probably specify the tools used and options passed along with whether or not metadata was modified.

Personally, I prefer TruePNG for optimization due to it having the least amount of bugs and then advancecomp for further compressing the deflate streams. I believe [css-ig.net](https://css-ig.net) had good write-ups and benchmarks comparing most PNG tools.

I'm not familiar with Dolphin's guidelines, but commits should probably be squashed, too.

**Comment by Masterfireheart** [comment]
I usually go for throwing everything through a modified PNGGauntlet once (or running CaesiumPH on a backup copy if JPEG), then doing alternate passes between a strict-lossless pingo and a genetic brute-forced ECT, sometimes throwing in AdvPNG if the colors are minimal, before finally closing by running them all through PNGGauntlet again shaving a few more bytes from everything.

**Comment by MayImilae** [comment]
Well, I freaked out a bit when I saw this. As the original artist, that attempt to tinypng everything scared me so much. >_< 

So just like all of the rest, I grabbed an image from this PR and compared it to one of the originals and... I couldn't spot any different pixels! Even gradients and alpha pixels, usually the first to go in lossy compression, are all here. I went through one for each of the colors, and even looked at the android on screen buttons, and they were all completely intact!

So how did you get the savings? What is being stripped out?

Also, I would feel a little better if you can do a pixel to pixel comparison of them all, like a hash check. Juuust in case there are some minor errors somewhere. I can't really hand inspect hundreds of files!

Well, I guess if the images are all intact, and the file sizes are lower, then I don't have any complaints about this PR. Works for me!

(and maybe just maybe this will keep people from trying to optimize it in tinypng again!)

**Comment by Techjar** [comment]
A number of images were mangled by your "optimizations", here's the full list.
https://gist.github.com/Techjar/663a553f4ccd1f59864ce16c42074a4c

**Comment by GrieverV** [comment]
I don't believe `Externals/` should be getting touched by this PR.  

Metadata may need to be discussed if any important information is stored there such as copyright or color information, although I'd guess @MayImilae would have brought it up if there was.  

I'd suggest keeping PNG optimizations to one program and then further optimizing the deflate streams through `advdef` to reduce the chance of breaking the images. It's not like Dolphin is a website with high traffic where you'd want to save every byte.

**Comment by Masterfireheart** [comment]
@Techjar well damn, this confirms my slight fear that the first commit had a slightly different process then the rest, I'd estimate either pngquant, pngcrush, or POCL were used and didn't follow strict losslessness (perhaps I was tired and used a color quantization algorithm without realizing?), thanks for letting me know! I'll retry those images to get a fixed version.

@MayImilae hash checks don't work as the data is inherently different, but still (should) display the same picture. I've done lots of tests on my archives before using DSSIM and photoshop, but this seemed to be an interesting edge case in changing methods.

**Comment by Techjar** [comment]
Either oyou recompressed the mangled images rather than the originals, or you just mangled them again, as they look just as messed up as they did before.

**Comment by Masterfireheart** [comment]
@Techjar Which images specifically..? I checked a few images from hdpi, xhdpi, and xxhdpi, and they all passed DSSIM flawlessly and came up black in PS after adding a background and using a difference filter.

**Comment by spycrab** [comment]
Not sure if I'm a fan of all these micro-optimizations. It seems like it barely makes a dent filesize-wise. The unnecessary editing of binary files also blows up our git repo even further.

**Comment by Masterfireheart** [comment]
The way I see it, if the files are truly lossless and no necessary information is being truncated, then there's no reason to not optimize your images to the furthest extent you can. Each extra byte saved makes Dolphin a bit easier to download and they add up over time.

It's also not necessarily about how many bytes you save, but about the ratio between new : old. For example: saving a 1x1 white PNG with no compression enabled out of Photoshop results in an image that is **1,779 bytes**. One (super quick) pass through PNGGauntlet already brings it down to **82 bytes**, 5% of it's original size! Another pass through pngwolf (PNGOptimizerCL and DeflOpt also provide the same result) brings that down to **69 bytes**. Another pass through PNGGauntlet shaves 2 more bytes, resulting in **67 bytes** of data, 4% it's original size with the exact same image.

6000x6000 white PNG? **120,866 bytes**. PNGGauntlet? **4,470 bytes**. Perhaps across my 8TBs of hard drives, an extra 100kb doesn't seem to matter too much, but why would I be happy settling for the image the way it was when the data itself _could_ be so so much smaller?

Unless there are some specific metadata tags (besides gamma info, as we've already seen) or PNG chunks that need to be kept for specific reasons (which I would be glad to hear about so I could try my best to shave space around them), I don't see the harm in lightening Dolphin's load.

**Comment by GrieverV** [comment]
I believe @spycrab's argument against this is that the savings are only ~650KB while modifying ~700 binary files, which can result in a large increase in the repository's size. It might be better to only modify images if they have a certain percent of savings or greater. I believe there were a lot of newly committed images for different themes which is likely where most of the savings in this PR are coming from.

For more information about how git stores file revisions and why modifying large binary files is bad, this page has a good explanation: https://docs.microsoft.com/en-us/vsts/git/manage-large-files?view=vsts

**Comment by Masterfireheart** [comment]
Alright, I ended up keeping the original commits on another branch but just reset the master and redid the compression, still preserving gamma metadata and skipping a few steps that were honestly trouble to begin with (like the icon compression, which while saving relatively much could cause some annoying edge cases).

**Comment by jordan-woyak** [comment]
Unfortunately this PR has aged and needs a rebase, which would probably produce another long discussion. It seems as optimizing PNGs is too controversial a change if it can't be approved after 2 years. :P We better sufficiently optimize our images when they are initially introduced. I'm closing this PR for now but can reopen it upon request.

**Comment by RinMaru** [comment]
I think everything being run through OXIPNG is better its lossless and does it pretty quick

**Pull request closed without merging**
