### PR TITLE
(WIP) Android: move MainPresenter and MainView to MainActivity

### PR DESCRIPTION
**Pull request by Gamer64ytb**

### CODE REVIEW

**Comment by Gamer64ytb** [comment]
This PR is causing some crashes on TvMainActivity, that`s the why of WIP.

**Comment by JosJuice** [comment]
Why?

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by Gamer64ytb** [comment]
makes the src more clean of files, you can have all main activities of the emulator on 1, no on 3.

**Comment by Gamer64ytb** [comment]
I know this is not really needed but I think is better and more fast for developing.

**Comment by JosJuice** [comment]
A smaller number of files isn't always better. The purpose of dividing code into files is to group code in a way that makes sense. I don't think the grouping you're changing to here makes sense, because the purpose of MainPresenter is to hold code which is used by both MainActivity and TvMainActivity. Your alternative solution of having TvMainActivity call into MainActivity both adds an unusual dependency on MainActivity for TvMainActivity, and also (at least in its current state) doesn't actually work.

**Comment by JosJuice** [comment]
I do agree that having to deal with MainPresenter and MainView is a little annoying as a developer if you just want to make a change to MainActivity, but it's like that for a reason. It makes it easier for us to maintain having both MainActivity and TvMainActivity.

**Comment by JosJuice** [comment]
Let's do it like this: If you can get TvMainActivity to work again, we can reopen this PR. (I think you will find that getting TvMainActivity to work with your change is extremely hard.)

**Pull request closed without merging**
