### PR TITLE
Silence -Wformat warnings.

### PR DESCRIPTION
**Pull request by rohit-n**

### CODE REVIEW

**Comment by lioncash** [comment]
Half of these are very incorrect (a u64 is certainly not equivalent to a long)

**Comment by randomstuff** [comment]
Well, they are probably correct on the committer system but not on Windows. The correct solution to silence the warnings would be to use PRIx64, etc.

**Comment by lioncash** [comment]
Yeah, unfortunately I'll have to revert that PR.

**Comment by rohit-n** [comment]
Closing this PR, then.

**Pull request closed without merging**
