### PR TITLE
VI: wait until start of ACV to sample XFB addr

### PR DESCRIPTION
**Pull request by booto**
The same XFB addr was always being used by VI for each field because it was being sampled from the associated VI register before being updated (one field updated it much later than the other).

### CODE REVIEW

**Comment by JMC47** [comment]
Screw the WIP, let's merge this.

Notes:

Fixes broken XFB Emulation in almost EVERY title of Dolphin.  Whether it's the half framerate glitch (Metroid Prime 2), Out of order frames glitch (Super Mario Galaxy) or even weirder stuff like Cel-damage where only RealXFB was broken (Works now?)

On top of that, it has the added bonus of fixing Sonic Mega Collection, which has been broken for a few months.

Now, I know what you're thinking, we need to regression test this, the last two times we merged booto's XFB changes bad stuff happened afterwards.  Well, here's the trick, instead of using Master, I've been using this PR all along for my testing the past few days!  That means I've tested at least 50+ games, and I've made sure to leave on at least Virtual XFB, and use RealXFB when I encounter any problems.

I'm not guaranteeing there won't be regressions because there probably will be, but, I've done a much more thorough job testing it.

**Comment by delroth** [comment]
@booto can you clarify why this is currently marked as WIP?

**Comment by JMC47** [comment]
I forgot to mention one thing. Cel-Damage's case was a real progressive bug, where as all the other games worked in real progressive but were bugged in interlaced/fake progressive.

**Comment by dmarj** [comment]
@delroth WIP because I think it still needs comments about why it's doing certain things. I also wanted it to be tested as wide as possible and not pushed through quickly to address regressions - esp. by those that I've poked on two related issues on the bug tracker. This was made into a PR prior to the addition of the comments mainly to get it built for testing.

**Comment by booto** [comment]
@delroth WIP because I think it still needs comments about why it's doing certain things. I also wanted it to be tested as wide as possible and not pushed through quickly to address regressions - esp. by those that I've poked on two related issues on the bug tracker. This was made into a PR prior to the addition of the comments mainly to get it built for testing.

**Comment by JMC47** [comment]
Fixes random flickering in Rogue Squadron 2

**Comment by booto** [comment]
@JMC47 I updated with some comments (i.e. no functional changes), rebased against master, squashed the commits and removed [WIP] from title.

**Pull request merged**
