### PR TITLE
CMake: re-run if .git/$(symbolic-full-name HEAD) changes

### PR DESCRIPTION
**Pull request by ligfx**
In an oversight, PR #4841 didn't handle committing to or amending a branch.

### CODE REVIEW

**Comment by ligfx** [comment]
@dolphin-emu-bot rebuild clean

**Comment by Orphis** [comment]
Now, you are the one teaching me something about git! Well, I guess this is fine!

**Comment by Orphis** [comment]
@dolphin-emu-bot rebuild

**Comment by ligfx** [comment]
@dolphin-emu-bot rebuild clean

**Pull request merged**
