### PR TITLE
InputCommon:SDL: Proper joy-con support

### PR DESCRIPTION
**Pull request by tellowkrinkle**
- Work around another SDL 2.0.22 bug that we uncovered in the first workaround
- Enable hints to use hidapi for joycons so we can have motion support

### CODE REVIEW

**Comment by shuffle2** [comment]
can you just use static sdl from externals for now on macos? it's more recent than the release and if needed you can just pull the submodule instead of adding hacks for older versions.

**Comment by OatmealDome** [comment]
I tried to compile with static SDL on the build machine, but I got some odd errors. I think these are it:

```
-- Configuring done
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_OBJC_COMPILE_OBJECT
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_OBJC_COMPILE_OBJECT
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_OBJC_COMPILE_OBJECT
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_OBJC_COMPILE_OBJECT
```

**Comment by dagstuan** [comment]
Is this meant to fix motion controls with switch pro controllers as well? I tried using this build with my switch pro controller but I get no motion inputs in the controller configuration for `SDL/0/Pro Controller`.

**Comment by tellowkrinkle** [comment]
> Is this meant to fix motion controls with switch pro controllers as well? I tried using this build with my switch pro controller over bluetooth but I get no motion inputs in the controller configuration for SDL/0/Pro Controller.

Yes, it is
What OS are you on?

**Comment by dagstuan** [comment]
> Yes, it is What OS are you on? If you're on macOS, make sure to select "Nintendo Switch Pro Controller" "Pro Controller" is forwarded by SDL from Apple's GCController API, which doesn't support motion (or vibration)

I'm on MacOS 12.4. I don't see any "Nintendo Switch Pro Controller" in the Dolphin settings when I configure controllers. Do I need to do anything else? See attached screenshots of MacOS Bluetooth settings and Dolphin controller settings.

Screenshot 2022-08-01 at 12 01 31Screenshot 2022-08-01 at 12 02 03

**Comment by tellowkrinkle** [comment]
Okay looks like the buildbot's version of SDL is older than 2.0.22, which is why that isn't working for you

Since it looks like SDL 2.0.24 is scheduled to come out in less than a month, I think it'll make sense to just wait for that and then upgrade the buildbot (and also remove the current 2.0.22 workarounds)

**Pull request closed without merging**
