### PR TITLE
Remove self-comparison

### PR DESCRIPTION
**Pull request by tygyh**
Most likely something has gone wrong here, but just in case I'll mark it for deletion

### CODE REVIEW

**Comment by Pokechu22** [comment]
This is checking for NaN, since NaN != NaN. (It's also checking for falsy values, as -0 != +0). For both of those, it compares the raw bits instead of comparing the values as floats, so that exact NaN and zero values can be checked (because we want the vertex loader to load them unchanged, instead of silently converting into a different NaN or zero value). We don't *always* compare as bit values, simply so that regular values give a clearer error message.

This change as currently written breaks the tests. A better solution would be to use [`std::fpclassify`](https://en.cppreference.com/w/cpp/numeric/math/fpclassify) and check for `FP_NAN` and `FP_ZERO` (or maybe check for not `FP_NORMAL`).

**Comment by tygyh** [comment]
> This is checking for NaN, since NaN != NaN.

I understand why my change was wrong, but I don't understand the fix you are suggesting. Should it be written as `actual != FP_NAN && actual != FP_ZERO`?

**Comment by Pokechu22** [comment]
`!actual` is equivalent to `std::fpclassify(actual) == FP_ZERO` and `actual != actual` is equivalent to `std::fpclassify(actual) == FP_NAN`.

**Comment by Tilka** [comment]
GCC and Clang don't fully optimize `std::fpclassify()` for NaNs, so while this is just a unit test, let's promote the simpler `std::isnan()` instead.

**Review by Pokechu22 — APPROVED** [review]
Looks good to me now.

**Pull request merged**
