### PR TITLE
Dolphin: New fantastic optional theme

### PR DESCRIPTION
**Pull request by lioncash**
I felt like today would be a great day to showcase a theme that clearly shows a lot of thought and work has been put into it :^)
lol
jej

Jaw dropping for all the right reasons, isn't it?

### CODE REVIEW

**Comment by Furyhunter** [comment]
:+1: looks great pls make default :ok:

**Comment by pauldacheez** [comment]
LGTM, marry me pls

**Comment by Stevoisiak** [comment]
I think we need a blind merge here. Don't even test this. Just merge it

**Comment by JMC47** [comment]
Honestly, I love the design, but there's a few minor flaws that I think need to be ironed out before it can be merged.

The fullscreen icon and the speaker icon are artistically stylized in a majestic manner, but the controller icon is just thick lines and near photo-realism.  While impressive, these two styles clash and cause serious issues in user enjoyment.

If this is fixed, I do think I could allow this to be merged as default UI.

**Comment by RachelBryk** [comment]
Been using this as my only theme for months, i love it and cannot imagine why you haven't made a pr for this before.

LGTM

**Comment by Tilka** [comment]
@lioncash: Please add https://github.com/Tilka/dolphin/commit/536898a0af22ea24a39afd3abf30c353c6dd40f7 (after fixing up the commit message).

**Comment by RamonSFe** [comment]
hello

**Comment by RamonSFe** [comment]
Hey LionCash, Can You Help Me? I am Having Troubles With F-Zero GX for GameCube on Dolphin, Can You Solve For Me? I Can Pay in Real Money " Only if it is the Case " I Am from Brazil

**Comment by JosJuice** [comment]
@RamonSFe Stop spamming. You will not get any help here.

**Comment by RamonSFe** [comment]
@lioncash  Hello I Am Having Troubles With F-Zero GX for GameCube On Dolphin, Can You solve to Me? I Can Pay in Real Money " Only if it is the Case " I Am From Brazil

**Comment by RamonSFe** [comment]
@JosJuice Okay Thanks for Advice

**Comment by Linktothepast** [comment]
Masterpiece, the artist expresses his inner thoughts and ideas by manipulating scribbles in a form and way that makes them understandable to the average viewer. Marvelous, simply marvelous.

**Comment by waddlesplash** [comment]
:+1: :shipit:

**Comment by ds84182** [comment]
Maybe you could make a variant of that theme to make it more colorful and
playful. Kinda like a McDonalds play place but with even more color.

**Comment by autofire372** [comment]
I lol'd. Good one :)

**Pull request closed without merging**
