### PR TITLE
Include xxhash in Externals

### PR DESCRIPTION
**Pull request by riking**
My first PR to Dolphin that actually changes behavior :) "Must... contribute... to more... projects!"

    <degasus> meh, anyone with too much motivation to do a stupid PR? Include xxhash within dolphin ... I can't get myself to work on this task right now :/

The files were obtained from https://code.google.com/p/xxhash/.

I've tested by calling `XXH32()` in a random location that the files include and link correctly. Building Dolphin like this won't do much, as it's never actually used, though.

### CODE REVIEW

**Comment by delroth** [comment]
@dolphin-emu-bot rebuild

What about Windows support?

**Comment by riking** [comment]
Oh, do I need to edit some VS files for that? Not set up to do that, and the uni lab machines are a version or two behind on Visual Studio.

**Comment by degasus** [comment]
Can anyone on windows create a trivial project file? Neither me nor @riking work with windows.

**Comment by BhaaLseN** [comment]
Maybe look at Lioncash@211657215f3f36232557f8c6b675639b17c289b1? He did that more than a year ago.

**Comment by degasus** [comment]
@dolphin-emu-bot rebuild

**Comment by degasus** [comment]
@dolphin-emu-bot rebuild

**Comment by degasus** [comment]
@dolphin-emu-bot rebuild

**Comment by Tinob** [comment]
do you think that including all the code in externals is neccesary? the code is bsd and we need a modified version, so including the header and a reduced version, removing the endiannes and memory alignment code will give us a better implementation for our scenario and we can even squeze a little more performance.

**Comment by riking** [comment]
@Tinob If we want to put it in-tree, we can just cherry-pick https://github.com/lioncash/dolphin/commit/211657215f3f36232557f8c6b675639b17c289b1.

**Comment by shuffle2** [comment]
Adding windows projects is easy...
Take a reference file from Externals:
https://github.com/dolphin-emu/dolphin/blob/master/Externals/zlib/zlib.vcxproj
Delete the content of the GUID tag, then change the ClCompile and ClInclude items.
Then `git grep` to find how the `zlib.vcxproj` is used and mimic that as well.
The GUID will be auto-filled by VS when the project is loaded, so you might have to do something funky to obtain that...

**Comment by Sonicadvance1** [comment]
I want proper benches of xxhash versus murmur3 before this gets merged.
Benches on both x86_64 and AArch64 would be preferred.

**Comment by degasus** [comment]
@Sonicadvance1 http://markus.members.selfnet.de/dolphin/xxhash.png - your turn

This was done on this PR comparing our built-in hashes vs xxhash on an i5-3320M

**Comment by ZephyrSurfer** [comment]
@degasus There is no option to display that info from the GUI yet, is that right?
How would one enable those stats?

@Sonicadvance1 I've already done testing and xxhash is faster for me than murmur3
But I'll provide numbers if you want?

**Comment by Sonicadvance1** [comment]
You've benchmarked the two on ARMv7 and AArch64?

**Comment by ZephyrSurfer** [comment]
@Sonicadvance1 Sorry I have not tested on AArch64 just x86_64 :(
So again my apologies. I had meant to add "on my computer".

**Comment by Sonicadvance1** [comment]
http://hastebin.com/ayejenewim.dreams
Proper benchmarks of CRC32 versus Murmur3 versus XXHash64 on the Nexus 9's Nvidia Denver CPU.
Shows that XXHash64 tends to be around Murmur3 performance, slightly better at times, slightly worse on others. Within margin of error.
Also shows that CRC32 performance on Nvidia Denver is less than ideal. Hopefully will be better on Cortex-A57.

**Comment by degasus** [comment]
I've finished this PR within #1924. Thx for your help.

**Pull request closed without merging**
