### PR TITLE
Android: Wiimote on-screen buttons + more

### PR DESCRIPTION
**Pull request by SeannyM**
Alright, I'll talk about each commit separately here.

First off, I chose to use button IDs instead of drawables to save the coordinates of the on-screen buttons. Using the drawables worked with the old control set, because no drawables were reused. Now that there are multiple joysticks, it just doesn't. This also allows for different control layouts for each system.

Next, I added a new d-pad class. It takes 4 button IDs, one for each direction. Pretty self-explanatory, yeah? Eventually I plan to have an option for a sideways Wiimote, and it will simply require a d-pad with the direction keys mapped to different spots.

Here's the main change: Wiimote + Nunchuk controls (and GameCube c-stick!). InputOverlay checks what type of game is being run to determine the control set to use. All the buttons are present for the Nunchuk combo, you just can't use any motion controls! Eventually I'd like to use the device accelerometer/gyroscope to emulate motion controls, but that's for another time.

And finally, the option to toggle on/off individual buttons. If you don't like how cluttered all these new buttons are, just disable the ones you don't need! Personally, I'd be fine with simply moving them off the screen, but that's just me. This is accessed from the "Toggle Touch Controls" menu in-emulation. Previously, this feature completely disabled/enabled the buttons. That functionality is still there, and it can be used by pressing the "Toggle All" button.

Here are some screenshots:
GameCube controls: http://i.imgur.com/cthBUhK.png
GameCube toggle menu: http://i.imgur.com/pnP5haA.png
Wii controls: http://i.imgur.com/No4Ra8i.jpg
Wii toggle menu: http://i.imgur.com/N8kpYer.png

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4236)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 89 files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, line 406 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4236#-KSJBOYSlKPpWvDdg55e:-KSJBOYT05BUKCH33mVc:b-tqdb9a) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7f46d6431855789293637bdb4f7b067d89954a32/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java#L406)):*
> ```Java
> 				if (mIsGameCubeGame)
> 				{
> 					for (int i = 0; i < 11; i++)
> ```

`i < enabledButtons.length`

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, line 434 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4236#-KSJBYYEmWByUva_WbFA:-KSJBYYEmWByUva_WbFB:b-tqdb9a) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7f46d6431855789293637bdb4f7b067d89954a32/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java#L434)):*
> ```Java
> 				else
> 				{
> 					for (int i = 0; i < 11; i++)
> ```

`i < enabledButtons.length`

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java, line 761 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4236#-KSJBBtGySltkBj9DEEl:-KSJBBtGySltkBj9DEEm:b-tkcvtl) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7f46d6431855789293637bdb4f7b067d89954a32/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/activities/EmulationActivity.java#L761)):*
> ```Java
> 	}
> 
> 	public static boolean getIsGameCubeGame()
> ```

You can just name this `isGameCubeGame()`

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java, line 334 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4236#-KSJDCyAqnY2uRIwALbN:-KSJDCyB8hY1VhU02SrA:b-h02kqs) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7f46d6431855789293637bdb4f7b067d89954a32/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java#L334)):*
> ```Java
> 
> 		// Add all the enabled overlay items back to the HashSet.
> 		if (EmulationActivity.getIsGameCubeGame()) {
> ```

Brace should be on a new line.

---

*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java, line 556 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4236#-KSJCffJb2suz0TLByIx:-KSJCffJb2suz0TLByIy:b-jkmqhq) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7f46d6431855789293637bdb4f7b067d89954a32/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/overlay/InputOverlay.java#L556)):*
> ```Java
> 	 *
> 	 * @return the initialized {@link InputOverlayDrawableDpad}
> 	 *
> ```

Unnecessary comment newline here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4236)*

**Comment by Pringo** [comment]
@SeannyM did you make those new buttons yourself or did @MaJoRoesch make them?

**Comment by MaJoRoesch** [comment]
@Pringo These new ones are not mine, even though I already made the entire set. I was definitely surprise by this!

@SeannyM So I made an entire suite of icons already, and they are a bit higher quality than what you have here. Sonicadvance1 didn't merge them when I gave him the set because there was no use for it at that time. I'll try to sort it out on my own, otherwise I'll just give them to you.

**Comment by MaJoRoesch** [comment]
And it has been added! You can just use the set that is already in Dolphin now. :)

**Comment by SeannyM** [comment]
@MajoRoesh Awesome! They definitely look better than mine. I just figured I'd throw some together so I had something to use when testing. Guess I should've just asked you for these ones :p

**Comment by MaJoRoesch** [comment]
@SeannyM Does this PR have motion controls? I have never made any icons for them, but I could if they are needed.

**Comment by mbc07** [comment]
Maybe also add a Home button? Just for completeness...

**Comment by SeannyM** [comment]
I'd be fine with adding motion controls and/or a home button, if people want them. @MaJoRoesch if you want to make images for them, I'll use them.

**Comment by degasus** [comment]
@sigmabeta Do you have an opinion on this PR?

**Comment by sigmabeta** [comment]
Concept is good & nothing seems obviously wrong, so LGTM

**Comment by MaJoRoesch** [comment]
@SeannyM I forgot about the scaling values! The buttons are all the same size, and a scaling factor is applied to make certain ones bigger or smaller than the average. Don't worry, I already measured it all out, look at the below image! (you may want to refine the GameCube scaling too, since these are super accurate measurements!) Customize as needed for weird things like the Wiimote B button.

android buttons image

**Comment by MaJoRoesch** [comment]
Ok, the home button has been added!

I thought about motion controls, and I have some ideas on how to do it, but that's probably beyond the scope of this PR. Feel free to talk to me on IRC if you want to talk about ideas for motion controls!

**Comment by degasus** [comment]
The wiimote home button images are now in master. Might you rebase again and add them please? But I doubt motion control matters.

**Comment by SeannyM** [comment]
@MaJoRoesch Yeah, I was planning on using the actual device accelerometer/gyroscope for motion controls, at least once I learn how to! I've never worked with that stuff before. I'll hop on IRC when I'm planning on doing that. For the scaling: I followed your guide (thanks for that by the way), but I did a few things different. First of all, I didn't scale the L, R, or Z buttons because they would look freakishly huge (I can change this if you want). Also, I did some measuring of my own, and I scaled the GC d-pad to 1.9cm and the Wii d-pad to 1.7cm. I scaled everything based on 0.125 being 1cm. Now that a lot of the buttons are smaller, I feel reimplementing customizable button scaling would be a good idea. But, that's for another PR. I have some screenshots below.
GameCube controls: http://i.imgur.com/cthBUhK.png
Wii controls: http://i.imgur.com/No4Ra8i.jpg

**Comment by SeannyM** [comment]
Oops, I scaled the c-stick nub wrong! Fixed :P

**Comment by MaJoRoesch** [comment]
@SeannyM That looks pretty good! The dpads don't look quite right, they look a lot bigger than reality, but honestly, I don't care! Obviously I knew going in that realities of someone pressing on a touchscreen versus the physical controller would require some adjustments for usability. So I'm totally fine with the tweaks you've made.

...well, I do think the L and R buttons should be a little bigger, but that's just a matter of taste. 

Oh! How does the joystick move regarding the edge? I imagined the joystick going beyond the edge, like a joystick at half the size serves as the "stick" for the joystick nub and hits the edges. Erm, I'll show you. (First image - how it appears. Second image - showing the half size "stick" that hits the edges)

joystickdistance joystickdistance2


How does it work in this PR? It doesn't have to be like how I thought it up, but it just needs to be functional, and I'd like to know how you worked it out.

**Comment by SeannyM** [comment]
@MaJoRoesch actually, the joysticks currently don't redraw when they are used. The nub just stays in the middle the whole time! This is on my todo list, along with showing the pressed images when buttons are pressed, because we don't do that right now either...
I'll make the triggers a bit bigger. Would you prefer larger d-pads too? I didn't want to use one size for all of them, I can see the size difference between the classic controller d-pad and the others (unless my classic controller is different? O.o).

**Comment by MaJoRoesch** [comment]
The dpad seems fine to me. It will really depend on how usable it is on an average sized phone, imo.

The classic controller pro's dpad is quite a bit bigger than the wiimote or gamecube's dpads. I measured! It's the full size dpad, like an SNES.

**Comment by SeannyM** [comment]
I find they are usable, though I also have a 5.5 inch screen. I think keeping them they way they are now is fine, I'll try to get around to user-adjustable scaling sometime soon so it shouldn't be too much of a problem either way.

**Comment by degasus** [comment]
LGTM
@dolphin-emu-bot allowmerge

**Comment by brujo5** [comment]
Some wii games can be played with gamecube controller but there is no option to switch controller overlay 

Also the wii overlay controller not working for me . 

Tested dbz budokai tenkiachi 3 wii in my galaxy S6 cm13 
screenshot_20161002-145209

**Comment by SeannyM** [comment]
@brujo5 I plan on adding an option to switch between controllers in Wii games, it's on my TODO list among other things. As for the controller not working, try deleting the file dolphin-emu/Config/WiimoteNew.ini from your device storage, and clearing the app data. Also, next time you have a problem like this, feel free use the [Dolphin forums](https://forums.dolphin-emu.org/Forum-android).

**Comment by brujo5** [comment]
OK,  thank You.

**Comment by brujo5** [comment]
Fresh install and still the same. Only the home button is detected in the wii overlay. 
Think the game detected the wii overlay as gamecube controller because some function in game looks like gamecube.

**Comment by SeannyM** [comment]
@brujo5 Go to GameCube input (tap the 3 dots in the top-right corner of the game list), tap controller 1, and set it to disabled. The game is probably trying to use the GameCube controller because it is still connected.

**Comment by brujo5** [comment]
Sorry for delay. Also here another user with similar issues https://forums.dolphin-emu.org/Thread-controls-problem--46371

Thanks

**Comment by brujo5** [comment]
Any idea why the dpad work inverted in the game contra rebirth (wii)?
Also is posible add more size to the button?

**Comment by Sonicadvance1** [comment]
Probably a similar issue to the inputmanager inverting Gamecube controller controls. Bug in the input manager.
Although PRs aren't support forums, so I'm going to be locking this as well, support should be in the forum.

**Pull request merged**
