### PR TITLE
Fix home button in tas input.

### PR DESCRIPTION
**Pull request by RachelBryk**

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Is there any reason why you don't use the array-size of ```m_buttons``` instead? Other than the fact that button indices 11 to 13 don't seem to be initialized at all (unless I missed something).

**Comment by RachelBryk** [comment]
11-13 are for extensions.

**Comment by BhaaLseN** [comment]
And should they be excluded from that loop for a particular reason that doesn't call for making it a distinct array?
It seems odd to me either way, and should probably be done differently...

**Comment by RachelBryk** [comment]
Yes, they have to be excluded, because they are not stored with the wiimote buttons.

As for making a different array for them, you can do that if you want. It's convenient as is though because in other places we do loop through all of them.

**Comment by BhaaLseN** [comment]
Just saying, it invites errors like the one you fix with this PR, and also lets guys like me ask the question "wait, isn't that wrong too, what about the other indices?".
Fine with me tho, as long as its understood why things happen that way.

**Comment by RachelBryk** [comment]
Yeah, if someone else wants to change it, i won't object, but not interested in doing it myself.

**Pull request merged**
