### PR TITLE
Qt/TAS: Allow using normal controllers

### PR DESCRIPTION
**Pull request by spycrab**

### CODE REVIEW

**Comment by rukai** [comment]
I assume this is to allow using controllers and TAS dialogs at the same time?
Because it doesnt seem to be working.
It works at first for regular controllers but the UI stops responding after a while.
With native GC -> wii u adapter it never works, and the UI also stops responding after a while.
This seems similar to an issue we had in wx, where the UI would freeze instantly? after opening the TAS dialog when using a GC -> wii u adapter and a game is running.

Something I attempted long ago was a toggle between taking inputs from controller or TAS dialogs. https://github.com/dolphin-emu/dolphin/pull/3609
It was then picked up by fog and then dropped again. https://github.com/dolphin-emu/dolphin/pull/4265
I cant remember if this fixed the UI freezing or not...?
It was definitely at least needed to differentiate between taking inputs from the real control stick or from the TAS control stick because the real control stick doesnt sit at (0,0) so we cant tell if its in use or not.

**Comment by spycrab** [comment]
Shouldn't hang anymore.

**Comment by rukai** [comment]
Awesome! Can confirm it doesn't hang anymore.

I sort of mentioned the following in my previous comment, but now that you fixed the hang its easier to see what's going on with this second issue.
Analog inputs can't be set in the TAS dialog in either of these cases, they are immediately overwritten with the physical controllers input:
*   Using a regular controller with Background Input is enabled.
*   Using a GC -> Wii U adapter (the adapter always takes input regardless of window focus)

It works with regular controllers + no background input because when the TAS dialog is focused no controller inputs are sent to dolphin.

**Comment by JMC47** [comment]
So we need it to override regular inputs?

**Comment by rukai** [comment]
Yes I expect the TAS dialog to override regular inputs. Otherwise I need to set my controller to keyboard in order to use the TAS dialog.

Doing this by window focus is actually something I didn't think of before when making the input toggle PR. But that would definitely be the most ergonomic solution if we can get that to work.

**Comment by rukai** [comment]
I'm working on a branch, that implements this with a toggle button instead, I'll submit a PR sometime tomorrow.
Using window focus wont work because Qt doesn't give you raw OS window focus, instead focus is split up by QWidgets.

**Comment by spycrab** [comment]
Superseeded by #7203

**Pull request closed without merging**
