### PR TITLE
Require clang-format 9 and reformat source code

### PR DESCRIPTION
**Pull request by leoetlino**
This updates the lint script to require clang-format 9 and reformats
existing source code. Since VS2019 ships with clang-format 9 this
should make auto reformats less painful.

This also updates the clang-format configuration to set
BraceWrapping.AfterCaseLabel to true to ensure consistent brace
style; otherwise clang-format 9+ defaults to putting braces on
the same line as switch case labels.

### CODE REVIEW

**Comment by jordan-woyak** [comment]
Yay!

**Comment by Tilka** [comment]
Now that #8527 is merged, this PR needs to update the readme.

**Comment by shuffle2** [comment]
please also remove the clang-format part of the windows build wiki https://github.com/dolphin-emu/dolphin/wiki/Building-for-Windows when this is merged

**Comment by leoetlino** [comment]
Removed the clang-format 7 paragraph from the readme

**Pull request merged**
