### PR TITLE
Fix manual update check which was hardcoded to "dev" track

### PR DESCRIPTION
**Pull request by delroth**
https://dolp.in/i12848

### CODE REVIEW

**Comment by delroth** [comment]
@dolphin-emu-bot rebuild

(? why did this not trigger)

**Comment by OatmealDome** [comment]
I tried fixing this previously in #9893, but apparently it is intentional behaviour.

**Comment by delroth** [comment]
I'm going to assume that the original decision was not made strongly. We now have the hindsight with us showing that users are confused enough by this behavior to file bug reports about it.

I think the proper fix would be something along the lines of "no update on your track, but if you switched to that other track there would be an update available". That's not completely trivial to implement, and this is a niche feature, so I think going for the less confusing "follow the selected track" option is probably better.

@spycrab any objection? You wrote this originally.

**Comment by delroth** [comment]
Merging this for now, please feel free to send a revert if you feel strongly otherwise and want to discuss it further!

**Pull request merged**
