### PR TITLE
Prevent mmap failure, closes #10016

### PR DESCRIPTION
**Pull request by sagb**
With explicit MAP_ANONYMOUS, mmap works on Debian Sid, 3.16.0-4-amd64, and returns MAP_FAILED otherwise.
Not tested on other systems.

### CODE REVIEW

**Comment by Parlane** [comment]
Do you have the reasoning behind why this fixes the issue? What does MAP_ANONYMOUS do ? And why is our code ok without it on other systems ?

**Comment by sagb** [comment]
From man mmap:

>        MAP_ANONYMOUS
>               The  mapping is not backed by any file; its contents are initialized to zero.  The fd and off‐
>               set arguments are ignored; however, some implementations require fd to be -1 if  MAP_ANONYMOUS
>               (or  MAP_ANON)  is  specified,  and  portable  applications  should  ensure  this.  The use of
>               MAP_ANONYMOUS in conjunction with MAP_SHARED is supported on Linux only since kernel 2.4.

I've added this flag solely because it fixed https://bugs.dolphin-emu.org/issues/10016 (you can see detailed trace there).
mmap returns MAP_FAILED probably because fd=-1, which is ok for anonymous mapping but wrong otherwise.
Source/Core/Common/MemArena.h confirms that these memory allocations are supposed to be anonymous (not backed by any file):

> // This class lets you create a block of anonymous RAM, and then arbitrarily map views into it.
> // Multiple views can mirror the same section of the block

I don't have any clue why code is ok without it on other systems.
I wonder why it works somewhere without this flag in the first place.

**Comment by sagb** [comment]
Possible pitfall: MAP_ANONYMOUS is probably not defined on Mac, so deprecated MAP_ANON should be used instead, which should be compatible with both Linux and Mac.

**Comment by Parlane** [comment]
Well it did build on our osx buildbot so it should be fine.

**Comment by Parlane** [comment]
So according to the documentation mmap should have fd set to -1 when the anonymous flag is used. So your code would need to only set the flag if fd is actually -1.

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by sagb** [comment]
This is kind of "if A follows B, then B follows A"
but considering that "fd" private member is initialized in obscured and intricated way,
you are probably right about this precaution, I've included it.

**Comment by Parlane** [comment]
sagb are you able to run it under gdb and put a breakpoint on MemArena.cpp:78 and see if that gets hit. Then if it does print errno .

**Comment by sagb** [comment]
Yes, it's hit.
errno = <error: Cannot access memory at address 0xffffd974b678>

**Comment by JosJuice** [comment]
Please don't put merge commits in the PR. Also, you should use rebase or amend when making small fixup changes rather than making separate commits.

**Comment by Parlane** [comment]
Hmm I wonder what happened to errno...

**Comment by hthh** [comment]
@sagb I'm afraid if you use `MAP_ANONYMOUS`, or if `shm_open` fails, memory mirroring is going to be broken. I'm not sure how many games this breaks, but I don't think it's a safe workaround.

If you can figure out why `shm_open` is failing, as Parlane asked, you might be able to fix the underlying issue, but making the allocation anonymous isn't a safe solution.

Printing `errno` is a bit tricky... You could instead try to enable logging so we could see the `ERROR_LOG(MEMMAP, "shm_open failed: %s", strerror(errno));` message, which might be clearer. Or you could maybe try one of the techniques listed here: http://stackoverflow.com/questions/11495720/why-cant-errnos-value-be-printed (the result should be a single number, not a string/message, but I'm not too familiar with GDB personally)

**Comment by Parlane** [comment]
print *((int*(*)())__errno_location)()

**Comment by sagb** [comment]
Sorry. 
11:10:712 Common/MemArena.cpp:78 E[MI]: shm_open failed: Function not implemented

**Comment by sagb** [comment]
errno=38

**Comment by sagb** [comment]
Mounting /dev/shm fixed the shm_open.
It's up to you if this requirement needs fix or clarification in docs or at runtime.

**Comment by hthh** [comment]
@sagb Thanks, I'm glad we now know what was going on. I'd suggest failing slightly more helpfully/gracefully, maybe:

```
if (errno == ENOSYS)
 PanicAlert("Error: shm_open unavailable, you may need to mount /dev/shm")
```

Are you interested in contributing something like this, or should we just close this PR?

**Comment by sagb** [comment]
I believe it's rare condition and may be closed as is.

**Pull request closed without merging**
