### PR TITLE
[JIT] Enable Accurate Double to Single Conversion

### PR DESCRIPTION
**Pull request by JMC47**
Fixes issue [11173](https://bugs.dolphin-emu.org/issues/11173)

I've been testing this a few days to see if there are performance implications, and a game I know uses this feature (Super Mario 64 on VC) is actually faster with this enabled for some reason.  Other games don't seem to have any noticeable impact.

### CODE REVIEW

**Comment by JMC47** [comment]
Can someone tell me what the heck lint wants?  It doesn't seem to be consistent with the rest of the file and isn't even in the section I touched.

**Comment by MrCheeze** [comment]
Confirming that this does indeed fix the SM64 platform raising issue.

**Comment by JMC47** [comment]
Good to hear!  Does anyone else want to review this?  @phire?  Since you did the original change, I just activated it.

**Comment by leoetlino** [comment]
From IRC

```
-*- Warepire wonders why the define is used instead of just removing the ifdef stuff
...
<leoetlino> I did suggest removing the ifdef, but JMC said someone wanted it to stay
<Bh44L> looks like the consensus is to get rid of the other code
```

**Comment by phire** [comment]
Ah, I was wondering why dolphin wasn't used when I saw that new strategy video.

From memory, the two versions of code are "meant" to be equally accurate, which is why my "more accurate" version was disabled. My guess is the x87's rounding mode is throwing things off, that could be configured, I guess, but if my "more accurate" code is just as fast, why keep the inaccurate code around.

Looks like there is an optimisation or two which can be applied to the more accurate ConvertDoubleToSingle code. 

1. I think you can get the demormal check down to a single branch with an extra scratch register and a branch.
2. The denormal handling code should be moved to far code.

No real need to include those optimisation in this PR, I'm just noting things down.

**Comment by phire** [comment]
I've thought about this some more.  
It's not (just) the x87 which is rounding incorrectly, CVTSD2SS is rounding incorrectly too (unless the game just so happens to have configured the FPU in the round towards zero mode)

This means the whole idea of the previous version (using CVTSD2SS when possible) is fundamentally flawed.

This code only gets run when the game uses the store floating single (stfs) instruction on the result of a double instruction. This forces a double result to be "reinterpreted" as a single. 

In the PowerPC spec, the result of such a re-interpretation is officially undefined, you are meant to use the round to single (frsp) instruction to convert any doubles into single precision floats (which mainly just applies the correct rounding mode to the bottom bits of the significand) before storing them as singles. 

On Gekko/Broadway, this undefined operation results in a reasonably successful double to single conversion, except it always applies the round towards zero rounding mode as a side effect of ignoring the bottom 30 bits of the significand. (Fun fact, the round towards zero rounding mode is otherwise known as truncate, exactly what is happening here),

I'm not 100% sure on hardware what happens to extremely large doubles (larger than 3.4E+38). In our implementation they wrap around to much smaller numbers. I have similar questions about extremely small numbers, smaller than what you could store in a denormal. I'm guessing round to zero, though our current implementation wraps them to larger numbers.

There are probably quite a few floating point edge cases waiting to be found due to the weird way PowerPC implements single precision. Like, I assume similar truncation of the significand happens when you feed a double into single precision instructions, and I'm slightly suspicious that denormal results (when flush to zero is off) get extra precision.

**Comment by MrCheeze** [comment]
For the record, the original code that results in the strange rounding behaviour in SM64 (before being compiled to MIPS and interpreted to PowerPC) is `y -= sin(t) * 0.58`, where y and the output of sin are both single precision and 0.58 is double. Which definitely fits what you're saying.

**Comment by phire** [comment]
> the original code that results in the strange rounding behaviour in SM64 (before being compiled to MIPS and interpreted to PowerPC) is `y -= sin(t) * 0.58`

I bet they intended to write `y -= sin(t) * 0.58f`.

Sounds like they got the implementation of `CVT.S.D` and `CVT.S.W` wrong.      
The correct implementation for `CVT.S.D` would be something along the lines of:

    frsp fdest, fsrc ; Round to single precision float.

However, it sounds like they have implemented it as a simple:

    fmr fdest, fsrc ; Floating point move register

It's kind of understandable they made this mistake, because the correct implementation of  `CVT.D.S` is actually:

    fmr fdest, fsrc ; Floating point move, or a nop if it's already in the correct location.

This is valid because on PowerPC, singles are automatically converted to doubles when they are loaded into a floating point register. The FPU ignores the lower bits of the significatand when executing single precision operations and rounds/clamps the result approximately.

**Pull request merged**
