### PR TITLE
Android: Various touch control improvements

### PR DESCRIPTION
**Pull request by SeannyM**
The joystick now moves with the user's finger, and displays as pressed when in use to match the other controls. The bug where dragging your finger off of a button would cause it to continue being pressed is finally fixed. Finally, dpad images for smaller resolution displays were added.

### CODE REVIEW

**Comment by brujo5** [comment]
Work good. 

Hope they merge this soon

**Comment by FishamanP** [comment]
> The bug where dragging your finger off of a button would cause it to continue being pressed is finally fixed.
Not sure if "fixing" this is ideal. I hate when I'm trying to hold down a button, and because my screen detects my finger as being on the edge, the emulator instead sees a virtual mash. The existing code avoids this problem.

**Comment by SeannyM** [comment]
@FishamanP I'm not sure why an edge touch would register as mashing? The biggest problem here is that moving your finger even slightly out of bounds before releasing caused buttons to become stuck pressed; this was never the intended result. With this, there is no chance of accidental stuck buttons, and it also more accurately mimics a physical controller (ex. swiping over ABXY will input A then B then X then Y, as opposed to previously where all 4 buttons would stay held down until pressed again). Looking at how other Android emulators handle touch input, this seems to be the standard.

**Comment by FishamanP** [comment]
Pressure on the touch screen is rarely positionally stable. A finger close to the edge of a button might read on it one frame, off the next, and then back on. This would break the intended hold input.

While I didn't realize the old behavior would press additional buttons, I believe that would still be preferable to this PR. However, IMO the best would be what I've seen as standard, which is to hold down the first button pressed until the user's finger is lifted. This ensures subtle subconscious sliding motions don't release the button.

**Comment by SeannyM** [comment]
Alright, I see your point. What I've done is remove the pointer move detection entirely; this, along with using track IDs to detect releases, means that as long as you press a button in its bounds, it will stay pressed until you release your finger, even if your finger slides out of bounds while you're pressing. And it _will_ release when your finger leaves the touch screen, even if it is released outside of the button's bounds. This ensures that buttons will not get stuck, while keeping the previous functionality.

**Comment by brujo5** [comment]
Without this joystick animation latest build looks weird.

**Comment by Sarkie** [comment]
@SeannyM Does the data need to be cleared from Android to see these new ones?

**Comment by SeannyM** [comment]
@Sarkie no, it shouldn't need to be.

**Comment by BreakPoints** [comment]
@SeannyM I know this is probably not the place for questions, so sorry, but are these features going to be implemented for GameCube control overlays as well?

**Comment by SeannyM** [comment]
Hmm, there might be a problem with Android buildbot builds, because the recent changes aren't appearing in them. @Sarkie @BreakPoints you're using the buildbot builds, right? @delroth (you're in charge of buildbots right?) could you look into it?

**Comment by degasus** [comment]
I can clear the buildbot in a few hours if this helps.

By the way, do you have an idea about https://bugs.dolphin-emu.org/issues/10287 ?
18:41:08   JonnyH`Work | yeah, seeding Dolphin.ini with [Core]\nGFXBackend = OGL\n
18:41:09   JonnyH`Work | fixes it

**Comment by BreakPoints** [comment]
@SeannyM yeah I'm using buildbot builds, brought up GC because I only have one GC game on my phone for testing. The reported build version in the app on my phone is 5.0-3617 with the latest build installed, might 5.0-3625 be the problem if changes are not appearing?

**Comment by brujo5** [comment]
@degasus 

work fine here. i can switch video backed without problem

tested in s6 edge and one plus 3T

the only thing is anymated joystick/buttons dont work

**Pull request merged**
