### PR TITLE
Use GNUInstallDirs for installation paths

### PR DESCRIPTION
**Pull request by h3xx**
Lets the user override the sane defaults from `GNUInstallDirs`.

More information on `GNUInstallDirs`: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

User-facing changes to configuration step:
- Use `-DCMAKE_INSTALL_BINDIR=...` instead of `-Dbindir=...`
- Use `-DCMAKE_INSTALL_MANDIR=...` instead of `-Dmandir=...`

If you specify none of these options, the installation paths should be the exact same.

### CODE REVIEW

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Review by Zopolis4 — APPROVED** [review]
LGTM-- sensible usage of GNUInstallDirs as far as I'm concerned, better way for users to define these directories rather than overriding our internal variables, and install directories are still the same as before.

**Comment by AdmiralCurtiss** [comment]
Needs a rebase.

**Comment by Simonx22** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
