### PR TITLE
IOS: Minor IPC fixes

### PR DESCRIPTION
**Pull request by leoetlino**
This adjusts IOS IPC timing to be closer to actual hardware according to [hardware tests](https://github.com/leoetlino/hwtests/blob/af320e4/iostest/ipc_timing.cpp).

Dolphin, before the fixes:

<details>

```
Invalid command (1000 tests)
ack_ticks=85/1, reply_ticks=1518/1

Invalid command (with IPC interrupt) (1000 tests)
ack_ticks=187/0, reply_ticks=1436/1

Open with full FD table (1000 tests)
ack_ticks=85/0, reply_ticks=1518/0

Invalid open (1000 tests)
ack_ticks=85/0, reply_ticks=1518/0

Invalid FD (0) (1000 tests)
ack_ticks=85/0, reply_ticks=1518/1

Invalid FD (200) (1000 tests)
ack_ticks=85/0, reply_ticks=1519/1
```

</details>
<br>

Dolphin, after the fixes:

<details>

```
Invalid command (1000 tests)
ack_ticks=502/1, reply_ticks=978/1

Invalid command (with IPC interrupt) (1000 tests)
ack_ticks=620/0, reply_ticks=979/1

Open with full FD table (1000 tests)
ack_ticks=502/0, reply_ticks=5000/0

Invalid open (1000 tests)
ack_ticks=502/0, reply_ticks=3700/0

Invalid FD (0) (1000 tests)
ack_ticks=502/1, reply_ticks=549/1

Invalid FD (200) (1000 tests)
ack_ticks=502/1, reply_ticks=550/1
```

</details>
<br>

Here are the results on my console:

<details>

```
Invalid command (1000 tests)
ack_ticks=661/22, reply_ticks=963/7

Invalid command (with IPC interrupt) (1000 tests)
ack_ticks=783/23, reply_ticks=959/4

Open with full FD table (1000 tests)
ack_ticks=667/31, reply_ticks=5209/22

Invalid open (1000 tests)
ack_ticks=673/53, reply_ticks=3786/42

Invalid FD (0) (1000 tests)
ack_ticks=659/14, reply_ticks=557/5

Invalid FD (200) (1000 tests)
ack_ticks=659/14, reply_ticks=550/5
```

</details>

<br>

I picked a slightly lower number of ticks for acks because JMC's console is faster than mine (~300-400 ticks).
 
This also fixes small issues with the IPC emulation code:

* The IPC interrupt is triggered when IY1/IY2 is set and Y1/Y2 is written to even when this results in clearing the bit. In practice, this shouldn't change anything but it's a difference that Dolphin wasn't taking into account, which made me waste some time when I was trying to write a hwtest :/
* A very basic hardware test shows that the ARMMSG doesn't change until IOS replies. (People could have disassembled IOS to verify this too...)
* Hardware tests indicate that IOS clears X1 when it acknowledges an IPC request.
* Also fix the FD table full error code.

In practice, this fixes a regression introduced by a663fcb97 which caused the HBC to crash on exit.

### CODE REVIEW

**Comment by degasus** [comment]
Why do you calculate the amount of ticks from a real time? I'd just use the ticks themself instead of querying GetTicksPerSecond

**Comment by leoetlino** [comment]
So the amount of timebase ticks × 12 to convert them to ticks, is that correct?

**Comment by degasus** [comment]
GetTicksPerSecond() always returns 729000000 in Wii more. So 12 PPC ticks per ARM tick sounds fine.

**Comment by sepalani** [comment]
I got the following results (almost the same after several attempts) while running the hardware test on my Wii:
```
Hello world!
IOS version 61

Low-level IPC
ran 1000 iteration(s)
average: ack_ticks=664, reply_ticks=961

Low-level IPC (with IPC interrupt)
ran 1000 iteration(s)
average: ack_ticks=763, reply_ticks=954
```

It was compiled using a very recent devkitPPC version and my Wii is from December 2006 (not sure that detail matters). It seems slightly faster. Regarding the current timing, it doesn't raise that old timing issue preventing some calls to return the proper value. So I'm okay with the current timing changes.

**Comment by leoetlino** [comment]
Yeah, I have pretty close results on my console, but I used slightly lower numbers since JMC's console was faster (~300-400 ticks).

**Comment by sepalani** [comment]
The results on my console:
```
IOS version 61

Invalid command (1000 tests)
ack_ticks=664/33, reply_ticks=962/5

Invalid command (with IPC interrupt) (1000 tests)
ack_ticks=797/21, reply_ticks=954/4

Open with full FD table (1000 tests)
ack_ticks=664/30, reply_ticks=5176/17

Invalid open (1000 tests)
ack_ticks=666/42, reply_ticks=3617/15

Invalid FD (0) (1000 tests)
ack_ticks=662/29, reply_ticks=557/4

Invalid FD (200) (1000 tests)
ack_ticks=662/29, reply_ticks=549/4
```

Homebrews are still working without timing issues, AFAICT.

**Comment by BhaaLseN** [comment]
And here's mine, quite old 4.3E (with vulnerable boot1, so yay, bootmii boot2):
```
Hello world!
 IOS version 58

 Invalid command (1000 tests)
 ack_ticks=661/23,  reply_ticks=963/7

 Invalid command (with IPC interrupt) (1000 tests)
 ack_ticks=782/26,  reply_ticks=959/5

 Open with full FD table (1000 tests)
 ack_ticks=667/31,  reply_ticks=5210/22

 Invalid open (1000 tests)
 ack_ticks=686/71,  reply_ticks=3699/18

 Invalid FD (0) (1000 tests)
 ack_ticks=659/15,  reply_ticks=559/32

 Invalid FD (200) (1000 tests)
 ack_ticks=659/18,  reply_ticks=550/5
```

**Comment by leoetlino** [comment]
PPLToast's Wii (from around 2010)

```
Invalid command (1000 tests)
ack_ticks=661/24,  reply_ticks=965/6
Invalid command (with IPC interrupt) (1000 tests)
ack_ticks=799/20,  reply_ticks=960/5
Open with full FD table (1000 tests)
ack_ticks=667/30,  reply_ticks=5216/22
Invalid open (1000 tests)
ack_ticks=670/46,  reply_ticks=3707/17
Invalid FD (0) (1000 tests)
ack_ticks=658/16,  reply_ticks=560/33
Invalid FD (200) (1000 tests)
ack_ticks=659/13,  reply_ticks=550/5
```

Results are surprisingly consistent with what we have so far.

**Pull request merged**
