### PR TITLE
[WIP] New configuration system

### PR DESCRIPTION
**Pull request by mathieui**
From @Sonicadvance1 (https://github.com/dolphin-emu/dolphin/pull/3516)

Newly rebased on master.

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3879)

### CODE REVIEW

**Comment by i30817** [comment]
I'm just wondering, does this allow per game controller configuration?

**Comment by Aestek** [comment]
It should https://github.com/dolphin-emu/dolphin/pull/3879/files#diff-ec8814d27388dc311cc27d6e60b81decR246

**Comment by mathieui** [comment]
But it doesn’t change the configuration dialogs yet, so it can only be manual.

**Comment by phire** [comment]
Oh and the old config system does support per-game controller setups.

Same thing, you setup a controller profile and refer to it in the game.ini

**Comment by i30817** [comment]
Never knew.

**Comment by delroth** [comment]
I'll repeat the opinion I've already given on this change several times on IRC: it's great, but please don't have cutesy names like "OnionPetal" into our codebase. It's really hard to understand (especially if you're not familiar with the chosen metaphors) and there are already technical terms for what this is doing (like... overlays, layers, probably others I can't think of right now).

**Comment by leoetlino** [comment]
Superseded by newer config PRs (+ I don't think it'll be fun to rebase this PR...)

**Pull request closed without merging**
