### PR TITLE
Update mbed TLS (PolarSSL)

### PR DESCRIPTION
**Pull request by Tilka**
After PolarSSL was bought by ARM last year, they renamed it to "mbed TLS", changed the license from GPLv2+ to Apache 2.0, and released a new major version that broke backwards compatibility.

Definitely needs some testing.

Fixes [issue 8976](https://bugs.dolphin-emu.org/issues/8976).

### CODE REVIEW

**Comment by JMC47** [comment]
Connecting to Wiimmfi still works with this build.

**Comment by Tilka** [comment]
The "adapt Dolphin code" commit is the main commit that needs to be reviewed.

**Comment by sepalani** [comment]
I can't go online using this build, I keep getting 20100 error code. I tried with Wiimmfi, local altwfc and they both raise the error code 20100 when using this branch. When I use Dolphin 4.0-5378, it works normally.

Altwfc didn't log a single connection attempt when I used this build which is very strange.

Here is the debug log:
```
58:19:475 IPC_HLE\WII_IPC_HLE_Device_net.cpp:349 I[WII_IPC_NET]: NET_NCD_MANAGE: Open
58:19:476 IPC_HLE\WII_IPC_HLE_Device_net.cpp:406 I[WII_IPC_NET]: NET_NCD_MANAGE: IOCTLV_NCD_GETLINKSTATUS
58:19:477 IPC_HLE\WII_IPC_HLE_Device_net.cpp:357 I[WII_IPC_NET]: NET_NCD_MANAGE: Close
58:19:481 IPC_HLE\WII_IPC_HLE_Device_net.cpp:574 I[WII_IPC_NET]: NET_IP_TOP: Open
58:19:486 IPC_HLE\WII_IPC_HLE_Device_net.cpp:66 I[WII_IPC_WC24]: NET_KD_REQ: Open
58:19:488 IPC_HLE\WII_IPC_HLE_Device_net.cpp:111 I[WII_IPC_WC24]: NET_KD_REQ: IOCTL_NWC24_STARTUP_SOCKET - NI
58:19:489 IPC_HLE\WII_IPC_HLE_Device_net.cpp:74 I[WII_IPC_WC24]: NET_KD_REQ: Close
58:19:505 IPC_HLE\WII_IPC_HLE_Device_net.cpp:1235 I[WII_IPC_NET]: IOCTLV_SO_GETINTERFACEOPT(0000FFFE, 00001003, 0, 4, 0) BufferIn: (13578500, 8), BufferIn2: (00000000, 0) 
58:19:515 IPC_HLE\WII_IPC_HLE_Device_net.cpp:873 I[WII_IPC_NET]: IOCTL_SO_GETHOSTID (BufferIn: (00000000, 0), BufferOut: (00000000, 0)
'DolphinD.exe' (Win32): Loaded 'C:\Windows\System32\dhcpcsvc.dll'. Symbols loaded.
'DolphinD.exe' (Win32): Loaded 'C:\Windows\System32\dhcpcsvc6.dll'. Symbols loaded.
58:19:603 IPC_HLE\WII_IPC_HLE_Device_net.cpp:66 I[WII_IPC_WC24]: NET_KD_REQ: Open
58:19:604 IPC_HLE\WII_IPC_HLE_Device_net.cpp:94 I[WII_IPC_WC24]: NET_KD_REQ: IOCTL_NWC24_SUSPEND_SCHEDULAR - NI
58:19:605 IPC_HLE\WII_IPC_HLE_Device_net.cpp:74 I[WII_IPC_WC24]: NET_KD_REQ: Close
58:19:611 IPC_HLE\WII_IPC_HLE_Device_net.cpp:66 I[WII_IPC_WC24]: NET_KD_REQ: Open
58:19:614 IPC_HLE\WII_IPC_HLE_Device_net.cpp:134 I[WII_IPC_WC24]: NET_KD_REQ: IOCTL_NWC24_REQUEST_GENERATED_USER_ID
58:19:616 IPC_HLE\WII_IPC_HLE_Device_net.cpp:74 I[WII_IPC_WC24]: NET_KD_REQ: Close
58:19:619 IPC_HLE\WII_IPC_HLE_Device_net.cpp:66 I[WII_IPC_WC24]: NET_KD_REQ: Open
58:19:620 IPC_HLE\WII_IPC_HLE_Device_net.cpp:103 I[WII_IPC_WC24]: NET_KD_REQ: IOCTL_NWC24_EXEC_RESUME_SCHEDULAR - NI
58:19:620 IPC_HLE\WII_IPC_HLE_Device_net.cpp:74 I[WII_IPC_WC24]: NET_KD_REQ: Close
58:19:671 IPC_HLE\WII_IPC_HLE_Device_net.cpp:873 I[WII_IPC_NET]: IOCTL_SO_GETHOSTID (BufferIn: (00000000, 0), BufferOut: (00000000, 0)
58:19:716 IPC_HLE\WII_IPC_HLE_Device_net.cpp:349 I[WII_IPC_NET]: NET_NCD_MANAGE: Open
58:19:717 IPC_HLE\WII_IPC_HLE_Device_net.cpp:382 I[WII_IPC_NET]: NET_NCD_MANAGE: IOCTLV_NCD_GETCONFIG
58:19:718 IPC_HLE\WII_IPC_HLE_Device_net.cpp:357 I[WII_IPC_NET]: NET_NCD_MANAGE: Close
58:19:737 IPC_HLE\WII_IPC_HLE_Device_net.cpp:349 I[WII_IPC_NET]: NET_NCD_MANAGE: Open
58:19:738 IPC_HLE\WII_IPC_HLE_Device_net.cpp:382 I[WII_IPC_NET]: NET_NCD_MANAGE: IOCTLV_NCD_GETCONFIG
58:19:738 IPC_HLE\WII_IPC_HLE_Device_net.cpp:357 I[WII_IPC_NET]: NET_NCD_MANAGE: Close
58:20:036 IPC_HLE\WII_IPC_HLE_Device_net.cpp:349 I[WII_IPC_NET]: NET_NCD_MANAGE: Open
58:20:037 IPC_HLE\WII_IPC_HLE_Device_net.cpp:412 I[WII_IPC_NET]: NET_NCD_MANAGE: IOCTLV_NCD_GETWIRELESSMACADDRESS
58:20:037 IPC_HLE\WII_IPC_HLE_Device_net.cpp:333 I[WII_IPC_NET]: Using MAC address: 00:17:ab:5c:b9:90
58:20:037 IPC_HLE\WII_IPC_HLE_Device_net.cpp:357 I[WII_IPC_NET]: NET_NCD_MANAGE: Close
'DolphinD.exe' (Win32): Loaded 'C:\Windows\System32\mswsock.dll'. Symbols loaded.
'DolphinD.exe' (Win32): Loaded 'C:\Windows\System32\dnsapi.dll'. Symbols loaded.
'DolphinD.exe' (Win32): Loaded 'C:\Windows\System32\FWPUCLNT.DLL'. Symbols loaded.
'DolphinD.exe' (Win32): Loaded 'C:\Windows\System32\rasadhlp.dll'. Symbols loaded.
'DolphinD.exe' (Win32): Loaded 'C:\Windows\System32\wship6.dll'. Symbols loaded.
58:20:224 IPC_HLE\WII_IPC_HLE_Device_net.cpp:1445 I[WII_IPC_NET]: IOCTLV_SO_GETADDRINFO (BufferIn: (13588fc0, 14), BufferOut: (13589020, 2100)
58:20:224 IPC_HLE\WII_IPC_HLE_Device_net.cpp:1446 I[WII_IPC_NET]: IOCTLV_SO_GETADDRINFO: nas.wiimmfi.de
'DolphinD.exe' (Win32): Loaded 'C:\Windows\System32\WSHTCPIP.DLL'. Symbols loaded.
58:20:241 IPC_HLE\WII_IPC_HLE_Device_net.cpp:680 I[WII_IPC_NET]: IOCTL_SO_SOCKET Socket: 0000040c (2,1,0), BufferIn: (13588fa0, 12), BufferOut: (00000000, 0)
58:20:249 IPC_HLE\WII_Socket.cpp:98 I[WII_IPC_NET]: SO_CONNECT failed with error 0: L, ret= -1
58:20:250 IPC_HLE\WII_Socket.cpp:228 I[WII_IPC_NET]: IOCTL_SO_CONNECT (0000040c, 46.4.79.141:80)
58:20:250 IPC_HLE\WII_Socket.cpp:532 D[WII_IPC_NET]: IOCTL(V) Sock: 0000040c ioctl/v: 4 returned: -1 nonBlock: 0 forceNonBlock: 0
58:20:256 IPC_HLE\WII_IPC_HLE_Device_net.cpp:700 D[WII_IPC_NET]: IOCTL_SO_CLOSE(40c) 0
58:20:314 IPC_HLE\WII_IPC_HLE_Device_net.cpp:349 I[WII_IPC_NET]: NET_NCD_MANAGE: Open
58:20:314 IPC_HLE\WII_IPC_HLE_Device_net.cpp:412 I[WII_IPC_NET]: NET_NCD_MANAGE: IOCTLV_NCD_GETWIRELESSMACADDRESS
58:20:315 IPC_HLE\WII_IPC_HLE_Device_net.cpp:333 I[WII_IPC_NET]: Using MAC address: 00:17:ab:5c:b9:90
58:20:315 IPC_HLE\WII_IPC_HLE_Device_net.cpp:357 I[WII_IPC_NET]: NET_NCD_MANAGE: Close
58:20:323 IPC_HLE\WII_IPC_HLE_Device_net.cpp:680 I[WII_IPC_NET]: IOCTL_SO_SOCKET Socket: 0000040c (2,1,0), BufferIn: (135914c0, 12), BufferOut: (00000000, 0)
58:20:323 IPC_HLE\WII_Socket.cpp:98 I[WII_IPC_NET]: SO_CONNECT failed with error 0: L, ret= -1
58:20:324 IPC_HLE\WII_Socket.cpp:228 I[WII_IPC_NET]: IOCTL_SO_CONNECT (0000040c, 46.4.79.141:80)
58:20:324 IPC_HLE\WII_Socket.cpp:532 D[WII_IPC_NET]: IOCTL(V) Sock: 0000040c ioctl/v: 4 returned: -1 nonBlock: 0 forceNonBlock: 0
58:20:324 IPC_HLE\WII_IPC_HLE_Device_net.cpp:700 D[WII_IPC_NET]: IOCTL_SO_CLOSE(40c) 0
58:20:366 IPC_HLE\WII_IPC_HLE_Device_net.cpp:349 I[WII_IPC_NET]: NET_NCD_MANAGE: Open
58:20:367 IPC_HLE\WII_IPC_HLE_Device_net.cpp:412 I[WII_IPC_NET]: NET_NCD_MANAGE: IOCTLV_NCD_GETWIRELESSMACADDRESS
58:20:367 IPC_HLE\WII_IPC_HLE_Device_net.cpp:333 I[WII_IPC_NET]: Using MAC address: 00:17:ab:5c:b9:90
58:20:367 IPC_HLE\WII_IPC_HLE_Device_net.cpp:357 I[WII_IPC_NET]: NET_NCD_MANAGE: Close
58:20:374 IPC_HLE\WII_IPC_HLE_Device_net.cpp:680 I[WII_IPC_NET]: IOCTL_SO_SOCKET Socket: 0000040c (2,1,0), BufferIn: (135914c0, 12), BufferOut: (00000000, 0)
58:20:375 IPC_HLE\WII_Socket.cpp:98 I[WII_IPC_NET]: SO_CONNECT failed with error 0: L, ret= -1
58:20:375 IPC_HLE\WII_Socket.cpp:228 I[WII_IPC_NET]: IOCTL_SO_CONNECT (0000040c, 46.4.79.141:80)
58:20:375 IPC_HLE\WII_Socket.cpp:532 D[WII_IPC_NET]: IOCTL(V) Sock: 0000040c ioctl/v: 4 returned: -1 nonBlock: 0 forceNonBlock: 0
58:20:376 IPC_HLE\WII_IPC_HLE_Device_net.cpp:700 D[WII_IPC_NET]: IOCTL_SO_CLOSE(40c) 0
58:20:873 IPC_HLE\WII_IPC_HLE_Device_net.cpp:66 I[WII_IPC_WC24]: NET_KD_REQ: Open
58:20:874 IPC_HLE\WII_IPC_HLE_Device_net.cpp:116 I[WII_IPC_WC24]: NET_KD_REQ: IOCTL_NWC24_CLEANUP_SOCKET - NI
58:20:875 IPC_HLE\WII_IPC_HLE_Device_net.cpp:74 I[WII_IPC_WC24]: NET_KD_REQ: Close
58:20:878 IPC_HLE\WII_IPC_HLE_Device_net.cpp:582 I[WII_IPC_NET]: NET_IP_TOP: Close
```

**Comment by JMC47** [comment]
Note:  I was on Windows.  Sorry for not specifying.

**Comment by sepalani** [comment]
@JMC47 
So am I (Windows 7 x64 Pro), I also have multiple network interfaces due to Ethernet, WiFi, VMware & VirtualBox. I tried with Ethernet (1st one) and WiFi (2nd one) but Dolphin failed again. I'm very confused. Do I have to setup specific settings in order to this PR to work?

**Comment by shuffle2** [comment]
@Parlane any idea?

**Comment by shuffle2** [comment]
@sepalani what is the output of `netsh interface show interface`? If it includes things like vmware adapters, try disabling them temporarily and see if that fixes the issue.

**Comment by shuffle2** [comment]
@sepalani also change to `WiiSockMan::DecodeError` to call `FormatMessageA` instead of `FormatMessage`

**Comment by sepalani** [comment]
@shuffle2 
Disabling interfaces which don't have the Internet doesn't solve my (compilation?) bug.

**Input:**
```
netsh interface show interface
```
**Output:**
```batch
État admin    État          Type            Nom de l'interface
-------------------------------------------------------------------------
Activé         Connecté       Dédié            Connexion réseau sans fil
Désactivé      Déconnecté     Dédié            Connexion réseau sans fil 2
Désactivé      Déconnecté     Dédié            Connexion réseau sans fil 3
Désactivé      Déconnecté     Dédié            VMware Network Adapter VMnet1
Désactivé      Déconnecté     Dédié            VirtualBox Host-Only Network
Désactivé      Déconnecté     Dédié            VMware Network Adapter VMnet8
Désactivé      Déconnecté     Dédié            Connexion réseau local
```

Here is the new debug log from **FormatMessageA** (that looks like the same as before?):
```
56:59:979 IPC_HLE\WII_IPC_HLE_Device_net.cpp:349 I[WII_IPC_NET]: NET_NCD_MANAGE: Open
56:59:981 IPC_HLE\WII_IPC_HLE_Device_net.cpp:406 I[WII_IPC_NET]: NET_NCD_MANAGE: IOCTLV_NCD_GETLINKSTATUS
56:59:982 IPC_HLE\WII_IPC_HLE_Device_net.cpp:357 I[WII_IPC_NET]: NET_NCD_MANAGE: Close
56:59:986 IPC_HLE\WII_IPC_HLE_Device_net.cpp:574 I[WII_IPC_NET]: NET_IP_TOP: Open
56:59:994 IPC_HLE\WII_IPC_HLE_Device_net.cpp:66 I[WII_IPC_WC24]: NET_KD_REQ: Open
56:59:996 IPC_HLE\WII_IPC_HLE_Device_net.cpp:111 I[WII_IPC_WC24]: NET_KD_REQ: IOCTL_NWC24_STARTUP_SOCKET - NI
56:59:997 IPC_HLE\WII_IPC_HLE_Device_net.cpp:74 I[WII_IPC_WC24]: NET_KD_REQ: Close
57:00:013 IPC_HLE\WII_IPC_HLE_Device_net.cpp:1235 I[WII_IPC_NET]: IOCTLV_SO_GETINTERFACEOPT(0000FFFE, 00001003, 0, 4, 0) BufferIn: (13578500, 8), BufferIn2: (00000000, 0) 
57:00:024 IPC_HLE\WII_IPC_HLE_Device_net.cpp:873 I[WII_IPC_NET]: IOCTL_SO_GETHOSTID (BufferIn: (00000000, 0), BufferOut: (00000000, 0)
57:00:111 IPC_HLE\WII_IPC_HLE_Device_net.cpp:66 I[WII_IPC_WC24]: NET_KD_REQ: Open
57:00:112 IPC_HLE\WII_IPC_HLE_Device_net.cpp:94 I[WII_IPC_WC24]: NET_KD_REQ: IOCTL_NWC24_SUSPEND_SCHEDULAR - NI
57:00:112 IPC_HLE\WII_IPC_HLE_Device_net.cpp:74 I[WII_IPC_WC24]: NET_KD_REQ: Close
57:00:118 IPC_HLE\WII_IPC_HLE_Device_net.cpp:66 I[WII_IPC_WC24]: NET_KD_REQ: Open
57:00:120 IPC_HLE\WII_IPC_HLE_Device_net.cpp:134 I[WII_IPC_WC24]: NET_KD_REQ: IOCTL_NWC24_REQUEST_GENERATED_USER_ID
57:00:123 IPC_HLE\WII_IPC_HLE_Device_net.cpp:74 I[WII_IPC_WC24]: NET_KD_REQ: Close
57:00:126 IPC_HLE\WII_IPC_HLE_Device_net.cpp:66 I[WII_IPC_WC24]: NET_KD_REQ: Open
57:00:127 IPC_HLE\WII_IPC_HLE_Device_net.cpp:103 I[WII_IPC_WC24]: NET_KD_REQ: IOCTL_NWC24_EXEC_RESUME_SCHEDULAR - NI
57:00:127 IPC_HLE\WII_IPC_HLE_Device_net.cpp:74 I[WII_IPC_WC24]: NET_KD_REQ: Close
57:00:184 IPC_HLE\WII_IPC_HLE_Device_net.cpp:873 I[WII_IPC_NET]: IOCTL_SO_GETHOSTID (BufferIn: (00000000, 0), BufferOut: (00000000, 0)
57:00:214 IPC_HLE\WII_IPC_HLE_Device_net.cpp:349 I[WII_IPC_NET]: NET_NCD_MANAGE: Open
57:00:216 IPC_HLE\WII_IPC_HLE_Device_net.cpp:382 I[WII_IPC_NET]: NET_NCD_MANAGE: IOCTLV_NCD_GETCONFIG
57:00:217 IPC_HLE\WII_IPC_HLE_Device_net.cpp:357 I[WII_IPC_NET]: NET_NCD_MANAGE: Close
57:00:237 IPC_HLE\WII_IPC_HLE_Device_net.cpp:349 I[WII_IPC_NET]: NET_NCD_MANAGE: Open
57:00:238 IPC_HLE\WII_IPC_HLE_Device_net.cpp:382 I[WII_IPC_NET]: NET_NCD_MANAGE: IOCTLV_NCD_GETCONFIG
57:00:238 IPC_HLE\WII_IPC_HLE_Device_net.cpp:357 I[WII_IPC_NET]: NET_NCD_MANAGE: Close
57:00:537 IPC_HLE\WII_IPC_HLE_Device_net.cpp:349 I[WII_IPC_NET]: NET_NCD_MANAGE: Open
57:00:539 IPC_HLE\WII_IPC_HLE_Device_net.cpp:412 I[WII_IPC_NET]: NET_NCD_MANAGE: IOCTLV_NCD_GETWIRELESSMACADDRESS
57:00:539 IPC_HLE\WII_IPC_HLE_Device_net.cpp:333 I[WII_IPC_NET]: Using MAC address: 00:17:ab:5c:b9:90
57:00:540 IPC_HLE\WII_IPC_HLE_Device_net.cpp:357 I[WII_IPC_NET]: NET_NCD_MANAGE: Close
57:00:713 IPC_HLE\WII_IPC_HLE_Device_net.cpp:1445 I[WII_IPC_NET]: IOCTLV_SO_GETADDRINFO (BufferIn: (13588fc0, 14), BufferOut: (13589020, 2100)
57:00:713 IPC_HLE\WII_IPC_HLE_Device_net.cpp:1446 I[WII_IPC_NET]: IOCTLV_SO_GETADDRINFO: nas.wiimmfi.de
57:00:724 IPC_HLE\WII_IPC_HLE_Device_net.cpp:680 I[WII_IPC_NET]: IOCTL_SO_SOCKET Socket: 000001bc (2,1,0), BufferIn: (13588fa0, 12), BufferOut: (00000000, 0)
57:00:731 IPC_HLE\WII_Socket.cpp:228 I[WII_IPC_NET]: IOCTL_SO_CONNECT (000001bc, 46.4.79.141:80)
57:00:731 IPC_HLE\WII_Socket.cpp:532 D[WII_IPC_NET]: IOCTL(V) Sock: 000001bc ioctl/v: 4 returned: -1 nonBlock: 0 forceNonBlock: 0
57:00:737 IPC_HLE\WII_IPC_HLE_Device_net.cpp:700 D[WII_IPC_NET]: IOCTL_SO_CLOSE(1bc) 0
57:00:798 IPC_HLE\WII_IPC_HLE_Device_net.cpp:349 I[WII_IPC_NET]: NET_NCD_MANAGE: Open
57:00:798 IPC_HLE\WII_IPC_HLE_Device_net.cpp:412 I[WII_IPC_NET]: NET_NCD_MANAGE: IOCTLV_NCD_GETWIRELESSMACADDRESS
57:00:798 IPC_HLE\WII_IPC_HLE_Device_net.cpp:333 I[WII_IPC_NET]: Using MAC address: 00:17:ab:5c:b9:90
57:00:799 IPC_HLE\WII_IPC_HLE_Device_net.cpp:357 I[WII_IPC_NET]: NET_NCD_MANAGE: Close
57:00:806 IPC_HLE\WII_IPC_HLE_Device_net.cpp:680 I[WII_IPC_NET]: IOCTL_SO_SOCKET Socket: 000001bc (2,1,0), BufferIn: (135914c0, 12), BufferOut: (00000000, 0)
57:00:807 IPC_HLE\WII_Socket.cpp:228 I[WII_IPC_NET]: IOCTL_SO_CONNECT (000001bc, 46.4.79.141:80)
57:00:807 IPC_HLE\WII_Socket.cpp:532 D[WII_IPC_NET]: IOCTL(V) Sock: 000001bc ioctl/v: 4 returned: -1 nonBlock: 0 forceNonBlock: 0
57:00:807 IPC_HLE\WII_IPC_HLE_Device_net.cpp:700 D[WII_IPC_NET]: IOCTL_SO_CLOSE(1bc) 0
57:00:848 IPC_HLE\WII_IPC_HLE_Device_net.cpp:349 I[WII_IPC_NET]: NET_NCD_MANAGE: Open
57:00:848 IPC_HLE\WII_IPC_HLE_Device_net.cpp:412 I[WII_IPC_NET]: NET_NCD_MANAGE: IOCTLV_NCD_GETWIRELESSMACADDRESS
57:00:848 IPC_HLE\WII_IPC_HLE_Device_net.cpp:333 I[WII_IPC_NET]: Using MAC address: 00:17:ab:5c:b9:90
57:00:848 IPC_HLE\WII_IPC_HLE_Device_net.cpp:357 I[WII_IPC_NET]: NET_NCD_MANAGE: Close
57:00:856 IPC_HLE\WII_IPC_HLE_Device_net.cpp:680 I[WII_IPC_NET]: IOCTL_SO_SOCKET Socket: 000001bc (2,1,0), BufferIn: (135914c0, 12), BufferOut: (00000000, 0)
57:00:857 IPC_HLE\WII_Socket.cpp:228 I[WII_IPC_NET]: IOCTL_SO_CONNECT (000001bc, 46.4.79.141:80)
57:00:857 IPC_HLE\WII_Socket.cpp:532 D[WII_IPC_NET]: IOCTL(V) Sock: 000001bc ioctl/v: 4 returned: -1 nonBlock: 0 forceNonBlock: 0
57:00:858 IPC_HLE\WII_IPC_HLE_Device_net.cpp:700 D[WII_IPC_NET]: IOCTL_SO_CLOSE(1bc) 0
57:01:350 IPC_HLE\WII_IPC_HLE_Device_net.cpp:66 I[WII_IPC_WC24]: NET_KD_REQ: Open
57:01:351 IPC_HLE\WII_IPC_HLE_Device_net.cpp:116 I[WII_IPC_WC24]: NET_KD_REQ: IOCTL_NWC24_CLEANUP_SOCKET - NI
57:01:352 IPC_HLE\WII_IPC_HLE_Device_net.cpp:74 I[WII_IPC_WC24]: NET_KD_REQ: Close
57:01:353 IPC_HLE\WII_IPC_HLE_Device_net.cpp:582 I[WII_IPC_NET]: NET_IP_TOP: Close
```

Otherwise, you can also try to freeze the game using netcat on port 443 (the game mustn't be SSL Stripped like Wiimmfi/Altwfc patched games i.e. unmodified games are fine):
```bash
nc -l 443
```
It will freeze the game when trying to connect to Nintendo servers.

**Comment by shuffle2** [comment]
@sepalani so you log no longer has the `SO_CONNECT failed with error ` line...?

**Comment by sepalani** [comment]
@shuffle2 
Indeed, I didn't noticed it.

Concerning my compilation "bug", the latest working version I tested was : Dolphin Debug 4.0-7528. I tried several debug builds and the bug happens in Dolphin Debug 4.0-7538. So there is a change between those that breaks/changes something. I'm going to investigate this PR https://github.com/dolphin-emu/dolphin/pull/2762 modifications.

**Comment by shuffle2** [comment]
@sepalani please file a bug on bugs.dolphin-emu.org and we can talk about it there. seems unrelated to this commit.

**Comment by sepalani** [comment]
It seems with PolarSSL the socket is non-blocking by default which makes the read non-blocking. While for some reason in mbedTLS, the socket is now blocking the read (by default?). I assume ```mbedtls_net_set_nonblock``` should solve the issue.

**Comment by Tilka** [comment]
@shuffle2 FYI, I was stringing random characters together until it compiled.

**Comment by shuffle2** [comment]
Linus would be proud

**Comment by sepalani** [comment]
@shuffle2 
@Tilka 
LBTM, see PR https://github.com/dolphin-emu/dolphin/pull/3132

**Comment by KAMiKAZOW** [comment]
"make install" wants to install loads of mbedtls header files. See https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Fedora/dolphin-emu/Fedora_22/x86_64
Are those really needed for Dolphin to run?

**Pull request merged**
