### PR TITLE
State: Avoid Global System Accessor

### PR DESCRIPTION
**Pull request by mitaclaw**

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
This isn't really deglobalizing anything, State.cpp still has global state that multiple instances of System would fight over.

**Comment by mitaclaw** [comment]
I see that `PowerPC::Cache` is accessing System through the global accessor, and can address that in another PR. `Wiimote::DoState` and `Gecko::DoState` I'm less confident I would know how to refactor those. Of course, the elephant in the room is `g_video_backend` participating in `DoState`. Still, isn't it a step in the right direction? I'm trying to bubble as many `Core::System::GetInstance()` uses up through functions until they reach the source of the problem, usually MainWindow.cpp, MainAndroid.cpp, or DolphinNoGUI.

**Comment by mitaclaw** [comment]
I just realized this PR conflicts with #12619 also authored by me. How I did that without noticing is beyond me. I think I will combine them under this PR.

**Comment by mitaclaw** [comment]
On closer inspection, I am unsure about simply copying the changes from #12619 because the `s_load_or_save_in_progress_mutex` currently is being locked *before* `Core::RunOnCPUThread` is called in SaveAs and LoadAs. I will be marking #12619 as a draft and leaving this PR as-is.

**Pull request merged**
