### PR TITLE
Remove unused initializers

### PR DESCRIPTION
**Pull request by tygyh**

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
This seems backwards. Leaving something accidentally uninitialized on some code path is a very classic C/C++ bug.

**Comment by tygyh** [comment]
> This seems backwards. Leaving something accidentally uninitialized on some code path is a very classic C/C++ bug.

But the variables are all given values before being used. You are guarding against some possible future bug which might never come.

**Comment by mitaclaw** [comment]
Yes, these are guarding against some possible future bug which may or may not ever come. An optimizing compiler can eliminate trivial [dead stores](https://en.wikipedia.org/wiki/Dead_store), so no problem here.

**Comment by Tilka** [comment]
No to this one.

**Pull request closed without merging**
