### PR TITLE
Add "Enable Controller Input" Checkbox on TAS dialogs

### PR DESCRIPTION
**Pull request by rukai**
wx used to display physical controller inputs in the TAS dialogs, this was cool but it broke TAS inputs when you had a controller plugged in that sent inputs in the background e.g. GC -> Wii U adapter or a regular controller with background input enabled.

This PR restores that functionality without background inputs causing problems by using a checkbox.
The same checkbox also allows the user to swap between input by TAS and input by physical controller.

Thanks to @spycrab for the initial attempt. You can close your existing PR.

use_tas_checkbox2

### CODE REVIEW

**Comment by JosJuice** [comment]
I think the wording "Use TAS" makes it too hard to understand what the option is supposed to be doing. "Use TAS Input" would be much better.

**Comment by rukai** [comment]
Fair enough. It was in an effort to conserve space on the GC TAS Dialog. Users could potentially have 4 of these TAS dialogs on screen at once.

If you want me to rename to "Use TAS Input", then I will move it to a separate line on the GC TAS dialog?

**Comment by JosJuice** [comment]
Having it on a separate line sounds fine. Alternatively, if you would prefer to have something as short as "Use TAS", I think "Enable" would work.

**Comment by JosJuice** [comment]
No, I mean "Enable", not "Enable TAS". The important thing is that it doesn't say "TAS" without "Input" afterwards.

**Comment by rukai** [comment]
Oh, my bad.
I need the "T" or at least some unique letter for the shortcut.
So I'll just stick it on a newline and call it "Enable TAS Input".

**Comment by spycrab** [comment]
Please take a look at [this](https://forums.dolphin-emu.org/Thread-feedback-required-what-benefits-are-there-to-the-wxwidgets-gui?pid=474341#pid474341) now.

**Comment by Techjar** [comment]
To amend to what spycrab linked, I think the best solution to this would be to drop the checkbox idea, and instead do it based on previous controller state. So as long as no buttons or axes on the controller are touched, use the TAS window, otherwise override whatever value(s) changed on the controller.

**Comment by rukai** [comment]
I'm looking into making it a QComboBox with an auto option.

**Comment by Techjar** [comment]
The issue with background input is why I suggested having the TAS input store the last controller state, and then have the TAS input override the controller values as long as the state of the real controller doesn't change.

**Comment by Techjar** [comment]
I did some quick testing already and, at least with my GC controllers, the axes will stay at one value as long as I don't touch it.

**Comment by rukai** [comment]
My gamecube controllers with GC -> Wii U adapter sometimes jitter between 2 values when left idle.

**Comment by Techjar** [comment]
Well, it might not work on everyone's hardware, but it will on more than it does now (which is none).

**Comment by rukai** [comment]
qt_tas_use_thingy_finished

All feedback should now be addressed.
The code should be re-reviewed as there has been significant changes since the last review.

This PR now adds an 'Enable Controller Input' checkbox to TAS dialogs.
*   When disabled: only inputs from TAS dialog are used.
*   When enabled: inputs from TAS dialog are used, except when a change in input is detected from a real controller, in this case the TAS value is replaced with the real controller value.

When the checkbox is ticked analog values may reset to controller values at random, due to jitter on control sticks/triggers.
To avoid users getting confused by this behavior:
*   The checkbox label includes a warning
*   The checkbox is disabled by default.

**Pull request merged**
