### PR TITLE
Android: Update the gradle file to use android studio 2.2 cmake.

### PR DESCRIPTION
**Pull request by degasus**
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4252)

### CODE REVIEW

**Comment by degasus** [comment]
@sigmabeta May you review this PR please?

**Comment by sigmabeta** [comment]
It looks good to me. I'm gonna take a quick minute to attempt a build before I pass the review, though.

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Android/app/build.gradle, line 78 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4252#-KSiUq03TCNLfr-Dc3wO:-KSiUq03TCNLfr-Dc3wP:b-jftjti) ([raw file](https://github.com/dolphin-emu/dolphin/blob/6ce13895bbebff6dbe493bb694027f5281f2e235/Source/Android/app/build.gradle#L78)):*
> ```Gradle
>     // of product flavors are paid vs. free, ARM vs. x86, etc.
>     productFlavors {
>         dolphin {
> ```

If we're not actually differentiating flavors anymore, it's a good idea to do away with the entire `productFlavors` block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4252#-:-KSiV6OFQEbnHQS5Mqol:b-858bl3)*

**Comment by sigmabeta** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Source/Android/app/build.gradle, line 68 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4252#-KSiVrDlhQH8rrg5NWUv:-KSiVrDlhQH8rrg5NWUw:by4z40t) ([raw file](https://github.com/dolphin-emu/dolphin/blob/6ce13895bbebff6dbe493bb694027f5281f2e235/Source/Android/app/build.gradle#L68)):*
> ```Gradle
>         externalNativeBuild {
>             cmake {
>                 //arguments "-DANDROID_TOOLCHAIN=gcc"
> ```

I'd either get rid of this comment or explain why it  might be necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4252)*

**Comment by sigmabeta** [comment]
LGTM - build works, a few tiny nitpicks but otherwise this is all stuff that needs to be done.

---

Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4252#-:-KSiXrCwK1XNO2GqZS09:b-tieqh2)*

**Comment by sigmabeta** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4252)*

**Comment by shuffle2** [comment]
is this uh, supposed to fail on the android buildslave?

**Comment by degasus** [comment]
@shuffle2 No, it's not. It needs manual interaction on the android buildbot. I'm waiting for the end of @delroth vacation.

**Comment by degasus** [comment]
This must be merged together with https://github.com/dolphin-emu/sadm/pull/63

---

Review status: 6 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Android/app/build.gradle, line 68 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4252#-KSiVrDlhQH8rrg5NWUv:-KTLpQuz8Re6C91GqTcu:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/6ce13895bbebff6dbe493bb694027f5281f2e235/Source/Android/app/build.gradle#L68)):*
<details><summary><i>Previously, sigmabeta (Eder) wrote…</i></summary>
> I'd either get rid of this comment or explain why it  might be necessary.
</details>
Done.

---

*[Source/Android/app/build.gradle, line 78 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4252#-KSiUq03TCNLfr-Dc3wO:-KTLpSWXPVNaCP8TEJqA:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/6ce13895bbebff6dbe493bb694027f5281f2e235/Source/Android/app/build.gradle#L78)):*
<details><summary><i>Previously, sigmabeta (Eder) wrote…</i></summary>
> If we're not actually differentiating flavors anymore, it's a good idea to do away with the entire `productFlavors` block.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4252#-:-KTLpMRs-_NUlwXJwNZg:b-uye4bf)*

**Comment by RisingFog** [comment]
Builds fine with Android Studio 2.2 on Windows (using assembleDebug).

**Comment by degasus** [comment]
@SeannyM @sigmabeta - This PR breaks the gamelist on mobile devices. Android TV is still fine. But I have no clue why. As you're by far more in the android UI, do you have an idea how this could broke?

**Comment by JosJuice** [comment]
To clarify, the non-TV game list now always acts as if there are no games.

**Comment by sigmabeta** [comment]
I have some time today and I can investigate why this is happening.

**Comment by degasus** [comment]
Thanks

**Comment by sigmabeta** [comment]
PR with the fix open here: https://github.com/dolphin-emu/dolphin/pull/4325

(worth noting, on my phone I can't launch any games, a JNI method  error occurs and I'm not quite good enough to figure that one out instantly.)

**Comment by SeannyM** [comment]
Something I noticed, the buildbot builds all have 5.0-995 as their build number since this was merged. I haven't compiled myself yet (just got home) but I'm assuming this is a buildbot problem.

**Comment by JosJuice** [comment]
Good catch. I've been having the same problem when compiling locally (except it was claiming to be a different version).

**Pull request merged**
