### PR TITLE
replace zlib with zlib-ng

### PR DESCRIPTION
**Pull request by shuffle2**
similar crc32 perf to #10882 , but this fork can be made a submodule and has more optimizations throughout other parts of their codebase (notably for zlib compress as well as decompress).

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
Did you mean to include the last two commits here?

**Comment by shuffle2** [comment]
yes

**Comment by AdmiralCurtiss** [comment]
How exactly is `USE_SHARED_LIBPNG` related to zlib, then...?

**Comment by shuffle2** [comment]
it's needed for me to build with cmake

**Comment by AdmiralCurtiss** [comment]
Okay, gave this a look-over. Seems fine to me except for one thing: As far as I can tell, the zlib-ng CMakeLists.txt only builds the static zlib (which is probably intended) because other external project we use (cubeb, glslang, pugixml, maybe something else) sets `BUILD_SHARED_LIBS` to OFF by default. If you didn't include those projects, `BUILD_SHARED_LIBS` would be undefined, and it would build both a static and shared lib instead.

We should probably make that explicit. I suggest adding a `option(BUILD_SHARED_LIBS "Build shared library" OFF)` in our zlib-ng CMakeLists.txt wrapper.

**Comment by AdmiralCurtiss** [comment]
(To be clear, I think this is poor behavior of zlib-ng -- an undefined `BUILD_SHARED_LIBS` should be treated the same as OFF based on what I can find in the CMake documentation. That its CMakeLists.txt treats it differently is questionable, but we have to deal with it if we don't want a completely custom CMakeLists.txt for it.)

**Comment by AdmiralCurtiss** [comment]
Oh and also, do you want to set the `shallow = true` for the submodule?

**Comment by shuffle2** [comment]
> BUILD_SHARED_LIBS stuff
yea sounds good

> Oh and also, do you want to set the `shallow = true` for the submodule?

sure. tbh i haven't checked if it actually ...works? I always seem to have to put it manually, git does not insert it itself (even when submodule is created with depth=1 or something)

**Comment by AdmiralCurtiss** [comment]
Hm, apparently `shallow = true` only works if you initially clone with `git clone --recurse-submodules`. `git submodule update` does fetch everything regardless. That's silly...

**Comment by shuffle2** [comment]
i also dropped the libpng cmake change

**Comment by shuffle2** [comment]
(only updated Externals/licenses.md for zlib-ng)

**Review by AdmiralCurtiss — APPROVED** [review]

**Comment by theofficialgman** [comment]
since I can't create a bug report I will report this directly here

@shuffle2 since the merge of this PR. building dolphin installs zlibng over the system zlib, breaking multiple other applications that depend on the functional system zlib

**Comment by AdmiralCurtiss** [comment]
Can you clarify? What system/distribution/version and how exactly are you building dolphin? The default settings should only build a static zlib-ng that gets linked directly into the dolphin binary, which shouldn't affect any other program.

**Comment by theofficialgman** [comment]
ubuntu bionic 18.04. using system libs whenever possible which is why only the required submodules are pulled.
This was reported to me by a user and I needed to replicate myself which is why I took a while to respond.
```
git clone https://github.com/dolphin-emu/dolphin
cd dolphin
git submodule update --init Externals/mGBA
git submodule update --init Externals/spirv_cross
git submodule update --init Externals/zlib-ng
git submodule update --init Externals/libspng 
mkdir -p build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-mcpu=native -DCMAKE_C_FLAGS=-mcpu=native -DCMAKE_C_FLAGS_INIT="-static" -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11
make -j$(nproc)
sudo make install
```

I see that during the make install, `libz.a` is copied to `/usr/local/lib/libz.a` which is not static at all

and you can see here in the CMakeCache.txt that it isn't static either

```
//Value Computed by CMake
zlib_BINARY_DIR:STATIC=/home/garrett/dolphin/build/Externals/zlib-ng/zlib-ng

//Value Computed by CMake
zlib_IS_TOP_LEVEL:STATIC=OFF
```

you can see the file output before installing dolphin:
```
garrett@garrett-usb:~$ file /usr/local/lib/libz.a
/usr/local/lib/libz.a: cannot open `/usr/local/lib/libz.a' (No such file or directory)
```
and after installing dolphin
```
garrett@garrett-usb:~$ file /usr/local/lib/libz.a
/usr/local/lib/libz.a: thin archive with 197 symbol entries
```

```
-- Installing: /usr/local/lib/libz.a
```

**Comment by shuffle2** [comment]
that's unfortunate @theofficialgman  :( 

fwiw we are just calling into zlib-ng's cmake file: https://github.com/zlib-ng/zlib-ng/blob/develop/CMakeLists.txt , and only expect it to be building a static library, which should not get installed along with dolphin.

**Pull request merged**
