### PR TITLE
Various icon improvements

### PR DESCRIPTION
**Pull request by spycrab**

### CODE REVIEW

**Comment by JMC47** [comment]
Still is weird, but, here.

image

**Comment by riking** [comment]
To get proper centering, should generate a version of https://github.com/dolphin-emu/dolphin/blob/master/Data/Sys/Resources/dolphin_logo%402x.png padded to square 1:1 aspect ratio.

**Comment by spycrab** [comment]
@JMC47 Should look normal now!

**Comment by JMC47** [comment]
Finally works!!

**Pull request merged**
