### PR TITLE
VideoCommon: force display list alignment

### PR DESCRIPTION
**Pull request by Tilka**
This fixes the shadows in "Wallace & Gromit in Project Zoo".

### CODE REVIEW

**Comment by JosJuice** [comment]
Please also remove the patch from ApprovedInis.json.

**Comment by Tilka** [comment]
Tests pass locally with a LINUX_LOCAL_DEV symlink. Do the buildbot workers use an unrelated Sys directory?

**Comment by JosJuice** [comment]
I'm guessing they copy all existing files from the checked-out Sys folder to the build folder's Sys folder, but neglect to delete old files from the build folder's Sys folder. (I wrote about this on IRC when I saw the build failure – I guess you didn't see it?)

**Comment by Pokechu22** [comment]
I assume that the game is calling `GXBeginDispList` and `GXCallDispList` with a non-32-byte aligned pointer, and it mostly gets away with it because both `PI_FIFO_BASE` and the call display list command end up truncating it to 32 byte alignment? (With the only problem being that data immediately before the display list would get clobbered.)

**Comment by JosJuice** [comment]
PR #13011 aims to fix the unit test problems that this PR has run into.

**Review by Pokechu22 — APPROVED** [review]
Untested, but looks good to me and seems like a reasonable change.

**Comment by dreamsyntax** [comment]
This PR causes vertex explosions and other graphical defects in a Luigi's Mansion romhack.
It potentially could be affecting other normal games.

Backend choice has no change, it applies to all.

2407-225 (before this PR)
image


2407-228 (this PR)
image

**Comment by Pokechu22** [comment]
Has that romhack been tested on real hardware? It seems plausible that a romhack could end up relying on emulation inaccuracies.

That fifolog plays back correctly on Dolphin 2409 and on real hardware with the [hardware fifoplayer](https://github.com/pokechu22/fifoplayer/tree/improved), but the fifo recorder inlines display lists so if you recorded it on 2407-225 then it'll play back on all versions. (See #9704 and #12292). The hardware fifoplayer also remaps memory and might end up forcing alignment.

**Comment by dreamsyntax** [comment]
@Pokechu22 we're talking about it on the discord. I just uploaded a 2nd fifolog that was recorded on 2409-59. My bad for not checking the initial capture, I assumed it wouldn't matter which Dolphin it was captured on.

**Comment by dreamsyntax** [comment]
Last update on this for me,
Did another capture on 2407-228 and the result is the same (GPU Unknown Opcode) as 2409+.

Per flacs:
> anyway, let's not waste time on dolphin-only mods

So no need to continue investigation.
Thanks for testing.

**Pull request merged**
