### PR TITLE
Add i18n comments for the acronym IR

### PR DESCRIPTION
**Pull request by JosJuice**

### CODE REVIEW

**Comment by JosJuice** [comment]
In case you're wondering about the big reformatting in HotkeyManager: It wasn't me, it was clang-format. The only change I made was adding comments.

**Comment by leoetlino** [comment]
Can we disable clang-format for that particular table? I don't think it's a good idea to put that many entries on the same line... Imagine having to add/remove/reorder one entry and going through the diff to figure out what changed.

**Comment by BhaaLseN** [comment]
You can, using comments: https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Core/DSP/DSPTables.cpp#L23
And just noticed this, `vertex_rounding_desc` uses two spaces after punctation; I think we should at least make this consistent across all the strings?

**Comment by JosJuice** [comment]
@BhaaLseN The spaces are fixed in PR #5227.

**Pull request merged**
