### PR TITLE
[Gameini] Serious Sam: Next Encounter

### PR DESCRIPTION
**Pull request by vlad54rus**
Game works perfectly on Dolphin 5.0. It does not need 'EFB to RAM' anymore.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4199)

### CODE REVIEW

**Comment by RisingFog** [comment]
@dolphin-emu-bot rebuild

**Comment by RisingFog** [comment]
@JMC47 can you confirm if this is the case?

**Comment by JMC47** [comment]
I do not have the game so I cannot confirm.  @vlad54rus, can you explain real quick the scenario in which it required EFB Copies to RAM before?

**Comment by vlad54rus** [comment]
Without EFB to RAM, camera transition scenes doesnt worked. In 5.0-release all works correctly without hacks. Just look at video: http://youtu.be/hN2NgkaxoHM

**Comment by JMC47** [comment]
What build did efb to ran get required?

**Comment by vlad54rus** [comment]
4.0.2-release and any earlier versions required EFB to RAM. This isuue has been fixed before 5.0 was released, i dont know which build introdused this fix.

**Comment by JMC47** [comment]
Oh, this is removal of EFB Copies to RAM requirement.

Sorry, I misread.  That's fine then.

**Pull request merged**
