### PR TITLE
Vulkan: Fix library load failure on Android

### PR DESCRIPTION
**Pull request by stenzek**
Regression from #7869.

### CODE REVIEW

**Comment by stenzek** [comment]
This also fixes the crash on Mesa due to querying subgroup operation support.

**Comment by brujo5** [comment]
few users with shield tv Still failed to initialize vulkan backend.

here info https://forums.dolphin-emu.org/Thread-vulkan-failed-to-initialize-video-backend-in-doplphin-5-0-9846

**Comment by stenzek** [comment]
Sounds like it's an instance issue, so it's loading the library, but not getting any further. Can't say much more without a log.

**Comment by Sanmorin** [comment]
Here is log
[dolphin.log](https://github.com/dolphin-emu/dolphin/files/3039077/dolphin.log)

**Pull request merged**
