### PR TITLE
Disable pinned memory for AMD mesa drivers

### PR DESCRIPTION
**Pull request by z0z0z**
Very sorry for multiple PRs I'm not good with git. I'm almost sure this is correct this time though.

Pinned memory causes a massive performance drop on my system using mesa with AMD cards.

### CODE REVIEW

**Comment by Krakn** [comment]
Which card(s) exhibit regressions when using pinned memory?

I assume it affects all games?

**Comment by z0z0z** [comment]
RX460 and an older 6850 card.

It effects some games more than others, Smash Bros Melee for example doesn't have it nearly as bad as some other games, but yes I believe it's all games. Sonic Adventure 2's opening cutscene was something I used to test it with, where the difference is huge.

Basically unplayable with it enabled, about 10-20fps in a 60fps game, and without it enabled getting 60fps with no framedrops.

Using mesa built from git (happens with older versions), and Linux 4.10.0

**Comment by JMC47** [comment]
@dolphin-emu-bot rebuild

**Comment by ds84182** [comment]
After updating to the latest mesa I went from 30-60fps in Kirby Air Ride City Trial to almost full 60fps at all times.

**Comment by stenzek** [comment]
@ds84182 Is that with or without this PR?

I'm wondering if it's worth introducing a different driverdetails bug for this, as the BROKEN_PINNED_MEMORY bug refers to broken index buffers, not performance issues with both vertex and index buffers (which appears to be the case here?).

**Comment by z0z0z** [comment]
Feel free to edit whatever you want or just make your own commit and close this. I don't care about any recognition.

I would just like something to be done because this has been quite a severe bug effecting me for a year now. I just didn't know what was causing the severely bad performance on my system until now. I worry that there's a lot of other users with complaints about bad performance on Linux with AMD cards who actually just need to disable pinned memory, but don't know it. You would never find out because they're just posting in forums or bug trackers with vague complaints about bad performance, and receiving tips/advice to improve performance that won't work.

**Comment by stenzek** [comment]
@z0z0z I think like you may be overstating the impact of this bug, if it is just restricted to users Mesa/AMDGPU with Polaris GPUs, and I hadn't seen any reports of performance issues prior to this (although I don't watch the forum).

I'm still wondering whether it's worth dropping the pinned memory case completely, as this patch disables it completely for the binary blob on Linux, as well as Mesa, only leaving Windows blob users (where D3D and Vulkan performance is better anyway).

If the percentage of Windows/AMD/GL users is high enough (and that comment about buffer storage being slow still holds true), LGTM.

**Comment by JMC47** [comment]
I'm fine with trying this out to see what happens.  What's the worst that happens?  We have to revert it due to some other gfx card not liking it?  Or coming up with another more specific disable?

**Comment by z0z0z** [comment]
>if it is just restricted to users Mesa/AMDGPU with Polaris GPUs

It also happened with older GPUs using the older radeon DRM driver. Yes I know this OS/GPU/Driver combo is much less common than someone using Windows/Nvidia, but it is still a severe bug for anyone experiencing this.

>I hadn't seen any reports of performance issues prior to this 

Relatively not too many users are using Linux with AMD open-source drivers, I imagine the ones that have ran into this problem just don't say anything because there's basically no point in complaining about performance if you don't already know specifically what is wrong, or have made a vague performance complaint and never found out what was causing bad performance. Like perhaps this guy:

https://forums.dolphin-emu.org/Thread-anyway-to-increase-performance-under-linux?highlight=linux

Sunshine is one of the better games with this bug, it's like Melee in that it gets almost full performance but constant bad fps drops (even with CPU and GPU set to performance mode, for GPU by setting /sys/class/drm/card0/device/power_dpm_force_performance_level (so it always run at highest clock rate)).

Other games are much worse, like Twilight Princess where you will get a much more severe impact.

If one of your developers are trying to test this and can't reproduce it, are you using recent versions of the graphics stack? What versions of the Linux kernel, mesa, llvm, xorg-server, xf86-video-amdgpu?

**Comment by z0z0z** [comment]
Here is a video of the difference I'm getting with and without pinned memory enabled. Dolphin settings are at 3x IR, 4x MSAA, x16 anisotropic filtering. 

https://a.pomf.cat/kvgovn.mp4

Some startups of Dolphin with pinned memory enabled I might get full performance, usually not.  If I close the game and start another game without restarting Dolphin with pinned memory enabled, I will usually get terrible unplayable performance. It is like a light switch that is decided everytime Dolphin is started, without disabling pinned memory it is either perfect full performance, or terrible unplayable performance.

If I disable pinned memory I get 100% full performance every single time I restart dolphin, I've restarted it over a hundred times with pinned memory disabled, every single time I get full performance. With pinned memory enabled I was lucky to get  a 1 in 10 restart with full performance.

**Comment by mirh** [comment]
You [might](https://bugs.freedesktop.org/show_bug.cgi?id=99974) want to try to ask on #mesa too.

**Comment by XMDS** [comment]
Hope can enhance the performance of the android version dophin

**Comment by mirh** [comment]
@z0z0z Marek is waiting for an answer on freedesktop

**Comment by degasus** [comment]
In my opinion, the pinned memory extension here is mostly legacy code. It was written before ARB_buffer_storage was specified. As mesa always supports buffer_storage, we should just use the better one. IIRC pinned memory is just used on Windows to avoid handling with the client and coherent flag of buffer_storage.

**Comment by mirh** [comment]
Pinned memory might have been fixed with https://github.com/mesa3d/mesa/commit/b52721e3b693e113aa537d163c8a855169e7b75d

In other news, intel is [looking into](https://patchwork.freedesktop.org/series/31897/) adding this too.

**Pull request merged**
