### PR TITLE
Fifo: fixes desync issue with movies from netplay

### PR DESCRIPTION
**Pull request by FunctionalDragon**
fixes desync issue when playing a movie recorded from netplay

### CODE REVIEW

**Comment by JosJuice** [comment]
I don't know much about this code, so I wonder: What's the reason for not simply doing this for all movies? The comment says that movies are excluded for now, but I don't understand why we would want that for movies but not netplay.

**Comment by FunctionalDragon** [comment]
I don't know much about it either, it is pretty old (Commit 6c0a68d5, from comex in 2014). If vertex arrays have been fixed then we can remove the special case but it could make older movies desync. I went with the change that seemed safest, meaning now I can play both my netplay and non-netplay movies that I had from before.

**Comment by JMC47** [comment]
Deterministic Dualcore is broken in some games.  But in the case of movies, you need determinism regardless so this check is safe imo.

The idea of doing this is fine with me, I don't know if the code/placement is correct, but, I think this is necessary.

**Comment by JosJuice** [comment]
@FunctionalDragon It can only make old movies desync if they were made with nondeterministic dual core. Such movies would desync even when played back in the same version of Dolphin as they were created in, so what you're describing isn't a problem. Besides, breaking movie compatibility happens all the time.

@JMC47 That makes sense, but if it is true, we should just remove the whole check rather than doing what this PR does.

**Comment by JMC47** [comment]
I'd be fine with removing the check.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
I've created a PR where it's removed: #4800

**Comment by PEmu1** [comment]
#4800 was merged. Is this PR still needed?

**Comment by FunctionalDragon** [comment]
@PEmu1 it's shouldn't be needed anymore (though I haven't personally tested with #4800)

**Pull request closed without merging**
