### PR TITLE
Update to mbedtls 3

### PR DESCRIPTION
**Pull request by winterheart**
Update to mbedtls 3.5.0, move mbedtls to git submodule to ease update and maintain.
Proper fix for https://bugs.dolphin-emu.org/issues/13124

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by winterheart** [comment]
Main concern that [mbedtls 2.28.x has EOL to late 2024](https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-2.28.5) and most Linux distributions will eventually switch system mbedtls to 3. While dolphin provides bundled version, this can be problem on mbedtls's security related issues.

Regarding to capping SSL version protocol - I honestly tried to reach that code in debugger with some games, but actually cannot get there. Can you please provide some use case where this code is actually reached? I see `mbedtls_ssl_conf_max_version(&ssl->config, MBEDTLS_SSL_MAJOR_VERSION_3, MBEDTLS_SSL_MINOR_VERSION_2)` was introduced in 2013, maybe at this time there no TLS 1.x capable servers?

**Comment by sepalani** [comment]
The reason why such low security standard was chosen is due to the Wii hardware limitation. Games/programs relying on the Wii's IOS SSL module can't use some SSL algorithms/versions nor modern TLS features. Enabling/enforcing higher security standard might make some games and servers unreachable since they support these legacy features.

I'm fine upgrading mbedtls as long as it doesn't prevent existing servers/services or replacement servers created by the community to be accessed.

**Comment by noahpistilli** [comment]
Looks like mbedtls [removed support for TLSv1/1.1](https://github.com/Mbed-TLS/mbedtls/issues/4286). back in 2021.

Testing with the Demae Channel which uses SSL proves this is true.
```06:59:840 Core/IOS/Network/Socket.cpp:418 E[IOS_SSL]: IOCTLV_NET_SSL_DOHANDSHAKE: SSL - Handshake protocol not within min/max boundaries```

**Comment by winterheart** [comment]
Well, obviously, this PR not going anywhere :( as main issue is SSL3 incompatibility.

For summary, there some options still available:
* Stick on mbedtls 2.28.* branch which will receive security updates until 2025
* Switch to to another SSL framework capable to work with deprecated security protocols (OpenSSL, WolfSSL, GnuTLS, ?)

**Comment by Mystro256** [comment]
Any reason it hasn't been updated to 2.28.9 already?
I can prepare a pull for updating it for good measure.

**Comment by JoshuaVandaele** [comment]
> * Switch to to another SSL framework capable to work with deprecated security protocols (OpenSSL, WolfSSL, GnuTLS, ?)

For future reference, OpenSSL plans to [remove SSLv3 support](https://github.com/openssl/project/issues/1319) soon-ish.
After a small look at plausible alternatives: [Botan](https://github.com/randombit/botan), [NSS](https://github.com/nss-dev/nss),  [GnuTLS](https://gitlab.com/gnutls/gnutls/), and [WolfSSL](https://github.com/wolfSSL/wolfssl) remain with SSLv3 support, albeit it is disabled by default for WolfSSL and GnuTLS, and is considered deprecated by WolfSSL.

**Pull request closed without merging**
