### PR TITLE
Gameini updates.

### PR DESCRIPTION
**Pull request by Linktothepast**
It removes settings that were removed from dolphin to clean up the
database. Modifies some gameinis to use the new 3 letter gameid. Adds
Hyrule field speedup hack for Japanese and American version of Twilight
Princess for wii. Removes efb to ram from Twilight Princess, Tony Hawk's
Pro Skater 3, Tony Hawk's Pro Skater 4, Prince of Persia Forgotten
Sands, Mario Superstar Baseball, Okami, FFCC the Crystal Bearers and The
Simpsons due to the recent dolphin changes. Enables efb to ram for The
Magic Obelisk because it needs it and some more minor changes.
Fixes issues 8147, 8181, 8194.

### CODE REVIEW

**Comment by Linktothepast** [comment]
It probably needs https://code.google.com/p/dolphin-emu/issues/detail?id=8258 to be fixed first for this to work properly with the buildbot.

**Comment by JosJuice** [comment]
This PR seems to change line endings of files from LF to CRLF. Is that intentional?

**Comment by Linktothepast** [comment]
No, that wasn't intentional, they were that way when i edited them. JosJuice can i upload the gameinis somewhere and do this pr in my place, seems i have git issues.

**Comment by Linktothepast** [comment]
Here are the gameinis: https://www.mediafire.com/?7909kqv7wjgv99p if you could make the pr properly in my place i would be grateful, just replace all ini files in the directory with them and don't copy paste them since there are ini deletions inside too.

**Comment by JosJuice** [comment]
Sure, I can do that. I'll use the files in this PR since they are the same as the ones in the download, and just fix the line endings and the merge conflicts.

**Comment by Linktothepast** [comment]
Ok thanks!

**Comment by JosJuice** [comment]
Oh, your repository hasn't been updated in a while... That combined with my recent PR is why there are so many merge conflicts. I'll take care of it for this PR, but you'll need to update your repository with the latest changes from master before the next time you make a commit/PR.

**Pull request closed without merging**
