### PR TITLE
NANDContentLoader: Minor changes

### PR DESCRIPTION
**Pull request by lioncash**
Commit messages tell all.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4214)

### CODE REVIEW

**Comment by Warepire** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/DiscIO/NANDContentLoader.cpp, line 112 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4214#-KRjIzbemsS9kxNIHb-1:-KRjIzbfJVQFWd_SiQL-:b-xzln9c) ([raw file](https://github.com/dolphin-emu/dolphin/blob/4c004b6dc978d7585bf0765e22351ef1edd39a3a/Source/Core/DiscIO/NANDContentLoader.cpp#L112)):*
> ```cpp
> const std::vector<u8> CNANDContentDataFile::Get()
> {
>   std::vector<u8> result;
> ```

Won't this disqualify the function from being RVO'd? Or is that irrelevant for this function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4214)*

**Comment by lioncash** [comment]
*[Source/Core/DiscIO/NANDContentLoader.cpp, line 112 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4214#-KRjIzbemsS9kxNIHb-1:-KRjpdnTUIP9A5bxAYWr:b-gssxwp) ([raw file](https://github.com/dolphin-emu/dolphin/blob/4c004b6dc978d7585bf0765e22351ef1edd39a3a/Source/Core/DiscIO/NANDContentLoader.cpp#L112)):*
<details><summary><i>Previously, Warepire wrote…</i></summary>
> Won't this disqualify the function from being RVO'd? Or is that irrelevant for this function?
</details>
That's pretty much compiler-dependent on the optimizer, so I'd consider it irrelevant.

Constructing vectors when the data size is known is generally much better than doing a construction and then resizing, however (very trivial demo [here](https://godbolt.org/g/t0lnkA))

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4214)*

**Comment by JosJuice** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4214)*

**Comment by Warepire** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4214)*

**Pull request merged**
