### PR TITLE
Reorder the Tools menu, with more separators

### PR DESCRIPTION
**Pull request by FRtranslator**
Reorder the Tools menu.
As many options appeared, it had to be reordered a bit ;)

### CODE REVIEW

**Comment by sepalani** [comment]
TBH, I would have ordered them the following way:

- Memory
  * _("&Memory Card Manager (GC)")
  * _("Import Wii Save...")
  * _("Export All Wii Saves"));
- Cheat/Netplay/Misc?
  * _("&Cheat Manager")
  * _("Start &NetPlay...")
  * _("FIFO Player")); // Or somewhere after System Menu
- System Menu
  *  _("Install WAD...")
  * (IDM_LOAD_WII_MENU, dummy_string);
  * _("Import BootMii NAND Backup..."));
  * _("Extract Certificates from NAND")); 
- Is a Separator needed?
  * _("Connect Wii Remotes"));

@FRtranslator could you justify your choice. I don't think my taste matters a lot because I consider myself to have a pretty bad one. However, I'm curious concerning your motivations for this change.

**Comment by FRtranslator** [comment]
@sepalani your choice is better for the game backups. I have updated the commit.

**Comment by BhaaLseN** [comment]
You can use `git rebase -i origin/master` (just in case, after you did `git fetch origin` first); this will open a text editor for you. If you're still in the command line, its most likely vim; so move your cursor to all lines that read "pick", starting with the *second* one (not the first one) and change them to "fixup". You can do that by hitting I (to go into Insert mode), then you type, then hit Escape to get out of insert mode. Once you're done, save and close the file by typing `:wq`. Check your history (using gitk for example) to verify this is what you want. If yes, `git push -f` (which overwrites your branch on your fork); if no do `git reset --hard FRtranslator/Tools_menu_reorder` and start over.
The PR updates automatically after the push.

**Comment by FRtranslator** [comment]
Thanks BhaaLseN for your help!
Do I still need to do something, or should I just wait for someone to merge the PR?

**Comment by JosJuice** [comment]
Commit 3691df8 still exists on here. Maybe you forgot to do `git push -f`?

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
