### PR TITLE
TextureConversionShader: Fix compile errors in OpenGL ES

### PR DESCRIPTION
**Pull request by stenzek**
Regression from #6369.

Could someone please confirm this fixes the compile errors on Android?

### CODE REVIEW

**Comment by degasus** [comment]
LGTM

**Comment by Latiosdude** [comment]
Doesn't fix the issue on Wind Waker. Other games I've tried (Melee, Twilight Princess) don't have this problem.

**Comment by brujo5** [comment]
https://forums.dolphin-emu.org/attachment.php?aid=17050

**Comment by stenzek** [comment]
@brujo5 thanks for the shader dump, could you please check with #6741?

**Pull request merged**
