### PR TITLE
Scale challenge icons based on screen height

### PR DESCRIPTION
**Pull request by LillyJadeKatrin**

### CODE REVIEW

**Comment by JosJuice** [comment]
This will be shown next to text, right? If so, you should use the same scale factor as for text: https://github.com/dolphin-emu/dolphin/blob/b0f8520a3d8fc39bbd4364f9c382b97363566936/Source/Core/Common/WindowSystemInfo.h#L45

**Comment by LillyJadeKatrin** [comment]
The change is actually kinda the opposite of HiDPI; there were complaints that at smaller screen sizes the icons were taking up too much space. Looked up what That Other Emulator Platform does and for 64x64 icons (same ones as here) they were scaled to 1/16 of the window height, which at 1024 is full size, hence the calculation I perform here.

**Comment by iwubcode** [comment]
I appreciate you bringing that up Jos.  I questioned it too but forgot to post about it.  We do already scale for hidpi (just to mention).

It feels a bit strange to me to scale just the icons.  I'd almost prefer if we came up with what visual look we want the UI to have and then we could have a general purpose scale parameter that increases or decreases the UI to user taste.

But at the same time, I don't want to block this over something so silly.  If this needs to get pushed, we can figure things out later.

**Review by JosJuice — APPROVED** [review]
It's fine I guess.

**Pull request merged**
