### PR TITLE
pch: Update Visual Studio version check

### PR DESCRIPTION
**Pull request by lioncash**
```
[19:18] <@shuffle2> https://github.com/dolphin-emu/dolphin/commit/aeee5be5ef123a3b98b8fb413573b077b580e380
[19:18] <@shuffle2> someone should update this now
```

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3760)

### CODE REVIEW

**Comment by Riski01** [comment]
Dolphin Emulator does not support Android Lollipop 5.1.1

**Comment by lioncash** [comment]
OK, apparently MS decided to diverge from the common way of indicating SNANs (setting the highest-order bit of the trailing significand to zero), which can be seen [here](http://rextester.com/TVZ77443) (I also want to smack the person who phrased "A signaling NaN bit string should be encoded with the first bit of the trailing significand field being 0." in the 2008 IEEE-754 standard with 'should' instead of 'must').

`IsQNAN` isn't actually used by anything, and `IsSNAN` is only used within emulated code (in the interpreter within Interpreter_FloatingPoint.cpp and in the JITIL within IR_X86.cpp). Section 3.3.1.7 of the Programming Environments Manual for 32-Bit Implementations of the PowerPC™ Architecture states however, that it uses the most significant bit to differentiate between QNANs and SNANs. So special-casing this for MSVC will likely break emulation. So, these should likely be moved over to PowerPC emulation code instead of being in MathUtils in Common. Anyone have any issues about this being done?

**Comment by Parlane** [comment]
No issues here, sgtm.

**Comment by Riski01** [comment]
Dolphin Emulator does not support Android Lollipop 5.1.1
Pada tanggal 1 Apr 2016 3:26 PM, "Matthew Parlane" <notifications@github.com>
menulis:

**Comment by degasus** [comment]
@Riski01 Please stop spaming our PRs.

**Comment by shuffle2** [comment]
the fp thing seems odd. let me check into it before merge, please.

**Comment by lioncash** [comment]
@shuffle2 Note that this behavior change is 100% allowed while still remaining IEEE compliant. SNANs are inherently non-portable with regards to representation.

The 2008 revision of IEEE-754 defines the use of the word 'should' as:

> **should** indicates that among several possibilities, one is recommended as particularly suitable,
> without mentioning or excluding others; or that a certain course of action is preferred but not
> necessarily required; or that (in the negative form) a certain course of action is deprecated but not
> prohibited (“should” means “is recommended to”).

And the relevant section relating to SNANs in the standard (at section 6.2.1) states (italics added by me):

> A signaling NaN bit string *should* be encoded with the first bit of the trailing significand field being 0.
> If the first bit of the trailing significand field is 0, some other bit of the trailing significand field must be
> non-zero to distinguish the NaN from infinity. In the *preferred* encoding just described, a signaling
> NaN shall be quieted by setting d1 to 1, leaving the remaining bits of T unchanged.

**Comment by shuffle2** [comment]
@lioncash sure, but who needs to be compatible? e.g. If x86 hardware has knowledge of what is/is not a signalling nan, then msvc cannot change this.

**Comment by shuffle2** [comment]
btw we should check if fread hack is still required. if so, update it. if not, remove it.

**Comment by shuffle2** [comment]
The SNAN thing is a confirmed compiler bug :'(  
I guess dolphin must work around it.

**Comment by shuffle2** [comment]
The good news is that the fread fix seems to have made it into C:\WINDOWS\SYSTEM32\ucrtbase.dll
10.0.10586.0 (the november windows 10 update [th2_release.151029-1700])  
So we dont need to continue updating that workaround code.  
The bad news is that we can't remove it, unless we stop supporting the versions of windows which have the affected ucrtbase.dll

**Comment by shuffle2** [comment]
For the SNAN issue, the problem is specifically
```
static _CONST_FUN _Ty signaling_NaN() _THROW0()
		{	// return signaling NaN
		return (__builtin_nans("1"));
		}
```
where `__builtin_nans` is not handled correctly by the compiler. So only places where dolphin winds up using this builtin should be affected.

**Comment by shuffle2** [comment]
The previous msvc behavior is to use `(_CSTD _Snan._Double)` to generate the constant for `numeric_limits<double>::signaling_NaN()`. This results in `0x7ff0000000000001`, which `MathUtil::IsSNAN` would classify as SNAN. However, it does differ from other compiler's constant, which is `0x7ff4000000000000`. Does it matter for dolphin? @Tilka  ?

**Comment by shuffle2** [comment]
@lioncash also, we need to ban using at least `std::numeric_limits<double>::signaling_NaN()` with msvc until it's fixed...

**Comment by lioncash** [comment]
FWIW, valid SNAN range is

7FF0000000000001 - 7FF7FFFFFFFFFFFF

and

FFF0000000000001 - FFF7FFFFFFFFFFFF

**Comment by shuffle2** [comment]
Here's a possible patch which passes the test.  
```
diff --git a/Source/Core/Common/MathUtil.h b/Source/Core/Common/MathUtil.h
index 3ca5c1b..5b6481f 100644
--- a/Source/Core/Common/MathUtil.h
+++ b/Source/Core/Common/MathUtil.h
@@ -6,12 +6,27 @@

 #include <algorithm>
 #include <cstdlib>
+#include <limits>
 #include <vector>

 #include "Common/CommonTypes.h"

 namespace MathUtil
 {
+template<typename T>
+constexpr T SNANConstant() {
+    return std::numeric_limits<T>::signaling_NaN();
+}
+#ifdef _MSC_VER
+// msvc needs a workaround, because its std::numeric_limits<double>::signaling_NaN()
+// will use __builtin_nans, which is improperly handled by the compiler and generates
+// a bad constant. Here we go back to the version msvc used before the builtin.
+template<>
+constexpr double SNANConstant() {
+    return (_CSTD _Snan._Double);
+}
+#endif
+
 template<class T>
 constexpr T Clamp(const T val, const T& min, const T& max)
 {
diff --git a/Source/UnitTests/Common/MathUtilTest.cpp b/Source/UnitTests/Common/MathUtilTest.cpp
index f7427cc..0eabd14 100644
--- a/Source/UnitTests/Common/MathUtilTest.cpp
+++ b/Source/UnitTests/Common/MathUtilTest.cpp
@@ -23,13 +23,13 @@ TEST(MathUtil, Clamp)
 TEST(MathUtil, IsQNAN)
 {
        EXPECT_TRUE(MathUtil::IsQNAN(std::numeric_limits<double>::quiet_NaN()));
-       EXPECT_FALSE(MathUtil::IsQNAN(std::numeric_limits<double>::signaling_NaN()));
+       EXPECT_FALSE(MathUtil::IsQNAN(MathUtil::SNANConstant<double>()));
 }

 TEST(MathUtil, IsSNAN)
 {
        EXPECT_FALSE(MathUtil::IsSNAN(std::numeric_limits<double>::quiet_NaN()));
-       EXPECT_TRUE(MathUtil::IsSNAN(std::numeric_limits<double>::signaling_NaN()));
+       EXPECT_TRUE(MathUtil::IsSNAN(MathUtil::SNANConstant<double>()));
 }

 TEST(MathUtil, IntLog2)
```

**Comment by shuffle2** [comment]
@lioncash if that looks ok, can you merge? :) @Parlane was complaining about windows buildbot being blocked.

**Comment by Parlane** [comment]
This looks good to me.

**Comment by Parlane** [comment]
Did you mean "documented compiler bug"?

**Comment by lioncash** [comment]
Nope

**Comment by Parlane** [comment]
Reviewed 3 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3760)*

**Comment by Pringo** [comment]
@lioncash this was determined by a user on the forum to be the first Dolphin version (4.0-9194) to break OS X 10.9 support. More details here: https://forums.dolphin-emu.org/Thread-osatomicincrement32barrier-missing-on-osx-10-9-5?pid=421379#pid421379

Do you know what the issue is? I am not sure if this PR caused the problem of if it's a buildbot issue or something.

**Comment by lioncash** [comment]
Completely unrelated. This is for windows, not OSX.

**Comment by phire** [comment]
It looks like something funky was going on with the buildbots at that time.

**Pull request merged**
