### PR TITLE
Externals/hidapi: Convert to submodule

### PR DESCRIPTION
**Pull request by SuperSamus**
This also updates to https://github.com/libusb/hidapi/commit/d3013f0af3f4029d82872c1a9487ea461a56dee4.

Motivation for the update: if both the bundled SDL and hidapi are used, SDL's hidapi and Dolphin's hidapi will conflict over the symbol `device_string_names`, and the compilation will fail. This doesn't happen anymore after the update.

I'm not sure if I did the conversion to submodule the right way. The upstream `CMakeLists.txt` mentions stuff that needs to be used only upstream, and I don't know how important the `applied_patches` are.

### CODE REVIEW

**Comment by khg8m3r** [comment]
Builds on Ubuntu 22.04 and solves the problem there.

Might want to clarify that this commit is the release commit for hidapi-0.14.0

**Comment by t895** [comment]
@dolphin-emu-bot rebuild

**Comment by SuperSamus** [comment]
Now it should build again even if `libusb` isn't installed system-wide, just like before (meaning that the Linux builds that were failing before should now succeed).
Still don't know anything about `applied_patches`.

**Comment by AdmiralCurtiss** [comment]
Err I have no idea what you did wrong with the submodule here but the git on our builders does not like it at all.

The `applied_patches` look like fixes for macOS behavior. Unless they've been fixed upstream we should probably just keep a modified hidapi version for it. Maybe @OatmealDome knows what's up with them in particular?

**Comment by AdmiralCurtiss** [comment]
> Err I have no idea what you did wrong with the submodule here but the git on our builders does not like it at all.

Looking into this, it's because the directory you've used for the submodule anchor point previously already existed, and yeah git does not like that. You should to use a directory that didn't exist yet.

Or alternatively, don't convert to a submodule at all, if we need to manually patch it anyway for macOS. Probably easier.

**Comment by OatmealDome** [comment]
I remember trying to switch to libusb's hidapi fork a few years ago, but it broke Wiimote compatibility on macOS (potentially due to an upstream bug). If the build is fixed, I can test it out and see if that's still the case.

**Comment by AdmiralCurtiss** [comment]
> One that renames the hidapi folder to avoid the conflict, and the other that does the rest.

That doesn't actually fix the problem because the issue happens during the `git checkout` step, which doesn't go through the intermediate revisions but instead directly switches from whatever the current HEAD state is to the target revision. Which means that to be perfectly clear, there never must have been any file at the submodule location in the entire git history.

(You can work around the issue with something like `git checkout --force`, for what it's worth, but it's still better to just avoid it in the first place.)

**Comment by SuperSamus** [comment]
If I have to guess, it's because this was removed in the previous build. (It is not removed now)

https://github.com/dolphin-emu/dolphin/blob/8482a50154648f653104d7da0b8d371efb720565/Externals/hidapi/CMakeLists.txt#L22

Anyway, pushing with a different name, let's see how that one goes.

**Comment by Simonx22** [comment]
@dolphin-emu-bot rebuild

**Comment by AdmiralCurtiss** [comment]
Okay I'm not entirely sure why that still didn't work but I fixed it.

**Comment by OatmealDome** [comment]
The newest build seems to work on macOS now. (I can only test non-TR Wii Remotes, though.)

**Comment by AdmiralCurtiss** [comment]
Okay, every PR fails now without this hidapi update so I'll just merge this, we may have to make a separate macOS fix if anything breaks there.

**Pull request merged**
