### PR TITLE
Outdated SoulCalibur 2 ini.

### PR DESCRIPTION
**Pull request by dvessel**
Fast texture cache samples and immediate xfb has no ill effects.

This is a fighting game so having the option to enable immediate xfb would be nice.

It was bulk added in 3fbb9d66, so I have no clue why it was added.

### CODE REVIEW

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by dvessel** [comment]
I’ve forced these settings for a while and it has never giving me problems. The fades still work.

Fixed the game id’s and title.

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by mbc07** [comment]
Why not just delete the INI file altogether? It's essentially empty and not overriding anything after dropping `SafeTextureCacheColorSamples` and `ImmediateXFBEnable`. AFAICT, all INI files shipped with Dolphin overrides something, there are no empty INIs...

**Comment by JosJuice** [comment]
Yes, if you're going to be removing both of those settings you should delete the file entirely.

**Comment by dvessel** [comment]
I missed that. I was skimming through the other ini files with a bunch of headers with empty values so I just deleted the values.

**Comment by Pokechu22** [comment]
Does the updater correctly handle deleting files?

**Comment by mbc07** [comment]
> Does the updater correctly handle deleting files?

Yep, it does.

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by Pokechu22** [comment]
Aright, this change is probably good to go then (but I'll hold back on approving it since I don't own SoulCalibur 2 myself).

**Comment by dvessel** [comment]
Don’t think this is a popular title so here’s a video addressing the [issue tracker](https://bugs.dolphin-emu.org/issues/8429)

> What's the problem? Describe what went wrong in few words.
The fade-in and fade-out effects in the game don't show up. In certain sequences, the game uses fade-to-black and fade-from-black effects when transitioning between scenes. Two examples I can think of:
> - The title screen of the game. After the opening FMV sequence to the game is skipped or ends, the title screen pops out of nowhere.
> - In an Arcade Mode run, after the victory sequence, the screen immediately jumps from the shot of the pose
>
> What did you expect to happen instead?
> - The title screen should fade in from black, rather than the jarring transition that it is now
> - Similarly, in the arcade mode transition to the next fight, there should be a quick fade-to-black at the end of the victory sequence, followed by a quick fade-in to the next match's versus screen.

https://user-images.githubusercontent.com/126473/195192942-aec40776-7bbe-48bf-a25f-ee56bd0b0c88.mov

Everything fades into each other as expected.

**Review by iwubcode — APPROVED** [review]
Seems to work fine.

**Pull request merged**
