### PR TITLE
Android: Add Panic Handlers toggle to UI

### PR DESCRIPTION
**Pull request by Ebola16**
Fixes https://bugs.dolphin-emu.org/issues/10787

I may separate this out into a dedicated interface section in a future PR. This is a feature I really want in Android and for the moment I just want to make sure I implemented it properly.

screenshot_20180322-141352

### CODE REVIEW

**Comment by JosJuice** [comment]
We already have a `UsePanicHandlers` setting in the `Interface` section. You shouldn't add another one in the `Core` section.

**Comment by MayImilae** [comment]
Could you add something like this as well as or instead of the method in this PR? 

https://github.com/dolphin-emu/dolphin/pull/6479

Disabling the panic alerts is honestly not something we want users to do unless they really need to, and an ignore function helps reduce that need considerably!

**Comment by Ebola16** [comment]
`SECTION_INTERFACE` hasn't been implemented yet for INI files. I'm putting this setting in `SECTION_CORE` for the moment. Would having this setting lingering in `SECTION_CORE` cause problems when it eventually gets moved to the proper location of `SECTION_INTERFACE`?

@JosJuice Done

@MayImilae I am a user who frequently needs to disable panic alerts when modifying code in games. This UI feature matches the other versions of Dolphin and is very important to me. I would eventually like to do something similar to #6479 for Android but that is separate from this PR. I'm teaching myself how to code as I go along so I need to start simple.

**Comment by Ebola16** [comment]
Closed in favor of #6499

**Pull request closed without merging**
