### PR TITLE
IOS/ES: Handle personalised tickets properly

### PR DESCRIPTION
**Pull request by leoetlino**
IOS unpersonalises device-specific ("personalised") tickets prior to storing them on the NAND.

This is required for installing titles from the shop channel. Thanks for booto for helping me figure out an issue with the shared secret part :)

### CODE REVIEW

**Comment by JMC47** [comment]
With this Pull Request... the Wii Shop Channel is usable.

**Comment by Starsam80** [comment]
Sorry for using this thread, but if it is working now, can someone explain why I still get this error message?
image

> 13:30:504 IOS\Network\Socket.cpp:318 E[IOS_SSL]: IOCTLV_NET_SSL_DOHANDSHAKE: SSL - Connection requires a read call
13:31:186 IOS\Network\Socket.cpp:107 E[IOS_NET]: SO_CONNECT failed with error 10035: A non-blocking socket operation could not be completed immediately. , ret= -1
13:31:259 IOS\Network\Socket.cpp:107 E[IOS_NET]: SO_CONNECT failed with error 10056: A connect request was made on an already connected socket. , ret= -1

**Comment by JMC47** [comment]
You probably don't have proper certs yet because our tool was extracting them incorrectly.  the tool was just updated a few hours ago.  This guide should now work, assuming the tool is uploaded.

https://wiki.dolphin-emu.org/index.php?title=Wii_Network_Guide

**Comment by Starsam80** [comment]
Ok, updated to the latest master (5.0-2870), redid the certificates and it's a different error now:

> Wii shop channel error code 204905

```
34:48:373 IOS\Network\Socket.cpp:107 E[IOS_NET]: SO_CONNECT failed with error 10037: An operation was attempted on a non-blocking socket that already had an operation in progress. , ret= -1
34:48:375 IOS\Network\Socket.cpp:107 E[IOS_NET]: SO_CONNECT failed with error 10056: A connect request was made on an already connected socket. , ret= -1
34:48:377 IOS\Network\SSL.cpp:110 E[IOS_SSL]: Failed to read D:/Dev/Projects/dolphin/Binary/x64/User/Wii/clientca.pem
34:48:377 IOS\Network\SSL.cpp:110 E[IOS_SSL]: Failed to read D:/Dev/Projects/dolphin/Binary/x64/User/Wii/clientcakey.pem
34:49:325 IOS\Network\Socket.cpp:107 E[IOS_NET]: SO_CONNECT failed with error 10035: A non-blocking socket operation could not be completed immediately. , ret= -1
34:49:400 IOS\Network\Socket.cpp:107 E[IOS_NET]: SO_CONNECT failed with error 10056: A connect request was made on an already connected socket. , ret= -1
```

And yes, the `clientca.pem` and `clientcakey.pem` files do exist (md5 hashes):
```md5
797567b427fa6b0ed74e7bf428d0a409 clientca.pem
a82c3521f532b7e21199cdcd976ff2d9 clientcakey.pem
f67797020b2dd108726efba4bfc34ba7 rootca.pem
```

I don't know what I'm doing wrong

**Comment by JMC47** [comment]
It can be really fickle about the NAND, it didn't work the first time for me either.  Just wait for @leoetlino to respond, he may have a better idea what's going on.

**Comment by sepalani** [comment]
@Starsam80 
According to your logs, Dolphin is unable to read your files. Do these files exist and do you have the right to read them? You should also provide the sha256 rather than the MD5 hash and check if it matches theses: https://github.com/dolphin-emu/dolphin/pull/5027/files#diff-eee12198da9fa0c6a4601d0eeaad7100R91

**Comment by Starsam80** [comment]
```
229ec678525e060588e8ea23e5459ec14af3c2ebb7b9e69ec46b0faf011730d9 clientca.pem
723be9b32c3afb83a4a3757adf352529e90c0ad6fad52509963ba8942ae625df clientcakey.pem
c5b0f8dfcec6b9ed2ac38b8bc69a4db7c209dc177d243c8df2bddf9e39171e5f rootca.pem
```

Yes, they do match. The only reason why I did MD5 was because it was a bit more inconvenient to use SHA256.

I also checked the permissions and nothing seems to be wrong (all users can read, and most users can write). I also ran dolphin as administrator and it was the same.

**Comment by JMC47** [comment]
Do you have keys.bin in place?

**Comment by Starsam80** [comment]
Hmm, sorta. I do have a keys.bin, I got it from when I dumped my Wii, but if I was supposed to place it somewhere special in dolphin's folder I didn't do that, because [the guide](https://wiki.dolphin-emu.org/index.php?title=NAND_Usage_Guide) that I had followed didn't say to place it anywhere.

**Comment by JMC47** [comment]
I have no idea if the guide is even ready for shop channel lol.  I more or less followed Leo's instructions, and even then it didn't work right away until it felt like it.  Keys.bin goes with all the other files in the Wii NAND root.

**Comment by Starsam80** [comment]
It's the same:
image

**Comment by JMC47** [comment]
I don't know.

**Comment by Starsam80** [comment]
I found a fix! Turns out we weren't opening the certificate file as a binary file, which caused it to fail once it hit certain characters. I made a pull request at #5069

**Pull request merged**
