### PR TITLE
Fix a codetype in the Gecko codehandler

### PR DESCRIPTION
**Pull request by ikalpo**
Using the codetype "Load into Gecko Register" (82) would not use the address given, but the base address instead.

Example cheat codes:
```
82210000 XXXXXXXX
84210000 XXXXXXXX

82200000 XXXXXXXX
84200000 XXXXXXXX
```
These codes should do nothing, but can crash games with the broken codehandler.

### CODE REVIEW

**Comment by dreamsyntax** [comment]
This explains an issue I've been having.
👍

**Comment by nbohr1more** [comment]
@dolphin-emu-bot rebuild

**Comment by nbohr1more** [comment]
@dolphin-emu-bot rebuild

**Comment by BhaaLseN** [comment]
I hope you do realize that you cannot use that command. Besides, you can download that build and copy `codehandler.bin` over to a more recent one if you want to keep testing it.

**Comment by leoetlino** [comment]
Well, I think one reason is that no maintainer here (including myself) is very familiar with the codehandler. I'll trust you though...

**Pull request merged**
