### PR TITLE
Remove support for projection hacks

### PR DESCRIPTION
**Pull request by JosJuice**
This isn't really useful for anything anymore as far as I know.

### CODE REVIEW

**Comment by riking** [comment]
Were the four games it appears to be enabled in tested with this change?

**Comment by JosJuice** [comment]
No, I don't have those four games, so I haven't been able to test them. Hopefully they're not uncommon enough that we can't find people who have them...

**Comment by JMC47** [comment]
These projection hacks are hiding bugs and features.  They disable shadows in Don King Boxing for instance.  With Shadows on, the game has some odd rendering bugs.

Console

donkingconsole

Dolphin (No Projection Hack)

r2ke54-1

That said, I'm for removing projection hacks.  They're hacks.  And removing shadows isn't a way to fix a shadow bug.

**Comment by degasus** [comment]
LGTM

**Comment by Margen67** [comment]
You forgot to remove some lines: https://github.com/dolphin-emu/dolphin/blob/c6d0d9a01f83baf9cf50d95a49907e27232fb84b/Source/Core/VideoCommon/VertexShaderManager.h#L13
https://github.com/dolphin-emu/dolphin/blob/69addc680dfdd6ace6ebbf2b50c7e8c4ece6f26c/Source/Core/Core/Config/GraphicsSettings.h#L110

**Comment by JosJuice** [comment]
Thanks for catching that. Fixed in PR #6637.

**Pull request merged**
