### PR TITLE
WatchWidget: Fix integer comparison signedness warnings

### PR DESCRIPTION
**Pull request by tkln**
Fixes integer comparison signedness warnings.

### CODE REVIEW

**Comment by lioncash** [comment]
`NUM_COLUMNS` should likely be changed to an `int`. The change as is doesn't resolve signedness conversions, but rather moves them elsewhere. e.g. QTableWidget's `setItem` function expects an `int` for its row and column arguments, however this change now passes in an unsigned int.

**Comment by CookiePLMonster** [comment]
Also I fail to see how this change fixes "enumeration value not handled in switch"? Seems like commit and PR refer to two different warnings.

**Comment by tkln** [comment]
@CookiePLMonster True, that is for another commit which I somehow got mixed up with this PR.
@lioncash That's indeed a better solution. I've pushed a version that does just that.

**Comment by CookiePLMonster** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
