### PR TITLE
Changed the timing of partially buffered DVD reads to optimistic buffered reads

### PR DESCRIPTION
**Pull request by skidau**
Not sure about this one.  Comments welcome.

Fixes issue 8725.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3677)

### CODE REVIEW

**Comment by JMC47** [comment]
Fixes issue [8725](https://bugs.dolphin-emu.org/issues/8725) and issue [8516](https://bugs.dolphin-emu.org/issues/8516)

**Comment by JosJuice** [comment]
So you're changing std::max to std::min? That seems suspicious... If `buffer_fill_time - current_time` is very small, the read will be done when the buffer gets filled, disregarding the time it takes to copy the data to RAM. On the other hand, if `buffer_read_duration` is the small one, it will act exactly like a full buffer read even though it isn't fully buffered yet. I don't think this is a correct solution.

**Comment by skidau** [comment]
Yeh, the part I am having trouble understanding is how the emulation caters for the situation where the data is already in the 1MB buffer due to read-ahead.  Say the drive requests offset 0, for a length of 512KB, so the drive reads 1MB from offset 0.  Shortly after, the drive requests offset 512KB, for a length of 512KB.  The data is already in the buffer, so the time should be the time it takes for the buffer to transfer to RAM, but it looks like Dolphin is saying that the data will not be the buffer and the time is the raw disc speed.  This is why I thought the current code is pessimistic and by using min, it makes the code optimistic.

**Comment by JosJuice** [comment]
If all the data already is in the buffer, `current_time > buffer_fill_time` will be true, triggering the fast buffer read path. The slow buffer read path that you modified is only for the case where some of the data hasn't been read into the buffer yet.

**Comment by skidau** [comment]
buffer_fill_time would be the time it took to fill 512KB in my example, not 1MB as a drive with a read-ahead buffer would do.  Basically, I think the reason why the emulation disc rate is too slow right now is because we do not emulate or cater for read-ahead.

**Comment by JosJuice** [comment]
No, we do emulate read-ahead. I will use the second read command from your example to demonstrate.

`buffer_fill_time` gets set to `s_last_read_time + CalculateRawDiscReadTime(s_last_read_offset, offset + length - s_last_read_offset)`. `s_last_read_time` is when the first 512 KiB finished being read. The `CalculateRawDiscReadTime` call returns how long it takes for your second 512 KiB to be read to the buffer. In total, you get when the whole 1 MiB read finishes.

**Comment by JMC47** [comment]
So what's the actual status of this change then?  Is it something I should continue testing with games to see if there are regressions?

**Comment by JosJuice** [comment]
This pull request contains a completely different change now than before, so ignore the earlier comments. While I don't fully understand the new change, it seems strange that you are setting `bFastDiscSpeed` to true. Could you explain why? It won't speed up the current read, it will only make future reads too fast. Also, your way of checking whether there is a read in progress might not work as intended in all cases. For instance, it doesn't check the command type.

**Comment by skidau** [comment]
@JosJuice, ignore this PR.  It does not fix anything.

**Pull request closed without merging**
