### PR TITLE
Contributing: Add switch cases to the style guide

### PR DESCRIPTION
**Pull request by lioncash**
[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3613)

### CODE REVIEW

**Comment by sepalani** [comment]
*[Contributing.md, line 116 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3613#-KAAjkThYxuTpS16PDdp:-KAAjkThYxuTpS16PDdq:1140723209) ([raw file](https://github.com/dolphin-emu/dolphin/blob/14ee8245705ace4768232c03a204d4b29172ffda/Contributing.md#L116)):*
Is the break statement necessary in the default case?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3613)*

**Comment by lioncash** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Contributing.md, line 116 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3613#-KAAjkThYxuTpS16PDdp:-KAAo72u72xEtgSY6P8D:455480249) ([raw file](https://github.com/dolphin-emu/dolphin/blob/14ee8245705ace4768232c03a204d4b29172ffda/Contributing.md#L116)):*
There's no reason not to have a break there other than laziness. That also makes the code more error prone if refactoring happens to that switch statement. It's also inconsistent. default, like any other case label, can appear in any order in a switch statement. Getting into the habit of omitting it is just asking for a mistake to happen.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3613)*

**Comment by sepalani** [comment]
*[Contributing.md, line 116 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3613#-KAAjkThYxuTpS16PDdp:-KAAx1nw8LswzW4gr2Bn:1782865725) ([raw file](https://github.com/dolphin-emu/dolphin/blob/14ee8245705ace4768232c03a204d4b29172ffda/Contributing.md#L116)):*
Typically, my reason here is usefulness rather than laziness or inconsistency because the default case is the last case in your example. Of course, the compiler will be smart enough (I hope) to ignore that last/useless break anyway.

While you're talking about switch case order should we strictly follow this order (numerical order of integer/enum) or are we able to follow any order we want (including moving the default case somewhere else)? I guess, it should be at least mentioned, especially in the case where multiple cases lead to the same code without breaking.

Otherwise, LGTM.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3613)*

**Comment by BhaaLseN** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Contributing.md, line 116 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3613#-KAAjkThYxuTpS16PDdp:-KABA4OFmuq4_PDN2h5y:-1237812412) ([raw file](https://github.com/dolphin-emu/dolphin/blob/14ee8245705ace4768232c03a204d4b29172ffda/Contributing.md#L116)):*
The `default` case need not be the last one; it could be anywhere in the list (and whether thats a good thing is a different story). My vote goes to `break` for every case, unless there is an intentional (and **commented**/documented) fallthru.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3613)*

**Comment by endrift** [comment]
It's worth nothing that if the default case (or the last case, if it's not the last one) has no code, the break is MANDATORY, as compilers will complain if the last case in a switch statement is completely empty. Just but breaks everywhere except places where fall through is intentional (which must be documented), as already stated here, and it sounds great to me. The one thing that's missing though, is blocks inside of switch statements, e.g.

~~~c++
switch (thing)
{
case 1:
{
    int a;
    // ...
}
break;
// ...
}
~~~

etc.
Based on the rest of the style guide, I'm assuming this would be the preferred approach, if blocks inside of cases are allowed, otherwise there might want to be a comment in the style guide about it.

**Comment by lioncash** [comment]
Not necessary now that we have a unified clang format file in place.

**Pull request closed without merging**
