### PR TITLE
DolphinWX: Improve HBC banner scaling

### PR DESCRIPTION
**Pull request by JosJuice**
Aspect ratios are now correct, and the scaling algorithm is better. The scaling still looks worse than in DolphinQt, but I don't know why. Maybe the quality of `wxIMAGE_QUALITY_HIGH` isn't especially high after all?

Needs testing with GC games when rendering at a 2x scale. I would also appreciate someone testing whether the white dots bug is fixed: https://bugs.dolphin-emu.org/issues/8899

The screenshot below can be compared to the ones in PRs #2958 (DolphinWX) and #2993 (DolphinQt).

### CODE REVIEW

**Comment by shuffle2** [comment]
Doesnt' HBC format include the name in xml or something? we only show boot.dol? :(

**Comment by JosJuice** [comment]
It does include the name in an XML file. DolphinQt handles it already, but not DolphinWX because we currently don't have a good way to parse XML there. Lioncash said that we don't have the wxXML module enabled, and I don't know any more than that.

**Comment by phire** [comment]
Enabling the wxXML module is easy enough.

**Comment by degasus** [comment]
sounds like all comments does not apply to this PR at all. This is about banners, not about the text. So LGTM

**Pull request merged**
