### PR TITLE
Add a Skip EFB Access Hotkey

### PR DESCRIPTION
**Pull request by Losuc**
For about a decade people have been requesting "Skip EFB Access" Hotkey in Dolphin forums, here are some examples:

https://forums.dolphin-emu.org/Thread-skip-efb-acces-from-cpu-hotkey
https://forums.dolphin-emu.org/Thread-shortcut-to-skip-efb-access-from-cpu
https://forums.dolphin-emu.org/Thread-hotkey-for-skip-efb-access-from-cpu
https://forums.dolphin-emu.org/Thread-skip-efb-access-from-cpu-hotkey--58079
https://forums.dolphin-emu.org/Thread-skip-efb-acces-from-cpu-shortcut

### CODE REVIEW

**Comment by Losuc** [comment]
I suppose a bunch of lines in all language files have to be modified. Is there any easy way to do it?

**Comment by mbc07** [comment]
AFAIK as long as you use _trans() in the new code, the new strings should appear for the translators automatically on the next resources sync with Transifex (OSD Messages, however, aren't translatable at the moment). Transifex syncs are done periodically by @JosJuice...

**Comment by JosJuice** [comment]
Correct. You are not supposed to modify the translation files in pull requests, as it will just get overwritten the next time the automatic syncing runs.

Please fix the lint error and squash the commits into one.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by Losuc** [comment]
I have no Idea how to fix the lint error or squash the commits. Can you do it for me?

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by Losuc** [comment]
@JosJuice, can you test/review it?

**Comment by JMC47** [comment]
I took a look at this and while it seems to behave correctly in Super Mario Galaxy, if I'm seeing this correctly it's a massive 11 commits.

**Comment by Losuc** [comment]
How exactly? I followed this https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by JosJuice** [comment]
That guide does seem like it would work, yet there are 11 commits in the PR right now... Are you sure you didn't use a command like `merge` or `pull` after squashing the commits?

**Comment by Losuc** [comment]
It doesn't let me squash it again. 
And (git push -f) giving an error

> warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

>  git config --global push.default matching

>To squelch this message and adopt the new behavior now, use:

 > git config --global push.default simple

>When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

>In Git 2.0, Git will default to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

>See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

>fatal: unable to access 'https://github.com/Losuc/dolphin.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by mbc07** [comment]
Try this:

```
git reset --soft 64f7a4448b3071a0419dc09125e2cdf73cb99b97
git add .
git commit -am "Commit message here"
git push --force
```

This will reset the commit story to the last revision before you forked the repository, but it will keep the changes you've made. Then, `git add .` will stage those changes for commit, which you will finally do with `git commit`. After that, force push the repository with `git push --force` and this PR should have only one commit with the most recent changes you made...

**Comment by Losuc** [comment]
It keeps giving the error when I do (git push --force). I'm using Github Desktop and couldn't find a fix for it.
>fatal: unable to access 'https://github.com/Losuc/dolphin.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

Can't you guys just "Squash and Merge" when merging a Pull Request?

Otherwise, I suggest that I close this Pull Request and other user implements it as it's really simple. Because it looks like a wasting of time to insist with this.

**Comment by mbc07** [comment]
I'm 100% sure the commands I mentioned earlier will work on this case. The error you're getting indicates a network connection issue, you'll likely hit the same problem if you try to just open another PR instead. Perhaps try updating Git to the latest version?

**Comment by Losuc** [comment]
The first 3 commands worked, but the force push command is giving the error.
The Github Desktop is already the latest version (2.5.6).
I suggested other user to open  another PR.

**Comment by JosJuice** [comment]
Maybe something is wrong with the way the remote was added? Normally it should say `https://github.com/Losuc/dolphin.git`, not `https://github.com/Losuc/dolphin.git/` with a slash at the end.

**Comment by BhaaLseN** [comment]
If `git push --force` doesn't work, you probably don't have a tracking reference (which would be set up if you use `git push -u [...]` on your first push) - guessing here since you didn't tell us what the error was. Using `git push --force origin HEAD` (replace `origin` with the name of your Forks remote) instead might help in that case. `HEAD` is a symbolic reference that always indicates your currently checked out branch; you can replace this with your branch name `skipEFBaccessHotkey` if you don't have it checked out currently.

**Comment by Losuc** [comment]
Tried in another PC and it worked.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by brujo5** [comment]
Thank you very much it works perfect and saves a lot of time not having to enter the settings at all times for some games.

**Review by JosJuice — APPROVED** [review]

**Comment by Losuc** [comment]
When is this going to be merged?

**Comment by Losuc** [comment]
@JosJuice, what is needed for it to be merged?

**Comment by JosJuice** [comment]
I don't think there's anything more that needs to be done on your side. I'm just waiting for a second person to look over the PR as well.

**Comment by brujo5** [comment]
Hopefully someone else approves of this along with josjuice dev. thx

**Review by leoetlino — APPROVED** [review]

**Pull request merged**
