### PR TITLE
Kirby's Return to Dreamland "Bypass Metafortress" patch ported to PAL

### PR DESCRIPTION
**Pull request by RedStoneMatt**
- Given proper credits for the NTSC-U "Bypass Metafortress" patch (SUKE01.ini)
- Ported the "Bypass Metafortress" patch to the PAL version (SUKP01.ini)

### CODE REVIEW

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by Pokechu22** [comment]
I'm a little confused. Is this patch actually needed for anything nowadays? It doesn't seem to be enabled by default, and I *thought* that whatever Metafortress was detecting was fixed in Dolphin a while ago (though I can't find any specific information on that).

**Comment by RedStoneMatt** [comment]
> I'm a little confused. Is this patch actually needed for anything nowadays? It doesn't seem to be enabled by default, and I _thought_ that whatever Metafortress was detecting was fixed in Dolphin a while ago (though I can't find any specific information on that).

It is needed for many cheats to work. Just look at the amount of cheats available for US versus the ones available for EU.
A very few amount of cheats work without this patch, but for most of them you need it, as otherwise the game detects code modifications and prevents the game from booting.

**Comment by JMC47** [comment]
This is probably fine imo.  Bypassing metafortress has multiple uses.

**Pull request merged**
