### PR TITLE
CMake: use configure_file to generate scmrev.h

### PR DESCRIPTION
**Pull request by ligfx**
The built-in `configure_file` command correctly handles the case where none of the variables change and scmrev.h doesn't need to be rebuilt. This saves a full re-link of Dolphin any time CMake is re-run.

### CODE REVIEW

**Comment by Orphis** [comment]
Great! That one really bugged me out, but linking is so fast on macOS anyway that it was high on my priority list!

**Comment by degasus** [comment]
Does this fix our SCMREV issue on android? AFAIK updating this file didn't work reliable

**Comment by ligfx** [comment]
@degasus what is the SCMREV issue on Android?

I can see how it would fail to update if no CMake files got changed when the checked-out commit changed. This PR would not fix that, unfortunately.

**Comment by JosJuice** [comment]
From the user's perspective, what goes wrong is that the version number string sometimes matches a build that was made in the past rather than the build that the user actually has. I haven't investigated deeper than that.

**Pull request merged**
