### PR TITLE
Pads and Wiimotes Renumbering in config files

### PR DESCRIPTION
**Pull request by GregoireLD**
This PR aims to unify the numberings of configuration parameters regarding controllers.

For instance, prior to this PR, PadType0 would match with PadProfile1, PadType1 with PadProfile2 and so on.

This PR tries to make all internal numberings of controllers and accessories match their "in-game" counterpart :
New numbering starting with PadType1, PadProfile1...

~~This PR does have two issues~~ :
- ~~Since the numbering is changed, the user must select back it's controller on the next launch (only the first time)~~ Fixed
- ~~Same as above, but for people using INI files for game-specific configurations (I myself is guilty of that a lot), this PR requires to edit INI files accordingly (but given the gained legibility, I would gladly edit my INIs, but that's just me)~~ Fixed

~~I am not sure this is ready for prime-time (it does compile and works on my computer) but I lack the know-how (and the android device) to test it on many configurations~~

This PR is open for comments or discutions.
(Being my first PR here, I hope I did it right)

### CODE REVIEW

**Comment by mbc07** [comment]
If I understood the code correctly, all this PR does is count controllers (in related config files) from 1 instead of 0, as it is right now, and to be honest, I don't think it's worth the hassle. Assuming this PR gets merged as is, it would break existing configs for virtually anyone updating to a build released after that, just to have a more "pretty" numbering in the config files that most users won't even see, unless manually editing the files.

The other route I can think of, to prevent the existing settings breakage while still counting from 1, would be writing code to detect and handle this migration, but even then, it would be more work to achieve (IMO) so little, so is it really worth the hassle? I don't think so, but I'm speaking for myself. Let's wait and see what other members think...

**Comment by GregoireLD** [comment]
Regarding issue 1, I will look if it's possible to detect the use of "PadType0" (which would be the canary in the coal mine), and if present, migrate each PadTypeX to PadTypeX+1. Not touching any other settings, it should be enough to achieve what I had in mind.

When it comes to INI, no default INIs uses any on these parameters (as far as I know), only manual edits would be affected.
I had the assumption that people who edit their INI would know how to react, but it's true I should find a way to alert them if they launch a game with "old-style"numbering.

**Comment by GregoireLD** [comment]
I might've found a way to make this change as transparent as possible :
I now understand that PadType already is a legacy-type parameter, replaced by SIDevice.

I used the legacy section "GetINIToLocationMap" in "GameConfigLoader.cpp" and added solely SIDevice0 as a legacy name for SIDevice1, making SIDevice1, SIDevice2, SIDevice3, and SIDevice4 the standard internal numbering, but allowing both old styles PadTypeX, and SIDevice0 to work as intended without any changes, both in global, and game-specific INIs.

Only last trouble is, if the global config contains an explicit SIDevice1, it will still be prioritized over SIDevice0, I will think of a way to detect/circumvent it.

**Comment by GregoireLD** [comment]
This is now working as intended :
- Old configurations, both global and game-specific are handled as before (both PadType0-3 and SIDevice0-3)
- New configurations, are created using SIDevice1-4
- Mixed configurations, ie. with SIDevice1-4 in the general settings and PadType0-4 in game-specific INIS are correctly handled as before (be aware that PadTypeX are [Controls] settings whereas SIDeviceX are [Core] settings)

This would allow to smoothly migrate from the old PadType parameters, to the new SIDevice, without breaking any previous configurations.

I let this PR as draft for now, If anyone wants to weight in. I know this is a small niche alteration, but it always bugged me to have mixed numbers in my INI files, I just hope I'm not the only one 😊 .

**Comment by mbc07** [comment]
To me, this still seems a bit overkill for something so minor, but I won't block it. If you get approval from other members, so be it...

**Comment by GregoireLD** [comment]
True,

To make it more sensible, I simplified this PR to the strict minimum, only focusing on the exposed settings, not on internal numbering nor on Android implementation (I don't have a device to try it).

(I fumbled on Git when trying to reverse some files 😅 , but the PR is finally fixed)

**Comment by GregoireLD** [comment]
After testing this, I feel a bit more comfortable submitting this PR.

I know this might be a pet peeve that only annoys me 😊 and if someone gets a better idea to unify all numbering in config files I'm more than open to suggestions.

As a reminder, what this does :
- New configurations, and default configurations, are created using SIDevice1-4 parameters (instead of 0 to 3)
- When a SIDevice0 parameter is detected in the current configuration, it loads them using the old 0-3 numbering
> - This allows for transparent migration, making the old behavior untouched
- The even older legacy PadType0-3 are mapped as before on legacy configuration, making sure they still works as before
>- This allows for untouched INIs to still load as before, not needing editing on the user side

Only caveat I can think of, if someone wants to use the newer SIDevice1-4 in a game ini, they must be sure not to have a SIDevice0 still lingering in their main config (if they do, no crash will happen, just the legacy numbering will trigger and will be shifted accordingly). Programmatically modifying the main config file to shift the SIDevices by one would fix this fringe issue, and if requested I will look how to proceed onward.

Again, this might not be the best solution, and I'm more than open to suggestions.

**Pull request closed without merging**
