### PR TITLE
Fix sample wrapping with new DSP ADPCM decoding

### PR DESCRIPTION
**Pull request by delroth**
Fixes possible regression from #6069.

### CODE REVIEW

**Comment by delroth** [comment]
@GlydetheSurfer could you try this PR and let me know if it fixes the audio issue you reported? https://dl.dolphin-emu.org/prs/pr-6073-dolphin-latest-x64.7z for a Windows build.

**Comment by delroth** [comment]
(@leoetlino for fyi)

**Comment by hackerboy777** [comment]
Not @GlydetheSurfer, but I was experiencing audio warping on the latest build as well (all settings default, except D3D11 backend + 2x internal res in Kirby's Return To Dreamland [SUKE01]). The build you posted seems to have resolved the issue.

**Comment by JMC47** [comment]
LGTM.  Tested Kirby before/after, definitely was having minor audio issues.

**Comment by Ebola16** [comment]
This also fixes audio issues from #6069 in Super Smash Bros Brawl. They're easily noticeable with Zero Suit Samus' forward grab throw.

**Comment by leoetlino** [comment]
Ouch, that's nasty... Sorry about that :(

**Comment by GlydetheSurfer** [comment]
yes this fixed it... btw.. what i mean by choppy.. is in new super mario bros wii... there were sounds that sounded like someone stuck the audio in a bass tuner and turned the knob all the way to "treble" .. you know... like telephone quality

**Pull request merged**
