### PR TITLE
[STALLED] OGL: Update EFB cache on pokes

### PR DESCRIPTION
**Pull request by degasus**

### CODE REVIEW

**Comment by magumagu** [comment]
Seems okay... although, does anything actually do this?

**Comment by degasus** [comment]
yes, monster hunter tri seem to do some kind of postprocessing with efb peeks/pokes.

**Comment by JMC47** [comment]
It seems kind of broken currently; you get little dots popping in and out on the character creation screen.  It makes the game run 100 fps vs 2 fps though with the bloom somewhat working.

**Comment by Alegend45** [comment]
@JMC47 Sounds better than nothing to me.

**Comment by JMC47** [comment]
It's not; before we had correct (at least, I think) emulation, albeit slow.  Now we have no way to get correct emulation.

**Comment by skidau** [comment]
@JMC47 what IR setting are you using for the bug to appear?  Maybe try integer multiples: 1x, 2x, 3x or 4x.

**Comment by JMC47** [comment]
1x IR

**Comment by mrgreywater** [comment]
Untested, but it seems like thats what you gotta do:
```cpp	
case POKE_Z:
	{
		ResetAPIState();

		glDepthMask(GL_TRUE);

		u32 z = 0;
		if (bpmem.zcontrol.pixel_format == PEControl::RGB565_Z16)
		{
			//16 Bit depth
			glClearDepthf(float(poke_data & 0xFFFF) / float(0xFFFF));
			z = poke_data << 16;
		}
		else 
		{
			// 24 Bit depth
			glClearDepthf(float(poke_data & 0xFFFFFF) / float(0xFFFFFF));
			z = poke_data << 8;
		}
		

		glEnable(GL_SCISSOR_TEST);
		glScissor(targetPixelRc.left, targetPixelRc.bottom, targetPixelRc.GetWidth(), targetPixelRc.GetHeight());

		glClear(GL_DEPTH_BUFFER_BIT);

		if (s_efbCacheValid[0][cacheRectIdx])
		{
			u32 xRect = x % EFB_CACHE_RECT_SIZE;
			u32 yRect = y % EFB_CACHE_RECT_SIZE;
			s_efbCache[0][cacheRectIdx][yRect * EFB_CACHE_RECT_SIZE + xRect] = z;
		}

		RestoreAPIState();

		break;
	}
```

**Comment by shuffle2** [comment]
stall is no bueno

**Comment by delroth** [comment]
@degasus what's the status of this PR? If it's dead, let's close it.

**Comment by degasus** [comment]
the idea is still valid, but it just need manpower to implement it. As the code here isn't worth, I'm closing it now.

**Pull request closed without merging**
