### PR TITLE
Vulkan: Update Vulkan headers, VulkanMemoryAllocator

### PR DESCRIPTION
**Pull request by luiscondesdi**
As part of my investigations on why Vulkan backend rendering via hardware for the Raspberry Pi 5 was not working in master latest I stumbled upon [this VulkanMemoryAllocator issue](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/362). I checked on `Core/VideoBackends/Vulkan/StagingBuffer.cpp` and in RPi5 VMA was indeed having trouble allocating memory when `VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT` was requested.

This PR updates the submodule to tag `v3.1.0` of VulkanMemoryAllocator and as per @Xphalnos request at #12821, the vulkan headers to tag `v1.3.288` from https://github.com/KhronosGroup/Vulkan-Headers. This resolves the issue for Raspberry Pi 5, potentially also fixes this same issue for Raspberry Pi 4 and does not modify dolphin emulator code.

I preserve a branch with only the VMA update just in case it is preferred to do just that (as it also solves the issue).

### CODE REVIEW

**Comment by iwubcode** [comment]
Thanks for doing this.  However, if we're going to update the vulkan headers, it'd be better to migrate them to a submodule from the source repo.

**Comment by luiscondesdi** [comment]
It has come to my attention the SDL library has its own copy of the vulkan headers. The good news is we already have configured SDL as a submodule and the SDL Dev team [updated the vulkan headers five months ago](https://github.com/libsdl-org/SDL/commit/fc74bf8455fe30fd577783ce67376f18ca3b488c). Should I worry? Should we update SDL as well? 
My gut tells me to do it in a separate PR.

**Comment by BhaaLseN** [comment]
Windows still uses MSBuild projects (and not CMake,) so you'll have to update this section as well:
https://github.com/dolphin-emu/dolphin/blob/21ab26ddcc869fe5b659a739e723b15dad56adca/Source/VSProps/Base.Dolphin.props#L17

**Comment by BhaaLseN** [comment]
No idea about this one, that _feels_ like an upstream issue?
```
Externals\VulkanMemoryAllocator\include\vk_mem_alloc.h(3841,13): error C2220: the following warning is treated as an error [c:\buildbot\pr-win-x64\build\Source\Core\DolphinLib.vcxproj]
Externals\VulkanMemoryAllocator\include\vk_mem_alloc.h(3841,13): warning C4505: 'swap': unreferenced function with internal linkage has been removed [c:\buildbot\pr-win-x64\build\Source\Core\DolphinLib.vcxproj]
```

**Comment by iwubcode** [comment]
Are you sourcing from the tags or main?  Would definitely suggest sourcing from a tag and referencing it in your commit

**Comment by luiscondesdi** [comment]
> Are you sourcing from the tags or main? Would definitely suggest sourcing from the latest tag and referencing it in your commit message

I am referencing the latest tag, specifically. Should I switch to latest?

**Comment by luiscondesdi** [comment]
> No idea about this one, that _feels_ like an upstream issue?
> 
> ```
> Externals\VulkanMemoryAllocator\include\vk_mem_alloc.h(3841,13): error C2220: the following warning is treated as an error [c:\buildbot\pr-win-x64\build\Source\Core\DolphinLib.vcxproj]
> Externals\VulkanMemoryAllocator\include\vk_mem_alloc.h(3841,13): warning C4505: 'swap': unreferenced function with internal linkage has been removed [c:\buildbot\pr-win-x64\build\Source\Core\DolphinLib.vcxproj]
> ```
Yeah, its an unused function they left there...

**Comment by iwubcode** [comment]
> I am referencing the latest tag, v3.1.0 and its in commit message from commit [b6bd882](https://github.com/dolphin-emu/dolphin/pull/12875/commits/b6bd882258356704b6268951a154db822ee09f9f). I'll make it explicit in the PR.

That's good too.  I was referring to the Vulkan headers submodule though.  Latest tag there is v1.3.288

**Comment by luiscondesdi** [comment]
> > I am referencing the latest tag, v3.1.0 and its in commit message from commit [b6bd882](https://github.com/dolphin-emu/dolphin/pull/12875/commits/b6bd882258356704b6268951a154db822ee09f9f). I'll make it explicit in the PR.
> 
> That's good too. I was referring to the Vulkan headers submodule though. Latest tag there is v1.3.288

You are absolutely right. Good catch. Vulkan-Headers are now on tag `v1.3.288` as suggested.

**Comment by Xphalnos** [comment]
Tested on Android on Zelda Wind Waker: Before 25-27 fps and after 27-30 fps

**Review by iwubcode — APPROVED** [review]
Code LGTM.  Tested on Windows.

**Review by Xphalnos — APPROVED** [review]

**Comment by luiscondesdi** [comment]
I am getting stable 29.9 fps on rpi5 at native res, default settings. I am getting stable 29.9 fps in menus, 16-ish fps on scenes at 2x native res, default settings. Color me impressed.

**Comment by Xphalnos** [comment]
Tested on Windows
Master:
Resident Evil Master
PR:
Resident Evil PR

**Comment by AdmiralCurtiss** [comment]
The commit history here is a bit of a mess so I feel like we should clean this up before merging...

**Comment by JohnLoveJoy** [comment]
Sadly, even with this, the API implementation for Imagination BXM(Latest architecture) remains broken and fails to start.

Capt

**Comment by iwubcode** [comment]
> The commit history here is a bit of a mess so I feel like we should clean this up before merging...

My suggestion @luiscondesdi  would be one commit for the VMA update and one commit for the Vulkan headers (migration + turn to submodule).

**Review by AdmiralCurtiss — APPROVED** [review]
Yup, looks good now.

**Pull request merged**
