### PR TITLE
Expand GameConfig Editor Preset Options

### PR DESCRIPTION
**Pull request by ChibiChoko**
Adds the following to the Presets menu for the GameConfig Editor, matching nearly all of the options on https://wiki.dolphin-emu.org/index.php?title=GameINI#Graphics_Backend

GFX Backend Selection (DX11/DX12/Vulkan/OGL/Metal/Software)
CPU Emulator Engine (JIT x64, Cached Interpreter, Interpreter)
Floating-Point Result Flag 
Emulation Speed settings with Unlimited and options from 10%-200% in 10% increments
CPU Overclock toggle, with 50%/100%/150%/200%
Sync GPU Thread toggle, with 50%/100%/150%/200%
Fast Disc Transfers
Progressive Scan
Internal Resolution settings with all GUI options
Shader/Ubershader selection
Precompiling shaders before launch
GPU Texture Decoding
Aspect Ratio selection
Cropping
Anti-aliasing selection with SSAA/MSAA toggling
Fast Depth Calculation
Per-Pixel lighting
Disable Fog
Load Custom Textures
Prefetch Custom Textures
Cull Vertices on the CPU
Anisotropic Filtering selection
Force Texture filtering selection
Force 24-bit color
Disable Copy Filter
Arbitrary Mipmap Detection
HDR Post-Processing
V-Sync
Output Resampling Selection

New Video Hacks sub-menu with:
Scaled EFB Copy
Skip EFB Access from CPU
Ignore Format Changes
Bounding Box
Vertex Rounding
Immediate XFB
Skip Presenting Duplicate Frames
Defer EFB Copies to RAM
Defer EFB Cache Invalidation
Manual Texture Sampling
VBI Skip

New Audio submenu with:
DSP HLE 
DSP Emulator engine, for switching between LLE Recompiler and LLE Interpreter

### CODE REVIEW

**Comment by iwubcode** [comment]
Appreciate the contribution!

I personally want to get rid of the editor eventually, instead having a proper game window (see #13063 ).  So I am not in favor of this change.

**Comment by mbc07** [comment]
I'd also want to see the editor gone, especially now that PR #13063 is in reviewing process. However, this PR does add new settings currently not editable per-game anywhere else other than manually editing the INI file.

Could you trim down this PR so it includes only what is not already editable in the General tab of the game properties window and what is present in PR #13063 (essentially all Graphics-related settings)?

**Comment by ChibiChoko** [comment]
I've trimmed down the options to only what is not present in PR #13063 as well as added a few missing GC/Wii options. 

image
image

**Comment by mbc07** [comment]
Regarding the Console submenu, I'd prefer if you kept the same order and labels from the GUI parts where they appear. Could also abbreviate and move the GameCube/Wii descriptors to the end. Like this:

Console > Skip Main Menu (GC)
Console > Use PAL60 Mode (Wii)
Console > Aspect Ratio (Wii)
Console > Insert SD Card (Wii)
Console > Allow Writes to SD Card (Wii)

Also, you'll need to squash the commits and fix the lint errors (if there's any), before this PR can be merged...

**Comment by mbc07** [comment]
@dolphin-emu-bot rebuild

**Comment by mbc07** [comment]
@dolphin-emu-bot rebuild

**Comment by ChibiChoko** [comment]
Okay, I've made the requested changes and I believe squashed the commits as well. Please let me know if I've made any issues are happen to be mistaken, I'm still rather new to this.

**Comment by mbc07** [comment]
@dolphin-emu-bot rebuild

**Comment by mbc07** [comment]
The commits weren't squashed in your previous attempt (it seems you're doing all the changes from GiHub's website, you'll need to install `git` locally in your machine to properly squash the commits). You can also use the patch that's generated by the linter bot to fix the formatting, just click "details" (example screenshot from another PR):
image

**Comment by ChibiChoko** [comment]
At the start of this PR I was using the Github website, yes.

I've been doing the last half dozen or so commits through git and VSCodium. I'll attempt squashing again now that I've submitted a commit that matches linter's output.

**Pull request closed without merging**
