### PR TITLE
VertexLoaderX64: optimize more color swizzles

### PR DESCRIPTION
**Pull request by Tilka**
Based on https://gist.github.com/rygorous/c5dba8c6c75bc83aa4ae, but with a small tweak and a somewhat related change for the 565 case.

### CODE REVIEW

**Comment by degasus** [comment]
Do you think it's worth to also change the generic vertex loader in this way? Not for performance, but as reference what those assembly does.

**Comment by Tilka** [comment]
Yes.

**Comment by degasus** [comment]
LGTM

**Comment by i30817** [comment]
One of the kirby-shadows comparisons is completely pink

**Comment by Tilka** [comment]
Ignore ogl-lin-intel for now.

**Comment by phire** [comment]
LGTM

**Pull request merged**
