### PR TITLE
OGL: don't hardcode buffer sizes

### PR DESCRIPTION
**Pull request by Tilka**

### CODE REVIEW

**Comment by phire** [comment]
Do we want to use StringFromFormat instead?

**Comment by Tilka** [comment]
Yes.

**Comment by Parlane** [comment]
LGTM

**Comment by phire** [comment]
lgtm

**Comment by degasus** [comment]
LGTM

btw, is this just random fifoci madness, or did we overflow those buffers?

**Comment by phire** [comment]
Looks like it was randomly just correct. Real fix in #3232

**Pull request merged**
