### PR TITLE
Updated and added new Action replay Codes

### PR DESCRIPTION
**Pull request by raziel23x**
Went on AR Code Website and Added codes to Selected Games and minor
changes to ini files
D43E01 - Legend of Zelda, The - Ocarina of Time - Master Quest
Added all the AR Codes

GDEE71 - Baldur's Gate: Dark Alliance
Added all the AR Codes

GFEE01 - Fire Emblem: Path of Radiance
Updated AR Codes Adding codes for TATANIA

GFEJ01 - Fire Emblem: Souen no Kiseki
Added all the AR Codes

GGSEA4 - Metal Gear Solid The Twin Snakes
Added all the AR Codes

GIGJ8P - Bleach: Tasogare Ni Mamieru Shinigami
Added all the AR Codes

GO2E4F - Legacy Of Kain: Blood Omen 2
Added all the AR Codes

GS2E78 - Summoner 2
Added all the AR Codes

GTKE51 - Turok: Evolution
Added all the AR Codes

PZLE01 - The Legend of Zelda: Collector's Edition

Added all the AR Codes and added in support for:
Legend of Zelda, The
Legend of Zelda 2, The - The Adventures of Link
Legend of Zelda, The - Ocarina of Time
Legend of Zelda, The - Majora's Mask
Legend of Zelda, The - The Wind Waker Demo

	new file:   Data/Sys/GameSettings/D43E01.ini
	new file:   Data/Sys/GameSettings/GDEE71.ini
	modified:   Data/Sys/GameSettings/GFEE01.ini
	new file:   Data/Sys/GameSettings/GFEJ01.ini
	new file:   Data/Sys/GameSettings/GGSEA4.ini
	new file:   Data/Sys/GameSettings/GIGJ8P.ini
	new file:   Data/Sys/GameSettings/GO2E4F.ini
	new file:   Data/Sys/GameSettings/GS2E78.ini
	new file:   Data/Sys/GameSettings/GTKE51.ini
	new file:   Data/Sys/GameSettings/PZLE01.ini

### CODE REVIEW

**Comment by raziel23x** [comment]
I closed the other PR since somehow when i used the rebase it made the commits even more instead of combining them when i synced github for windows

**Comment by raziel23x** [comment]
I am surprised this has not been merged just yet as it is just add Action replay cheats to some games

**Comment by robertybob** [comment]
@raziel23x Don't be disheartened, sometimes it takes a long to time for even the smallest things to be merged. Thanks for taking the time to do this PR - I'm looking forward to reaping the benefits it brings!

**Comment by JMC47** [comment]
I'll ping the INI guy to take a look :)

@Linktothepast

**Comment by Linktothepast** [comment]
While i am the ini guy i have no saying about codes, i deal mainly with settings, i don't cheat in games. Plus i find them a burden since they are packed along with the ini files and makes settings difficult to see just from windows explorer preview. So basically i have nothing to say about them. Somebody else should handle game codes in dolphin.

**Comment by raziel23x** [comment]
Perhaps the ini files should be organized to where the cheat section is at the very bottom of the ini that way we looking for game settings the cheats will be the last thing on the list

**Comment by raziel23x** [comment]
which is something i am willing to do if need be

**Comment by JosJuice** [comment]
I've been considering making the six-character files only contain codes and no settings, as all the settings are inherited from the three-character files anyway. (With exceptions for Triforce games and other corner cases, of course.)

**Comment by Linktothepast** [comment]
I like both of the above approaches, JosJuice approach makes things even more tidy though. Sorry for going offtopic in this pr btw.

**Comment by raziel23x** [comment]
Which ever way you want to go i am up to making the changes if need be

**Comment by JosJuice** [comment]
This PR is fine as it is in my opinion. I can do the change in a separate PR after this one is merged.

**Comment by raziel23x** [comment]
have you thought about moving all the cheats out of the GameSettings folder and have them in there own section like create a new folder called GameCheats

**Comment by raziel23x** [comment]
@Linktothepast @JosJuice Any more info on this PR needed before it will be merged or some type of autobuild to test it?

**Comment by JosJuice** [comment]
I don't think anything else is needed. Sometimes it just takes a while for PRs to get through.

A build isn't really necessary since game INIs don't affect the build process, but I might as well do one anyway.
@dolphin-emu-bot rebuild

**Pull request merged**
