### PR TITLE
Vs cleanup

### PR DESCRIPTION
**Pull request by shuffle2**

### CODE REVIEW

**Comment by JosJuice** [comment]
Any particular reason you're increasing the SDK version and MSVC version?

If you're going to change the SDK version, you need to update it in the readme as well.

**Comment by shuffle2** [comment]
I went to compile dolphin, and I only have the latest sdk installed.

**Comment by JosJuice** [comment]
And the MSVC version?

**Comment by shuffle2** [comment]
There's no reason _not_ to.

**Comment by JosJuice** [comment]
But the older versions still work fine, don't they?

**Comment by stenzek** [comment]
FWIW, VS2019 has a "SDK: Windows 10 (latest installed)" option, so when/if we update, having a newer SDK version should no longer be an issue.

**Pull request closed without merging**
