### PR TITLE
Add common Wii SDK function signatures to the signature DB

### PR DESCRIPTION
**Pull request by leoetlino**
The signature DB is very helpful for generating a symbol map for games
which don't ship with debugging symbols, since it includes signatures
for common SDK functions.

However, it isn't very complete and only contained signatures for GC
games -- the current database isn't very helpful for Wii games, which
still have a huge number of unknown functions even after using this DB.

Yet Wii games typically share a lot of code (since they all use the
SDK), and not having symbols makes it a lot harder to look into what
a game is doing… So this commit adds common Wii SDK function signatures
to the database, in order to make generated symbol maps a lot more
useful for Wii games.

The debug info comes from the debugging map that was left in the Wii
version of The Legend of Zelda: Twilight Princess. To avoid cluttering
the DB with game-specific debug info (even though it already contains
some game-specific symbols), some basic filtering was done on the
shipped symbol map:

    egrep '(section layout|\.a|m_Do|lib|Lib| OS)' tp-framework.map | grep -v Z2 > common-wii-sdk.map

Then this map was loaded in Twilight Princess, and "append to existing
signature file" was used to append the new hashes to totaldb.dsy.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4490)

### CODE REVIEW

**Comment by sepalani** [comment]
In my opinion, this method is just overkill. It also creates false-positives with other games. I know that because I tried it a few month ago. The safest way to do so would be to create a map file on file basis. Then you can choose the ones which are "safe" to add.

With these you can distinguish between symbols from object and library files:
```bash
# Grep library functions
grep_library_function()
{
    grep -Po "[ \t]\K([^ \t]*\.a)" $@ | sort -u
}

# Grep object functions
grep_object_function()
{
    grep -Pv "[ \t][^ \t]*\.a" $@ | grep -Po "[ \t]\K([^ \t]*\.o)" | sort -u
}
```

Then you can store them in a file:
```bash
grep_library_function RframeworkF.map > files.txt
grep_object_function RframeworkF.map >> files.txt
cat files.txt | sort -u > sorted_files.txt
```

Finally, you can create map per file basis.
```bash
# Create map file
# $1 = filename
# $2 = map
create_map_file()
{
    grep -P "section layout|[ \t]$1" "$2" > "$1.map"
}

# Create map files
# $1 = list
# $2 = map
create_map_files()
{
    while read line; do
        create_map_file "$line" "$2"
        echo "${line}.map created"
    done < "$1"
}
```

I know, this method is time-consuming but it prevents weird symbols to be added in the database that still contains false-positives.

Anyway, there are also others ways to improve symbols detection:
1. Make dolphin analyses sel, rso, rel, ... that are loaded.
2. Load elf files from the game rather than booting from the iso/dol to generate the map file.
3. Patch dolphin maps with mega files from Megazig's WiiTools.

Regardless, I can provide symbols from the following PAL games:
 * Mario Kart Double Dash (GC)
 * My Sims (Wii)
 * Need for Speed Underground 2 (GC, via elf file)
 * Zelda Twilight Princess (Wii)

Concerning the ```JUTWarningConsole_f``` case, I would rather find a way to make ```vprintf``` work or use another function for the HLE hook. Can you see in the registers where are the parameters (format string, parameter 1, etc.) and if there is an easy work around to get ```HLE_GeneralDebugPrint``` working? As said in [PR #4469](https://github.com/dolphin-emu/dolphin/pull/4469), ```HLE_HOOK_REPLACE``` is quite destructive and can crash games when used. You can leave it as ```HLE_HOOK_REPLACE``` for the time being I guess.

**Comment by leoetlino** [comment]
What new false positives are there? I've manually checked the newly inserted signatures, and there doesn't seem to be any false positive… It's all GX, OS, IPC, Bluetooth, home menu stuff as far as I can see and they were recognised properly in all games I tried.

FYI, I did notice there are a few false positives in the *existing* database (probably caused by game-specific functions that were not filtered out). Are you sure the false positives you saw weren't due to that?

Also, the point of only having the SDK functions and doing it this way is that you won't have to do this on a per-game basis. Rather, it works with all SDK titles, even if it's not as complete/100% accurate. As you said, it's time consuming, but it's a maintenance issue as well imo: where do you draw the line at which debug info to include?

As for `JUTWarningConsole_f`, HLE_GeneralDebugPrint handles it perfectly as the registers contain everything we need. By the time it gets to call vprintf though, it stored something else into the registers and r4 doesn't point to the data we want to print anymore.

**Comment by sepalani** [comment]
When I was talking about false-positives issues I was referring to the "method", the way of adding symbol into the database, not specifically the one you provided. For instance, all these symbols with a size of 8 or 4 will more likely collide with others. I'm not going to talk about the collision caused by the way the hash is calculated.

I don't think all the symbols you added are from the SDK or are from libraries used in others games. I'm not a Wii/Nintendo developer so feel free to correct me if I'm wrong. The regexp accepts strings containing lib and m_Do but you have no guarantee that these are from the SDK. For example, I'm doubting that all "m_Do_*.o" files that don't belong to a library are from the SDK.

Then, if you want to know if it from the SDK or not, you almost answered the question yourself. The name of the library or the content of the map file will provide you enough detail to know if its from the SDK or not. Let say there is a file "os.a" and all symbols begin with OS, there are high probabilities for this map to be part of the SDK.

For the ```JUTWarningConsole_f```, were the string and the parameters moved into others registers? Are you sure that the function you're into is a ```vprintf```? (I mean, if you're using that map/db with another game. I don't think developers would name a function vprintf if it does something else)

**Comment by leoetlino** [comment]
Here's the list of added symbols, just so everyone can have a look (instead of just seeing a binary diff): https://gist.github.com/leoetlino/851456e1079bc8cfdd21294746605a5f

There are the obvious SDK functions, but I forgot to note that this also adds some Nintendo specific symbols, such as their in-house particle engine (JPA/JStudio), JAudio (which decodes audio banks), J2D and J3D. What I'm *not sure of* is the objects from m_Do, which however contains OSReport (!). I do agree this method isn't 100% foolproof, but I just went through the list again and there doesn't seem to be *anything* specific to Twilight Princess.

If you find anything that shouldn't be there, let me know and I'll remove them.

For `JUTWarningConsole_f`, the string (at r3) hasn't changed, but r4 now contains 0x32 (IIRC). And I'm not 100% sure it's vprintf since I don't have the original symbol map, but the function called by JUTWarningConsole_f still has the string to print (`%s`) in r3.
It looks like in that particular game, only JUTWarningConsole_f is used and never printf/vprintf directly, so it would make sense to hook that.

**Comment by leoetlino** [comment]
Just in case, I have removed m_Do and lib. OSReport is already matched by " OS", and lib is unnecessary because libs are already in .a files.

**Comment by sepalani** [comment]
LGTM.

According to my version of Zelda TP (PAL), it seems ```JUTWarningConsole_f``` can call ```vsnprintf``` but it's never the case for me because some checks make it take another branch.

I was wondering if ```HLE_GeneralDebugPrint``` supports ```v*printf``` functions and it doesn't. The first parameter given for the format string is the va_list. The others are luckily the 2nd up to the nth parameters (might not always be the case).

**Comment by JMC47** [comment]
I can't get this to work.

**Comment by leoetlino** [comment]
We haven't figured out why it doesn't work for JMC47 yet, but it appears to work on Windows as well:

Windows

**Comment by leoetlino** [comment]
Just for reference, the issue was that I forgot to tell him to save the symbol map after generating it.

**Comment by JMC47** [comment]
LGTM

**Pull request merged**
