### PR TITLE
Android: Inherit from Material 3 themes and round corners on box art

### PR DESCRIPTION
**Pull request by t895**
In order to retain the app's original look, I had to import the back button clip art and change the title bar text color in the settings theme because there isn't a Theme.Material3.DayNight.DarkActionBar.

I also made the box art for games fit with their associated cardviews so they appear rounded.

### CODE REVIEW

**Comment by Simonx22** [comment]
@dolphin-emu-bot rebuild

**Comment by Simonx22** [comment]
Please provide screenshots for UI changes.

**Comment by t895** [comment]
Screenshot_20220324-014923
Screenshot_20220324-014918
Screenshot_20220324-014913

**Comment by MayImilae** [comment]
Small nitpick, but the covers are too close to the console selection tabs at the top. It makes the white line tab indicator look almost like the selection for the games and just looks kind of broken. Moving the covers a bit downward away from the tabs will address that.

**Comment by t895** [comment]
@MayImilae The app has always had the games close to the tabs like that but I could add additional padding if necessary

Example in the current build -
IMG_0194

**Comment by t895** [comment]
On a second look though, it would be a good idea to tighten the cards a bit more because there is still a small space on box art with a base color other than white. If I really wanted to round the box art properly I could import another library like Glide to do that for me but that could just be too extra.

**Comment by MayImilae** [comment]
> The app has always had the games close to the tabs like that but I could add additional padding if necessary

Ah, I see why. The shadowing under the blue top bar in the old style helps give it separation that doesn't exist in the Material 3 version. A little extra padding should fix that.

**Comment by t895** [comment]
With new commits -
signal-2022-03-24-123941_001

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
Not entirely sure how I feel about the rounded upper corners on the cover art... But maybe that's just because of how used I am to seeing the original physical GC/Wii game boxes.

Code changes look OK. I'd like to let May have the final say on the design (if she does want to have the final say on Android design).

**Comment by t895** [comment]
@MayImilae Just let me know if you want more changes to the existing look, but I've been wondering. The styles.xml way of handling themes currently implemented really prevents some cool color customization work for a full on dynamic theme (>API30). If I made a pull request for changing to a system surrounding themes.xml files, would it be up for consideration?

The reason I ask is because I heard somewhere that larger commits aren't likely to be accepted.

**Comment by JosJuice** [comment]
Larger commits aren't forbidden per se. If it's a good change and there's no reasonable way to break it into smaller commits (which seems to be the case here on a first impression), it's okay, but it may take longer to get reviewed.

But either way, if you want to do this, it should be in a separate pull request.

(FWIW, right now I know almost nothing about what dynamic themes are and should probably read up on them :))

**Comment by t895** [comment]
This is a pretty good guide on how the colors work in Material 3 and when done right you can maintain the Dolphin-Blue color while introducing wallpaper-generated ones.
https://m3.material.io/styles/color/dynamic-color/overview

And thanks a lot for the information! @JosJuice

**Comment by JosJuice** [comment]
Ah, right, the new color system in Android 12. I don't have any personal opinion on whether we should use it, but I have nothing against doing a larger refactoring of how we handle themes, if it's necessary for dynamic themes or even just if it makes the code more maintainable.

(Just to clarify, since I think you're new to contributing to Dolphin: I'm the main person responsible for the Android code, and May is the main person responsible for design, but she doesn't specialize in Android.)

**Comment by t895** [comment]
I am new, and that's really helpful to know. Happy to meet you both and I hope to contribute more in the near future.

**Comment by t895** [comment]
I meant I fixed this gap
159851052-edce2647-cb74-4dcd-a104-acfd13c36cf4

Everything about this current screenshot
image

is fine

**Review by MayImilae — APPROVED** [review]

**Comment by t895** [comment]
@JosJuice Just squashed and ready to commit

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
