### PR TITLE
D3DBase: Implement Windows 7 swapchain fallback.

### PR DESCRIPTION
**Pull request by Armada651**
Fixes D3D backend initialization on Windows 7.

### CODE REVIEW

**Comment by Armada651** [comment]
@mimimi085181 Let me know if this build works for you, then we can merge the fix.

**Comment by mimimi085181** [comment]
D3D works again with this pr, thank you.

**Comment by Armada651** [comment]
@mimimi085181 Just to be sure, can you also test a build with that new commit?

The `IsWindowedStereoEnabled()` call should always return false on Windows 7, so it should be okay. This also has the advantage of explicitly failing when the user attempts to use quad-buffering on Windows 7 instead of silently turning it off.

**Comment by mimimi085181** [comment]
The new build from 08:25 works as well as the older one from 08:11.

**Pull request merged**
