### PR TITLE
Attempt re-adding the missing AXWii DSP_SYNC

### PR DESCRIPTION
**Pull request by degasus**
Rebase of PR #3756

### CODE REVIEW

**Comment by iwubcode** [comment]
While the code change seems fairly trivial and I can understand what it's doing at some level, I can't offer any suggestions.  However, I'm happy to do some testing.  Is there any specific game / scenario I should be looking at?

**Comment by delroth** [comment]
LGTM if @JMC47 doesn't notice anything breaking with AX Wii games.

**Comment by iwubcode** [comment]
@delroth - out of curiosity, what are "AX" Wii games?  Sorry I know little about this stuff..

**Comment by JosJuice** [comment]
@iwubcode AX is the most common series of DSP ucode. There is also a series that we call Zelda ucode.

**Comment by JMC47** [comment]
As it was last time, I still can't find any bugs with this.  Ran a bunch of Wiiware and a few super popular titles.

**Pull request merged**
