### PR TITLE
FifoRecorder: Don't allocate ~100.7MB on program startup

### PR DESCRIPTION
**Pull request by lioncash**
Something I noticed when going through the core codebase in #5580 to look for headers to normalize/remove.

So, a FifoRecorder instance is instantiated as a file-local variable and used as a singleton (ugh). Since it's a file-local variable, this means it's allocating no matter what, since it's done in the constructor. FifoRecorder's internal RAM and ExRAM vectors are 33554432 and 67108864 bytes respectively, which is around 100.66MB in total. Most users likely don't regularly use the FIFO player/FIFO recorder at all, so this is kind of a substantial waste of memory

Just on the game list view on a clean build with nothing loaded, this knocks debug build memory usage down from ~232.4MB to ~137.5MB, and release build memory usage down from ~101MB to ~5.7MB on Windows.

Problem case: I'd like to also deallocate this memory as well when records are finished; however, the FIFO player is accessed on more than one thread. Placing it after the finalizer callback will crash Dolphin, because it could still be accessing the FifoRecorder instance during shutdown (in particular, call into UseMemory()). If someone knows a non-ugly way of rectifying that, I'm all ears.

### CODE REVIEW

**Comment by shuffle2** [comment]
haven't looked at its use, but can things just take a shared_ptr to it?

**Comment by BhaaLseN** [comment]
Would resizing them back to 0 in `StopRecording` work? Assuming Start and Stop are symmetric and called as first/last action there.

**Comment by shuffle2** [comment]
btw, the memory clearing takes enough time that it's noticeable in program startup time. Will be nice to have it fixed to decrease that, as well :)

**Comment by lioncash** [comment]
@BhaaLseN Unfortunately that wouldn't work. It sets the flag to request recording to end, but the video thread is still going, so it may still try to do stuff with the memory (e.g. UseMemory() can still be called by the opcode decoder in VideoCommon), so an overrun would happen in that case. 

Placing:

```cpp
if (!m_IsRecording)
  return;
```

at the top of it seems to fix that issue, but I don't even know if that's a correct solution. Basically global recording state sucks (in this case, `g_bRecordFifoData`).

@shuffle2 If merging as is seems fine, I can add a TODO comment to properly handle memory after records, which I'll look into resolving separately; that way the common case usage case is covered in the meantime.

**Comment by shuffle2** [comment]
@lioncash sgtm

**Comment by Sarkie** [comment]
screenshot_20170620-202955
screenshot_20170620-203112


@lioncash roughly the same on Android

**Comment by Helios747** [comment]
It's pretty safe to ignore Android in regards to this. It's a bit nutty when it comes to memory allocation.

**Pull request merged**
