### PR TITLE
CMakeLists: Add Clang's Specific WShadow Diagnostics

### PR DESCRIPTION
**Pull request by mitaclaw**
For Clang parity with GCC. GCC is justified in detecting this, as it is [technically correct when using decltype](https://stackoverflow.com/a/74511081), but I believe it would be better to disable the warning if it were an option, hence my comment.

### CODE REVIEW

**Comment by mitaclaw** [comment]
This change is motivated by https://github.com/dolphin-emu/dolphin/pull/12610 being necessary after Clang failed to notify me of these GCC warnings.

**Comment by mitaclaw** [comment]
Clang also has `-Wshadow-field-in-constructor`, another kind of shadowing Clang does not detect by default which GCC detects as part of its `-Wshadow` option. Would it be worth enabling that as well for parity, seeing as we already avoid it in many places?

**Comment by AdmiralCurtiss** [comment]
Yes, please add `-Wshadow-field-in-constructor`. I'd also remove the comment, though I get where you're coming from.

**Comment by mitaclaw** [comment]
Looking again at Clang's documentation, there is also `-WShadow-field` to catch members shadowed during inheritance.
https://releases.llvm.org/5.0.0/tools/clang/docs/DiagnosticsReference.html#wshadow-field
Enabling this, it doesn't seem to happen anywhere in Dolphin's codebase. Is it worth adding as well?

**Comment by AdmiralCurtiss** [comment]
Oh, sorry didn't see that comment. If you want, but it seems pretty unlikely to be a problem.

**Pull request merged**
