### PR TITLE
SectorReader: Fix reading the last block of the disc.

### PR DESCRIPTION
**Pull request by delroth**
Regression from PR #3795. Fixes https://bugs.dolphin-emu.org/issues/9565

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3868)

### CODE REVIEW

**Comment by delroth** [comment]
@EmptyChaos mind reviewing the logic here?

**Comment by EmptyChaos** [comment]
When I wrote that code, I assumed `GetDataSize() % m_block_size` would be zero which may have been a bad assumption to make. I suspect the math is breaking because it's rounding down instead of up. Making the calculation round-up should fix it:
```cpp
u64 end_block = (GetDataSize() + m_block_size - 1) / m_block_size;
```

**Comment by delroth** [comment]
Good point, fixed it as you recommend.

**Comment by EmptyChaos** [comment]
:lgtm:

<details><summary><i>Previously, delroth (Pierre Bourdon) wrote…</i></summary>
> Good point, fixed it as you recommend.
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3868#-:-KIxLpBn-ZZkjWixpNsL:1417088721)*

**Pull request merged**
