### PR TITLE
GZLP01.ini – Update Cheatcode to Remove Distance Blur

### PR DESCRIPTION
**Pull request by b3rru**
The old code caused the black and white effect in some rooms not to work. The new one works properly.

### CODE REVIEW

**Comment by JMC47** [comment]
This is an improvement, but I must ask if maybe a graphics mod might be a better solution for this long term?  @iwubcode might want to look into this?

**Comment by AdmiralCurtiss** [comment]
FWIW even if a graphics mod exists that can do better, what's the harm in having an AR code too? Especially if it's just an improvement of one we already ship anyway.

**Comment by JMC47** [comment]
@dolphin-emu-bot rebuild

**Comment by JMC47** [comment]
This is good to merge once I double check the buildbots + linter

**Pull request merged**
