### PR TITLE
Qt2 translation: Don't place "zh_CN" and "zh_TW" after "zh"

### PR DESCRIPTION
**Pull request by JosJuice**
The least specific language code should be tried last.

@ligfx Does this make sense to you?

### CODE REVIEW

**Comment by ligfx** [comment]
It adds `zh_CN` immediately after `zh_Hans` and `zh_TW` immediately after `zh_Hant`, right? Is the issue that before it could have e.g. `["zh_Hans", "zh"]`, which would get expanded to `["zh_Hans", "zh", "zh_CN"]`?

This makes sense to me!

**Comment by JosJuice** [comment]
Yes, exactly.

**Comment by ligfx** [comment]
That logic makes sense to me. Not sure about how precedence works in `if (int i = GetIndexOfCode() != -1)` though. Will `i` be the index, or a casted boolean?

**Comment by JosJuice** [comment]
Ah, I didn't think of that... I'm not sure if it's going to do what we want, so I'd better change it.

**Comment by JosJuice** [comment]
Done.

**Pull request merged**
