### PR TITLE
Android: Also copy sys/Wii directory.

### PR DESCRIPTION
**Pull request by degasus**
This directory was just missed. This will fix some Wii games magically....

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3767)

### CODE REVIEW

**Comment by degasus** [comment]
@sigmabeta Do you want to review?

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by sigmabeta** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3767#-KERQspuxJYFFQMgfEJG:-KERQspuxJYFFQMgfEJH:455384272) (no related file):*
Java side LGTM.  Native & CMake files... don't look obviously wrong to me, at least. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3767)*

**Comment by eddiebrook** [comment]
Any chance to merge?

**Comment by eddiebrook** [comment]
Any chance to ADD in the Master?

**Comment by brujo5** [comment]
posible to merge?

this fix Naruto Shippuden: Gekitou Ninja Taisen Special

thanks.

**Comment by eddiebrook** [comment]
@delroth 
any chance to merge,please?

sorry to bother you, thanks

**Comment by degasus** [comment]
I doubt I'll get a better reviewment. @delroth, may you merge it please?

**Comment by eddiebrook** [comment]
thanks for merged but any idea why no link for android appear in the DL page?

**Pull request merged**
