### PR TITLE
Update maker information to match the wiki

### PR DESCRIPTION
**Pull request by t27duck**
This updates the maker data to (mostly) mirror that of the Wiki:
https://wiki.dolphin-emu.org/index.php?title=GameIDs

Only maker ids from that page are now included in Dolphin. This
means no homebrew/unofficial makers.

### CODE REVIEW

**Comment by Rukario** [comment]
There are still lot of missing and bad GameIDs. https://wiki.dolphin-emu.org/index.php?title=GameIDs

**Comment by t27duck** [comment]
Oh sweet, an actual master list of some sort. Are we considering that page the absolute source of truth? If so, I'd be happy to use this branch to fill in the blanks.

**Comment by Rukario** [comment]
It's the most up to date and can be trusted, Wiki editors there did great work appending between publisher code <-> publisher based on existing information game pages on Wiki. I did contribute there quite a bit (I happen to go by the editor name "Lucario"), Xerxes and Kolano are two other prominent editors and they did really good jobs there too. That list was dumped from somewhere I forgot, but I did remember there were lot of redlinks.

**Comment by t27duck** [comment]
I ended up constructing a Spreadsheet that pushed up the maker codes + values in Dolphin with the data in that Wiki page.

Read-only link: https://docs.google.com/spreadsheets/d/17y9z0WIFf0d1PfqcoVi_IKsiuruX7Jekqlz2D4UbCrA/edit?usp=sharing

There are codes in Dolphin that are not in that page and visa versa. Any code that shows up on the wiki but not in Dolphin I flagged as "keep" and feel like we should use whatever is in the wiki for the maker value. Codes that appear in both pages and their values are the same I also flagged as "keep." Codes that show up in both, but their values differ, I flagged as "keep" but we need to figure out which value to actually use. Codes that only appear in Dolphin I flagged as "Do not keep."

I "sledgehammer" my way through the initial creation of the spreadsheet and obviously we'd want to go through all of the codes, but I feel like this gets us ~80% of the way there if we treat the Wiki page as the primary source of truth.

I do not feel like I should make the final decision as to what values these codes point to, so I'm going to need some help. I'd be more than willing to share the edit link to whoever wishes to go through these and make decisions. Once complete, I can update this PR to set the "final" list of maker information for Dolphin.

**Comment by Rukario** [comment]
You could divide this PR into two stages: first stage to add codes that only exist in Wiki and replace maker names, and then second stage to clean up the bogus maker codes. Stage 1 will be easy to work on, it should be easy to figure out the correct maker name. Stage 2, however, will gonna be bit challenging and will take quite some time to confirm each. With two PR's, we can ship the first one to Dolphin and have it out of the way.

I've reviewed several bogus maker code that I find earlier in list, there's something I noticed, most were probably for the actual games that are available on virtual console, but virtual console games will use maker code of the manufacturer's system, such as any game made for Nintendo 64 will use 01 "Nintendo" instead of maker code of the actual publisher of the original game. I wonder where did dolphin team in the past got the list from...

**Comment by xerxespersrex** [comment]
A majority of the IDs on the wiki for physical releases have been confirmed against their box covers for the first four characters, but the publisher IDs mostly come from GameTDB after running it past a sanity check (i.e. that GameIDs trends page). The IDs that were initially populated onto the wiki all came from there and redump from what I've been told, but there's been a lot of independent work to try and make the database more accurate. There's not really a great way to get perfectly accurate publisher IDs in mass amounts besides third partys though (that I'm aware of), since it's not printed in the product ID on the cover.

**Comment by JosJuice** [comment]
> I wonder where did dolphin team in the past got the list from...

It was taken from http://www.gametdb.com/WiiCompanies, with only minor edits such as changing "Use Co.,Ltd." into "Use Co., Ltd.".

**Comment by Rukario** [comment]
GameTDB is good place to find information about the game, but that's where it ends when it comes to the hard-to-find information. It can't be trusted for everything, apparently.

What do you recommend? Replace the whole thing from Wiki without taking careful review on the unconfirmed codes, or keep them (and perhaps hold them for stage two of the two-stage PR's that I proposed)?

**Comment by leoetlino** [comment]
Please keep the changes in a single PR. Feel free to separate the changes into two commits, but we probably don't want to invalidate the game list cache _yet again_.

**Comment by t27duck** [comment]
I like the idea of just combining the lists into one as both lists have codes that the other doesn't (ex: The wiki has Telltale for the Strong Bad games while gametdb.com does not. I'd think we'd rather have too many codes than too little. For codes that appear in both, it would be a matter of "picking the best name" between the two options. 

I'll see about rebuilding that Spreadsheet based on that idea and see what the final list would look like.

**Comment by t27duck** [comment]
Looking through what few 3rd party VCs I have, it does look like the maker code is all coded to the original console maker, so not much we can really do about that. :/

**Comment by Rukario** [comment]
Oh, alright, single PR then.

Actually, I would go for cleanup, it'll make the list more honest, and not to throw false maker names to the modded discs with custom GameID. The maker entry will appear blank if it doesn't exist, right? If we confirm any more maker codes in the future we can make another PR for that?

**Comment by t27duck** [comment]
I think the point of this PR is we don't want to constantly open up PRs for missing codes and busting the game list cache over and over again.

Originally this PR was adding a couple missing codes and this convo has spin out from it. My assumption is this spurred from this being the third PR in a string of additions to the list.

**Comment by Rukario** [comment]
Yeah, sorry, this PR used to be for small changes then eventually turned into a large project. I have suggested a two-stage PR's as I thought it'd go easy on you on the first one and hand off the second one to someone else if you don't want to do it. Anyways, I can't imagine invalidating cache would be a such big deal... well, maybe for nitpick changes. :P

**Comment by t27duck** [comment]
I would have to defer to one of the main developers about any qualms with invalidating the cache

**Comment by t27duck** [comment]
After doing a little more research, I am leaning very close to saying the Dolphin Wiki is probably a better source of truth than the current list in Dolphin.

I took the codes that only showed in Dolphin and butted them up against a copy of the downloadable copy of gametdb's database. All codes found in Dolphin that are not found in the wiki appear to be linked to homebrew/custom games. The Google doc now has a new tab listing the code, current maker in Dolphin, and a game in gametdb that it belongs too. From what I can tell, they're all custom games.

Therefore, I feel like the best course of action is to primarily use the codes in the wiki for Dolphin with some slight modifications to the maker names (01 would just be called "Nintendo", for example). VC games are a lost cause, but that's currently how Dolphin handles them anyway.

Thoughts anyone?

**Comment by xerxespersrex** [comment]
I checked through the new tab and those all look fine to remove. The only ones that even looked legitimate were the Virtua Striker entries, but the GameTDB pages for them say that they're modified IDs. I even ran DPLs for around half of the publisher IDs on there to make absolutely sure the wiki didn't have any matching IDs, and none of the ones I ran gave any results.

**Comment by t27duck** [comment]
Alrighty, I updated the list to only include the maker info from the wiki. I 90-95% took an exact copy of the maker names in the wiki with a couple exceptions. 

My selection of Wii games and WiiWare titles appear to match up with what I expect locally, at least.

Feel free to scrutinize any of the entries I added/removed. I'd be more than happy to change stuff if deemed needed.

**Comment by Rukario** [comment]
Publisher names those without Wiki link probably shouldn't make it to your list, such as "2K Games" at 54 and "ZeniMax Media" at 68, as they weren't wiki-linked because no games actually have these publishers. There are additional publisher names (especially their former names) that have been omitted from your list -- these are still valid because some games do have these as their publisher during their time. I like the idea of using " / " as separator between multiple publisher names. There are several other publishers that didn't make it to your list, like DSI games, I think it should, because again, some games use that publisher as well. As a side note, I've updated small changes to the list on Wiki: "Namco Bandai Partners" at NQ.

**Comment by t27duck** [comment]
List should be updated to reflect closer to the wiki. If the maker name has a link then it's used (unless it's virtual console).

The other exception that I went with is `82` and `B2` which were the dedicated Namco and Bandai maker codes - I just gave them the maker string of "Namco" and "Bandai" as "Namco-Bandai" has its own code.

**Comment by mbc07** [comment]
Probably out of the scope of this PR but wouldn't be more feasible to update Dolphin's publisher database to match the wiki and then make it report IDs that don't match any publisher we know through analytics reporting? We could potentially end with some false reportings (e.g. custom/modded ISOs) but it should still be helpful...

**Comment by t27duck** [comment]
@mbc07 - I agree that could be helpful, but I believe adding to analytics would be a separate feature. Right now, I'm focusing on getting the maker list accurate to the official titles. Right now, what's on the wiki is our best bet.

**Comment by t27duck** [comment]
Does anyone have any opinions about this maker list in this branch?

**Comment by riking** [comment]
The new list LGTM.

**Comment by xerxespersrex** [comment]
@riking That's just not true. Here's [Super Mario Galaxy 2's cover on GameFAQs](https://www.gamefaqs.com/wii/960551-super-mario-galaxy-2/images/1198059) with an iQue publisher. Most of the Nintendo titles with a W region code were published under Nintendo's iQue brand. I did a write-up about it on my wiki talk page [here](https://wiki.dolphin-emu.org/index.php?title=User_talk:Xerxes#W_Region_GameIDs).

**Comment by t27duck** [comment]
Is there any more discussion that we want to have on this list now?

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
