### PR TITLE
Fix wrong GUID and missing tag

### PR DESCRIPTION
**Pull request by akyryz**
This PR allows newcomers build without the following error:
The project file '' has been renamed or is no longer in the solution.

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3977)

### CODE REVIEW

**Comment by akyryz** [comment]
this PR allows new comers to build without:

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by Parlane** [comment]
This doesn't build on windows.

**Comment by RisingFog** [comment]
What's the status of this PR?

**Pull request closed without merging**
