### PR TITLE
Update cubeb to mozilla/cubeb@27d2a102b0b75d9e49d43bc1ea516233fb87d778

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
Our current revision is from October 2017, so it's reasonable to update it. This fixes a long-standing issue where Windows would not remember Dolphin's volume as set in the Volume Mixer between sessions.

What complicates this is that cubeb at some point changed so it requires the user to initialize COM on Windows rather than doing it by itself, and also (at least via documentation, although it seems in practice this isn't a hard rule -- still, one should abide by the documentation...) requires that all calls to the cubeb API be only done on threads where COM has been initialized in MTA (`CoInitializeEx(nullptr, COINIT_MULTITHREADED)`) mode.

I've done this by adding a `RunInCubebContext()` function that tries to initialize in MTA mode, and if that fails creates a temporary thread to do it there instead. This is inspired by a long comment thread over in #8920, the last attempt at this, though with my own spin on it. That attempt never got merged, but maybe this one will be good enough?

Some extra notes:
- The cubeb sources are 1:1 copied from the linked commit, except for the `CMakeLists.txt`, which was slightly modified to work with our CMake build scripts.
- Two extra libraries are required to be linked on Windows compared to the October 2017 version, which have been added to the relevant `.csproj` files.

### CODE REVIEW

**Comment by shuffle2** [comment]
Worth noting that it seems Mozilla deprecated the library in favor of the rust version: https://github.com/mozilla/cubeb/wiki/Backend-Support

I would recommend using [wil](https://github.com/dolphin-emu/dolphin/tree/master/Externals/WIL) for the COM management , since it nicely solves the problem(s) and we already include it (maybe time to update that External, as well :))

Otherwise, lgtm

**Comment by AdmiralCurtiss** [comment]
Hey this actually builds now with the build server upgrade, great!

**Comment by shuffle2** [comment]
nice.

in addition to using WIL, what do you think about using submodule instead of copying the sources?

**Comment by AdmiralCurtiss** [comment]
Yeah I think we can use a submodule.

Regarding WIL, I'm not quite sure how to design this as-is with WIL? I guess it would in general be better to always use a separate thread here since we don't want to randomly enable MTA mode on whatever thread happens to call a Cubeb function... let's see...

**Comment by shuffle2** [comment]
hrm, starting a thread to handle a single function call seems a bit smelly  :p but yea, maybe it doesn't fit.

**Comment by AdmiralCurtiss** [comment]
We could have a cubeb worker thread that gets function calls to execute via a queue, if that's better.

**Comment by AdmiralCurtiss** [comment]
7c8dd95bf6ab0abc43c6baddb29e9d341cff7f5a is a variant using a worker thread. It's a bit ridiculous, but maybe actually the better option? Avoids the CoInitialize on the main thread and never opens any temporary secondary threads.

**Comment by AdmiralCurtiss** [comment]
I'll be honest, I'm not sure how either WIL or WinRT help me here. If you have an idea how to do this better please go ahead, because this is the best I can come up with.

**Comment by AdmiralCurtiss** [comment]
Well, don't mind me then...

**Comment by Zopolis4** [comment]
Depending on how the deprecation goes we could presumably use the C++ bindings to cubeb-rs, btw.

**Comment by Filoppi** [comment]
Happy to see this got merged. Thanks for quoting your references. I have resumed work on my other audio PRs, so this should make things a little simpler.

**Comment by Filoppi** [comment]
@AdmiralCurtiss 
It seems like cubeb still hasn't re-enabled `IAudioClient3` by default, which would allow for lower latency on Win 10/11:
[PR commit](https://github.com/dolphin-emu/dolphin/pull/8920/commits/3690b7d3afb589fc8ac01e75553b8c75780b4ed6)
[cubeb bug thread](https://bugzilla.mozilla.org/show_bug.cgi?id=1590902)
I'd say we should give it a try given that it should sensibly reduce audio lag, and almost make it [on par with exclusive mode WASAPI](https://learn.microsoft.com/en-us/windows-hardware/drivers/audio/low-latency-audio#windows-audio-session-api-wasapi). If any issues arise, we could disable it again, but it's been a while since that bug was opened, so maybe Windows updates fixed it, and it seems like it had always been a problem exclusively with input stream, which are still prevented from using `IAudioClient3` with my change.

**Comment by Filoppi** [comment]
> @AdmiralCurtiss It seems like cubeb still hasn't re-enabled `IAudioClient3` by default

I've done it here: https://github.com/dolphin-emu/dolphin/pull/11466

**Pull request merged**
