### PR TITLE
BitFieldView: Gekko changes

### PR DESCRIPTION
**Pull request by Minty-Meeo**
This PR is part 1 of splitting the monolithic PR #10610.  It is dependent on PR #10846.

### CODE REVIEW

**Comment by Minty-Meeo** [comment]
I may have violated a [coding style guideline](https://github.com/dolphin-emu/dolphin/blob/master/Contributing.md#functions) with my changes to Core/Core/PowerPC/Interpreter/Interpreter_FPUtils.h.  Should the references be changed back to pointers?

**Comment by JosJuice** [comment]
Yes, preferably.

**Comment by Minty-Meeo** [comment]
I don't think I agree with this coding style guideline.  Lvalue references are better than pointers for this sort of use-case, and their const-ness should be enough to signal whether or not it will be modified by a function.  Either way, it is now conformant, whether I like it or not.

**Comment by JosJuice** [comment]
The thing is that you only see the constness if you go and look up the function signature. When you're reading through code that's calling a bunch of functions you're not familiar with, you wouldn't be able to know which of the functions modify the argument if it wasn't for this convention. (Though, admittedly Dolphin doesn't comply 100% with this convention, so when reading through code you can't be 100% sure that just because there's no pointer operator there's no mutability...)

**Comment by Minty-Meeo** [comment]
I almost wonder if all the FPSCR util functions should be methods of Reg_FPSCR?  Might clutter up Gekko.h, though...  and is outside the scope of this PR for sure.

**Comment by Minty-Meeo** [comment]
The automagic BFVIEW/BFVIEWARRAY macros no longer require the structs to declare the storage member before the macros, meaning I can now make much prettier diffs for the record.  Maybe a future PR can move the storage members to all be consistent, but minimizing the diffs is one of the goals for these massive PRs.

**Pull request closed without merging**
