### PR TITLE
Android: Sharpen icons

### PR DESCRIPTION
**Pull request by t895**
Create vector Wii and GameCube icons and re-import default android icons as vector graphics. Scales better on a greater range of devices and takes up less space.

The app doesn't visually change except for the Wii and GameCube tab icons because the originals were very low res.

Note - I also removed redundant settings and refresh icons for Android TV. These still appear as intended on the TV version.

Before - 
before

After -
after

### CODE REVIEW

**Comment by MayImilae** [comment]
Um be sure to check this on Android TV cause I think you're deleting some files our Android TV interface is using.

**Comment by t895** [comment]
@MayImilae Here's the TV icons still visible
tvicons

**Review by MayImilae — APPROVED** [review]

**Comment by t895** [comment]
I'll check that out. I had no idea there were already vector icons around.

**Comment by MayImilae** [comment]
Well they are vector on my side but they are raster in Qt. For now at least.

**Comment by t895** [comment]
Would you have a way of sending that? I could add that to this PR if you'd like

**Comment by MayImilae** [comment]
Not right now, I'd need to do some prep to them and I'm waaay too busy right now. I just moved and I'm working on the Progress Report while still unpacking! For now, this PR should just be merged as is and any icon can be in a separate PR.

**Comment by t895** [comment]
Oh wow ok, we'll do that later. Just let me know when you have the time.

**Pull request merged**
