### PR TITLE
Android: Use Glide for cover caching

### PR DESCRIPTION
**Pull request by t895**
Glide has a built-in system for caching images so we don't have to use the custom caching system. Only downside is the TV channels will be loading covers from a URL instead of a local file.

### CODE REVIEW

**Comment by JosJuice** [comment]
Hm, wait a little... PicassoUtils used to have a system of fallbacks if a specific cover was missing: https://github.com/dolphin-emu/dolphin/blob/31efd16e16dd60b580cd9f470113277e00b69729/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/utils/PicassoUtils.java#L127

Did this system just disappear when we switched to Glide and I never noticed it? I was going to ask if this PR would introduce [the refetching problem I mentioned a while ago](https://github.com/dolphin-emu/dolphin/pull/10626#discussion_r942867598), but I can't find the code anymore.

**Comment by t895** [comment]
> Hm, wait a little... PicassoUtils used to have a system of fallbacks if a specific cover was missing:
I'm pretty sure that we removed it because when I was asking if we needed it, we couldn't find a reason for why GameTDB wouldn't have the cover for the region that the game file was reporting.

**Comment by JosJuice** [comment]
I do suppose that's true. But ideally we would support doing what the PC version of Dolphin does: First trying to fetch the version that matches the user's selected language, and then falling back to "the cover for the region that the game file was reporting". (The logic of which file to fetch being different from the PC version is kind of a historical accident.) I'm not saying this has to be implemented now, but it's something we should keep in mind so that whatever decisions we make for caching don't end up making that harder to implement.

**Comment by JosJuice** [comment]
Okay, after checking, it seems like the PC version actually doesn't have a fallback at all and just doesn't show anything if the cover isn't available in the user's language :(

I'm undecided on what we should do then... Does anyone else have any opinions?

**Comment by t895** [comment]
> I'm undecided on what we should do then... Does anyone else have any opinions?

We could figure this out sometime later. I don't want to block this PR because of a fallback system.

**Comment by t895** [comment]
Continued in #11408

**Pull request closed without merging**
