### PR TITLE
Render: Add an OSD notification for screenshot saving

### PR DESCRIPTION
**Pull request by lioncash**
Restores behavior that was removed.

### CODE REVIEW

**Comment by degasus** [comment]
Should this be merged into master or stable @Armada651 

LGTM

**Comment by MaJoRoesch** [comment]
I wondered what happened to this behavior. When and why was it removed?

**Comment by degasus** [comment]
Likely just missed on a cleanup ;)

**Comment by Armada651** [comment]
Yeah this is a stable blocker, but since this is just a single commit I don't mind cherry-picking it.

**Pull request merged**
