### PR TITLE
PostProcessing: Add support for user-supplied anaglyph shaders.

### PR DESCRIPTION
**Pull request by Armada651**
There are lots of different anaglyph glasses out there and there may be even more creative uses for stereoscopic post-processing shaders.

### CODE REVIEW

**Comment by degasus** [comment]
LGTM

**Comment by ADormant** [comment]
Can it be merged  ?

**Comment by Armada651** [comment]
@ADormant Not yet, there's still a minor issue where the shader is not applied when switching to Anaglyph mode.

**Comment by Armada651** [comment]
@degasus Last bug solved, ready for review.

**Pull request merged**
