### PR TITLE
Lighting Attenuation

### PR DESCRIPTION
**Pull request by degasus**
Recreate of PR #2021 
I've rebased and cleaned up the commit a bit, and added a last one to use the same normalization also for the other  configurations.

### CODE REVIEW

**Comment by degasus** [comment]
@NanoByte011 Can you please review my last patch?

**Comment by NanoByte011** [comment]
ok good stuff, but there are a few tweaks I didn't have committed yet that fix other things (like Mario Tennis score and preview court), reviewing your code has motivated me to finish this off now, do you mind if I take it from here?

**Comment by degasus** [comment]
@NanoByte011 you're welcome :D

**Comment by neobrain** [comment]
"attn"?

**Comment by degasus** [comment]
I've droped my last commit as it seems to not be correct. So this PR is mostly the same as NanoByte's.

His changes LGTM, so ready for merging IMO.

@NanoByte011 Your next changes are welcome, but I'd like to merge this here right now.

**Pull request merged**
