### PR TITLE
Add License for Boomy Icons

### PR DESCRIPTION
**Pull request by Pringo**
Add license with website link for remaining Boomy icons as required: http://yumek0n.deviantart.com/art/Boomy-multiplatform-36215357

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3970)

### CODE REVIEW

**Comment by JosJuice** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3970)*

**Comment by delroth** [comment]
That's not a license that's compatible with our project. Did we really never get better from the author?

**Comment by Pringo** [comment]
@delroth I have no idea if there is any special arrangement with the author. If there is it would have been done many years ago. If the license is an issue perhaps we should just remove those icons instead.

**Comment by MaJoRoesch** [comment]
Honestly we want to remove them anyway, is there any reason to do this?

**Comment by Pringo** [comment]
@MaJoRoesch see #3971.

If we keep the icons then we should be compliant with the license. If we delete them then this PR doesn't matter.

**Comment by Pringo** [comment]
This is no longer necessary with #3971 now merged.

**Pull request closed without merging**
