### PR TITLE
Use std::ssize when appropriate

### PR DESCRIPTION
**Pull request by Minty-Meeo**
C++20's new `std::ssize(const Container&)` helper is a decent concession for the lack of a std::ssize_t type or `Container::ssize()` method.  It looks nicer than a static_cast\<int\> of the `Container::size()` method of a container, imo.  That being said, I predict a similar response to the last time I made a find-and-replace coding style pull request.  Do your worst.

### CODE REVIEW

**Review by delroth — APPROVED** [review]
LGTM 👍 

Not merging this immediately in case I've missed anything that would make this a no-go -- but in general I think it simplifies a pattern we use widely in the codebase, and all the toolchains we care about seem to support it fine.

**Comment by lioncash** [comment]
It seems like quite a few of these are turning an explicit size-correct cast into an implicit truncating cast (since ssize is going to return the signed equivalent of the size_type of the container, which is 64-bits and then gets implicitly truncated), particularly when used with external libraries. Other uses seem to be fine for the most part though

**Comment by AdmiralCurtiss** [comment]
Yeah I'm a bit confused why you think the implicit 64bit -> 32bit conversion is okay here but the cast was not.

**Comment by AdmiralCurtiss** [comment]
(In fact, I'm surprised the compiler doesn't warn about this. Do we disable that warning, and if yes why?)

**Comment by Minty-Meeo** [comment]
For GCC/Clang, our CMakeLists.txt has this to say:
```
  # TODO: would like these but they produce overwhelming amounts of warnings
...
  #check_and_add_flag(CONVERSION -Wconversion)
```
Turning this warning setting on takes me from ~50 warnings to over 8000.  Initially, my thoughts while putting this together was, "implicit or explicit conversion, it does the same thing."  But, if preventing this warning means [leaving the static_casts in](https://learn.microsoft.com/en-us/cpp/cpp/type-conversions-and-type-safety-modern-cpp?view=msvc-170#narrowing-conversions-coercion), it might not be worth changing to a less familiar pattern.  Thoughts?

**Comment by Minty-Meeo** [comment]
I can count on one hand the number of places where using std::ssize alone isn't coercion in this PR.

**Pull request closed without merging**
