### PR TITLE
Add hotkey for centering mouse in render window.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
Kinda-sorta extracted from #10613 (actually just rewritten) so that one doesn't do five things in one commit.

Includes Windows, Linux and macOS implementations (the last one from @Dentomologist).

### CODE REVIEW

**Review by Dentomologist — CHANGES_REQUESTED** [review]
Tested on Windows, [here's](https://gist.github.com/Dentomologist/48f206f359c33ca821c6d2826bc76f81) a patch for macOS.

**Comment by AdmiralCurtiss** [comment]
Thanks!

**Comment by AdmiralCurtiss** [comment]
Okay, I believe this works on all platforms correctly now, though I can't verify the Mac implementation.

**Review by Dentomologist — APPROVED** [review]

**Comment by AdmiralCurtiss** [comment]
Does anyone else want to look at this? Otherwise I'll merge this tomorrow or so.

**Pull request merged**
