### PR TITLE
GameINI: Force safe texture cache for the System Menu and the shop

### PR DESCRIPTION
**Pull request by leoetlino**
Otherwise, input fields do not update properly.

### CODE REVIEW

**Comment by JMC47** [comment]
LGTM

**Comment by JosJuice** [comment]
There is a newline at the end. GitHub would've shown a special symbol otherwise.

**Comment by mimimi085181** [comment]
Are those settings applied always when the system menu is started? So from Dolphin's menu, a wad file or via home menu from a game? And if you lanch something from the system menu, does it apply the game settings then?

A cool feature would be to unload the system menu ini when launching a game from there. I mean, if you launch a game that does not set the texture cache accuracy, it resets to the user set value.

About this this setting: Does it really need to be the safe setting? Medium is not enough?

**Comment by leoetlino** [comment]
Might be better to wait until we can live swap specific settings from GameINIs before merging this; otherwise safe texture cache is going to be enabled for everything launched from the menu.

Safe texture cache is also needed for the shop.

**Comment by leoetlino** [comment]
Depends on #5855

**Pull request merged**
