### PR TITLE
GameSettings: force DSPLLE in remaining Neo Geo games

### PR DESCRIPTION
**Pull request by Tilka**
These two games were missed in PR #3841.

### CODE REVIEW

**Comment by Pokechu22** [comment]
Wouldn't it be better to just put this in `E.ini`?  Or is E used for both Neo Geo games and something else?

**Comment by JMC47** [comment]
There was a definite reason we didn't put it in e.ini.  I don't remember what game overlapped.

**Comment by JosJuice** [comment]
I looked it up, and it seems like E also covers "Virtual Console Arcade".

**Comment by Tilka** [comment]
I've merged everything into three files.

**Comment by JosJuice** [comment]
Dolphin doesn't support two-character game INIs.

**Comment by Tilka** [comment]
Reverted.

**Pull request merged**
