### PR TITLE
(Visual Studio) Categorize SoundStream.h with other SoundStream files

### PR DESCRIPTION
**Pull request by Stevoisiak**

### CODE REVIEW

**Comment by Tilka** [comment]
lgtm

**Comment by Stevoisiak** [comment]
I found another odd mismatch as well within Visual Studio's solution explorer.

In Source\Core\Core\DSP, there's a folder for JIT files. For some reason, Visual Studio includes DSPEmitter.cpp and DSPEmitter.h in the JIT section, when they are not present in the folder.

**Comment by lioncash** [comment]
No, because the emitter is used in conjunction with the JIT.

**Comment by Stevoisiak** [comment]
Should I move those files into the JIT folder then?

**Comment by Stevoisiak** [comment]
Is this good to merge? It's a fairly minor change.

**Pull request merged**
