### PR TITLE
Qt: Make Qt 5.9 a hard requirement

### PR DESCRIPTION
**Pull request by spycrab**
This has multiple benefits:
* Allows us to remove the ugly ``ActionHelper.h``
* Allows us to remove the version check macro in Main
* We won't have to worry about ``moc`` not being able to parse C++17 nested namespaces.

### CODE REVIEW

**Comment by spycrab** [comment]
The ``pr-ubu-x64`` buildbot should be updated before this can be merged (pinging @delroth)

**Comment by spycrab** [comment]
Kind of messed this one up by accident, will recreate it soon.

**Comment by StefanBruens** [comment]
>     Allows us to remove the ugly ActionHelper.h
The required addAction is available since 5.6.0
>    Allows us to remove the version check macro in Main
Obviously, as the check is ">= 5.6.0", also only requires 5.6.0
>    We won't have to worry about moc not being able to parse C++17 nested namespaces.
Support was added in 5.8.0, https://codereview.qt-project.org/#/c/170035/
Is this already used/required in dolphin?

Otherwise I would suggest to lower the requirements to 5.6, or 5.8 at most.Qt 5.6 is an LTS with support until March 2019.

**Comment by Zexaron** [comment]
@StefanBruens IMO Except that March 2019 from this date just doesn't look like "long term" to me.

**Comment by spycrab** [comment]
5.9 is the latest LTS release and was released over a year ago. Since 5.8 isn't even supported anymore, it's clearly the way to go IMO.

**Comment by StefanBruens** [comment]
@Zexaron but dolphin does not use a single feature introduced after 5.6.0

Nested namespace specifiers are a C++17 feature which you may use one day, but currently it is not used, so there is no need for a newer moc.

Qt 5.9 or newer is only available in the distribution releases from the last 3 months, e.g. Ubuntu 18.04 (2018-04-26), openSUSE Leap 15.0 (2018-05-18). There is no stable Debian with anything later than 5.7.x. I have tested building it for openSUSE Leap 42.3, which only provides Qt 5.6.4.

The only change to make it compatible with 5.6 is lowering the version in the CMakeLists.txt

**Comment by lioncash** [comment]
@StefanBruens We actually already use nested namespace specifiers in the IOS and DSP code (and likely  other places in the future). Of the list provided, we don't directly support openSUSE, we only have integration buildbots for Debian, Ubuntu, and FreeBSD as far as unix/unix-like support goes.

**Comment by KAMiKAZOW** [comment]
Artificially limiting platform support makes no sense, though. Qt 5.6 still works. Pls accept #7259

**Comment by StefanBruens** [comment]
I fear you are confusing nested namespaces with nested namespace identifiers. E.g. DSP::Analyzser is a nested namespace, but the code does *not* use nested namespace identifiers, but the plain old C++98 syntax:
`namespace DSP { namespace Analyzer { /* foo */  }}`
The same using C++17 nested-namespace-identifiers would be
`namespace DSP::Analyzer { /* foo */ }`

**Comment by JosJuice** [comment]
While nested namespace identifiers may be the more correct way to refer to it, lioncash's argument is correct – we do use nested namespace identifiers. See this commit, for instance: fb124c2

**Comment by delroth** [comment]
Let's not escalate this further please.

@KAMiKAZOW @StefanBruens we are not going to limit ourselves to the 5.6 feature set. We are targetting 5.9, and while we are not currently relying on anything that's not in 5.6 this is 1. by pure chance; 2. going to change.

Our benchmark for Linux compatibility re: external dependencies is "latest Ubuntu LTS". We are not going to subject ourselves to the slow update schedule of every single distro that exists.

If you distribution is not packaging Qt 5.9 yet, then I would recommend to not use latest Dolphin and keep to pre-5.9 required versions. Or maintain a patch as part of your package that decreases the Qt requirement until it breaks. Then you're on your own.

**Pull request merged**
