### PR TITLE
GPFifo: Use a pointer instead of an index

### PR DESCRIPTION
**Pull request by MerryMage**
This simplifies code generated by both JITs.

x86_64 jit now emits PIC.

### CODE REVIEW

**Comment by degasus** [comment]
I'd prefer more pointer usage in C++, but I'm fine with both.

LGTM

**Comment by JohnCalin** [comment]
Using Android build 5.0-3358 and newer, games no longer launch.  I just get a black screen, and must force quit the app.  Apologies if this is not the right place to put this, but as it coincides with this pull it seemed reasonable.

**Comment by JohnCalin** [comment]
Sorry, i meant that 3358 is the last version games do work with.

**Comment by MerryMage** [comment]
@JohnCalin Could you test if [pr-5268-dolphin-latest.apk](http://dl.dolphin-emu.org/prs/pr-5268-dolphin-latest.apk) fixes your issue?

**Comment by JohnCalin** [comment]
Same behavior - black screen, app must be force quit.

**Comment by MerryMage** [comment]
@JohnCalin Pushed another fix. Could you re-download and test once more?

**Comment by JohnCalin** [comment]
You nailed it.  It's working now.

**Comment by MerryMage** [comment]
Thanks for testing!

**Pull request merged**
