### PR TITLE
Add a few input expression functions (trigonometry, sqrt, pow, min, max, clamp)

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
Someone [on the forums](https://forums.dolphin-emu.org/Thread-feature-request-thread?pid=510144#pid510144) requested trigonometric functions to be added, so I figured might as well, easy enough. Also added a few more functions that seemed useful.

### CODE REVIEW

**Comment by jordan-woyak** [comment]
Just an FYI. min and max are already available using the `&` and `|` operators but it probably makes sense to have named versions too.

**Comment by Filoppi** [comment]
I've added some of these here already:
https://github.com/dolphin-emu/dolphin/blob/85c26e1b018f331f55a5e2ef2e4d7468018119a6/Source/Core/InputCommon/ControlReference/FunctionExpression.cpp

**Comment by Rumi-Larry** [comment]
Poke. Is this pr still alive?

**Comment by AdmiralCurtiss** [comment]
This is good-to-go from my side.

**Pull request merged**
