### PR TITLE
Add info. about the Building process of the Qt Gui in the README v2

### PR DESCRIPTION
**Pull request by joaoh1**
The same as #4327 but with 1 commit.

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4328)

### CODE REVIEW

**Comment by leoetlino** [comment]
"Update Readme.md" is a very undescriptive commit title.

**Comment by JosJuice** [comment]
The wording can still be improved. If you're getting the submodule the right way, you don't need to place things anywhere, they will be placed in the right directory automatically for you.

I recommend using a proper git client so you can update a PR without having to add new commits. GitHub's web interface is very limited.

**Comment by shuffle2** [comment]
This should just point to the github wiki which already has more correct description of how to do this per platform.

**Comment by joaoh1** [comment]
I tried the github client, still i cant change the commit

**Comment by leoetlino** [comment]
No idea if the GitHub GUI lets you do this, but the best git client is command-line git.

**Pull request closed without merging**
