### PR TITLE
Externals: Update OpenAL-Soft to 1.23.1

### PR DESCRIPTION
**Pull request by Xphalnos**
I updated OpenAL-Soft because it hasn't been updated for 10 years!

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
I'm a bit confused about these headers. Where do the matching binaries come from?

**Comment by AdmiralCurtiss** [comment]
What I meant was, how does Dolphin actually link against the binary? But after checking, it doesn't at all and expects the user to provide the dll for it:
https://github.com/dolphin-emu/dolphin/blob/c8ea116658ab814751c514d9062d694547bf3a6d/Source/Core/AudioCommon/OpenALStream.cpp#L73

It also is only implemented for Windows, which is also pretty weird. I wonder when the last time anyone even used this audio backend was...

**Comment by AdmiralCurtiss** [comment]
Also, are you sure you got the right headers? Whatever you got here does *not* match the headers in the 1.23.1 release.

**Comment by CasualPokePlayer** [comment]
Official headers would Creative Labs's OpenAL SDK, which is available on OpenAL's official site. Dolphin does not necessarily use OpenAL Soft, but rather any OpenAL 1.1 compliant implementation (of which there are several, although practically there's just the Creative Lab's implementation, OpenAL Soft, and I guess Apple OpenAL exists?). In this case, judging from the copyright headers the headers Dolphin uses appear to be from a really old version of OpenAL Soft? (alext.h is definitely not from the base SDK anyways; although this OpenAL Soft version seems so old the base headers appear to be copies of the official SDK).

OpenAL also hasn't received any updates to their base API past 1.1 (spec released in 2005, although the SDK apparently last changed in 2009?). The actual implementation version isn't of much concern for Dolphin, that's up to the user or package manager providing the shared library (although I guess this is kind of undercut by this being a Windows specific backend? It should be possibly to trivially make available on any platform, which is probably useful for obscure Unix like platforms if anything?).

**Pull request closed without merging**
