### PR TITLE
Minor strings.xml Fixes

### PR DESCRIPTION
**Pull request by Pringo**
We should not assume that Android devices are phones. Also "Dolphin Mobile" is not a proper name  for the program as far as I know and I do not believe the sentence was meant to be a question.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4370)

### CODE REVIEW

**Comment by SeannyM** [comment]
Haha, the Android code is somewhat of a mess right now. Especially in the strings department. Tons of unused strings, including this one. I have a cleanup incoming sometime soon.

**Comment by Pringo** [comment]
So this string isn't even used? Is this worth pushing through or should I close this and just wait for your cleanup?

**Comment by SeannyM** [comment]
Yeah, it's not used. This is from back when Dolphin first got its Android port, when we had to make sure the device supported NEON. Now, we don't even support ARMv7, so it's irrelevant. I'll try to get my cleanup ready tonight if I get a chance, since I'll be removing this string, this isn't needed.

**Comment by Pringo** [comment]
Alright, sounds good.

**Pull request closed without merging**
