### PR TITLE
[AArch64] Implement CRC32 texture hashing.

### PR DESCRIPTION
**Pull request by Sonicadvance1**
In a particular hashing heavy scene in Crazy Taxi the Murmur3 hash used 3.11% CPU time.
The new CRC32 hash in the same scene used 1.86%
This was tested on a Nvidia SHIELD Android TV with Cortex-A57s.

This will be a bit slower on the Nexus 9, the Denver CPU core is a bit slower with CRC32 texture hashing than Murmur3 texture hashing.

### CODE REVIEW

**Comment by Parlane** [comment]
Why would we merge with a "FIXME:" <_<

**Comment by Sonicadvance1** [comment]
Because it's already in the original code

**Comment by Parlane** [comment]
Your #if blocks are really bad now... Please don't allow two returns to be included at the same time. And for the case where it is not supported only return 0 should be in the final code. Not the random vars.
For instance:

    #if _M_SSE >= 0x402  || defined(_M_ARM_64)
      u64 h[4] = { len, 0, 0, 0 };
      u32 Step = (len / 8);
      const u64 *data = (const u64 *)src;
      const u64 *end = data + Step;
      if (samples == 0)
      	samples = std::max(Step, 1u);
      Step = Step / samples;
      if (Step < 1)
      	Step = 1;
    #endif

    #if _M_SSE >= 0x402  || defined(_M_ARM_64)
        // FIXME: is there a better way to combine these partial hashes?
        return h[0] + (h[1] << 10) + (h[2] << 21) + (h[3] << 32);
    #endif

**Comment by Sonicadvance1** [comment]
Did it

**Pull request merged**
