### PR TITLE
Android: update dependencies

### PR DESCRIPTION
**Pull request by Simonx22**

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
I will have to update the buildbot first, it seems like.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
Buildbot updated. We are now blocked on PR #10212.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Review by JosJuice — APPROVED** [review]

**Review by lioncash — APPROVED** [review]

**Pull request merged**
