### PR TITLE
CMake: use BundleUtilities to fix up Dolphin.app

### PR DESCRIPTION
**Pull request by ligfx**

### CODE REVIEW

**Comment by ligfx** [comment]
@orphis @endrift

**Comment by endrift** [comment]
Since you manually copy the Qt plugins in, this SHOULD work fine, but I'm not sure BundleUtilities is trustworthy. I think @Orphis said in IRC that it's unmaintained? It might be better to use a downstream approach in case it breaks in the future instead of hoping the upstream approach doesn't ever break when no one is going to fix it.

**Comment by ligfx** [comment]
We looked into it, and it is maintained—it just doesn't change that much. It's included in CMake's automatic testing, and they're open to accepting any patches.

One specific issue this fixes is handling libraries that use @rpath. They aren't supported by the deploy-mac.py script, but are by BundleUtilities.

**Comment by Orphis** [comment]
Also, if we need fixes in there, we can probably just copy the updated script into our repository while submitting the fix upstream. It should be fine.

**Comment by endrift** [comment]
In that case, lgtm

**Comment by Parlane** [comment]
Can you delete the Mac py file in this too then?

**Comment by ligfx** [comment]
@Parlane yep, I did

**Pull request merged**
