### PR TITLE
Android: Convert Settings to Kotlin

### PR DESCRIPTION
**Pull request by t895**
Nothing functionally changed here, just swapping to Kotlin.

Apologies in advance for such a large PR. This isn't really something you want to do in smaller chunks because it leads to a lot of annoying clean up later.

### CODE REVIEW

**Comment by JosJuice** [comment]
The enum class listings are really long after translation to Kotlin. Do they have to be formatted like that?

**Comment by t895** [comment]
If you try to put them in one line and then use the built in formatting, then only the ones that reach the character limit will be formatted like that. That felt inconsistent so I had them all follow the same pattern.

But no they don't have to.

**Comment by JosJuice** [comment]
Something we probably should do sooner or later is replace stuff like `Settings.FILE_DOLPHIN` and `Settings.SECTION_INI_CORE` with direct string literals, so the declarations take up less space and are easier to read. (This more or less matches what we do in C++ too.) I'm fine with doing that either before or after this PR, but either way, I think I would prefer to put stuff on one line where it is possible.

Also, it seems like SettingsFragmentPresenter has the same problem of setting declarations being overly long. I guess there isn't as much we can do here since almost all of them are longer than one line?

**Comment by t895** [comment]
> Something we probably should do sooner or later is replace stuff like Settings.FILE_DOLPHIN and Settings.SECTION_INI_CORE with direct string literals, so the declarations take up less space and are easier to read. (This more or less matches what we do in C++ too.) I'm fine with doing that either before or after this PR, but either way, I think I would prefer to put stuff on one line where it is possible.

I'm not sure what you mean. Like replacing instances of `Settings.SECTION_INI_CORE` with the string it represents? ("Core" in this case)

> Also, it seems like SettingsFragmentPresenter has the same problem of setting declarations being overly long. I guess there isn't as much we can do here since almost all of them are longer than one line?

I'll at least check, but in those cases, yes.

**Comment by JosJuice** [comment]
> I'm not sure what you mean. Like replacing instances of `Settings.SECTION_INI_CORE` with the string it represents? ("Core" in this case)

Yes, exactly. Sorry if it was unclear.

**Comment by t895** [comment]
You're fine, I'm just a little dull. I guess we could do that? It just feels less intuitive to me. I'll push that off to another PR, though.

**Comment by t895** [comment]
Reformatted the settings types and the presenter. As expected I couldn't do much about the presenter but a lot were collapsed in `BooleanSetting`

**Review by JosJuice — COMMENTED** [review]
I'm really not a fan of how the already long SettingsFragmentPresenter is now even longer. But if we're converting everything to Kotlin, I guess that's how it has to be.

I'll merge this after a day or so, in case someone else wants to offer any comments.

**Comment by mbc07** [comment]
It would be nice to get this merged, as it's a blocker (kinda) for the work I'm doing in PR #11600...

**Pull request merged**
