### PR TITLE
Fixes crash on Castlevania - The Adventure ReBirth (game INI update)

### PR DESCRIPTION
**Pull request by CharlesCorrin**
Disables dual core on Castlevania - The Adventure ReBirth. Without this toggle, the game will crash after the title screen.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4043)

### CODE REVIEW

**Comment by JosJuice** [comment]
Please only use one commit, use a title that mentions that this is a game INI update (so that nobody thinks this fixes something in the emulation core, which the current PR title implies), and don't change newlines to CRLF.

**Comment by CharlesCorrin** [comment]
I'm sorry for the bother, but I'm very new to Github. Could you please tell me how to remove the erroneous extra commit? I didn't intend to propose both.

I also don't understand how not to use a CRLF. What should I use instead, please?

**Comment by JosJuice** [comment]
You can't remove or edit commits on GitHub. You will need to use a local git client with a cloned version of your Dolphin repository. You can then squash the two commits into one using `git rebase -i`. You can look up details on how to rebase in the git manual, or ask us either here or on IRC.

Use LF line endings, like the file was using before. Your text editor probably has a setting for this, maybe named something like "Unix line endings".

**Comment by CharlesCorrin** [comment]
I'll erase this and start again, I suppose. I can't seem to get it right.

**Comment by CharlesCorrin** [comment]
I have a new one I believe fixes all of the problems. :3 Thank you.

**Pull request closed without merging**
