### PR TITLE
DolphinWX: Enable/disable config UI options based on core state

### PR DESCRIPTION
**Pull request by lioncash**
Noticed this was doable when finishing up #4422 

This makes the UI options in the config dialog dynamically enable and disable in realtime based on what the core state is (and any pre-conditions in the UI code itself, of course). This allows for making the main config window modeless if preferable, since there's no worry about UI options not properly enabling/disabling.

I didn't make it modeless yet, since I'm not sure on opinions regarding that (IMO, it'd lead to better UX, since you can leave the config open if you ever need to quickly change something if the window is modeless). If making it modeless is desired, I can just update this PR with the necessary code, considering it's pretty trivial to do. If not, then this PR is good as is.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4427)

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Not really sure if all of those necessarily need to be disabled (such as Audio Latency or Disable Screensaver...) but other than that, the cleanup is very nice.

Something you might want to consider: we have quite a few `OnUpdateIfCoreNotRunning` members now that all do the same (that is, checking for `Core::IsRunning`). Maybe those common ones should be moved into `WxUtils` for example?

**Comment by leoetlino** [comment]
Yeah, that's a nice cleanup, and it makes the UI less confusing. IMO, making the config windows modeless is a good idea; I can't think of any reason not to.

Moving out the common OnUpdateIfCoreNotRunning would be great indeed (if it's possible), since other parts of the UI (such as the controller config diag) could also be changed to use UI update events.

**Comment by Helios747** [comment]
:lgtm:

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4427#-:-KVp5WYE5gQJ8h-KfRuy:bnfp4nl)*

**Comment by Helios747** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4427)*

**Comment by lioncash** [comment]
@dolphin-emu-bot rebuild

**Comment by lioncash** [comment]
@leoetlino @BhaaLseN @Helios747 Updated the PR to make the main config dialog modeless.

**Comment by Helios747** [comment]
I'm fine with making it modeless.

**Comment by BhaaLseN** [comment]
LGTM

**Comment by MayImilae** [comment]
This is a factor in a recently discovered bug: https://bugs.dolphin-emu.org/issues/10222

**Pull request merged**
