### PR TITLE
Made cycle count atomic to avoid using a mutex

### PR DESCRIPTION
**Pull request by SizzlingCalamari**

### CODE REVIEW

**Comment by lioncash** [comment]
@dolphin-emu-bot rebuild

**Comment by shuffle2** [comment]
Good. Perhaps you would also like https://github.com/dolphin-emu/dolphin/pull/2218

**Comment by mimimi085181** [comment]
You seem to be interested in the DSP LLE threading, maybe take a look at this: https://github.com/dolphin-emu/dolphin/pull/1341

Well, i haven't checked if Dolphin is still working the same as it was back then, so sorry in advance if that pr is completely useless now.

**Comment by SizzlingCalamari** [comment]
@mimimi085181 I don't think #1341 is an issue because a wait on an event will return and reset the signal if the event is already in the signaled state. In the error case described, if the dsp event were signaled before the dsp thread started waiting, the dsp thread would just fall through the wait and reset the signal. That's my take on it anyways.

**Comment by lioncash** [comment]
Looks good to me.
@dolphin-emu-bot allow-merge

**Pull request merged**
