### PR TITLE
Fix dithering/output loop

### PR DESCRIPTION
**Pull request by kamiyo**
removed float->s16
added float scaled to s16
moved DITHER_NOISE define to cpp
Thx to Tinob for pointing this out.

### CODE REVIEW

**Comment by kamiyo** [comment]
wait.

**Comment by kamiyo** [comment]
@Tinob or anyone else, do you think I should go ahead and implement shaped dither?

**Comment by Tinob** [comment]
triangle should be just fine.

**Comment by degasus** [comment]
Thx for this fix, but we've reverted this feature because of some other remaining issues. Sadly he didn't came up with a fixed version either :/

**Pull request closed without merging**
