### PR TITLE
Qt/D3D: Fix render widget size not being restored properly

### PR DESCRIPTION
**Pull request by spycrab**
Fixes [issue #11118](https://bugs.dolphin-emu.org/issues/11118).
[LocalDolphin.zip](https://github.com/dolphin-emu/dolphin/files/2010331/LocalDolphin.zip)

### CODE REVIEW

**Comment by spycrab** [comment]
Might still be broken. Needs confirmation before merging.

**Comment by JMC47** [comment]
Still doesn't restore for me.

**Comment by spycrab** [comment]
@delroth So my local windows build works fine (confirmed by @JMC47) but the buildbot one doesn't. Any idea why that might be? (Outdated MSVC, perhaps?)

**Comment by spycrab** [comment]
Confirmed to be working on the buildbot now.

**Pull request merged**
