### PR TITLE
Core: Remove MemoryWatcher

### PR DESCRIPTION
**Pull request by Techjar**
MemoryWatcher only works on Linux and affects emulation determinism due to scheduling additional events, which causes NetPlay to desync. Considering that this interface is a rather specialized use case, the communication with it is kinda crappy *and* it's affecting emulation, I think it's best to just axe it and come up with a better implementation of the functionality.

This was as extremely silly bug, and an absolutely incredibly bug hunt. Thanks to all those who helped track this down!

### CODE REVIEW

**Comment by JosJuice** [comment]
What if determinism gets enabled while emulation is running?

**Comment by Techjar** [comment]
When does that even happen?

**Comment by JosJuice** [comment]
It happens when starting a TAS while running a game. (This creates a savestate that has to be loaded when the TAS is played back.)

You can also cancel TASing while a game is running.

**Comment by JosJuice** [comment]
How about instead of disabling MemoryWatcher entirely when we want determinism, we make it so that MemoryWatcher always registers its event on all OSes but never actually does any memory watching on OSes where we don't support it? That way it's still possible to use MemoryWatcher on netplay/TAS for those who want that.

**Comment by Techjar** [comment]
Yeah that's possible. The code only works on operating systems that support unix sockets, so we could ifdef code out based on that.

**Comment by JMC47** [comment]
This is the greatest bug hunt I've ever seen.

**Comment by JMC47** [comment]
We need netplay fixed before the monthly build and this is confirmed to fix it.  If we need to revert, so be it.

**Comment by vladfi1** [comment]
I use this! The memory watcher doesn't run unless there is a `Locations.txt` file present, so I'm not sure how it could affect anything normally. We could also just turn it off in the CMakeLists.txt by default...

**Pull request merged**
