### PR TITLE
Revert "Merge pull request #4916 from leoetlino/cpp-optparse"

### PR DESCRIPTION
**Pull request by Helios747**
This reverts commit 06428c3f14485e644006dcbb6329a4591b1d82ec, reversing
changes made to 722ff4c020b07ca0a285c70e26923cdab5623589.

Please test this and review to make sure I've reverted correctly.

This PR introduced significant regressions on Windows that nobody is sure if we can easily resolve, including flat out triggering assertions on dbg builds

https://github.com/dolphin-emu/dolphin/pull/4916

### CODE REVIEW

**Comment by Parlane** [comment]
@dolphin-emu-bot

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by Helios747** [comment]
@dolphin-emu-bot rebuild

**Comment by degasus** [comment]
The PR description lacks why you want to revert it.

**Comment by Helios747** [comment]
updated PR. Still don't know why buildbot won't touch it.

**Comment by Helios747** [comment]
Closing in favor of https://github.com/dolphin-emu/dolphin/pull/5133

**Pull request closed without merging**
