### PR TITLE
Disable bbox

### PR DESCRIPTION
**Pull request by degasus**
This PR adds a new GUI option for disabling bbox.
Also the unreachable (but on arm7) SW fallback is dropped now.

### CODE REVIEW

**Comment by degasus** [comment]
Why?? JitRegister.cpp:(.text+0x8): undefined reference to `SConfig::m_Instance'

**Comment by degasus** [comment]
@delroth Do you have an idea why the vertex loader unittest can't be linked?

**Comment by magumagu** [comment]
Are we just completely giving up on making games which require bbox playable on PCs which can't reasonably support the current HW bbox implementation?  We have the code; we could use it by disabling vertex loader JIT, even if the resuting performance is less than ideal.

In any case, just throwing a checkbox into the UI which people using certain GPUs must always check, and which does absolulely nothing on other GPUs, seems like a terrible idea.  We should be able to figure out whether we need to disable bbox in code, and not expose it to the UI.  Or if we really need to expose it to the UI because we can't come up with a good enough heuristic, we should at least put a good explanation into the UI, visible by default, and disable the checkbox in cases where it isn't relevant.

**Comment by lioncash** [comment]
I agree with @magumagu; having the functionality switch occur behind the scenes would be best if possible (and be less error-prone in terms of how users enable/disable settings).

**Comment by degasus** [comment]
@magumagu falling back to the old loader is easy, but I want to get rid of the hard videocommon - videosw dependency. At the moment we will call half of the software backend to get bbox support within the vertex loader. I just dislike this implemention very much.

**Comment by Ofunniku** [comment]
Muramasa is no longer eating my GPU (99% GPU usage, single digit framerate, CPU on idle)

Without switching to my testing profile, game easily hits 169 FPS/VPS in borderless fullscreen

**Comment by degasus** [comment]
I've fixed the linking error in the last commit, so BUMP.

We need a design decision here. Do we want to break a game (paper mario) without ogl4/d3d11 support? Or do we want to keep the in my opinion very ugly hack to include the software video backen within the ogl backend for software transformation?

In my opinion, it's just one game. And only on older GPUs. This isn't worth to keep the old path.

**Comment by shellashock** [comment]
Wouldn't dropping this hack break every other game that uses the bounding box in someway for GPU's not supported? (Even ones like Resident Evil that apparently use it for something that isn't readily apparent?) If this is true, I would expect some backlash like when D3D9 was removed. 

Even though I will be among those affected (Intel HD graphics in laptop), I also agree with degasus that it would be better to remove this than to keep the old path around. Hopefully there will be some improvements to bounding box support that allows the old GPU's to work again someday; but there are things of more importance for Dolphin then supporting the ability to use an old GPU to support a small pool of games (beloved they may be).

**Comment by degasus** [comment]
@shellashock Right now, this bbox "fallback" is disabled. So the game would also be broken on master. iirc Resident Evil just clears the bbox values, but it doesn't read them at all, so the emulation isn't required. It would just lead to a big slowdown. For intel HD, haswell does support OGL4.3, but I have no clue about ivy bridge. Does the current implementation works fine?

And I don't think there will be another implementation which support bounding box on older GPUs, but those GPUs will get older by time ;)

**Comment by MaJoRoesch** [comment]
What will be the default value for the BBox option? And will there be a gameini setting so it can be on or off by default for games that require it? I know that before it was default off and a gameini setting could be used to turn it on by default when needed, but I don't know how it will be applied here.

**Comment by degasus** [comment]
Here, it's default on, and there is a gameini option for it. But I'm also thinking about disable it by default.

**Comment by MaJoRoesch** [comment]
How many games use bounding box? Less than 10 out of 3000+? :P I think default off is a good idea, and just use the gameini to turn it on when needed.

**Comment by JosJuice** [comment]
If game INIs are used to enable it for games that need it, the user's bounding box setting would be ignored for those games, right? I don't see what the point of being able to turn off bounding box is if it doesn't affect games that use bounding box.

**Comment by degasus** [comment]
@MaJoRoesch default setting is now swapped

**Comment by shellashock** [comment]
@degasus I am using an old Intel Core B940, so my Intel HD Graphics version is probably the original version lol (IIRC it is the HD 2000 variant). Yes, these games are broken on master to me; I was just thinking that if this was merged and then removed later down the road (which is not going to happen judging by other people's sentiments), that there would be backlash for people not being able to play these games or at severely reduced speeds.

I didn't think it would be likely for these older GPU's to be supported any longer because they are almost certainly not helping the emulation of the games in the first place. But again, even though it will hurt not being able to play PM:TTYD until I get a new computer; it is better for long term Dolphin development to remove this now and get the sting over with. Besides, there are many powerful GPUs (compared to the penny pincher's GPUs that is), that have dropped dramatically in price recently; so it is not that big of a deal these days.

**Comment by degasus** [comment]
So how do we want to continue?

**Comment by MaJoRoesch** [comment]
In our IRC discussion, we came to a consensus that the more accurate option should be default on, and any games that need it can have bbox disabled by default in the gameini. That way if any random unknown game uses bbox and we don't know about that, it would show problems and we'd learn about it when a user complains. ...ok that's not very likely but it's a healthy practice!

**Comment by degasus** [comment]
@MaJoRoesch I've changed the behavior again: Now bbox is enabled by default, and both game inis + gfx option is parsed to disable it. Do we want both, gui + game ini?

**Comment by MaJoRoesch** [comment]
How often will it need to be disabled? How many cases are known where it misbehaves? If it's only like, one or two, then users would access it so infrequently that I don't really think there's a reason to fill GUI space with it.

**Comment by degasus** [comment]
I guess there are like 20 to 100 games which clears this register without using them :/

**Comment by MaJoRoesch** [comment]
Oh... that's a lot more than I thought. It will probably need a GUI option then, so the users can experiment with it and the wiki inform people of this.

**Comment by degasus** [comment]
@MaJoRoesch So shall I swap again?

**Comment by Sonicadvance1** [comment]
Make it default disabled so the Game INI files can be set in the games that require it.

**Comment by BhaaLseN** [comment]
I'll just leave this here: BhaaLseN@6d7081ee4e603ac02abbfec57d84eb7770b436d2.

As said on IRC:
> -16:37:18- [Bh44L] MaJoR1: i made a test branch yesterday that disables bbox after a frame
> -16:37:40- [Bh44L] since various sources seem to indicate an intended clearbbox -> render geometry -> readbbox cycle if you want to use it
> -16:37:52- [Bh44L] but it seems i dont have any useful games to try this out
> -16:38:17- [Bh44L] and i'm a bit hesitant to create a pr for something where i dont have any clue on what it actually does nor whether i could even go and test this in a useful way

Maybe someone else (\*looks at JMC\*) can give it a shot and see if this even makes sense and doesn't break anything.

**Comment by Linktothepast** [comment]
So we are basically reverting to the old behavior. Seems good since the enabled by default for everyone and every game didn't work out that well.

**Comment by degasus** [comment]
No, it's disabled by default, but raise an ERROR_LOG if it's used but enabled. So we hopefully get noticed for broken games

**Pull request merged**
