### PR TITLE
Audio: new dsp_coef.bin with windowed sinc filter coefficients

### PR DESCRIPTION
**Pull request by stgn**
Replaces the old linear interpolation coefficients with windowed sinc filter coefficients closely matching those from the Nintendo ROM, reducing aliasing artifacts in resampled audio.

Comparison:

### CODE REVIEW

**Comment by delroth** [comment]
Can you provide a reproducible way to generate these coefficients?

**Comment by stgn** [comment]
Yes.

https://gist.github.com/stgn/23a6f1dccbbf213bd808

**Comment by RisingFog** [comment]
@dolphin-emu-bot rebuild

**Comment by BhaaLseN** [comment]
Maybe include that script in the Tools folder or something like that?

**Comment by delroth** [comment]
LGTM if we can get this tool checked in as @BhaaLseN said.

**Comment by RisingFog** [comment]
@dolphin-emu-bot rebuild

**Comment by shuffle2** [comment]
nice!

**Pull request merged**
