### PR TITLE
Change JC4E01.ini to use ascii single quote

### PR DESCRIPTION
**Pull request by Parlane**

### CODE REVIEW

**Comment by Buddybenj** [comment]
Thanks for this. This will fix the merge conflicts in PR #1890.

**Comment by Parlane** [comment]
@Buddybenj This won't fix your issue as there is another game that uses the curved single quote. This pr was a test to see what central is doing with the diff.

**Comment by degasus** [comment]
please use your own fork for PRs :/

**Comment by Parlane** [comment]
@degasus This is not a real PR. I was testing what Github was doing when it created the patch.

**Comment by CarlKenner** [comment]
Why is there a single quote there anyway?
That is just a comment, right?
Or is there something exact I have to put there when I add my own ini files?

**Comment by Parlane** [comment]
@CarlKenner It's just grammatically correct, no technical need for it to be.

**Comment by Buddybenj** [comment]
@Parlane Oops, I was on mobile so I didn't see the Buildbot. Good to see it's not a problem on my end though. Perhaps we should try to delete the file, push the changes, then add the file back in with the ASCII single quote instead (I don't know if that would work or not).

BTW, I did a search and confirmed that JC4E01 is the only one that does have the curved (non-ASCII) single quote. What other game did you think used the curved quote?

**Comment by Buddybenj** [comment]
Any news on if the issue with the Buildbot is going to be fixed soon?

**Pull request merged**
