### PR TITLE
WIP: FrameDump: Multiple Upgrades, Reimplement API, Proper VFR, CFR and TAS Support

### PR DESCRIPTION
**Pull request by altimumdelta**
The FFmpeg external has to be updated for any of this to actually work on Windows. Currently it is not certain yet what kind of FFmpeg integration will be chosen, it's up to the community, I have initially provided the static method here #8123 while the other delayed-dynamic method is here #7110 

There is also a testing branch with all the dependent commits combined: https://github.com/altimumdelta/dolphin/tree/FrameDumpUpgradeCOMB
Which I'll keep up to date as development continues.

---
### Merged PRs:
- [x] #8128 - Code Refactor: Rename AVIDump to FrameDump
- [x] #9182 - FrameDump Fixes & Cleanup

### Merged Improvements:
- #9182 - Changes to frame dump timing code ("PTS code")
- #9182 - Output filename format standardized with the one used by screenshots (GAMEID + Timestamp), while the original timestamp from when the frame dump was manually started will be preserved,during automatic splits.
- #9182 - Framedump will now create a new file (restart) on VI refresh-rate change and savestate load
 

### PRs Pending Review:
- [ ] #9188 - FrameDump: Remove code for older versions of libavcodec

### PRs Ready To Merge:
- nothing yet

### Work In Progress (altimumdelta):
- [ ] Error messaging standardization

### Long-term ToDo Overview:
- [ ] Support different codec/container combinations separately, with their own defaults/configs.
- [ ] more to be added as development continues

----

## Variable frame rate (VFR) and video editor compatability support - MPEG-TS / Matroska

Similarly to the recent FFV1 BGRA->BRG0 patch tackling inoptimal output, the AVI container format it self is not optimal since it doesn't really support variable frame rate (VFR) and may lead to compatability and playback issues if there are any frame rate changes during dumping. It is possible only with hacks and those create a non-standard AVI file. The initial purpose of this PR was to support it if it does happen during the existing method of correcting for game-speed, not that the dump output has to be the same as original game-speed (variable FPS) according to performance, but with such support the original behavior can be dumped optionally for some other purpose, possibly testing and troubleshooting. 

If there were any hacks done within Dolphin to compensate for AVI limitations then those would need to be looked at, and probably removed. I'm merely speculating right now as I'm not sure if any of them exist at this moment, it does seem to work fine as is.

Optimally I chose Matroska as the container format which is actually designed for VFR and suitable for flexibility within Dolphin, with multiple encoders, in case more get added later as well (possibly even GPU Accelleration, etc).  

However Matroska still isn't supported as much with video editing softwares, but thankfully MPEG-TS, another container supporting VFR, is and it works right there in Adobe Premiere Pro CC 2019 along with Premiere's VFR support which was added back in 2018 https://www.premierebro.com/blog/premiere-pro-1201-update-variable-frame-rate-and-new-features

FrameDump_MPEG-TS_AdobePremiereProCC2019

However this is where the good news ends, MPEG-TS isn't as flexible in terms of codec support as Matroska is, which means FFV1 can't be used with it, it will need it's own defaults, and it makes things a bit more complicated for this PR than I initially estimated.

## TAS Videos Support - AVI

In addition, because there is also TAS videos which have their own specific need this will be a more dynamic solution which would satisfy multiple use cases, so AVI support will be kept no matter what for those that rely on it.

---

## Future Thoughts

One of the possible proper solutions is to simply defer encoding, so it doesn't need to encode in real-time and at full speed, including that the ffmpeg's/encoder's encoding threads shouldn't be allowed on the same CPU core-s which Dolphin's threads already occupy, but that depends on Dolphin's threads actually sticking to their own CPU core's as well (not just logical, but physical). Also the thread affinity separation could only be used when Dolphin is actually framedumping.

https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Common/Thread.cpp#L43

Furthermore it would also help to look at the ffmpeg and encoders them selfs for any already built-in throttling capabilities. And, any ideas if the throttling should be done on the externals outside this project or can/should it be done within Dolphin?

Such a solution would require additional storage space to save a temporary recording file, the deferr does not need to be absolute, meaning that it only starts encoding after the user is finished recording, but that it does encode at a certain speed and behavior (explained above) that does not slow Dolphin down, which can be used to help keep down the size of the temporary file as the old unnecessary frames which were already encoded can be deleted regularly (in batches, easier on FS).

### CODE REVIEW

**Comment by Techjar** [comment]
MKV is supported by very few video editors (even the popular ones like Adobe Premiere and DaVinci Resolve don't support it), so this doesn't seem like a good change.

**Comment by altimumdelta** [comment]
@Techjar 
> MKV is supported by very few video editors (even the popular ones like Adobe Premiere and DaVinci Resolve don't support it), ~so this doesn't seem like a good change.~ Then again, I guess AVI isn't well supported either, so it doesn't really make a difference.

Already went looking into that and I think I found a "temporary" alternative as we speak.

> I'm confused about the "windows-only" bit though.

Yeah that was only referring to one commit, I've spinned that one away there: #8123

**Comment by stenzek** [comment]
FWIW, the encoding is already asynchronous and occurring on a background thread, it's just only allowed to lag up to one frame behind emulation.

**Comment by vadosnaprimer** [comment]
Does it allow for any frame perfect importing into avisynth?

**Comment by altimumdelta** [comment]
@vadosnaprimer 
It's not really hardcoding, you can choose any of the supported encoders and container formats from the INI configuration like before, the only hardcode right now is lack of AVI container support, which I was having second thoughts about anyway.

Are you referring to this: 
> "M2TS, TS: Seeking seems to be off a few frames here and there" 

MPEG-TS files can come in many different ranges of qualities depending on various factors (DVB-T/C/S, DVD, etc) so are you sure this is a general MPEG-TS issue? 

Anyway we'll first need to be sure what kind of behavior a Dolphin produced .TS is showing. Have you actually tested a .ts file that is produced by this PR?

**Comment by vadosnaprimer** [comment]
What's the ini option's name? Are there docs describing it?

I don't have the build environment right now so I can't test the produced file.

The problem is generally with ffmpeg-based importer plugins that don't do the job perfectly.

**Comment by altimumdelta** [comment]
@vadosnaprimer 
Rest assured that we will eventually find a solution that works for both use cases, including adding more support in subsequent PRs if necessary. Right now we simply have to put it all down on the table so we know what we're dealing with, but it's also time for others to step up and in my opinion it's not fair for one project to always keep adapting to whatever's out there, a line has to be drawn somewhere, surely we're not going to be stuck with AVI forever, for example. I didn't happen to develop this PR with TAS in mind but no problem, we'll figure it out now.

If you or anyone else is experienced in TAS, which I'm not, so I'll have to do some catchup, you can test the files here: 
[Dolphin_8121-framedump-MP1_MPEG-TS_MPEG4.zip](https://github.com/dolphin-emu/dolphin/files/3224143/Dolphin_8121-framedump-MP1_MPEG-TS_MPEG4.zip)

 ... only MPEG4 encoding tho.

I completely forgot, you can't have FFV1 in MPEG-TS unless doing some private-stream tricking which may not be worthwhile to mess around with, so this makes this very interesting again, indeed I was planning on updating this part of Dolphin in many ways and it looks like it'll need a few PRs to get there.

**Comment by altimumdelta** [comment]
Oh I only now realized the PR separation effect, can't test/develop one without the other.
For anyone to test this locally, it'll take getting both branches and cherry-picking to combine all the commits.

**Comment by vadosnaprimer** [comment]
> Right now we simply have to put it all down on the table so we know what we're dealing with, but it's also time for others to step up and in my opinion it's not fair for one project to always keep adapting to whatever's out there, a line has to be drawn somewhere, surely we're not going to be stuck with AVI forever, for example.

Have you looked at the code I linked? Allowing the client to use **all** the ffmpeg functionality freely is the best solution. Until then you hardcode things you explicitly allow, in this case it's the container, and apparently the encoder. ffmpeg capabilities are incredible, and everyone can get what they need from it, so I don't see how limiting which part of it is accessible is bringing us to productive future where we won't have to adapt every time. Explicit support for just a few of its features **is** adapting.

> When you say lossless you mean FFV1 right?

There are other lossless encoders ffmpeg can use, but from our tests, it's the one that's the easiest to use, the most compatible and reliable one, relatively fast, with reasonable compression. It's not there out of whim, it's actually good.

**Comment by altimumdelta** [comment]
@vadosnaprimer 
> Have you looked at the code I linked? Allowing the client to use **all** the ffmpeg functionality freely is the best solution. Until then you hardcode things you explicitly allow, in this case it's the container, and apparently the encoder. ffmpeg capabilities are incredible, and everyone can get what they need from it, so I don't see how limiting which part of it is accessible is bringing us to productive future where we won't have to adapt every time. Explicit support for just a few of its features **is** adapting.

Which code specifically? Those are 3rd party tools which aren't part of Dolphin so I'm not familiar with any of it. Moreover I haven't done anything with AVISynth before.

I'm not limiting anything, everything else remains the same, the only thing that's removed currently is AVI support. Are you sure the other devs would be okay with a +50 megabyte bigger Dolphin executable from this point onward if I include the full FFmpeg package? Doubt it.

When you're talking about the Windows version of Dolphin in regards to dumping frames with FFmpeg then you have to talk about specifics, Windows version currently supports only the AVI container format, MPEG4 and FFV1 encoders, nothing else. 

Here is the relevant part of the current actual configuration used for compiling the FFmpeg static libraries for use within Dolphin:
`--disable-avdevice --disable-programs --disable-avfilter --disable-postproc --disable-doc --disable-pthreads --enable-w32threads --disable-network --disable-everything --disable-encoders --disable-muxers --disable-hwaccels --disable-parsers --disable-protocols --enable-static --disable-shared **--enable-muxer=avi --enable-encoder=ffv1 --enable-encoder=mpeg4** --enable-protocol=file`

With this PR that support is expanded to a number of containers and encoders I've mentioned above.

It's more efficient obviously to only include the features which will be used within Dolphin most of the time, if you're talking about "VfW" which implies the Windows platform then you either haven't used the Windows version of Dolphin, or you haven't really tested an actual Dolphin framedump and you're comparing codecs and AVISynth behavior with non-Dolphin produced videos, which is also evident because you didn't know about the INI overrides, so you should actually first produce a real Dolphin generated framedump and test that, but that's currently only possible with other platforms where Dolphin has access to the full FFmpeg or whatever from the OS.

For general testing ofcourse using non-Dolphin generated video which is fine, but without jumping to conclusions whether it'll work or not.

I do agree it's a bit confusing with this windows-specifics, everything in this PR affects every platform, but, we're limited by Windows, or, the Windows path needs it's own valid settings, or I would have to first build another static lib and include another encoder/muxer. 

You just need to explain what the problem is right now and what do you wish me to do. But forget about MPEG-TS for FFV1, that'll go back to MKV.

**Comment by vadosnaprimer** [comment]
> Which code specifically? Those are 3rd party tools which aren't part of Dolphin so I'm not familiar with any of it. Moreover I haven't done anything with AVISynth before.

The only code I linked is this
https://github.com/TASVideos/BizHawk/blob/master/BizHawk.Client.EmuHawk/AVOut/FFmpegWriter.cs
https://github.com/clementgallet/libTAS/blob/master/src/library/encoding/AVEncoder.cpp

> I'm not limiting anything, everything else remains the same, the only thing that's removed currently is AVI support. Are you sure the other devs would be okay with a +50 megabyte bigger Dolphin executable from this point onward if I include the full FFmpeg package? Doubt it.

That's a fair point, libTAS uses ffmpeg that's installed in the system, bizhawk ships ffmpeg.exe, and it's no small.

> It's more efficient obviously to only include the features which will be used within Dolphin most of the time, if you're talking about "VfW" which implies the Windows platform then you either haven't used the Windows version of Dolphin, or you haven't really tested an actual Dolphin framedump and you're comparing codecs and AVISynth behavior with non-Dolphin produced videos, which is also evident because you didn't know about the INI overrides, so you should actually first produce a real Dolphin generated framedump and test that, but that's currently only possible with other platforms where Dolphin has access to the full FFmpeg or whatever from the OS.

I don't see how using Dolphin dumps that are compatible with VfW editing tools (avisynth, virtualdub) means that I haven't tested Dolphin, its Windows version, or I'm talking about non-Dolphin dumps. I don't know about overrides because what is there in the UI has been enough for tasvideos needs. I'm still interested in seeing docs on what options are available for those overrides.

> You just need to explain what the problem is right now and what do you wish me to do. But forget about MPEG-TS for FFV1, that'll go back to MKV.

I need a lossless dump so I could test importer tools I mentioned against it. Having different containers means different importers are available/required. If there's no way to have a lossless dump in .ts, there's no point in testing that in avisynth.

BTW I'm still waiting for an answer when Dolphin needs to use VFR.

**Comment by altimumdelta** [comment]
@vadosnaprimer 
> I need a lossless dump so I could test importer tools I mentioned against it. Having different containers means different importers are available/required. If there's no way to have a lossless dump in .ts, there's no point in testing that in avisynth.

Yes, but you need to avoid using the term _lossless_ vaguely like that, it's about the codec and container combination, you can have _lossless_ H.264 inside MPEG-TS if you want, for example. You simply need to tell me what is it that you want, **specifically.** :) 
I cannot include the whole FFmpeg package for consideration, at least highly unlikely, however I think I'm starting to understand what you meant, maybe, it can be done only for testing temporairly then, a test branch can be created with the full blown FFmpeg integrated into dolphin. Is that what you're asking for?


> BTW I'm still waiting for an answer when Dolphin needs to use VFR.

Dolphin corrects the variating FPS in-game to have the video playback at correct speed in the resulting frame dump, right, so to clear this out, I'm didn't mean to use term VFR (variable frame rate) initially as in the context of actually having a VFR video like in-game, which actually would then be possible to add as an option for some other purpose, but there's a bunch of timing stuff going on under the hood that doesn't make it strictly CFR. There's minute differences which aren't as obvious in practice on first glance, if you force that into something that doesn't do VFR then it may produce glitches with various things like video editors, it may produce A/V desync for longer videos, and bunch of things I can't immediately explain right now. I can tell you more later when I go into that again.

Secondly the FFmpeg implementation code should also get a refresh and some things have probably changed in the FFmpeg API since the time it was first introduced into Dolphin. This is infact also a prerequisite to all of those improvements, even if it may not be strictly necessary, it's safer for proper development for that risk to be completely avoided.

**Comment by MayImilae** [comment]
Will it be the possible to configure CFR vs VFR and the bitrate? If so, where are the controls? And what are the defaults you are using?

**Comment by altimumdelta** [comment]
Sure, but the scope of this PR would have to expand, I don't have any of that developed/thought out yet, I haven't forseen this twist. 

Maybe this should get a WIP label.

**Comment by MayImilae** [comment]
I brought this up since because there are a lot of different use cases for recording video of Dolphin, some will greatly benefit from VBR, and some really need every single frame. Testing for example, and like, deep analysis of game animation, really need every frame.

**Comment by altimumdelta** [comment]
I see, interesting, well thanks for bringing it up so I can plan ahead with this in mind. Now did you actually mean VBR or was that a typo? But yes, variable bit rate should also be something to think about later on, however that could have something to do with buffering and because it's not allowed to lag more than 1 frame that may be in conflict.

**Comment by thecoreyburton** [comment]
It's great to see more progress being made to the video dumper!

I've had a fair bit of dumping with Dolphin in the past (some of which was specifically dealing with sync and VFR situations) and I have a few questions and concerns. I'm hoping they're not too irritating, but I don't have access to any reasonable PC (and potentially won't during this pull request's life span) and want to be thorough.

1) What's being defined as VFR here? Is this exclusively targeting rate changes in games (such as PAL titles which begin at 50 and switch to 60) or any variance in frame timings (such as held frames during loading areas)?

2) From what I've experienced in the past, ffmpeg dumping dumps at a flat 60fps. This leads to a dropped frame (and potentially duplicates, I'm unsure) every once in a while as this frame rate is not correct. This can be compared on early 4.0 revisions where ffmpeg dumping had been enabled on Linux, but not Windows. I typically dumped prolonged segments of games, removed the duplicate frames and aligned the footage on a frame-by-frame basis (desyncs in the line-up are typically one-way, so you can seek to locate the issues faster). Eventually, you'll come across an extra frame in the dump done on Windows (though the dumping was still broken at this point). As far as I know, [this](http://tasvideos.org/forum/viewtopic.php?p=373299#373299) provides the correct rate. I may also be mistaken or the information may be outdated.

I'm unable to see if this pull request resolves the problem, but if not, is this something that could affect this? I'm concerned that this could somewhat nullify the point of supporting multiple frame rates if they're all incorrect. If this problem doesn't affect anything and can be sorted out later, then you're welcome to ignore this.

3) I don't see a point in adding .ts specifically. I think MKV is definitely the superior option. It not only supports VFR, but a whole host of other features that could (potentially) be utilized later. The downside (as has already been noted) is that it's not as widely supported as .ts, but from what I've experienced usually if MKV has trouble, so does VFR (often being imported as a CFR clip, without duplicating or dropping frames, leading to an often sped-up video). What are the advantages of using .ts here?

4) You asked @vadosnaprimer what his requirements are and I can definitely elaborate here. I'm also from TASVideos and I specifically tackle 3D consoles and some of the more difficult encodes. We require lossless rgb. The codec itself isn't important, but we simultaneously want as small a file size as possible whilst still having relatively fast seek times at high resolutions (4K+). 

We need to import the video file into AVISynth for processing. _Note: I got on a bit of a tangent here. I was going to remove or reword it, but I've kept it in case some of the details end up being relevant. If you'd like to skip past this paragraph the end result is that we require AVI._
This can be done a number of ways, such as using the internal AVISource function or the external FFMS2 (FFVideoSource) or LSMASHSource (LWLibAVVideoSource) plugins. AVISource only supports AVI, but relies on installed codecs for decoding (in this case, LAV filters). It's frame-perfect, it loads instantly and you can seek anywhere in the video file without it breaking, FFMS2 and LSMASH load using LibAV (and so support most containers, such as .avi or .mkv), though both have to create an index of the keyframes. A 3 hour long, 4K dump which is over 1tb in size takes hours on this alone, and the results are not fantastic. FFMS ends up dropping frames frequently. I'd estimate 1/5th of the frames are missing and the loaded frame rate reflects this (being somewhere around ~47fps). If you force a frame rate upon loading, such as 60/1, it will not load the additional frames but rather duplicate frames from the ~47fps stream to accomodate this. Interestingly enough, if you force 60000/1001, it behaves differently and many more frames are present (though still not all). This leads me to conclude that FFMS2 is unreliable. LSMASH fairs a bit better. The initial result is the same, with 1/5th of the frames missing, but when you force the rate to 60/1 the results showed that over an hour long clip there were no deviations. This is a positive sign, but I'm still very wary of these source filters as they're built using the same libraries.

Back on track, there's no perfect situation for what we require in terms of compression and also usability, but @vadosnaprimer and I did some [extensive](http://tasvideos.org/forum/viewtopic.php?t=19537) [testing](http://tasvideos.org/forum/viewtopic.php?p=473878#473878) and concluded that as of his last pull request (which fixed a problem where FFV1 couldn't be decoded by VFW and therefore AVISource), the current FFV1 encoding settings are likely the best we're going to get and whilst the AVI format is very old and severely limited, it's the most appropriate for this kind of processing. As far as I remember, ffvhuff wasn't used in these tests. It's not a codec I'm familiar with though, so it's something I'll have to look in to.

The move to VFR dumping feels is overdue and there's no doubt that MKV is a good end-user format, but I'm not sure what portion of users will be using that file directly in it's dumped state. I'd guess there'd be at least a few people trimming, cutting, resizing (or excessively processing, in my case) these further. VFR MKV definitely feels like the best-fitting solution, but I'd like to have access to something more compatible with all these editing scenarios when lossless is enabled (eg: Frame Dumps Use FFV1 could be replaced or complimented witrh with Frame Dumps Use Compatibility).

The alternative here would be a custom command line (even if it means the user has to specify their own provided ffmpeg executable location when this option is enabled). 

Anyway, sorry to bring up so much in one post and apologies if some of the answers are obvious.
I'm really looking forward to seeing how this all turns out!

**Comment by thecoreyburton** [comment]
Quick note: This is my second revision of this post. When I wrote the first, the page hadn't loaded correctly and I missed a significant chunk of discussion (that answered some of my questions) and so I removed it in favour of rewriting it, save responses repeating information.

It's great to see more progress being made to the video dumper!

I'm also from TASVideos and I specifically tackle 3D consoles and some of the more difficult encodes. I've had a fair bit of dumping with Dolphin in the past (some of which was specifically dealing with sync and VFR situations) and I have a few questions and concerns. I don't have access to any reasonable PC (and potentially won't during this pull request's life span) and so my test files do not come specifically from this version of Dolphin, but I've tried to faithfully re-create appropriate files for my demonstrations and tests. If anything comes into doubt, I'm happy to redo anything (when I can). Also, apologies for the length and if some of these answers are obvious, I'm just trying to be thorough.

What's being defined as VFR here? Is this exclusively targeting rate changes in games (such as PAL titles which begin at ~50 and switch to ~60) or any variance in frame timings whatsoever on a frame-by-frame basis?

From what I've experienced in the past, Dolphin's ffmpeg dumping is set at a flat 60fps. This leads to a dropped frame (and in theory, duplicates, though I've not come across that) every once in a while as this is not the correct rate. This can be compared on early 4.0 revisions where ffmpeg dumping had been enabled on Linux, but not Windows. To test this, I typically dumped prolonged segments of games, removed the duplicate frames and aligned the footage on a frame-by-frame basis (desyncs in the line-up are typically one-way, so you can seek to locate the issues faster). Eventually, you'll come across an extra frame in the dump done on Windows (though the dumping was still broken at this point). As far as I know, [this](http://tasvideos.org/forum/viewtopic.php?p=373299#373299) provides the correct rate. I don't know why this was introduced and I'm unable to see if this pull request resolves the problem, but if not, is this something that could negatively affect this? I'm concerned that this could somewhat nullify the point of supporting multiple frame rates if they're all incorrect.

> However Matroska still isn't supported as much with video editing softwares, but thankfully MPEG-TS, another container supporting VFR, is and it works right there in Adobe Premiere Pro CC 2019 along with Premiere's VFR support which was added back in 2018 https://www.premierebro.com/blog/premiere-pro-1201-update-variable-frame-rate-and-new-features
I use CS5 for most Creative Suite tasks and so I can't speak for Premiere Pro here, but I do have After Effects CC 2019. I often work with VFR live-action sequences and have had no trouble importing VFR MKV files in the past. For reference, the source files are typically AVC encoded with FLAC audio and use any combination of the following frame rates: 24000/1001, 30000/1001 and 60000/1001 (this includes cases of all three). Given Matroska's flexibility and support here, I really don't see any advantage for .ts.

My next concern here is compatibility. You asked @vadosnaprimer what his requirements are and I can definitely elaborate here. We require a lossless RGB that can be reliably loaded into AVISynth. The codec itself isn't important, but we simultaneously want as small a file size as possible whilst still having relatively fast seek times at high resolutions. I've had to deal with several cases of 4K dumps with resulting file sizes that are well over one terabyte in size and I've had to make frame-perfect adjustments to these dumps, which is when these factors become absolutely crucial.

There's no perfect situation for what we require in terms of compression and also usability, but @vadosnaprimer and I did [some](http://tasvideos.org/forum/viewtopic.php?t=19537) [testing](http://tasvideos.org/forum/viewtopic.php?p=473878#473878) and concluded that as of his last pull request (which fixed a problem where FFV1 couldn't be decoded by VFW and therefore AVISource, see below), the current FFV1 encoding settings are likely the best we're going to get. There's always room for improvement though and as far as I remember, ffvhuff wasn't considered in these tests. It's not a codec I'm familiar with, and so it looks like I have some interesting tests to do at some point.

As far as AVISynth is concerned, we need a method that can load the dump and also be frame-accurate. That means there are typically three relevant methods we can use to import the video file.

1) The first is AVISource, which loads the file using installed codecs (in this case, LAV filters). Loading is instant, frame seeking is accurate and it does everything we want. It's also internal, meaning no additional plugins are required to use it beyond the installed codecs. The limitation here is that it requires an AVI file.

2) The second is FFMS2 (FFVideoSource), which can doesn't have that limitation and can instead open any any container and decode any stream supported by LAVF. It also requires the file to be indexed for keyframe locations in order to maintain frame-accurate seeking. This isn't necessarily a problem, but it can take several hours on larger files. The problem with FFMS2 is that in all of my tests, it dropped an excessive amount of frames. I'd estimate it at 1/5 of the total, and the frame rate was around ~47fps, also reflecting this. It does have a parameter to specify the source frame rate (for loading VFR clips), but when fed 60/1 it simply duplicated frames from the ~47fps clip instead of loading additional unique frames. Interestingly, if I specify 60000/1001 as the frame rate (despite the file being 60/1) it loads a vast majority of the frames, with the drops being much more infrequent. This is not the only trouble I've had with FFMS2 (it's also dropped audio samples from WAV files, for instance), and so I'd go as far as saying it's completely unreliable and should not be used in any important sense.

3) The third is LSMASHSource (LWLibAVVideoSource). It shares a lot of properties with FFMS2, such as the need to index the file and is even built on the same libraries. It shares the same initial problem of loading the file with about 1/5 of the frames dropped and the rate being reported as ~47fps, but when 60/1 is specified the file loads correctly. This was confirmed by doing a subtraction test, using footage that lasted just over an hour long at 4K. The resulting file had a single keyframe, indiciating that no frames had been dropped or loaded incorrectly. Despite this, I still have concerns (due to it's similarities with FFMS2) and when faced with one of the older Dolphin FFV1 dumps (before the compatibility pull request), I would transcode from FFV1 .avi to FFV1 .avi with those compatibility settings using ffmpeg, as it would allow usage of AVISource, which is guaranteed to be reliable.

The concencus currently seems to be that in addition to lossless rgb, decent compression and decent seek times, we also require .avi for compatibility. In simple VFR situations (no individual frame-time variance, but complete rate changes such as 50 > 60), this is typically handled via a modification to split the file when such a change is detected. This enables each AVI segment to be CFR and maintain maximum compatibility with most major editing software (I've tested this using After Effects, Premiere Pro, Vegas and AVISynth).

The move to VFR dumping feels overdue and there's no doubt that MKV is likely the best candidate for a single-file VFR output, but I'm not sure what portion of users would be able to properly take advantage of it. It definitely feels like the best end-user format and the best for modern, high-end video processing software but these packages are expensive and the chances of a majority of users having access to them is open to speculation. I'm stuck with CS5 for most of the Creative Suite and both it and AVISynth can't do much here. At the same time, I don't like the idea of the limitations of software dictating the limitations of other software. It gets in the way of good progress.

As far as possible solutions go, I'm not too sure what the best route would be. VFR MKV definitely feels like the best-fitting solution, but I'd like to have access to something more compatible with all these editing scenarios. Things that come to mind are perhaps a VFR/CFR toggle (default VFR), that switches between a single MKV or a split-on-rate-change AVI, though depending on handling hacks required, this could be an awful suggestion. Another alternative here would be a custom command line (even if it means the user has to specify their own provided ffmpeg executable location when this option is enabled). I'm honestly not sure.

Anyway, sorry to bring up so much in one post and apologies if some of the answers are obvious. I'm really excited to see the start of a proper VFR implemenation and I'm looking forward to seeing how this all turns out!

**Comment by mbc07** [comment]
On the scope of shipping a tailored, statically linked ffmpeg build with Dolphin vs shipping the full ffmpeg binary, [this PR might be relevant](https://github.com/dolphin-emu/dolphin/pull/7110). From what I could tell it allowed users to manually provide a full ffmpeg library, thus enabling all available codecs and containers, without bloating the Dolphin binary by statically linking ffmpeg...

**Comment by vadosnaprimer** [comment]
> Yes, but you should avoid using the term _lossless_ vaguely like that, it's about the codec and container combination, you can have _lossless_ H.264 inside MPEG-TS if you want, for example. You simply need to tell me what is it that you want, **specifically.** :) Some codecs are inhernetly lossless, like FFV1, you can now also can try FFVhuff, it's said to be faster.

I don't think it has [a lot of definitions regarding video](https://en.wikipedia.org/wiki/Lossless_compression#Video).

Theoretically, it doesn't matter which lossless encoder is used. But in practice, their compatibility varies broadly. The currently used configuration of FFV1 has the highest compatibility I've seen. Lossless mode of x264 is good, but its compatibility is lower. It results in seeking problems and [sometimes even glitches](http://tasvideos.org/forum/viewtopic.php?p=474070#474070) when imported into avisynth directly. To compensate for that, we could use an importer filer as Corey has explained. But in order to figure out which importer we should focus on, we need to know which lossless encoder options are available for the given container that Dolphin is using.

> I cannot include the whole FFmpeg package for consideration, at least highly unlikely, however I think I'm starting to understand what you meant, maybe, it can be done only for testing temporairly then, a test branch can be created with the full blown FFmpeg integrated into dolphin. Is that what you're asking for?

As linked by @mbc07, full-blown ffmpeg doesn't even have to be shipped with the Dolphin binary. That'd be an entirely different approach than this PR is taking, so I don't know where we want to discuss it - here or in that other PR comments.

> The scope of this PR would have to be expanded, solution like I thought earlier wouldn't be useful. I'll probably have to add some lossless option to the MPEG-TS, etc, but I didn't plan time-wise for that right now. It may be easier to bring back AVI container support, without being the default.

I'm fine with that as long as the _current_ functionality remains available.

> > BTW I'm still waiting for an answer when Dolphin needs to use VFR.
> 
> Dolphin corrects the variating FPS in-game to have the video playback at correct speed in the resulting frame dump, right, so to clear this out, I didn't mean to use term VFR (variable frame rate) initially as in the context of actually having a VFR video like in-game, which actually would then be possible to add as an option for some other purpose, but there's a bunch of timing stuff going on under the hood that doesn't make it strictly CFR. There's minute differences which aren't as obvious in practice on first glance, if you force that into a container that doesn't support VFR then it may produce glitches with various things like video editors, it may produce A/V desync for longer videos, and bunch of things I can't immediately explain right now. I can tell you more later when I'll be going into that in depth.

I'm not convinced footage GC/Wii generates is fundamentally VFW. The configuration that determines the exact framerate (which is never internally equal to 50 or 60) is internally present in Dolphin code, and [the tasvideos post](http://tasvideos.org/forum/viewtopic.php?p=373299#373299) has it covered. This framerate doesn't seem to change as long as the TV standard mode isn't changing in the game (NTSC <-> PAL). So I believe framerate remains constant outside of this scenario, which not a lot of games do.

Dolphin has explicit code to change the fractional framerate of the console to flat 50 or 60, so I guess it's by design, and I don't think it's just a random mistake. Even if this rounding gets removed, the console isn't supposed to generate a VFR video the way we know it. From my talks with @RisingFog, dropping duplicated frames before they go into the dump was also a design decision, and now with flat framerate output, it doesn't seem to belong anymore.

**Comment by altimumdelta** [comment]
> On the scope of shipping a tailored, statically linked ffmpeg build with Dolphin vs shipping the full ffmpeg binary, [this PR might be relevant](https://github.com/dolphin-emu/dolphin/pull/7110). From what I could tell it allowed users to manually provide a full ffmpeg library, thus enabling all available codecs and containers, without bloating the Dolphin binary by statically linking ffmpeg...

That's indeed another valid way of doing it. The method of FFmpeg integration for the Windows version of Dolphin should be the first thing to clear up. It's not practical for me to commit to anything further before this is decided. 

Nothing's wasted though, I've wanted to build ffmpeg from scratch myself not only for the experience but also for an unrelated project.

On the other hand it only conveniently works as long as someone is providing/hosting the .dll files for the community, hopefully Zeranoe does and it looks like 2-3 years is okay, before Dolphin will need another update, in that case.

Other questions will take some time to respond to, however I would like to ask a question ahead: why do you guys need to use AVISynth in the first place?

**Comment by vadosnaprimer** [comment]
> why do you guys need to use AVISynth in the first place?

It's what the workflow has been for more than a decade. There are thoughts about completely rewriting it, but I'm the only person who can push this forward and I don't have time. The goal is switching to vapoursynth. So for now, non-avisynth encoding is completely out of question for tasvideos.

**Comment by altimumdelta** [comment]
@vadosnaprimer 
Allright, I think I've got the draft of it figured out what I should do.

But I can't do anything substantial except some minor stuff until the community decides what kind of FFmpeg integration is most suitable for the Windows version, this wasn't a big deal since two big methods it's good to have them both testable and on the table, but I wouldn't want to commit to any further work until a choice is confirmed. Either way, AVI support will be kept.

**Comment by altimumdelta** [comment]
It seems the sentiment is that the Delay-Loaded method is preferred, via LoadLibrary+GetProcAddress, with that out of the way should make things immediately easier going forward, a PR for that does not exist yet tho.

Coincidentially after some time of having to deal with unrelated chores, work has started again for this PR :)

**Pull request closed without merging**
