### PR TITLE
Movie: Improve handling of non-hexadecimal revision strings

### PR DESCRIPTION
**Pull request by JosJuice**
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3872)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/Movie.cpp, line 1399 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3872#-KJ0zFPd9Rfp48H4Kls1:-KJ0zFPetUNXw81r2REr:1360353813) ([raw file](https://github.com/dolphin-emu/dolphin/blob/088799c0357df68dec8b797ae0dd2777265dba56/Source/Core/Core/Movie.cpp#L1399)):*
> ```cpp
> 	unsigned int temp1;
> 	unsigned int temp2;
> 	for (size_t i = 0; all_hexadecimal && i < revision_bytes_to_write; ++i)
> ```

Is there any particular reason why something like the following could not be done?

```cpp
// Determines if an arbitrary sequence range contains hex characters.
// or just make it a lambda function.
template <typename ForwardIter>
bool IsHexString(ForwardIter begin, ForwardIter end)
{
    return std::all_of(begin, end, ::isxdigit);
}

// Converts the Git has into a compact representation for DTM storage
std::array<u8, 20> ConvertGitHashToDTMRevision(const std::string& str)
{
    // Already zeroed out with braces, don't need to care about it at the end.
    std::array<u8, 20> dtm_revision{};

    size_t end_offset = /* Calculations here */

    if (IsHexString(str.begin(), str.begin() + end_offset))
    {
        // Do conversion here.
    }
    else
    {
         // Do full copy
    }

    return dtm_revision;
}
```

which can then be std::copy-ed into s_revision (or just make s_revision a std::array). It also keeps the logic separate from the global revision string itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3872)*

**Comment by JosJuice** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/Movie.cpp, line 1399 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3872#-KJ0zFPd9Rfp48H4Kls1:-KJ18AObr1I7cM11clhU:-152086988) ([raw file](https://github.com/dolphin-emu/dolphin/blob/088799c0357df68dec8b797ae0dd2777265dba56/Source/Core/Core/Movie.cpp#L1399)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> Is there any particular reason why something like the following could not be done?
> 
> ```cpp
> // Determines if an arbitrary sequence range contains hex characters.
> // or just make it a lambda function.
> template <typename ForwardIter>
> bool IsHexString(ForwardIter begin, ForwardIter end)
> {
>     return std::all_of(begin, end, ::isxdigit);
> }
> 
> // Converts the Git has into a compact representation for DTM storage
> std::array<u8, 20> ConvertGitHashToDTMRevision(const std::string& str)
> {
>     // Already zeroed out with braces, don't need to care about it at the end.
>     std::array<u8, 20> dtm_revision{};
> 
>     size_t end_offset = /* Calculations here */
> 
>     if (IsHexString(str.begin(), str.begin() + end_offset))
>     {
>         // Do conversion here.
>     }
>     else
>     {
>          // Do full copy
>     }
> 
>     return dtm_revision;
> }
> ```
> 
> which can then be std::copy-ed into s_revision (or just make s_revision a std::array). It also keeps the logic separate from the global revision string itself.
</details>
That's a better idea. I'll add it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3872)*

**Comment by JosJuice** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/Movie.cpp, line 1399 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3872#-KJ0zFPd9Rfp48H4Kls1:-KJ1MhwnhMWoudn3N3bi:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/088799c0357df68dec8b797ae0dd2777265dba56/Source/Core/Core/Movie.cpp#L1399)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary>
> That's a better idea. I'll add it.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3872)*

**Comment by delroth** [comment]
@lioncash should this be merged?

**Comment by lioncash** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/Movie.cpp, line 151 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3872#-KJGqTGfkuUCLvG4LO4g:-KJGqTGgsBnnR3ohpTHN:2057185440) ([raw file](https://github.com/dolphin-emu/dolphin/blob/0f2604020f3d45d62bb57bf72ae3e76582850a4f/Source/Core/Core/Movie.cpp#L151)):*
> ```cpp
> 		// the intended design of the DTM format, but it's the most sensible fallback.
> 		size_t bytes_to_write = std::min(revision.size(), revision_bytes.size());
> 		memcpy(revision_bytes.data(), revision.c_str(), bytes_to_write);
> ```

This can just be `std::copy_n(std::begin(revision), bytes_to_write, std::begin(revision_bytes));`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3872)*

**Comment by lioncash** [comment]
@delroth Don't see why not, since it's fairly trivial.

**Comment by lioncash** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3872)*

**Pull request merged**
