### PR TITLE
NetPlay: One click host

### PR DESCRIPTION
**Pull request by Aestek**
Add a context menu entry in main game list to host a netplay game based on saved settings. This acts as a shortcut.

This feature was in 4.0-652 but lost since then.

This also tries to put all netplay messy launch logic in the same place and centralize magic strings/numbers.

This PR is based on my other netplay PR (https://github.com/dolphin-emu/dolphin/pull/3588) because it uses some of its features, only the last commit was added. I can rebase if this is a problem.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4057)

### CODE REVIEW

**Comment by JosJuice** [comment]
Review status: 0 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/DolphinWX/ISOFile.h, line 43 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4057#-KNS4oynlM1Fww1OL7ps:-KNS4oynlM1Fww1OL7pt:1748652427) ([raw file](https://github.com/dolphin-emu/dolphin/blob/b5b1d655ee508d4287cd8b7d60f55fc5db392557/Source/Core/DolphinWX/ISOFile.h#L43)):*
> ```objc
>   std::string GetName(DiscIO::Language language) const;
>   std::string GetName() const;
>   std::string GetFullName() const;
> ```

This function name isn't great. It doesn't simply return a name, it returns a combination of the game ID, revision, name and disc number. A possible alternative could be something like `GetNetplayIdentifier`. (Or are we still capitalizing it `NetPlay`?)

---

*[Source/Core/DolphinWX/NetPlay/NetWindow.cpp, line 77 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4057#-KNS5YLZ5_mudX25Xt8g:-KNS5YL_BEQLA2dDuU6b:-523209866) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aa34e5e20e5f66cfdbace167b98c30c1fedcf522/Source/Core/DolphinWX/NetPlay/NetWindow.cpp#L77)):*
> ```cpp
> {
>   // Lang needs to be consistent
>   const DiscIO::Language lang = DiscIO::Language::LANGUAGE_ENGLISH;
> ```

You should be able to remove `#include "DiscIO/Enums.h"` now that this is gone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4057)*

**Comment by Aestek** [comment]
Review status: 0 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/DolphinWX/ISOFile.h, line 43 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4057#-KNS4oynlM1Fww1OL7ps:-KNSBzFl2qfVa39BsRtF:-1913583877) ([raw file](https://github.com/dolphin-emu/dolphin/blob/b5b1d655ee508d4287cd8b7d60f55fc5db392557/Source/Core/DolphinWX/ISOFile.h#L43)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary>
> This function name isn't great. It doesn't simply return a name, it returns a combination of the game ID, revision, name and disc number. A possible alternative could be something like `GetNetplayIdentifier`. (Or are we still capitalizing it `NetPlay`?)
</details>
While this is used by netplay it doesnt have to be netplay-specific. Thats why I tried to find a name that woulndt imply netplay but I agree it's not that great :/.

What do you think of `GetUniqueIdentifier`? Thats what netplay wants. 

---

*[Source/Core/DolphinWX/NetPlay/NetWindow.cpp, line 77 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4057#-KNS5YLZ5_mudX25Xt8g:-KNSDJSgP2_ikHbeTqcx:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aa34e5e20e5f66cfdbace167b98c30c1fedcf522/Source/Core/DolphinWX/NetPlay/NetWindow.cpp#L77)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary>
> You should be able to remove `#include "DiscIO/Enums.h"` now that this is gone.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4057)*

**Comment by E2xD** [comment]
Tested and works as intended. (HYPE AF)
(both direct connect and traversal)

**Comment by JosJuice** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/DolphinWX/ISOFile.h, line 43 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4057#-KNS4oynlM1Fww1OL7ps:-KNSTzA-HVPUW-1TqIDr:2020604659) ([raw file](https://github.com/dolphin-emu/dolphin/blob/b5b1d655ee508d4287cd8b7d60f55fc5db392557/Source/Core/DolphinWX/ISOFile.h#L43)):*
<details><summary><i>Previously, Aestek wrote…</i></summary>
> While this is used by netplay it doesnt have to be netplay-specific. Thats why I tried to find a name that woulndt imply netplay but I agree it's not that great :/.
> 
> What do you think of `GetUniqueIdentifier`? Thats what netplay wants. 
</details>
That name is okay. A problem is that it sounds similar to `IVolume::GetUniqueID()`, which returns the game ID, but I can't think of anything that's much better. I might as well rename `IVolume::GetUniqueID()` in a later PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4057)*

**Comment by Aestek** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/DolphinWX/ISOFile.h, line 43 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4057#-KNS4oynlM1Fww1OL7ps:-KNTXPT_B0AWeblSWmKz:-339371935) ([raw file](https://github.com/dolphin-emu/dolphin/blob/b5b1d655ee508d4287cd8b7d60f55fc5db392557/Source/Core/DolphinWX/ISOFile.h#L43)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary>
> That name is okay. A problem is that it sounds similar to `IVolume::GetUniqueID()`, which returns the game ID, but I can't think of anything that's much better. I might as well rename `IVolume::GetUniqueID()` in a later PR.
</details>
I renamed it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4057)*

**Comment by Helios747** [comment]
Reviewed 6 of 13 files at r1, 2 of 12 files at r3, 1 of 4 files at r5.
Review status: 9 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4057)*

**Comment by JMC47** [comment]
Does this need to be rebased or anything after hte previous merges or is it okay?

**Comment by MaJoRoesch** [comment]
I'm actually a little worried by this change, from a UX perspective... There is such a thing as making shortcuts too good, so that users don't know how to operate it with anything but the shortcut and don't know how to use necessary functionality.

I don't really use netplay, and I don't know the typical audience, but what would be the net effect of this changes on the userbase? @JMC47 I would definitely like your opinion on this, since you know the netplay userbase so well!

**Comment by E2xD** [comment]
The SmashLadder Netplay userbase as a whole want things simplified as much as possible. This has never been an issue back when DC Netplay was being developed 2.5+ years ago and it has been the most requested feature from vet users (Myself and Anther [Creator of SmashLadder] included) since it was removed/we moved ahead. It was never included as it was only a beta feature thrown in for the hell of it (as I can recall).

**Comment by Helios747** [comment]
I would normally agree with @MaJoRoesch, but in this case, with how stupid and finnicky netplay is, it's likely worth it to make it a "stupid easy shortcut". Power users (or users who can't get it working) will likely need to not use the shortcut anyways to go into the UI and configure things.

**Comment by Jofzar** [comment]
@MaJoRoesch I understand the concern, but to connect to netplay you will still have to go through

 tools > start netplay > connect,

 You will still see all of the alert/warnings on the page and other information, it just saves like 6 clicks and multiple dialogs to easily host the game. Assuming that the other side of the userbase (not counting smashladder players) is people playing with there friends, one of them will see these dialog's/warnings telling them what settings need to be set. 

Overall this just shortens the setup time for repeated actions and honestly makes the netplay feature a bit easier to find for the first time instead of being tucked away in tools.

**Comment by JMC47** [comment]
I'm one of the people who don't see the need for this, but, everyone in the smash netplay community really seems to think that this is great.  It was one of those big features in the old DC-netplay branch people loved that was totally unexpected.  I think it'll see a lot of use.

**Comment by MaJoRoesch** [comment]
Ooooh, it is in the netplay gamelist? Ok! That makes more sense than what I apparently assumed!

Anyway, you guys know how the netplay community is, so if you guys are cool with it, I'm fine with it too.

**Comment by clinchergt** [comment]
Is this ready to get merged? (rebase aside)

**Comment by shuffle2** [comment]
Moving to https://github.com/dolphin-emu/dolphin/pull/4279

**Pull request closed without merging**
