### PR TITLE
Include externals as system headers

### PR DESCRIPTION
**Pull request by Minty-Meeo**
Following a suggestion given by @iwubcode on PR #11709, let's just include all externals as system headers so the warnings from their headers can stop leaking into our warnings.

### CODE REVIEW

**Comment by Minty-Meeo** [comment]
Okay seems like not all of the buildbots are on CMake 3.25+

**Comment by iwubcode** [comment]
For VisualStudio, you can likely use:  https://learn.microsoft.com/en-us/cpp/build/reference/external-external-headers-diagnostics?view=msvc-170

**Comment by OatmealDome** [comment]
Requiring CMake 3.25+ is problematic. Android Studio only comes with CMake 3.22.1 maximum.

**Comment by Minty-Meeo** [comment]
Curse Android, always holding back my PRs.

**Pull request closed without merging**
