### PR TITLE
MMU: Get rid of type punning in FP read/write functions

### PR DESCRIPTION
**Pull request by lioncash**
The previous code is considered undefined behavior.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4262)

### CODE REVIEW

**Comment by GitToTheHub** [comment]
It does not give a better type conversion as with memcpy? seems so complicated the code :/

**Comment by degasus** [comment]
@GitToTheHub using union for convertion is undefined behavior. That's the only difference.

**Comment by GitToTheHub** [comment]
I understand that. I mean only if the conversion could be more simpler with a cast or so as this:
` double Read_F64(const u32 address)
 {
   return (double)Read_U64(address);
 }`

**Comment by degasus** [comment]
We need to binary representation, not a cast. 1.0 != 0x1

**Comment by GitToTheHub** [comment]
Ok, thank you for the explanation :) C++ seems a little bit more complexer as for example Java :)

**Pull request merged**
