### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by shuffle2**
Reword submodule statement to be more general.
Add pointer about dealing with clang-format.

### CODE REVIEW

**Comment by JosJuice** [comment]
Does the clang-format that's included with Visual Studio not work? (Different version than what's on the lint bot?)

**Comment by shuffle2** [comment]
It produces output which differs from what the bot expects. lint.sh uses 7.0 so I assume it is some behavioral change between llvm releases. (which is lol, but whatever)

**Comment by JosJuice** [comment]
These changes sound reasonable to me, then.

**Comment by shuffle2** [comment]
```
/mnt/c/Program Files (x86)/Microsoft Visual Studio/2019/Community$ ./VC/Tools/Llvm/bin/clang-format.exe --version
clang-format version 9.0.0 (tags/RELEASE_900/final)
```
```
$ clang-format --version
clang-format version 8.0.0-3 (tags/RELEASE_800/final)
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco
```

**Pull request merged**
