### PR TITLE
Update free DSP ROM and coefficients to support GBA ucode

### PR DESCRIPTION
**Pull request by ligfx**
- coef: Explicitly set 23 different values that are used by GBA UCode, and tweaked overall parameters to more closely match those values.
- irom: Moved a few functions to their proper places, updated BootUCode to configure DMA transfers using AX registers as well as IX register (the GBA UCode uses this to do two sequential transfers in one call), and added partial functions used by GBA UCode.

All functions were reverse-engineered solely based off of observed effects on the virtual machine: register states before-and-after, dmem interactions, and DMA transfers. The specific coefficients were observed being read from dmem, and must be exactly those values to function properly. I have no knowledge of how the official ROM implements these functions, or how it is implemented overall.

Tested with The Legend of Zelda: Four Swords Adventures, Final Fantasy Crystal Chronicles, and Billy Hatcher and the Giant Egg (to download ChuChu Rocket!).

### CODE REVIEW

**Comment by ligfx** [comment]
@delroth @shuffle2

**Comment by delroth** [comment]
How much do the "alien" values in the coefficient table screw up with the resampler? That's my main worry looking at this change.

**Comment by ligfx** [comment]
Ah good q, I should have written that up. The largest discrepancy from the generated values is `0x98`. Most are much smaller. The final quadrant, of course, has huge discrepancies, because it's not generated at all.

Here's the output of `generate_coefs.py`:

```
At 003b: replacing 0061 with 0065 (diff. of  0x4)
At 0043: replacing 0073 with 0076 (diff. of  0x3)
At 00ca: replacing 345a with 3461 (diff. of  0x7)
At 00e2: replacing 3768 with 376f (diff. of  0x7)
At 01b8: replacing 007c with 007f (diff. of  0x3)
At 01f8: replacing 0006 with 0009 (diff. of  0x3)
At 01fc: replacing 0000 with 0003 (diff. of  0x3)

At 0229: replacing 656a with 657c (diff. of  0x12)
At 0231: replacing 64ea with 64fc (diff. of  0x12)
At 0259: replacing 6131 with 6143 (diff. of  0x12)
At 0285: replacing 5aed with 5aff (diff. of  0x12)

At 0456: replacing 0fef with 102f (diff. of  0x40)
At 0468: replacing f802 with f808 (diff. of  0x6)
At 0491: replacing 6981 with 6a0f (diff. of  0x8e)
At 05f1: replacing 01d9 with 0200 (diff. of  0x27)
At 05f6: replacing 7ecd with 7f65 (diff. of  0x98)

At 066c: replacing 0000 with 06f2 (diff. of  0x6f2)
At 06fe: replacing 0000 with 0008 (diff. of  0x8)
At 0723: replacing 0000 with ffe0 (diff. of  0xffe0)
At 0766: replacing 0000 with 0273 (diff. of  0x273)
```

**Comment by delroth** [comment]
OK, that looks fine. No complaints about the rest of the change. LGTM.

**Comment by shuffle2** [comment]
Nice job!

**Pull request merged**
