### PR TITLE
State: Don't use memcpy and memcmp with strings

### PR DESCRIPTION
**Pull request by JosJuice**

### CODE REVIEW

**Comment by lioncash** [comment]
@dolphin-emu-bot rebuild

**Comment by phire** [comment]
LGTM

**Comment by lioncash** [comment]
Is gameID used in cases where having a type of u8 is a requirement? If not, it can just be changed to be an array of type char, eliminating the need for the casts.

**Comment by neobrain** [comment]
To be honest, there doesn't seem to be any reason to treat this as a string rather than a plain chunk of memory, and hence no reason to prefer str(n)cmp/cpy over memcmp/cpy.

**Comment by JosJuice** [comment]
Treating `gameID` as a plain chunk of memory is fine, but we shouldn't read what's after the null byte in `GetUniqueID().c_str()`.

**Comment by mimimi085181** [comment]
Isn't it more important how the Wii would handle a game id with null terminator? It doesn't matter if there is a title that has one or not.

**Comment by phire** [comment]
Especially when also doing a memcmp

**Comment by phire** [comment]
This changes the behavior for a gameID less than 6 chars from undefined to null padded.

**Pull request merged**
