### PR TITLE
JIT x64: Recalculate flags after add/sub

### PR DESCRIPTION
**Pull request by mickdermack**
The x86/x64 add and sub instructions (and a few more) can set OF, which causes merged branches to take wrong jumps. The easiest way to fix this seems to be to recalculate the flags with test afterwards.
This fixes [Issue 8787](https://bugs.dolphin-emu.org/issues/8787).

I wrote some test cases for some instructions; if someone is interested, I can submit a PR at hwtests.

Proper emulation of PPC SO flag remains to be done, though I don't know if there is a game using it.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3212)

### CODE REVIEW

**Comment by phire** [comment]
Ignore the ogl-lin-intel FifoCi, a driver issue is causing it to randomly get different results every time.

**Comment by JMC47** [comment]
Can confirm this fixes Lilt Line Wiiware.

**Comment by FioraAeterna** [comment]
I don't quite understand what case this covers; isn't setting OF a correct part of branch merging? x86 jump conditions require correct OF values.

Which particular case does this fail in?

**Comment by mickdermack** [comment]
@FioraAeterna PowerPC does not use overflow when determining LT and GT flags, but it uses the most significant bit of the output, which is represented by the sign flag SF on x86.

x86 `jg` uses `OF==SF && !ZF`, while PPC `bgt` uses GT, which is `!SF && !ZF` on x86.
These conditions are equal if and only if `OF==0`.

An x86 `test` on the result sets SF and ZF according to the result and clears OF.

Although PPC LT/GT(/EQ) are correctly represented by x86 SF and ZF, there is no single x86 instruction with a condition of `!SF && !ZF` which means we either have to clear OF and use `jg`, or emit two jump instructions for a single branch. Similar goes for `bge` vs `jge`, `blt` vs. `jl` and `ble` vs `jle`.

x86 OF corresponds to the PPC SO and OV flags, which are currently not, or only partially emulated by Jit64.

The current implementation fails in cases where a signed overflow occurs.
0x70000000 + 0x10000000 sets OF on x86 and SO+OV on PPC, but a subsequent `jg` on x86 would jump, while a `bgt` on PPC would *not* jump, because the signed result is not greater (in fact, less) than zero.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JMC47** [comment]
@degasus there's a hardware test and everything setup?  Can we merge this before the feature freeze to get compatibility back on this title?

**Comment by degasus** [comment]
By the way, is the interpreter already fine or does it need the same fix? Our JIT backends should have the same behavior as the interpreter, but faster. So also updating the interpreter is required :/

**Comment by JMC47** [comment]
Interpreter does not have this bug it seems.  I wasn't able to get any popups, at least.

**Comment by delroth** [comment]
Given the lack of activity on that PR I'm tempted to merge it as is. AIUI, it only disables an optimization. It is proven to fix at least one bug, and the reasoning and the implementation make sense to me.

If anyone is opposed to that, speak now or forever hold your peave. I'll merge next time I have a look through the queue.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3212#-:-K8ayNgrh3iLZzhuxw8j:1033338502)*

**Pull request merged**
