### PR TITLE
Don't have as many framelimit options

### PR DESCRIPTION
**Pull request by Buddybenj**
Makes the selection list shorter by six options. I don't know if I'm the only one that finds it ugly that there are so many options.

### CODE REVIEW

**Comment by JMC47** [comment]
Make it so users can enter their own number for framelimit if you're going to change the options.  Not exactly thrilled about taking away some when I tend to use weird framerates when testing.

**Comment by cammelspit** [comment]
Not sure what options you culled but as a cleaner and more usable solution could be a typable field with a couple arrows, could be a good idea...

**Comment by Buddybenj** [comment]
OK. I think after "Auto" should be "Custom", and a text box will appear where users can type in any value. I don't know enough about wxWidgets to do that though... Also, if there was going to be a way to easily enter a custom framelimit, I think even more options could be removed. Something like this:
Off
Auto
5
10
20
30
45
50
60
90
100
120

If someone could give me a patch for a custom framelimit option I'll add it in, because I agree, the framelimit shouldn't be artificially limited to certain values.

**Comment by mimimi085181** [comment]
This needs to be changed anyways. It doesn't work properly for games that run with 2 different frame rates. Wind Waker PAL for example runs at 50 and 30 fps.

**Comment by magumagu** [comment]
Yes, we should probably just make it a percentage.

**Comment by degasus** [comment]
+1 for percentage

**Comment by mimimi085181** [comment]
Percentage slider does sound nice. Maybe with a checkbox, like the cpu overclocking? So the default 100% is more clear than it already is.

**Comment by Buddybenj** [comment]
I'm going to close this since I don't know enough about wxWidgets to do that. However, I hope someone else can implement it soon.

**Pull request closed without merging**
