### PR TITLE
PowerPC: HostR/W float/double added

### PR DESCRIPTION
**Pull request by sepalani**
This PR added HostRead/Write functions for floating points.

Ready to be review & merged.

### CODE REVIEW

**Comment by JMC47** [comment]
@dolphin-emu-bot rebuild

**Comment by JMC47** [comment]
Do you have any test cases and or any way I can test this?

**Comment by sepalani** [comment]
Unfortunately not so much.

The function "HostRead_F64" was kind of missing when I was implementing https://github.com/dolphin-emu/dolphin/pull/4481.
```C++
template <typename T, typename std::enable_if_t<IsArgReal<T>::value>* = nullptr>
T GetArg()
{
    double value;
   // (...)
   // This part can be replaced with: value =  PowerPC::HostRead_F64(m_stack);
   const u64 integral = PowerPC::HostRead_U64(m_stack);
   std::memcpy(&value, &integral, sizeof(double));
   m_stack += 8;
  // (...)
}
```
That part deals with double passed as parameter and are read normally. So I can suppose that reading F64 is working and writing back shouldn't be too different. I'm not sure for F32, though.

**Comment by riking** [comment]
I feel like these could use some `static_assert(sizeof(double) == sizeof(u64))` seeing as there is no float32_t or float64_t.

**Comment by lioncash** [comment]
If we're to include a check like that, it's likely best suited for being placed within `CommonTypes.h` with all the custom type definitions/aliases along with:

```cpp
static_assert(std::numeric_limits<float>::is_iec559(), "Your system's floating point types are straight-up bonkers.");
static_assert(std::numeric_limits<double>::is_iec559(), "Your system's floating point types are straight-up bonkers.");
```

**Comment by sepalani** [comment]
Just rebased. I really think there should be helper functions like these to prevent the use of the `PowerPC::Read_F*` alternatives which might generate DSI exceptions and might not be what people using it want.

**Comment by shuffle2** [comment]
the names integral and real dont really make sense right? after the memcpy the value will have purposefully not been converted.

**Comment by sepalani** [comment]
The names are based on the `PowerPC::Read_F32` implementation. `bytes` or `raw` instead of `integral` would have made more sense, IMO, since we only used it to read/write the `real`'s bytes. But I also think that name bikeshedding deserves its own PR which also addresses the other naming/coding issues in the MMU file.

**Pull request merged**
