### PR TITLE
make libusb vcxproj use standard dolphin template and don't compile strerror.c.

### PR DESCRIPTION
**Pull request by shuffle2**

### CODE REVIEW

**Comment by Tilka** [comment]
(Sorry, I fell asleep before I could submit a PR.) Can you please move this file up one directory and revert 7a305bef86e6e63eea2bee4024c5053a54d4e901? Makes updates easier.

**Comment by delroth** [comment]
Ping?

**Comment by shuffle2** [comment]
Will reverting that commit actually help git somehow?  
Also, why would I move the file up a directory, since it seems like it is with many other msvc files, in the msvc directory...?

**Comment by shuffle2** [comment]
Oh, nevermind...

**Comment by shuffle2** [comment]
Should be good now.

**Pull request merged**
