### PR TITLE
Remove Hybrid Wii Remote

### PR DESCRIPTION
**Pull request by JosJuice**
It simply doesn't seem to work for anything useful, and nobody seems to care about maintaining it.

### CODE REVIEW

**Comment by Helios747** [comment]
Yes pls

**Comment by autofire372** [comment]
I don't even know what it was _supposed_ to do...

**Comment by MayImilae** [comment]
On the forum we haven't even been giving support for it for years. No one uses it, so no one knows how to help anyone who has problems with it!

**Comment by steampunko** [comment]
I was using this to get my wiimote working .-.

**Comment by legoboy0109** [comment]
I feel like there are a few instances where a hybrid wiimote could be useful, such as using a mouse or other external device to control IR while using the real wiimote for game controls. Would it be possible to rework it?

**Comment by Helios747** [comment]
If the emulated Wiimote system in general is rewritten to not be an incomprehensible pile of "Oh god it works but please don't touch a single line" it probably wouldn't be a problem to reintroduce the feature.

Right now it just straight up didn't work, and we were getting too many support requests from users trying to get it working when nobody wanted to touch it, risking making everything worse.

**Comment by VineST** [comment]
Is this seriously gone for good? Using the mouse for IR and having the real wiimote for everything else was a godsend. Guess I'll stick to release 5.0.

**Pull request merged**
