### PR TITLE
[WIP] Fix efb2tex for Sonic Riders: Zero Gravity

### PR DESCRIPTION
**Pull request by phire**
Was broken by #2960. Compared to the original code, this probably improves efb2ram quality at higher IRs.

The game was padding the size of the efb2ram copy from 640x480 to 1024x512 (power of 2), It didn't actually use the rest of the texture, just leaving it a solid pink color, so our current method of "just give it the efb copy anyway no matter what dimensions, as long as the starting address and hash match" works just fine. 

But our efb copy code hashes a 1024x480 texture, while the texture loading code hashes a 1024x512 texture, so they get different results.

The new texture loading code checks the size of the efb copy hash and re-does it's hash to match,

### CODE REVIEW

**Comment by mimimi085181** [comment]
In my opinion, this would be fine with texture_size < entry->size_in_bytes. But texture_size != entry->size_in_bytes includes texture_size > entry->size_in_bytes as well. And this would mean that Dolphin ends up using a small efb copy when trying to use a big texture.

**Comment by phire** [comment]
Which is exactly the case this is trying to copy with,

**Comment by mimimi085181** [comment]
But we only know this for this game. In other games, this would be just guessing. If it would only affect efb2tex, it might be fine, as efb2tex is a hack anyways. But this affects efb2ram as well, where efb2ram is working fine for this game already, and now it could be broken for something else.

**Comment by phire** [comment]
Hmm, I guess you are right. This will potentially change the behaviour of things that a currently working in only efb2ram.

**Comment by degasus** [comment]
Why is the NSMBW hack not working here?

**Comment by mimimi085181** [comment]
I think both, the efb copy and the texture that Dolphin ends up creating, start at the same offset. So the partial texture updates code needs to be updated to support this. Also, Dolphin must not delete the efb copy, in order to be able to use it.

Apparently phire is working on a bigger change that makes the partial texture updates code way more general.

**Comment by JMC47** [comment]
This is kind of wanted before the progress report.  I don' tlike having huge regressions around a featured change.

**Comment by JMC47** [comment]
As far as I can tell, NSMBWii's coins work in this, too.

**Comment by phire** [comment]
I think I'll make this fix apply to efb2tex only, which fixes the regression without causing any new ones.

It can be replaced by the new feature when I get around to writing it.

**Comment by JMC47** [comment]
Tick tock, the progress report is coming.  Makes it easier for me to write if there aren't regressions to mention!

**Comment by baptiste0602** [comment]
It also fix the left corner of Sin and Punishment 2.
Since #2960, it's black...

**Comment by bb010g** [comment]
Is this waiting on anything?

**Comment by phire** [comment]
This has been fixed by mimimi's PR

**Pull request closed without merging**
