### PR TITLE
DriverDetails: Disable OGL shadercache on intel/windows

### PR DESCRIPTION
**Pull request by degasus**
We have lots of crash reports, so just disable this feature completely
for the next stable release.

### CODE REVIEW

**Comment by Tilka** [comment]
lgtm

**Comment by Armada651** [comment]
@degasus Please re-submit this as a PR against the stable branch so we can merge this branch without cherry-picking.

**Comment by degasus** [comment]
Oh, I thought we want to merge everything in master and to only pick it in stable? IMO this here should be in both.

**Comment by TurboK234** [comment]
What kind of performance hit should be expected? I haven't tested this myself, yet, but do you have any figures / educated guesses?

**Comment by Tilka** [comment]
It has an infinite performance gain from "crash" to "runs at all."

**Comment by Armada651** [comment]
@degasus Also, can you refer to some specific issue reports in the PR description?

**Comment by TurboK234** [comment]
@Tilka :) good point. I did a quick test, see https://code.google.com/p/dolphin-emu/issues/detail?id=8658 , OGL does not crash (at least immediately) on my IntelHD 4600 with latest drivers on Win 8.1 when running a game twice. So maybe it's not THAT black and white.
Will do some performance testing with this PR later.

**Comment by degasus** [comment]
It seems like not all driver/gpus are affected, so we should first check exactly which one are.

**Comment by degasus** [comment]
looks like this was only on out-dated driver versions...

**Pull request closed without merging**
