### PR TITLE
Port memory card size override setting to new config system.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
Found this straggler that was in neither config system!

### CODE REVIEW

**Comment by Techjar** [comment]
This setting should go in SessionSettings rather than MainSettings, as we don't ever under any circumstances want this handled globally.

**Comment by chrisleigh-stack** [comment]
It's there any possibility to add gyroscope on the settings. To use PS4 gamepad with gyro sensor

**Comment by JosJuice** [comment]
This setting is used in game INIs that we ship. Does the Session layer actually allow loading from game INIs?

**Comment by AdmiralCurtiss** [comment]
You seem to be correct. Reverting to Main then...

**Review by JosJuice — APPROVED** [review]

**Comment by AdmiralCurtiss** [comment]
I think in the future we probably want a way to designate a setting as 'use when loaded from GameINI but ignore when in global config', but I think this setting is fairly harmless to potentially load globally in the meantime -- there isn't a GUI setting for it so you'd have to manually write it into your global settings INI and then be surprised about it.

**Pull request merged**
