### PR TITLE
[ GMS.ini ] Missing Override

### PR DESCRIPTION
**Pull request by McAchi**
_[Video_Settings]_
_EnableGPUTextureDecoding = False_

**Missing override that prevents the already present Arbitrary Mipmap Detection override from taking effect if the user's settings enables GPU Texture Decoding.**
~Rebuilding Dolphin to keep it up to date keeps overwriting my personal changes to the .ini file, therefore I propose fixing the issue from the source.~

~(While I'm at it, - _this is only a suggestion/idea_ - but an override override could be useful to keep the base overrides up to date without compromising personal overrides. No obligation to implement that, of course.)~

Thank you.

### CODE REVIEW

**Comment by JosJuice** [comment]
> (While I'm at it, - *this is only a suggestion/idea* - but an override override could be useful to keep the base overrides up to date without compromising personal overrides. No obligation to implement that, of course.)

This exists. Put the game INI file in the user folder (can be opened by pressing Config > Open User Folder) instead of the Sys folder.

**Comment by McAchi** [comment]
> This exists. Put the game INI file in the user folder (can be opened by pressing Config > Open User Folder) instead of the Sys folder.

Oh my god, I completely missed it, I'm so sorry.
The change I proposed still stands though, so I guess being foolish isn't the worst sometimes.

Thank you!

**Comment by Dentomologist** [comment]
I've created [a PR](https://github.com/dolphin-emu/dolphin/pull/13058) to handle the other games where this happens. 

I'd suggest adding a comment in the .ini to explain why it's being disabled.

**Comment by McAchi** [comment]
> I'd suggest adding a comment in the .ini to explain why it's being disabled.

I added a comment.
IDK if I should have done the commit merge to my fork; I just wanted to sync my repo, but it counted as a commit.

I'm a Git and GitHub newbie, so I'm not so sure how all of this works.

**Comment by JosJuice** [comment]
Please squash your commits into one. We don't merge PRs that contain merge commits (at least not under normal circumstances).

**Pull request closed without merging**
