### PR TITLE
Properties/GameConfig: Remove "Skip DCBZ"

### PR DESCRIPTION
**Pull request by spycrab**

### CODE REVIEW

**Comment by skidau** [comment]
Wasn't this needed for Rubik's Puzzle Galaxy: RUSH?

**Comment by MayImilae** [comment]
It's just removing the UI option. If Rubik's Puzzle Galaxy has a GameINI setting for this already set up, it will still work fine!

**Comment by MayImilae** [comment]
For future reference, this came about because a user had a weird hard to diagnose problem and it was because they had Skip DCBZ enabled - https://forums.dolphin-emu.org/Thread-metroid-prime-1-corruption-resolved

**Comment by Helios747** [comment]
And only in Qt, at that. Which is why I yolo merged it.

**Pull request merged**
