### PR TITLE
Win32/FileUtil: Fix IsDirectory() not working for certain directories

### PR DESCRIPTION
**Pull request by spycrab**
Fixes e.g. ``C:\`` not being recognized as a valid directory.

### CODE REVIEW

**Comment by JMC47** [comment]
Fixes using my network drive with the installer.

Some file utilities like installing Wiiware games doesn't work though, so, there's still some issues somewhere.

**Comment by delroth** [comment]
Do you mean they don't work anymore, or they never worked?

**Comment by JosJuice** [comment]
Shouldn't something be done to `FileInfo::IsDirectory()` as well? Even if it's just to remove it (either on Windows only or on all OSes)...

**Comment by JosJuice** [comment]
Or hm, I guess `FileInfo::IsDirectory()` is acceptable to use in some contexts where we don't care about the roots of drives (like the handling of the emulated NAND), but it would still be good to have a comment that it has limitations compared to `File::IsDirectory(const std::string&)`.

**Pull request merged**
