### PR TITLE
Game INI updates

### PR DESCRIPTION
**Pull request by JosJuice**
A continuation of #3735, with additions based on the following reports:

https://bugs.dolphin-emu.org/issues/9465
https://forums.dolphin-emu.org/Thread-unreadable-characters-on-get-fith-with-mel-b
https://forums.dolphin-emu.org/Thread-gc-mortal-kombat-deadly-alliance--26173?pid=397717#pid397717

If there's anything that needs to be removed or changed (RMC.ini MSAA?), please tell me.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3768)

### CODE REVIEW

**Comment by Linktothepast** [comment]
Why not enforce real xfb in Mortal Kombat? It can be easily changed afterwards when Hybrid Xfb is done although i admit i don't have a clue when that may be.

**Comment by JosJuice** [comment]
It seems like the main part of the game doesn't require real XFB, and I thought it would be better to not force 1x resolution for something optional. That we can batch edit this when hybrid XFB becomes available is a good point, but 5.0 will not have hybrid XFB, so I prefer this for now.

**Comment by MarioManTAW** [comment]
So, when will this be looked over?

**Comment by JosJuice** [comment]
Now also fixes https://bugs.dolphin-emu.org/issues/9490

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JMC47** [comment]
Reviewed 7 of 8 files at r1, 3 of 4 files at r2, 3 of 3 files at r3.
Review status: 13 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[Data/Sys/GameSettings/RUU.ini, line 25 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3768#-KGUArc7ZnLAub-lGvKm:-KGUArc8pdwAimb-YUQq:432232502) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3f6db818fcfe9dbfeb6988aa2123d241010f5a72/Data/Sys/GameSettings/RUU.ini#L25)):*
I don't like setting safe texture cache for non essential things.  It's very demanding and causes slowdowns fairly commonly.

---

*[Data/Sys/GameSettings/SNG.ini, line 21 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3768#-KGUBAOaI4V16viMhRSg:-KGUBAOb5EmOGoSI1eAB:1433440218) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3f6db818fcfe9dbfeb6988aa2123d241010f5a72/Data/Sys/GameSettings/SNG.ini#L21)):*
What is safe texture cache doing for this?  Can you add that in emulation notes if it's neccessary?

---

*[Data/Sys/GameSettings/WPA.ini, line 21 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3768#-KGUBFkkivji89N491UY:-KGUBFkkivji89N491UZ:1184244932) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3f6db818fcfe9dbfeb6988aa2123d241010f5a72/Data/Sys/GameSettings/WPA.ini#L21)):*
I already know it's necessary in this game, but please note in the INI why it's set.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3768)*

**Comment by aserna3** [comment]
I agree with both comments about safe texture settings. Unless it's necessary, I don't think it should be in a gameini.

**Comment by JosJuice** [comment]
Review status: 13 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[Data/Sys/GameSettings/RUU.ini, line 25 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3768#-KGUArc7ZnLAub-lGvKm:-KGVrgBTED2rX0xdjKHC:-645922503) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3f6db818fcfe9dbfeb6988aa2123d241010f5a72/Data/Sys/GameSettings/RUU.ini#L25)):*
Good point. The pattern editor is a very tiny part of the game, so I will remove this along with `ForceFiltering = False` and make an emulation note instead.

---

*[Data/Sys/GameSettings/SNG.ini, line 21 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3768#-KGUBAOaI4V16viMhRSg:-KGVwrKlQDzFet_pJ5iE:512879570) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3f6db818fcfe9dbfeb6988aa2123d241010f5a72/Data/Sys/GameSettings/SNG.ini#L21)):*
The text gets messed up with fast texture cache. I'll add it to the emulation notes.

---

*[Data/Sys/GameSettings/WPA.ini, line 21 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3768#-KGUBFkkivji89N491UY:-KGVwx8ln-M9MJxPWbIv:-833172714) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3f6db818fcfe9dbfeb6988aa2123d241010f5a72/Data/Sys/GameSettings/WPA.ini#L21)):*
In the emulation notes, in a comment or both?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3768)*

**Comment by JMC47** [comment]
Review status: 13 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[Data/Sys/GameSettings/WPA.ini, line 21 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3768#-KGUBFkkivji89N491UY:-KGabcYmXKsbzl1hMij9:-1340152779) ([raw file](https://github.com/dolphin-emu/dolphin/blob/3f6db818fcfe9dbfeb6988aa2123d241010f5a72/Data/Sys/GameSettings/WPA.ini#L21)):*
I think emulation notes would be fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3768)*

**Comment by aserna3** [comment]
Is this good to merge? Closes a blocker~

**Pull request merged**
