### PR TITLE
Use Common::Flag and Common::Event when possible

### PR DESCRIPTION
**Pull request by leoetlino**
Replaces old and simple usages of std::atomic<bool> with Common::Flag
(which was introduced after the initial usage), so it's clear that
the variable is a flag and because Common::Flag is well tested.

This also replaces the ready logic in WiimoteReal with Common::Event
since it was basically just unnecessarily reimplementing Common::Event.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4093)

### CODE REVIEW

**Comment by lioncash** [comment]
You might want to explain in the commit message *why* the change was necessary or preferable, as opposed to just stating *what* was changed.

**Comment by degasus** [comment]
:lgtm: - and sorry for the merge conflict ;)

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp, line 537 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4093#-KOoRI7_B-saEuimUMo0:-KOoRI7_B-saEuimUMo1:b-i8b8om) ([raw file](https://github.com/dolphin-emu/dolphin/blob/8e995c996adc36ae497d52d5f28fa21c708a1dc3/Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp#L537)):*
> ```cpp
> {
>   m_run_thread.Set();
>   m_wiimote_thread = std::thread(&Wiimote::ThreadFunc, this);
> ```

Do you think this order is a race condition?
eg if StartThread() and StopThread() are called at once, IOWakeup may be called while the thread isn't started.
I think m_run_thread.Set() needs to be moved after m_thread_ready_event.Wait(), but no idea if this will break other stuff...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4093#-:-KOoRcf9Az0uMDf9pRiP:b-9d831c)*

**Comment by leoetlino** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp, line 537 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4093#-KOoRI7_B-saEuimUMo0:-KOoYSVkxkLrIbuFknHO:baarh56) ([raw file](https://github.com/dolphin-emu/dolphin/blob/8e995c996adc36ae497d52d5f28fa21c708a1dc3/Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp#L537)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> Do you think this order is a race condition?
> eg if StartThread() and StopThread() are called at once, IOWakeup may be called while the thread isn't started.
> I think m_run_thread.Set() needs to be moved after m_thread_ready_event.Wait(), but no idea if this will break other stuff...
</details>
Yes, I think there is indeed a race condition.
But if we set m_run_thread after m_thread_ready_event.Wait(), then this becomes a race condition with Wiimote::ThreadFunc().

What do you think of moving it to after setting m_thread_ready_event?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4093)*

**Comment by degasus** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp, line 537 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4093#-KOoRI7_B-saEuimUMo0:-KOofM_fgW1LSO9iv1o0:b-fumryq) ([raw file](https://github.com/dolphin-emu/dolphin/blob/8e995c996adc36ae497d52d5f28fa21c708a1dc3/Source/Core/Core/HW/WiimoteReal/WiimoteReal.cpp#L537)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> Yes, I think there is indeed a race condition.
> But if we set m_run_thread after m_thread_ready_event.Wait(), then this becomes a race condition with Wiimote::ThreadFunc().
> 
> What do you think of moving it to after setting m_thread_ready_event?
</details>
Also fine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4093)*

**Comment by degasus** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4093)*

**Pull request merged**
