### PR TITLE
Fifo: get rid of global variables

### PR DESCRIPTION
**Pull request by lioncash**
[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3560)

### CODE REVIEW

**Comment by degasus** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/VideoCommon/Fifo.h, line 48 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3560#-K8n7LI2yL7pSgNiK060:-K8n7LI2yL7pSgNiK061:1110835616) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f3da9997297f0b9f5a02da36ae2a4fce10458169/Source/Core/VideoCommon/Fifo.h#L48)):*
It's not if we're able to skip this frame, it's more about if the current frame *will* be skipped. So just drop the "Can"?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3560)*

**Comment by degasus** [comment]
Small nitpick, else LGTM

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3560#-:-K8n86I2FBzZ0Gh_gEMF:-1675237205)*

**Comment by BhaaLseN** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/VideoCommon/Fifo.h, line 48 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3560#-K8n7LI2yL7pSgNiK060:-K8nSSYoeDNy_bW6hTkl:1964169214) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f3da9997297f0b9f5a02da36ae2a4fce10458169/Source/Core/VideoCommon/Fifo.h#L48)):*
Was about to ask the same, is it really _Can_ Skip?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3560)*

**Comment by lioncash** [comment]
@degasus I changed the "Can" to "Will" mainly because "bool SkipCurrentFrame" looks like it attempts to skip the frame and returns whether or not it succeeded.

**Comment by degasus** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3560)*

**Pull request merged**
