### PR TITLE
Fix Gecko codehandler lag

### PR DESCRIPTION
**Pull request by TryTwo**
Mostly removes lag caused by the last major codehandler update. Makes gecko check if data to be written already exists at the write location, so that it can skip writing and icbi invalidations when they are redundant. Side effect: reduces max number of cheats by 3 lines.

### CODE REVIEW

**Comment by delroth** [comment]
@dolphin-emu-bot rebuild

I think the workaround makes sense, definitely easier than implementing an extra layer of caching in our JIT to reuse unmodified blocks. Assuming someone can verify that codes still work after this, LGTM.

**Comment by TryTwo** [comment]
I followed the affected codetypes instruction-by-instruction and they looked good. Someone with experience using button activators should definitely double-check they still work though.

**Comment by TryTwo** [comment]
Thanks, forced push seems to have restored it. I'm guessing I need to make a new branch for my other pull request.

**Comment by Helios747** [comment]
Yes. PRs track branches. If you want two PRs open at once, you need two branches. (And it's recommended to not make branches depend on each other, but just make a note in the PR if you do)

**Comment by JMC47** [comment]
I tested this with some widescreen codes that were lagging and sent it to another person who used it to unlock hidden content.  Will have their results soon as well.

**Comment by nbohr1more** [comment]
I'll try testing this tonight.

As I recall, Spiderman 2's 60FPS hack has a hard lockup roughly half a minute after starting the game, then it performs anywhere from 25FPS to 60FPS depending on scene.

**Pull request merged**
