### PR TITLE
Update mgba to 59ebf1c12dcbbe0141000cddccf667cd42e386a1

### PR DESCRIPTION
**Pull request by CasualPokePlayer**
A prerequisite for https://github.com/dolphin-emu/dolphin/pull/11611

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
You sure you don't want to update to current master? Or at the very least to https://github.com/mgba-emu/mgba/commit/5f3ee83bcc23e7ca7f3e1ce85cbdc4cf6f027f69?

**Comment by CasualPokePlayer** [comment]
I can go update it to the latest master (this was the latest master at the time I originally did this update in the other PR, a look at later commits shows no changes to cmake scripts mGBA side so the project files shouldn't need another update)

**Comment by AdmiralCurtiss** [comment]
Uh, maybe because it's checked out shallow by default? Maybe try something like

```
git submodule deinit Externals/mGBA/mgba
git submodule update --init --recursive --no-recommend-shallow Externals/mGBA/mgba
cd Externals/mGBA/mgba
git pull
```

**Comment by CasualPokePlayer** [comment]
Still seems screwy, I think it's something fubared locally on my side, it seems fine if I do it from a fresh clone.

**Pull request merged**
