### PR TITLE
Capitalize Dolphin in Game INI Files

### PR DESCRIPTION
**Pull request by Buddybenj**
Thanks to FAR - Find And Replace

### CODE REVIEW

**Comment by Linktothepast** [comment]
Can't see all the diff's but if there are no merge conflicts now, it looks good to me.

**Comment by phire** [comment]
@dolphin-emu-bot rebuild

**Comment by phire** [comment]
@dolphin-emu-bot rebuild

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by magumagu** [comment]
What happened to GCCE01.ini?

**Comment by Buddybenj** [comment]
@magumagu I have no idea how that happened, fixed.

**Pull request merged**
