### PR TITLE
VideoCommon: Add imgui-based graphics settings window

### PR DESCRIPTION
**Pull request by stenzek**
This PR adds a graphics configuration window which can be used in-game. The main motivation is so that graphics options can be changed while the game is running on android, but more relevant to myself, nogui builds.

Note that the options won't be tweakable on android yet, as we haven't hooked up imgui input to touch events. This will come later.

imgui

Options overriden by gameini/netplay/etc will be shown in red (we can't do bold in imgui, since it's a bitmap font).
image

### CODE REVIEW

**Comment by JosJuice** [comment]
As mentioned in PR #7959, please don't use GetStringT with imgui before we have a font with better language support.

**Comment by stenzek** [comment]
@JosJuice I was hoping to address the font issue as well as the input issue prior to merging. If that doesn't happen, I'll replace it with a placeholder in the interim.

**Comment by 8times9** [comment]
Is there any reason the option descriptions aren’t visible?

**Comment by iwubcode** [comment]
First of all - that looks really good @stenzek !  I ran into this with the #7930 where I was concerned about the overhead to change options / add new options if you have to now do it in two places.  That's why for that, I opted to only pick up a handful of the settings (IR and Ansio atm) which gives it a more PC style experience, leaving the full system still tweakable in Qt.  Are you worried about the duplication at all?

Since I was aiming for a more couch-style solution so I didn't want comboboxes (even if they were interact-able with a controller) but they look nice here.

Nice work!

**Comment by stenzek** [comment]
@8times9 It would be trivial to implement the descriptions by tooltip, but given this is targeted more towards Android, the mouse-over technique doesn't really map over. I'm open to other suggestions.

@iwubcode I don't see why the two can't complement each other. As I said above, the settings window itself is more targeted towards platforms which don't have the Qt Frontend.

**Comment by JMC47** [comment]
Is there anything (aside from merge conflicts?) preventing this from being merged?

**Comment by Meowlithius** [comment]
Stylistically, looks really off-putting to the current Android interface, and not following material design like the rest of the app currently is. I would say that imgui needs either a desaturated material look (my personal design judgement), or needs to be replaced by another library. (But that's probably going to be a fork for another time.)

**Pull request closed without merging**
