### PR TITLE
Replace gamecube fonts with free alternatives

### PR DESCRIPTION
**Pull request by jcowgill**
As part of me trying to get official Debian/Ubuntu packages for dolphin, I have replaced the previous gamecube font files with ones generated from free fonts to avoid any copyright issues.

I've also written a program `gc-font-tool` (which turned out to be quite fun) from info found on the internet which can create font files from truetype fonts if that ever needs to happen again.

Previously the fonts were based off Arial and Lucida which are clearly non-free (+ you have to pay a licence to redistribute them). These new fonts are based on Droid Sans and WenQuanYi Micro Hei and are licensed under the Apache 2. This should be fine as long as dolphin never integrates the fonts into any binaries, and the `font-licenses.txt` (or equivalent) file is distributed with all (including binary) versions of dolphin.

##### ANSI Before (Arial)
ansi_old

##### ANSI After (Droid Sans)
The ANSI font has been dithered.
ansi

##### SJIS Before (Lucida Sans Unicode)
This is only the second page of the font for comparison purposes (the actual font is much bigger).
sjis_old

##### SJIS After (WenQuanYi Micro Hei)
The SJIS font has not been dithered (it seems to look better that way). As you can see, both SJIS fonts have a few missing characters. This is a PITA. Hopefully these aren't used much - all the main Japanese glyphs seem to be ok.
sjis

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
Are we allowed to distribute apache 2 licensed files with our GPLv2 source/binary?

**Comment by jcowgill** [comment]
I think it would fall under the "aggregate work" clause of the GPLv2. As long as the files stay separate and are never incorporated into any GPLed binaries then it should be OK.

**Comment by Sonicadvance1** [comment]
Alright. We'll need to setup our buildbots to pull in that license file.

**Comment by Sonicadvance1** [comment]
@dolphin-emu-bot rebuild

**Comment by Sonicadvance1** [comment]
< XgF> You might want to consider the Noto fonts for JP glyphs; they should be pretty complete (also theres a Noto Latin, if you want consistency between both sets)
< XgF> (Noto is a family of Apache 2 licensed fonts Google has been releasing which should be complete for each supported language)

Maybe this should be taken in to consideration due to the missing characters?

**Comment by jcowgill** [comment]
I didn't know about them, but yes they look like they might be better (and they're derived from droid sans anyway).

**Comment by tueidj** [comment]
Got any in game before and after screenshots? Metal Gear Solid or Starfox Assault would probably be likely to show them off.

**Comment by MaJoRoesch** [comment]
Could this enhancement be turned on and off?

**Comment by Parlane** [comment]
@MaJoRoesch this is not an enhancement, this is a bug fix. It's not really clear if we can legally have gamecube font files for redistribution...

**Comment by delroth** [comment]
"Not clear"? I think the situation is pretty clear here — if these are actually extracted from the IPL and not just some reproductions that someone else did in the past, this is illegal and the only reason it's still here is because I didn't know about it.

The interop argument has nothing to do with that, copyright laws don't allow you to reproduce copyrighted files without a license to do, even for interop purpose.

**Comment by leftmostcat** [comment]
For what it's worth, there's a Droid Sans Japanese font and, at the very least, Droid Sans should have support for the Cyrillic characters as well. This could be nice for consistency.

**Comment by jcowgill** [comment]
I replaced the Japanese font with one generated from Droid Sans Japanese (which seemed the easiest). Here's the preview:
out

I don't have those games to test them with, but anyone should be able to test the fonts by simply replacing their font files with these ones. The only think which might be an issue is that the font metrics (widths of each glyph) are different for these fonts.

**Comment by shuffle2** [comment]
@delroth it was said on irc, but just so it's clear on the issue: the current font files are not copied from the IPL and are therefor not violating any Nintendo copyright.

**Comment by xerxespersrex** [comment]
Tried out these new fonts with GiFTPiA. With the kanji when the characters work they look much better and much closer to hardware but often they'll just not render at all or show a garbled square mess of pixels. 

(first two pictures from http://wikiwiki.jp/gcwiiemu/?Tips_Font_Improvement)

Fonts dumped from console:
systemfont_after

Old included fonts:
systemfont_before

New fonts:
0db7a3d9a4259e3e3c1df2373e1ff73f

**Comment by jcowgill** [comment]
I'll have a look at it tonight. I'm really puzzled how some characters work and some don't though??

**Comment by jcowgill** [comment]
@xerxespersrex Thanks for your test! On closer inspection, it looks like the font data had to be aligned on a 4-byte boundary which wasn't being done in the SJIS font. Can you test the new fonts I've pushed?

**Comment by waddlesplash** [comment]
@dolphin-emu-bot rebuild

**Comment by xerxespersrex** [comment]
Did a shot-for-shot comparison of about half of GiFTPiA's intro with a longplay on youtube. Didn't notice any missing/garbled characters at all. Only thing I'd say is the font for kanji is still a little bit too thin, but compared to how bad it used to be this is a major improvement. Looking forward to this getting merged.

Same part of the intro with the new fonts for reference:
e92c2d3f45ac11734b1bbe0ae5c9f188

**Comment by Parlane** [comment]
Looks good to me! :)

**Comment by Sonicadvance1** [comment]
Sounds good to me.

**Pull request merged**
