### PR TITLE
Small changes to description to "Store EFB Copies to Texture Only"

### PR DESCRIPTION
**Pull request by aserna3**
MaJoR pointed out that the wording for this is a bit poor and could be improved.

### CODE REVIEW

**Comment by degasus** [comment]
@Armada651 Do you want such PRs against master or stable?

**Comment by MaJoRoesch** [comment]
Honestly, this change should have been done when the option was changed to Store EFB Copies to Texture Only, but we had bikeshedded the name so so SO much, I was like, JUST MERGE IT!

The purpose of this is that EFB Copies to Texture and EFB Copies to RAM are used in the previous release, the code, and by devs/helpers on a regular basis. So I think it really needs to be mentioned in the description text. Also, it uses the "store" language that we bikeshedded over so much previously to be more descriptive overall, as opposed to the synchronization language which was, well, wrong.

**Comment by phire** [comment]
I vote stable.

**Comment by Armada651** [comment]
@degasus Preferably all PRs that should be in the stable release should be submitted against the stable branch. But for small PRs I don't mind cherry-picking them.

**Comment by Armada651** [comment]
@aserna3 Could you rebase this PR?

**Comment by aserna3** [comment]
I'm confused. Do you need me to rebase this to the stable branch? I'm really bad at rebasing. Could you give me instructions?

**Comment by phire** [comment]
You shouldn't need to rebase it, just recreate it the PR and pick the stable branch as the target.

Github will tell you if you need to manually rebase it

**Comment by aserna3** [comment]
I need to rebase and the instructions you gave me aren't working.

I either get no commits to rebase when I do "git rebase -i stable" or I get literally thousands which look like they're from master.

help

**Comment by aserna3** [comment]
After getting extensive help in IRC, it was recommended that I just make the changes to stable and PR against that. I've found the commit that renamed this option and can then apply my changes to that. Should I just make the changes there, apply my changes, and make a PR?

**Comment by AdmiralCurtiss** [comment]
Uh, this PR confuses me. The exact phrasing already seems to be in master.
https://github.com/aserna3/dolphin/blob/master/Source/Core/DolphinWX/VideoConfigDiag.cpp#L119

**Comment by neobrain** [comment]
Is there any long-term point in keeping around the old terminology?

**Comment by AdmiralCurtiss** [comment]
Oh I see what's going on. You have to sync your fork, see here: https://help.github.com/articles/syncing-a-fork/

**Comment by Armada651** [comment]
No need to rebase this on the stable branch, just rebase it on the master branch to resolve the merge conflict (I can't merge the PR like this). I'll cherry-pick this one to the stable branch since it's just one small commit.

**Comment by Armada651** [comment]
Merged in commit 8d69c2b4b722e2c4f9f0496b9ff1912c1a10d9e1.

**Pull request closed without merging**
