### PR TITLE
Branch Watch Tool: Add Set Breakpoints Submenu

### PR DESCRIPTION
**Pull request by mitaclaw**
First I rewrote the Table Context Menu code to only construct it once (lazily) and hide/show/activate/deactivate actions based on what column was right clicked to bring it up. Right clicking the table's scroll area when all columns are hidden will now bring up the Column Visibility Menu. I also made the `OnTableSetNOP` and `OnTableSetBLR` functions follow DRY.

Next, I made it possible to set breakpoints en-mass from a selection in the Branch Watch Tool. This works for the origin, destination, and symbol columns.

Branch Watch Tool Set Breakpoint

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
It would be nice if there was an actual marker on the option that is currently active if you right-click on a address that already has a breakpoint, but otherwise this seems to work as expected.

**Comment by mitaclaw** [comment]
I could try that, but it could get ugly if a multi-selection contains mixed or partial breakpoints.

**Comment by mitaclaw** [comment]
I hope this is satisfactory:
Full BP Partial BP
When every relevant address already has the same kind of breakpoint, the breakpoint icon will display on the action for setting that kind of breakpoint.  Otherwise, a square icon will display on each action for setting a breakpoint with a non-zero number of breakpoints of that kind already set at the relevant addresses.

**Comment by mitaclaw** [comment]
I realized I forgot to disable the Set Breakpoints menu when emulation was uninitialized (setting breakpoints without emulating anything is discouraged in the UI, even though it works fine at the moment). This is now fixed.

**Comment by AdmiralCurtiss** [comment]
#12862 actually removes that breakpoint UI behavior so I don't think that's really important...

Anyway, yeah I think this is way more clear now.

**Pull request merged**
