### PR TITLE
Set Medium Texture Cache for Fantastic Football Fan Party

### PR DESCRIPTION
**Pull request by RisingFog**
Fixes [issue 9531](https://bugs.dolphin-emu.org/issues/9531).

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3839)

### CODE REVIEW

**Comment by RisingFog** [comment]
@Linktothepast feel free to review this.

**Comment by JosJuice** [comment]
This needs to be a three-character INI. Six-character INIs are only used when actually required (for instance for AR codes, because they are specific to a certain version of a game) and for Triforce games. The current practice is to use a three-character INI for general settings for all GameCube/Wii games, even if the game only is released released in one region.

Also (perhaps less importantly), I don't like the branch name. Please use names that are short and make sense. This isn't your first time making a PR with a weird branch name.

**Comment by phire** [comment]
Does this mean you don't like my branch names either?

**Comment by JosJuice** [comment]
Nah, I'm mostly fine with names that contain funny things. This one just looks weird because it's so long. I'm not going to let that block this PR from being merged, though.

LGTM, but I'd like confirmation from someone else that 512 is the right value, because I don't remember how that scale works.

**Comment by mimimi085181** [comment]
512 is medium texture cache accuracy. 128 would be fast and 0 would be safe.

**Comment by JMC47** [comment]
LGTM

**Comment by lioncash** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3839)*

**Pull request merged**
