### PR TITLE
Update SFML to 2.4

### PR DESCRIPTION
**Pull request by meffij**
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4114)

### CODE REVIEW

**Comment by RisingFog** [comment]
@dolphin-emu-bot rebuild

**Comment by RisingFog** [comment]
@dolphin-emu-bot rebuild

**Comment by Helios747** [comment]
@dolphin-emu-bot rebuild

**Comment by shuffle2** [comment]
Please try another PR which doesn't somehow modify 720 files...dolphin has subset of SFML only.

**Pull request closed without merging**
