### PR TITLE
VideoCommon: Use unrestricted depth range on backends that support it.

### PR DESCRIPTION
**Pull request by CrossVR**
This reverts the vertex shader depth range processing.
Thus backends that don't support this feature will regress.

### CODE REVIEW

**Comment by DXGLdotinfo** [comment]
What backends support unrestricted depth range?

**Comment by Degerz** [comment]
What's the status of this PR and the drivers as well ? Any other blockers or does it need a rebase ?

**Comment by JMC47** [comment]
Some drivers were having issues with it last I checked.

**Comment by Degerz** [comment]
I think the only drivers left that didn't work were Intel's and maybe mobile vendors. Their Vulkan implementation straight up doesn't work on Windows and I don't know if it's been patched yet on the ANV driver to work with depth clamp. As for the mobile drivers, we'll need to see if they [passed](https://www.khronos.org/conformance/adopters/conformant-products) a more recent version of the Vulkan CTS ...

**Comment by jordan-woyak** [comment]
This PR has aged and needs a rebase. I am closing it now but can reopen upon request.

**Pull request closed without merging**
