### PR TITLE
DolphinDevice: Expose the host's CSPRNG

### PR DESCRIPTION
**Pull request by stblr**

### CODE REVIEW

**Review by vabold — APPROVED** [review]

**Comment by JosJuice** [comment]
What's the purpose of this?

**Comment by vabold** [comment]
Many methods of seeding a CSPRNG for GC games are deterministic on Dolphin. The usecase for this is encrypting UDP packets in GC games.

**Comment by JosJuice** [comment]
GC games can't access IOS devices, so I don't see how this PR solves that problem.

**Comment by vabold** [comment]
They can if you [manually implement them](https://github.com/doubledashdeluxe/ddd/blob/main/common/Dolphin.cc).

**Comment by JosJuice** [comment]
Wait, is Dolphin running IOS HLE while emulating a GameCube?

**Comment by sepalani** [comment]
> Wait, is Dolphin running IOS HLE while emulating a GameCube?

That or the game is run in Wii mode instead of GC mode: https://github.com/doubledashdeluxe/ddd/blob/e3294d4bdbe8d5ca6e7e3d8a105c2af50e66cb03/loader/loader/Start.cc#L58

**Comment by stblr** [comment]
Yeah this PR is only for "Wii mode". An alternative to this PR is ES_SIGN, but that cannot be accessed in most contexts (for instance from an HBC app) and thus would require the installation of a dummy channel to get the right permissions.

One thing I haven't investigated so far is where does IOS get its entropy from.

**Comment by stblr** [comment]
After some consideration, I think the dummy channel with ES_SIGN is the better approach even if it needs more code, as it has the advantage of only needing a single implementation for both the Wii and Dolphin (for the RNG part at least, channel installation is another story). Thus closing this.

**Pull request closed without merging**
