### PR TITLE
For idle loops, perform an exception check before CoreTiming::Advance.

### PR DESCRIPTION
**Pull request by magumagu**
This is more consistent with the way Dolphin behaves with idle skipping off.

### CODE REVIEW

**Comment by JMC47** [comment]
I can't get to the area to test now because it's segfaulting randomly.

**Comment by skidau** [comment]
@magumagu, you can't call CheckExternalException from the middle of a
jit block because CheckExternalException has the potential to update PC.

**Comment by magumagu** [comment]
@skidau Updated to be a bit more obviously safe.

**Comment by JMC47** [comment]
New Code fixes The Last Story's cutscene audio.

**Comment by delroth** [comment]
@dolphin-emu-bot rebuild (/me tests infra stuff)

**Comment by magumagu** [comment]
Ping.

**Comment by JMC47** [comment]
Ping again.

**Pull request merged**
