### PR TITLE
Core/Common: Convert all old-style casts into C++ casts

### PR DESCRIPTION
**Pull request by ligfx**
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4215)

### CODE REVIEW

**Comment by Fallcrest** [comment]
I could have sworn that another PR did this, and I cannot seem to find it among open or closed PRs. Anyone remember that?

**Comment by phire** [comment]
@dolphin-emu-bot rebuild

**Comment by nbohr1more** [comment]
Perhaps you are thinking of: 3565

https://github.com/dolphin-emu/dolphin/pull/3565

**Comment by JosJuice** [comment]
#3565 seems completely wrong. Could it be #3281?

**Comment by Fallcrest** [comment]
@JosJuice, thank you, that was it. For whatever reason, I couldn't find it.

**Comment by ligfx** [comment]
@Fallcrest looks like that other PR was blocked because it said it was an optimization, and it's not (which could be confusing in the commit logs).

To the best of my knowledge, C-style casts are replaced with the appropriate C++-style casts by the compiler, so there should be zero performance changes (maybe an infinitesimal increase in compiler speed, but don't quote me on that).

The main benefit, in my mind, of switching to C++-style casts is that they're more explicit and thus safer. I used `static_cast` here whenever I could, and `reinterpret_cast` for pointer casts (which are inherently not very safe, and can now be easily distinguished from simple static casts!).

**Comment by ligfx** [comment]
On further reflection, don't think it's worth it. There are so many C-style casts in the codebase it's probably better to just change them as individual sections get modified for other reasons.

**Pull request closed without merging**
