### PR TITLE
Small fix leak and optimize

### PR DESCRIPTION
**Pull request by Karaulov**
Small fix leak and optimize, Attempt number two :8ball:

### CODE REVIEW

**Comment by Helios747** [comment]
I recommend Googling some resources on how to use Git and practice on your own repository before making anymore Pull Requests.

Sorry.

**Comment by Karaulov** [comment]
i wrote:
git rebase -i HEAD~3

replace pick to fixup or squelch 

save, but it not works... :)

**Comment by Karaulov** [comment]
i try to drop b4d7810 and 2bccf42 but it too not works.

**Comment by Karaulov** [comment]
ok i try googleng it :+1:

**Pull request closed without merging**
