### PR TITLE
Qt/Debugger Memory View update frequency

### PR DESCRIPTION
**Pull request by TryTwo**
Adds update on Step.
Adds updates while the game is running. Not constant, requires an update trigger, such as clicking memory view. -- Similar to PR #7576

/edit Changed this to a preview of updates while running.

### CODE REVIEW

**Comment by dreamsyntax** [comment]
Is this PR still relevant @TryTwo ?
If resolved can we also close #7576

**Comment by TryTwo** [comment]
It is, dolphin still erases the memory display when the game is running. Of course, these PRs are horribly outdated.

In my custom debugger I even let it auto-update the displayed memory values when the game is running, plus color values that recently changed. I don't know how much people want features like this, so i haven't put effort into keeping it up.

**Comment by AdmiralCurtiss** [comment]
IMO the entire Memory View could use a big redesign, it's quite bad -- the old one from the WX days was a lot more usable. So if you have done that, some people would definitely appreciate that.

**Comment by TryTwo** [comment]
@[AdmiralCurtiss](https://github.com/AdmiralCurtiss) Can you list some improvements you'd like to see? Then I can compare with what I've already messed with.

**Comment by AdmiralCurtiss** [comment]
In no particular order and a bit rambly:
- The current implementation is horrible at keeping your position. Clicking anything jumps the window around in confusing ways, and it tries to 16-byte align itself even if you manually go to a non-16-byte-aligned offset.
- You can't just click into the hex view and type a value into it, like you would be able in say a standard hex-editor.
- Columns have no fixed width, so they may jump left and right while scrolling depending on the width of the content -- particularly in the Float view, but sometimes also in the ASCII one. The ASCII view is also weirdly inconsistent for no obvious reason.
- There's no way to set the amount of bytes per row, it's always 16.
- There's no mixed Hex left / Text right view, like a hex editor.
- No support for encodings like Shift-JIS, UTF-16, or UTF8.
- No base-10 integer view.
- WX had a view that displayed each 4 byte group as both hex and its IEEE float representation -- maybe we could expand on this combined with some previous issues and allow an arbitrary 'right' view (int, float, text, whatever) to a standard hex 'left' view?

**Comment by AdmiralCurtiss** [comment]
Might also be useful to integrate the Cheat Search into the Memory View better, but I think that's for after the memory view itself is nice.

**Comment by TryTwo** [comment]
I haven't done most of that. My stuff is mainly:

-  Color the target address, so you always know where that is. 
- Tighter spacing
- Shift clicking a value loads its address into the address box, crtl clicking loads the value into the edit box.
- Option to always align addresses to 0 so they don't skip around.
- Bookmark ability for known addresses.
- u32 + float/ascii displayed at the same time, but it's very hacky
- What I said before about auto-updates and highlighting recent changes to memory.

I think your idea on a separate right-side view logic would probably work better than what I did. Integers are a bit odd to deal with though, as they changed based on how many bytes you think they are composed of.

**Comment by TryTwo** [comment]
Does anyone know at what times UpdateDisasmDialog is needed to update the Code/Memory debug widgets? Right now if I open code widget, run a game, and then move an option slider it spams updates to the point Dolphin can crash!  I could put some checks on it, but I don't know when we actually want that signal. Also, RunAsCpuThread calls updatedisasmdialog too...

Secondly when the code/memory widget is updated it calls update on code/memory view widgets, but they both contain OnStateChanged and UpdateDisasmDialog updates. Isn't that just redundant?

I can test a lot of this stuff myself, but I feel I'll miss specific use cases that other people need.

**Comment by TryTwo** [comment]
Alright. I'll see if I can put out an update for testing.

**Comment by TryTwo** [comment]
@AdmiralCurtiss  Could you try this and tell me what you think? Start a game and point the memory at the stack/r1 address, then right click memoryview and select auto update, then run the game.

**Comment by TryTwo** [comment]
Yeah it's probably the update rate. It works even with 1ms, so it could go faster. The colors disappear faster with a shorter overall update interval. Maybe 400.

**Pull request closed without merging**
