### PR TITLE
[Need Testing] Externals: Update wxWidgets to 3.1.0

### PR DESCRIPTION
**Pull request by EmptyChaos**
Follow up from #3720.

wxWidgets 3.1.0 has improved HiDPI support via `FromDIP()` which provides a poor-man's version of Qt/CSS/GTK3/OSX Device Independent Pixels. This is needed to fix the worst of DolphinWX's HiDPI scaling problems.

The wxWidgets code is not completely vanilla, I made the following changes:
- Existing tree pruning is preserved
- comex's `__w64` unnecessary warning disable is carried over
- WXMSW `wxRadioBox` (src/msw/radiobox.cpp) was clipping off the right edge of text.
- Added `wxWindowMSW::GetContentScaleFactor()` which is not currently implemented on wx-master.
- Modified `wxWindowGTK::DoSetClientSize()` to not call a function in a way that does not adhere to the interface contract. This fixes Dolphin's Debug Toolbars on Linux/wxGTK.
- Modified `wxWindowMac::DoSetClientSize()` the same way since the code has the same logic flaw.

wxgtkfix

There are some minor updates to DolphinWX:
- [DolphinWX.vcxproj] I added EnableDpiAwareness to the manifest. wx3.1 removed its internal call to `SetProcessDPIAware()` (Microsoft has also deprecated that function) without which Windows will upscale Dolphin on HiDPI making everything blurry.
- [FrameTools.cpp] The default toolbar style used to include `wxTB_FLAT`, it needs to be specified manually now.
- [AboutDolphin.cpp] A wx-assert popup due to `wxALIGN_BOTTOM` on a `wxVERTICAL` sizer.
- [TasInputDlg.cpp] A bunch of wx-assert popups due to bad wxSizer parameters, also a loop which tried to attach some checkboxes to 2 different sizers simultaneously.
- [NetPlaySetupFrame.cpp] More wx-assert popups due to bad wxSizer parameters.
- [CodeView.cpp/DebuggerUIUtil.cpp/MemoryView.cpp] Various "use X instead" deprecation warnings in GCC.

I regenerated wx/wxgtk.h from ./configure and updated the CMakeLists.txt to get it to build on Linux; I also updated wx/wxcocoa.h by hand. Thanks to Lioncash, it's confirmed to build and run on OS X.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3737)

### CODE REVIEW

**Comment by lioncash** [comment]
Thanks for tackling this :)

**Comment by delroth** [comment]
I wonder if it should be considered for inclusion in 5.0. We've had some
hard to track bugs before with WX version bumps. OTOH, HiDPI support is
important.

**Comment by EmptyChaos** [comment]
There seems to be a serious whitespace conflict in the patch generated from the commit which is preventing the build bot from applying the patch. I'm not sure what I need to do resolve this.

**Comment by degasus** [comment]
sounds like a git issue....

**Comment by EmptyChaos** [comment]
I'm pretty stumped by this. I downloaded some of the patches as generated by the buildbot and diffed them against the output from `git format-patch -1 HEAD` and it's just long chains of:
```
-@@ -164,10 +164,8 @@ private:
+@@ -164,10 +164,8 @@ class WXDLLIMPEXP_CORE wxAcceleratorEntry
```
`git am localpatch` doesn't seem to like applying the patch to the XPMs (line endings were changed from windows to unix style in wx-master) but adding `--ignore-whitespace` fixes it. The patch processor seems to really hate dealing with different line endings. I don't think I did anything special that would cause this.

This is a problem because I'm worried about whether OS X even compiles, I was hoping the buildbot would tell me that. :/

**Comment by lioncash** [comment]
@EmptyChaos worst-case scenario, I can tell you if it compiles on my MacBook Pro after work

**Comment by delroth** [comment]
The patches are not generated by the Buildbot, they're generated by Github (
https://patch-diff.githubusercontent.com/raw/dolphin-emu/dolphin/pull/3737.patch
).

**Comment by EmptyChaos** [comment]
I think I've isolated the problem with the buildbot. version.rc contains an ISO-8869-1 Copyright symbol, I think the buildbots all use UTF-8 so were trying to process it as a character continuation byte which is invalid. I've removed src/msw/version.rc from the commit which seems to have fixed it. I also cleaned the whitespace problems by exporting the commit as a patch then reapplying with `--whitespace=fix`.

The FreeBSD bot was failing so I've updated wx/wxgtk.h and CMakeLists.txt to get the FreeBSD build to work. Unfortunately the OS X builder is still not working, it seems to be losing its connection to the build master for some reason (PBConnectionLost: Connection was closed cleanly).

**Comment by aserna3** [comment]
I'm iffy on including this in 5.0, while this does fix a ton of things just based off of my basic testing, I doubt that this doesn't cause regressions elsewhere. It's Wx.

**Comment by lioncash** [comment]
@EmptyChaos I attempted to build it on my MacBook, and I was presented with the following build failure: [pastebin](http://pastebin.com/KCCRdYBv)

**Comment by EmptyChaos** [comment]
@lioncash Looks like that file is missing its configure guards. Could you open Externals/wxWidgets3/CMakeLists.txt and find `"src/generic/activityindicator.cpp"` and put a comment (`#`) marker in front then rerun cmake && make?

**Comment by lioncash** [comment]
@EmptyChaos Almost makes it through compilation with that change, but fails on wxStandardPaths now
[pastebin](http://pastebin.com/t0Kct631)

**Comment by EmptyChaos** [comment]
@lioncash That file seems to only be intended for BSD/Linux; OS X has its own separate implementation which is supposed to be used instead. Could you comment out `"src/unix/stdpaths.cpp"` as well?

**Comment by aserna3** [comment]
Just tested your PR on my hi DPI windows system as well. The toolbar is still rendering low DPI icons. I don't know if your PR intended to fix that part or not.

**Comment by lioncash** [comment]
@EmptyChaos After commenting those both out, Dolphin builds and executes fine on OSX.

**Comment by EmptyChaos** [comment]
@aserna3 I haven't done any HiDPI modifications to DolphinWX in this PR, there are only some gains from some of wxWidget's own internal DPI bugs being fixed. The UI code in DolphinWX still needs to be modified one by one to use the new APIs, load the right icon bitmaps (on MSW/GTK, I think OS X does this automatically from the scale factor in `wxBitmap::LoadFile`), etc. [This is what I was referring to with `FromDIP()` being a poor-man's version of Qt's DIPs. The code in Dolphin has to be changed to use the new APIs in order for it to make a difference, it's not free with the version bump]

I was planning to do the HiDPI patches as a separate follow up PR from this to make them easier to review.

@lioncash I've updated the CMakeLists.txt to not try to build those files on OS X.

**Comment by DarthVitrial** [comment]
is this related to PR 3142?

**Comment by Pringo** [comment]
It would be nice to have wxWidgets updated now that 5.0 is out.

**Comment by lioncash** [comment]
Giving a buffer period of until ~6:30PM EST for others to get objections in or point things out, otherwise this is being merged.

**Comment by delroth** [comment]
Who needs buffer time when people can send followup fix PRs?

**Comment by lioncash** [comment]
Fair enough

**Comment by Nucleoprotein** [comment]
Windows 10 x64, following thing broken by this PR :
- Dolphin now set itself below opened windows at start
- Colum lines are visible
- "Maker" and "File" columns are visible but rolled up
Screenshot: http://imgur.com/a/OT5LR

**Comment by Pringo** [comment]
I am getting the same first two issues as @Nucleoprotein in Windows 10. I'm not sure if the column lines are a bug or a new feature but they look off in the Region column. I noticed that enabling the Game ID column seems to fix that. Other than that I think the visible column lines actually look a bit neater than the old UI.

**Comment by davidbepo** [comment]
cannot set language to spanish after this

**Comment by EmptyChaos** [comment]
@davidbepo What do you mean "cannot set"? Is it still displaying in English after you exit and reopen? Which platform (Win7/8/10, Linux, OS X)?

**Comment by davidbepo** [comment]
exactly the option is set to spanish but dolphin still displays in english
im on linux

**Comment by Nucleoprotein** [comment]
On Windows language change works fine.

**Comment by davidbepo** [comment]
a screenshot of the issue
captura de pantalla de 2016-07-16 14-00-50

**Comment by Nucleoprotein** [comment]
Make sure you have .mo files (ie. translation files) in proper directory or it will fallback to english.

**Comment by EmptyChaos** [comment]
@davidbepo It should be fixed by #4015.

**Comment by gamax92** [comment]
Apologies for being late to the testing party, but I'm having an issue with this change.
Each time I go to run a game, Dolphin seems to forget what my old game window size was or ignoring the "Auto adjust Window Size" setting, defaulting to some tiny window.
Tiny Window
Versions before this change don't exhibit this issue, instead immediately displaying games in a correctly sized window.
I don't have multiple monitors or HiDPI displays so I don't think that's related

**Comment by Pringo** [comment]
@gamax92 Does #4013 fix your problem?

**Comment by gamax92** [comment]
@Pringo Indeed it does, will be happy with that PR getting merged in

**Pull request merged**
