### PR TITLE
Change default overlay settings for emulated wii classic controller

### PR DESCRIPTION
**Pull request by yingshaoxo**

### CODE REVIEW

**Comment by Rumi-Larry** [comment]
A few comparision screenshots would be useful here.

**Comment by MayImilae** [comment]
Your motivation for this would be nice too. Why do you want us to merge this into Dolphin?

**Comment by JosJuice** [comment]
@yingshaoxo Giving people a binary of Dolphin without making the source code available is against Dolphin's license. Unless you're going to comply with the license and make the source code available, you need to remove your fork of Dolphin from Google Play.

**Comment by yingshaoxo** [comment]
Can I make a fresh new simulator?

**Comment by JosJuice** [comment]
If you're not using our code or other assets, you can do whatever you want as far as we're concerned.

**Comment by yingshaoxo** [comment]
OK

I just unpublished the google play app, it will take 1 hour

And I'm going to create a fresh new simulator by spending one month

And you won't catch me 😉

**Comment by yingshaoxo** [comment]
@JosJuice 

I just gave up. Dev an emulator is too complexed to finish in a short time.

___

I just want to ask, if I open source the code, can I use it for commercial use? Like publish the apk as a paid app to google play?

**Pull request closed without merging**
