### PR TITLE
Android: Remove the old UI, and remove support for pre-5.0 devices.

### PR DESCRIPTION
**Pull request by sigmabeta**
The new UI is effectively at feature parity and nary a soul exists who wants to work on the old one.

Let's kill it with fire, so we can move on to bigger and better things.

Edit: I should've made this clearer before, but effectively this PR will end support for Android devices running OS older than 5.0

### CODE REVIEW

**Comment by ds84182** [comment]
Is it OK if I make a pull request with my AppCompat changes now?

**Comment by sigmabeta** [comment]
I assume what you mean by that is to switch out all the Android 5.0+ UI views with their AppCompat equivalents.

The biggest thing that'll get us is the ability to run the new UI on pre-5.0 devices. I am trying to remove support for those intentionally, because any device that has a chance of running Dolphin capably will come preloaded with, or has been updated to, 5.0.

I've been meaning to move to AppCompat equivalents eventually anyway, as it will add some future-proofing (and may be required to use the Design Support Library announced last week). If you've already done this, there's no reason not to submit a PR for it once this is merged.

**Comment by sigmabeta** [comment]
By the way, you don't need to ask permission to make PRs - I'd love it if the Android UI wasn't a one-man project. Join us in the IRC so we can plan things out.

**Comment by sigmabeta** [comment]
Anything blocking a merge here?

I know there are still some feature-parity issues, but unless they are considered giant showstoppers I would like to have them in master so people see them / report them / have opinions about them.

**Comment by Sonicadvance1** [comment]
Someone brought it up to me that the input overlay configuration no longer works.
I've investigated and it looks like this one is the culprit.
Removing the old UI, managed to accidentally remove the input config overlay activity. Which is of course still required in the new UI.
If you could fix this that would be great.

**Pull request merged**
