### PR TITLE
TextureConversionShader: Also invert color encoders if they're used to encode depth.

### PR DESCRIPTION
**Pull request by Armada651**
The WriteC8Encoder and WriteC4Encoder are also used to encode depth buffers, but when D3D depth inversion was implemented I only accounted for the encoders that were only used for depth.

This fixes Metroid Prime 2 when using the depth visor to scan objects, [issue 8925](https://bugs.dolphin-emu.org/issues/8925).

### CODE REVIEW

**Comment by delroth** [comment]
LGTM. Please get a review from someone who understands our video code better than I do (degasus?) and feel free to merge.

**Comment by JMC47** [comment]
Confirmed to work.

**Comment by degasus** [comment]
Yeah, sounds fine to me.

**Comment by phire** [comment]
LGTM

**Pull request merged**
