### PR TITLE
GCI Folder: Skip 'header-only' writes

### PR DESCRIPTION
**Pull request by LPFaint99**
issue #8961

This should be merged to both master and stable

### CODE REVIEW

**Comment by JMC47** [comment]
For those who don't want to read the issue, a game could go through and corrupt an entire GCI folder through this in some weird scenario.

**Comment by phire** [comment]
Could we get a comment saying why we need to skip writing if only the header is modified?

**Comment by LPFaint99** [comment]
sure thing.
I figured this would be a better way to get feedback on the different options of preventing this issue, since the bugtracker didn't seem to.

The GCIFolder only loads the header into memory until the game reads/writes to the block area.
This unusual scenario of a game modifying the header broke a (bad) assumption that the save_blocks were in memory when flushing the save to disk.

This solution is to simply ignore header writes if the game hasn't writtento/read from the save blocks.

An alternative would be to change the logic to use the "r+b" mode when writing files (and create an empty file the first time the save is written)

A third (ugly) option would be to load the savedata into memory before saving using 'LoadSaveBlocks' which only reads the data if m_save_data.size is 0

**Comment by phire** [comment]
It's an ok solution, as there isn't really any important data in the header that would make a header only write make sense.

**Comment by cammelspit** [comment]
+1billion.. dont know if this has anything to do with my problem but I just recently had this exact issue https://forums.dolphin-emu.org/Thread-all-gci-files-corrupted and would ADORE to see a fix for it for my own peace of mind. Sorry for commenting on the GitHub but you are all my heroes. Keep it up!

**Comment by LPFaint99** [comment]
@cammelspit yeah, this should prevent the issue that you reported

**Comment by BhaaLseN** [comment]
Does it have to be an ERROR? Other than that, its probably a good enough solution.

**Comment by phire** [comment]
It's an ERROR_LOG, so it will just show up in the log at the error level.

It's an error because as far as we know this shouldn't happen, but apparently it is.

**Comment by BhaaLseN** [comment]
LGTM then.

**Comment by phire** [comment]
LGTM

**Comment by LPFaint99** [comment]
what's the procedure for getting this merged to stable?

**Comment by JosJuice** [comment]
The procedure is to ask @Armada651.

**Comment by aserna3** [comment]
@Armada651 ping.

**Pull request merged**
