### PR TITLE
DolphinWX: Don't use a special color for compressed games

### PR DESCRIPTION
**Pull request by JosJuice**
- There's no clear definition of what it means for a GC/Wii game to be compressed. GC games in GCZ are obviously compressed, but what about formats like WBFS and CISO that just discard data?
- Hardcoded colors might have bad contrast with the used theme. (PR #4939 brought this to my intention.)
- It feels Windows XP to me.

### CODE REVIEW

**Comment by FishamanP** [comment]
Would it be possible to instead make the "compressed" color a theme option?
It's always been incredibly useful for me to distinguish between game dumps and folder locations.

**Comment by JosJuice** [comment]
It's not impossible, but right now, Dolphin themes are just a set of images, nothing more. If we start including colors in them, I don't think we just should do it for something small like the compressed games color. (Note that the "theme" I was talking about in the PR description was the OS theme, not the Dolphin theme.)

In case you're interested, there's already a setting in Dolphin.ini for disabling/enabling the compression color. It's `ColorCompressed` in `[GameList]`.

**Comment by Helios747** [comment]
SGTM purely because it looks Windows XP.

**Comment by shuffle2** [comment]
It would probably make more sense to display the detected file type rather than only if it's compressed or not.

**Comment by degasus** [comment]
I agree with shuffle2, but feel free to do so in another PR. LGTM

**Comment by Helios747** [comment]
I'm merging this because I want to be involved in making Dolphin XP-less.

**Comment by MayImilae** [comment]
I definitely agree that showing the file type makes more sense than the compressed color! Ideally for me, the file type would be an additional column in the interface, and not added to the name or something silly.

**Comment by mbc07** [comment]
Current Windows versions display an overlay with two small blue arrows on the icon of files marked as compressed, but just like the blue color we had before, it's not something pretty to look at. Showing the file type as an additional column sounds good, though...

**Comment by sjnewbury** [comment]
I've updated #4939 to account for this landing.

**Pull request merged**
