### PR TITLE
Update to MaJoR1's latest on screen buttons

### PR DESCRIPTION
**Pull request by Sonicadvance1**
This change is [Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3722)

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
Example look of the buttons provided by MaJoR1
Image

**Comment by FishamanP** [comment]
I think I prefer the old style. The buttons are much easier to pick out from game content.

**Comment by Tsunamical** [comment]
These look wonderful imo

**Comment by Tsunamical** [comment]
Any update on these?

**Comment by MaJoRoesch** [comment]
@delroth @lioncash Merge pleeeaase!

**Pull request merged**
