### PR TITLE
Update Android cmake.

### PR DESCRIPTION
**Pull request by Sonicadvance1**
This is required to properly build the MIPS64 and x86_64 targets with clang.

### CODE REVIEW

**Comment by Icekhaos** [comment]
Wait.

We have a MIPS port now?

**Comment by Sonicadvance1** [comment]
Nope

**Comment by Alegend45** [comment]
"This is required to properly build the MIPS64 and x86_64 targets with
clang." implies that there's a MIPS64 port.

**Comment by Sonicadvance1** [comment]
There isn't.

**Comment by Icekhaos** [comment]
Then why do we need it to build on MIPS and Intel?

**Comment by pauldacheez** [comment]
MIPS "support" is interpreter-only and is done via the "generic" build config, which builds as long as you're building for a little-endian architecture that your compiler supports. Without a JIT, though, you can't really call an arch "supported", can you?

**Comment by Icekhaos** [comment]
Actually, yes, you can, but not supported by official means, rather as collateral. Provided as-is is sufficient here.

**Comment by Sonicadvance1** [comment]
We test multiple build targets that we don't support purely on the basis to make sure we remain portable enough to potentially be on those platforms.
If in the future someone wants to add support, we choose to make their life easier.
Makes sure we don't have any architecture specific quirks that would impede development on a new architecture.

**Comment by Icekhaos** [comment]
Might then be my learning dive into MIPS.

**Comment by Sonicadvance1** [comment]
There aren't any MIPS32 targets that are capable of running our OpenGL backend.
I'd recommend MIPS64 since it would be a more viable target.

**Comment by Icekhaos** [comment]
When the Warrior I goes into full scale production, I will probably get myself to do something about that. As is, no 64 bit MIPS processor is out.

**Comment by Sonicadvance1** [comment]
Aye, which is why the AArch64 recompiler core was started under qemu

**Pull request merged**
