### PR TITLE
CMake: make option ENABLE_SDL work again

### PR DESCRIPTION
**Pull request by ligfx**
Broken in PR #4755 / commit f978765

### CODE REVIEW

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by tienhahoi** [comment]
Vào Th 3, 07 thg 2 2017 lúc 13:25 Matthew Parlane <notifications@github.com>
đã viết:

**Pull request merged**
