### PR TITLE
Synchronize DVDInterface::ChangeDisc with the CPU thread properly

### PR DESCRIPTION
**Pull request by JosJuice**
This is an updated version of PR #2535. Fixes a 5.0 blocker: https://bugs.dolphin-emu.org/issues/8568

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by Tilka** [comment]
I assume you have tested that it really does fix the bug?

**Comment by JosJuice** [comment]
I thought I had tested it back when the original PR was created and found that it worked fine, but apparently not... Now that I run a build of this PR, there's a "ScheduleEvent from wrong thread" instead of "ScheduleEvent_Threadsafe from wrong thread".

**Comment by JosJuice** [comment]
I made the typo `bool is_cpu = !Core::IsCPUThread();` while updating the commit. Oops! Thanks for reminding me about the importance of testing. I've confirmed that the current version of this PR works without problems when recording input, playing back input, and using Dolphin normally.

**Pull request merged**
