### PR TITLE
Restore saving logger settings to .ini

### PR DESCRIPTION
**Pull request by shuffle2**
This was broken by https://github.com/dolphin-emu/dolphin/pull/4231

The callstack is:
```
>	DolphinD.exe!LogConfigWindow::SaveSettings() Line 136	C++
 	DolphinD.exe!LogConfigWindow::~LogConfigWindow() Line 35	C++
 	DolphinD.exe!LogConfigWindow::`scalar deleting destructor'(unsigned int)	C++
 	DolphinD.exe!wxWindowBase::Destroy() Line 574	C++
 	DolphinD.exe!CFrame::DoRemovePage(wxWindow * Win, bool bHide) Line 453	C++
 	DolphinD.exe!CFrame::ToggleLogConfigWindow(bool bShow) Line 145	C++
 	DolphinD.exe!CFrame::ClosePages() Line 181	C++
 	DolphinD.exe!CFrame::~CFrame() Line 558	C++
 	DolphinD.exe!CFrame::`scalar deleting destructor'(unsigned int)	C++
 	DolphinD.exe!wxAppConsoleBase::DeletePendingObjects() Line 637	C++
 	DolphinD.exe!wxAppConsoleBase::ProcessIdle() Line 445	C++
 	DolphinD.exe!wxAppBase::ProcessIdle() Line 373	C++
 	DolphinD.exe!wxEventLoopBase::ProcessIdle() Line 98	C++
 	DolphinD.exe!wxEventLoopManual::DoRun() Line 263	C++
 	DolphinD.exe!wxEventLoopBase::Run() Line 76	C++
 	DolphinD.exe!wxAppConsoleBase::MainLoop() Line 380	C++
 	DolphinD.exe!wxAppConsoleBase::OnRun() Line 302	C++
 	DolphinD.exe!wxAppBase::OnRun() Line 312	C++
 	DolphinD.exe!wxEntryReal(int & argc, wchar_t * * argv) Line 503	C++
 	DolphinD.exe!wxEntry(int & argc, wchar_t * * argv) Line 181	C++
 	DolphinD.exe!wxEntry(HINSTANCE__ * hInstance, HINSTANCE__ * __formal, char * __formal, int nCmdShow) Line 290	C++
 	DolphinD.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * __formal, int nCmdShow) Line 59	C++
 	DolphinD.exe!invoke_main() Line 99	C++
 	DolphinD.exe!__scrt_common_main_seh() Line 253	C++
 	DolphinD.exe!__scrt_common_main() Line 296	C++
 	DolphinD.exe!WinMainCRTStartup() Line 17	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
```
Is this bad on OSX for some reason?

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4292)

### CODE REVIEW

**Comment by EmptyChaos** [comment]
I think the problem is that it goes CFrame::OnClose -> DolphinApp::OnExit -> CFrame::~CFrame -> CLogWindow::~CLogWindow -> Dereference dead LogManager -> Crash.

**Comment by shuffle2** [comment]
Oh so m_LogManager is free'd while in LogConfigWindow::SaveSettings...?

**Comment by EmptyChaos** [comment]
By UICommon::Shutdown in DolphinApp::OnExit then the destructor is called after that happened. I'm guessing, but that's the only obvious potential problem I see.

**Comment by shuffle2** [comment]
LogConfigWindow::SaveSettings is called before UICommon::Shutdown so I'm not seeing the problem :/

**Comment by EmptyChaos** [comment]
If you're testing on OS X then the problem supposedly only happens when exiting through the Dock Icon, Right Click Dock Icon > Exit or something. If it doesn't crash then there isn't a problem any more, I guess?

**Comment by ligfx** [comment]
@shuffle2 what OS did you see this issue on?

**Comment by shuffle2** [comment]
@ligfx as @EmptyChaos said, OnClose is not fired for this class, at least on windows...

**Comment by ligfx** [comment]
This does break quitting from the Dock on macOS, but upon further investigation it seems to be because of something weird with wxWidgets (OnEndSession gets called with events pending, so `main_frame` doesn't get destroyed until _after_ `OnExit`), not an issue with this code. So 👍  on this PR.

**Pull request merged**
