### PR TITLE
Removed the ability for PAL televisions to be set to progressive mode.

### PR DESCRIPTION
**Pull request by skidau**

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
I got shouted at last time I tried to change the hardware emulation logic. I suggest a if ( bWii && !bNTSC && !bPAL60 ) { bProgressive = false; } in the BootManager instead.

**Comment by skidau** [comment]
Your suggestion isn't correct because there should be no difference between a GC and a Wii.

Let me know if PAL60 really does break.  Going by the theory that PAL60 is NTSC timing on a PAL television, this PR seems plausible.  Up for discussion tho.

**Comment by AdmiralCurtiss** [comment]
Well then without the bWii in the if.

**Comment by skidau** [comment]
We cannot simply switch the bProgressive flag because it represents a component cable being used to connect the console to the TV.

**Comment by skidau** [comment]
Tested The Last Story PAL (EuRGB60), Xenoblade PAL (Wii PAL60), ZWW PAL (GC PAL60), MKDD NTSC (GC Prog) and they all work.

**Comment by yorkiesandskittles** [comment]
By "PAL" televisions, do you mean 50Hz-only TVs or actual PAL region TVs
capable of all resolutions and modes?

**Comment by AdmiralCurtiss** [comment]
I'm not entirely convinced this is right but this does seem to fix the Xenoblade PAL 50Hz/Progressive crash without disabling 60Hz modes, so okay.

I still think the Progressive option should be split from the Component Cable option, for the record.

**Pull request merged**
