### PR TITLE
Remove ARMv7 support.

### PR DESCRIPTION
**Pull request by Sonicadvance1**

### CODE REVIEW

**Comment by sigmabeta** [comment]
Looks so, so, so good to me.

**Comment by lioncash** [comment]
gonna have to word this PR

**Comment by Sonicadvance1** [comment]
@dolphin-emu-bot rebuild

**Comment by Sonicadvance1** [comment]
@dolphin-emu-bot rebuild

**Comment by JBoughter** [comment]
So, if I read this right, ARMv7 devices no longer work?

**Comment by sigmabeta** [comment]
ARMv7 devices have crashed on launch for about 2,000 commits now, when running Android 5.0 or above.

The app fails to map enough memory to start emulation, and crashes. It seems to be related to adding 64-bit support, but no one really knows why. Until someone who is a POSIX/Linux expert helps us figure out how to make it work, we can't really do anything about it.

Combined with the fact that 64-bit ARM devices now exist, which cannot use most of the existing JIT work and need a lot of attention to be properly supported, and the fact that no 32-bit device was ever really going to have a shot of offering reliable performance, there isn't a lot of reason to keep allowing people to install an app that will crash on launch.

**Comment by duskgao** [comment]
PLZ release the last build which support ARMv7 devices...

**Pull request merged**
