### PR TITLE
IPC_HLE: Small cleanup

### PR DESCRIPTION
**Pull request by leoetlino**
This is mostly moving code around, removing duplicate code, dropping dead/unneeded code and cleaning up naming, includes and logging.

The first three commits were originally part of another PR I'm working on, but I split some commits into this PR since the changes were independent and to make it easier to review.

(Note: looks like this PR may not be as _small_ as I originally intended it to be, but I've split the changes in different commits.)

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4375)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 43 files reviewed at latest revision, 9 unresolved discussions.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device.h, line 13 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWF_f1u-EpTHGJyPW_N:-KWF_f1u-EpTHGJyPW_O:biikprp) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device.h#L13)):*
> ```objc
> #include "Common/ChunkFile.h"
> #include "Common/CommonTypes.h"
> #include "Common/Logging/Log.h"
> ```

Log shouldn't need to be included in the header anymore, the relevant functions that use log calls aren't defined in the header anymore.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_fs.h, line 10 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFa8N46ENtSaaXFKbZ:-KWFa8N5T7KkKTc44KO2:b-q67ky8) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_fs.h#L10)):*
> ```objc
> 
> #include "Common/CommonTypes.h"
> #include "Core/HW/SystemTimers.h"
> ```

You can move `GetFSReply()` to the cpp file to avoid including this in the header.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_sdio_slot0.h, line 20 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFb8_--rQ5TJRHerF9:-KWFb8_--rQ5TJRHerFA:bxhd6t) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_sdio_slot0.h#L20)):*
> ```objc
> namespace File
> {
> class IOFile;
> ```

This forward declaration should be removed if `FileUtil` is included.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_sdio_slot0.h, line 128 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFaSXzQdzxSAzUwfnQ:-KWFaSXzQdzxSAzUwfnR:bi0uhko) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_sdio_slot0.h#L128)):*
> ```objc
>   u32 m_Registers[0x200 / 4];
> 
>   File::IOFile m_Card = nullptr;
> ```

This initializes the internal handle to nullptr by default, so this isn't necessary.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_base.h, line 7 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFZOQb_RStx5Ou1JFt:-KWFZOQcT1ae09F2r7FF:b-h8tj1i) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_base.h#L7)):*
> ```objc
> #pragma once
> 
> #include <stddef.h>
> ```

`<cstddef>

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_base.h, line 11 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFZSO8wib8b5Z1ee-K:-KWFZSO8wib8b5Z1ee-L:b-z8m23x) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_base.h#L11)):*
> ```objc
> 
> #include "Common/CommonTypes.h"
> #include "Core/HW/Memmap.h"
> ```

If you move CtrlBuffer::SetRetVal's implementation into the cpp file, you won't need to include this in the header file.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.h, line 14 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWF_73xdObQDHdBamIz:-KWF_73yP9MDia7Lu87P:bp8fblb) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.h#L14)):*
> ```objc
> #include <vector>
> 
> #include "Common/ChunkFile.h"
> ```

As far as I can tell, you can just forward declare PointerWrap instead of including this.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.h, line 16 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFZwdNqV1iPoVJVmPb:-KWFZwdNqV1iPoVJVmPc:bklrj5l) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.h#L16)):*
> ```objc
> #include "Common/ChunkFile.h"
> #include "Common/CommonTypes.h"
> #include "Common/MsgHandler.h"
> ```

You can move SQueuedEvent's constructor into the cpp file to avoid including this in the header (this would also apply to cstring)

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_kbd.h, line 11 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWF_NDHKHVcq_YrwQNv:-KWF_NDIFscVAKVpjIBV:b62uuty) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_kbd.h#L11)):*
> ```objc
> #include <string>
> 
> #include "Common/CommonFuncs.h"
> ```

You can move SMessageData's constructor into the cpp file, which would get rid of needing to include this and cstring in the header file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375)*

**Comment by leoetlino** [comment]
Review status: 0 of 43 files reviewed at latest revision, 9 unresolved discussions.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device.h, line 13 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWF_f1u-EpTHGJyPW_N:-KWFcpIj2L5omkTjXpnT:b5bnpww) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device.h#L13)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> Log shouldn't need to be included in the header anymore, the relevant functions that use log calls aren't defined in the header anymore.
</details>
There are no log calls anymore, but DumpCommands and DumpAsync still use LogTypes::LOG_TYPE and LogTypes::LOG_LEVELS. So including the header seems to be still necessary.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_fs.h, line 10 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFa8N46ENtSaaXFKbZ:-KWFdRqbaE59pGnzjXkL:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_fs.h#L10)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> You can move `GetFSReply()` to the cpp file to avoid including this in the header.
</details>
Done.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_sdio_slot0.h, line 20 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFb8_--rQ5TJRHerF9:-KWFdceYi9RG8d3P6SMM:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_sdio_slot0.h#L20)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> This forward declaration should be removed if `FileUtil` is included.
</details>
Done.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_sdio_slot0.h, line 128 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFaSXzQdzxSAzUwfnQ:-KWFdpf47NIAMN7FNhaX:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_sdio_slot0.h#L128)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> This initializes the internal handle to nullptr by default, so this isn't necessary.
</details>
Done.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_base.h, line 7 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFZOQb_RStx5Ou1JFt:-KWFdssRe1c5EQ6MZQEw:b3kre) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_base.h#L7)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> `<cstddef>
</details>
?

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_base.h, line 11 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFZSO8wib8b5Z1ee-K:-KWFeAyLBC1ZZoH0u4CE:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_base.h#L11)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> If you move CtrlBuffer::SetRetVal's implementation into the cpp file, you won't need to include this in the header file.
</details>
Done.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.h, line 14 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWF_73xdObQDHdBamIz:-KWFeJIAn4C2dpCPsh67:b-ajc364) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.h#L14)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> As far as I can tell, you can just forward declare PointerWrap instead of including this.
</details>
You're right. IWYU (and I) seems to have missed this…

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.h, line 16 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFZwdNqV1iPoVJVmPb:-KWFfW9DOM2zHNGNsIfU:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.h#L16)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> You can move SQueuedEvent's constructor into the cpp file to avoid including this in the header (this would also apply to cstring)
</details>
Done.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_kbd.h, line 11 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWF_NDHKHVcq_YrwQNv:-KWFfzVvLTcELsmsLJau:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_kbd.h#L11)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> You can move SMessageData's constructor into the cpp file, which would get rid of needing to include this and cstring in the header file.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375)*

**Comment by lioncash** [comment]
*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_base.h, line 7 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFZOQb_RStx5Ou1JFt:-KWFk4kZfq-c335hYQrN:b-8nhh7k) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_base.h#L7)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> ?
</details>
Whoops, I meant to write:`<cstddef>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375)*

**Comment by lioncash** [comment]
*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device.h, line 13 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWF_f1u-EpTHGJyPW_N:-KWFl1zTg5FuPDvA7-Sk:bt1ntkd) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device.h#L13)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> There are no log calls anymore, but DumpCommands and DumpAsync still use LogTypes::LOG_TYPE and LogTypes::LOG_LEVELS. So including the header seems to be still necessary.
</details>
Ah OK. Technically you could add `: int` to the `LOG_TYPE` and `LOG_LEVELS` enums to give them a concrete size, then they can be forward declared, but I wouldn't worry about that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375)*

**Comment by leoetlino** [comment]
Review status: 0 of 43 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_base.h, line 7 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWFZOQb_RStx5Ou1JFt:-KWFoLqGsfq6ItD1IZw8:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a3c43c70de10f13fb19d13de71555a9b2ac86fdb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_base.h#L7)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> Whoops, I meant to write:`<cstddef>`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375)*

**Comment by JosJuice** [comment]
Reviewed 34 of 43 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp, line 582 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWyMQNHykEmAyyNrVeq:-KWyMQNIjdDRmd1NecpR:b-m8qitm) ([raw file](https://github.com/dolphin-emu/dolphin/blob/10b4529cf3ead5a4eb9e7d8e4c57b4d091c84590/Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp#L582)):*
> ```cpp
> 
> // Helper function that handles overwriting the cmd and fd fields for async replies.
> void EnqueueAsyncReply(const u32 command_address)
> ```

Is it possible to find a better name for this? The `Async` implies that it does something asynchronously, which is misleading (at least when called from the CPU thread).

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp, line 588 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWyMeSl6oaaUjlDY0NX:-KWyMeSm14cLJ5t7Ya0l:b-axboty) ([raw file](https://github.com/dolphin-emu/dolphin/blob/10b4529cf3ead5a4eb9e7d8e4c57b4d091c84590/Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp#L588)):*
> ```cpp
>   // IOS also overwrites the command type with the async reply type.
>   Memory::Write_U32(IPC_REP_ASYNC, command_address);
>   EnqueueReply(command_address, 0, CoreTiming::FromThread::ANY);
> ```

Like a comment in `CoreTiming` says, please don't use `ANY` unless it's actually required. This function should probably take a `FromThread` parameter in the same way as `EnqueueReply`.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device.h, line 84 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWyOqTtaolh5QrLF-dK:-KWyOqTu3LORGfcj62aD:bhx4i9r) ([raw file](https://github.com/dolphin-emu/dolphin/blob/10b4529cf3ead5a4eb9e7d8e4c57b4d091c84590/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device.h#L84)):*
> ```objc
>   virtual bool IsHardware() const { return m_Hardware; }
>   virtual bool IsOpened() const { return m_Active; }
>   // Returns an IPCCommandResult for a reply that takes 250 us (arbitrarily chosen value)
> ```

The comment references an exact time. Is there an unnecessarily large risk of the comment becoming out of date because it isn't close to the implementation?

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.cpp, line 35 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWyQ8zvjFVkzZeWIIwp:-KWyQ8zwlXiRUZuYD4-e:bbtpzm) ([raw file](https://github.com/dolphin-emu/dolphin/blob/10b4529cf3ead5a4eb9e7d8e4c57b4d091c84590/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.cpp#L35)):*
> ```cpp
>   {
>     PanicAlert("SQueuedEvent: allocate too big buffer!!");
>   }
> ```

Remove the braces. You might also want to reword the message (e.g. "SQueuedEvent: The size is too large!") because the old one's grammar is bad and because it's misleading to talk about allocations when nothing is getting allocated based on the size.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_ven.cpp, line 10 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWyL6i64ZBTLP1kWrIt:-KWyL6i7Oz4nAoSyazfY:bkyso17) ([raw file](https://github.com/dolphin-emu/dolphin/blob/10b4529cf3ead5a4eb9e7d8e4c57b4d091c84590/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_ven.cpp#L10)):*
> ```cpp
> 
> CWII_IPC_HLE_Device_usb_ven::CWII_IPC_HLE_Device_usb_ven(u32 dev_id, const std::string& dev_name)
>     : IWII_IPC_HLE_Device(dev_id, dev_name)
> ```

Please use `device` instead of `dev` in these variable names, both because the meaning of `dev` might not be clear and because it's good to aim for using the same names in the .cpp file as in the .h file (see https://github.com/dolphin-emu/dolphin/pull/3932#issuecomment-228547225)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375)*

**Comment by leoetlino** [comment]
Review status: 30 of 45 files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp, line 582 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWyMQNHykEmAyyNrVeq:-KWyhGUWOaNhdI8HNnVZ:b-en4nyi) ([raw file](https://github.com/dolphin-emu/dolphin/blob/10b4529cf3ead5a4eb9e7d8e4c57b4d091c84590/Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp#L582)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary>
> Is it possible to find a better name for this? The `Async` implies that it does something asynchronously, which is misleading (at least when called from the CPU thread).
</details>
As discussed on IRC, I have removed this and moved the async syscall handling part to EnqueueReply itself.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp, line 588 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWyMeSl6oaaUjlDY0NX:-KWyhOp4VvHBPkkkJop-:b7c5swz) ([raw file](https://github.com/dolphin-emu/dolphin/blob/10b4529cf3ead5a4eb9e7d8e4c57b4d091c84590/Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp#L588)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary>
> Like a comment in `CoreTiming` says, please don't use `ANY` unless it's actually required. This function should probably take a `FromThread` parameter in the same way as `EnqueueReply`.
</details>
Done. (Missed that; sorry!)

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device.h, line 84 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWyOqTtaolh5QrLF-dK:-KWyht1mn6RjQLoeJUF-:b-n4mnuj) ([raw file](https://github.com/dolphin-emu/dolphin/blob/10b4529cf3ead5a4eb9e7d8e4c57b4d091c84590/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device.h#L84)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary>
> The comment references an exact time. Is there an unnecessarily large risk of the comment becoming out of date because it isn't close to the implementation?
</details>
I agree. I have moved the two comments to the implementation.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.cpp, line 35 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWyQ8zvjFVkzZeWIIwp:-KWyi15rSBHTgyhYckq6:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/10b4529cf3ead5a4eb9e7d8e4c57b4d091c84590/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_bt_emu.cpp#L35)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary>
> Remove the braces. You might also want to reword the message (e.g. "SQueuedEvent: The size is too large!") because the old one's grammar is bad and because it's misleading to talk about allocations when nothing is getting allocated based on the size.
</details>
Done.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_ven.cpp, line 10 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KWyL6i64ZBTLP1kWrIt:-KWyiAxJMTzMxC0WJdK6:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/10b4529cf3ead5a4eb9e7d8e4c57b4d091c84590/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_usb_ven.cpp#L10)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary>
> Please use `device` instead of `dev` in these variable names, both because the meaning of `dev` might not be clear and because it's good to aim for using the same names in the .cpp file as in the .h file (see https://github.com/dolphin-emu/dolphin/pull/3932#issuecomment-228547225)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375)*

**Comment by JosJuice** [comment]
Reviewed 15 of 15 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp, line 565 at r3](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KX0k8-U9bpWWx0uHcpm:-KX0k8-VVvy_yfK98irs:b1dxnwa) ([raw file](https://github.com/dolphin-emu/dolphin/blob/1d492871b2b2caad2a866bc2ab8d9c5c4a2be8bf/Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp#L565)):*
> ```cpp
> }
> 
> // Called to send a reply to an IOS async syscall
> ```

Remove "async" from this comment. This function is used for sending replies to all syscalls, regardless of whether they get executed asynchronously. The only difference is that synchronously executed syscalls don't need to call EnqueueReply on their own, because ExecuteCommand does it instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375)*

**Comment by leoetlino** [comment]
Review status: 44 of 45 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp, line 565 at r3](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KX0k8-U9bpWWx0uHcpm:-KX0oJD3IAV1WJXgb2rJ:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/1d492871b2b2caad2a866bc2ab8d9c5c4a2be8bf/Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp#L565)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary>
> Remove "async" from this comment. This function is used for sending replies to all syscalls, regardless of whether they get executed asynchronously. The only difference is that synchronously executed syscalls don't need to call EnqueueReply on their own, because ExecuteCommand does it instead.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375)*

**Comment by JosJuice** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375)*

**Comment by JosJuice** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp, line 565 at r3](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375#-KX0k8-U9bpWWx0uHcpm:-KX0t7X4cueZyJkmtpAH:b-k04qkt) ([raw file](https://github.com/dolphin-emu/dolphin/blob/1d492871b2b2caad2a866bc2ab8d9c5c4a2be8bf/Source/Core/Core/IPC_HLE/WII_IPC_HLE.cpp#L565)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> Done.
</details>
We discussed this further on IRC. What I said before is true from Dolphin's code's perspective, but even those syscalls that Dolphin executes synchronously are asynchronous from the PPC's perspective. So technically, the comment is correct regardless of whether it includes the word "async", but including "async" has the risk of people misunderstanding what "async" means in the same way as I did.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375)*

**Comment by JosJuice** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4375)*

**Pull request merged**
