### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by yingshaoxo**
Fix a building error

### CODE REVIEW

**Comment by mbc07** [comment]
Err, why are you adding a Linux-specific command to the Android build instructions?

**Comment by yingshaoxo** [comment]
Because I'm building under linux

Without that command, build will raise an error

**Comment by Rexogamer** [comment]
This won't work on Windows or distros that don't use apt so this would need some kind of note

**Comment by yingshaoxo** [comment]
No, for the stupid windows, if you want to do the cpp compile, you have to
install a lot of other stupid things

And by the way, even if the first line of code executed failed, when the
user execute second line, the compile will still be successful if the user
has right dependence

___

Now I'm going to close this pull, because you guys have low efficiency on
code review, and I can't endure it

**Comment by flagrama** [comment]
> CMake will inform you if a bundled library is used or if you need to install any missing packages yourself.

Is already in the readme.

**Comment by JosJuice** [comment]
> No, for the stupid windows, if you want to do the cpp compile, you have to install a lot of other stupid things

That's not true in my experience.

**Pull request closed without merging**
