### PR TITLE
Fix warnings on generic builder

### PR DESCRIPTION
**Pull request by Dentomologist**
Now that the nightly-generic builder is working it uncovered a couple warnings I haven't seen from the other builders.

The other warnings it gave are covered by #10624.

### CODE REVIEW

**Comment by shuffle2** [comment]
I don't understand the change of `break` to `continue`. but the removal of the outer `continue` and addition of `default` case seems ok...

**Comment by Dentomologist** [comment]
It's not an essential change but breaking at the end of each case, following that to the end of the switch, then seeing it continues the loop seems less clear to me than just having each case continue the loop.

**Comment by AdmiralCurtiss** [comment]
I'm not a fan of using `continue` from within a switch statement, due to the inconsistent behavior between `break` and `continue` affecting two different scopes. But whatever.

**Comment by Dentomologist** [comment]
Ok, I removed that change.

**Comment by shuffle2** [comment]
Thanks, lgtm

**Pull request merged**
