### PR TITLE
Externals: Update mbedtls to 2.28.0

### PR DESCRIPTION
**Pull request by OatmealDome**
Our current version of mbedTLS has a bug when compiled for x86_64 with newer versions of Clang (Mbed-TLS/mbedtls#4947), which causes the Wii system update code to fail on macOS with an RSA verification error.

In addition, [the 2.16.x release line of mbedTLS has now reached end-of-life](https://github.com/Mbed-TLS/mbedtls/releases/tag/v2.16.12).

Thanks to spotlight on IRC for bringing this to my attention.

### CODE REVIEW

**Comment by shuffle2** [comment]
should the min version in cmake be updated? https://github.com/dolphin-emu/dolphin/blob/master/CMake/FindMBEDTLS.cmake#L13

why not just update sources in Externals to the latest current release (which is 3.1.0)?

this diff will fix the current build of this PR (the problem is that `library` subdir needs to be in header search path, and `constant_time.c` needs to be compiled. those `third_party` things can be removed):

```diff
diff --git a/Externals/mbedtls/mbedTLS.vcxproj b/Externals/mbedtls/mbedTLS.vcxproj
index cc3d0a3ee8..5694756ea3 100644
--- a/Externals/mbedtls/mbedTLS.vcxproj
+++ b/Externals/mbedtls/mbedTLS.vcxproj
@@ -15,14 +15,12 @@
     <Import Project="$(VSPropsDir)ClDisableAllWarnings.props" />
   </ImportGroup>
   <PropertyGroup Label="UserMacros" />
+  <ItemDefinitionGroup>
+    <ClCompile>
+      <AdditionalIncludeDirectories>.\library;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
+    </ClCompile>
+  </ItemDefinitionGroup>
   <ItemGroup>
-    <ClCompile Include="3rdparty\everest\library\everest.c" />
-    <ClCompile Include="3rdparty\everest\library\Hacl_Curve25519_joined.c" />
-    <ClCompile Include="3rdparty\everest\library\Hacl_Curve25519.c" />
-    <ClCompile Include="3rdparty\everest\library\x25519.c" />
-    <ClCompile Include="3rdparty\everest\library\kremlib\FStar_UInt64_FStar_UInt32_FStar_UInt16_FStar_UInt8.c" />
-    <ClCompile Include="3rdparty\everest\library\kremlib\FStar_UInt128_extracted.c" />
-    <ClCompile Include="3rdparty\everest\library\legacy\Hacl_Curve25519.c" />
     <ClCompile Include="library\aes.c" />
     <ClCompile Include="library\aesni.c">
       <ExcludedFromBuild>true</ExcludedFromBuild>
@@ -39,9 +37,10 @@
     <ClCompile Include="library\certs.c" />
     <ClCompile Include="library\chacha20.c" />
     <ClCompile Include="library\chachapoly.c" />
-    <ClCompile Include="library\cipher.c" />
     <ClCompile Include="library\cipher_wrap.c" />
+    <ClCompile Include="library\cipher.c" />
     <ClCompile Include="library\cmac.c" />
+    <ClCompile Include="library\constant_time.c" />
     <ClCompile Include="library\ctr_drbg.c" />
     <ClCompile Include="library\debug.c" />
     <ClCompile Include="library\des.c" />
@@ -49,10 +48,10 @@
     <ClCompile Include="library\ecdh.c" />
     <ClCompile Include="library\ecdsa.c" />
     <ClCompile Include="library\ecjpake.c" />
-    <ClCompile Include="library\ecp.c" />
     <ClCompile Include="library\ecp_curves.c" />
-    <ClCompile Include="library\entropy.c" />
+    <ClCompile Include="library\ecp.c" />
     <ClCompile Include="library\entropy_poll.c" />
+    <ClCompile Include="library\entropy.c" />
     <ClCompile Include="library\error.c" />
     <ClCompile Include="library\gcm.c" />
     <ClCompile Include="library\havege.c" />
@@ -72,15 +71,15 @@
       <ExcludedFromBuild>true</ExcludedFromBuild>
     </ClCompile>
     <ClCompile Include="library\pem.c" />
-    <ClCompile Include="library\pk.c" />
     <ClCompile Include="library\pk_wrap.c" />
+    <ClCompile Include="library\pk.c" />
     <ClCompile Include="library\pkcs11.c" />
     <ClCompile Include="library\pkcs12.c" />
     <ClCompile Include="library\pkcs5.c" />
     <ClCompile Include="library\pkparse.c" />
     <ClCompile Include="library\pkwrite.c" />
-    <ClCompile Include="library\platform.c" />
     <ClCompile Include="library\platform_util.c" />
+    <ClCompile Include="library\platform.c" />
     <ClCompile Include="library\poly1305.c" />
     <ClCompile Include="library\psa_crypto_aead.c" />
     <ClCompile Include="library\psa_crypto_cipher.c" />
@@ -96,8 +95,8 @@
     <ClCompile Include="library\psa_crypto.c" />
     <ClCompile Include="library\psa_its_file.c" />
     <ClCompile Include="library\ripemd160.c" />
-    <ClCompile Include="library\rsa.c" />
     <ClCompile Include="library\rsa_internal.c" />
+    <ClCompile Include="library\rsa.c" />
     <ClCompile Include="library\sha1.c" />
     <ClCompile Include="library\sha256.c" />
     <ClCompile Include="library\sha512.c" />
@@ -112,13 +111,13 @@
     <ClCompile Include="library\ssl_tls13_keys.c" />
     <ClCompile Include="library\threading.c" />
     <ClCompile Include="library\timing.c" />
-    <ClCompile Include="library\version.c" />
     <ClCompile Include="library\version_features.c" />
-    <ClCompile Include="library\x509.c" />
+    <ClCompile Include="library\version.c" />
     <ClCompile Include="library\x509_create.c" />
     <ClCompile Include="library\x509_crl.c" />
     <ClCompile Include="library\x509_crt.c" />
     <ClCompile Include="library\x509_csr.c" />
+    <ClCompile Include="library\x509.c" />
     <ClCompile Include="library\x509write_crt.c" />
     <ClCompile Include="library\x509write_csr.c" />
     <ClCompile Include="library\xtea.c" />
```

**Comment by OatmealDome** [comment]
@shuffle2

Thanks for helping me fix the Windows build!

> should the min version in cmake be updated?

Yeah, probably a good idea. Updated.

> why not just update sources in Externals to the latest current release (which is 3.1.0)?

[mbedTLS 3.x.x has API breaking changes](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/3.0-migration-guide.md). The 2.x.x release line is still being maintained (2.28.0 is an LTS release with support up to 2024), so I went with that as the path of least resistance.

**Comment by shuffle2** [comment]
cool, lgtm

**Comment by OatmealDome** [comment]
@AdmiralCurtiss I assume it's because my branch hasn't been rebased on top of master for a while.

**Review by AdmiralCurtiss — APPROVED** [review]
Simple version update that fixes a known problem, seems fine to me.

**Review by lioncash — APPROVED** [review]

**Comment by cristian64** [comment]
It seems the [`scripts`](https://github.com/Mbed-TLS/mbedtls/tree/v2.28.0/scripts) directory is now missing.

Dolphin prints the following errors at configuration:

```
-- Performing Test MBEDTLS_VERSION_OK
-- Performing Test MBEDTLS_VERSION_OK - Failed
-- Could NOT find MBEDTLS (missing: MBEDTLS_INCLUDE_DIR MBEDTLS_LIBRARY MBEDX509_LIBRARY MBEDCRYPTO_LIBRARY MBEDTLS_VERSION_OK) 
-- Using static mbed TLS from Externals
-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter 
/usr/bin/python3.8: can't open file '/tmp/dolphin/Externals/mbedtls/scripts/config.py': [Errno 2] No such file or directory
/usr/bin/python3.8: can't open file '/tmp/dolphin/Externals/mbedtls/scripts/config.py': [Errno 2] No such file or directory
-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS
-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS - Success
/usr/bin/python3.8: can't open file '/tmp/dolphin/Externals/mbedtls/3rdparty/../scripts/config.py': [Errno 2] No such file or directory
```

The errors do not to stop the build process, apparently, and copying the directory from the official repository into Dolphin's externals directory prevents the errors.

From the CMake file, it seems these Python scripts are used for verifying configuration. See https://github.com/Mbed-TLS/mbedtls/blob/v2.28.0/CMakeLists.txt#L87-L129. I don't see any reference to the `scripts` directory in this PR; unsure if it was omitted intentionally.

**Comment by shuffle2** [comment]
I guess the linux buildbot uses system mbedtls, so it wasn't caught?

**Comment by cristian64** [comment]
For reference, `scripts/config.py` was added as part of #10579. (Thanks!)

**Pull request merged**
