### PR TITLE
GCMemcardDirectory: Save memory card header

### PR DESCRIPTION
**Pull request by spycrab**
Should fix the issue of not being able to save GCI files after loading a save state.

### CODE REVIEW

**Comment by spycrab** [comment]
@LPFaint99 Any reason you disabled saving in the first place?

**Comment by JMC47** [comment]
A lot of popular games have this issue.  From Rogue Squadron, to Wind Waker, to Mario Sunshine, to Mario Tennis.

The key is savestating, closing the emulator, opening the emulator, and loading the game, then loading the state.

**Comment by LPFaint99** [comment]
@JMC47 Just tried to reproduce with Mario Sunshine on https://dolphin-emu.org/download/dev/07e0b9c0d2218f7756aab8f8f1041cccc4937856/

seems to work fine for me?

**Comment by JMC47** [comment]
Yeah, forgot about that part, sorry :(

**Comment by LPFaint99** [comment]
off the cuff fix/direction that I'd propose https://github.com/LPFaint99/dolphin/commit/a5c6e5ce320ae28203b6aa888c22fab67ddebd32

needs more testing, especially with normal memorycards

**Comment by spycrab** [comment]
Will probably just create a PR featuring LPFaint's solution at some point if he himself doesn't.

**Pull request closed without merging**
