### PR TITLE
[RFC] OpenAL removal

### PR DESCRIPTION
**Pull request by Ebola16**
Removes OpenAL, OpenAL externals, and CheckNeedForLatencyControl().

### CODE REVIEW

**Comment by Helios747** [comment]
So, this is my screw up. I'm sorry. We didn't remove OpenAL. So what you're doing is... Removing it.

Which, I don't really care about, but just throwing that out there.

**Comment by Ebola16** [comment]
I've never used OpenAL. Does it offer any advantage over the other backends? I also don't see it as an audio backend option on Windows.

**Comment by mbc07** [comment]
Okay, I didn't  check for a while but Dolby Surround decoding used to be available only in OpenAL. If that's still the case nowadays, I think it's worth keeping this backend until Cubeb reaches feature-parity. Otherwise, LGTM

**Comment by LAGonauta** [comment]
OpenAL is currently used only in Windows, and is shown in the GUI only when any OpenAL backend is installed (OpenAL Soft, Creative OpenAL, Rapture3D). Useful for HRTF with the Surround Decoder when the internal sound device has no HRTF in its driver, and for using hardware OpenAL with a X-Fi card (really low latencies).

Actually, OpenAL is not needed for surround sound anymore. Cubeb can use it, and XAudio2 if my PR #6171 is merged.

I vote on fixing and keeping it as I use it, but I might be one in a million...

**Comment by Ebola16** [comment]
Removed OpenAL headers from externals too.

I did some digging and I think the source of cmake's OpenAL complaints is #5691
Also, I found more details about @LAGonauta's reasoning for keeping OpenAL in #5256

Is Cubeb able to support HRTF (even if Dolphin currently can't use it)? Apparently HRTF currently works best with DSPLLE which is a performance hit. And could Cubeb be used with X-Fi for the same low latency in the future?

If we went the fixing OpenAL route instead, is there a way to dynamically load openal32.dll without triggering a fatal_error in cmake when the dll doesn't exist?

**Comment by LAGonauta** [comment]
I believe Cubeb has no internal HRTF, at least not yet. On Linux one can simply use the PulseAudio backend and a VirtualSurround sink module, but I believe the only clean and free way to do that on Windows is OpenAL Soft. There are some alternatives such as Razer Surround, but on my computer they introduce even more latency than OpenAL Soft.

Yes, currently the surround information is only generated with DSPLLE as there is currently no surround ENcoder in HLE (but I believe that if surround is ever implemented in HLE it won't go through encoding/decoding 5.1 --> DPLII encoder --> DPLII decoder --> 5.1 output).

**Comment by Ebola16** [comment]
I was able to change `FATAL_ERROR` to `STATUS` with no problems. I split the fix for https://bugs.dolphin-emu.org/issues/10924 into #6419.

If anyone thinks they'll be interested in making HRTF compatible with DSPHLE, they can close this PR. That would be something that only OpenAL can currently do. However, if there is no interest in this, a DSPLLE-only feature isn't really justification to keep this backend around IMO.

Is the X-Fi latency reduction alone significant enough to justify having OpenAL?

**Comment by LAGonauta** [comment]
Just tested on Rockband 2 audio calibration with my mouse click as a button on windows 8.1 and HLE.
With Cubeb the average audio latency was ~63ms, with XAudio2 ~67ms, with OpenAL Soft ~75ms (v1.18.2, latency setting set to 20 ms), while it was ~24ms with OpenAL (Creative X-Fi, latency setting set to 10ms).
Also, with the new to-be-merged WASAPI Exclusive mode the average latency was 24ms with 10ms set as audio latency.

So I guess we can say OpenAL latency with a Creative X-Fi is equivalent to WASAPI Exclusive mode latency, without the need to be have exclusivity of the device and maybe allowing HRTF effect (I do not know if the HRTF software is disable when using exclusive mode on software-based solutions such as Razer Surround).

**Comment by Ebola16** [comment]
I think we can revisit removing OpenAL once an audio backend can use positional audio data with DSPHLE.

**Pull request closed without merging**
