### PR TITLE
msvc: use buildcache [dont merge]

### PR DESCRIPTION
**Pull request by shuffle2**
https://github.com/shuffle2/buildcache/commits/msvc-direct
[dont merge]: still experimenting, but the branch is available for people to try locally.

This introduces a tool like ccache, which wraps execution of `cl.exe` and provides cached `.obj` and `.pch` responses. The hope is that this can speed up buildbot compile times, but it should help local dev machines as well. Note the current windows buildbot is cpu-bound, and buildcache only provides a speedup for the case where git branch switches are causing build outputs to be invalidated.

After some non-exhaustive testing, it seems to bring pr-win-dbg-x64 compile time down from 500 seconds to 110 seconds. But the difference in real life usage may not be that drastic. Locally I do see higher speedup, so YMMV.

For now, I've hacked it into the buildbot to try and get a better idea of the perf impact. I'll try to keep an eye on it.

Since it just wraps `cl.exe`, it should be compatible with both msbuild and cmake/ninja (however the cmake config has a ways to go in terms of feature/perf parity with current msbuild config - it should be possible to do, though).

### CODE REVIEW

**Comment by shuffle2** [comment]
@dolphin-emu-bot rebuild

**Comment by shuffle2** [comment]
@dolphin-emu-bot rebuild

**Comment by orbea** [comment]
It doesn't seem nice to add a binary .exe file to the git history when it only benefits one platform. Especially given there are no such other files currently in the Tools directory.

**Comment by shuffle2** [comment]
I don't think there's a good alternative

**Comment by orbea** [comment]
Windows already uses submodules, you could extend that. As long as submodules remain only for windows it will not burden other platforms.

**Comment by shuffle2** [comment]
How is it a burden for other platforms???

**Comment by orbea** [comment]
Because git is far less than ideal with binary files and adding random .exe files is a terrible precedent. If one gets added then arguing that more should not be added further down the line becomes harder.

1.65 MB may not seem to be that much, but it quickly adds up with repeated clones. Especially for remote areas with poor internet connections.

**Comment by shuffle2** [comment]
I agree in principle, however dolphin set this precedent from the initial commit. There are currently binary files in the repo, and there have been many more in the past.

**Comment by orbea** [comment]
> There are currently binary files in the repo

I see what you mean...
```
$ find . -type f -not -path "./.git*" ! -size 0 -exec grep -IL . "{}" \; | grep -v '.png'
./Installer/Dolphin.ico
./Installer/dxredist/APR2007_xinput_x64.cab
./Installer/dxredist/APR2007_xinput_x86.cab
./Installer/dxredist/DSETUP.dll
./Installer/dxredist/DXSETUP.exe
./Installer/dxredist/dsetup32.dll
./Installer/dxredist/dxupdate.cab
./Installer/vcredist/vc_redist.x64.exe
./Data/Sys/GC/dsp_coef.bin
./Data/Sys/GC/dsp_rom.bin
./Data/Sys/GC/font_japanese.bin
./Data/Sys/GC/font_western.bin
./Data/Sys/Wii/shared2/wc24/mbox/wc24recv.ctl
./Data/Sys/Wii/shared2/wc24/mbox/wc24recv.mbx
./Data/Sys/Wii/shared2/wc24/mbox/wc24send.ctl
./Data/Sys/Wii/shared2/wc24/mbox/wc24send.mbx
./Data/Sys/Wii/shared2/wc24/misc.bin
./Data/Sys/Wii/shared2/wc24/nwc24dl.bin
./Data/Sys/Wii/shared2/wc24/nwc24fl.bin
./Data/Sys/Wii/shared2/wc24/nwc24fls.bin
./Data/Sys/Wii/shared2/wc24/nwc24msg.cbk
./Data/Sys/Wii/shared2/wc24/nwc24msg.cfg
./Data/Sys/totaldb.dsy
./Data/Sys/codehandler.bin
./Data/Dolphin.icns
./Externals/gettext/libgettextlib.dll
./Externals/gettext/libgettextsrc.dll
./Externals/gettext/libiconv2.dll
./Externals/gettext/libintl3.dll
./Externals/gettext/msgfmt.exe
./Externals/MoltenVK/libvulkan.dylib
./Externals/ffmpeg/lib/avcodec.lib
./Externals/ffmpeg/lib/avformat.lib
./Externals/ffmpeg/lib/avutil.lib
./Externals/ffmpeg/lib/swresample.lib
./Externals/ffmpeg/lib/swscale.lib
./Source/Android/gradle/wrapper/gradle-wrapper.jar
./docs/WiiMote/HID_SPEC_V10.rar
./docs/WiiMote/Dumps/WiiMote_AttribTree_0x10000.bin
./docs/WiiMote/Dumps/WiiMote_AttribTree_0x10000_strip.bin
./docs/WiiMote/Dumps/WiiMote_AttribTree_0x10001.bin
./docs/WiiMote/Dumps/WiiMote_AttribTree_0x10001_strip.bin
./docs/WiiMote/Dumps/WiiMote_ServiceScan.bin
```
Its unfortunate it got to this point.

**Pull request closed without merging**
