### PR TITLE
Require frontend to initialize controllers

### PR DESCRIPTION
**Pull request by JosJuice**
We currently have two different code paths for initializing controllers: Either the frontend (DolphinQt) can do it, or if the frontend doesn't do it, the core will do it automatically when booting. Having these two paths has caused problems in the past due to only one frontend being tested (see PR #9086). I would like to get rid of the latter path to avoid further problems like this.

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
I think nogui never deinitializes controllers so it now crashes on program termination because some parts of that are still running. At least I'm getting a failure in some `std::thread` destructor on Windows.

**Comment by AdmiralCurtiss** [comment]
Yeah, adding a call to `UICommon::ShutdownControllers();` before `UICommon::Shutdown();` fixes it, but only if `BootManager::BootCore()` succeeds. Can you put the shutdown stuff in nogui in a ScopeGuard?

**Comment by JosJuice** [comment]
I've marked this as a draft for now because of the FifoCI failures. Neither I or AdmiralCurtiss can reproduce the problem on Windows, so if there's someone who could try to reproduce this on Linux (maybe headless is needed?), that would be appreciated. Alternatively, if there's some way to get logs from FifoCI that I'm not aware of...

**Comment by AdmiralCurtiss** [comment]
FifoCI logs are at eg. https://dolphin.ci/#/builders/16/builds/7127/steps/7/logs/stdio but it doesn't really help here, it just says segmentation fault.

**Comment by JosJuice** [comment]
[FifoCI is no longer reporting any failures.](https://fifo.ci/version/dabad822193f23bd01c13c4d0798f0a507e910eb/) Well, I'm not quite sure what happened, but since there seem to be no problems right now and I don't know of anything that's wrong in the code, I'll unmark this as a draft.

**Comment by golivax** [comment]
Hi. Sorry to hijack this PR. However, I believe I have information that might be useful to you folks. This PR broke Dolphin on Android using Real WiiMotes and a DolphinBar. Steps to reproduce:

- Install Dolphin 5.0.16940
- Go to Settings - Wii Input - Wii Remote 1
- Change from Emulated to Real Wii Remote
- Go to Config - Wii 
- Enable Wii Remote Continuous Scanning
- Enable Wii Remote Speaker
- Go to game selection screen and confirm that INI file has been updated
- Close Dolphin
- Try to open Dolphin

Dolphin will try to launch, but will crash immediately. Phone is a Galaxy S10 with Snapdragon CPU running Android 12. Logs [here](https://www.dropbox.com/s/1fmeowdnhm4nn6b/dolphin.log?dl=0)

**Comment by JosJuice** [comment]
Thanks for quickly noticing and reporting this! Since you've already created a report on the issue tracker, let's continue the conversation there: https://bugs.dolphin-emu.org/issues/12980

**Pull request merged**
