### PR TITLE
Qt: Implement Wiimote pane

### PR DESCRIPTION
**Pull request by spycrab**
Rebased and updated based on #5804.
Screenshot

### CODE REVIEW

**Comment by spycrab** [comment]
@dolphin-emu-bot rebuild

**Comment by spycrab** [comment]
Any comments?

**Comment by container1234** [comment]
Misc Settings and Wii Remote Settings won't be changeable after emulation is stopped.

**Comment by JMC47** [comment]
lol, that happens after Netplay on WX as well.

**Comment by MayImilae** [comment]
Can you give us new images please?

**Comment by spycrab** [comment]
@container1234 Fixed.
@MayImilae Added a screenshot. See above.

**Comment by MayImilae** [comment]
Looks good!

**Pull request merged**
