### PR TITLE
[Config UI] add "normal speed" to speed limit 100%

### PR DESCRIPTION
**Pull request by aserna3**
@MaJoRoesch asked for this.

image

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3690)

### CODE REVIEW

**Comment by aserna3** [comment]
done

**Comment by JosJuice** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/DolphinWX/Config/GeneralConfigPane.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3690#-KBlFk-zPTp7pMMGR54f:-KBlFk0-rAN1uINfDyGA:-1110114736) ([raw file](https://github.com/dolphin-emu/dolphin/blob/0d87ba2242fac599fd4a4ec083c6c7d94698484e/Source/Core/DolphinWX/Config/GeneralConfigPane.cpp#L46)):*
This string needs to be translatable.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3690)*

**Comment by pauldacheez** [comment]
Surprisingly, I'm _100%_ fine with this. MingLee

**Comment by Twilit-Soul** [comment]
Paul, that joke is one of the few things I understand in these e-mails.

**Comment by aserna3** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/DolphinWX/Config/GeneralConfigPane.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3690#-KBlFk-zPTp7pMMGR54f:-KBv1HuhEAKDZlfdyb4N:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/0d87ba2242fac599fd4a4ec083c6c7d94698484e/Source/Core/DolphinWX/Config/GeneralConfigPane.cpp#L46)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3690)*

**Comment by BhaaLseN** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/DolphinWX/Config/GeneralConfigPane.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3690#-KBlFk-zPTp7pMMGR54f:-KBxN1XShi_Lvea2JlXW:-39710390) ([raw file](https://github.com/dolphin-emu/dolphin/blob/0d87ba2242fac599fd4a4ec083c6c7d94698484e/Source/Core/DolphinWX/Config/GeneralConfigPane.cpp#L46)):*
Errr...that's not what I meant. Translating `"%i%%"` doesn't make much sense (to me at least), and for the 100% case I'd simply have used `_("100% (Normal Speed)")` (with the 100% spelled out rather than formatted in, since its always 100).
This, however, lets the translator remove the "100%" figure if they wanted to. Not sure if we want to force that for "Normal Speed".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3690)*

**Comment by JosJuice** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/DolphinWX/Config/GeneralConfigPane.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3690#-KBlFk-zPTp7pMMGR54f:-KBxPRtLytZWT9jLIFFg:-1211938981) ([raw file](https://github.com/dolphin-emu/dolphin/blob/0d87ba2242fac599fd4a4ec083c6c7d94698484e/Source/Core/DolphinWX/Config/GeneralConfigPane.cpp#L46)):*
For correctness, some languages are supposed to have a space before the %. Having "%i%%" translatable is worthwhile in my opinion.

I think I prefer "%i%% (Normal Speed)" over "100% (Normal Speed)" so that the two strings are consistent. If they aren't, a translator who understands "100%" but not "%i%%" might place a space in one string and not the other. This isn't particularly important though, because a consistency problem like that should be easy to notice by just looking through Dolphin's GUI.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3690)*

**Comment by BhaaLseN** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/DolphinWX/Config/GeneralConfigPane.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3690#-KBlFk-zPTp7pMMGR54f:-KBxQPFYG9KRyeRdg0bC:-1265168165) ([raw file](https://github.com/dolphin-emu/dolphin/blob/0d87ba2242fac599fd4a4ec083c6c7d94698484e/Source/Core/DolphinWX/Config/GeneralConfigPane.cpp#L46)):*
To me, thats screaming format-string-errors all over the place, but I suppose you do have a point too. That being said, I'm fine with either solution.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3690)*

**Pull request merged**
