### PR TITLE
DolphinQt: Query mapping indicator colors using QPalette for better behavior with alternative themes.

### PR DESCRIPTION
**Pull request by jordan-woyak**
Inspired by @8times9's PR #7789.

Look is mostly unchanged on my typical "light" theme.

Users of "dark" themes should please test.

### CODE REVIEW

**Comment by 8times9** [comment]
Tested on Windows, doesn't seem to be working?
windows

I'll test on macOS as soon as the buildbot comes back online

**Comment by jordan-woyak** [comment]
@8times9 I'll have to read deeper into Qt's documentation. QApplication::palette is apparently not working how I'd expect.

**Comment by jordan-woyak** [comment]
@8times9 please try my recent change.

**Comment by 8times9** [comment]
Looks much better!
1a747793-7349-495f-9c2c-efb4ba9f1cb6 png
d9a331ac-5a8a-49b8-9a69-4036832359d9 png

**Comment by jordan-woyak** [comment]
@8times9 Thanks for testing.

**Comment by 8times9** [comment]
> I'll test on macOS as soon as the buildbot comes back online

Do you have any idea when the Mac buildbot will be working again? It’s been a long time

**Comment by chargeflux** [comment]
Assuming Dark Mode for Dolphin is only triggered when macOS Mojave is set to Dark Mode (saw no options in the Interface tab), this is how the controller screen looks:
mojave dark mode

**Comment by chargeflux** [comment]
Assuming Dark Mode for Dolphin is only triggered when Dark Mode on macOS Mojave is enabled (saw no option to turn it on manually in Interface config), this is how the Controller screen looks mojave dark mode

**Comment by jordan-woyak** [comment]
I guess that's what it should look like in "dark mode".. At least it matches everything else..?

**Comment by riking** [comment]
Lightening the main stick and darkening the c stick on that Mojave theme seems appropriate. Perhaps some color math is in order?

**Comment by jordan-woyak** [comment]
@riking I can do that, but dark yellow is usually pretty nasty looking.

**Comment by chargeflux** [comment]
@jordan-woyak FWIW, I like the yellow color for the c stick.

**Comment by 8times9** [comment]
Is the yellow even necessary for the C-stick indicator? The title of that column and being to the right of the other joystick already show it’s the C-stick well enough. 

The yellow seems a bit overly skeuomorphic to me, plus it doesn’t match anywhere else in the Dolphin UI color scheme. ¯\\\_(ツ)_/¯

**Pull request merged**
