### PR TITLE
Add Wii Mini system menu version detection

### PR DESCRIPTION
**Pull request by Fullmetal5**

### CODE REVIEW

**Comment by JosJuice** [comment]
4608 is equal to `4096 & 512` (bitwise AND). What do you think about changing `switch (title_version & ~0xf)` to `switch (title_version & 0xff0)` instead of adding an extra case?

**Comment by Fullmetal5** [comment]
Yeah, that seems fine however, do you think the mini's system menu should be distinguishable from regular one? Like M4.3U to indicate Mini or should it just be left alone.

**Comment by JosJuice** [comment]
I think it's fine to leave it alone. But if we do want to have an indicator, I think adding something like `(Wii Mini)` at the end would be the best way to go. The meaning of just an M isn't super obvious.

**Comment by CookiePLMonster** [comment]
Since effectively those three commits now change a single line only, I guess it makes sense to squash it and rewrite the commit message to be more accurate.

**Comment by Fullmetal5** [comment]
Sorry about the wait, should be good now.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
