### PR TITLE
Qt: Don't force a minimum size for the main window

### PR DESCRIPTION
**Pull request by Starsam80**

### CODE REVIEW

**Comment by MayImilae** [comment]
Can you post a few images of extremes please?

**Comment by Starsam80** [comment]
Smallest: 
image

At least it's still functional: 
image

It works the best with the logging PR and its docking windows: image

Compared to before (just look at how tall that window is, it almost doesn't fit on my screen and that's the *smallest* size): 
image

**Comment by MayImilae** [comment]
Oh, just to be clear, on first run for a new user, it doesn't start at minimum size, right?

**Comment by Starsam80** [comment]
@MayImilae That is correct.

**Pull request merged**
