### PR TITLE
Update cheats for GALE01r2.ini

### PR DESCRIPTION
**Pull request by jefflongo**
Completely rewritten Global Melee Netplay Settings.  The individual codes can be found here (http://pastebin.com/38CFazXq).  The previous Global Melee Netplay Settings have some issues such as not being able to change the random stage select, various crashes in 1P mode, friendly fire being off by default, and a general lack of new features due to its age.

### CODE REVIEW

**Comment by bb010g** [comment]
Is there a SmashBoards thread for this? Any changes to the netplay codes should be discussed there and approved by the community before merge. Personally, just the code list LGTM.

**Comment by jefflongo** [comment]
I made a thread so I can get some input from others http://smashboards.com/threads/new-global-melee-netplay-settings.409703/

**Comment by jefflongo** [comment]
This should be ready to go now.  I have tested it myself for about an hour and everything seems to be working as expected, would really appreciate if anybody else tested as well.  

I polled the community and got 150+ unique responses, with the majority supporting individually every added code.  For the list of codes added + results of poll you can view this thread: http://smashboards.com/threads/409703

Anyways, should be ready to merge, but would appreciate if somebody else tested just to confirm with me.

**Comment by mirrorbender** [comment]
could I add some updated widescreen codes to this PR?  With the recent corrections to how dolphin handles aspect ratios, the codes need to be altered slightly.  The 4:3 code is no longer needed, and the widescreen code should now be:

C2021ABC 00000002
39C00001 38600006
60000000 00000000
C236A4A8 00000007
C03F0034 2C0E0001
41820024 3C004080
90010030 3C004040
90010034 C0010030
EC210032 C0010034
EC210024 39C00000
281E0000 00000000

**Comment by jefflongo** [comment]
Done. Once again good to go.

**Comment by JMC47** [comment]
@dolphin-emu-bot rebuild

**Comment by JMC47** [comment]
lgtm.  Anyone ready to merge?

**Pull request merged**
