### PR TITLE
PowerPC: cosmetic changes

### PR DESCRIPTION
**Pull request by Tilka**
Most of these commits are probably best looked at with `--word-diff-regex=.` On GitHub you can generate `-w` diffs by adding `?w=1` to the URL.

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Not sure about the ```_ARCH_64``` change in JitBase, maybe ping @Sonicadvance1 about that. Otherwise, lgtm.

**Comment by Tilka** [comment]
`LogGeneratedX86()` is not used on ARM.

**Comment by lioncash** [comment]
Looks fine to me

**Comment by degasus** [comment]
But LogGeneratedX86 should be in Jit64Common instead :/

**Comment by Tilka** [comment]
@degasus I'd rather move everything around in one go when we figure out a better way to organize PowerPC/*

**Pull request merged**
