### PR TITLE
Android: some minor changes

### PR DESCRIPTION
**Pull request by weihuoya**
- don't mark setting changed with same setting value
- MSAA default is 1 in cpp code
- discard setting with empty setting value
- remove margin in setting activity
- remove no used ApplicationTest.java

### CODE REVIEW

**Comment by JMC47** [comment]
@dolphin-emu-bot rebuild

@zackhow plz review

**Comment by weihuoya** [comment]
default MSAA is 1 and it mean turn off MSAA, but for Anisotropy 1 mean `2x`.
https://github.com/dolphin-emu/dolphin/blob/3627ef8a0489765eb10ab29a7988866b52493239/Source/Core/Core/Config/GraphicsSettings.cpp#L61

**Comment by weihuoya** [comment]
fix MSAA values in `arrays.xml`

**Comment by weihuoya** [comment]
MSAA values are `1, 2, 4, 8` not `0, 1, 2, 3`.

**Comment by Helios747** [comment]
Thank you for this.

In the future, please try to keep PRs to fixing or implementing one thing (Or similar things)

When PRs do several different things especially in one commit, it gets harder to review. Fortunately this PR was pretty small so the review wasn't that much harder. But just to know for the future.

**Pull request merged**
