### PR TITLE
Add a hotkey for toggling texture dumps

### PR DESCRIPTION
**Pull request by slashiee**
This adds a hotkey that toggles the dump textures option. I was not able to find any other spot that would fit for where the toggle would be.

### CODE REVIEW

**Comment by leoetlino** [comment]
@dolphin-emu-bot rebuild

**Comment by GitToTheHub** [comment]
Can you add a hotkey for toggling the graphics option "Show FPS"?

**Comment by JosJuice** [comment]
@GitToTheHub This isn't a forum for feature requests.

**Comment by GitToTheHub** [comment]
Sorry, i thought it would be a small change and would be in line with that

**Comment by Helios747** [comment]
LGTM. Can somebody test this? I'm at work.

**Pull request merged**
