### PR TITLE
Add Metal as backend option with Vulkan Disabled

### PR DESCRIPTION
**Pull request by Hibyehello**
Current implementation requires vulkan to be enabled to have the metal backend as an option.

### CODE REVIEW

**Comment by dvessel** [comment]
Thanks, it’s working on my end.

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Review by Pokechu22 — APPROVED** [review]
Untested, but looks good to me.

**Comment by mbc07** [comment]
Also, does Vulkan needs to take precedence on macOS now that we have a native Metal backend?

**Comment by Pokechu22** [comment]
I'm pretty sure that OpenGL needs to not be the default on macOS still, but I don't know whether it'd be better to have Vulkan or Metal be the default.

**Comment by mbc07** [comment]
I was talking about making Metal the default on macOS. While MoltenVK is great, it just seems logical to me to default to the native Metal API now that we have a backend for it...

**Comment by PEmu2** [comment]
I believe the decision in the original Metal PR was to leave Vulkan as default until the Metal backend matures: https://github.com/dolphin-emu/dolphin/pull/10754#discussion_r918327999

For what it's worth there's still an unmerged PR of Metal backed fixes in #11028.

**Comment by pizuz** [comment]
> I was talking about making Metal the default on macOS. While MoltenVK is great, it just seems logical to me to default to the native Metal API now that we have a backend for it...

+1

Dolphin requires macOS Mojave and later, which in turn requires a Metal-compatible video adapter.

Yes, there are ways to make a Mac run unsupported macOS versions (I‘m currently running Monterey via OCLP on my Late 2013 iMac and it works like a charm), but at least the officially supported Macs should run the Metal backend out of the box. Users running patched macOS versions should know what they are doing and switch to OpenGL.

**Comment by Hibyehello** [comment]
I almost considered making metal take precedence, but then I remembered that it was decided to keep vulkan as default for now.

**Pull request merged**
