### PR TITLE
Use the C locale for non-Windows CharArrayFromFormatV() and StringFromFormat()

### PR DESCRIPTION
**Pull request by randomstuff**
The Windows implementations of `CharArrayFromFormatV()` and `StringFromFormat()` use the `"C"`/`".1252"` locale instead of the user locale (using `_vsnprintf_l`). On non-Windows, the user locale was used.

This leads to bugs on non-Windows: the Overclock parameter was serialised with the user locale (`0,279322` in some locale) and was interpreted back as `0` (because the `"C"` locale is used for parsing the string).

Make non-Windows `CharArrayFromFormatV()` and `StringFromFormat()` consistent with their Windows counterpart.

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Hmm, shouldn't we consistently use the C locale everywhere, for everything? User locale is always bound to make problems when inter-opping, or when assuming something/nothing about the values and their representation.

**Comment by randomstuff** [comment]
The non-C locale is used (and setup) by the GUI toolkit (wxWidgets via [wxLocale](http://docs.wxwidgets.org/trunk/classwx_locale.html#a37c254f20d4862b6efea2fedf63a231a)) in order to handle localisation.

**Comment by Armada651** [comment]
@dolphin-emu-bot rebuild

The code looks good to me.

**Comment by randomstuff** [comment]
`uselocale` and friends are available in Android API 21. Since it is build with `android:minSdkVersion="18"`, I guess I should use the old code (without `locale_t`) for Android.

**Comment by Armada651** [comment]
@randomstuff IIRC uselocale() in the NDK doesn't do anything, as far as I know Android always assumes C locale.

**Comment by Armada651** [comment]
@dolphin-emu-bot rebuild

**Comment by randomstuff** [comment]
Yes, recent version of bionic have locale management fucntions but [they only support "C" vs "C.UTF-8"](https://github.com/android/platform_bionic/blob/75ef63d6cf83787233d1c45489c4ec03b0a67d16/libc/bionic/locale.cpp#L142) (the default).

**Comment by Mullin** [comment]
LGTM

**Comment by randomstuff** [comment]
This bug is stil on master. Can this be merged or should another fix be used ?

**Comment by degasus** [comment]
I'm for merging as it is.

**Comment by tapcio** [comment]
This was reverted ? I get problem with saving CPU Override in r6963 on Windows.

**Comment by randomstuff** [comment]
@tapcio: This specific patch does not change the behaviour on Windows. I think, it was supposed to have been fixed on Windows.

**Comment by tapcio** [comment]
It's not fixed on Windows.
My Windows is set to Polish locale and it saves coma instead of dot when saving CPU Override to ini.. Then when I re-run Dolphin CPU Override is set to 0%, so then cannot run game - I need to uncheck option. This issue is really even more annoying when you want to enable CPU Override, because it is always 0 and slider is disabled (grayed out) when option is disabled so enabling it causes game freeze (ie. sets slider value - 0% ...).

**Comment by BhaaLseN** [comment]
Can you please create an issue on our issue tracker, instead of posting on a closed PR? This would help us more in keeping track of issues that are still present.

**Comment by tapcio** [comment]
Hym, there already is: https://code.google.com/p/dolphin-emu/issues/detail?id=8095

**Pull request merged**
