### PR TITLE
CMake: Generate scmrev.h at build time instead of configure time.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
This avoids the reconfigure every time your git HEAD changes. It should also detect the `-dirty` suffix more reliably.

### CODE REVIEW

**Comment by TellowKrinkle** [comment]
I feel like the proper way to do this would be with an `add_custom_command(OUTPUT scmrev.h DEPENDS git files)`, which you then `target_sources` into common, so it would have proper dependency tracking and you wouldn't need the copy_if_different to avoid recompiling files for every build.

**Comment by AdmiralCurtiss** [comment]
I understand what you mean conceptually but I have no idea how that would actually look in practice. You can't exactly put a dependency on the entire `.git` directory.

**Comment by AdmiralCurtiss** [comment]
(Note that that wouldn't detect the `-dirty` flag correctly either even if you did somehow manage a dependency on everything in `.git`.)

**Comment by iwubcode** [comment]
Might not be related, but my PR build fails with:

> ../Source/Core/Common/Version.cpp:8:10: fatal error: Common/scmrev.h: No such file or directory
    8 | #include "Common/scmrev.h"

Just coincidence?

**Comment by TellowKrinkle** [comment]
> You can't exactly put a dependency on the entire .git directory.

Same two files the current script uses to decide whether to rerun cmake

> (Note that that wouldn't detect the `-dirty` flag correctly either even if you did somehow manage a dependency on everything in `.git`.)

True, I guess this is fine then.

Could you find git with `QUIET` or pass it in as an argument to the script so it doesn't print this on every build?
```
-- Found Git: /usr/bin/git (found version "2.39.2 (Apple Git-143)") 
```

**Comment by AdmiralCurtiss** [comment]
> I don't understand why this build would taint other PRs but my PR build fails with:

I mean... I agree that this feels related, but I'm not really sure why this would cause this, either. Odd.

> Could you find git with `QUIET` or pass it in as an argument to the script so it doesn't print this on every build?

Yup, I've added the git executable path to the passed parameters.

**Review by TellowKrinkle — APPROVED** [review]

**Pull request merged**
