### PR TITLE
Fix focus bug when using the "render to main window" feature

### PR DESCRIPTION
**Pull request by clinchergt**
~~This basically reverts this PR https://github.com/dolphin-emu/dolphin/pull/1118~~

Fixes this issue: https://bugs.dolphin-emu.org/issues/9703

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4030)

### CODE REVIEW

**Comment by Parlane** [comment]
@lioncash Have a look at this and give your thoughts. I'm perfectly okay with reverting the old change until someone has an idea of how to fix further.

But @clinchergt you should add a comment to the WIN32 case explaining why the win32 case is needed,

**Comment by Parlane** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4030)*

**Comment by EmptyChaos** [comment]
FYI, there's an API for this in wxWidgets: `wxPanel::SetFocusIgnoringChildren`. Unfortunately, it requires recovering m_RenderParent's type.
```cpp
if (auto panel = wxDynamicCast(m_RenderParent, wxPanel))
  panel->SetFocusIgnoringChildren();
else
  m_RenderParent->SetFocus();
```
wxWidgets implements tab navigation itself so presumably this would be broken on all platforms?

**Comment by clinchergt** [comment]
That worked well. Thanks, @EmptyChaos 
The issue does not occur on this branch on Windows and Linux functionality was not affected. I can't really test OSX

**Comment by Helios747** [comment]
LGTM.

**Comment by MaJoRoesch** [comment]
I wasn't able to reproduce the bug on macOS. But I tested the PR and it still worked, so, I guess that's as good as macOS testing can get!

**Pull request merged**
