### PR TITLE
Move a significant amount of video backend logic to VideoCommon

### PR DESCRIPTION
**Pull request by stenzek**
**Huge scary pull request ahead!**

This pull request moves a decent amount of logic from the video backends to VideoCommon. It's something I've been putting off for a while now, but finally found the motivation/time to do.

In addition to the maintainability improvements, as all backends are now considered equal, it adds things like:
- Post-processing to D3D
- GPU texture decoding to D3D
- Vulkan-style EFB cache to D3D and OpenGL
- Vulkan-style EFB poke batching to D3D and OpenGL

Some things makes easier in the future:
- Better state tracking in OpenGL -> performance improvements (since all state is now controlled via pipelines, we know what it is, and it hasn't been changed by random functions)
- Post-processing of XFB copies, rather than just the scanout (something I started a long time ago but was put off because of how much duplication there was in backends)
- Multi-threading of the backends
- Who doesn't like fewer lines of code for the same functionality
- Re-implementing D3D12? :) (if we can keep it to 5k lines of code or so, in line with the other backends)

Unfortunately, due to it being backend-specific, it does remove the **stencil buffer bounding box emulation**. I figured now that we have Vulkan/Metal on macOS, this removes one of the main uses for it.

I'm sorry for the size of this PR, but with most of the changes touching the same code, if I separated it, I'd be writing a lot of code just to throw it out again. I started doing that, but it got old quick :(

A rough work list:
- [x] Use abstract textures for EFB emulation
- [x] Move FramebufferManager to common and create implementation using abstract classes
- [x] Move TextureCache functionality to common (EFB copies, palette texture conversion)
- [x] Remove a lot of duplicated logic in Vulkan (largest backend by far...)
- [x] Re-implement GPU texture decoding
- [x] Implement texel buffers on OpenGL and Vulkan (for palette texture conversion)

### CODE REVIEW

**Comment by JMC47** [comment]
Fixes Brawl/Panel De Pon on D3D. https://bugs.dolphin-emu.org/issues/6572

**Comment by JMC47** [comment]
Fixes the D3D crash in Paper Mario.

**Comment by Helios747** [comment]
I'd be cool with reimplementing D3D12 if it can be proven that maintaining it (read, fixing issues) can be done by fixing common code, so that we're not trapped to only graphics devs that have windows 10 set up and can be bothered.

Intel iGPU users would rejoice.

**Comment by lioncash** [comment]
> Isn't the true solution to add a new maintainable D3D7 backend

thanks, i hate it

**Comment by stenzek** [comment]
> I'd be cool with reimplementing D3D12 if it can be proven that maintaining it (read, fixing issues) can be done by fixing common code, so that we're not trapped to only graphics devs that have windows 10 set up and can be bothered.

The idea is that with all the driving logic in common, it shouldn't need much in the way of actual maintenance, since it's just converting to the API. The backend code shouldn't ever need to change, unless it's for new features :)

**Comment by stenzek** [comment]
@M220 thanks, will look into it. FWIW, the logs are empty because none of the channels are enabled by default. They have to be turned on in Logging.ini.

**Comment by M220** [comment]
Thanks for letting me know! I thought it was my phone problem not giving dolphin the access to write to my storage or something like that :D

**Comment by iwubcode** [comment]
I tried about 10 to 15 Wii titles tonight (all on D3D), no regressions that I noticed!

However, it doesn't seem like D3D can enable GPU Texture decoding?

**Comment by stenzek** [comment]
Yeah, I decided against including D3D GPU texture decoding as part of the initial PR, since it requires a non-trivial amount of change to the shaders.

I'm actually considering pulling in SPIRV-Cross, and just transpiling to HLSL rather than generating HLSL in the first place. We'd need it for post-processing anyway, as there are subtle differences between the languages which could cause issues.

**Comment by stenzek** [comment]
Changed my mind and implemented GPU texture decoding on D3D, wasn't as much of a change as I feared (ended up hiding stuff behind macros).

Only two issues I'm currently aware of is broken stereo EFB copies on GL/Vulkan, and incorrect GPU texture decoding in Vulkan.

**Comment by stenzek** [comment]
Stereoscopy and GPU texture decoding on Vulkan should work fine now. This probably still needs further testing, but otherwise I'd say it's complete now as I'm not aware of any other issues.

**Comment by iwubcode** [comment]
I've only tested a few games in Vulkan but I am seeing a weird situation where the game "No More Heroes" will lock right when you start the game up (with no prior save data, right as he whistles and gets on his bike).  This does not occur on master and does not occur on D3D in this branch.

Otherwise, I've noticed no regressions.  AMD Rx480 is my card, Win10 (latest drivers to date).  I can look at logs tomorrow but wanted to post my initial observation.

**Comment by JMC47** [comment]
Does a fifolog from D3D reproduce the crash in OpenGL?

**Comment by iwubcode** [comment]
The issue is in Vulkan and unfortunately it doesn't seem to be reproducible in a fifolog

**Comment by stenzek** [comment]
@iwubcode I did find an issue where a stitched texture could be transitioned inside a render pass, which shouldn't happen now. I doubt it's what's causing the crash, but you never know. Speaking of which, is it a game crash, or a dolphin/gpu crash? JMC47 was unable to reproduce it with a NV GPU.

**Comment by iwubcode** [comment]
> 
> 
> @iwubcode I did find an issue where a stitched texture could be transitioned inside a render pass, which shouldn't happen now. I doubt it's what's causing the crash, but you never know. Speaking of which, is it a game crash, or a dolphin/gpu crash? JMC47 was unable to reproduce it with a NV GPU.

Thanks @stenzek .  I tried the new build but still see the same issue.

Dolphin itself doesn't crash, the image freezes up and then turns to black (no sound of course).  Even hitting the 'stop' button (multiple times) does not stop the rendering and I must force-quit the application.

**Comment by stenzek** [comment]
@iwubcode Again, not sure if it's the same issue, but we found strided XFB copy reconstruction could issue out-of-range copies. This should really crash/reset the driver, but it might be related.

I'd be curious what the call stack looks like when it's frozen if you attach a debugger to dolphin and pause it (the CPU/GPU threads).

**Comment by iwubcode** [comment]
@stenzek - the new build didn't help.

Here's the callstack:

```
DolphinD.exe!Common::Semaphore::Wait() Line 25
DolphinD.exe!Vulkan::CommandBufferManager::PrepareToSubmitCommandBuffer() Line 200
DolphinD.exe!Vulkan::Renderer::ExecuteCommandBuffer(bool submit_off_thread, bool wait_for_completion) Line 403
DolphinD.exe!Vulkan::VertexManager::ResetBuffer(unsigned int vertex_stride) Line 155
DolphinD.exe!VertexManagerBase::UploadUtilityVertices(const void * vertices, unsigned int vertex_stride, unsigned int num_vertices, const unsigned short * indices, unsigned int num_indices, unsigned int * out_base_vertex, unsigned int * out_base_index) Line 280
DolphinD.exe!Renderer::DrawImGui() Line 1082
DolphinD.exe!Renderer::Swap(unsigned int xfbAddr, unsigned int fbWidth, unsigned int fbStride, unsigned int fbHeight, const MathUtil::Rectangle<int> & rc, unsigned __int64 ticks) Line 1222
```

**Comment by stenzek** [comment]
@iwubcode huh, odd. Does turning off backend multi-threading in advanced options change anything?

**Comment by iwubcode** [comment]
> 
> 
> @iwubcode huh, odd. Does turning off backend multi-threading in advanced options change anything?

No it does not

**Comment by stenzek** [comment]
Could you check the callstack with the MT option off? I'm curious where it's getting stuck, it seems like it's somewhere in presentation.

**Comment by iwubcode** [comment]
@stenzek - seems to be the same callstack as before.  So it's getting stuck in presentation when waiting on the semaphore for submitting the command buffer?

**Comment by stenzek** [comment]
With multithreading off, the semaphore shouldn't ever block. I'll double-check the code.

**Comment by iwubcode** [comment]
Confirmed fixed.  Here was the original issue:

> The vertex buffer is full after the semaphore is drained, so it tries to submit the current buffer (and in the process, tries to drain the already-drained semaphore)

**Comment by falikhukoma1996** [comment]
im try it maybe great

**Comment by JMC47** [comment]
Works fine here.  Are you sure it runs fine in master too?

**Comment by M220** [comment]
Maybe He's Talking about android🤔, because any game that I tried to open in android ( with renderer set to OpenGL ) ended up closing itself (not emulator) but with vulkan or software, everything is like before and I can load any game that I have and it runs without a problem

**Comment by weihuoya** [comment]
crashed at `Renderer::ClearScreen` when call `glClearDepthf` on android.

**Comment by stenzek** [comment]
Reproduced the crash, except it was in SetAndClearFramebuffer (glClearDepth instead of glClearDepthf). Fixed as of latest push.

**Comment by RinMaru** [comment]
finally DX11 has multithreading I can disable dualcore THANK YOU

**Comment by dxgldotorg** [comment]
Anyone unable to use the Scan Visor in Metroid Prime 3 since this update?  I started a game up and it didn't work, even after checking the EFB copy settings.

**Comment by JMC47** [comment]
There's probably some regressions like that here and there.  I'll check it out.  Please keep testing games as this is a huge change that touched a lot of things!

**Comment by JMC47** [comment]
Cannot reproduce your issue.  Tested Vulkan and D3D real quick.

image

**Comment by weihuoya** [comment]
5.0-9654, mario kart wii glitches in vulkan on android. opengl don't have this issue.
screen

**Comment by riking** [comment]
@dxgldotorg , @weihuoya - please make sure to specify the GPU in use! also, filing bugs on http://dolp.in/i helps too without cluttering up Github.

**Comment by dxgldotorg** [comment]
My card is a GeForce GTX 1080 with driver 419.17.  What config options did you use?  It appears you were using 1x native and no antialiasing; I was using 3X resolution and tried both 8x MSAA and no antialiasing.

**Comment by JMC47** [comment]
GTX 1070.  I just use the default settings.  MSAA is known to break EFB stuff... so...

**Comment by JMC47** [comment]
In Super Mario Galaxy, the lenses flare effect is ~15 - 20% slower in OpenGL than it was before.  Vulkan and D3D seem to be about the same (Vulkan actually seems a bit faster, at least at 1x IR.  At 3x IR it seems about the same.)

A user with lower specs than me reported that it drops in a different scene with less geometry (but with the same effect lenses flare effect) from 95 FPS to 50 - 55 FPS even in D3D.

**Comment by dxgldotorg** [comment]
@JMC47 Just tested a bit more - Works at 1x IR (even with MSAA, haven't checked to see if it still randomly picks the wrong target), works sometimes at 2x IR with the reticule jumping around, and is completely non-functional at 3x and above.

**Comment by JMC47** [comment]
Alright, sounds like something's broken.  Thanks for the report, I'll test it more thoroughly now.

**Comment by JMC47** [comment]
Reproduced, Metroid Prime 3's scanner is broken at higher resolutions.

**Comment by nbohr1more** [comment]
FMV in iNinja is a rather strange looking...

**Comment by stenzek** [comment]
@nbohr1more please record and upload a fifolog.

**Comment by TheManuel2** [comment]
Just FYI, this update makes Mario Kart 64 crash at the end of a race.
See [here](https://forums.dolphin-emu.org/Thread-virtual-console-mario-kart-64?pid=489349#pid489349).
It does not happen with build 5.0-9633 but happens with 5.0-9638.

**Comment by JMC47** [comment]
There are some fixes in upcoming pull requests.  They should be merging soon.

**Comment by TheManuel2** [comment]
K, thanks.  I'll keep an eye out.  Just reporting in case it helps.

**Comment by stenzek** [comment]
@weihuoya MKWii should be fixed in #7895.

**Comment by weihuoya** [comment]
nice, it works again.

**Comment by Intiroso** [comment]
Having this problem since 5.0-9638 version with Metroid Prime 2 when trying to activate the scanner and with LoZ-Twilight Princess when trying to load a save file (both GameCube and EU versions. G2MP01 and GZ2P01 IDs)
Error

My config
Config

In MP2 **Store EFB Copies to Texture only** is disabled by default.

**Comment by stenzek** [comment]
Please create issues on the bug tracker if there are regressions from these changes.

**Pull request merged**
