### PR TITLE
[WIP] D3D: Invert depth

### PR DESCRIPTION
**Pull request by mrgreywater**
Notice: Please don't review. This probably breaks the OGL backend. This probably won't pass Lint.

This PR inverts the D3D depth buffer, which increases the accuracy of the perspective division and therefore fixes problems with several games such as [Pokemon Snap which previously didn't allow to finish the tutorial](https://code.google.com/p/dolphin-emu/issues/detail?id=4460&q=pokemon%20snap). (Also it fixes the currently broken viewport in D3D)

This PR mainly exists right now to run it through the fifoci.

Before this can be merged, it should be researched exactly where the differences in the depth buffer are between the software/opengl/d3d renderer, since they still seem to generate quite different results in some cases. Also if this will get merged, the OGL backend depth invert has to be added as well.

### CODE REVIEW

**Comment by delroth** [comment]
@dolphin-emu-bot rebuild

**Comment by mrgreywater** [comment]
seems to me the viewport in the first frame, and zfreeze is broken and needs a fix. (only looking at d3d)

**Comment by JMC47** [comment]
zfreeze not working kind of makes sense.  It's broken with fast depth.

**Comment by Linktothepast** [comment]
It seems to fix sonic adventure dx ui missing.

**Comment by mrgreywater** [comment]
@Linktothepast I reverted #1392, so that was expected. I will look into a proper replacement once the rest is working.

**Comment by BhaaLseN** [comment]
Took a shot at it too again, available at BhaaLseN/dolphin@2fb6522dff999 (branch depth-rewrite2). Fixed the OGL issue by including ApiType checks; but in the end its very close to your implementation (altho I started from the original galop1n commit again) - so things like zfreeze are most likely broken there aswell.

**Comment by comex** [comment]
I have a semi-new opinionated agenda: I want the open PR queue to be a list of things that either need Someone to take a look at them or will soon, so it's harder for PRs to fall down the list into oblivion.  Since this one has... existed for the purpose of fifoci... for a long time, I'm closing it.

**Pull request closed without merging**
