### PR TITLE
Change Debug Icon Size to 32 x 32

### PR DESCRIPTION
**Pull request by Pringo**
Change debug icon size to 32 x 32 from 24 x 24. This is mostly just to test if this fixes a bug as I am not at all familiar with wxWidgets.

Edit: Please don't merge this. There are proper 32 x 32 icons available instead of the resized icons in this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3969)

### CODE REVIEW

**Comment by Pringo** [comment]
Okay I believe this should now fix [Issue #9658](https://bugs.dolphin-emu.org/issues/9658). I believe it is now possible to squash commits when merging, if not someone please close this PR and open one without the commit mess.

Also before merging I wanted to know do 

toolbar_add_breakpoint
toolbar_add_memorycheck
toolbar_debugger_delete

actually show up in the interface anywhere? They are referenced in BreakpointWindow.cpp but I can't seem to actually find them when looking at the program.

**Comment by RisingFog** [comment]
Are these just resized 24x24 icons? Are there any native 32x32 icons available?

**Comment by Pringo** [comment]
@RisingFog Good point... These are actually available as native 32 x 32 icons here: http://www.deviantart.com/art/Boomy-multiplatform-36215357 which I probably should have looked at originally. I guess this PR should be closed as it is a mess and someone can add the higher resolution icons properly.

PS: Do you know what

SetToolBitmapSize(wxSize(24, 24));

does in BreakpointWindow.cpp? From what I can tell those icons are 16 x 16 and when I changed those numbers (the 24s) it didn't seem to do much of anything.

**Comment by RisingFog** [comment]
Closing PR per request.

**Pull request closed without merging**
