### PR TITLE
Remove Audio Settings from Menu

### PR DESCRIPTION
**Pull request by PEmu1**
Audio settings are a subset of the general configuration window. No other section like this has its own menu option so it should be removed to be consistent with the rest of the menu.

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4311)

### CODE REVIEW

**Comment by lioncash** [comment]
Completely disagree on removing this. This makes it less annoying to quickly change audio settings. This will also make it more annoying to test changes against multiple backends or DSP HLE/LLE, since it increases the amount of click-through.

**Comment by Pringo** [comment]
The current menu UI there is poor. No other menu subsection has its own menu option aside from audio. I see two ways of fixing this:

1. Remove the audio settings menu option.
2. Split the audio settings menu option out from the configuration and make it its own window.

Option 2 involves more work and I generally think that audio settings having its own window is really unnecessary. The argument that it will take more clicks to change settings can apply to a ton of other sections that there aren't menu options for as well.

**Comment by lioncash** [comment]
> Edit: Also when taking into account the config toolbar icon shortcut the clicks should be the same. 2 clicks from Config > Audio compared to 2 clicks for Options > Audio Settings.

That's fair, however this still makes it more annoying when it comes to bringing up the dialog quickly with the accelerators, which I use quite often when testing out changes because it's much quicker than moving a cursor around to select the same thing (in this case pressing `ALT+O+A`).

Audio settings are also part of the main three settings that are probably accessed more often than the others (the other two being controls and graphics), I don't think it's wise to bury it like that, all things considered.

> The current menu UI there is poor.

I wouldn't necessarily call this a fantastic way of fixing it either, considering the above.

**Comment by Pringo** [comment]
I won't argue this too much if it's decided that removing the option would be a pain for testers/developers but I do still think the UI should be reworked to some degree.

> Audio settings are also part of the main three settings that are probably accessed more often than the others (the other two being controls and graphics), I don't think it's wise to bury it like that, all things considered.

I suspect other subsections like graphics enhancements are accessed more frequently than audio. As an aside does Dolphin's stat collection collect info on this kind of thing and if so is the data publicly available? I was interested in looking into that previously but I wasn't sure who had access to it.

**Comment by lioncash** [comment]
> but I do still think the UI should be reworked to some degree.

Agreed.

> does Dolphin's stat collection collect info on this kind of thing and if so is the data publicly available?

I don't believe it does. Though it would be a pretty neat idea to have UI statistics. It'd certainly be nice to have data to back UI changes (e.g. culling UI options that are extremely underused). What do you think @delroth?

**Comment by Helios747** [comment]
Also against this. a UI rework would be better but Wx is not the place to be making reworks to UI IMO. Qt is where that should happen, but, then that gets into the whole problem of Qt just being in development hell.

I recognize that the current situation is not great but I do not want to remove UI here.

**Comment by Pringo** [comment]
> Also against this. a UI rework would be better but Wx is not the place to be making reworks to UI IMO. Qt is where that should happen, but, then that gets into the whole problem of Qt just being in development hell.

The problem with this approach (that you touched on) is that if the Qt version never gets finished then the UI is never going to be improved. I feel that we should work on improving the wx UI as long as it is around as the default.

**Comment by Armada651** [comment]
Closing this PR as there doesn't seem to be any support for this change. The decision to keep the menu item was made in PR #2807 and I agree with the original reasoning there.

**Pull request closed without merging**
