### PR TITLE
Update externals

### PR DESCRIPTION
**Pull request by shuffle2**
for arm64 compat

### CODE REVIEW

**Comment by stenzek** [comment]
@dolphin-emu-bot rebuild

**Comment by stenzek** [comment]
Seems this doesn't build on non-windows.

**Comment by shuffle2** [comment]
hm i only saw the lint error and just fixed that, was there more?

**Comment by stenzek** [comment]
Yeah, bunch of SFML errors.. which sound familiar, I vaguely recall them from a while back.

@dolphin-emu-bot rebuild

**Comment by shuffle2** [comment]
it seems clang-format as executed by VS doesn't result in something the linter is happy with ...

**Comment by stenzek** [comment]
> `../Source/Core/Core/NetPlayClient.cpp:1558:12: error: ambiguous overload for 'operator>>' (operand types are 'sf::Packet' and 'lzo_uint {aka long unsigned int}')`

Might have to be explicit about the type here?

**Comment by shuffle2** [comment]
Tools/lint.sh uses an out of date clang-format. WTF

**Comment by shuffle2** [comment]
> > `../Source/Core/Core/NetPlayClient.cpp:1558:12: error: ambiguous overload for 'operator>>' (operand types are 'sf::Packet' and 'lzo_uint {aka long unsigned int}')`
> 
> Might have to be explicit about the type here?

I'm not really sure how sf::Packet (a nontrivial class) can be ambiguous with respect to...a scalar integer.

**Comment by stenzek** [comment]
I was more wondering if you had to use u32/u64 (or the SFML typedefs for those).

**Comment by shuffle2** [comment]
I mean..might as well try, but note the arg type to lzo1x_decompress is `lzo_uint`

**Comment by stenzek** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
