### PR TITLE
Removed iterative input from the option group. It already exists in t…

### PR DESCRIPTION
**Pull request by MikeRavenelle**
…he mapping window. The checkbox in the option group also did not function. Since the iterative input is not a option for the actual controllers I agree with having it in the mapping window.

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by spycrab** [comment]
Please shorten your commit message and give it a proper prefix e.g. ``Core/HW: ...``

**Comment by MikeRavenelle** [comment]
Done.

**Comment by Techjar** [comment]
You should squash those commits.

**Comment by MikeRavenelle** [comment]
Okay should be squashed and removed the styling issue.

**Pull request merged**
