### PR TITLE
Remove primitive restart

### PR DESCRIPTION
**Pull request by weihuoya**
Is there any reason to use such feature? it just make code complex.

### CODE REVIEW

**Comment by stenzek** [comment]
Is there a reason not to use it? My suspicion would be that fewer transfers across PCIe could lead to better performance on low-end systems. But I'm happy to be corrected if the numbers say it's not any slower...

**Comment by weihuoya** [comment]
the mapped gpu memory  is constant size, not baseed on data size. and is it really reduces  generate index buffer size? use 4 indices per triangle.

**Comment by stenzek** [comment]
Yes, the mapping is a constant size, but it's a persistent (and potentially coherent) mapping. There is no implicit copy of the entire buffer, the only bytes copied are the ones which are written.

**Comment by degasus** [comment]
The GC GPU does not support indexed vertices. So to avoid redundant transforming & lighting, high polygon games use triangle_strips for their big meshes. This fits better to the primitive_restart path, and it was the reason to implement it many years ago.
But honestly, I was told that the strips generator with primitive restart was slower for some other developer by a small margin. So I wonder if you are able to confirm the same behavior. And if so, I wonder if the strip merger has an implementation issue or if the algorithmn is slower in general.

**Comment by weihuoya** [comment]
oh, i'm not familiar with this.:laughing:

with this changes, run stereo mode in vulkan backend, game will crash in some place, don't known where going wrong.

**Pull request closed without merging**
