### PR TITLE
[WIP] Add support for 16bit compressed z buffer format EFB peeks.

### PR DESCRIPTION
**Pull request by phire**
Please review only the last commit, Currently only supports OpenGL

### CODE REVIEW

**Comment by phire** [comment]
I've probably done something wrong.

To get RS3 working, I needed to reverse the depth buffer and use bits 0-23 instead of bits 8-31. But WW doesn't work anymore with the same changes.

**Comment by degasus** [comment]
rebase to resolv the zfreeze dependency?

**Comment by ADormant** [comment]
What's the status on this ?

**Comment by phire** [comment]
This is completely wrong. Should be re-done correctly.

**Pull request closed without merging**
