### PR TITLE
Android: Update Gradle Plugin to 3.6.0

### PR DESCRIPTION
**Pull request by Simonx22**
Android Studio recommends updating to version 3.6.0

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by leoetlino** [comment]
Sounds fine to me, but the Android build is failing.

**Comment by Simonx22** [comment]
@leoetlino the android NDK version on the buildbot needs to be updated.

**Comment by Simonx22** [comment]
This is outdated now, see #8805 (the buildbot still needs to be updated though)

**Pull request closed without merging**
