### PR TITLE
Delete apprsrc.h

### PR DESCRIPTION
**Pull request by Krak-n**
I was casually browsing the "// TODO"s and came across this file. Is it still needed? I'm unable to find anything that references it... (I'm using the default GitHub search, so I may have missed something)

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3828)

### CODE REVIEW

**Comment by Krak-n** [comment]
Disregard, I've found a few more files that are empty... I'm going to look at a few more files an create a new PR.

**Comment by phire** [comment]
It's probably best to leave things in externals alone, they are all reflections of upstream.

**Comment by Krak-n** [comment]
Understood!

**Comment by SwooshyCueb** [comment]
On a related note, can we use git submodules for more of the stuff in Externals?

**Pull request closed without merging**
