### PR TITLE
Jit64: drop more x86_32 left-overs

### PR DESCRIPTION
**Pull request by Tilka**

### CODE REVIEW

**Comment by lioncash** [comment]
Doesn't ARMv7 use the 32-bit stuff? Forget which ifdefs are used for each platform. cc @Sonicadvance1

**Comment by Tilka** [comment]
No, all of this is x86-only.

**Comment by Sonicadvance1** [comment]
_ARCH_{32,64} hits all platforms.
I'm actually surprised that this compiles on ARM. How odd.

**Comment by Sonicadvance1** [comment]
@dolphin-emu-bot rebuild
Just because I don't believe it.

**Pull request merged**
