### PR TITLE
Added buffer joystick input toggle on Windows

### PR DESCRIPTION
**Pull request by Sage-King**

### CODE REVIEW

**Comment by jordan-woyak** [comment]
I don't think this needs to be exposed to the user. I also don't think "non-buffered" data is going to result in a less latency.
When using "buffered" data all of the events are popped through to get the latest data available as soon as possible. https://github.com/dolphin-emu/dolphin/blob/f6b07840b70a52de375d16a6414a080a1ba633dc/Source/Core/InputCommon/ControllerInterface/DInput/DInputJoystick.cpp#L248

Code is in place to fallback to non-buffered just because DirectInput is an old mess and some devices require one way and not the other.

Do you have evidence that this is actually reducing latency?

**Comment by Sage-King** [comment]
@jordan-woyak Nope. I don't have evidence. Just attempting to reduce latency. It seems reasonable that popping through all of the events is adding latency though. If I can't get the latency down to where I want it with other fixes, I may come back to this. I don't understand how buffering inputs would help with "troublesome" devices though. Can you explain that? Why not just remove buffering entirely?

**Comment by JosJuice** [comment]
> It seems reasonable that popping through all of the events is adding latency though.

Yeah, by maybe a microsecond or something. I don't think we should add an option for this unless you've tested that it lowers latency by a measurable amount.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by Sage-King** [comment]
Nope I haven't. I will close the PR. My friends were just talking about the latency they feel on their controllers so I thought I'd give it a go.

**Pull request closed without merging**
