### PR TITLE
Linted markdown for the README

### PR DESCRIPTION
**Pull request by rogersachan**
I've linted the markdown to improved legibility and to avoid errors in markdown rendering.

### CODE REVIEW

**Comment by lioncash** [comment]
LGTM once the two merge commits are rebased out.

**Comment by rogersachan** [comment]
@lioncash rebased

**Comment by JosJuice** [comment]
That's not a rebase, that's another merge commit.

**Comment by rogersachan** [comment]
bad button

This is what I did, but I'll have to create a new PR to rebase then

**Comment by JosJuice** [comment]
Creating a new PR does work, but it gets unnecessarily messy. Please rebase using command-line git. (It's not possible to rebase using GitHub's web UI.)

**Comment by leoetlino** [comment]
If you do decide to rebase this PR properly instead of making a new PR, don't forget to reopen this PR before pushing it. Otherwise GitHub will force you to open a new one.

**Comment by rogersachan** [comment]
I moved the PR to #4561

**Comment by rogersachan** [comment]
That PR doesn't have any of the merge baggage from earlier, so I think that one is better to merge and is up to date with master.

**Pull request closed without merging**
