### PR TITLE
TypeUtils: Add ToPointer function

### PR DESCRIPTION
**Pull request by Minty-Meeo**
This esoteric use of operator overloads is a better way to convert iterators into raw pointers when applicable.

### CODE REVIEW

**Comment by Minty-Meeo** [comment]
This PR is more so to gauge interest in such a utility.  I would not be too offended if it were rejected, but I believe this is an elegant solution that simply needed a friendly wrapper to become easily usable.

**Comment by lioncash** [comment]
Personally, it seems like it'd be more explicit to do `std::addressof(*iter)` to disambiguate getting the address. I feel otherwise it's not exactly clear from a glance whether or not the iterator itself or the data it points to is having its address taken (at least with the current name of ToPointer)

**Comment by AdmiralCurtiss** [comment]
Yeah, agreed with that, the way it's currently just makes it ambigous what exactly you're getting a pointer to.

**Comment by Minty-Meeo** [comment]
Well, any name specific to iterators wouldn't be ideal, as this function also works great with std::optional, std::expected, and Common::Result (and maybe more).  The next best option I can think of would be along the lines of "GetMemberOfPointer".  There is also the nuclear option of simply using operator-> at these sites, but this does nothing to help generic code (not that it is currently required of the utility).

**Comment by Minty-Meeo** [comment]
@dolphin-emu-bot rebuild

**Pull request closed without merging**
