### PR TITLE
Android: Gradle updates

### PR DESCRIPTION
**Pull request by t895**
- Updates gradle to 8.2 and AGP to 8.2.0 (currently in beta so I'm waiting for stable before this is ready)
- Updates dependencies and removes redundant lifecycle dependency
- Regenerates baseline profile module using new AGP 8.2.0 interface that doesn't require a copy task
- Compile/Target Android 14 (Waiting on testing in Android TV due to changes to services)
- Convert gradle files from Groovy DSL to Kotlin DSL - Should make things a little less painful for edits to version codes and all

### CODE REVIEW

**Comment by lioncash** [comment]
What's the status on this?

**Comment by t895** [comment]
I was just waiting on the AGP update. It came out within the past day or two so I'll have this ready soon.

**Comment by t895** [comment]
This is ready to review now, but I will need to pair this with a PR to the infra repo for the new baseline profile generation command.

**Comment by JosJuice** [comment]
Please squash "Android: Use stable AGP 8.2" into the commits where the use of the beta version was added.

**Comment by t895** [comment]
Fixed

**Comment by t895** [comment]
This should be merged alongside [this](https://github.com/dolphin-emu/sadm/pull/195) infra PR

**Comment by t895** [comment]
Well, this could be merged without the infra PR since that build step can fail silently.
Also side note from the discussion in the discord earlier about the baseline profile build step failing. This PR should fix that issue. I'm pretty sure it was failing because I didn't update the java version in the benchmark module back when I had it bumped in [this](https://github.com/dolphin-emu/dolphin/commit/9a7e1652f3e622f4a6391d6e1677e0b70b2b12a9) commit.

**Review by JosJuice — APPROVED** [review]

**Pull request merged**
