### PR TITLE
Remove frame skipping.

### PR DESCRIPTION
**Pull request by RachelBryk**

### CODE REVIEW

**Comment by phire** [comment]
Can we remove the g_bSkipCurrentFrame code from video common and the video backends too?

Or is it still used for something?

**Comment by magumagu** [comment]
You missed deleting VideoBackend::Video_SetRendering etc.

Frame skipping is a substantial benefit when dealing with crappy integrated graphics, but I'm not sure that justifies keeping it around.

**Comment by JMC47** [comment]
It breaks a lot of games, it works sporatically in a lot of games, and the CPU Clock Override does everything this feature can do in terms of making less frames render in most titles.

**Comment by phire** [comment]
And CPU Cock Override has the advantage of reducing CPU load too.

**Comment by degasus** [comment]
honestly, I like this feature for the software renderer. It's mostly broken, but sometimes you'll get a correct image much faster.

**Comment by JMC47** [comment]
That's the first legit reason I've heard for keeping it.

**Pull request closed without merging**
