### PR TITLE
Dragon Ball Z: Budokai Tenkaichi 3 - Graphics Mod Bloom and HUD Definitions

### PR DESCRIPTION
**Pull request by Seedonator**
The only HUD textures I'm aware of that I haven't defined are the character faces as there's a LOT to go through. Would really appreciate if anyone wants to help out.
The native resolution bloom fix is definitely needed for this game, as you can see [on the wiki](https://wiki.dolphin-emu.org/index.php?title=File:Budokai_Tenkaichi_3_Bloom.png)

### CODE REVIEW

**Comment by iwubcode** [comment]
I think this looks good.  Can you squash your commits?

**Comment by Seedonator** [comment]
> I think this looks good. Can you squash your commits?

Alrighty should be done! By the way I'm not fully sure how Graphics Mods work cause there's pretty limited documentation out there, so I don't know exactly how to handle textures like these:
tex1_256x64_974aae7fb39dd3fe_dc826162c7781cf3_9
tex1_256x64_974aae7fb39dd3fe_c0adc9c4480c91c1_9
Basically where there's a lot of textures that have the same beginning first half, it's a pain to manually enter all of them and probably isn't too easy for anyone else to work with either

**Comment by iwubcode** [comment]
> Basically where there's a lot of textures that have the same beginning first half, it's a pain to manually enter all of them and probably isn't too easy for anyone else to work with either

Unfortunately, this is just the way graphics mods work.  In the future that might change but the one-by-one approach is how it works right now.

**Review by iwubcode — APPROVED** [review]
Seems fine.  Untested!

**Pull request merged**
