### PR TITLE
Fix recording a movie with the GC Adapter

### PR DESCRIPTION
**Pull request by mathieui**
Fix for https://bugs.dolphin-emu.org/issues/9298.

Also use a newly introduced function in netplay to check if the device can be assimilated to a GC controller.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3589)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/Core/HW/SI.cpp, line 267 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9YsdtlBohtH4QWn8fu:-K9YsdtmwiK806Sue8hN:-1667240386) ([raw file](https://github.com/dolphin-emu/dolphin/blob/27a1f2433b110902a2f88fce60808583e7ee710d/Source/Core/Core/HW/SI.cpp#L267)):*
Unnecessary `b` at the end.

---

*[Source/Core/Core/HW/SI_Device.cpp, line 75 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9YrBbSIQD7SecQ91S4:-K9YrBbSIQD7SecQ91S5:-489186407) ([raw file](https://github.com/dolphin-emu/dolphin/blob/27a1f2433b110902a2f88fce60808583e7ee710d/Source/Core/Core/HW/SI_Device.cpp#L75)):*
cases should be at the same indentation as the opening brace.

---

*[Source/Core/Core/HW/SI_Device.cpp, line 81 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9YrHZSSyQPtDt4VoCl:-K9YrHZTupIpZ2lF64uy:272123774) ([raw file](https://github.com/dolphin-emu/dolphin/blob/27a1f2433b110902a2f88fce60808583e7ee710d/Source/Core/Core/HW/SI_Device.cpp#L81)):*
Unnecessary break.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589)*

**Comment by mathieui** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/Core/HW/SI.cpp, line 267 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9YsdtlBohtH4QWn8fu:-K9YuVcZtOu-osjANDCI:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/27a1f2433b110902a2f88fce60808583e7ee710d/Source/Core/Core/HW/SI.cpp#L267)):*
Done.

---

*[Source/Core/Core/HW/SI_Device.cpp, line 75 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9YrBbSIQD7SecQ91S4:-K9YuUTQSc3AsjF375mw:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/27a1f2433b110902a2f88fce60808583e7ee710d/Source/Core/Core/HW/SI_Device.cpp#L75)):*
Done.

---

*[Source/Core/Core/HW/SI_Device.cpp, line 81 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9YrHZSSyQPtDt4VoCl:-K9YuUFVSQfcJoF6efCr:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/27a1f2433b110902a2f88fce60808583e7ee710d/Source/Core/Core/HW/SI_Device.cpp#L81)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589)*

**Comment by skidau** [comment]
*[Source/Core/Core/HW/SI_Device.cpp, line 73 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9Z5eUYy9ETt67CenhW:-K9Z5eUYy9ETt67CenhX:-1938577448) ([raw file](https://github.com/dolphin-emu/dolphin/blob/92bd443df6a3df6372dc1384a94c5921d662fdab/Source/Core/Core/HW/SI_Device.cpp#L73)):*
Instead of checking against type, should this be checking against SI_GC_STANDARD ?  It is not clear what the purpose of this function is for.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589)*

**Comment by mathieui** [comment]
*[Source/Core/Core/HW/SI_Device.cpp, line 73 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9Z5eUYy9ETt67CenhW:-K9Z84cob0Ki7-u4taCa:1980995305) ([raw file](https://github.com/dolphin-emu/dolphin/blob/92bd443df6a3df6372dc1384a94c5921d662fdab/Source/Core/Core/HW/SI_Device.cpp#L73)):*
It’s not the same enum

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589)*

**Comment by skidau** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/HW/SI_Device.cpp, line 73 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9Z5eUYy9ETt67CenhW:-K9Z8axtJpLCYKyVKUcL:182582096) ([raw file](https://github.com/dolphin-emu/dolphin/blob/92bd443df6a3df6372dc1384a94c5921d662fdab/Source/Core/Core/HW/SI_Device.cpp#L73)):*
I mean, how did you arrive at this list of devices?  What is the difference between calling this function and checking against SI_GC_STANDARD?  If it is to check for devices that can be substituted for a GC controller, I don't think SIDEVICE_GC_STEERING should be in this list.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589)*

**Comment by mathieui** [comment]
*[Source/Core/Core/HW/SI_Device.cpp, line 73 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9Z5eUYy9ETt67CenhW:-K9ZATWzG4U0JoW_47iq:1635916315) ([raw file](https://github.com/dolphin-emu/dolphin/blob/92bd443df6a3df6372dc1384a94c5921d662fdab/Source/Core/Core/HW/SI_Device.cpp#L73)):*
I looked at which devices inherited from the GC Controller SI device, and the Steering Wheel came up (it appears that it maps the pedals & stuff to standard buttons, looking at the code). And I’m not sure how I should check against SI_GC_STANDARD because I am not seeing a way to map the SIDevices enum (which is all I have) type to the TSIDevices one, or if it would have an additional benefit.
This function was mostly to avoid having ifs all over the place checking for every device it could work with (like the two next commits do).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589)*

**Comment by RisingFog** [comment]
Any update on this?

**Comment by BhaaLseN** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/HW/SI_Device.cpp, line 73 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9Z5eUYy9ETt67CenhW:-KB9-q4O6wOByvFIbRJb:1040355032) ([raw file](https://github.com/dolphin-emu/dolphin/blob/92bd443df6a3df6372dc1384a94c5921d662fdab/Source/Core/Core/HW/SI_Device.cpp#L73)):*
It might help to extend on the comment above by specifying what you meant with "inherits from the gc controller" (as in, more specifically, derives from `CSIDevice_GCController`) and (perhaps even more than the former) by adding the actual _intent_ of the function (as in, at least by guessing from the discussion, to determine if the given device acts as if it were a controller, even when it doesn't look like one physically; or uses the same control structures or whatever...)

Also, does the same logic in SI.cpp apply to the N64 ones, or is this exclusively meant for GC? If not, maybe that distinction can further add to commenting the purpose and intent of this function.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589)*

**Comment by mathieui** [comment]
*[Source/Core/Core/HW/SI_Device.cpp, line 73 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9Z5eUYy9ETt67CenhW:-KBPR7bU-1797W0zz7d1:-1606532851) ([raw file](https://github.com/dolphin-emu/dolphin/blob/92bd443df6a3df6372dc1384a94c5921d662fdab/Source/Core/Core/HW/SI_Device.cpp#L73)):*
The goal is to check if the controller is a CSIDevice_GCController and as such provides the relevant hooks for netplay and movie input. The "right" way (in my opinion) of doing things for netplay would be to have a special SI Device that only works there (but that will probably wait until a netplay overhaul after 5.0), and I don’t see how to do differently for movie input currently, as the player often wants to keep playing after the end of the movie (implicitly swapping devices would probably cause a whole new lot of issues).

As for N64 SIDevices, I am not sure as I don’t exactly understand how they work yet.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589)*

**Comment by RisingFog** [comment]
LGTM, but would like other opinions before merging.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/HW/SI_Device.cpp, line 73 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9Z5eUYy9ETt67CenhW:-KBiRftPERGv5eYXDtpi:-807108557) ([raw file](https://github.com/dolphin-emu/dolphin/blob/92bd443df6a3df6372dc1384a94c5921d662fdab/Source/Core/Core/HW/SI_Device.cpp#L73)):*
I'm okay with the comment as it is now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-:-KBiRnbKeZVU6ASnd3oZ:1200459437)*

**Comment by BhaaLseN** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/HW/SI_Device.cpp, line 73 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9Z5eUYy9ETt67CenhW:-KBipItiuttolWdUoObO:-674407809) ([raw file](https://github.com/dolphin-emu/dolphin/blob/92bd443df6a3df6372dc1384a94c5921d662fdab/Source/Core/Core/HW/SI_Device.cpp#L73)):*
Good enough I guess. Still not sure about the name, but for the lack of anything better, the comment gives an indication of what its supposed to do.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589)*

**Comment by skidau** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589)*

**Comment by skidau** [comment]
*[Source/Core/Core/HW/SI_Device.cpp, line 73 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9Z5eUYy9ETt67CenhW:-KBizFdHcqb-s4QwAz-8:5174689) ([raw file](https://github.com/dolphin-emu/dolphin/blob/92bd443df6a3df6372dc1384a94c5921d662fdab/Source/Core/Core/HW/SI_Device.cpp#L73)):*
ok

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589)*

**Comment by mathieui** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/HW/SI_Device.cpp, line 73 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9Z5eUYy9ETt67CenhW:-KBizZnlZWzO5bTdSJ17:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/92bd443df6a3df6372dc1384a94c5921d662fdab/Source/Core/Core/HW/SI_Device.cpp#L73)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589)*

**Comment by mathieui** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/HW/SI_Device.cpp, line 73 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589#-K9Z5eUYy9ETt67CenhW:-KBj-7yHqrTDlWGUZaUL:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/92bd443df6a3df6372dc1384a94c5921d662fdab/Source/Core/Core/HW/SI_Device.cpp#L73)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3589)*

**Pull request merged**
