### PR TITLE
Interpreter: Update CR when FRSP's record bit is set

### PR DESCRIPTION
**Pull request by lioncash**
Checked using my tests [here](https://github.com/lioncash/DolphinPPCTests)

### CODE REVIEW

**Comment by degasus** [comment]
Do you think the fallback to this instruction shall be added to the jits within the same PR?

**Comment by Phatcat** [comment]
You didn't wanna add the fallback to JitArm64 as well now that you're at it?

**Comment by lioncash** [comment]
@degasus done

**Comment by degasus** [comment]
LGTM

**Pull request merged**
