### PR TITLE
[Android] NDK Updates

### PR DESCRIPTION
**Pull request by Tsunamical**
Commits currently untested, but should improve the range of devices we can build on.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3780)

### CODE REVIEW

**Comment by delroth** [comment]
"Will it build at the moment? I highly doubt it." why don't you test it locally?

@dolphin-emu-bot rebuild

**Comment by Tsunamical** [comment]
Very minimal time, don't have NDK r11x installed. Was planning on testing this weekend.

**Comment by Tsunamical** [comment]
Also, if we're bumping to 21, we may want to trim down our allowed versions to reflect that, meaning get rid of versions that don't support it.

**Comment by Tsunamical** [comment]
Okay, I'll get around to testing ASAP but I've pulled in a few build fixes for higher cmake revisions and just cleaned up the gradle script a tiny bit. It's probably more trouble than it's worth at the moment to revamp the script - but it's on the backburner for sure.

**Pull request closed without merging**
