### PR TITLE
TextureCache: Use same color coefficients for EFB2Tex as EFB2RAM

### PR DESCRIPTION
**Pull request by stenzek**
Fixes "blotches" in metroid prime 3 (not sure if correctly yet though).

### CODE REVIEW

**Comment by JMC47** [comment]
This has been heavily tested and fixes a ton of minor color issues in games.  fixes SW renderer not being blue enough. or being too green. Semantics.

**Comment by JMC47** [comment]
Can this be reviewed ASAP by graphics people?  I'd like to do work on the progress report early this month and this is one of the big candidates.

**Comment by iwubcode** [comment]
@stenzek - just curious how you came up with those 'magic numbers' were they trial and error or some knowledge you knew somehow!  

I can't speak to the details of what the code is doing but would it be possible to take the magic numbers with division and put them in a constant? (constexpr?)

**Comment by stenzek** [comment]
@iwubcode they're the same as the ones used in the EFB2RAM shaders (https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/VideoCommon/TextureConversionShader.cpp#L196). It converts the normalized color a 0-255 range, scales it to the difference in the number of bits in the texture format (e.g. for RGB565 this would be 2^3 or 2^2), and then is normalized again before being output.

I would've assumed that scaling to floor(2^(nbits-1)) / 2^(nbits-1) would've been correct, but the expression in the PR produces results closer to that of the console. 

The next logical step here is to use integer math instead of floating-point, but we're not sure if we should scale or truncate to the lower number of bits (the software renderer truncates, and does not produce correct results, but IIRC it's using the lower bits not the higher bits).

This is however outside the scope of this PR (the aim here was to fix a few graphical glitches, mainly MP3), but definitely something we should do in the future.

As for the division in the expression, any decent compiler should evaluate 255.0f / 8.0f and store that in a constant, no need to be explicit about it (gcc does this even at -O0).

**Comment by hthh** [comment]
I reviewed this very thoroughly yesterday and checked through the constants, but I'm not a graphics person, so I don't want to waste peoples time. But I do want to merge this, and I'd be happy to sign off on it if you can answer a couple of questions.

Firstly, the constants work perfectly with IEEE754 floating point, but fast-math in shaders makes me wary when using `floor` on precise integer values. Would it be safer to add a constant delta (`1.0/64.0` as half of the required precision) when rounding down to avoid `floor(0.3-0.2-0.1) == -1` style problems. Is there a reason to believe it won't be optimised unsafely? Or a reason to avoid adding a constant delta? (I spent some time looking at the Nvidia VP6 bug lately, hence the paranoia)

Secondly, there is one constant you didn't change, even though you changed the operation to `floor` - the default (multiply-by-255 constant). While it was obviously dodgy before, it occurs to me that in MSAA mode the average of seven (255,255,255)s and one (254, 254, 254) used to map to (255,255,255). It now would map to (254, 254, 254). Is that worth rectifying? Or is that out-of-scope, since it used to behave even more weirdly?

Thanks for doing these changes, I learned a lot by reading through them, and sorry if the comments are too nit-picky - this is a huge change for the better! 👍

**Comment by hthh** [comment]
Okay, I'm probably crazy, and sorry for commenting twice, but after reading that I realised both my concerns are kind of the same issue, and could be fixed in the same way.

I propose adding half the precision before `floor`: `floor((texcol * colmat[5]) + (colmat[5] / 255 / 2))`. This will add 0.5 before rounding for the 255.0 case, and add 1/64 before rounding in the 255.0/32.0 case. I think it's a combination of the benefits of `floor` and `round`. (Optimise with multiply by reciprocals if shader compilers can't for some reason.) Does that make any sense?

**Comment by stenzek** [comment]
@hthh The main purpose of this PR is to make the efb-to-texture shaders generate the same values as efb-to-ram, I'd prefer to avoid changing the behavior of both paths for now.

Adding half of the final divisor like you've suggested does make sense to me though. If 8-bit color isn't forced, I'm not sure how likely rounding error is though, as we're truncating colors to 5/6 bit in the fragment shader, so the delta between inputs would only be 1/32 or 1/64 respectively. However, when you throw blending into the mix, which is done at the full 8-bit precision, that could complicate things.

There's a few other places format conversion is done as well (efb2ram, EFB format changes) that we should probably be consistent across, but IMO switching to integer math here and avoiding this situation entirely would be preferable.

In regards to the MSAA case, good point, however as far as I can tell that'll only affect D3D in this way, in GL/Vulkan we resolve the texture first. I'm not sure if the spec enforces a specific filter for resolving, but regardless it's out of our control here, unless we sampled the MSAA texture in the shader as D3D does.

**Comment by hthh** [comment]
@stenzek Thanks for clarifying all that, I hadn't realised the initial precision was 5/6-bit, and integer math will definitely be a more readable solution.

LGTM

**Comment by stenzek** [comment]
@hthh Just to clarify, there are a few options, IIRC it's RGB8, RGB565 or RGB5A3. Not sure what the distribution of these formats is like in games, I'd assume the latter two are used more frequently though (and if there's any alpha-channel based effects, there's only one choice).

**Comment by degasus** [comment]
No need to keep care about the colmat value on rounding behavior. It should be fine to just add a small epsilon like 1.0/256.0. But I agree, we should focus in integer shaders, so LGTM.

**Pull request merged**
