### PR TITLE
Refactor Member Ignoring Method smell in TvMainActivity class

### PR DESCRIPTION
**Pull request by emaiannone**
Hi, I'm Emanuele Iannone, a master student at University of Salerno.
Since my bachelor's thesis I have been working on a **code smell refactoring plugin** called *aDoctor*, which is able to identify and fix energy-related problems in Android apps.
I launched it on your project, finding different instances of code smells. I chose one of them and let the plugin automatically fix it.
In this case I chose Member Ignoring Method, that is present when a non static method does not use at all instance variables and other non static methods. These kind of smell may have a non trivial impact on energy consumption, as shown in this paper: `https://www.sciencedirect.com/science/article/pii/S0950584918301678`.
Besides, this kind of refactoring does not impact on the functionalities of your app, so it is totally safe. Let me know if you are interested in this refactoring proposal.

### CODE REVIEW

**Comment by jordan-woyak** [comment]
I realize this change was done by a program but it has removed comments and changed the formatting of the code. Please undo those changes.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by BhaaLseN** [comment]
Is the actual change there making the method `static`? If so, I wonder if it would be more consistent to keep it the same across different `buildXxxxRow` methods (preferably: make all of them `static`, but I'm guessing that isn't possible since otherwise the tool would've made it?)

**Comment by Helios747** [comment]
Given that Dolphin barely spends any time in the Java UI code and the vast majority of the CPU time in the common emulation code compiled with the NDK, it's hard to justify refactors with the goal of energy consumption. Especially since you don't really have any data to support that this helps Dolphin specifically. A paper on how it works for mobile workloads is great, but we're hardly a standard mobile workload. (As shown by mobile CPU governors getting wildly confused with Dolphin :))

**Comment by emaiannone** [comment]
Thanks for the feedbacks, I will improve the tool in order to avoid situations where it changes the formatting instead of forcing one in particular.
@Helios747 if you show me an important class (or package)  where to run the tool I might try to find other smells. Let me know, if you are interested.

**Comment by jordan-woyak** [comment]
@emaiannone Do you plan on fixing the formatting issues in this PR?

**Comment by emaiannone** [comment]
@jordan-woyak Hi Jordan, sorry for late response. I fixed this aspect of the tool, so subsequent refactoring will not break the indent. Anyway, I won't fix this PR because I don't want to break anything else :)

**Comment by BhaaLseN** [comment]
If you leave this PR as-is, it will likely never be merged. If that is what you want, you might as well close it.

**Comment by JosJuice** [comment]
Closing, then. Feel free to reopen this if you want to change the PR so that it just adds the `static` without changing anything else.

**Pull request closed without merging**
