### PR TITLE
Jit64: implement FPSCR related instructions

### PR DESCRIPTION
**Pull request by Tilka**

### CODE REVIEW

**Comment by lioncash** [comment]
Does mffs set all the top bits of the destination register to 1?

**Comment by Tilka** [comment]
@lioncash: Something like this? Did you do a hardware test? (I'd actually expect something like fctiw where it just makes it a NaN.)

`riPS0(_inst.FD) = (0xFFFFFFFFu << 32) | FPSCR.Hex;`

**Comment by lioncash** [comment]
I've re-run my tests, and you're correct; MFFS-ing a cleared FPSCR into a reg set to zero does produce a NaN. I might have been thinking about a different instruction.

**Comment by Tilka** [comment]
Haven't run into any problems.

**Pull request merged**
