### PR TITLE
VideoCommon: xxhash

### PR DESCRIPTION
**Pull request by degasus**
This branch fork the xxhash source into common. I've tried to not touch the source as much as possible.

I'm going to use the XXH64 for custom texture hashes.

### CODE REVIEW

**Comment by mimimi085181** [comment]
If this is faster than murmur, what about using this for devices that don't have hardware crc32 support?

**Comment by degasus** [comment]
@mimimi085181 Only if the safe texture cache is enabled. But maybe (read likely) it's worth to also change the hash itself based on the texture cache accuracy.

**Comment by degasus** [comment]
Profile: http://markus.members.selfnet.de/dolphin/xxhash.png

In my opinion, only the safe hash performance matters for custom textures. So CRC32 would win, but it depends on a CPU extension. So I think XXH64 is the one to use. Murmur3 however shouldn't be used because of the 250% cpu overhead.

If anyone wants to try this on windows, have fun: http://dl.dolphin-emu.org/wips/degasus-dolphin-xxhash-4.0-5156+-x64.7z

**Comment by BigheadSMZ** [comment]
I will test anything that gets this moving along since this is needed for the custom texture changes. I won't get to it until tonight though, but what exactly needs testing? Bugs? Speed? Basically anything and everything?

**Comment by degasus** [comment]
This was just a try to work around my lacking visual studio knowledge. But #1898 is the way to go here. Sadly, I think I'll have to learn how to generate thos project files on linux.

**Comment by shuffle2** [comment]
I've built this branch locally and it works fine...so there is some issue with old objects in the buildbot's build tree :|

**Comment by shuffle2** [comment]
@degasus you should also add the xxhash's guid in the sln's `GlobalSection(NestedProjects) = preSolution` section, within the guid for "Externals". This causes it to appear in the correct location in the solution tree view.

**Comment by degasus** [comment]
Yey, it did compile. Ready to review + merge :D

**Pull request merged**
