### PR TITLE
DVDInterface: Less rounding error

### PR DESCRIPTION
**Pull request by JosJuice**
[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3680)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/Core/HW/DVDInterface.cpp, line 673 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3680#-KBi2pBlJ1unJP_ECCEz:-KBi2pBmzKU411uvFhA_:-305512373) ([raw file](https://github.com/dolphin-emu/dolphin/blob/451bb6db8d83689c654a2bfe016ecddcc97b50b0/Source/Core/Core/HW/DVDInterface.cpp#L673)):*
static_cast

---

*[Source/Core/Core/HW/DVDInterface.cpp, line 1327 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3680#-KBi2rXtT6r2SQ06YP67:-KBi2rXtT6r2SQ06YP68:-469765787) ([raw file](https://github.com/dolphin-emu/dolphin/blob/451bb6db8d83689c654a2bfe016ecddcc97b50b0/Source/Core/Core/HW/DVDInterface.cpp#L1327)):*
ditto

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3680)*

**Comment by lioncash** [comment]
Actually, is there any particular reason why both functions don't just have their respective parameters changed to take a u64 instead of just casting it in the first place?

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3680#-:-KBi3n8Rj0yCRafrXFom:157411002)*

**Comment by JosJuice** [comment]
We use u32 for the length in many places because it can't possibly be larger than that. This includes a parameter of DVDThread::StartRead, which ExecuteReadCommand uses, so I can't have a u64 there without casting it to u32. Changing the types in DVDThread just for this would be unnecessary. On the other hand, there are no problems with using a u64 in SimulateDiscReadTime, so I've changed that now.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3680#-:-KC0Au_Ys0lVn5CmUPtz:-2110927641)*

**Comment by Parlane** [comment]
ReBASE.

**Comment by JosJuice** [comment]
PR #4829 happened to fix this.

**Pull request closed without merging**
