### PR TITLE
Crypto cleanup

### PR DESCRIPTION
**Pull request by shuffle2**

### CODE REVIEW

**Comment by cobalt2727** [comment]
tests performed with an Ubuntu 18.04 aarch64 Oracle VM

with `cmake ..` I got the following:
```bash
[ 27%] Built target mbedtls
In file included from /home/ubuntu/test/dolphin/Source/Core/Common/Assert.h:9:0,
                 from /home/ubuntu/test/dolphin/Source/Core/Common/Arm64Emitter.h:12,
                 from /home/ubuntu/test/dolphin/Source/Core/Common/Arm64Emitter.cpp:4:
/home/ubuntu/test/dolphin/Source/Core/Common/Arm64Emitter.h: In member function ‘u32 Arm64Gen::ArithOption::GetData() const’:
/home/ubuntu/test/dolphin/Source/Core/Common/Assert.h:16:12: note: in expansion of macro ‘PanicYesNoFmtAssert’
       if (!PanicYesNoFmtAssert(_t_,                                                                \
            ^~~~~~~~~~~~~~~~~~~
/home/ubuntu/test/dolphin/Source/Core/Common/Assert.h:29:7: note: in expansion of macro ‘ASSERT_MSG’
       ASSERT_MSG(_t_, _a_, _fmt_, ##__VA_ARGS__);                                                  \
       ^~~~~~~~~~
/home/ubuntu/test/dolphin/Source/Core/Common/Arm64Emitter.h:495:7: note: in expansion of macro ‘DEBUG_ASSERT_MSG’
       DEBUG_ASSERT_MSG(DYNA_REC, false, "Invalid type in GetData");
       ^~~~~~~~~~~~~~~~
/home/ubuntu/test/dolphin/Source/Core/Common/Arm64Emitter.cpp: In member function ‘void Arm64Gen::ARM64FloatEmitter::EmitConvertScalarToInt(Arm64Gen::ARM64Reg, Arm64Gen::ARM64Reg, Arm64Gen::RoundingMode, bool)’:
/home/ubuntu/test/dolphin/Source/Core/Common/MsgHandler.h:88:20: error: invalid use of void expression
       ##__VA_ARGS__)
                    ^
/home/ubuntu/test/dolphin/Source/Core/Common/MsgHandler.h:129:3: note: in expansion of macro 
‘GenericAlertFmt’
   GenericAlertFmt(true, Common::MsgType::Warning, log_type, format, ##__VA_ARGS__)
   ^~~~~~~~~~~~~~~
/home/ubuntu/test/dolphin/Source/Core/Common/Assert.h:16:12: note: in expansion of macro ‘PanicYesNoFmtAssert’
       if (!PanicYesNoFmtAssert(_t_,                                                                \
            ^~~~~~~~~~~~~~~~~~~
/home/ubuntu/test/dolphin/Source/Core/Common/Assert.h:29:7: note: in expansion of macro ‘ASSERT_MSG’
       ASSERT_MSG(_t_, _a_, _fmt_, ##__VA_ARGS__);                                                  \
       ^~~~~~~~~~
/home/ubuntu/test/dolphin/Source/Core/Common/Arm64Emitter.cpp:2194:3: note: in expansion of macro ‘DEBUG_ASSERT_MSG’
   DEBUG_ASSERT_MSG(DYNA_REC, IsScalar(Rn), "fcvts: Rn must be floating point");
   ^~~~~~~~~~~~~~~~
Source/Core/Common/CMakeFiles/common.dir/build.make:789: recipe for target 'Source/Core/Common/CMakeFiles/common.dir/Arm64Emitter.cpp.o' failed
make[2]: *** [Source/Core/Common/CMakeFiles/common.dir/Arm64Emitter.cpp.o] Error 1
CMakeFiles/Makefile2:1873: recipe for target 'Source/Core/Common/CMakeFiles/common.dir/all' failed
make[1]: *** [Source/Core/Common/CMakeFiles/common.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2
```

seems to work out fine with my preferred method of running `cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_INIT="-static" -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11`

**Comment by cobalt2727** [comment]
It's worth noting I need to force GCC 11 on mainline already anyways for it to build, so this looks good to merge to me

**Comment by shuffle2** [comment]
ok. that error isn't related to any of the code i've been changing.

**Comment by cobalt2727** [comment]
At any rate, this branch works fine without the `-DCMAKE_CXX_FLAGS=-flax-vector-conversions` parameter, which I needed on mainline

**Pull request merged**
