### PR TITLE
CoreTiming: Drop ProcessFifoWaitEvents.

### PR DESCRIPTION
**Pull request by degasus**
globalTimer is only written in Advance, so this function should have no function.

Never ever in 5.0.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3716)

### CODE REVIEW

**Comment by JMC47** [comment]
I guess I should test this.  Any idea what it could effect?

**Comment by phire** [comment]
:lgtm: 

I agree that this is dead code (or code which could only possibly be executed on a race condition)

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3716#-:-KLBBRJPzY1lTRxLZWP6:494280206)*

**Comment by Nucleoprotein** [comment]
This PR broke Eternal Darkness, created issue about this https://bugs.dolphin-emu.org/issues/9706

**Comment by phire** [comment]
Interesting.

**Comment by Nucleoprotein** [comment]
Yep, but build-bot does not have revs 70 and 71 so maybe I'm wrong.

**Comment by phire** [comment]
Revs 70 and 71 don't really exist (they represent the two commits in this PR)

**Comment by Nucleoprotein** [comment]
Ehh, I did not know about that, so definitely problem is in this PR.

**Pull request merged**
