### PR TITLE
Set the default audio backend to be Pulseaudio in Linux.

### PR DESCRIPTION
**Pull request by Sonicadvance1**
It's about time.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3462)

### CODE REVIEW

**Comment by RisingFog** [comment]
LGTM

**Comment by delroth** [comment]
So... I don't see the point. Why not PA through ALSA as the default?

**Comment by degasus** [comment]
PA is the best linux backend right now, but alsa has a higher availbility.

**Comment by sepalani** [comment]
Then, why not put them both? Set PulseAudio by default and if it doesn't exist use ALSA instead.

**Comment by Sonicadvance1** [comment]
Responding to delroth's comment on this.
PA through Alsa has a fun issue that you can't on the fly switch between multiple audio output devices. (At least in my setup and my audio arrangement).
I've also hit multiple issues where PA has issues outputting audio correctly from Alsa applications, not sure wtf that is about.

**Comment by degasus** [comment]
Code is fine, so how shall we continue on discussion which one to select? Maybe PA if we have a fallback if PA is not available?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3462#-:-K8nAw31f7aVJOl45jpn:-874839147)*

**Comment by delroth** [comment]
I'm fine with PA as default if we auto-fallback when PA is unavailable.

**Pull request closed without merging**
