### PR TITLE
Gameini updates.

### PR DESCRIPTION
**Pull request by Linktothepast**
Updates for Sonic Adventure 2 Battle, Surf's Up, Drawn to Life The Next
Chapter, Boogie, Boogie SuperStar, Quantum of Solace, Tiger Woods PGA
Tour 08, Call of Duty: Black Ops.
Fixes issues 9123, 9191, 9204, 9205, 9206, 9050, 9183.

### CODE REVIEW

**Comment by JosJuice** [comment]
Looks good in general, but could you also take care of this one? https://bugs.dolphin-emu.org/issues/9177

**Comment by Linktothepast** [comment]
Sure if there isn't anything else left to be added/chaged i will push it.

**Comment by shellashock** [comment]
GC2E9G - Conflict: Desert Storm II (NSTC version at least), requires Real XFB to display cinematics/videos. Been reported before but neer acted upon. Prolly a good idea to include this considering there have been reports on the wiki since at least 4.0.

**Comment by JosJuice** [comment]
Using real XFB will force the resolution to native in the entire game, so forcing it on for the entire game might not be desirable. The EmulationIssues text should be updated, though.

**Comment by Linktothepast** [comment]
Those can be fixed at one fell swoop when hybrid xfb is done, and it is good to have them marked in the meanwhile. I will see to it.

**Comment by Linktothepast** [comment]
Ok, done. Also fixes issue 9177.

**Comment by JosJuice** [comment]
LGTM.

**Pull request merged**
