### PR TITLE
Moves AlertDialogs imports to AndroidX and fix tabs background color

### PR DESCRIPTION
**Pull request by rafaeltoledo**
Screenshot_1574449687
Screenshot_1574449724

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by Simonx22** [comment]
Doesn't seem to work for me on Android 9:

image

**Comment by Simonx22** [comment]
Two things I noticed:
- the bar on the first startup is white instead of blue
- the animation when tapping the icons doesn't work

Play Store Release:

play_store_doc_2019-11-22_19-59


This PR:

pr_doc_2019-11-22_19-59-50

**Comment by rafaeltoledo** [comment]
@Simonx22 I've updated the theme for the tabs to keep the previous behavior, based on the [docs](https://github.com/material-components/material-components-android/blob/master/docs/components/TabLayout.md#legacy-material-style)

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
