### PR TITLE
DolphinWX: Stop using XPM images

### PR DESCRIPTION
**Pull request by JosJuice**
Using the XPM format for images has become a maintenance problem because people don't know how to create them. This commit removes all XPM images and all C files that contain PNG images. DolphinWX now uses the PNGs in the Resources folder instead, just like DolphinQt and DolphinQt2 do.

This is a WIP for now, because the PNG platform icons are 50 pixels wide and DolphinWX expects 32 pixels, which means they get cut off. I think @MaJoRoesch wanted to change the PNG icons anyway...?

With this PR, DolphinWX does not require some images to be padded to 96x32 anymore. This means that it's possible to remove the padding in the PNG files, and any potential code in DolphinQt/DolphinQt2 that was made to accommodate it can be removed. @spxtr, is there any such code in DolphinQt2?

### CODE REVIEW

**Comment by spxtr** [comment]
We have to cut platform and rating icons. Once the icons are fixed, remove [these](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/DolphinQt2/GameList/GameList.cpp#L43-L47) lines. Flag icons are fine, the line setting their width can be removed immediately.

**Comment by JosJuice** [comment]
There is currently one file left in the DolphinWX/resources folder, which is Dolphin.icns. Is it still needed? It seems like DolphinQt and DolphinQt2 use a file named Dolphin.icns, but I don't know why the file they use would be in DolphinWX. There's another Dolphin.icns in DolphinQt/Resources.

**Comment by JosJuice** [comment]
@spxtr Okay, thanks. I'll wait with fixing it until I get a response from MaJoR.

**Comment by MaJoRoesch** [comment]
Talk with me about this on IRC. I would love to work on this!

**Comment by BhaaLseN** [comment]
.icns is commonly a Mac icon; not sure if/where/how DWx uses it.

**Comment by aserna3** [comment]
Is this ready?

**Comment by JosJuice** [comment]
MaJoR's new icons have been added, so this PR is ready for reviewing/merging.

**Comment by aserna3** [comment]
yay no more wxGetBitmapFromMemory

LGTM

**Comment by JosJuice** [comment]
degasus asked on IRC about what the size difference is.

pr-3357-dolphin-latest-x64:
Dolphin.exe: 13 662 720 bytes
Sys: 2 375 359 bytes

dolphin-master-4.0-8572-x64:
Dolphin.exe: 13 768 192 bytes
Sys: 2 347 634 bytes

In total, this PR is 77 747 bytes smaller when uncompressed. Keep in mind that master only has 1x platform icons, while this PR also has 2x and 4x versions.

**Comment by ZephyrSurfer** [comment]
Can you look at https://bugs.dolphin-emu.org/issues/7793

**Comment by JosJuice** [comment]
That's not related to this at all.

**Comment by spxtr** [comment]
This looks really nice :)

**Pull request merged**
