### PR TITLE
WIP: Android display cutout setting

### PR DESCRIPTION
**Pull request by simonmarien**
[Issue #12483](https://bugs.dolphin-emu.org/issues/12483)
Black bar at the top of the display on android.
The app does in fact not support the cutout display.
Make an option in the graphics advanced settings to enable cutout support.

### CODE REVIEW

**Comment by MayImilae** [comment]
Why are you also adding it to Qt?

**Comment by mbc07** [comment]
Isn't the notch a thing now on the newer MacBooks? From that perspective it might be worth adding this to Qt too...

**Comment by JosJuice** [comment]
Does the implementation in this PR actually work for the MacBook notch, though?

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by MayImilae** [comment]
I have one of those macbooks and can test it, if it will build. However, it probably will not work. macOS does NOT want the notch to eat into content, and does not allow it to happen under any circumstances. In fullscreen apps for example, it just turns the entire top most of the display black as a big bezel rather than block content with the notch. I do not believe an application is able to override this at all. I'm all for this, and I don't mind the notch on my laptop at all because it is handled so well. The menu bar lives up there and _that's it_.

I do not think this is appropriate in Qt. Notches are not common on desktop OSes (thank goodness) so there's no standardization like what the android part of this PR takes advantage of. It is highly doubtful that we could take up notch handling across macOS, Windows, and all the Linux DEs. And frankly, I don't think we should.

**Comment by JosJuice** [comment]
Closing in favor of PR #10552.

**Pull request closed without merging**
