### PR TITLE
DualShockUDPClient: add motors for rumble

### PR DESCRIPTION
**Pull request by breeze2**
[cemuhook-protocol](https://github.com/v1993/cemuhook-protocol) has been updated, two unofficial message types about rumble were added, so I implemented them.
By the way, I am developing a mobile application about DSU Server, I can vibrate the phone to simulate a rumble.

### CODE REVIEW

**Comment by iwubcode** [comment]
While it might work, I'm not sure how I feel about tacking on additional message types like this to the existing protocol.  I've commented on the cemuhook-protocol about how version should have been bumped for that change.

**Comment by Sam-Belliveau** [comment]
@dolphin-emu-bot rebuild

**Comment by breeze2** [comment]
As for bumping version, it does break compatibility.

Let's look at the implementation of Dolphin DSU Client:

E6640365-AC65-4A40-A8F6-A72D08EC74B9


```cpp
if (m_message.header.protocol_version > CEMUHOOK_PROTOCOL_VERSION)
    return std::nullopt;
```

The Dolphin DSU Client does not handle the messages from a higher version DSU Server. All features of the higher version DSU Server do not work properly with current or previous Dolphin (version <= 5.0-18515), including the original features.

But what we expect should be that the previous version of Dolphin gets the original features, and the new version of Dolphin gets more features.
This problem also exists in other clients and servers. So I think the version number should not be bumped now, maybe later.

**Comment by iwubcode** [comment]
I said most of my thoughts on the [cemuhook PR](https://github.com/v1993/cemuhook-protocol/pull/7).

To reiterate, adding messages without rolling the version feels wrong to me.  I would expect there to be incompatibilities and that the implementation + the version change would be implemented when new features are formalized in the cemuhook specification.  Whether that actually happens, will be up to the cemuhook protocol maintainer(s).

**Comment by v1993** [comment]
This queries motor count only once, which might fail due to unreliable nature of UDP. Also not sure why call those *virtual* motors, since they are often going to be perfectly real.

**Review by mbc07 — CHANGES_REQUESTED** [review]
I'm strongly against merging this to Dolphin without a bump to the protocol version. 

This protocol nowadays is used across several projects, not just Dolphin, if we don't do things correctly now (like bumping the protocol version since additions were made -- like any sane, versioned protocol would do), it'll become a mess in the future.

I would rather make breaking changes now, while (AFAICT) no existing DSU Servers has adopted the new rumble extension yet, than later when DSU Servers would have potentially adopted the new message types with the old protocol version and becomes unpredictable in how they'll interact with DSU Clients not updated to handle the new rumble extension...

**Comment by lioncash** [comment]
Given the author's refusal (based on what I've read so far) to Just Increase The Version like any normal spec or protocol out there (for the record, I agree with increasing the version), should this just be closed, considering this has been sitting for 3 weeks with no input or discussion?

**Comment by jkcoxson** [comment]
What would the path forward be for this PR? https://github.com/v1993/cemuhook-protocol/pull/7 was merged without bumping the protocol version. Would Dolphin merge this as-is, or would you prefer a new PR with protocol version 1002?

This is blocking for BLE drivers (Switch 2 controllers) on MacOS that can only expose DSU.

**Comment by v1993** [comment]
Fwiw, I'd be more than happy to transfer my protocol repository either to dolphin-emu or to a new github org with r/w access for interested people. I never intended my document to become a source of authority - merely an RE effort - and if it has to be one then it's probably best to have someone else hold power over it; preferably a group of people across the DSU ecosystem (i.e. both client and server sides).

On the other hand, given that a version bump is going to require updating code all across the ecosystem either way, I believe this is an opportunity to rework the protocol in general - e.g to make it a little more generic than the DS4-centric current version. Additionally, giving it a new name would make the upgrade less confusing for end users who'd otherwise have to live with sudden incompatibilities vaguely reflected in release dates.

**Comment by jordan-woyak** [comment]
> Fwiw, I'd be more than happy to transfer my protocol repository either to dolphin-emu or to a new github org with r/w access for interested people. I never intended my document to become a source of authority - merely an RE effort - and if it has to be one then it's probably best to have someone else hold power over it; preferably a group of people across the DSU ecosystem (i.e. both client and server sides).
> 
> On the other hand, given that a version bump is going to require updating code all across the ecosystem either way, I believe this is an opportunity to rework the protocol in general - e.g to make it a little more generic than the DS4-centric current version. Additionally, giving it a new name would make the upgrade less confusing for end users who'd otherwise have to live with sudden incompatibilities vaguely reflected in release dates.

I'd still vote for increasing the protocol version at this time. If clients explode we can add a version selector or tell them to fix their version handling.

I think making the protocol more generic is also a good idea for the future, and there can be another version bump then.

**Pull request closed without merging**
