### PR TITLE
Qt: Move CPU Emulation Engine options to the Advanced tab

### PR DESCRIPTION
**Pull request by ethteck**
Solves https://bugs.dolphin-emu.org/issues/11743

I changed the CPU Emulation options to a combobox selection and moved it over to the Advanced tab.

### CODE REVIEW

**Comment by MayImilae** [comment]
Screenshot please!

**Comment by ethteck** [comment]
Sure! Here's the new General tab:
General tab

And the Advanced tab:
Advanced tab

**Comment by MayImilae** [comment]
Works well! Still though, there definitely needs to be more space between the CPU Emulation Engine and the CPU Clock Override, mainly because CPU Engine is SO much smaller than the enormous Clock Override.

So it might be best to have a CPU Options group and a Clock Override group.

**Comment by ethteck** [comment]
Okay, I'll work on that tomorrow. While we're at it, is the "Enable Dual Core" option in the General tab also suitable to go under "CPU Options"?

**Comment by MayImilae** [comment]
Probably best to leave that as is for now. Moving Dual Core will spur some discussion.

**Comment by JosJuice** [comment]
I think dual core should be on the General tab like it currently is. It's something you have a lot more reason to adjust than the CPU emulation engine.

**Comment by BhaaLseN** [comment]
Please rebase your branch instead of merging (`git fetch origin; git rebase origin/master move-cpu-emulation-engine-options` - replace `origin` with the name of the dolphin remote). This also gives you the option of [combining commits](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing) if you use `git rebase -i` instead.
Note that you'll have to force-push (`git push -f`) your changes afterwards.

**Comment by Helios747** [comment]
If May is happy with this layout (I am), I see no reason to hold this back. Would be nice if that third commit could be squashed into the first or second. First two commits are fine.

**Comment by MayImilae** [comment]
LGTM!

**Comment by ethteck** [comment]
I went ahead and squashed the third commit into the second.

**Comment by Helios747** [comment]
Thanks!

**Pull request merged**
