### PR TITLE
Add info. about the Building process of the Qt Gui in the README

### PR DESCRIPTION
**Pull request by joaoh1**
As the title says, This PR adds information about the Building process of the Qt Client in the README file.
This would be useful for developers that wants to contribute on the Qt Client project.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4327)

### CODE REVIEW

**Comment by JosJuice** [comment]
We typically don't call it "Qt Client". Maybe "Qt GUI" would be better? Or should we call it by its project name, DolphinQt2?

You should probably note that the Externals/Qt/ directory is a submodule that can be pulled to obtain the necessary files.

**Comment by lioncash** [comment]
We have a submodule that automatically sets that up. You run `git submodule init` and then `git submodule update` or use `git clone --recursive https://github.com/dolphin-emu/dolphin.git` to clone both dolphin and any submodules.

**Comment by joaoh1** [comment]
I didn't noticied the submodule before, going to update the README

**Comment by leoetlino** [comment]
You may want squash your two commits to keep things clean.

By the way, GitHub's web editor is very limited; I suggest using command-line git directly instead.

**Comment by JosJuice** [comment]
"Install" isn't a good word for what needs to be done with the submodule.

**Comment by joaoh1** [comment]
i tried with commands, but it doesn't worked, i accidentally pressed Update branch button, going to create a another PR.

**Pull request closed without merging**
