### PR TITLE
Make title column toggleable (Issue #9952)

### PR DESCRIPTION
**Pull request by spycrab**
Also see [Issue #9952](https://bugs.dolphin-emu.org/issues/9952).

### CODE REVIEW

**Comment by sepalani** [comment]
Are all cases covered in ```CGameListCtrl::AutomaticColumnWidth()```? I can only see:
 - Title & Maker & Filename
 - ~Title & Maker~
 - ~Title & Filename~
 - ~Title~
 - Maker & Filename
 - Maker
 - Filename
 - Dummy

Or is there a reason not to cover them?

I'd rather see another way of handling them such as looping over a container but it might deserve its own PR I guess.

**Comment by spycrab** [comment]
@sepalani Oops, looks like a forgot a few in the beginning. I think I've got them all covered now though.

I agree that the way it is implemented is not very prettty or functional. Might create a seperate PR, once this one is merged.

**Comment by sepalani** [comment]
@dolphin-emu-bot rebuild

**Comment by sepalani** [comment]
Not sure if it's a good idea to mess with the ```COLUMN_DUMMY``` column.

Regardless, LGTM.

**Pull request merged**
