### PR TITLE
windows{wx/qt}: opt in to dpi/scaling options where available

### PR DESCRIPTION
**Pull request by shuffle2**
Untested as I don't use scaling. Would be cool if someone who did checked it out.  
Based on https://msdn.microsoft.com/en-us/library/windows/desktop/aa374191.aspx

### CODE REVIEW

**Comment by mimimi085181** [comment]
I have 125% scaling enabled in my windows 7. Neither wx nor qt look any different. Is this supposed to make the windows and icons bigger? Or just use higher resolution images?

**Comment by shuffle2** [comment]
Well, I blinded did this just because the .manifest files were there - I assumed the settings were useful :D
It seems dolphin _doesn't_ actually support high DPI (at least in the sense windows means): Windows sends the app events which should tell the app to adjust to new dpi settings (the scaling used on initial app load, but also possibly the new dpi setting if moved to a differently-scaled monitor, or if the user changes the scaling setting on the fly). It seems all dolphin does for "high dpi" is have multiple .png files which are of different resolutions, and it decides which to use at initialization time.

Perhaps this is something we can revisit with Qt, which probably has proper support. In that case it would be nicer to have different (scalable) image files (cc @MayImilae ).

@Orphis any idea why the manifest files were originally added? It seems they don't really do anything?

p.s. in addition to above link, there is also https://msdn.microsoft.com/en-us/library/windows/desktop/dn280512.aspx

**Comment by mimimi085181** [comment]
Why not just add a scaling setting? This would fix the problem, and you wouldn't have to figure out how to read the scaling value on 5 different OSes.

**Comment by shuffle2** [comment]
@mimimi085181 that sounds horrible from a UX point of view? How many other apps do you know of that have that?

**Comment by mimimi085181** [comment]
Well, i kinda like the size of the GUI right now, and if it was scaled, i might wish to be able to set to back to 100%.

**Comment by shuffle2** [comment]
Windows allows you to do that.

**Comment by MayImilae** [comment]
Yeeaaa, I'd prefer to leave that to the OS...

**Comment by Orphis** [comment]
No idea, that was before my time. They were already there.

**Comment by shuffle2** [comment]
Well it seems the manifest for DPI awareness was added by #4880 .  
So, @ligfx did you test this? AFAICT dolphin only supports "system" dpi awareness, which is essentially the default setting, anyways. Dolphin does not appear to actually be DPI-aware at all, and I don't the the GDI scaling really applies to Dolphin, either.

**Comment by ligfx** [comment]
@shuffle2 I'd like to think I tested with DolphinWX (though I don't remember), but I definitely didn't with DolphinQt2, if that's what you're asking! Does removing the manifest file not affect anything?

**Comment by Starsam80** [comment]
Tested on Windows 10 (version 10.0.14393) with a 4k monitor set to 200% scaling, and with the latest version of this PR it works still works

**Pull request closed without merging**
