### PR TITLE
[Feedback Wanted] Android: IR pointer improvements

### PR DESCRIPTION
**Pull request by Ebola16**
Fixes https://bugs.dolphin-emu.org/issues/12307 and should be the final IR pointer PR.
This PR combined with #9209 should significantly improve the IR pointer.

### CODE REVIEW

**Comment by Ebola16** [comment]
Updated TODO

**Comment by Ebola16** [comment]
I think this properly fixes the IR pointer now but I'm still not 100% sure it's the best solution. When testing, be sure to use the updated default values in #9209.

**Comment by JosJuice** [comment]
This change doesn't make much sense to me. I believe #9215 is the proper fix.

**Comment by Ebola16** [comment]
Yeah, the values I used worked on my phone and manipulating the buffer should be device agnostic but I had a feeling there was a better way to accomplish what I wanted. #9215 is less hacky so let's go with that.

**Pull request closed without merging**
