### PR TITLE
Memory Card Path handling improvements.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
Does a few things:

- Unify handling of raw memory card path. I've wanted to do this for a while, since several places in the code handled this differently and you could get some weird results where eg. the GUI thought a different memory card was inserted compared to the actual emulation. This should unify it, as best as possible anyway.
- GameCube Config window now actually shows the selected memory card path.
- GCI Folder paths are now configurable.

The last one might be a bit unintuitive... I didn't want to use the existing GCI folder override option because it forces all regions to use the same folder, which is not great if you're eg. mixing JP and US games. So this is what I came up with. Feel free to discuss this with me.

Implements or fixes:
https://bugs.dolphin-emu.org/issues/12169 (partial)
https://bugs.dolphin-emu.org/issues/10442

### CODE REVIEW

**Comment by mbc07** [comment]
Hmm, the GUI looks a bit odd (especially the input box suddenly appearing/disappearing depending of what you select in the Slot A/B dropdowns), but I can't think of a better approach. Perhaps it would be less jarring to always show the input box and just set its state (disabled/enabled) based on what the user selected in the dropdown?

**Comment by JMC47** [comment]
Seemed to work fine, even with things like the Advance Game Port.

**Comment by AdmiralCurtiss** [comment]
@mbc07 
grafik

ymmv whether this is better or worse, I can see either.

**Comment by AdmiralCurtiss** [comment]
Maybe more clear like this:
grafik

**Comment by Miksel12** [comment]
Currently on master, you can select which folder you want to use for Memory Cards and for the AGP by clicking on the three dotted button. Couldn't the same be done for GCI folders?

**Comment by AdmiralCurtiss** [comment]
Yes, and that's still the case, but while I was here I wanted to address a GUI deficiency that you can't actually see what those paths are currently set to. I can move that to a separate PR if people feel it confuses this one.

**Comment by Miksel12** [comment]
Ah ok, in that case maybe it could be brought in line with the rest of the path options where the three dotted button is placed behind the path name.

**Comment by AdmiralCurtiss** [comment]
Mhm, yeah that's probably better.

**Comment by AdmiralCurtiss** [comment]
grafik

?

**Comment by Miksel12** [comment]
That makes more sense, at least for me. Probably best to remove the buttons besides the dropdowns since they are non functional now.

**Comment by AdmiralCurtiss** [comment]
It's still used for the Microphone button.

**Comment by mbc07** [comment]
> grafik
> 
> ?

I'm sold on this one If you could also set the state of the input box and the accompanying button to enabled/disabled accordingly to what's selected on the Slot A/B dropdowns (like in one of the previous screenshots you sent)...

**Comment by JMC47** [comment]
...is it really worth listing AGP Cartridge Path on there?  This really seems more cluttered to me anyway.  Why can't it just be the one selected below it?

Honestly I'm just laughing because the AGP is there, and it doesn't even run right in the latest builds without serious shenanigans.

**Comment by AdmiralCurtiss** [comment]
I mean, you're not *wrong*, but it'd be odd to treat the AGP path differently than the other two paths. Only showing the selected thing is what I had originally, we can certainly revert to that if you think that's better. I don't really mind either way.

**Comment by mbc07** [comment]
Ok, what about having only one input box and accompanying button below the Slot A/B dropdowns that's always visible but dynamically changing it to the corresponding device? My only nitpick with the initial design was the input box appearing/disappearing out of nowhere...

(at this point we should probably ping @MayImilae as well just in case she hasn't seen this PR yet)

**Comment by Techjar** [comment]
I agree we should only be showing the text field for the currently selected device (and yes, no field if the device is none or doesn't have a path). Looks too cluttered as you have it right now.

**Comment by AdmiralCurtiss** [comment]
-> #11236

**Pull request closed without merging**
