### PR TITLE
[WIP] TAS dialog: Toggle analog inputs between TAS and regular input

### PR DESCRIPTION
**Pull request by RisingFog**
Rebase of #3609 .

I've been considering an alternative UI element instead of using a lock/unlock bitmap toggle. Possibly using a checkbox instead. Would like some comments on this to see what's needed.

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4265)

### CODE REVIEW

**Comment by shuffle2** [comment]
put WIP in the title as this PR appears to have some unresolved things.

**Comment by RisingFog** [comment]
@MaJoRoesch thoughts on what to do with this UI element?

**Comment by dragonbane0** [comment]
Isn't this a regression? On 4.0-5371 it worked exactly as you would expect. When the controller is not used (stick is in idle position) the TAS input overrides it and works properly. Unless the change back then was required to fix something else I don't see why crutches like a locking button should be necessary when it worked just fine without before

**Comment by RisingFog** [comment]
WX is now deprecated, so I'm closing this.

**Pull request closed without merging**
