### PR TITLE
Audio: Fix subwoofer output in software 5.1 decoding

### PR DESCRIPTION
**Pull request by adamdmoss**
The FIR filter was only using the first sample of each input packet.
Tested with Eternal Darkness and the new Pulse 5.1 backend (though OpenAL will also see the same benefits) - much improved LFE.

### CODE REVIEW

**Comment by adamdmoss** [comment]
Added a second possibly more controversial 'fix' which uses all channels to calculate the bass, not just front-left and front-right.  FWIW the bass sounds 'clearer' and the upstream HRTF code also does this.

**Comment by skidau** [comment]
@dolphin-emu-bot rebuild

**Comment by skidau** [comment]
Please fix the warning found:
https://buildbot.dolphin-emu.org/builders/pr-win-x64/builds/536/steps/compile/logs/warnings%20%282%29

**Comment by adamdmoss** [comment]
Done, I believe.

**Comment by skidau** [comment]
@dolphin-emu-bot rebuild

**Comment by skidau** [comment]
The subwoofer sounds too boomy to me now, drowning out the rest of the audio.  I think this commit was a bit much and should be changed back to how it was: 7580069deaf0455b9dc0fe4a576b5ad5cbd8120b

https://github.com/adamdmoss/dolphin/commit/7580069deaf0455b9dc0fe4a576b5ad5cbd8120b

**Comment by adamdmoss** [comment]
@skidau Is there a subwoofer gain factor that sounds better to you, say 1/2 volume?  I think I was too generous leaving the ampliture divisor as 2.0 even with the extra channels mixed in, /4.0-6.0 might be more appropriate, though I don't think going back to only using the LF and RF outputs is the fix - much of the contributing power has already been taken out of those and put into CF.

**Comment by adamdmoss** [comment]
@skidau  That said, it sounds okay on my set-up, only as boomy as movie 5.1 mixes, but I don't have a physical Pro Logic II decoder to compare officially-decoded real Wii output with.

**Comment by skidau** [comment]
The games which were affected most seem to be the Star Wars games by LucasArts (games on both the GC and Wii).  They are at a level where the dialogue can't be heard.  I'll try a 4.0 to 6.0 divisor and let you know if that helps.

**Comment by adamdmoss** [comment]
Thanks.  I've taken a look at what other software DPL2 decoders do, but none of them generate a subwoofer channel, except the HRTF decoder upstream from Dolphin's DPL2 decoder implementation.

**Comment by skidau** [comment]
No matter the divisor, the Star Wars opening scroller booms at the beginning.  I tried changing it back to how it was and that didn't help either.  Guess we'll chalk this down to the game(s).

**Comment by adamdmoss** [comment]
@skidau Curious - does the divisor not affect the subwoofer volume at all?  If so, that'd probably indicate either that Dolphin, Pulse, or OpenAL are using the wrong channel map (the wrong channel is going to the subwoofer channel), the system speaker layout is wrong, or possibly a redundant second Dolby decode is happening downstream from Dolphin (external amp, possibly sound card, etc).

Does Rogue Squadron show the problem?

**Comment by adamdmoss** [comment]
@skidau (Is this the OpenAL backend?)

**Comment by skidau** [comment]
Yes, the OpenAL backend with DSP LLE.  Rogue Leader isn't as pronounced.  Nor is Rebel Strike.  Applying #1882, Clone Wars seems to be bass heavy as is Star Wars Forced Unleashed II.  The channel map seems to be ok, because the audio test in Rogue Leader seems to work more or less ok.

**Comment by oshepherd** [comment]
Why is Dolphin producing LFE output from a Dolby Surround matrix encoded source? Dolby Surround does not contain LFE.

A Dolby Surround encoder discards the LFE channel (LFE 0dB FS = 10db FS for every other channel, that is 10dB over digital clipping, so incorporating LFE is impossible. Besides, LFE is explicitly and only for bombastic subwoofer effects and in AC3 is band limited to 120Hz). A DPLII decoder consequently does not produce LFE, because there is none in the DPLII audio.

Go and try it with an actual DPLII decoder: feed it something DPLII encoded, and nothing will come out of the LFE channel (Easiest way to try this is to turn off bass management on an AV receiver, in which case you will find your subwoofer doing nothing) 

Bass management shouldn't be Dolphin's job - people should configure their system appropriately. All sensible OSes have a "bass management" feature for when they're dealing with a discrete 5.1 system with no integral processing (on Windows this is the "Bass management" audio enhancement, reachable from the audio device's control panel).

If both Dolphin and the system attempt to do bass management, the end result is going to be terrible; especially since Dolphin doesn't high pass filter the surround channels, so on the systems of people like myself (who have AV receivers with bass management, etc, hooked up to their computers), all of that bass is going to get redirected **twice**.

If you're going to implement bass management (for people who cannot enable it in their OS or outboard equipment for whatever reason), it should be a completely separate option, which low passes the subwoofer channel and high passes the main channels (for their protection).

**Comment by adamdmoss** [comment]
To clarify, we get a DPL2 mix in, not Dolby Surround.  The decoder derives the LFE from a delayed 125Hz low-pass.  Examining the implementation, these frequencies are left in the surround channels too - I don't know if this is intentional but it doesn't seem right (the DPL2 module seems to have been an HRTF implementation first and then cut down into a DPL2 decoder as an afterthought).  The fix we're discussing puts the LFE result into the LFE channel instead of there being random crap there, but I suspect it'd be better if we just output the 5.0 instead of the fakey .1 on top and let the OS etc derive the .1 downstream.

**Comment by oshepherd** [comment]
Dolby ProLogic and ProLogic II are both decoders for Dolby Surround mixes (to clarify - Dolby Surround is the name for the encoder and for the earliest decoder; DPL and DPLII are refinements of that)

Correct behavior is to just output a 5 channel mix and let downstream equipment do bass management . Even if Dolphin did high-pass the surround channels, it doesn't know the capabilities of the user's surround system - different crossover points for the front and surround speakers aren't unheard of. There's also the matter that a crossover appropriate for most home equipment is liable to put some content above the 120Hz band limit of AC3, and therefore negatively affect anybody using S/PDIF output encoded with AC3 to drive a surround sound system.

**Comment by adamdmoss** [comment]
See https://github.com/dolphin-emu/dolphin/pull/1917

**Pull request merged**
