### PR TITLE
Fix a hang with the GC Adapter

### PR DESCRIPTION
**Pull request by mathieui**
Fix for https://bugs.dolphin-emu.org/issues/9502

The fix made for netplay in 3df4b09a9428fe08a8ca caused the behavior
introduced in 49410576e to provoke hangs, because it relied on both
functions having to handle the error cause. Since the error handling is
not available in the SI device anymore, this created an issue, so I
remove that handling from the Adapter code as well.

The behavior will need to be added back for correctness, so I am leaving a
note about it.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3821)

### CODE REVIEW

**Comment by JMC47** [comment]
LGTM performance wise.

**Comment by phire** [comment]
LGTM. The only thing this affects is automatic plug/unplug detection of the GC adapter, which while nice to have is not important.

<details><summary><i>Previously, JMC47 wrote…</i></summary>
> LGTM performance wise.</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3821#-:-KHLa-Lsc1fPh9spxD3A:2025570844)*

**Comment by mimimi085181** [comment]
What was the result of the discussion about this and reverting pr https://github.com/dolphin-emu/dolphin/pull/3797 for non netplay?

I think it would be best to make non netplay work as before, and only restrict the capabilities for netplay, with a todo comment to add it for netplay as well.

**Comment by mimimi085181** [comment]
Thanks for implementing this. Now we need new test results and a review.

@phire: Do you want to take another look at this?

**Comment by JMC47** [comment]
This still appears to work correctly.

**Comment by phire** [comment]
Get rid of the code duplication.

The only diffrence between `CSIDevice_GCAdapter::RunBuffer` and `CSIDevice_GCController::RunBuffer` is the 7 lines of code which make GCAdapter return a different result that's not connected.

Either make GCAdaper call the GCController version of the code after doing some checks, or break it out into another function (only implemented in the GCController class)

**Comment by mimimi085181** [comment]
Reviewed 1 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3821)*

**Comment by phire** [comment]
New code looks good to me too.

**Comment by lioncash** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[Source/Core/Core/HW/SI_DeviceGCAdapter.cpp, line 37 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3821#-KHanEunQ2nbwBLDhNRl:-KHanEuoXR7-m-WTTHjH:-1404818020) ([raw file](https://github.com/dolphin-emu/dolphin/blob/47ed47ea526f672fdffa2b068b65805a3c367c70/Source/Core/Core/HW/SI_DeviceGCAdapter.cpp#L37)):*
> ```cpp
> }
> 
> int CSIDevice_GCAdapter::RunBuffer(u8* _pBuffer, int _iLength)
> ```

```cpp
u8* buffer, int length
```

---

*[Source/Core/Core/HW/SI_DeviceGCAdapter.cpp, line 50 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3821#-KHanNHIk5qlDtPpWrj3:-KHanNHJBVAt3oso8Fdo:1417249252) ([raw file](https://github.com/dolphin-emu/dolphin/blob/47ed47ea526f672fdffa2b068b65805a3c367c70/Source/Core/Core/HW/SI_DeviceGCAdapter.cpp#L50)):*
> ```cpp
> 		if (!GCAdapter::DeviceConnected(ISIDevice::m_iDeviceNumber))
> 		{
> 			reinterpret_cast<u32*>(_pBuffer)[0] = SI_NONE;
> ```

This should be done as a memcpy. This is undefined behavior (I know we do this in other places, but we really shouldn't).

---

*[Source/Core/Core/HW/SI_DeviceGCAdapter.h, line 18 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3821#-KHan2rjxdjKwxnmakc-:-KHan2rkK3Vy_rAOnHFf:-728849508) ([raw file](https://github.com/dolphin-emu/dolphin/blob/47ed47ea526f672fdffa2b068b65805a3c367c70/Source/Core/Core/HW/SI_DeviceGCAdapter.h#L18)):*
> ```objc
> 	GCPadStatus GetPadStatus() override;
> 	int RunBuffer(u8* _pBuffer, int _iLength) override;
> };
> ```

```cpp
int RunBuffer(u8* buffer, int length);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3821)*

**Comment by lioncash** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/Core/HW/SI_DeviceGCAdapter.h, line 18 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3821#-KHan2rjxdjKwxnmakc-:-KHao0r8v0D5YaBlbrps:-1360153647) ([raw file](https://github.com/dolphin-emu/dolphin/blob/47ed47ea526f672fdffa2b068b65805a3c367c70/Source/Core/Core/HW/SI_DeviceGCAdapter.h#L18)):*
<details><summary><i>Previously, lioncash (Mathew Maidment) wrote…</i></summary>
> ```cpp
> int RunBuffer(u8* buffer, int length);
> ```</details>
whoops, left the override out of that by accident.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3821)*

**Comment by mathieui** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/Core/HW/SI_DeviceGCAdapter.cpp, line 37 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3821#-KHanEunQ2nbwBLDhNRl:-KHasdxgJuXHTEA_WjGZ:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/47ed47ea526f672fdffa2b068b65805a3c367c70/Source/Core/Core/HW/SI_DeviceGCAdapter.cpp#L37)):*
<details><summary><i>Previously, lioncash (Mathew Maidment) wrote…</i></summary>
> ```cpp
> u8* buffer, int length
> ```</details>
Done.

---

*[Source/Core/Core/HW/SI_DeviceGCAdapter.cpp, line 50 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3821#-KHanNHIk5qlDtPpWrj3:-KHasfwglqOOP028rbi4:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/47ed47ea526f672fdffa2b068b65805a3c367c70/Source/Core/Core/HW/SI_DeviceGCAdapter.cpp#L50)):*
<details><summary><i>Previously, lioncash (Mathew Maidment) wrote…</i></summary>
> This should be done as a memcpy. This is undefined behavior (I know we do this in other places, but we really shouldn't).</details>
Done.

---

*[Source/Core/Core/HW/SI_DeviceGCAdapter.h, line 18 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3821#-KHan2rjxdjKwxnmakc-:-KHasiZVrDo9CFz1sWtG:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/47ed47ea526f672fdffa2b068b65805a3c367c70/Source/Core/Core/HW/SI_DeviceGCAdapter.h#L18)):*
<details><summary><i>Previously, lioncash (Mathew Maidment) wrote…</i></summary>
> whoops, left the override out of that by accident.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3821)*

**Comment by JMC47** [comment]
Seems to fix the issue for me in Melee.

**Comment by lioncash** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3821)*

**Pull request merged**
