### PR TITLE
RFC: Enable sustained performance mode on Android

### PR DESCRIPTION
**Pull request by JonnyH**
Is this useful? Should we add it to a UI option?

### CODE REVIEW

**Comment by Techjar** [comment]
Devices don't necessarily handle this properly, so it should definitely be an option. As for whether its useful, I would say yes as long as we can find some devices with show an improvement with it on.

**Comment by zackhow** [comment]
The way I understand this is it brings a consistent experience over the course of the activity, that it will drop performance in the short term to prevent slowdowns later due to heating. So instead of 60 fps for 15 minutes -> 30 fps after, you get 45fps for 60 minutes.

**Comment by Techjar** [comment]
@zackhow Doesn't look like that does anything to the CPU governor, and is just a higher level construct for CPU pinning to prevent other threads preempting yours. Not very useful to us, as our problem is aggressive CPU scaling causing stutters.

**Comment by Helios747** [comment]
It certainly wouldn't hurt. Default it on.

**Comment by Gamemulatorer** [comment]
How about this now?

**Comment by JosJuice** [comment]
I uploaded a rebased version as PR #10206.

**Pull request closed without merging**
