### PR TITLE
windows: detect and warn if running x64 dolphin on arm64

### PR DESCRIPTION
**Pull request by shuffle2**
this came up in conversation on irc.

### CODE REVIEW

**Comment by delroth** [comment]
@dolphin-emu-bot rebuild

**Comment by Rumi-Larry** [comment]
> Are there any plans to offer ARM native builds for Windows? If ARM Windows builds aren't being tested or made available for download I'm not sure if this warning will be beneficial for users.

I think that is already possible.

**Comment by JosJuice** [comment]
> I think that is already possible.

We're talking about us building them for users, not just about building them being possible.

**Comment by shuffle2** [comment]
https://github.com/dolphin-emu/sadm/pull/124

**Comment by Rumi-Larry** [comment]
> > I think that is already possible.
> 
> We're talking about us building them for users, not just about building them being possible.

Ahh, I thought users could already build ARM on Windows

**Comment by shuffle2** [comment]
The infrastructure is now fully handling arm64/windows stuff, so there aren't those type of missing prereqs for this PR anymore.
Any comments about this PR itself (moved to different location / better wording / etc) ?

**Comment by delroth** [comment]
Nitpicking: instead of being in the JIT, should this be in https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Common/x64CPUDetect.cpp instead? Seems to me like a more logical location.

**Review by delroth — APPROVED** [review]

**Pull request merged**
