### PR TITLE
GCMemcard: Fix out of bounds access in F-Zero GX checksum calculation.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
Pretty self-explanatory. `block` was incremented one loop too late; slight rewrite so it's clearer what it's doing.

This probably worked regardless because the data blocks are lying right next to eachother in memory, but Visual Studio's Debug build rightly complained about this.

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
Noticed another small thing, this never checked if the file actually had four data blocks, so if you constructed yourself a custom file with the correct filename but only one block you could trash 0x6000 bytes of memory. Unlikely, but hey.

**Comment by AdmiralCurtiss** [comment]
Block size is fixed at 0x2000 bytes at a hardware level (and implemented as a fixed size array), so no real need to check that unless we expect memory card block sizes to change somehow.

**Comment by Tilka** [comment]
Did someone test this?

**Comment by AdmiralCurtiss** [comment]
Poking this one. Could someone else test this?

**Comment by JMC47** [comment]
Seems to work and is a small change.  Was able to save a regular save and garage data and reload it.

**Pull request merged**
