### PR TITLE
CommonFuncs: Get rid of pointer casting

### PR DESCRIPTION
**Pull request by lioncash**
The previous code was considered undefined behavior.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4293)

### CODE REVIEW

**Comment by shuffle2** [comment]
ew :/

**Comment by shuffle2** [comment]
Is this really true for integral types? People say trust the compiler but I find that unwise advice.

**Comment by lioncash** [comment]
@shuffle2 Yes. because it's casting from a weaker aligned type to a more strongly aligned type (that, and you also break strict aliasing on top of that).

**Comment by shuffle2** [comment]
I think the alignment rule is about the pointer alignment (not alignment of the datatype it points to). Which will all be the same here. Strict aliasing is technically an issue, however, my question was about if we can trust the compiler to still optimize this even when global optimizations are disabled (ie I'll give this a big 👎 if it increases overhead on debug builds). I'm checking the binary now...

**Comment by lioncash** [comment]
> Which will all be the same here

This isn't a hard guarantee. You will get misaligned pointers casting like that on some platforms. You can even compile ubsan into Dolphin on Linux and let it run for a bit to get a nice stream of examples.

> (ie I'll give this a big 👎 if it increases overhead on debug builds). I'm checking the binary now...

I completely disagree with leaving undefined behavior in an application regardless of what it does when compiled as a debug implementation.

**Comment by shuffle2** [comment]
> This isn't a hard guarantee. You will get misaligned pointers casting like that on some platforms. You can even compile ubsan into Dolphin on Linux and let it run for a bit to get a nice stream of examples.  

Well, it's hard enough since we know which platforms are supported by dolphin. Are there some where pointers to integrals [u8,u64] are not uniformly aligned?

> I completely disagree with leaving undefined behavior in an application regardless of what it does when compiled as a debug implementation.

There is such a thing as making debug builds too cumbersome to be usable.

**Comment by lioncash** [comment]
> I think the alignment rule is about the pointer alignment (not alignment of the datatype it points to

I missed addressing this, but it applies to the datatype's alignment requirements. (See point 5 in Explanation [here](http://en.cppreference.com/w/cpp/language/reinterpret_cast). It's also reiterated in Type Aliasing further down).

> Are there some where pointers to integrals [u8,u64] are not uniformly aligned

See previous point, since alignment reqs apply to the type being pointed to.

> There is such a thing as making debug builds too cumbersome to be usable.

I can assure you, a memcpy is the least of your worries in that scenario when it comes to literally anything else that should be looked at in Dolphin.

**Comment by shuffle2** [comment]
(it produces the same code)

**Pull request merged**
