### PR TITLE
Updated license

### PR DESCRIPTION
**Pull request by AnonEx**
[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3665)

### CODE REVIEW

**Comment by delroth** [comment]
That's automatically generated, and it has no legal value.

**Comment by AnonEx** [comment]
Not to sound rude, but of course it has legal value. It _is_ a license after all, and what's the point of having a license if it's not going to be kept up to date?

**Comment by delroth** [comment]
That's not how copyright works.

**Comment by AnonEx** [comment]
My apologies.

**Comment by vgturtle127** [comment]
@delroth Would a pull request updating all the copyright years be merged? Just curious.

**Comment by lioncash** [comment]
No. The copyright date is there to establish how far back the claim to copyright is.

**Comment by vgturtle127** [comment]
@lioncash OK, I figured.

**Pull request closed without merging**
