### PR TITLE
fix Android app name Dolphin E

### PR DESCRIPTION
**Pull request by soundsnow**
fixed Dolphin E

### CODE REVIEW

**Comment by K0bin** [comment]
Why?

**Comment by MayImilae** [comment]
Dolphin emulator is not the only software named after a popular porpoise. Even on Android!

**Comment by JosJuice** [comment]
My phone shows it as "Dolphin Emulator" on two lines. Having it show up as "Dolphin E..." on some phones isn't a big deal in my opinion, so I'm not really sold on this change.

**Comment by mbc07** [comment]
The default launcher on Samsung phones running One UI 6 or newer (Android 14, essentially) now truncates app names as well instead of displaying them in two lines (like in One UI 5.1 and earlier), but still I don't think that's enough to justify the change proposed in this PR. There are several Android devices out there, from several brands, you can also install several different launchers on them so I don't think it's even possible to get it right in every phone out there...

**Pull request closed without merging**
