### PR TITLE
Clean up the Android specific C++ code.

### PR DESCRIPTION
**Pull request by Sonicadvance1**
Change over to using the JavaHelper namespace to clean up interfaces.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3606)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Common/JavaHelper.h, line 5 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3606#-K9ym8P3XJMXkg5psgIz:-K9ym8P3XJMXkg5psgJ-:1435629800) ([raw file](https://github.com/dolphin-emu/dolphin/blob/05c48f5d3063d2edbaaf0ec11e965953e389db31/Source/Core/Common/JavaHelper.h#L5)):*
std::string needs to be included

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3606)*

**Comment by lioncash** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3606#-K9ymw2ik5ME6V5aZXji:-K9ymw2ik5ME6V5aZXjj:-518510492) (no related file):*
Should JavaHelper be placed in Common? It's quite Android-specific.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3606)*

**Comment by Sonicadvance1** [comment]
*[a discussion](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3606#-K9ymw2ik5ME6V5aZXji:-K9z54izxCJgF7UF3fB4:739915204) (no related file):*
Excellent question. It's used in that Core, InputCommon, and in the future will most likely also might be used in Common for a configuration backing class.
InputCommon originally broke the mold with including things from the "UI"  with the ButtonManager class since that's basically what the break is between the layers.
This clear break between what the UI provides to the core routines is becoming fuzzier and fuzzier due to Android having to do so many dumb Java<->JNI interfacing layers.
I'm not sure if it's the right move or not to move this to Android/jni.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3606)*

**Comment by BhaaLseN** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/Core/Common/JavaHelper.cpp, line 23 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3606#-KA-a94o5TMKomD4Hifv:-KA-a94pS88Zv32T2E61:1222906355) ([raw file](https://github.com/dolphin-emu/dolphin/blob/05c48f5d3063d2edbaaf0ec11e965953e389db31/Source/Core/Common/JavaHelper.cpp#L23)):*
Would it make much of a difference to use `env->GetObjectClass(class_loader)` instead? You got an instance already, so why not use it?

---

*[Source/Core/Common/JavaHelper.cpp, line 65 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3606#-KA-_oMIkVL9gZHSpG-M:-KA-_oMJPt2dMx5qBnww:-949255194) ([raw file](https://github.com/dolphin-emu/dolphin/blob/05c48f5d3063d2edbaaf0ec11e965953e389db31/Source/Core/Common/JavaHelper.cpp#L65)):*
You could probably just use `ExceptionCheck` instead, since you don't really care about the exception itself at this point...

---

*[Source/Core/Common/JavaHelper.cpp, line 84 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3606#-KA-Yrt-R3GrsI1ZszmF:-KA-Yrt0W4Bnp5UA-AAW:674945497) ([raw file](https://github.com/dolphin-emu/dolphin/blob/05c48f5d3063d2edbaaf0ec11e965953e389db31/Source/Core/Common/JavaHelper.cpp#L84)):*
Hmm, calling a method called `DetachThread` with a parameter `!attached` sounds a bit backwards, especially when the actual parameter name is `skip`. I think it would be easier if you turn this around, and call the parameter `has_been_attached`/`was_attached` (or smth like that) to make the link to `AttachThread` more visible for other developers...

Maybe it might also be a good idea to consider an RAII approach for attach/detach? As far as I could see, your calls are pretty much confined to methods, from start to end (or rather close to that).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3606)*

**Comment by Tsunamical** [comment]
Just now saw this. Though my input holds minimal value, code looks good other than suggested changes. It would likely be beneficial to rebase.

**Pull request closed without merging**
