### PR TITLE
DVDInterface: Reduce a global variable to translation unit scope

### PR DESCRIPTION
**Pull request by lioncash**
g_bStream isn't used anywhere else.

Also corrects the prefixes on other translation unit scoped variables as well.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3558)

### CODE REVIEW

**Comment by JosJuice** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/HW/DVDInterface.cpp, line 236 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3558#-K8muE9XeHqpYCIX8asb:-K8muE9XeHqpYCIX8asc:-600545081) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a68708cf338d72ef0dec6ebfebdd901011962712/Source/Core/Core/HW/DVDInterface.cpp#L236)):*
`s_audio_position`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3558)*

**Comment by JosJuice** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3558)*

**Comment by degasus** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3558)*

**Comment by BhaaLseN** [comment]
LGTM apart from those two underscores (which may or may not belong in this PR; but since you changed others it probably doesn't matter much...)

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[Source/Core/Core/HW/DVDInterface.cpp, line 509 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3558#-K8nTVUHH4Qto5elDnpm:-K8nTVUIjhGncEI1NXN-:-1015599230) ([raw file](https://github.com/dolphin-emu/dolphin/blob/eca7641c355a7109ddc326f43c35b48719191b03/Source/Core/Core/HW/DVDInterface.cpp#L509)):*
You might want to rename this one too, while you're at it (underscore at start)

---

*[Source/Core/Core/HW/DVDInterface.cpp, line 627 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3558#-K8nTg85xws3EeG-gB3s:-K8nTg86hJ51EC9D2uaY:-1321424255) ([raw file](https://github.com/dolphin-emu/dolphin/blob/eca7641c355a7109ddc326f43c35b48719191b03/Source/Core/Core/HW/DVDInterface.cpp#L627)):*
And perhaps this one too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3558#-:-K8nTqo-Qc_ynNhqhnVx:-1761169515)*

**Comment by delroth** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3558)*

**Comment by delroth** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3558)*

**Comment by degasus** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3558)*

**Comment by JosJuice** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3558)*

**Pull request merged**
