### PR TITLE
Renderer: Move framedumping logic to VideoCommon.

### PR DESCRIPTION
**Pull request by degasus**
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4318)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/VideoCommon/RenderBase.cpp, line 546 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-KTVfnXzaDlvmK4oBrRx:-KTVfnXzaDlvmK4oBrRy:b-1foqc0) ([raw file](https://github.com/dolphin-emu/dolphin/blob/5c9c884c92eeffecc4552520416155f3ba0f964b/Source/Core/VideoCommon/RenderBase.cpp#L546)):*
> ```cpp
>     return true;
>   }
>   else
> ```

else isn't necessary.

---

*[Source/Core/VideoCommon/RenderBase.cpp, line 590 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-KTVfvzcARPWrtaeRHSN:-KTVfvzcARPWrtaeRHSO:b-31mfz0) ([raw file](https://github.com/dolphin-emu/dolphin/blob/5c9c884c92eeffecc4552520416155f3ba0f964b/Source/Core/VideoCommon/RenderBase.cpp#L590)):*
> ```cpp
> 
>   // TODO: Refactor this. Right now it's needed for flipping the image.
>   memcpy(frame_data.data(), data, image_size);
> ```

You can just do `frame_data.assign(data, data + image_size);`. It also lets you get rid of the resize call in the upper if statement.

---

*[Source/Core/VideoCommon/RenderBase.h, line 192 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-KTVg0OiZlGu39BkTAFF:-KTVg0OiZlGu39BkTAFG:b329t6q) ([raw file](https://github.com/dolphin-emu/dolphin/blob/5c9c884c92eeffecc4552520416155f3ba0f964b/Source/Core/VideoCommon/RenderBase.h#L192)):*
> ```objc
> 
>   // framedumping
>   std::vector<u8> frame_data;
> ```

`m_`, etc for the others. The Hungarian `b` can also be dropped.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318)*

**Comment by degasus** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/VideoCommon/RenderBase.cpp, line 546 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-KTVfnXzaDlvmK4oBrRx:-KTVkH6EzKFJ1dPg9RBN:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/5c9c884c92eeffecc4552520416155f3ba0f964b/Source/Core/VideoCommon/RenderBase.cpp#L546)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> else isn't necessary.
</details>
Done.

---

*[Source/Core/VideoCommon/RenderBase.cpp, line 590 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-KTVfvzcARPWrtaeRHSN:-KTVlDOGxIgOEp6D5Njo:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/5c9c884c92eeffecc4552520416155f3ba0f964b/Source/Core/VideoCommon/RenderBase.cpp#L590)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> You can just do `frame_data.assign(data, data + image_size);`. It also lets you get rid of the resize call in the upper if statement.
</details>
Done.

---

*[Source/Core/VideoCommon/RenderBase.h, line 192 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-KTVg0OiZlGu39BkTAFF:-KTVn7SLZA4cdrzHmX3-:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/5c9c884c92eeffecc4552520416155f3ba0f964b/Source/Core/VideoCommon/RenderBase.h#L192)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> `m_`, etc for the others. The Hungarian `b` can also be dropped.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318)*

**Comment by RisingFog** [comment]
*[Source/Core/VideoCommon/RenderBase.cpp, line 617 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-KTVswG2ABi1VHyj_nK_:-KTVswG2ABi1VHyj_nKa:b-2e1ckj) ([raw file](https://github.com/dolphin-emu/dolphin/blob/5c9c884c92eeffecc4552520416155f3ba0f964b/Source/Core/VideoCommon/RenderBase.cpp#L617)):*
> ```cpp
> }
> 
> void Renderer::RepeatFrameDumpFrame()
> ```

This entire function should be able to get dropped, it seems like the places where this was used was left-over from the days of VFW. Not 100% certain on this, however.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318)*

**Comment by degasus** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/VideoCommon/RenderBase.cpp, line 617 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-KTVswG2ABi1VHyj_nK_:-KTVu3JcMZb85dj7rVs0:b-jbqecl) ([raw file](https://github.com/dolphin-emu/dolphin/blob/5c9c884c92eeffecc4552520416155f3ba0f964b/Source/Core/VideoCommon/RenderBase.cpp#L617)):*
<details><summary><i>Previously, RisingFog (Chris Burgener) wrote…</i></summary>
> This entire function should be able to get dropped, it seems like the places where this was used was left-over from the days of VFW. Not 100% certain on this, however.
</details>
Do you want me to do this before this PR, or after? I'm fine with both, but I don't want such a big functional change within the same PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318)*

**Comment by RisingFog** [comment]
*[Source/Core/VideoCommon/RenderBase.cpp, line 617 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-KTVswG2ABi1VHyj_nK_:-KTVujM3FFjBSsHju7qs:blzjis) ([raw file](https://github.com/dolphin-emu/dolphin/blob/5c9c884c92eeffecc4552520416155f3ba0f964b/Source/Core/VideoCommon/RenderBase.cpp#L617)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> Do you want me to do this before this PR, or after? I'm fine with both, but I don't want such a big functional change within the same PR.
</details>
Whatever floats your boat, I'll tinker with it tonight see if there are any negative impacts of it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318)*

**Comment by RisingFog** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/VideoCommon/RenderBase.cpp, line 539 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-KTVwQbvaCQNB1n4Desb:-KTVwQbvaCQNB1n4Desc:by7mdeb) ([raw file](https://github.com/dolphin-emu/dolphin/blob/9fe7012f5b847638fc9713c467b1c354966a7da4/Source/Core/VideoCommon/RenderBase.cpp#L539)):*
> ```cpp
> }
> 
> bool Renderer::WantNextFrameDump()
> ```

This could be simplified to just IsFrameDumping or something of that nature.

---

*[Source/Core/VideoCommon/RenderBase.cpp, line 558 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-KTVwBeNu0CEevb8wQSY:-KTVwBeNu0CEevb8wQSZ:b-yaykg0) ([raw file](https://github.com/dolphin-emu/dolphin/blob/9fe7012f5b847638fc9713c467b1c354966a7da4/Source/Core/VideoCommon/RenderBase.cpp#L558)):*
> ```cpp
> }
> 
> void Renderer::PushFrameDumpData(const u8* data, int w, int h, AVIDump::DumpFormat format,
> ```

This probably can be renamed to DumpFrames or DumpFrameData.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318)*

**Comment by degasus** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/VideoCommon/RenderBase.cpp, line 539 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-KTVwQbvaCQNB1n4Desb:-KTW-bqiB0nsEIY2hcP7:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/9fe7012f5b847638fc9713c467b1c354966a7da4/Source/Core/VideoCommon/RenderBase.cpp#L539)):*
<details><summary><i>Previously, RisingFog (Chris Burgener) wrote…</i></summary>
> This could be simplified to just IsFrameDumping or something of that nature.
</details>
Done.

---

*[Source/Core/VideoCommon/RenderBase.cpp, line 558 at r2](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-KTVwBeNu0CEevb8wQSY:-KTW-bO_DDV6ZLHPzbOT:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/9fe7012f5b847638fc9713c467b1c354966a7da4/Source/Core/VideoCommon/RenderBase.cpp#L558)):*
<details><summary><i>Previously, RisingFog (Chris Burgener) wrote…</i></summary>
> This probably can be renamed to DumpFrames or DumpFrameData.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318)*

**Comment by RisingFog** [comment]
Reviewed 1 of 7 files at r1, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318)*

**Comment by RisingFog** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4318#-:-KTWLVCyvL9rMmGrVZhR:bnfp4nl)*

**Pull request merged**
