### PR TITLE
IOS/ES: Partially restore hack to fake IOS titles

### PR DESCRIPTION
**Pull request by leoetlino**
This partially restores a hack which causes ES to fake ticket views for IOS titles.

This is necessary because we still allow users to boot games from the game list, so, with no way of making sure the required IOSes are installed beforehand, games may OSPanic() when they try to reload to some IOS version and just find out that the IOS is not installed (something which *never* happens on the real console, of course).

A warning is printed in the logs to make sure technical users know the IOS titles are being faked. To try and keep things accurate in all other cases, this hack is only active when it is needed (when the current title is a disc title which was launched from the game list).

### CODE REVIEW

**Comment by JMC47** [comment]
I think this is necessary.  Fixes issues with Metroid Prime Trilogy and Brawl

**Comment by Helios747** [comment]
I'm for this. Accuracy is important, but I'm not particularly thrilled about requiring users to have to launch system menu to play (to them) random games due to reasons they don't understand.

**Comment by BhaaLseN** [comment]
The improvements are important, but breaking what end users have been doing for years (booting games from the game list) without giving them a usable replacement is a considerably high price to pay; so I'd rather have this piece of code in there.
It's clearly documented and obvious, yet fairly concise and contained - LGTM if it works.

**Comment by Helios747** [comment]
@JMC47 can you test this please?

@leoetlino this will need rebasing before merging.

**Pull request merged**
