### PR TITLE
[WIP] Add option to dump video and audio together

### PR DESCRIPTION
**Pull request by RisingFog**
Another untested dumping feature which attempts to sync video and audio together when both are dumped together.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3549)

### CODE REVIEW

**Comment by BhaaLseN** [comment]
I'd prefer one common place where both are started at the same time, but I guess it's better than being terribly out of sync. The variable names threw me off a bit at first tho (`audio_dump_start` vs. `start_audio_dumping`), but I guess that makes sense too if you look closely...and I can't think of names that make it more clear atm.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-:-K8e7il8dO6XUZja4A4B:-2073481019)*

**Comment by lioncash** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Source/Core/VideoCommon/AVIDump.cpp, line 19 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8e7_IFswaXGbdttfzq:-K8e7_IGMOHCTNtZWmz8:-1454222501) ([raw file](https://github.com/dolphin-emu/dolphin/blob/53d150bb02509fc5ec15a3205396f099c8e0976b/Source/Core/VideoCommon/AVIDump.cpp#L19)):*
Quotations should be used, not `<` and `>`

---

*[Source/Core/VideoCommon/AVIDump.cpp, line 144 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8e8-IllQi1kEYFYBI9:-K8e8-ImQNUe3Q2pzBkz:-39017446) ([raw file](https://github.com/dolphin-emu/dolphin/blob/53d150bb02509fc5ec15a3205396f099c8e0976b/Source/Core/VideoCommon/AVIDump.cpp#L144)):*
Should be its own function and not be called in this function. It has nothing to do with the creation of the file.
As its own function, this would ideally be called within Start

---

*[Source/Core/VideoCommon/AVIDump.cpp, line 272 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8e8HIo5EhLNb9j_Hv4:-K8e8HIo5EhLNb9j_Hv5:2022901925) ([raw file](https://github.com/dolphin-emu/dolphin/blob/53d150bb02509fc5ec15a3205396f099c8e0976b/Source/Core/VideoCommon/AVIDump.cpp#L272)):*
Same as starting audio dumping. This should be its own function, and not be called within CloseFile, it has nothing to do with the successful closing of the file. As its own function, it would ideally be called in Close

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549)*

**Comment by lioncash** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Source/Core/VideoCommon/AVIDump.cpp, line 272 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8e8HIo5EhLNb9j_Hv4:-K8e9engO2SC5pJ_IpIp:-429346034) ([raw file](https://github.com/dolphin-emu/dolphin/blob/53d150bb02509fc5ec15a3205396f099c8e0976b/Source/Core/VideoCommon/AVIDump.cpp#L272)):*
it would ideally be called in Stop, I mean

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549)*

**Comment by lioncash** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Core/VideoCommon/AVIDump.cpp, line 19 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8eAIm-WzvL-h_VQ-qd:-K8eAIm0OcvHeHZEJ9I7:1898805382) ([raw file](https://github.com/dolphin-emu/dolphin/blob/53d150bb02509fc5ec15a3205396f099c8e0976b/Source/Core/VideoCommon/AVIDump.cpp#L19)):*
Including Mixer.h isn't necessary.  Also, quotations, not angle brackets

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549)*

**Comment by lioncash** [comment]
*[Source/Core/VideoCommon/AVIDump.cpp, line 231 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8eCGTEVnmcLdvtelk0:-K8eCGTFtY38Cyd_Af0J:-394896607) ([raw file](https://github.com/dolphin-emu/dolphin/blob/8009299c41cf6a3e5558aa671860276ccb69815c/Source/Core/VideoCommon/AVIDump.cpp#L231)):*
You should likely stop the dumping before closing the file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549)*

**Comment by BhaaLseN** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/VideoCommon/AVIDump.cpp, line 141 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8eKI31zqCgDon2oTC2:-K8eKI320azzt099HvHq:1764798722) ([raw file](https://github.com/dolphin-emu/dolphin/blob/e394e7aad18ee430fcb5e9fccbbd960d88b1028c/Source/Core/VideoCommon/AVIDump.cpp#L141)):*
Mh, would it make sense to move this over to `Start` instead?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549)*

**Comment by RisingFog** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/VideoCommon/AVIDump.cpp, line 141 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8eKI31zqCgDon2oTC2:-K8eNa-76dxbcQX4pxnA:842065222) ([raw file](https://github.com/dolphin-emu/dolphin/blob/e394e7aad18ee430fcb5e9fccbbd960d88b1028c/Source/Core/VideoCommon/AVIDump.cpp#L141)):*
Maybe, not really sure though if it should be though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549)*

**Comment by JosJuice** [comment]
*[Source/Core/Core/ConfigManager.h, line 252 \[r7\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8epaLxv_8qEnkFzd0J:-K8epaLyOab_mOdqk8aC:40071038) ([raw file](https://github.com/dolphin-emu/dolphin/blob/baf4543dababba37896a2446b71faaab33fb14e5/Source/Core/Core/ConfigManager.h#L252)):*
Adding a "dump frames and audio" checkbox in addition to the existing options "dump frames" and "dump audio" is bad UI, because users won't understand the difference between enabling "dump frames and audio" and enabling the two other options together. I'm against adding this unless there's a clear reason.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549)*

**Comment by lioncash** [comment]
Review status: 2 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/VideoCommon/AVIDump.cpp, line 141 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8eKI31zqCgDon2oTC2:-K8eXQr73uIxe5ej0JuI:-2105285917) ([raw file](https://github.com/dolphin-emu/dolphin/blob/e394e7aad18ee430fcb5e9fccbbd960d88b1028c/Source/Core/VideoCommon/AVIDump.cpp#L141)):*
This code was modified in the latest revision, however I'd like to give you some (hopefully) constructive advice on approaching/dealing with the concerns of where behaviours should be placed in a library or application, or rather, being uncertain about where they should go. I see this problem quite a bit in some other open-source libraries and applications. Note that I'm not saying this because I'm upset or anything, I want to make that clear, but because it's a common issue I see, and I know you can improve and do better.

When you work on an API—even if it's open-source—approach it as if you were planning to ship a closed-source library to a client [insert OSS zealot gasps here]. Now, your packaged build to them contains the following:

- the compiled libraries to link against
- the header files
- the documentation (In Dolphin's case, assume this doesn't exist, since most headers unfortunately don't have documentation)

that's it—no source files.

Assume whatever code you write in the implementation .cpp file will not be seen by anyone else when writing a new API, or extending an existing one. Now with this viewpoint in mind, consider the following:

With only a function prototype in the header file named `CreateFile`, what do you think your client would assume it does without seeing any documentation? I can, with certainty, say that starting an audio dump is *not* one of the first things that would come to mind. They'd likely assume it creates an arbitrary file; nothing more, nothing less.

After you write an extension to something, consider yourself in the position of someone using the class interface from scratch and ask yourself, "Does this make sense to be here from a behavioural standpoint?", or "Assuming internals cannot be exposed, is the outcome of the behaviour for this function an *expected* one?". 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549)*

**Comment by lioncash** [comment]
Review status: 2 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/VideoCommon/AVIDump.cpp, line 69 \[r6\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8ew0aq8b_CEaOQ-kMS:-K8ew0ar2tEZuaJhyuRy:-1835811241) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f3440eb0ffbce5fcbb806a2f17843e31cf27eb70/Source/Core/VideoCommon/AVIDump.cpp#L69)):*
This should likely begin after the file is successfully created.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549)*

**Comment by lioncash** [comment]
Review status: 2 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Core/VideoBackends/D3D/Render.cpp, line 719 \[r7\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8ewR3OhjXyCMgb8T1w:-K8ewR3OhjXyCMgb8T1x:696577923) ([raw file](https://github.com/dolphin-emu/dolphin/blob/baf4543dababba37896a2446b71faaab33fb14e5/Source/Core/VideoBackends/D3D/Render.cpp#L719)):*
These two options being is a bunch of if statements is quite a bit of code duplication, perhaps add a method to SConfig for checking if either of these are active. Something like:

```cpp
bool SConfig::IsDumpFramesEnabled() const
{
    return m_DumpFrames || m_DumpFramesAndAudio;
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549)*

**Comment by RisingFog** [comment]
Review status: 2 of 13 files reviewed at latest revision, all discussions resolved.

---

*[Source/Core/Core/ConfigManager.h, line 252 \[r7\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8epaLxv_8qEnkFzd0J:-K8fgsN6v42EWiRJtCj4:731139328) ([raw file](https://github.com/dolphin-emu/dolphin/blob/baf4543dababba37896a2446b71faaab33fb14e5/Source/Core/Core/ConfigManager.h#L252)):*
Not really a clear reason, may just decide to revert it.

---

*[Source/Core/VideoBackends/D3D/Render.cpp, line 719 \[r7\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8ewR3OhjXyCMgb8T1w:-K8fgTxHboJZ6QGepkBu:1760884396) ([raw file](https://github.com/dolphin-emu/dolphin/blob/baf4543dababba37896a2446b71faaab33fb14e5/Source/Core/VideoBackends/D3D/Render.cpp#L719)):*
Still mulling over if having a third option is even necessary at this point. The majority of opinions seem against it so I may just change the logic up anyways. If I do keep the menu, I'll make it a method for easier code.

---

*[Source/Core/VideoCommon/AVIDump.cpp, line 141 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549#-K8eKI31zqCgDon2oTC2:-K8ffxAqMmPnqG6KxV8Z:-812828420) ([raw file](https://github.com/dolphin-emu/dolphin/blob/e394e7aad18ee430fcb5e9fccbbd960d88b1028c/Source/Core/VideoCommon/AVIDump.cpp#L141)):*
Very informative, thanks for that. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3549)*

**Comment by RisingFog** [comment]
Closing this PR, PR #3551 solves the problem in a much simpler way.

**Pull request closed without merging**
