### PR TITLE
I wish it was april the second.

### PR DESCRIPTION
**Pull request by MoochMcGee**
Reverts dolphin-emu/dolphin#2256

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by MoochMcGee** [comment]
FUCK I LITERALLY HIT THE REBUILD BUTTON. WHATEVER, THIS IS STILL AN EFFECTIVE PROTEST.

**Comment by delroth** [comment]
Duplicate of #2258.

**Comment by MoochMcGee** [comment]
DAMMIT I WAS PROTESTING

**Pull request closed without merging**
