### PR TITLE
Interpreter: fix slwx

### PR DESCRIPTION
**Pull request by FioraAeterna**

### CODE REVIEW

**Comment by magumagu** [comment]
JIT64 has the same bug.

**Comment by FioraAeterna** [comment]
Are you sure? x86 masks the shift amount by 0x3f for 64-bit shifts, as far as I know

**Comment by magumagu** [comment]
I mean the constant-folding codepath.

**Comment by FioraAeterna** [comment]
Oh darn, you're totally right. Fixed.

**Comment by Sonicadvance1** [comment]
Can you fix this in ARM's constant folding path as well?
https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Core/PowerPC/JitArm32/JitArm_Integer.cpp#L374

**Comment by FioraAeterna** [comment]
Those paths look totally wrong for all three instructions (they're missing the &0x20 check too).

**Comment by Sonicadvance1** [comment]
Isn't the 0x20 check silly enough since shifting left by 32 just zeros out the result?

**Comment by FioraAeterna** [comment]
Depends on the architecture; it's not defined in C IIRC. On x86, the shift amount is masked by the register size.

**Comment by Sonicadvance1** [comment]
I'll fix it later.
Not too big of an issue.

**Comment by hrydgard** [comment]
Still finding bugs in the interpreter! Incredible :)

**Pull request merged**
