### PR TITLE
DolphinWX: Support 2x images for all resources

### PR DESCRIPTION
**Pull request by JosJuice**
https://bugs.dolphin-emu.org/issues/9275

Untested, because I don't have OS X. I'm creating this PR so @MaJoRoesch can test it.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3533)

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by absolome** [comment]
Comparison image on my end (OS X, Retina display) http://i.imgur.com/MQi6bjL.png

**Comment by absolome** [comment]
http://i.imgur.com/BREHl2x.png after the fix

**Comment by RisingFog** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3533)*

**Comment by RisingFog** [comment]
LGTM

**Comment by Sonicadvance1** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3533)*

**Pull request merged**
