### PR TITLE
DolphinQt: Use qOverload where applicable

### PR DESCRIPTION
**Pull request by lioncash**
Provides the same behvaior, but in a much more concise manner.

### CODE REVIEW

**Comment by lioncash** [comment]
Windows buildbot seems to have a version of Qt less than 5.7, which would put it around early 2016. It may be worth updating it to 5.11 or any other newer version.

**Comment by BhaaLseN** [comment]
Any reason to not simply use `QOverload<T>::of(&QType::method)` instead of `qOverload<T>(&QType::method)`? We use the former in other places already (like this one: https://github.com/dolphin-emu/dolphin/blob/dea2b9c509b96cb58182b883c1df9f9f7f9234bf/Source/Core/DolphinQt/Settings/GameCubePane.cpp#L141-L144), and it only differs by 4 characters.

**Comment by lioncash** [comment]
It's (now) intended as a stopgap for C++11-only code that is unable to use C++14. While it's an option, I do think the buildbot should be updated to use roughly the same version of the Qt libraries that is used in our [ext-win-qt](https://github.com/dolphin-emu/ext-win-qt) dependency, which provides the equivalent of 5.11.1.

It's quite odd to remain on an old version of Qt for the buildbots, but not actually use that version in our own dependencies.

**Comment by BhaaLseN** [comment]
I do wonder about that as well...it _should_ be using it, since there is no installation of Qt on them (at least to my knowledge - and if there is, we should probably remove it?)

**Comment by leoetlino** [comment]
Now that we've updated to Qt 5.14, would this build fine on the Windows builder?

**Pull request merged**
