### PR TITLE
[WIP] [RFC] Switch bWii to new config system

### PR DESCRIPTION
**Pull request by MerryMage**
Putting this up for comments early on before proceeding with more work.

What's in this PR:

* Corrected a mistake in Config::Section::Get.
* Just allocate the CurrentRun layer in Config::Init.
* Implement Config::Get and Config::Set.
* Replaced bWii as a demonstration. (Clearly the code in ConfigManager.cpp will not exist when everything is complete.)

Things not done/investigated:

* Loading settings from INI.

Questions:

* Is this approach acceptable?
* Why is bWii even part of SConfig in the first place?
* Given the potential frequency of configuration access, it seems prudent to reduce the amount of std::map lookups as possible. Flattening the structure from what's effectively a std::map<System, std::vector<std::map<Key, Value>>> into a std::map<struct{System,Section,Key}, Value> might be advisable.

(Note: There are a few obvious code formatting errors such as missing newlines and misplaced #includes I'll eventually get round to.)

### CODE REVIEW

**Comment by lioncash** [comment]
> Is this approach acceptable?

The only downside I can think of, is that each translation unit that uses the constexpr struct instances will get its own copy of the struct within itself in certain circumstances. Since internally linked variable instances have a different address in each translation unit, if it's passed/taken by reference (anything involving the address), then it will likely be copied into the translation unit itself, which leads to minor bloat due to redundant copies. This can get quite large considering it also involves strings and default values.

> Why is bWii even part of SConfig in the first place?

I don't know, but things about it being silly wouldn't be too far-fetched, considering it stores [things that should be UI frontend-independent](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Core/ConfigManager.h#L271)

> Given the potential frequency of configuration access ...

Minimizing indirections would be very nice, I agree.

**Comment by degasus** [comment]
Seems like bWii isn't used very often, so I doubt the std::map lookup matters. Other variables are, so we may need some kind of caching. No clue if this shall be done by the using code, or within the config framework.

**Comment by spycrab** [comment]
``DolphinQt2/Settings.cpp`` uses it. Please consider updating the IsWiiGameRunning() method. (Don't know if you already did that, because getting a comprehensive changed file overview from GitHub is quite hard)

**Comment by BhaaLseN** [comment]
I wouldn't be surprised if `bWii` is only in there because `SConfig` was something global-ish that could be accessed pretty much anywhere.
I _think_ the idea was to have some sort of run-time information (what game is currently up and running, what system are we emulating, whether to disable certain Jit instructions etc.) - and that should've been `SConfig`. It shouldn't do stuff like read ini files or other configs; only receive values it needs where necessary.

But cleaning that up is likely a huge PR on its own...

**Comment by MerryMage** [comment]
Closing, going to use a different approach.

**Pull request closed without merging**
