### PR TITLE
Game INI Updates

### PR DESCRIPTION
**Pull request by Linktothepast**
This is mainly a virtual console update. Removes progressive scan option
from snes, genesis, etc. games since it is no longer needed for proper
speed. Adds gameinis for Neo geo, Arcade and missing gameinis for
genesis.

### CODE REVIEW

**Comment by Linktothepast** [comment]
This is a great git failure from my part and i don't have a clue how to fix this apart starting from scratch.

**Comment by BhaaLseN** [comment]
```git rebase dolphin-emu/master master``` and cross your fingers. If it worked, ```git push -f origin master``` (or whatever your own fork is called, if its not ```origin```).
In the future, you might want to consider creating branches for that, instead of using master (to avoid this).

**Comment by Linktothepast** [comment]
I created a branch gameinis locally but for some weird reason it didn't showed up in the repo online from the beginning instead every time i committed something to gameinis locally it committed it to master in the online repo...

**Comment by BhaaLseN** [comment]
Only branches you pushed will show up on GitHub, otherwise they're only local to your clone. Maybe try ```git rebase dolphin-emu/master gameinis``` followed by ```git push origin gameinis``` (again, replace ```origin``` if necessary).
Maybe drop by on IRC, easier to discuss there if anything else comes up.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by shellashock** [comment]
Since you have a pr for game inis open, I'll just leave this here.

Conflict - Desert Storm 2: Back to Baghdad NTSC (GC2E9G) will display videos if Real XFB is enabled and will only produce the audio with a black screen with either Virtual XFB or Disabled XFB. 

At the time of writing, Real XFB is not enabled in the .ini for this game and it probably should be considering that it makes cutscenes visible without any side effects that I am aware of. This change makes this game fully playable out of the box with no issues whatsoever. (wiki can be changed to 5 star rating after adding the requirement for Real XFB to the video issue?)

**Comment by Linktothepast** [comment]
Oh thanks i will try to add it, it seems there is another game that the hybrid xfb branch can help. Although i am pissed at git, might as well pack all the inis and ask someone else to do a pr about it.

**Pull request merged**
