### PR TITLE
Install the GC Adapter udev rule on Linux

### PR DESCRIPTION
**Pull request by linkmauve**
This makes it readable by the user, and thus usable without manual system modification.

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3803)

### CODE REVIEW

**Comment by jcowgill** [comment]
See #2510 and #3670. This has already been discussed quite a lot.

**Comment by linkmauve** [comment]
I wasn’t aware of those before opening this PR, but it seems the issue pointed by #2510 that the rule should use TAG+="uaccess" has been fixed in the latest file, and when I compare with how the 70-uaccess.rules file does on my system it’s the exact same.

This PR lowers the amount of downstream changes required for packaging, so I think it’s overall a good change.  Even in the odd chance that a distribution would want not to ship this file they could simply remove it post-`make install`.

**Comment by RisingFog** [comment]
Is this PR valid with 3670 being merged?

**Comment by clinchergt** [comment]
It's valid but it's about whether we want the packagers to install the rule or dolphin itself

**Pull request closed without merging**
