### PR TITLE
NetPlayClient: Minor changes

### PR DESCRIPTION
**Pull request by lioncash**
Should be separated fairly well for individual reviewing.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3567)

### CODE REVIEW

**Comment by delroth** [comment]
That's a really really nice cleanup. Thanks a lot! Just one nit, feel free to merge once adressed/ignored.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/NetPlayClient.cpp, line 625 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3567#-K8s-l0iOzibEQs0xOwz:-K8s-l0iOzibEQs0xOx-:1341608264) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d41429dc828f63e7ae709cb7ddb842faafa843f4/Source/Core/Core/NetPlayClient.cpp#L625)):*
Nit: maybe inline this in the .h?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3567#-:-K8s1-vr5MsJqJNR8vil:181178263)*

**Comment by delroth** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3567)*

**Comment by degasus** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3567)*

**Comment by degasus** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3567)*

**Comment by Temperhoof** [comment]
All we need now is for NetPlay to be capable of Loading Game Data from a Single Users, Ideally the HOST to allow larger Netplay games. Haven't had it since Build 6498 and it needs to be brought back.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3567#-:-K8tVOvEUIM4_DYEAW1X:-867095641)*

**Pull request merged**
