### PR TITLE
TAS dialog: Toggle analog inputs between TAS and regular input

### PR DESCRIPTION
**Pull request by rukai**
Solves https://bugs.dolphin-emu.org/issues/9325

As suggested by @Sonicadvance1 I have added a toggle button for each analog input allowing the user to have fine grained control over whether each analog input should be taken from the TAS input or its regular input. Digital inputs remain as they were, deciding which input to take automatically
`input = TASInput && regularInput`

Previously the code assumed a keyboard input which is not compatible with analog inputs.

@MaJoRoesch Can you please make a proper icon for this?

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3609)

tasanaloglockprdemo

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Got a screenshot?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/DolphinWX/TASInputDlg.h, line 147 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609#-KA-vsW-bkpyX2mm_ZNg:-KA-vsW-bkpyX2mm_ZNh:-1103490265) ([raw file](https://github.com/dolphin-emu/dolphin/blob/908bd9a3003831073cf002e5b7c2b87b4d0e0840/Source/Core/DolphinWX/TASInputDlg.h#L147)):*
Alignment looks off here; Tabs for indent., then spaces for alignment if necessary - this line seems to be all spaces.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609#-:-KA-w2VjQ5b-eOkL2k6u:1128554305)*

**Comment by BhaaLseN** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609)*

**Comment by rukai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/DolphinWX/TASInputDlg.h, line 147 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609#-KA-vsW-bkpyX2mm_ZNg:-KA-zxrgA67UtZ5_jWFe:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/908bd9a3003831073cf002e5b7c2b87b4d0e0840/Source/Core/DolphinWX/TASInputDlg.h#L147)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609)*

**Comment by JosJuice** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[Source/Core/DolphinWX/TASInputDlg.cpp, line 44 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609#-KA0EdzQEVqTQud-UrSA:-KA0EdzQEVqTQud-UrSB:-1052245620) ([raw file](https://github.com/dolphin-emu/dolphin/blob/1ff65244031e4dd573f5ccb46ccaac8ed8cd2405/Source/Core/DolphinWX/TASInputDlg.cpp#L44)):*
This is wrong. The original alignment is the correct one.

---

*[Source/Core/DolphinWX/TASInputDlg.h, line 30 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609#-KA0Et4rNlruQvgzhZez:-KA0Et4rNlruQvgzhZf-:1662569705) ([raw file](https://github.com/dolphin-emu/dolphin/blob/1ff65244031e4dd573f5ccb46ccaac8ed8cd2405/Source/Core/DolphinWX/TASInputDlg.h#L30)):*
Same here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609)*

**Comment by lioncash** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609#-KA0PgfXZjEiCuQaONz8:-KA0PgfZpb-_exYrxAJh:1996125630) (no related file):*
There should be a tooltip set for the lock buttons that explain what they do. Also the lock buttons should be considerably smaller to fit the UI. It's almost overlapping the depression that indicates the shoulder buttons. It would likely be a better idea to place the button under the slider value indicators for them as well.

---

*[Source/Core/DolphinWX/TASInputDlg.cpp, line 1137 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609#-KA0ODNJCoSfd_aw5isv:-KA0ODNJCoSfd_aw5isw:-843635930) ([raw file](https://github.com/dolphin-emu/dolphin/blob/1ff65244031e4dd573f5ccb46ccaac8ed8cd2405/Source/Core/DolphinWX/TASInputDlg.cpp#L1137)):*
This event table can be replaced with a Bind call in the constructor .

```cpp
Bind(wxEVT_TOGGLEBUTTON, &TASInputDlg::OnLockToggle, this);
```

---

*[Source/Core/DolphinWX/TASInputDlg.h, line 11 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609#-KA0NswEiA3LPBdvwyzK:-KA0NswEiA3LPBdvwyzL:-1797076754) ([raw file](https://github.com/dolphin-emu/dolphin/blob/1ff65244031e4dd573f5ccb46ccaac8ed8cd2405/Source/Core/DolphinWX/TASInputDlg.h#L11)):*
this can be replaced with a forward declaration. The include can then be moved to the cpp file to avoid cluttering anything that includes the TAS header.

---

*[Source/Core/DolphinWX/TASInputDlg.h, line 66 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609#-KA0NjH3JHAAoKWOIbuQ:-KA0NjH42FeIdDECWQum:-670486778) ([raw file](https://github.com/dolphin-emu/dolphin/blob/1ff65244031e4dd573f5ccb46ccaac8ed8cd2405/Source/Core/DolphinWX/TASInputDlg.h#L66)):*
lowercase `tas`

---

*[Source/Core/DolphinWX/TASInputDlg.h, line 148 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609#-KA0N4ltq0uNAuCR5_ff:-KA0N4ltq0uNAuCR5_fg:176958988) ([raw file](https://github.com/dolphin-emu/dolphin/blob/1ff65244031e4dd573f5ccb46ccaac8ed8cd2405/Source/Core/DolphinWX/TASInputDlg.h#L148)):*
`m_locked_graphic`
`m_unlocked_graphic`

---

*[Source/Core/DolphinWX/TASInputDlg.h, line 149 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609#-KA0NGCsMyiRtEAMMa3x:-KA0NGCtN0t0AAQEHfIF:-1855239627) ([raw file](https://github.com/dolphin-emu/dolphin/blob/1ff65244031e4dd573f5ccb46ccaac8ed8cd2405/Source/Core/DolphinWX/TASInputDlg.h#L149)):*
This should be placed with all the other functions.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3609)*

**Comment by RisingFog** [comment]
@rukai anything left with this PR?

**Comment by rukai** [comment]
@RisingFog Yeah, still need a proper icon for it. @MaJoRoesch seems really busy these days, is there anyone else who could make/find one? Or alternatively is there a more suitable UI element we could use here instead of a lock icon?

**Comment by Pringo** [comment]
Not sure if this is really related to the PR but is there a reason why the circle is being rendered (1, 1) off-centre or is that intended? I know that happens in master too.

**Comment by Pringo** [comment]
The issue I noted in my previous post turned out to be a wxWidgets problem and is fixed now as of [5.0-211](https://dolphin-emu.org/download/dev/fac7d090919d260aa4c0e62d4e3e5e4f31b921ae/).

**Comment by RisingFog** [comment]
This PR will need to be rebased.

If I don't see any response within two weeks, I'll rebase and re-submit a PR for this.

**Comment by shuffle2** [comment]
Moving to https://github.com/dolphin-emu/dolphin/pull/4265

**Pull request closed without merging**
