### PR TITLE
Update to support miniupnpc 1.9 API version 14

### PR DESCRIPTION
**Pull request by OrdinaryMagician**
So, after I got a package update for miniupnpc on my system, I noticed Dolphin failed to build with something about upnpDiscover() called with too few arguments. I went on to investigate and found that the function now takes an additional parameter for TTL. So... being a complete stranger to using CMake and whatnot, I began an adventure to fix this problem.

I'm using the default value of 2, and I'll be honest, I haven't actually tested this thing thoroughly since I have no one to do netplay with. It does build and the emulator works.

Sorry for the whole thing being scattered across 5 commits, again, it's my first time working with CMake. Please don't hurt me.

### CODE REVIEW

**Comment by shuffle2** [comment]
please merge the commits

**Comment by OrdinaryMagician** [comment]
How do I do that?

**Comment by Antidote** [comment]
git rebase -i HEAD~<number of commits>
Then change the the 'p' to 's' up to your first commit (but leave it at 'p').

**Comment by CryZe** [comment]
Or just ``git reset --soft 16957fcaec6f6f7e22b41d30210a3b4c0061cb10`` and then ``git commit`` to make a new clean commit.

**Comment by Tilka** [comment]
@OrdinaryMagician It's probably easier to explain stuff if you join #dolphin-dev (on freenode).

**Comment by sigmabeta** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
