### PR TITLE
GZ2E01: Add Quick Item Select ActionReplay code

### PR DESCRIPTION
**Pull request by CyberShadow**
As suggested in https://github.com/dolphin-emu/dolphin/pull/6105, this adds the AR code part to allow single-key item selection for Legend of Zelda: Twilight Princess (GCN/NA), an enhancement I found extremely useful.

The ActionReplay code was generated by this program:
https://gist.github.com/CyberShadow/02da7df8322400840f8de83d95d6f2ed#file-ar_tpkey-d

I'll add the remaining part (description + input profile) to the wiki once this is merged.

### CODE REVIEW

**Comment by JosJuice** [comment]
Are you sure that this is going to be accepted on the wiki and is going to stay on there for a reasonable amount of time? Otherwise, it doesn't make sense to put "read wiki" in the description of the code. As far as I know, this kind of code isn't of the type that the wiki normally allows.

**Comment by CyberShadow** [comment]
> Are you sure that this is going to be accepted on the wiki and is going to stay on there for a reasonable amount of time?

Not for me to decide, but this seems in line with existing enhancement sections on wiki game pages.

> As far as I know, this kind of code isn't of the type that the wiki normally allows.

This is why this is a submission to the INI file instead of the wiki. See the discussion in #6105, though - I think codes like this (which make sense only on an emulator) ought to be accepted as well.

**Comment by xerxespersrex** [comment]
You can propose a change to the wiki's AR/Gecko code standard on [General Discussions](https://wiki.dolphin-emu.org/index.php?title=Project:General_Discussions) if you want. The debate's been had multiple times in the past though, and it's a wonder that the codes that are allowed on there even managed to slip past (once upon a time, there was no "enhancements" sections at all, and codes were strictly not allowed besides the Triforce games that needed them).

**Comment by JosJuice** [comment]
No changes have been proposed to the wiki's policy, so I'm going to close this PR for now. But if you want to, feel free to upload the code to the forums along with a description.

**Comment by CyberShadow** [comment]
@JosJuice Can we put the documentation somewhere else if not the wiki?

**Comment by JosJuice** [comment]
No, we don't really have any place that fits for this kind of thing. (You can put it on the forums if you want to, but that's not good enough for being able to add the code to the game INI in my opinion.)

**Comment by CyberShadow** [comment]
OK. The problem is that it's not discoverable there (nobody who would play this game would think to check there), and once it's scrolled off the first page, it might as well have never existed.

I'm obviously biased, but I think the code is a massive usability improvement when playing with a keyboard, and needed a bit of R&D to develop.

**Comment by CyberShadow** [comment]
@JosJuice Could you please advise a course of action to make this code discoverable to Dolphin users who intend to emulate this game?

**Comment by JosJuice** [comment]
I don't think I have any better suggestion than posting it on the forums, even though there are discoverability problems with that.

**Pull request closed without merging**
