### PR TITLE
Switch to codehandleronly.bin

### PR DESCRIPTION
**Pull request by gamemasterplc**
It will support up to about 400 codes more than the usual 231 of codehandler.bin.

### CODE REVIEW

**Comment by mimimi085181** [comment]
I think you shoudl either add the source code, or leave it as it is: Just have the binary. There are 2 problems with the link: 1. The code might be deleted from that source in a few years and then the link is pointless. 2. The original source for this is Gecko OS, all other projects have copied it from there.

If i remember correctly, this was discussed years ago and somebody wanted to keep the normal codehandler, the one with the usb gecko support, for some reason. Even though i'm not sure you can actually use that in Dolphin, maybe it would be a better idea to make this optional. Maybe tie it to a check whether memory card 1 or 2 is set to an usb gecko?

**Comment by gamemasterplc** [comment]
I hardly know anything about C but know ASM well.

**Comment by gamemasterplc** [comment]
Who was that somebody who wanted the codehandler with USB Gecko support.

**Comment by skidau** [comment]
Do you have the .s for this codehandleronly bin? Does the source contain your "invalidate icache" fix for the codehandler?

**Pull request closed without merging**
