### PR TITLE
Support Quad-Buffered stereoscopy.

### PR DESCRIPTION
**Pull request by Armada651**
This is the ideal stereoscopy mode that is officially supported in both the OpenGL and DirectX API. This mode is only supported on Nvidia Quadro cards and AMD cards from Radeon HD 6000 series and up.

This mode is also known as AMD HD3D, which is the competitor of Nvidia 3D Vision.

This PR should be tested thoroughly, though I'm not sure if anyone has the necessary hardware.

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/1792)

### CODE REVIEW

**Comment by comex** [comment]
@dolphin-emu rebuild

@degasus Is this safe to merge (even if it doesn't necessarily work correctly)?

**Comment by degasus** [comment]
@comex I think so, but this PR will drop windows vista support :/

**Comment by shuffle2** [comment]
Should be possible to (relatively cleanly) maintain vista support...just drop back to older dxgi if QI fails for newer ones.

However, this is a good time to bring up dropping vista support...should we do it when win10 is released? It seems to make sense to even focus on win10-level users, instead of any other windows version (this reasoning mirrors Microsoft's DirectX12 logic; "we are giving free upgrades to everyone, so developers should only target win10/dx12 [shuffle2 note: dx12 has feature level 11 support]").

**Comment by rexcaptain501** [comment]
Regarding to Vista support, would it be a good idea to make a poll on the Site/Blog/Forum? Might be a good way to find out how many Vista users are around. Could also be a good opportunity to see what other Operating Systems people use (eg. XP 64-Bit/Vista/7/8/8.1/10).

**Comment by shuffle2** [comment]
what's the status captain @Armada651

**Comment by Armada651** [comment]
Waiting for confirmation that Vista support is dropped and that Quad-Buffering mode actually works for someone.

Will rebase this soon and resolve the conflicts.

**Comment by Pringo** [comment]
@Armada651 Windows Vista is officially not supported anymore with the [5.0 release](https://dolphin-emu.org/blog/2016/06/24/dolphin-50-release/).

**Comment by Fallcrest** [comment]
@Pringo Thank goodness for that. The less reason Vista has to still exist, the better. With this news, hopefully some progress can be made on the oldest open PR in Dolphin.

**Comment by DarthVitrial** [comment]
Are there any other benefits to switching to dxgi 1.2?

**Comment by mirh** [comment]
Why Vista dropping was even a requirement?
Can't you just hide everything behind a single "3D" checkbox?

If at loading time only < 1.2 DXGI is available prevent it from being toggleable and don't use any newer shiny function.

**Comment by Armada651** [comment]
@mirh This Pull Request hasn't been merged and it is not the reason Vista support was dropped.

Also, Dolphin may still work on Vista for now, but that will change in the future. You should still be able to upgrade to Windows 10 for free before the end of the month.

**Comment by mirh** [comment]
I know Vista wasn't dropped for this. 
But there's a difference between just conservatively stopping to bother for potential bugs in older Windows versions, and jumping on the microsoft "last or nothing" upgrade train. 

I'm of course delighted by your PR but I don't see which kind of "legacy" you would *hit* with newer code to be used on modern proper OS, and the old one left for those that don't care.

**Comment by Armada651** [comment]
Implementing fallbacks is more difficult than just "not using a shiny new feature", it takes time and increases code complexity.

In the case of Quad-Buffered Stereoscopy this means that adding support for this feature was simply not worth it when you consider the need for a fallback. That's why I held off on merging this Pull Request.

Now it is the oldest open Pull Request and Vista support has officially been dropped. It's about time we moved past Vista, don't you think?

**Comment by mirh** [comment]
I'm nobody to counter you, but I would assume it could be something as stupid as not using the new codepath when dxgi.dll version is < 6.2.9200.16492 ?
I mean: unless dxgi 1.1 functions aren't forward compatible with 1.2, I think it's not all that different from what pcsx2 is already doing with XAudio2 2.8 with respect to 2.7. 
Then, if in this case the emulator doesn't crash at start and I misunderstood what "drop" actually meant I apologize. 

> It's about time we moved past Vista, don't you think?

And my point wasn't about "continuing to support it". If it breaks for god knows which reason, peace. 
But I didn't believe a little _if_ could be such of a problem.

**Comment by Armada651** [comment]
It's not one little if-statement, the entire API for creating a swap chain has changed. So we'd need to keep two code paths alive. One for the obsolete DXGI 1.0 API and one for the DXGI 1.3 API.

And when you think about how many people will actually be able to use Stereoscopic Quad-Buffering, that really doesn't seem to be worth the trouble. The amount of users being able to use this feature is likely to be less than the amount of users still using Vista.

**Comment by mirh** [comment]
Did you mean 1.2?
Anyway I see it, thanks.

**Comment by RisingFog** [comment]
What's the current status of this PR?

**Comment by Parlane** [comment]
Rebase?

**Comment by Armada651** [comment]
I'm closing this PR as I don't have the necessary hardware to test this functionality with. I'll keep the branch around in my repo for people interested in finishing and testing Quad-Buffering support.

**Comment by shuffle2** [comment]
fwiw, Vista support (from MS) ends in about a month.

**Pull request closed without merging**
