### PR TITLE
Qt: Update graphics backend description to include Vulkan

### PR DESCRIPTION
**Pull request by 8times9**
Updates the description for the graphics backend as it didn't include Vulkan.

### CODE REVIEW

**Comment by leoetlino** [comment]
Changes LGTM, but please squash your commits. (git rebase -i, change the second `pick` to `fixup`)

**Comment by 8times9** [comment]
Done

**Comment by leoetlino** [comment]
Looks like there's a lint failure which needs to be fixed

**Comment by 8times9** [comment]
I'm new to git and have made a few mistakes here, I think it's best I close this and start fresh with a separate pull request.

**Pull request closed without merging**
