### PR TITLE
Add OS X as a unix-like system (readme.md)

### PR DESCRIPTION
**Pull request by TijmenW**
Apple Mac OS X is a unix-like system.

### CODE REVIEW

**Comment by BhaaLseN** [comment]
The point of the Readme is indicating that other, not explicitly listed Unix-likes might work. OSX is considered supported anyways and doesn't need to be included there twice.

**Comment by TijmenW** [comment]
Ok, but why is linux then included twice?

**Comment by BhaaLseN** [comment]
Is it? It says "other than Linux", if you meant that. The line is generally pointed at BSD and the likes, provided you can get the prerequisites and build system up and running.

**Comment by Tilka** [comment]
Just say "Other Unix-like systems might work ..." [/bikeshed]

**Comment by Buddybenj** [comment]
Technically, Mac OS X is Unix, not Unix-like. So, the current way is correct.

**Comment by comex** [comment]
Can we just change it to 'Other Unix-like systems'? :p

**Pull request closed without merging**
