### PR TITLE
[Android] Remove CPUHelper Class

### PR DESCRIPTION
**Pull request by Tsunamical**
Remove CPUHelper class.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3704)

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
This java class isn't even being used anymore, the bit using it has been removed and isn't planned to be reintroduced. Might as well as just remove the class entirely instead of extending it.

**Comment by Tsunamical** [comment]
Okay, I noticed it was unused as detected by Android Studio, I just wasn't sure we were completely ditching it. I can just rebase this pr and remove it if you'd like.

**Comment by Sonicadvance1** [comment]
That'd work.

**Comment by Tsunamical** [comment]
Done! @Sonicadvance1

**Comment by Sonicadvance1** [comment]
@dolphin-emu-bot rebuild

**Comment by Sonicadvance1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3704)*

**Pull request merged**
