### PR TITLE
Revert "[Android] Load the game banner from the ROM and use it if no screenshot is available"

### PR DESCRIPTION
**Pull request by JosJuice**
This reverts PR #5118.
.
We have gotten reports of it making Dolphin crash when there are non-GC games in the TV UI. Also, the banner colors seem to be wrong. See https://github.com/dolphin-emu/dolphin/pull/5118#issuecomment-296382435 for details.

### CODE REVIEW

**Comment by mahdihijazi** [comment]
@JosJuice do we have the stack trace from these crashes? can I reproduce it by loading wii only games on the Android TV?

**Comment by JosJuice** [comment]
> do we have the stack trace from these crashes?

No.

> can I reproduce it by loading wii only games on the Android TV?

I'm not sure. All I know is what's written at https://forums.dolphin-emu.org/Thread-dolphin-crashes-when-going-to-wii-tab

**Comment by JosJuice** [comment]
I'm going to merge this revert in four days unless someone disagrees or there's progress on fixing the crash.

**Comment by degasus** [comment]
I haven't seen such a crash report any more. As this is just a revert, let's close it for now.

**Comment by JosJuice** [comment]
I've continued setting occasional reports of it. I'm fine with having this PR closed, though.

**Pull request closed without merging**
