### PR TITLE
InputCommon: Add "Dead Zone" and "Calibration Period" to raw gyro inputs.

### PR DESCRIPTION
**Pull request by jordan-woyak**
Mapping indicator draws a line representing the angular velocity relative to the configured dead zone assisting configuration.
Sphere outline turns blue during calibration which occurs after the configured period of data is as stable as the configured dead zone.
image

This fixes horizontal drift of IMU pointing with imperfectly calibrated controllers.
https://bugs.dolphin-emu.org/issues/11971

### CODE REVIEW

**Comment by MayImilae** [comment]
Sorry, I don't really have a better word for you. Dead Zone is just so ubiquitous. ┐(´-｀)┌

**Comment by Miksel12** [comment]
Myabe "Gyration threshold"?

**Comment by jordan-woyak** [comment]
Hmmm. I guess "Dead Zone" is an okay enough name that people will understand.
I think "Gyration threshold" will scare people. :P

**Comment by Miksel12** [comment]
Probably true, haha.

**Comment by jordan-woyak** [comment]
Included in PR #8575

**Pull request closed without merging**
