### PR TITLE
ConfigManager: Vertical Alignment

### PR DESCRIPTION
**Pull request by Stevoisiak**

### CODE REVIEW

**Comment by bb010g** [comment]
How is this different than #2206?

**Comment by Stevoisiak** [comment]
The scope is really the only difference. Limiting this one to areas where I think vertical alignment makes more sense.

For instance, most of ConfigManager was already vertically aligned.

**Comment by Tilka** [comment]
meh, lgtm

**Comment by BhaaLseN** [comment]
I still think this kind of alignment is only adding noise/work in places where it isn't really necessary, sorry. The table on top (```g_HKData```) makes sense because its easier to read and helps you see patterns (yes, its a table with 3 columns!).
Inside functions, I usually only align within blocks but not within lines - and we pretty much do the former all over the place anyways.

**Pull request closed without merging**
