### PR TITLE
msbuild: don't explicitly set _SECURE_SCL

### PR DESCRIPTION
**Pull request by shuffle2**
just some old cruft

### CODE REVIEW

**Comment by iwubcode** [comment]
Should we be using `_ITERATOR_DEBUG_LEVEL` instead now?

**Comment by shuffle2** [comment]
yes; well, we're using the default values of _ITERATOR_DEBUG_LEVEL

**Comment by iwubcode** [comment]
Ah missed that it is defaulted to on.  Nice!  Thanks

**Review by iwubcode — APPROVED** [review]

**Comment by AdmiralCurtiss** [comment]
Makes sense to me.

**Pull request merged**
