### PR TITLE
[UI] Make NetPlay UI bigger and neater

### PR DESCRIPTION
**Pull request by Lionel07**
This PR does 5 things:
* It increases the default small size of the NetPlay window to a larger
and more appealing size.
* It cleans up and reorganizes a bit of the NetPlay Setup UI code.
* It moves the Direct or Transversal Selector to be more appealing and
nice looking.
* The Direct or Transversal also gets a label and nicer text, and a
spacer.
* The language and text of the Netplay Window have been improved.

Images:

Before:
ss 2016-05-01 at 10 19 56
ss 2016-05-01 at 10 20 05

After:
ss 2016-05-01 at 11 52 29
ss 2016-05-02 at 12 29 15

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3809)

### CODE REVIEW

**Comment by aserna3** [comment]
@dolphin-emu-bot rebuild

**Comment by aserna3** [comment]
The code LGTM. A lot easier to read. I'm not going to comment on the UI changes because I don't really care. Bikeshed away

**Comment by aserna3** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp, line 72 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809#-KGjJ-kZEg_K3eDqS4Ks:-KGjJ-kZEg_K3eDqS4Kt:-1831241583) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a7da7e69e89611da005137ec59b7eecdc9caff2f/Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp#L72)):*
Please fix the trailing whitespace here, linter will fail with trailing whitespace.

---

*[Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp, line 74 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809#-KGjJ9kdxQZpeaFC4tT9:-KGjJ9kdxQZpeaFC4tTA:1243838654) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a7da7e69e89611da005137ec59b7eecdc9caff2f/Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp#L74)):*
And here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809)*

**Comment by Lionel07** [comment]
Done. Thank you for being quick with the response c:

**Comment by aserna3** [comment]
No problem. And to make things clean in git history please squash commits for PR fixup things (Like linter fixes) into one commit. If you don't know how to do this, google and people in #dolphin-dev on freenode can help.

In the future, you can modify an already pushed commit by doing 'git commit --amend' and 'git push --force', however I only recommend doing that to fix up small things just because it's quick. Rewriting history is messy.

**Comment by aserna3** [comment]
@dolphin-emu-bot rebuild

**Comment by Lionel07** [comment]
There, I think that's done it.
Thank you for being patient and explaining things. I'm still rather new to Pull Requests.

**Comment by aserna3** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809)*

**Comment by lioncash** [comment]
You may want to add slight padding to the buttons so they aren't right up against the colon after "Connection Type". If it was already like that, feel free to ignore this.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809#-:-KGjOF7qIC5nntBPYTIi:577232553)*

**Comment by Lionel07** [comment]
Done.

**Comment by CoolOppo** [comment]
IMO, these changes are for the worse.

**Comment by Lionel07** [comment]
@CoolOppo Could you be more constructive? Tell me what you think should be included and I can see about tweaking it?

**My Reasons for the changes:**

1. The Setup Dialog I feel needed a better list and label, because having a non-aligned button in the corner with no text other then "Traversal" was not befitting of an emulator this good.
2. I feel like the bigger NetPlay window makes it nicer, less dense, and more "professional". If it's not to your liking, it can be resized anyways, so I believe that a bigger net-play window is nicer.

Though, I while I would love to make some changes based on your feedback, and will if I feel they're good ideas, I think at this point it's pushing into major bikeshedding territory..

**Comment by aserna3** [comment]
I'll put myself on record as liking the UI changes. Because whenever anybody does UI work, everybody who has done zero UI work pops up out of the woodwork and pretends they're an expert.

**Comment by Lionel07** [comment]
@aserna3 , can you poke buildbot?

**Comment by aserna3** [comment]
@dolphin-emu-bot rebuild

**Comment by E2xD** [comment]
I dislike these changes as well.

**Comment by Lionel07** [comment]
@E2xD Can you explain why? I'm willing to make edits if I feel they're necessary.
So: _Can you tell me exactly what I need to do in order to make the edits nicer?_

**Comment by aserna3** [comment]
See what I mean?

**Comment by Lionel07** [comment]
Mhm. Thought they'd at least respond. LGTM?

**Comment by aserna3** [comment]
I'd like @MaJoRoesch to take a look at this, seeing that she actually knows a thing or two about UX. But I'm fine with it.

Can you update the screenshots with your tweaks?

**Comment by aserna3** [comment]
Some before screenshots would be nice too for visual comparison

**Comment by Lionel07** [comment]
Updated with Screenies and comparison.

**Comment by FishamanP** [comment]
Initial window is definitely an improvement. Nothing I can think to add.
The second window seems a little too large for my tastes; in particular, the Chat box is far wider than I think necessary, and maybe a tad tall as well. Of course, I'm biased because I never use Chat anyway.

**Comment by aserna3** [comment]
The only change made in the lobby was that the window was made bigger by default. The proportions of the text windows are the same....

The setup window is a significant improvement. Before we had a drop down box with no explanation of what it was, which was stupid. As well as lacking any sort of padding from the edge of the window before these changes. Also stupid. This is much better.

**Comment by MaJoRoesch** [comment]
Everything seems fine to me! The addition of "Connection Type" is something that was definitely needed. The misalignment is a little annoying, but it would be fairly easy to solve. At the very least the nickname block could be expanded to the right until it ends at the same point as the connection type dropdown. That would even it up a bit!

**Comment by Lionel07** [comment]
Hold on, fighting git. I've fixed the things and have a screenie, here
ss 2016-05-01 at 11 52 29

ss 2016-05-01 at 11 52 53

**Comment by Lionel07** [comment]
Gave love and attention to the NetPlay window besides changing it's size (before and after screenshots show more room and nicer phrasing in the options), This makes it look cleaner.

Before:
ss 2016-05-02 at 12 30 35

After:
ss 2016-05-02 at 12 29 15

**Comment by Parlane** [comment]
Looks much better now!

**Comment by Lionel07** [comment]
T﻿hank you! hopefully it'll get merged so everyone can see it

**Comment by aserna3** [comment]
@dolphin-emu-bot rebuild

**Comment by aserna3** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Core/DolphinWX/NetPlay/NetWindow.cpp, line 205 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809#-KGlTGAwbrj9nkuZBxlZ:-KGlTGAwbrj9nkuZBxl_:224168322) ([raw file](https://github.com/dolphin-emu/dolphin/blob/2eaf07c7eac3745e6052e53899fcdd5d7e328735/Source/Core/DolphinWX/NetPlay/NetWindow.cpp#L205)):*
Linter says there is trailing whitespace at line 205.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809)*

**Comment by aserna3** [comment]
@dolphin-emu-bot rebuild

**Comment by aserna3** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809)*

**Comment by Lionel07** [comment]
Alright, everything seems good now. The fate of this is now up to whoever gets to press "Merge".
Thanks for making my second PR exciting. It's been a learning experience.

**Comment by JosJuice** [comment]
How does this interact with https://github.com/dolphin-emu/dolphin/pull/3588? Is this PR appropriate to merge this far into the feature freeze?

**Comment by aserna3** [comment]
As far as I can tell #3588 was a bit too invasive to merge during feature freeze. I see this PR as a safe way of fixing the worst problems with the UI now, and when 5.0 releases, we can look into getting 3588 merged as a better solution. I just greatly dislike how netplay's UI is right now and feel like if we have this option to fix the worst problems safely, we should take it.

**Comment by Lionel07** [comment]
@JosJuice Oh dear. I didn't know that PR existed.
They both do some nice things, but this doesn't add new features, merely labeling and shifting of already existing elements to make netplay nicer.
I don't know how they interact, but I can say that it's way closer to current Dolphin then that PR. I feel it'd be appropriate during the feature freeze, as it's basically just conservative #3588. It's similar to a "backport" I suppose.
@aserna3 said it well.

**Comment by JosJuice** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp, line 57 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809#-KGlvaC-ccPUk8oAKbec:-KGlvaC0OmFxYI53re5W:-1188249426) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a867a125a8bd9a1726abba85713cc40a01e05443/Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp#L57)):*
Space after each comma. Don't have a space before the colon in the string.

---

*[Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp, line 76 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809#-KGlvhkZ3iageAWY9zXL:-KGlvhkZ3iageAWY9zXM:-1188249426) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a867a125a8bd9a1726abba85713cc40a01e05443/Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp#L76)):*
Space after each comma. Don't have a space before the colon in the string.

---

*[Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp, line 81 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809#-KGlvkRq0qmGIbkj4dcA:-KGlvkRrzsmf0PBevbNW:-1705898155) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a867a125a8bd9a1726abba85713cc40a01e05443/Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp#L81)):*
Space after each comma.

---

*[Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp, line 102 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809#-KGlw9xa-G8xjwGLv-1R:-KGlw9xa-G8xjwGLv-1S:-25600232) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a867a125a8bd9a1726abba85713cc40a01e05443/Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp#L102)):*
Would it be okay to remove the space in the translatable string, e.g. by doing `_("Traversal Server:") + " "`? It would probably make things easier for translators.

---

*[Source/Core/DolphinWX/NetPlay/NetWindow.cpp, line 130 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809#-KGlvn1a_kv-VB5k8i-V:-KGlvn1bxekA7XvESNyP:-1705898155) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a867a125a8bd9a1726abba85713cc40a01e05443/Source/Core/DolphinWX/NetPlay/NetWindow.cpp#L130)):*
Space after each comma.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809)*

**Comment by JosJuice** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp, line 76 \[r5\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809#-KGlvhkZ3iageAWY9zXL:-KGm0k-erjdU-_dn8P6e:-1477238196) ([raw file](https://github.com/dolphin-emu/dolphin/blob/a867a125a8bd9a1726abba85713cc40a01e05443/Source/Core/DolphinWX/NetPlay/NetPlaySetupFrame.cpp#L76)):*
` ,wxDefaultPosition` is supposed to be `, wxDefaultPosition`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809)*

**Comment by Lionel07** [comment]
Whoops, missed that. Should be all good now.

**Comment by MaJoRoesch** [comment]
Much better! Nice things are nicely aligned with padding! ...I should have mentioned the padding, whoops. Oh well, you got it!

**Comment by Lionel07** [comment]
Thank you c: hopefully we'll get this merged and people won't be in major design-pain anymore.

**Comment by aserna3** [comment]
@dolphin-emu-bot rebuild

It LGTM. People might be slow to merge because we're very very careful during feature freeze. To any merge people though, I'd like this in before 5.0 please.

**Comment by Lionel07** [comment]
Alright, got it. c:

**Comment by Lionel07** [comment]
Hey, mind reviewing the code on reviewable so it shows as a check?

**Comment by aserna3** [comment]
Reviewed 1 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3809)*

**Comment by Parlane** [comment]
Thanks @Lionel07

**Comment by Lionel07** [comment]
No problem. Thank you all for being nice, pleasant, and helping me with what I think is my second pull request ever.

**Pull request merged**
