### PR TITLE
Fix TitleDatabase

### PR DESCRIPTION
**Pull request by JosJuice**
a2a1e04 regression.

### CODE REVIEW

**Comment by dreamsyntax** [comment]
Is there a reason this regression was done?

Prior to this commit the Title field would be pulled from the game's DOL.
This is preferred when dealing with multiple modified copies of a game in the list.
@JosJuice

**Comment by JosJuice** [comment]
> Is there a reason this regression was done?

The regression was because I overlooked that the temporary `std::string` gets destroyed before we use the `std::string_view` again. (Most likely I applied less thinking and testing to it than I usually would since the change to `std::string_view` was done in response to a review comment.) Nothing more than a simple mistake.

> Prior to this commit the Title field would be pulled from the game's DOL.

The DOL doesn't have a title field. I'm assuming you mean the opening.bnr file. You can get the old behavior back by turning off the setting Config > Interface > Use Built-In Database of Game Names.

**Comment by CookiePLMonster** [comment]
Does it truly solve the issue? Right now it relies on `line_view` which would also get invalid as soon as `line` is destroyed. Or is it that `StripSpaces` on `std::string` returns a `std::string` and now it's invoking it on `std::string_view`?

**Comment by JosJuice** [comment]
> Does it truly solve the issue? Right now it relies on `line_view` which would also get invalid as soon as `line` is destroyed.

We only need `line_view` to be valid until we've done the `emplace` (because the `emplace` converts to `std::string` when inserting into the map), so `line` becoming invalid after that is fine.

> Or is it that StripSpaces on std::string returns a `std::string` and now it's invoking it on `std::string_view`?

No, it always returns an `std::string_view`. (If it had returned an `std::string` we wouldn't have had any bug to begin with.)

**Pull request merged**
