### PR TITLE
Fix saving/loading screenshots for Android

### PR DESCRIPTION
**Pull request by mahdihijazi**
- Saving screenshot was broken for Android TV.
- Loading screenshots was broken because of the change in the name of the saved images from the native library.
- Remove obsolete menu item from Android TV.

### CODE REVIEW

**Comment by degasus** [comment]
@sigmabeta What do you think about this PR?

**Comment by sigmabeta** [comment]
Looks good. Excellent use of IntDef too. If this builds, LGTM.

**Comment by mahdihijazi** [comment]
hey @sigmabeta I am thinking of doing some changes for the Android TV, how I can propose the feature to make sure it worth the time to invest in? Do you guys have any TODO list for Android? or a channel to ask?

**Comment by JosJuice** [comment]
This kind of discussion usually happens in #dolphin-dev on freenode IRC. But because sigmabeta isn't on IRC as far as I know and there isn't really any other developer who cares much about Android right now, there's a chance that nobody will respond.

**Comment by brujo5** [comment]
For me still happens this in recent build.
screenshot_20170321-081900

**Comment by mahdihijazi** [comment]
@brujo5  this will patch will not pickup old screenshots, because the name has changed. You can delete them and create ones.

**Comment by brujo5** [comment]
Ok thanks

**Pull request merged**
