### PR TITLE
Android: Ignore failed bulkTransfers from wiimotes

### PR DESCRIPTION
**Pull request by zackhow**
When initializing some wiimotes, some input report reads error out. From debugging it appears
that some games send a request to read memory on the wiimote and get an input report that the memory does not exist. The next input report after this will error out, causing a crash.
So we return the read size of the previous input report, which is still located in wiimote_payload[index].
From testing, these failures only occur when initializing the wiimote or when emulation exits, never during normal gameplay. I know this is really hacky but I don't know enough about wiimotes to figure it out atm and this will allow the use of TR wiimotes for the time.

Some more digging revealed that the input report error is actually intended [here](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp#L500). Which means that we are getting the proper response. Still don't know why the next input report after getting the error report fails....
Output report: 17000017700001
Input report: 210000f817700000000000000000000000000000000000

### CODE REVIEW

**Comment by JMC47** [comment]
Seems to work with my TR Wii Remotes on the Shield T.V.

**Comment by nathanraiderxxx** [comment]
Anyone knows where is the issue on fatal frame 4 as is running in game
around 5 fps? Exynoss runs well fatal frame 2 but not 4 ..that is weird

Il Dom 16 Set 2018, 00:40 JMC47 <notifications@github.com> ha scritto:

**Comment by eludias** [comment]
This also fixes the crash for my two RVL-CNT-01 . So the patch also helps my non-TR remotes.

**Comment by zackhow** [comment]
So I guess it was an issue with all official wiimotes?

**Comment by zackhow** [comment]
I know this is a bandaid but it does fix emulation crashing and allows the use of official wiimotes. If this can't get merged in as it stands I can go back and try to figure out what is being done wrong when communicating with the wiimote/dolphin bar.

**Comment by Tilka** [comment]
> If this can't get merged in as it stands I can go back and try to figure out what is being done wrong when communicating with the wiimote/dolphin bar.

I would very much prefer that. Thanks for working on this.

**Comment by ScottESanDiego** [comment]
This fix worked for me with NVIDIA Shield TV + DolphinBar + Wiimote + Motion Plus add-on.

**Pull request closed without merging**
