### PR TITLE
More CMake updates for AudioCommon dependencies

### PR DESCRIPTION
**Pull request by Orphis**

### CODE REVIEW

**Comment by Orphis** [comment]
The Ubuntu error is likely to be a CMake cache issue.

**Comment by lioncash** [comment]
Nice! These should have been moved into their own find modules from the get-go.

**Comment by Orphis** [comment]
Do you have any idea who has access to the Ubuntu build machine? to nuke the build folder before merging this?

**Comment by lioncash** [comment]
I think that would be delroth

**Pull request merged**
