### PR TITLE
Allow EuRGB60 to be set via game ini.

### PR DESCRIPTION
**Pull request by RachelBryk**

### CODE REVIEW

**Comment by Buddybenj** [comment]
Bump.

**Comment by Linktothepast** [comment]
Hm, after seeing the comments in https://github.com/dolphin-emu/dolphin/pull/1798, could the issue i am having here is from using Greek Windows 7, that's why Rachel can't replicate it locally? Just an idea, since psennermann had something similar using Italian Windows 8.

**Comment by mimimi085181** [comment]
What's the status of this? I'd like to disable PAL60 for Okami PAL, because it causes issues there(white line on top of the screen, which happens on wii as well, and 35 fps instead of 30). But in general i like 60 fps better than 50.

**Comment by Stevoisiak** [comment]
I think one thing that might help mitigate this issue is if we automatically disabled Pal60 for NTSC games. (It can cause crashes in some scenarios, like Doc's Punch Out)

**Comment by comex** [comment]
I have a semi-new opinionated agenda: I want the open PR queue to be a list of things that either need Someone to take a look at them or will soon, so it's harder for PRs to fall down the list into oblivion.  Since this one has been pending author revision for a long time, I'm closing it.

**Pull request closed without merging**
