### PR TITLE
AX: make volume field signed

### PR DESCRIPTION
**Pull request by Tilka**
This fixes overly loud sounds in Freestyle Metal X ([issue 13120](https://bugs.dolphin-emu.org/issues/13120)).

### CODE REVIEW

**Comment by Pokechu22** [comment]
This seems like a plausible fix; I haven't attempted to confirm it though (I don't own Freestyle Metal X and don't want to dig through AX right now). I am curious as to what value of `cur_volume` was the game setting here, though.

----

Looking at how it's implemented:

https://github.com/dolphin-emu/dolphin/blob/ec69ed21733f25d11c3ebb34ff96814964515761/Source/Core/Core/HW/DSPHLE/UCodes/AXVoice.h#L424-L430

the maximum value of `32767` or `0x7fff` would be multiplied by the sample and then shifted by 15. Since `0x7fff >> 15 == 0` but `0x8000u >> 15 == 1`, I'm pretty sure this means that the volume is always reduced slightly (e.g. `(0x7fff * 0x7fff) >> 15 == 0x7ffe`, `(-0x8000 * 0x7fff) >> 15 == -0x7fff`).

The clamping would only apply if the volume and sample were both `-0x8000`, as `(-0x8000 * -0x8000) >> 15 == +0x8000` which would be clamped to `+0x7fff`. I don't think there's any cases where `-0x8000` could be generated (and clamped to `-0x7fff`) anymore. Even still, if they are using the normal saturation functionality in the DSP, it would be clamped to `-0x8000` through `+0x7fff`. In practice, this *probably* doesn't matter.

**Comment by Tilka** [comment]
> I am curious as to what value of `cur_volume` was the game setting here, though.

The volume is 0xFF64 aka -156 (delta is 0).

**Comment by Pokechu22** [comment]
>> I am curious as to what value of `cur_volume` was the game setting here, though.
>
> The volume is 0xFF64 aka -156 (delta is 0).

OK, so effectively `-0.00476`, which would behave basically the same as `0.00476`, but was instead being treated as `1.99524` (or 419 times larger, though I don't know how much louder that would actually be perceived as).

**Comment by Tilka** [comment]
Here is a comparison without the background music (careful, it's quite loud):

https://github.com/dolphin-emu/dolphin/assets/123798/225789a0-f0b2-47cb-9d03-ca4eca35657a

https://github.com/dolphin-emu/dolphin/assets/123798/bb29bce7-cca6-4813-85d9-8fa31e971ad8

**Comment by Pokechu22** [comment]
That's a pretty significant difference and definitely seems better (though I can't really hear the chickens at all in the fixed version). For the chickens specifically, does the game try to change the volume based on distance, or are they at a constant volume? I'm curious if there's some kind of overflow or something there. (Though this would also depend on the chickens actually existing in the world, which I'm not 100% sure is the case.)

**Comment by Tilka** [comment]
They do get louder when you get closer to a barn.

**Review by Pokechu22 — APPROVED** [review]
Seems plausible enough. I haven't done any testing though.

**Pull request merged**
