### PR TITLE
enet: Search for shared library

### PR DESCRIPTION
**Pull request by degasus**

### CODE REVIEW

**Comment by magumagu** [comment]
@dolphin-emu-bot rebuild

**Comment by comex** [comment]
I don't think this is a good idea.  There are a few modifications to enet I want to make soon:

- IPv6 support - some enet forks have implement this but upstream doesn't have it.  IMO, in 2015 no new application should omit IPV6, so this is important.

- Opportunistic resending - the current merged enet-using code doesn't have this at all.  My original enet branch supported it using a wrapper around stock enet, but I think it would be more elegant and have a bit less overhead to do this in enet itself (it wouldn't require changing the protocol).  This might be counteracted by the benefit of going stock, but considering the first point...

**Comment by degasus** [comment]
rebased.

@comex I think we should try to not fork our externals if possible. Are those features possible to include within enet directly? So projects will win.

**Comment by comex** [comment]
Well, I can try.  The problem is that judging by the history of pull request:

https://github.com/lsalzman/enet/pull/21

I'm not too enthusiastic about upstream accepting patches.

But maybe if I implement IPv6 without breaking ABI compatibility, lsalzman will be more interested.

**Comment by degasus** [comment]
@comex So do you think this should be merged as it is or shall I remove the global enet usage? I mean you're always free to revert this change on forking enet.

**Pull request merged**
