### PR TITLE
Post Processing: Dither Effect

### PR DESCRIPTION
**Pull request by Sam-Belliveau**
image
image
image

### CODE REVIEW

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by Sam-Belliveau** [comment]
Keep in mind, that the dithering effect depends on the Gamma of your display, so the screenshots will not appear to be the right color, but when you are using the effect, everything looks fine.

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by iwubcode** [comment]
My personal take on this, other devs may feel differently, is the same as most other post processing shaders that have come up in the past couple months:

1) The post processing system is being overhauled, see:  #10362 .  I will be purging many of the unnecessary shaders (or moving them to some non-Dolphin location) before that gets merged.
2) This seems very niche. I'd prefer to not bloat Dolphin's released shaders with these and instead leave in general purpose shaders.  Just like Reshade, these types of shaders are better provided by users *outside* Dolphin.  Either in a repo, on the forums, etc.  To that end, I tried to make installing user provided shaders easy.
3) For shaders that go into Dolphin, I prefer shaders that are in use in other systems (Reshade, Mame, etc).

**Pull request closed without merging**
