### PR TITLE
VertexShaderGen: Process the depth range in the vertex shader.

### PR DESCRIPTION
**Pull request by Armada651**
This PR fixes is an attempt to fix depth-range issues in Donkey Kong Country Returns, Starfox Adventures, Mini-Ninjas and Haruhi. These games all require slow depth because their depth range values go beyond the 2^24-1 limit.

As per PR #3587 it is known that some games have far values that are beyond the normal 2^24 range. It is also known as per PR #2534 that some games have depth ranges beyond the normal 2^24 range. Both these values had to be clamped, because neither DirectX nor OpenGL could handle oversized depth ranges.

Neither of these PRs solved their issues in an accurate way and it becomes clear that further workarounds would not solve it. As per @degasus suggestion this PR now processes the depth range in the vertex shader. The advantage is that we no longer have to clamp these values early and we can process them in a way that more closely matches the actual hardware.

As and added advantage this removes the D3D depth inversion which required special handling all across the code base.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3676)

### CODE REVIEW

**Comment by Armada651** [comment]
Trying to find a fix for SW3, some games with ridiculously large z range which somehow fails this method.

**Comment by Armada651** [comment]
And ofcourse it breaks mario tennis again. This PR needs some more work to tweak everything so every test passes.

**Comment by JMC47** [comment]
Mii Channel, Mario Tennis, and many others appear broken.

**Comment by Armada651** [comment]
@JMC47 Those should all be fixed now, waiting on FIFOCI for confirmation.

**Comment by Armada651** [comment]
Forgot to check for round-trip errors, compensating for the perspective division introduces a round-trip error.

**Pull request closed without merging**
