### PR TITLE
Option to allow free-look always on for stereoscopic 3d

### PR DESCRIPTION
**Pull request by longjoel**
Feature:

It is now possible to stream dolphin games to your phone using google cardboard and a number of different android apps. In conjunction with stereoscopic 3d, free look is a powerful feature and can significantly enhance gameplay in a number of games.

This feature adds a toggle to the graphics setting under enhancements => Stereoscopic 3d to allow for free-look to always be engaged. The current method of invoking free-look while wearing a VR headset is impractical.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3938)

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Please rebase your branch on top of latest master, instead of merging it in. Most easy way to do it would be `git rebase upstream/master feature/freelook` (given that our repository is a remote called upstream in your clone). Don't forget to fetch upstream first.
If you need help with that, join us on FreeNode #dolphin-dev

**Comment by longjoel** [comment]
I have no idea what I am doing :p

**Comment by BhaaLseN** [comment]
Since you left IRC, you might wanna do the following:
`git rebase -i dolphin-emu/master features/freelook`
then change the text editor that opens to something similar to that:
```
pick 325cc78 added some solid freelook stuff.
edit 8b6c022 fixes
pick 1418aae relocated control to stereoscopy
```
(delete all other lines. the hashes are important and should match for this run)
Once it stops, open up `git gui` and check "Amend last commit", then remove the changes from `Source/Core/DolphinWX/Frame.cpp` completely (they look like formatting changes that don't belong there; if there is something useful in there, leave only that around).
When you're done, call `git rebase --continue` and it should leave you with 3 commits in the end. If thats what you wanted, you can do that again, but change the "edit" to "fixup" so you'll be left with just two commits.

**Comment by longjoel** [comment]
This PR is such a mess. I am going to resubmit it after I get everything cleaned up.

**Pull request closed without merging**
