### PR TITLE
Move to Visual Studio 2015

### PR DESCRIPTION
**Pull request by shuffle2**
Currently this PR is in tiny commits so they can be looked at easily.
Once reviewed it will be squashed down.

### CODE REVIEW

**Comment by shuffle2** [comment]
blocked on #2218

**Comment by waddlesplash** [comment]
@shuffle2: FWIW, with latest VS2015, I just merged this into master locally and it built with no additional changes. Maybe the issues are solved?

**Comment by waddlesplash** [comment]
Other than the volatile problems, LGTM.

**Comment by shuffle2** [comment]
@dolphin-emu-bot rebuild

**Comment by shuffle2** [comment]
The commit is ready now, once @Parlane fixes the buildbot this should be merged to keep master building.

**Comment by shuffle2** [comment]
After reviewing the state of CRT libraries going forward, I decided not to package parts of it with dolphin anymore (the so-called "app-local deployment" method). App-local deployment was [originally not going to be supported at all](http://blogs.msdn.com/b/vcblog/archive/2015/03/03/introducing-the-universal-crt.aspx) but [as of VS2015 RTM, support is maintained](https://www.reddit.com/r/cpp/comments/3fqxj0/visual_c_2015_redist_dlls/ctr64yg).  
So while it's technically possible to do, I think it is much better to go with the "proper" method of telling people to run VCRedist (vcredist_x64.exe in our case). We could package this with dolphin, host it somewhere, or just give people instructions. Doing it this way ensures dolphin references the most up-to-date version of the binaries, prevents us from having to ship dozens(!) of DLLs with dolphin, and automatically deploys the correct files for the version of windows they're running on. I also doubt dolphin will be the first app doing this that people will try to execute, so it's likely most people won't even notice.

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Comment by shuffle2** [comment]
@dolphin-emu-bot rebuild

**Comment by MaJoRoesch** [comment]
They'll notice. They will SO notice!

**Pull request merged**
