### PR TITLE
Add TypeUtils.h unit test

### PR DESCRIPTION
**Pull request by Minty-Meeo**
TypeUtils.h was pretty cluttered.  A unit test should do this job just as well.

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
Uh, this seems just worse.

**Comment by Minty-Meeo** [comment]
If someone is going to change the behavior of existing structs in this file (unlikely), they can refer to the unit test to ensure it still behaves correctly.  Other Common utils have very similar unit tests.  Putting Foo and Bar in the detail namespace doesn't seem like enough to prevent a possible naming collision, since those are very generic names.

**Comment by sepalani** [comment]
I'm not against adding unit tests but removing `static_assert` which the goal is different sounds off to me. I don't think the unit tests are run automatically when you build locally. Plus removing the `static_assert` won't produce a compilation error anymore.

**Comment by Minty-Meeo** [comment]
Frankly, the static assertions are only checking the obvious.  I've seen few other things in the codebase with such paranoid compile-time checks.  They are not crucial.

**Comment by Minty-Meeo** [comment]
Would it be a fair compromise to add a comment stating this header has a unit test?

**Comment by Minty-Meeo** [comment]
Did the change to EnumMap in #11034.  As you can see, the behavior of what was formerly IsNOf becomes self-evident when split into the two things it's really trying to test and given self-documenting names.  As well, the MemberPointerInfo static asserts are simply testing properties of C++ itself.  I think that the unit test is more of a formality at this point.

**Comment by Minty-Meeo** [comment]
Lucky for those who don't approve of this idea, neither do I anymore.  I don't feel like writing unit tests is necessary for every self-evident type trait added in the Common Concepts PR, so I'll just leave the static asserts for MemberInfo.

**Pull request closed without merging**
