### PR TITLE
Separate option for Component Cable instead of combining it with Progressive Scan.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
See #2618, was previously included there.

[Advanced](http://i.imgur.com/0KUzvl2.png)

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3392)

### CODE REVIEW

**Comment by MaJoRoesch** [comment]
I am against relocating this to advanced. Compared to the CPU clock override, it is remarkably safe!

Also, doesn't both the wii and gamecube use the component cable for progressive scan? This kind of doesn't make any sense...

**Comment by ZephyrSurfer** [comment]
I think you misunderstood. It used to be in advanced tabs under the graphics configuration GUI

**Comment by badkarma12** [comment]
This doesn't make sense. Both the Wii and gamecube required component cables to use progressive scan do theres no readon to split the options and why move the Progressive scan checkbox from its current tab?

**Comment by JosJuice** [comment]
The point of separating component cable and progressive scan is being able to emulate having a component cable plugged in without having progressive scan enabled in the Wii settings. This ability is practically useless for regular users, though. See the discussion in #2532 for more details.

Like the others, I don't think these checkboxes fit in Config > Advanced.

**Comment by AdmiralCurtiss** [comment]
Yeah like I said in #2618, I'm not sure anymore if such an option even makes sense. Figured it'd be better to have a PR anyway since the code was already there from half a year ago, if no one thinks it's useful we can just ignore it.

**Comment by RisingFog** [comment]
What's the status of this PR?

**Comment by AdmiralCurtiss** [comment]
Like I said, this is a fairly useless option for the vast majority of users. If you want me to rebase it I can, but I'm inclined to just close the PR.

**Pull request closed without merging**
