### PR TITLE
Android: Optimize imports

### PR DESCRIPTION
**Pull request by Ebola16**
This changed more imports than I expected so let's see what the buildbot thinks about this.

### CODE REVIEW

**Comment by JosJuice** [comment]
Not that I really mind the change, but why is this titled "optimize"?

**Comment by Ebola16** [comment]
I ran the "Optimize Imports" feature of Android Studio.

**Comment by JosJuice** [comment]
I suppose its main effect is to remove unused imports, but it so happens that most of what it did to Dolphin's codebase was to reorder `androidx` imports...?

Maybe we could update Dolphin's coding style (`Source/Android/code-style-java.xml`) to put `androidx` right below `android`? https://stackoverflow.com/questions/62839554/android-studio-reformat-code-optimize-imports-order-not-working-properly/62844115#62844115

**Comment by Ebola16** [comment]
Like this?

**Review by JosJuice — APPROVED** [review]

**Review by lioncash — APPROVED** [review]

**Pull request merged**
