### PR TITLE
Use Consistent Spelling of "License"

### PR DESCRIPTION
**Pull request by Buddybenj**

### CODE REVIEW

**Comment by BhaaLseN** [comment]
You got a commit from Sonic caught up in there, that shouldn't happen.
Try a rebase: ```git rebase --onto dolphin/master license~1 license```
Replace ```dolphin``` with the name of the dolphin remote (which should be fully fetched first).

**Comment by Buddybenj** [comment]
I always find some way to screw it up lol. I fixed it myself by doing ```git rebase -i HEAD~2```, then delete the line with Sonic's commit.

**Comment by Buddybenj** [comment]
waddlesplash: It was referenced, but the .nsi referenced it as "license.txt", so the filename should not have been "licence.txt".

**Comment by waddlesplash** [comment]
Ah. LGTM

**Comment by Buddybenj** [comment]
Merge? @delroth

**Comment by phire** [comment]
@dolphin-emu-bot rebuild

**Comment by Buddybenj** [comment]
Bump.

**Comment by Buddybenj** [comment]
Bump.

**Pull request merged**
