### PR TITLE
Please merge my Chinese Translation

### PR DESCRIPTION
**Pull request by qingan1996**

### CODE REVIEW

**Comment by JosJuice** [comment]
Huh, a translation for Android? I'm not sure in what way we want to handle those... We used to have a Japanese translation a while ago, but it was removed due to being out of date, so right now we don't have any translations for Android at all.

But either way, we can't merge this PR in its current state, since it's replacing the English strings rather than adding a new folder for Chinese strings.

**Comment by Sarkie** [comment]
This is how you do translations in Android @qingan1996 

https://developer.android.com/studio/write/translations-editor.html

**Comment by mbc07** [comment]
Also, some strings of the Android port seems hardcoded in the source files...

**Comment by qingan1996** [comment]
Thank you for reminding me

2017年10月16日 下午3:38，"JosJuice" <notifications@github.com>写道：

Huh, a translation for Android? I'm not sure in what way we want to handle
those... We used to have a Japanese translation a while ago, but it was
removed due to being out of date, so right now we don't have any
translations for Android at all.

But either way, we can't merge this PR in its current state, since it's
replacing the English strings rather than adding a new folder for Chinese
strings.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dolphin-emu/dolphin/pull/6119#issuecomment-336804813>,
or mute the thread

**Pull request closed without merging**
