### PR TITLE
ScmRevGen: Set commits ahead to zero when on a tag

### PR DESCRIPTION
**Pull request by OatmealDome**
Prevents the current ref from being shown in the DolphinQt window title while HEAD is on a tag.

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
What exactly is this supposed to solve? This looks identical to master to me.

This PR:

grafik

Master:

grafik


(built with CMake, not the Visual Studio files)

**Comment by OatmealDome** [comment]
Sorry, I didn't explain it that well in the PR description. You also have to create the tag on a branch that's ahead of master:

1. `git checkout -b release-prep-2407`
2. Create any commit (in [the actual procedure](https://docs.google.com/document/d/1ZMktt1m3tY0114lEuQVnTLlxz6FuEkYHfB6KVyhzKNA/edit), the major version in `ScmRevGen` is bumped in a commit)
3. Create an annotated tag

Without the PR, I get this:

image

**Comment by AdmiralCurtiss** [comment]
Ah, okay yeah. That does indeed detect as 'n commits ahead of master' (which makes sense, I suppose) and show the branch name in the title without your fix.

**Review by AdmiralCurtiss — APPROVED** [review]
Seems good for CMake at least.

**Comment by BhaaLseN** [comment]
The document doesn't really mention this, but is this supposed to be an annotated tag or a regular (lightweight) tag?

**Comment by BhaaLseN** [comment]
Ah well, it doesn't seem to make a difference without this change. Seems to work on Windows (based on the `scmrev.h` contents, I haven't updated my WinSDK so it doesn't fully build.)

**Comment by Tilka** [comment]
Every build prints `fatal: no tag exactly matches '7e9e4ef445c11455c8b1e50e580e3c255b904a88'` now.

**Comment by OatmealDome** [comment]
I've opened #12901 to silence this noise.

**Pull request merged**
