### PR TITLE
SI: Minor bugfixes

### PR DESCRIPTION
**Pull request by booto**
- VI was using "lines" count from SI without converting to half lines.
- origin calibration structure for controllers is 10 bytes, not 12

### CODE REVIEW

**Comment by BhaaLseN** [comment]
The `SIPOLL` change seems to make sense, but I can't find anything about `CMD_ORIGIN` or `CMD_RECALIBRATE` in YAGCD. [libogc](https://github.com/devkitPro/libogc/blob/b4ad94705b8d9d68fb51014615582b3b9f9ae836/libogc/pad.c#L59) seems to have a 12-byte buffer for it (albeit only using 6 of them).
Do you have any references for that change?

**Comment by booto** [comment]
Disassembling a title (Windwaker, nice enough to include a symbol map on disc) that sends 0x41/0x42 commands:

For 0x41=CmdReadOrigin
request_length=1,
response_length=0xa

For 0x42 0x00 0x00 =CmdCalibrate
request_length=3
response_length=0xa

Breaking at either of [these](https://github.com/dolphin-emu/dolphin/blob/398aa2a9f976169c4ac8228f0969971f3e2ba2f3/Source/Core/Core/HW/SI/SI_DeviceGCController.cpp#L81) [locations](https://github.com/dolphin-emu/dolphin/blob/398aa2a9f976169c4ac8228f0969971f3e2ba2f3/Source/Core/Core/HW/SI/SI_DeviceGCController.cpp#L94) has `length` of `0xb`. This is not 0xa because the param gets [incremented](https://github.com/dolphin-emu/dolphin/blob/398aa2a9f976169c4ac8228f0969971f3e2ba2f3/Source/Core/Core/HW/SI/SI.cpp#L287-L299). I have no idea why it does that, SI's treatment of the expected-response-length seems pretty silly, or maybe there's something that I'm missing.

**Comment by BhaaLseN** [comment]
I suppose because there's no point in having an empty response; so they just save the bit. Seen this a couple of times in wire formats just to squeeze in another tiny bit of data.

**Comment by JMC47** [comment]
This has been tested and hardware verified to be correct.

**Pull request merged**
