### PR TITLE
VideoBackend: Remove extraneous shifts from indirect texture lookups

### PR DESCRIPTION
**Pull request by endrift**
Fixes a handful of bugs, including the notorious [8613](https://bugs.dolphin-emu.org/issues/8613) and seemingly [7193](https://bugs.dolphin-emu.org/issues/7193) as well.

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3570)

### CODE REVIEW

**Comment by neobrain** [comment]
This is your chance to add some documentation about the black magic happening in those code paths! ;)

**Comment by degasus** [comment]
Much better patch. May you also change the same on https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/VideoBackends/Software/Tev.cpp#L468 ?

Also, what do you think about adding a "shift" function which does the if/else for us? If we're going to check for 32bit bounds, this is likely required.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3570#-:-K8x1NOj9uHZggeFnLWo:1046182994)*

**Comment by degasus** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3570#-K8xfH5uskXi3iOKLDFd:-K8xfH5uskXi3iOKLDFe:1484459608) (no related file):*
After looking at this patch again, the old code did make a good point about s24 being used. So why do you think those 3 bits are not stripped?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3570)*

**Comment by endrift** [comment]
*[a discussion](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3570#-K8xfH5uskXi3iOKLDFd:-K9Au63JPzSvnT3BPRDu:2135751403) (no related file):*
I'm honestly not 100% sure, but I think the issue might be related to shifting the sign bit off the top. fifoci doesn't seem to show any changes, so it seems safe to merge.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3570)*

**Comment by delroth** [comment]
I'd love if someone who knows our graphics code better than I do could review this and LGTM.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3570#-:-K9HUfTl1t4y-0yQwOS7:1805030039)*

**Comment by endrift** [comment]
*[a discussion](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3570#-K8xfH5uskXi3iOKLDFd:-K9JJ0WNDBkmh6V2AeWn:-655246577) (no related file):*
So after thinking about this some more, this train of logic implies that the order of operations for the transform inside Flipper is multiply *then* scale, but afaik there's no reason to believe that it can't be scale *then* multiply, which would prevent the bottom bits from being shaved off, and those are likely more important than the top bits of an s17.7 that will likely overflow anyway. I have no way of verifying this, though. For all I know, the other shader compilers are already combining the bitshifts, preventing the bottom bits from being stripped, although that does imply a behavior change.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3570)*

**Comment by mbc07** [comment]
Accordingly to [an user on the forums](https://forums.dolphin-emu.org/Thread-wii-epic-mickey?pid=399966#pid399966), this PR also fixes Epic Mickey (and very likely to fix Epic Mickey 2 too which runs on the same engine) when running on Mac OS X...

**Comment by endrift** [comment]
I'm not really sure what's holding up this PR, actually. @degasus?

**Comment by JMC47** [comment]
On the plus side, it fixes bugs.  On the negative side ti fixes Mac OSX bugs.  If we fix all of the Mac OSX bugs then we run the risk of alienating all the people who accuse us of treating OSX as a third world OS.

**Comment by degasus** [comment]
To be honest, there are some issues.

First, it's a guessed behavior change. The old code was implemented using the fixed point format descripted within the patents. Why did you choose this behavior?

Second, the behavior change is only done within the hardware backends. Please implement the same for videosw.

Thrid, it's called a OSX bug fix. For me, it looks like a workaround. Did we trigger undefined behavior? If so, did you fix it? Or does the new code just not trigger the OSX optimization pass any more?

**Comment by neobrain** [comment]
Has any attempt been made so far to verify the behavior against hardware? Keep in mind that just because this affects subtexel precision doesn't mean it cannot be tested!

**Comment by phire** [comment]
Shouldn't need to verify against hardware, Our video software backend gets the ea games videos right.

**Comment by RisingFog** [comment]
Any update on this?

**Comment by degasus** [comment]
@endrift May you still write this change for videosw please?

**Comment by DJRM2021** [comment]
Hi, any update regarding Issue # 7193?

**Pull request merged**
