### PR TITLE
Minor DSP JIT optimizations

### PR DESCRIPTION
**Pull request by Sintendo**
Noticed some minor improvements could be made in this area. Probably won't make a measurable difference. Notable changes include:

* Merge two ORs and early exit when _Value == 0
* Remove some extraneous instructions (don't recalculate flags, AND already modifies flags, ...)
* Prefer TEST over CMP for comparison to zero

### CODE REVIEW

**Comment by FioraAeterna** [comment]
This looks pretty reasonable from a quick glance.

If you want to optimize more of the DSP recompiler, I think there's a number of things that could be made branchless with the appropriate reallocations of registers, though I don't know what's worth it. e.g. the "double after multiplication if flag is set" could be turned into an unconditional shift.

**Comment by phire** [comment]
@dolphin-emu-bot rebuild

**Comment by Sintendo** [comment]
Hmm, I'll try look into it.
Aside from that, would it make sense to merge Update_SR_Register64_Carry and Update_SR_Register64_Carry2 by adding a boolean parameter? They differ in just two lines.
I also wonder if the comments might be wrong. For instance, Update_SR_Register16 is claimed to clobber RDX, but doesn't actually seem to use RDX. Update_SR_Register16_OverS32 is said to clobber RDX, but actually seems to clobber RCX.

**Comment by skidau** [comment]
Yes, you may as well merge the two  Update_SR_Register64_Carry by adding a boolean parameter.
The comments re: clobbering are probably out of date (this can be checked by reviewing the revision when the comment was added).

**Comment by Tilka** [comment]
lgtm so far

**Comment by Sintendo** [comment]
And with that, Update_SR_Register64_Carry2 is no more. No sure about the parameter name, so if anyone has a better idea I'd love to hear about it. I also fixed the comments I believe are incorrect.

I noticed that all callers of Update_SR_Register64_Carry pass EAX for the first parameter. Maybe we should so something with that?

**Comment by skidau** [comment]
EAX and RAX are synonums.  Feel free to change EAX to RAX or do you have something else in mind?

**Comment by Sintendo** [comment]
I was thinking it seems redundant to have a parameter if you're always passing the same argument anyway, but I guess the code is more flexible like this.

In any case, I don't think I'll make any additional changes for this PR (aside from addressing any concerns there may be), so I think we can look into getting this merged?

**Comment by skidau** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
