### PR TITLE
Gameini updates. (PR #2130 fixed and rebased)

### PR DESCRIPTION
**Pull request by JosJuice**
This is based on PR #2130. It changes all line endings to LF, is based on a recent version of master, and contains some small fixes (mostly de-duplicating a few extra game INIs). Original description:

It removes settings that were removed from dolphin to clean up the database. Modifies some gameinis to use the new 3 letter gameid. Adds Hyrule field speedup hack for Japanese and American version of Twilight Princess for wii. Removes efb to ram from Twilight Princess, Tony Hawk's Pro Skater 3, Tony Hawk's Pro Skater 4, Prince of Persia Forgotten Sands, Mario Superstar Baseball, Okami, FFCC the Crystal Bearers and The Simpsons due to the recent dolphin changes. Enables efb to ram for The Magic Obelisk because it needs it and some more minor changes.

### CODE REVIEW

**Comment by pauldacheez** [comment]
The Simpsons Game still requires EFB to RAM for me, but I may or may not be fucking something up somehow. I'll have to double-check if I rebased properly and didn't somehow not merge in mimimi's changes once I get home from this sleep-inducing HTML class. Regardless of the EFB issues, though, the game still has black lines/spots everywhere, e.g. on Homer Simpson's sideburns, hands and pants. :\

**Comment by pauldacheez** [comment]
Never mind the EFB to RAM issues, I guess something's broken for me and me only. :< I'll complain to degasus, I guess.

**Comment by ZephyrSurfer** [comment]
Could you remove the projection hack from GKTJA4 please?
It will resolve <a href="https://code.google.com/p/dolphin-emu/issues/detail?id=4790">Issue 4790</a>

**Comment by JosJuice** [comment]
I can't find any projection hack in GKTJA4.ini...

**Comment by ZephyrSurfer** [comment]
@JosJuice I'm sorry. You're right, there's none there.
I'll go and mention it on the tracker.

**Comment by Linktothepast** [comment]
It lgtm and thanks again.

**Pull request merged**
