### PR TITLE
ProgramShaderCache: Simplify SHADERUID comparison operators

### PR DESCRIPTION
**Pull request by lioncash**

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Looks simpler/more readable to me, and I suppose it doesn't produce any more overhead than doing it by hand? If so, LGTM.

**Comment by lioncash** [comment]
@BhaaLseN Yeah, all tie does is make a tuple of lvalue references (no copies, which is easily optimized away), and it also prevents accidental assignment if this changes in the future, such as accidentally doing

```cpp
vuid = r.vuid &&  guid == ...
```

**Comment by delroth** [comment]
How does the generated code look like? This part of the code is fairly performance critical.

**Comment by lioncash** [comment]
Well, it actually gets inlined now when compiling with MSVC considering placing a breakpoint on it in VS now fails to activate in release mode. However if I force it not to inline it, the generated code difference can be seen in this [gist](https://gist.github.com/lioncash/9667e70828f99255005e)

**Comment by degasus** [comment]
LGTM

**Pull request merged**
