### PR TITLE
OGL: Fix assertion when minimizing window

### PR DESCRIPTION
**Pull request by stenzek**
Pretty simply change, this was a regression introduced by #4436.

When minimizing a window you get a client area size of (0, 0), at least on Windows. Also fixes a potential divide by zero in Renderer::RenderText, as well as replacing C-style casts with static_cast.

The variables themselves should probably be unsigned as well, but there's a few of these in RenderBase that would need to be changed (e.g. target width/height, backbuffer width/height).

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Thank god I didn't mention it on the other PR with you saying "everyone does `max(n, 1)` there" :)

**Comment by degasus** [comment]
Wouldn't it be better to just add lots of "if (!width || !height) return;" to all affected functions? No need to print the OSD, or to swap at all.

**Comment by stenzek** [comment]
@degasus Yeah, that'd be good idea. Only problem with that is under the current setup if we return from SwapImpl the window dimensions won't be updated, so it'll never render again. Also if SwapBuffers causes the GL to flush, we may need an explicit glFlush call, otherwise several frames worth of commands would be queued (but I'm not sure how drivers handle this, do they flush on their own in this scenario?)

Maybe something to consider when/if we swap to using size update events rather than querying the window size every frame?

**Comment by degasus** [comment]
Ok, fine. Let's do this properly on implementing event based resizing. LGTM for now.

**Pull request merged**
