### PR TITLE
Add an option to eject the disc

### PR DESCRIPTION
**Pull request by JosJuice**
Accessible through File > Eject Disc and a hotkey. It can be useful for triggering glitches in games, as described here: https://forums.dolphin-emu.org/Thread-how-to-properly-eject-disc

### CODE REVIEW

**Comment by sepalani** [comment]
SGTM. I tested it and it seemed to work properly. However, I didn't manage to trigger Zelda TP loading glitches (it might be just me being to rusty, though).

**Comment by GlydetheSurfer** [comment]
ok this isnt related to this particular update but i wanna know if you guys could fix the photo channel 1.1 not showing up... i used NUS downloader to get it.. i tried various methods to get it show up on the system menu but its not working no matter how many times i try

**Comment by JMC47** [comment]
Asking for support on unrelated pull requests is a good way to get banned from posting on pull requests in the future.  Please refrain from that.  We have forums for general support an an issue tracker for potential bugs in the emulator.

The photo channel was moved to the Wiishop in later updates.  You can get v1.1 on the Wiishop with proper credentials inputted into Dolphin.

**Comment by GlydetheSurfer** [comment]
my wii is bricked i cant get credentials

**Pull request merged**
