### PR TITLE
Windows/DolphinQt: set the default style to fusion

### PR DESCRIPTION
**Pull request by shuffle2**

### CODE REVIEW

**Comment by Pokechu22** [comment]
Before:

image

After:

image

This looks kinda weird to me (it doesn't match the system styling at least).

Would it be possible to allow configuring it in the interface settings? As far as I can tell, this is unrelated to the currently available theme setting.

**Comment by Pokechu22** [comment]
Hmm. For reference, this is the windows style, which is definitely not what we want:

image

For some reason, I assumed that the windows style would be newer than the vista style. But clearly it's not.

Also, at first I wasn't sure what you meant by distributing the DLL for it, since I only see `Qt6Core.dll`/`Qt6Gui.dll`/`Qt6Widgets.dll` next to Dolphin.exe, but it looks like the DLL exists at `QtPlugins\styles\qwindowsvistastyle.dll`. It also seems like only fusion and windows are built-in.

**Comment by mbc07** [comment]
TBH, I don't think fusion brings any noticeable improvement to the GUI styling, at least based on what I've seen so far. If the only argument for making it the default style (and not allowing users to change it without resorting to command-line parameters) is "there's one less DLL to ship", then yeah, that's a hard pass from me.

Currently, on master, Dolphin will match the system style of the OS it's running on and won't look out of place, as it'll render like any other native app from that same OS. By switching to fusion, it'll have a consistent style (identical across all OSes we support) but at the same time it'll feel out of place across all OSes we support, since it won't match the look and feel of any of them. I don't think this is the right approach.

-----

I tested both this PR and dolphin-svg-dpi.7z you've linked on PR #11785 and something is wrong with the latter. The build from this PR renders like the [screenshots posted earlier](https://github.com/dolphin-emu/dolphin/pull/11789#issuecomment-1519193095) by Pokechu22, but it won't react to the light/dark mode setting from the OS. 

Fusion on the light color theme on Windows doesn't match the system style but looks... usable. Accent color remains blue and it matches well with our Clean icon sets. I still prefer the Vista style, though. Didn't manage to make it switch to the dark color theme, so I can't evaluate that. 

When testing dolphin-svg-dpi.7z, things look very weird, I'm almost certain something is broken. This time it reacts to the light/dark mode setting from the OS but the styling doesn't seem to match neither fusion, nor vista. It looks like old Windows 9x style with the OS accent color slapped almost everywhere (it's worse in dark mode). Is that intentional?
image
image

**Comment by mbc07** [comment]
So, to get things straight: Qt Vista style doesn't support dark mode?

**Comment by mbc07** [comment]
>that's correct

Okay, that makes the change far more reasonable. 

Is it possible to at least tweak Fusion default colors? Fusion light looks fine out of the box, but Fusion dark is a bit jarring (especially the tab backgrounds)
<br/>

> I was also under the impression that fusion is already the default style on linux and maybe on macos

AFAICT Qt has a macOS style that matches the look and feel of the OS (similar to the Vista style on Windows). I have no idea if it already supports dark mode, though.

**Comment by OatmealDome** [comment]
Tried the macOS build, and it does look quite different.

I think I prefer the current style on macOS. It makes Dolphin look more native and takes into account user settings like the accent color.

#### 5.0-19280

image

#### This PR
image

**Comment by FearlessTobi** [comment]
The fusion theme looks a bit dated honestly. 
If we are forced to use this for light theme as well, to get the dark mode functionality, then I'd honestly prefer shipping a dark theme seperately. 
But I'm obviously a bit biased since I made the original PR for that :)

**Comment by MayImilae** [comment]
> I don't really have an opinion about how it looks on non-windows OS, so i'm fine with making this PR only apply to windows, if that's what people want.

I think that's a good idea. The fusion style has a kind of not-common-frontend linux-y vibe, it's more or less just ok imo. On Windows it's a step up from the vista theme, but it's a step back on other platforms like macOS. Making this Windows only seems like a good choice.

**Comment by MayImilae** [comment]
> because dolphin wants to style the balloonTip lightly if the system theme is dark (which is probably, itself, an error).

That was deliberate - it was done that way for contrast. https://dolphin-emu.org/blog/2020/12/10/dolphin-progress-report-october-2020/#50-13163-remove-description-box-in-graphics-tabs-and-use-custom-tooltips-instead-by-iwubcode

**Comment by mbc07** [comment]
> [...] because dolphin wants to style the balloonTip lightly if the system theme is dark (which is probably, itself, an error).

That's intended behavior. Dark balloon tips on light theme (and vice versa) was one of @MayImilae design requests to make them stand out more. This behavior can also be controlled by adding a `UseHighContrastTooltips = True/False` entry on the `[Interface]` section of `Dolphin.ini `...

**Comment by mbc07** [comment]
Out of curiosity, now that PR #11774 was merged, I tried running the most recent build of this PR with argument `-platform windows:darkmode=2` (which became the default value for that parameter on Qt 6.5) and Fusion dark renders differently?

image

It doesn't apply the accent color (Qt 6.5 seems required for that) and the background is pitch black, however the tab background at least remains consistent. Any thoughts? 

(by the way, the same theme gets applied on current master if you add arguments `-platform windows:darkmode=2 -style fusion`)

**Comment by mbc07** [comment]
I'm OK with the accent color usage, the only thing from Fusion dark on Qt 6.5 that's bugging me out is the gray background of tab contents and buttons, which is too "light" (e.g. the contrast between them and the window background is a bit too high). Fusion light, on the other hand, looks good out of the box, no tweaking required.

Back to Fusion dark, that's what I think needs tweaking, not to make the tab content and buttons the same #1E1E1E color of the windows background, but to make them a little more dark than the current #4B4B4B they default to...

(the pitch black screenshot I sent earlier was just to show that having closer colors between the window background and the tab content looks overall more uniform IMO -- again, they don't need to be the same, but should at least be more close to each other)

**Comment by mbc07** [comment]
Here, I tweaked the background colors a bit with an user style sheet to show what I mean. First screenshot is default Fusion dark on Qt 6.5, second one is with slightly darker tab backgrounds (and related elements):

default

tweaked

At least on the stylesheet, they affected elements all seem derived of the same base color, tweaking that color in the source would very likely fix that everywhere else. It doesn't even have to be a hardcoded color, we could just take the default base color returned by Qt and multiply it by 0.75 or other suitable factor to get it slightly darker...

(other interesting bit is that the preview feature of Qt Designer 6.5 with the default Fusion dark style uses a more uniform palette as well -- the tweaks I did in the mockup above comes mostly from that -- not sure why the final, compiled application, look more contrasty with the default Fusion dark style)

**Comment by mbc07** [comment]
Umm... May I ask what happened?

**Pull request closed without merging**
