### PR TITLE
Pushed required version of lib-zstd to 1.4.0 or higher

### PR DESCRIPTION
**Pull request by jwsharpe**

### CODE REVIEW

**Comment by JosJuice** [comment]
As far as I know, 1.3.8 or higher should work fine, so enforcing 1.4.4 seems a little excessive.

**Comment by jwsharpe** [comment]
Was just matching the `./Externals` package, can bump down to 1.3.8 if you want.

**Comment by Tilka** [comment]
> Was just matching the `./Externals` package, can bump down to 1.3.8 if you want.

Please do.

**Comment by cyrozap** [comment]
Per #9017, the minimum version should probably be kept at 1.4.0, since Dolphin fails to build with zstd 1.3.8 on Debian 10.

**Pull request merged**
