### PR TITLE
CachedInterpreter: Implement MMU.

### PR DESCRIPTION
**Pull request by degasus**
This fixes ISI and DSI exception. It also optimize EndBlock in a way that no abort call is required.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3853)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/Core/PowerPC/CachedInterpreter.cpp, line 190 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3853#-KI8AVUM2oxHw4ZprTdf:-KI8AVUNpAzr4C99QMul:560170357) ([raw file](https://github.com/dolphin-emu/dolphin/blob/d5bf3aaad3ff2227c0c1605addb80cc873910bf0/Source/Core/Core/PowerPC/CachedInterpreter.cpp#L190)):*
> ```cpp
> 			m_code.emplace_back(GetInterpreterOp(ops[i].inst), ops[i].inst);
> 
> 			if(jo.memcheck && (ops[i].opinfo->flags & FL_LOADSTORE))
> ```

space after the `if`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3853)*

**Comment by BhaaLseN** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/Core/PowerPC/CachedInterpreter.cpp, line 74 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3853#-KI8yyw5bSNLbdjGBIUW:-KI8yyw6jk9nwW7tY15b:-2016100307) ([raw file](https://github.com/dolphin-emu/dolphin/blob/8533387e5c2b8ae0ab6a084726c5ec7790178e51/Source/Core/Core/PowerPC/CachedInterpreter.cpp#L74)):*
> ```cpp
> }
> 
> static bool EndBlock(u32 data)
> ```

Why the bool return value when all it ever does is return true?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3853)*

**Comment by degasus** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/Core/PowerPC/CachedInterpreter.cpp, line 74 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3853#-KI8yyw5bSNLbdjGBIUW:-KI9-j3ZI6kOcSarBQyJ:1275366591) ([raw file](https://github.com/dolphin-emu/dolphin/blob/8533387e5c2b8ae0ab6a084726c5ec7790178e51/Source/Core/Core/PowerPC/CachedInterpreter.cpp#L74)):*
<details><summary><i>Previously, BhaaLseN (BhaaL) wrote…</i></summary>
> Why the bool return value when all it ever does is return true?
</details>
To match the interface of the runner. It's either just a call, or a boolean return value which checks if this instructions end the block. So "return true" here says that this instructions always ends the block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3853)*

**Comment by BhaaLseN** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/Core/PowerPC/CachedInterpreter.cpp, line 74 \[r2\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3853#-KI8yyw5bSNLbdjGBIUW:-KI91MzQ4YtBGV2daTh4:805233221) ([raw file](https://github.com/dolphin-emu/dolphin/blob/8533387e5c2b8ae0ab6a084726c5ec7790178e51/Source/Core/Core/PowerPC/CachedInterpreter.cpp#L74)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> To match the interface of the runner. It's either just a call, or a boolean return value which checks if this instructions end the block. So "return true" here says that this instructions always ends the block.
</details>
Alright, LGTM then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3853)*

**Comment by JMC47** [comment]
Works for Rogue Squadron 2/3

**Comment by degasus** [comment]
So ready to merge, but should this be in 5.0?
The cached interpreter wasn't in 5.0, so it's not a regression, but a fix to a new feature.

**Comment by JMC47** [comment]
It was decided to wait until after 5.0 to merge this on IRC.

**Comment by magumagu** [comment]
It looks like this doesn't correctly decrement the downcount when a DSI occurs.  Not really a big deal, but better to make it consistent with the other JITs.

Otherwise LGTM.

**Comment by degasus** [comment]
This already land on master within the jitcache PR.

**Pull request closed without merging**
