### PR TITLE
Use ffmpeg for Windows Video Dumping instead of VFW

### PR DESCRIPTION
**Pull request by RisingFog**
Still needs lot of work, would also require to have libav included as Externals.

Looking for comments,

EDIT: Work done, still looking for comments on ffmpeg binary inclusion.

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
I personally like how it fails on all the bots.
I do like the idea that we should use libav everywhere rather than different solutions per OS.
Is VFW an API that allows hardware vendors to hook in and accelerate video encoding, or is it software only?

**Comment by RisingFog** [comment]
@Sonicadvance1 It's a software API only for Windows if I recall correctly, but I'm not 100% sure

**Comment by magumagu** [comment]
On Windows, as far as I can tell you have to use vendor-specific APIs for accelerated encoding.  Windows 7 and up does have a builtin software H.264 encoder, but you can't access it through VFW.

If we're going to be distributing libav, we need to be careful we don't trip over any patent licensing requirements.

**Comment by RisingFog** [comment]
@magumagu PPSSPP uses ffmpeg, which also uses GPL v2 as far as I know. I don't believe that it cause any licensing issues.

**Comment by Sonicadvance1** [comment]
PPSSPP is GPLv2+, so a slightly different license.
Have to be aware of the differences.

**Comment by RisingFog** [comment]
For the pre-built libraries, will pre-compiled libraries from zeronoe suffice? Or should I build the library locally and use that instead?

Also, thoughts on including ffmpeg for linux/osx (perhaps in buildbots only)?

**Comment by FioraAeterna** [comment]
VFW is a /really/ outdated API (from the early 90s, I think). It has a lot of constraints that break modern audio and video compression, so I think even among Windows codecs it's considered pretty deprecated.

**Comment by CarlKenner** [comment]
ffmpeg is a huge pain in the neck on windows. As far as I can tell, there are no working ffmpeg builds for Windows that are compatible with Visual Studio. I had to use it in Doom 3 BFG to play the .bik files, but neither statically nor dynamically linking the dll file would work without crashing unless I disabled unused function removal in the linker.

I'd stick with VFW if it does what we need.

**Comment by RisingFog** [comment]
@CarlKenner I have yet to run into any issues with regards to the build I'm using in terms of crashing and such.

**Pull request merged**
