### PR TITLE
Movie: simplify silly loop

### PR DESCRIPTION
**Pull request by Tilka**
NFC

### CODE REVIEW

**Review by JosJuice — APPROVED** [review]

**Comment by mitaclaw** [comment]
A more literal interpretation of this loop would be std::count_if, though std::all_of could also be a good rework. Initializing an array to compare against seems inefficient.

**Review by Pokechu22 — COMMENTED** [review]
Looks like a previous version of this loop was added in ca650d44352f4cd994a51c6bbc813b3b3bb4adda, where it looked like this:

https://github.com/dolphin-emu/dolphin/blob/ca650d44352f4cd994a51c6bbc813b3b3bb4adda/Source/Core/Core/Src/Movie.cpp#L1162-L1169

but that returns if the last byte in the md5 is 0, rather than all bytes. (If it used `break` instead of `continue` I think it would work?)

That was changed to the current loop with two variables in 1917f832440e6841de5661f11d859213681a2560:

https://github.com/dolphin-emu/dolphin/blob/1917f832440e6841de5661f11d859213681a2560/Source/Core/Core/Src/Movie.cpp#L1144-L1152

It's worth noting that `std::array` was only used here in 75d056bc486f01af48b2e3942a44bd9cbc8332f6; before it was a C-style array.

A comment like this might be helpful:

```c++
  // Very old DTM files don't include an md5, in which case that previously-reserved area is all zeros.
  // Skip the MD5 check in that case.
```

**Comment by JosJuice** [comment]
> A more literal interpretation of this loop would be std::count_if, though std::all_of could also be a good rework. Initializing an array to compare against seems inefficient.

It depends on how the compiler optimizes it. If we're lucky, the compiler might be able to skip putting the std::array on the stack, putting it in two registers instead. We'd need to see the emitted assembly to know for sure. Personally, since this runs super rarely, I don't care too much either way.

**Comment by Tilka** [comment]
Added a comment.

**Pull request merged**
