### PR TITLE
UpdaterCommon: Use File::Copy() on non-macOS platforms

### PR DESCRIPTION
**Pull request by OatmealDome**
Because RenameFile on Windows is apparently cursed.

### CODE REVIEW

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by leoetlino** [comment]
LGTM after fixing the lint issue

**Review by Dentomologist — APPROVED** [review]
LGTM

**Comment by OatmealDome** [comment]
OK, I think the lint is fixed.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
