### PR TITLE
Don't Use Abbreviation for "Memory Card"

### PR DESCRIPTION
**Pull request by PEmu1**

### CODE REVIEW

**Comment by MayImilae** [comment]
Images please if it affects the gui.

**Comment by MayImilae** [comment]
Well... that's a very tight screenshot, but it seems fine to me.

**Comment by JosJuice** [comment]
Good idea, but please replace all the other occurrences of memcard too:

https://github.com/dolphin-emu/dolphin/blob/c8cb1fa7d70fccb280dc44c61a118f2796af8456/Source/Core/DolphinWX/NetPlay/NetWindow.cpp#L259
https://github.com/dolphin-emu/dolphin/blob/1af9f68240d8bcd87b684e9736da784f7740f438/Source/Core/Core/HW/GCMemcard.cpp#L193
https://github.com/dolphin-emu/dolphin/blob/1af9f68240d8bcd87b684e9736da784f7740f438/Source/Core/DolphinWX/MemcardManager.cpp#L289
https://github.com/dolphin-emu/dolphin/blob/1af9f68240d8bcd87b684e9736da784f7740f438/Source/Core/DolphinWX/MemcardManager.cpp#L426
https://github.com/dolphin-emu/dolphin/blob/1af9f68240d8bcd87b684e9736da784f7740f438/Source/Core/DolphinWX/MemcardManager.cpp#L450
https://github.com/dolphin-emu/dolphin/blob/1af9f68240d8bcd87b684e9736da784f7740f438/Source/Core/DolphinWX/MemcardManager.cpp#L474
https://github.com/dolphin-emu/dolphin/blob/1af9f68240d8bcd87b684e9736da784f7740f438/Source/Core/DolphinWX/MemcardManager.cpp#L597
https://github.com/dolphin-emu/dolphin/blob/1af9f68240d8bcd87b684e9736da784f7740f438/Source/Core/DolphinWX/MemcardManager.cpp#L820
https://github.com/dolphin-emu/dolphin/blob/1af9f68240d8bcd87b684e9736da784f7740f438/Source/Core/DolphinWX/MemcardManager.cpp#L834

**Comment by PEmu1** [comment]
@JosJuice Done.

**Pull request merged**
