### PR TITLE
TextureCacheBase: Add m_ prefix to member variables

### PR DESCRIPTION
**Pull request by Dentomologist**
As per style guidelines.

### CODE REVIEW

**Review by iwubcode — APPROVED** [review]
LGTM

**Comment by AdmiralCurtiss** [comment]
Err... I'll merge this if you want but are you sure you want this merged with your outstanding PRs that touch some code in here?

**Comment by iwubcode** [comment]
@AdmiralCurtiss - yeah I wondered about that but it's fine.  I can just rebase if there are conflicts.

**Comment by AdmiralCurtiss** [comment]
Well okay, if you're sure.

**Pull request merged**
