### PR TITLE
Android spec cleanups, add missing mipmap icons and round icons

### PR DESCRIPTION
**Pull request by 4KZelda**
-Use built in android.R strings
-Move icons to mimap folder per Android specs
-Add round icon

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Ping @MayImilae to review the icons.

Whats the difference/advantage of using mipmap instead of drawable?

**Comment by 4KZelda** [comment]
From a end users perspective nothing.

Per the Google blog

"It’s best practice to place your app icons in mipmap- folders (not the drawable- folders) because they are used at resolutions different from the device’s current density."

https://android-developers.googleblog.com/2014/10/getting-your-apps-ready-for-nexus-6-and.html

**Comment by ds84182** [comment]
When launchers like Nova launcher want to use app icons that are larger
than the standard resolution it utilizes the mipmaps to select a resolution
that still looks crisp on the screen. Otherwise, most launchers will just
display a blurrier version of the app icon selected for the device
resolution.

**Comment by MayImilae** [comment]
Why the addition of a shadow and the white circle?

**Comment by mbc07** [comment]
> So um, why do we care about meeting pixel launcher schemes?

Starting with Android 7.1, [it's the system framework who decides whether or not to return either the regular icon or the round icon](https://www.xda-developers.com/psa-android-7-1-circular-icon-support-is-determined-by-the-oem/), and OEMs can enforce that as they wish (e.g. if it's enforced, you'll always get rounded icons regardless of the launcher you're using). If a circular icon isn't provided, it'll just insert the regular icon inside a circle, and well, that auto generated icon might not look good, so Google now recommends app developers to provide a rounded icon version on their apps...

**Comment by degasus** [comment]
@sigmabeta Do you have time for a rough review? Should be streight forward.

**Comment by sigmabeta** [comment]
Everything others have posted here is correct. 

Worth noting also, as of Android O (currently in developer preview, estimated release sometime this fall) there's planned to be support for OEMs specifying more than just round icons: 

https://developer.android.com/preview/features/adaptive-icons.html

So it's worth also thinking about support for that.

As for the actual implementation, it is indeed straight forward. No reason not to merge once this passes design review.

**Comment by 4KZelda** [comment]
Thanks all, I have made the discussed changes.

@sigmabeta I agree the new maskable icons concept is pretty cool and more scalable than creating different shaped icons. The app would need to target API 26 (O) to use this so I think it's wise to wait until O is fully released.

**Comment by sigmabeta** [comment]
Correct. O is a long way away.

**Comment by Meowlithius** [comment]
Just as idea to help discussion, as it has stagnated for a few years.
I created a icon to fit with more modern "flat look".
SVG
[DolphinICO.zip](https://github.com/dolphin-emu/dolphin/files/3884039/DolphinICO.zip)

PNG
DolphinICO

**Comment by sigmabeta** [comment]
I like it, though I'm not sure you needed to cut the dolphin's tail off :)

**Comment by Meowlithius** [comment]
@sigmabeta i was struggling with the tail a bit, I'm not a professional designer, but i can try to fix that.

**Comment by mbc07** [comment]
At this point I think we should just have the current icon on a white background with proper padding, then update it to be an "adaptive" icon so the actual shape can be anything the system/launcher requests (circular, round, square, etc). There's really no need to reinvent the wheel and in fact this is the approach that many existing apps are taking, I strongly think our current icon design still is good enough...

**Comment by Meowlithius** [comment]
@mbc07 I find that the gradient and inner flat shadow can't be seen easily on mobile, and even some tablet screens (well a lot of tablet screens for me). I think though you can add a flat drop shadow to it.
How do you feel about this?
DolphinICO

**Comment by mbc07** [comment]
> I find that the gradient and inner flat shadow can't be seen easily on mobile, and even some tablet screens (well a lot of tablet screens for me).

I can perfectly see those fine details on my phone, which has a (rather small for today's standards) 5" 1080p screen with 16:9 ratio, even on the current design which is just a transparent background. Your icon design just throws our current visual identity out of the window by simply flatting out and shading everything with rather strange and unusual colors. This might sound harsh but for me it looks more like a bootleg clone design used by some unknown unofficial Dolphin fork than something we would use on our official builds.

Like I said, there's no need to reinvent the wheel, updating our current icon to be adaptive and have a white background with proper padding makes it work correctly with any shape the new customization options from newer Android versions might apply to the icon, while still retaining our visual identity...

**Comment by Helios747** [comment]
rebase pls

**Comment by JosJuice** [comment]
Closing due to inactivity from the PR creator's part. I'm not opposed to reopening this if the PR author wants to rebase the PR and address the issues that have been brought up by May.

**Pull request closed without merging**
