### PR TITLE
[Android] Remove NonNull annotation from GameProvider

### PR DESCRIPTION
**Pull request by Tsunamical**
Let's give it a whirl.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3856)

### CODE REVIEW

**Comment by Tsunamical** [comment]
@lioncash Can you get BuildBot to do a build of this?

**Comment by RisingFog** [comment]
@dolphin-emu-bot rebuild

**Comment by lioncash** [comment]
Why?

The annotation is entirely a marker-based annotation for an IDE to help the parser/inspector detect if an API is potentially being misused. It does nothing at runtime.

**Comment by Tsunamical** [comment]
To be honest I'm not sure of what else could be causing it. Nothing else is really even related, I'll have to do a thorough look through when I get a chance, I'm just throwing random things out atm.

**Comment by BhaaLseN** [comment]
If NPEs happen, just add the stupid null check? Or do we not know whats causing it?

**Comment by lioncash** [comment]
@Tsunamical 

It wouldn't matter what IDE is being used, the code itself comes from the android.support.annotation package. Please don't make random guesses.

**Pull request closed without merging**
