### PR TITLE
QtCompile.props: Update for Qt 5.5.

### PR DESCRIPTION
**Pull request by waddlesplash**
Will break the build even more until dolphin-emu/ext-win-qt#1 is merged.

### CODE REVIEW

**Comment by shuffle2** [comment]
Is this actually needed? Seems like just another "oh random thing is totally blocking me!!" commit...

**Comment by waddlesplash** [comment]
> Is this actually needed? Seems like just another "oh random thing is totally blocking me!!" commit...

Yes. As you can see, in my currently-open PR, the buildbot fails because I'm using (at least) some Win10 detection stuff which wasn't added until this version. I'm working offline with it just fine, but in order to keep the buildbot happy this needs to be merged.

**Comment by waddlesplash** [comment]
(#3032 is the PR this is blocking ATM.)

**Comment by waddlesplash** [comment]
@shuffle2 / @Parlane ping

**Comment by Parlane** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
