### PR TITLE
Improve illegal instruction handling.

### PR DESCRIPTION
**Pull request by magumagu**
This should more reliably show an error message for illegal
instructions.

### CODE REVIEW

**Comment by FioraAeterna** [comment]
Probably should note in the commit message it's only for the interpreter (I think?), but otherwise looks okay.

**Comment by magumagu** [comment]
This affects JIT: the JIT has these opcodes configured to FallBackToInterpreter.  (Not sure if that's the best arrangement, but it seems okay.)

**Comment by FioraAeterna** [comment]
Okay, that makes sense. Does this mean we'll get an illegal opcode message twice (once in PPCAnalyst, once here?)

**Comment by magumagu** [comment]
PPCAnalyst only pops an illegal opcode message if GetOpInfo() returns nullptr; that can happen because we don't fill out the tables completely, but it doesn't happen for unknown primary opcodes like 0x00000000.

Actually, we should probably just fix the tables so GetOpInfo() never returns null, and remove the special case from PPCAnalyzer::Analyze.

**Comment by magumagu** [comment]
Added a commit to fix the tables so GetOpInfo() never returns null.

**Comment by phire** [comment]
LGTM

**Pull request merged**
