### PR TITLE
Support for RVT-R disc images

### PR DESCRIPTION
**Pull request by GerbilSoft**
RVT-R (Wii debug) disc images are basically the same as retail, except they use a different set of keys and signatures. This patch checks for the debug issuer, and if found, uses the debug key instead of the retail key.

Tested with a recently dumped RVT-R prototype of Sonic and the Black Knight.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4479)

### CODE REVIEW

**Comment by RisingFog** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
Please fix the problems that lint points out.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Source/Core/DiscIO/VolumeCreator.cpp, line 99 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4479#-KXqKHP6gI36Vg-3T949:-KXqKHP7IfY5VRGgJGRk:b-xcwx6v) ([raw file](https://github.com/dolphin-emu/dolphin/blob/b175387f909e7ad00ab517b6ec2fbe9775fb1add/Source/Core/DiscIO/VolumeCreator.cpp#L99)):*
> ```cpp
>   mbedtls_aes_context AES_ctx;
> 
>   u8 Issuer[32];
> ```

This variable is supposed to be named `issuer` with a lowercase `i`.

---

*[Source/Core/DiscIO/VolumeCreator.cpp, line 101 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4479#-KXqKO0HekI6HSokJets:-KXqKO0IPNOs_sUQImXI:bh9o0st) ([raw file](https://github.com/dolphin-emu/dolphin/blob/b175387f909e7ad00ab517b6ec2fbe9775fb1add/Source/Core/DiscIO/VolumeCreator.cpp#L101)):*
> ```cpp
>   u8 Issuer[32];
>   _rReader.Read(offset + 0x140, sizeof(Issuer), Issuer);
>   if (!memcmp(Issuer, s_issuer_rvt, sizeof(s_issuer_rvt)))
> ```

Is it intentional that you're ignoring the last few bytes of what you read from the reader?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4479#-:-KXqK6YDETpVarzzgtW4:b-4vlr48)*

**Comment by GerbilSoft** [comment]
For that last part: The issuer field is 32 bytes, but the actual issuer ID is less than that. (It's NULL padded.) Since only the issuer ID is important, I'll reduce it to sizeof(s_issuer_rvt).

Will fix the rest of the lint issues tonight and update the PR.

**Comment by GerbilSoft** [comment]
Fixed the lint issues and updated issuer[].

**Comment by JosJuice** [comment]
Please squash the second commit into the first one, since it's just a fix-up commit.

**Comment by GerbilSoft** [comment]
Done.

**Comment by JosJuice** [comment]
The squash seems correct, but the merge commit that you added recently needs to be removed.

**Comment by GerbilSoft** [comment]
...huh, I don't remember making that merge commit. GitHub must have done something when I clicked "Update branch".

I manually removed the commit.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by GerbilSoft** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/DiscIO/VolumeCreator.cpp, line 99 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4479#-KXqKHP6gI36Vg-3T949:-KXvRo1_Lt976Mf4N4pH:bfadvh4) ([raw file](https://github.com/dolphin-emu/dolphin/blob/b175387f909e7ad00ab517b6ec2fbe9775fb1add/Source/Core/DiscIO/VolumeCreator.cpp#L99)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary><blockquote>

This variable is supposed to be named `issuer` with a lowercase `i`.
</blockquote></details>

Fixed with lint commit update + squash.

---

*[Source/Core/DiscIO/VolumeCreator.cpp, line 101 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4479#-KXqKO0HekI6HSokJets:-KXvRj2pRSy4tsBCkKBS:bfadvh4) ([raw file](https://github.com/dolphin-emu/dolphin/blob/b175387f909e7ad00ab517b6ec2fbe9775fb1add/Source/Core/DiscIO/VolumeCreator.cpp#L101)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary><blockquote>

Is it intentional that you're ignoring the last few bytes of what you read from the reader?
</blockquote></details>

Fixed with lint commit update + squash.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4479)*

**Comment by JosJuice** [comment]
Oh right, I forgot to update the Reviewable status. Sorry.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4479#-:-KXvfyxiaAzG0E1iKDw6:b-9zmw9i)*

**Comment by JMC47** [comment]
Are there any other known debug discs?  I'd like to get my hands on one if possible, knowing which ones are out there to find would be nice.

**Comment by GerbilSoft** [comment]
A Mario & Sonic 2010 Olympic Winter Games demo disc from GamesCom was also dumped recently. I'm pretty sure there's a few other RVT-R prototypes around.

(NR prototypes, i.e. GameCube, don't have any special encryption, so they "just work" as long as they don't need any extra RAM like the Metroid Prime 3 prototype.)

**Comment by Fallcrest** [comment]
As a related question, does this include NR Discs? I don't know if those (the GameCube development discs) are related to the Wii development discs. (And as far as I know, NR Discs are not supported by Dolphin currently either.)

**Comment by JosJuice** [comment]
@Fallcrest, please don't make so many comments that won't lead to any improvements to the PRs you're commenting on. It's getting annoying. Ask on the forums instead if you want a place to ask questions.

As far as I know, NR discs can't be dumped by the usual methods (normal GC/Wii hardware can't read them, PCs with special drives need to use modified dumping software), but once you've managed to dump one, it will work in Dolphin just like any other disc image.

**Comment by einstein95** [comment]
This PR also works with GCM files from the Wii SDK once the first 0x8000 bytes have been stripped.

**Comment by Fallcrest** [comment]
@JMC47 There are beta versions of the Mii channel, some game demos, and some debug channels present on the RVT dev units, shown [here](https://www.youtube.com/watch?v=U2vMZUWG3lU) and [here](https://www.youtube.com/watch?v=zm_XeV9OFJk). Although, I am not sure where the software would actually be found, you would have to ask the owner of those units.

**Comment by GerbilSoft** [comment]
I tested both RVT-R prototypes of Mario & Sonic 2010, and both booted successfully. (Tested up to the title screen; it's running slowly on my ThinkPad X230, possibly due to the glibc AVX issue.)

**Comment by Parlane** [comment]
Thanks @GerbilSoft

**Pull request merged**
