### PR TITLE
Don't force compile everything as Objective-C++ on macOS

### PR DESCRIPTION
**Pull request by ligfx**
Changes include:
- Remove CMake directives that force C++ source to be treated as Objective-C++ source, and C source to be treated as Objective-C source.
- Rename `Core/Common/GL/GLInterface/AGL.{cpp,mm}`
- Extract IOBluetooth-dependent code into `IOdarwin_private.h`
- Remove specialized fullscreen handling from DolphinWX. From my reading of the wxWidgets code, it should still be doing the same thing. I manually tested fullscreen options and didn't see any behaviour differing from master.
- Replace a call to `[NSWorkspace openFile: ... withApplication:@"TextEdit"]` with `wxExecute({ "open", "-a", "TextEdit", filename}, ...)`

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4227)

### CODE REVIEW

**Comment by shuffle2** [comment]
is there an advantage to this?

**Comment by ligfx** [comment]
@shuffle2 Are you asking if there's a performance advantage? There should be no practical changes to the final compiled binaries. What it does change is it makes the project less surprising and more consistent with usual expectations, in that files that are named `.cpp` are only C++, and all Objective-C is in files that are named `.mm`.

**Comment by endrift** [comment]
I tried proposing this sort of thing a while back, and people's general reaction was "yeah but why does it matter?" I didn't have a good answer, so I kinda gave up pushing for it, but I'd like it if this sort of thing got merged.

**Comment by endrift** [comment]
@dolphin-emu-bot rebuild

**Pull request merged**
