### PR TITLE
Interface: Static Game Window Title option

### PR DESCRIPTION
**Pull request by Pikterra32**
Implementing Feature Request from https://bugs.dolphin-emu.org/issues/11982
Screenshot_20241013_131257

Adds a "Static Window Title" checkbox in ( Options->Configuration->Interface ).
This makes the render window title always be "Render".

My only problem is that I made it so if "Show Active Title in Window Title" is enabled, the render window title will be "Render" + [game name], I don't know if this is the right thing to do but i don't know how else I would implement it.

A solution would be to name the option differently, but I don't know which name and description to use, Help would be appreciated, thanks.

### CODE REVIEW

**Comment by JMC47** [comment]
I don't think static window title is a bad idea at all.  It's an option for streamers and other people who rely on the window name for projects.

**Comment by mbc07** [comment]
I think you could make them exclusive. For example, "Static Window Title" has priority over "Show Active Title in Window Title", you could also signal that in the UI by setting the disabled state in the "Show Active Title in Window Title" checkbox when "Static Window Title" is enabled.

About the actual window title, "Render" is a bit too generic. I'd go with "Dolphin Render Window" or something like that...

**Comment by Pikterra32** [comment]
Thanks for the help ! My PR is ready now !

**Comment by mbc07** [comment]
@dolphin-emu-bot rebuild

**Comment by Pikterra32** [comment]
I just realized the setEnabled on the "Show active window title" is only triggered when the "Static window title" button is clicked, so if the GUI is refreshed the "Show active window title" will be enabled even if "Static window title" is set to true, I can't fix that right now, I know I just have to put a single function call but I don't have access to my computer for now.

**Comment by JosJuice** [comment]
> Also, do I have to edit my commit description to include changes when I bring updates to it ?

Minor edits you make as a result of review comments shouldn't be included in the commit description. The commit history of a PR should reflect not what the review process was like, but rather what you are changing as a whole.

**Comment by Pikterra32** [comment]
Ok, I understand better now, Thanks. I'm sorry for all these problems it is my first ever pull request and I don't know a lot about github and git. I'm closing this PR and making a new clean one.

**Pull request closed without merging**
