### PR TITLE
[WIP] DolphinQt: Add dark theme for Windows

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
Rebase of #11446 with the user style handling changes removed and Qt embedding added -- that is, this is only adding the dark theme for Windows, none of the other things that PR does.

Open questions:
- Do we want this theme (which is supposedly based on 'QDarkStyle' but I can't actually find the exact source...?), do we want a different one? Do we want to make a custom one instead?
- If we take an existing one, how do we ship the license?

I'm kinda leaning towards finding or making a theme that looks closer to how actual Windows apps look in dark mode, but ymmv.

Clipboard023

### CODE REVIEW

**Comment by MayImilae** [comment]
> I'm kinda leaning towards finding or making a theme that looks closer to how actual Windows apps look in dark mode, but ymmv.

That probably would be best, imo.

**Comment by cobalt2727** [comment]
I'm not 100% positive, but wouldn't this be fixed by using QT 6.5+?

https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5

**Comment by AdmiralCurtiss** [comment]
Oh, yeah that sure sounds like it! Maybe we should just wait for that then and do a Windows Qt version bump.

(I did definitely search for Qt dark style stuff and all I ever found was 'yeah Qt does not support this on Windows, you have to do it manually'. Oh well.)

**Comment by mbc07** [comment]
Assuming the screenshot at the OP is up-to-date, the title bars being white are an eye sore. If there's no way of getting dark title bars when using the dark theme, it's probably better to update Qt to 6.5 when available instead of going with this custom dark theme...

**Comment by AdmiralCurtiss** [comment]
Well Qt 6.5 isn't out yet, planned release at the end of this month. But yeah I agree that it's probably best to wait for that if it will handle it automatically for us.

**Comment by EndangeredNayla** [comment]
Feel free to use my style sheet EndangeredNayla/Dolphin-Dark-Mode

**Comment by mbc07** [comment]
> I built dolphin with Qt 6.5.0 and changed QStyle to "fusion", here's x64 and arm64 binaries to test: https://drive.google.com/file/d/16jd4tzq5zjwBT5kVMzdrvg9tw4Q7uqcy/view?usp=sharing

Just tested it. The good news is that it works, the bad news is that it results in some weirdness (both on light and dark modes). For reference, I tested this on Windows 11 and my accent color is currently purple/pink-ish.

* Light theme applies the accent color in some places (e.g. sliders and buttons) but not others (e.g. checkboxes). Tabs also look a bit off compared to master:
  light0
  light1

* Dark theme applies the accent color in more places, but also looks more off with our default "Clean" theme. Tabs also have a gray-ish look that is weird:
  dark0
  dark1

* If you change between light/dark mode on Windows or change the accent color while Dolphin is already open, parts of the GUI fail to update and get stuck in their previous state (screenshots shows the result of a light => dark transition, but the same happens the other way around):
  mismatch0
  mismatch1

So yeah, it needs some work. While the idea of applying the Windows accent color is nice, perhaps we should disable it somehow, or default to a Dolphin-specific theme (blue?). I also didn't expect Dolphin to become aware of runtime theme changes out of the box with just a Qt version bump (you normally need to write code for that), but it did and seems to need some fixes...

**Comment by FearlessTobi** [comment]
What is the status on this? Stuck in eternal review hell? :p

**Comment by mbc07** [comment]
We recently updated to Qt 6.5, which has native support for a dark mode, but not with the Qt's Vista style (the default on Windows). There's another PR for changing the default style on Windows to Qt's Fusion, which has a dark mode, and this PR will likely get closed when that one gets merged.

If you don't want to wait for the PR, you can already launch Dolphin with the  `-style fusion`  CLI parameter to use the dark theme (it'll follow the system settings)...

**Comment by cobalt2727** [comment]
link to the PR?

**Comment by AdmiralCurtiss** [comment]
Only because a feature 'works fine' doesn't mean that we actually want it, especially if it's a change that is mainly aesthetics and affects about half of our userbase.

**Pull request closed without merging**
