### PR TITLE
FramebufferManagerBase: Compress a loop into a find_if

### PR DESCRIPTION
**Pull request by lioncash**

### CODE REVIEW

**Comment by degasus** [comment]
LGTM

**Comment by shuffle2** [comment]
have you looked at the codegen? I would hazard to guess that the lambda version is worse...

**Comment by delroth** [comment]
Agreed with @shuffle2's concerns.

**Comment by lioncash** [comment]
The difference is negligible https://www.diffchecker.com/t4xogkuw (lhs being original code, rhs being this code).

**Comment by phire** [comment]
Code is pretty much the same, perhaps marginally better.

LGTM.

**Comment by shuffle2** [comment]
wow, they finally fixed that, then... :) lgtm

**Pull request merged**
