### PR TITLE
HW/WiimoteEmu: Allow emulating the "Classic Controller Pro".

### PR DESCRIPTION
**Pull request by jordan-woyak**
The "Pro" version does not have analog triggers.
Apparently some games are aware of this and change their controls.
The mapping indicator changes appropriately when enabled.
image
Setting name good as just "Classic Controller Pro" ?

### CODE REVIEW

**Comment by mbc07** [comment]
I think all controls except for L and R should be changed to disabled state when the user mark the "Classic Controller Pro" checkbox. Perhaps also add a tooltip when hovering the "Classic Controller Pro" saying that the Pro lacks analog triggers. Other than that LGTM...

**Comment by jordan-woyak** [comment]
Now I'm wondering if I was misinformed about any games being aware of the "Pro" controller.
This PR might be unnecessary.

**Comment by iwubcode** [comment]
> Apparently some games are aware of this and change their controls.

Haven't gone through the code yet but which games have this behavior?  Just curious!

**Comment by jordan-woyak** [comment]
@iwubcode Apparently 007 Goldeneye, according to https://strategywiki.org/wiki/GoldenEye_007_(2010)/Controls#Classic_Controller_Style
But my testing is showing otherwise.
Now I'm not sure...

**Comment by mbc07** [comment]
I think being able to emulate a Classic Controller or a Classic Controller Pro is a worthy addition just for the sake of emulating all Wiimote extensions, even if no commercial game actually makes a distinction between them...

**Comment by jordan-woyak** [comment]
I think literally no game is actually is aware of the "controller pro" and UI should be improved if we decided to actually have this option.

**Pull request closed without merging**
