### PR TITLE
Update GALE01r2.ini

### PR DESCRIPTION
**Pull request by jefflongo**
Replaces the broken gecko code for widescreen support with a functional one in SSBM.

### CODE REVIEW

**Comment by JosJuice** [comment]
The [Internet Explorer] comment denotes the author, right? Was this new code made by the same author or someone else?

**Comment by jefflongo** [comment]
Yes, that denotes the author.  This code was made by IE as well.

**Comment by jefflongo** [comment]
(source: http://smashboards.com/threads/melee-gecko-codes-guide-and-discussion.327311/ under other codes)

**Comment by Fuzzik** [comment]
Just tested out the code; works great.

**Comment by jefflongo** [comment]
Just a quick note force 16:9 aspect ratio must be on in graphics settings for this to function properly.

**Comment by phire** [comment]
LGTM

**Comment by phire** [comment]
@dolphin-emu-bot rebuild

**Comment by someguyongithub** [comment]
bump, LGTM

**Pull request merged**
