### PR TITLE
CMake: Use CMAKE_CXX_STANDARD instead of passing -std=c++14

### PR DESCRIPTION
**Pull request by ligfx**
Available since CMake 3.1

### CODE REVIEW

**Comment by lioncash** [comment]
```cmake
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
```

will likely be preferable to have set as well.

**Comment by ligfx** [comment]
> ```cmake
> set(CMAKE_CXX_STANDARD_REQUIRED ON)
> set(CMAKE_CXX_EXTENSIONS OFF)
> ```
> will likely be preferable to have set as well.

Sure, I'll add those in and see what happens.

**Comment by ligfx** [comment]
The Android build seems to be running into android-ndk/ndk#222, where something in the NDK's toolchain file prevents `CMAKE_CXX_STANDARD` from working.

**Comment by Orphis** [comment]
Yes, and I knew of the issue, which is why I didn't use the flag.

**Comment by Orphis** [comment]
On a side note, the Android support in 3.7 (independent from Google's Gradle integration) works fine with it. Not sure we want to use it though...

**Comment by ligfx** [comment]
@Orphis: there are two proposed fixes up for AOSP (https://android-review.googlesource.com/#/c/326383/ (mine) and https://android-review.googlesource.com/#/c/324419/). Hopefully something will get merged for r14, and then `CMAKE_CXX_STANDARD` will work as intended.

In the meantime... what do you think about something like

```cmake
# The Android NDK toolchain file is broken.
# See https://github.com/android-ndk/ndk/issues/222
if(CMAKE_TOOLCHAIN_FILE MATCHES "android.toolchain.cmake$")
  set(_new_toolchain_file "${CMAKE_CURRENT_BINARY_DIR}/android.toolchain.cmake")
  if(NOT EXISTS "${_new_toolchain_file}")
    file(TO_CMAKE_PATH "${CMAKE_TOOLCHAIN_FILE}" CMAKE_TOOLCHAIN_FILE)
    file(WRITE "${_new_toolchain_file}" "
      include(\"${CMAKE_TOOLCHAIN_FILE}\")
      set(CMAKE_C_COMPILER_ID_RUN FALSE)
      set(CMAKE_CXX_COMPILER_ID_RUN FALSE)
    ")
    set(CMAKE_TOOLCHAIN_FILE "${_new_toolchain_file}")
  endif()
endif()
```

? Too much?

**Comment by Orphis** [comment]
Something will be merged for r14, the issue is tagged with r14 in Github after all.
Yours look much better and I wonder why CMake would have issues detecting the compiler at all.

**Comment by degasus** [comment]
The android buildbot was updated a few weeks ago, may you rebase and ask anyone to merge it? LGTM.

**Pull request merged**
