### PR TITLE
Adjust Touchscreen Controls Opacity

### PR DESCRIPTION
**Pull request by MayImilae**
This updates the onscreen buttons' opacities to be more friendly to opacity adjustment from #9439, and alters the default opacities in that opacity setting to roughly match how they were before 9439.

All buttons are optimized with Optifine to strip out Photoshop leftovers.

[Screenshots To Go Here]

-----
Full Change List

* Text changed from 70% opacity to 100%

* White buttons changed from 50% to 80%

* Pressed (Black) buttons changed from 75% to 90%

* Nunchuk Z lost gradient

* Wiimote B gradient adjusted 30-65

* Home button outer ring adjusted to 30% opacity

* altered classic L and R buttons to fix small pixel alignment whoops

* altered gamecube z to fix small pixel alignment whoops

* Dpad Pressed is now:
  * active "text" 100%
  * inactive "text" 20%
  * pressed area 100%
  * unpressed area 50%

* Joystick area unaltered

### CODE REVIEW

**Comment by JosJuice** [comment]
Some screenshots:

Screenshot_20210516-091507266
Screenshot_20210516-091548950
Screenshot_20210516-091728154

**Comment by JosJuice** [comment]
It looks like a lot of the PNG files had their permissions changed to be executable. (GitHub's list of changes shows this as `100644 → 100755`.) Also, you used the name `wiimote_2.png` instead of `wiimote_two.png`. Could you fix those two things? LGTM otherwise.

**Comment by JosJuice** [comment]
Screenshots of the fixed version of this PR (the earlier version had only updated the xxxhdpi files, which were not in use on my phone):

Screenshot_20210517-090125759
Screenshot_20210517-090148814
Screenshot_20210517-090255451

**Review by JosJuice — APPROVED** [review]

**Comment by JMC47** [comment]
Are there comparison shots to before?  Just for easy access to see them.

**Comment by JosJuice** [comment]
Here are screenshots of master:

Screenshot_20210517-091243140
Screenshot_20210517-091357743
Screenshot_20210517-091448247

**Comment by JMC47** [comment]
Here's from before the previous opacity changes.  F-Zero GX doesn't work in that build.

https://cdn.discordapp.com/attachments/477774491280211968/843748031211634748/Screenshot_20210517-031301.png
https://cdn.discordapp.com/attachments/477774491280211968/843748514197405766/Screenshot_20210517-031509.png

**Review by JMC47 — APPROVED** [review]
Looks better to me.

**Pull request merged**
