### PR TITLE
try for system libmgba first

### PR DESCRIPTION
**Pull request by alucryd**
Patch made for the arch linux package, figured I would try to upstream it. Please let me know if that is something desirable, and if so whether it's in acceptable state or requires modifications.

### CODE REVIEW

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by Pokechu22** [comment]
Based on https://github.com/dolphin-emu/dolphin/pull/9600#discussion_r667532847 there were previously concerns about distros shipping libmbga but not libmgba-dev, and also about determinism with netplay/movies where the same version of dolphin should imply the same version of libmgba. I'm not sure how relevant these concerns (particularly the former) are nowadays though.

**Comment by delroth** [comment]
> Based on https://github.com/dolphin-emu/dolphin/pull/9600#discussion_r667532847 there were previously concerns about distros shipping libmbga but not libmgba-dev

I don't think you'd have a pkg-config file if it's not libmgba-dev anyway? So it will fall back to Externals as it currently does.

> determinism with netplay/movies where the same version of dolphin should imply the same version of libmgba

Sounds like we should fix this by including a libmgba version string in the netplay handshake then?

**Comment by v1993** [comment]
Note: this PR had an issue with include directory detection that's fixed by #11566.

**Pull request merged**
