### PR TITLE
Support the OpenGL core profile in EGL.

### PR DESCRIPTION
**Pull request by Sonicadvance1**
This should make our Mesa EGL users happy.
Fixes issue #9282

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3550)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Source/Core/Common/GL/GLInterface/EGL.cpp, line 180 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3550#-K8eJttlkU1FQEeDeBh7:-K8eJttlkU1FQEeDeBh8:-798846400) ([raw file](https://github.com/dolphin-emu/dolphin/blob/fdfe3c2724180d72137cfd8467902ee7246e0ad7/Source/Core/Common/GL/GLInterface/EGL.cpp#L180)):*
This can just be

```cpp

std::array<std::pair<int, int>, 2> versions_to_try =
{
    {4, 0},
    {3, 3},
}
```

---

*[Source/Core/Common/GL/GLInterface/EGL.cpp, line 197 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3550#-K8eK8CXI8HurMX0onUz:-K8eK8CXI8HurMX0onV-:2006508236) ([raw file](https://github.com/dolphin-emu/dolphin/blob/fdfe3c2724180d72137cfd8467902ee7246e0ad7/Source/Core/Common/GL/GLInterface/EGL.cpp#L197)):*
Trailing parenthesis is one space too many

---

*[Source/Core/Common/GL/GLInterface/EGL.cpp, line 206 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3550#-K8eKBxdEhRXtBSBsr3Q:-K8eKBxdEhRXtBSBsr3R:2006508236) ([raw file](https://github.com/dolphin-emu/dolphin/blob/fdfe3c2724180d72137cfd8467902ee7246e0ad7/Source/Core/Common/GL/GLInterface/EGL.cpp#L206)):*
Trailing parenthesis is one space too many

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3550)*

**Comment by Sonicadvance1** [comment]
*[Source/Core/Common/GL/GLInterface/EGL.cpp, line 180 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3550#-K8eJttlkU1FQEeDeBh7:-K8eMavZcsV1qFxioxDZ:808356576) ([raw file](https://github.com/dolphin-emu/dolphin/blob/fdfe3c2724180d72137cfd8467902ee7246e0ad7/Source/Core/Common/GL/GLInterface/EGL.cpp#L180)):*
Wrong sir.
error: too many initializers for ‘std::array<std::pair<int, int>, 2ul>’

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3550)*

**Comment by Sonicadvance1** [comment]
This requires the Android buildbot to be kicked to update its configuration from using native API level 18 to API level 21.
Which I've already updated the configuration in sadm, so something just needs to be kicked somewhere.
@Parlane ^

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3550#-:-K8ePCsY6wF-c_YG1rOX:-700936069)*

**Comment by sepalani** [comment]
*[Source/Core/Common/GL/GLInterface/EGL.cpp, line 180 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3550#-K8eJttlkU1FQEeDeBh7:-K8eSZtlmI-A6cH5qD8S:984707743) ([raw file](https://github.com/dolphin-emu/dolphin/blob/fdfe3c2724180d72137cfd8467902ee7246e0ad7/Source/Core/Common/GL/GLInterface/EGL.cpp#L180)):*
You need to use the double braces syntax instead:
```C++
std::array<std::pair<int, int>, 2> versions_to_try =
{{
    {4, 0},
    {3, 3},
}}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3550)*

**Comment by Sonicadvance1** [comment]
*[Source/Core/Common/GL/GLInterface/EGL.cpp, line 180 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3550#-K8eJttlkU1FQEeDeBh7:-K8eUbWPeFCyu5C5tOjl:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/fdfe3c2724180d72137cfd8467902ee7246e0ad7/Source/Core/Common/GL/GLInterface/EGL.cpp#L180)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3550)*

**Comment by Sonicadvance1** [comment]
@dolphin-emu-bot rebuild

**Comment by Sonicadvance1** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3550)*

**Pull request merged**
