### PR TITLE
Create G2RE52.ini

### PR DESCRIPTION
**Pull request by kirbyUK**
Adds codes for G2RE52 (Shrek SuperSlam). Sourced from [here](https://github.com/ShrekBoards/patches/blob/master/gamecube/G2RE52.ini).

Not sure if this is the right way to ask for this or if I'm missing something in the codes file, apologies if so.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4477)

### CODE REVIEW

**Comment by JMC47** [comment]
If you're going to add an INI for it, please don't enable any cheatcodes by default.  It'd be best to fill it out based on other INIs with cheats (as well as give it a proper rating, which, if you're not sure, is usually 4 with GC games currently.)

**Comment by JosJuice** [comment]
Like JMC says, the Gecko_Codes section must be removed, because we don't want any cheat codes to be enabled by default. You also need to delete the ActionReplay section because it's empty.

Unlike what JMC says, don't put an emulation rating in there. Those are only supposed to be in 3-character INIs (except in special cases), and we do already have an emulation rating in G2R.ini.

**Comment by kirbyUK** [comment]
I have removed these sections? Is this good, or does anything else need doing?

**Comment by JosJuice** [comment]
You need to squash your new commit into the first one.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
Looks nice (but I can't review the individual codes).

**Comment by kirbyUK** [comment]
Would you prefer descriptions on the codes, or is this fine? Thanks for your help.

**Comment by JosJuice** [comment]
It seems fine to me.

**Comment by JMC47** [comment]
Sorry about my mistake!  I always forget about the 3 letter INI code stuff.

**Pull request merged**
