### PR TITLE
Android: improve app design

### PR DESCRIPTION
**Pull request by Simonx22**
This PR does several things:

- migrate AppCompat to Material Components. This is recommended by Google: https://material.io/blog/migrate-android-material-components (in the future I plan on migrating to the newest standard, Material 3, once it's fully released). Note: Dolphin used MaterialComponents before but was then changed back to AppCompat: https://github.com/dolphin-emu/dolphin/pull/8659. I can no longer reproduce this issue.
- adjust the colors
- remove two colors: dolphin_purple and dolphin_accent_gamecube. These colors don't fit in the app IMO. Let me know if I should revert this change
- add a missing up button in the UserDataActivity
- adjust the toolbar of the main screen to better indicate which tab is currently selected

~~I tried to test this as best as I could but I do not own any Android TV device and Google didn't release an arm64 emulator image, so I'm unable to test on that platform.~~ Tested on an Android device. Looks fine to me.
Let me know if anyone has any suggestions on what to change

Screenshots: (left is before, right is after)
Main menu:
 
 

Settings menu:
 
 

Cheats menu:

### CODE REVIEW

**Comment by JosJuice** [comment]
Overall I like this change, but I think the new style for the currently selected game list tab looks rather awkward. Not sure if that's just because I'm not used to it or not...

Regarding TV testing, what I usually do is to configure Android Studio to launch TvMainActivity on my phone. You can't test features like truly are exclusive to Android TV, like channel syncing, but the entire TV GUI is available and should work like it does on a real Android TV device.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by ajay9634** [comment]
Please add 1.5 resolution option in Android dolphin emulator

**Comment by JosJuice** [comment]
@ajay9634 Commenting on a random pull request is not how you make feature requests. Please refrain from doing this.

**Comment by ajay9634** [comment]
I don't know how to pull request, I am sorry

**Comment by Simonx22** [comment]
> Overall I like this change, but I think the new style for the currently selected game list tab looks rather awkward. Not sure if that's just because I'm not used to it or not...
Agreed. I reverted this change and added a white color that is being used as the tab indicator. I've also made the tab indicator slightly thicker.
> Regarding TV testing, what I usually do is configure Android Studio to launch TvMainActivity on my phone. You can't test features like truly are exclusive to Android TV, like channel syncing, but the entire TV GUI is available and should work as it does on a real Android TV device.
Thanks, that worked. Android TV looks OK to me.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by JosJuice** [comment]
That only works if there in fact is box art for the game. Perhaps if you only play popular releases it is the case that all your games have box art, but there are certainly games out there without box art (especially if you count homebrew releases), and being able to see the name of a game is such a critical function that it in my opinion has to work for all games no matter what.

The company is less important.

**Comment by Simonx22** [comment]
I plan on improving the game layout eventually, but I rather do that in a new PR so that this one is not getting too big.

**Comment by MayImilae** [comment]
So I typically focus on the desktop UX side of things but I was asked to give this a look.

I so, so friggin happy to see the purple get removed, finally. It was a very odd decision from way back and I never agreed with it. And the use of white for tab indication and stuff is a great touch! Thank you for making this PR!

I have a nitpick however. For the dark mode cheats menu, there's a shortcut to settings that for whatever reason has black text in your screenshot. I'm not sure if you have fixed this already, but I do not care for it. It really should have white text there to match the rest of the UI.

settingsblack

Another small nitpick is that I don't care for the further darkening of the background in the dark mode, though that's kind of just my personal taste. White on grey is nice but white on black is searing for me, worse than black on white.

**Comment by Simonx22** [comment]
@MayImilae Thanks for the review!
> there's a shortcut to settings that for whatever reason has black text

Good point! Fixed.

> further darkening of the background

Apparently that's the default for Material Components. I didn't see any easy way to change this without having to edit the color for each activity. This also applies to the text. I'm fine with the background and text color as is in both light and dark mode.

>  The text in the cheats window light mode is a lighter colour than the header

Good catch! I've fixed this.

**Review by JosJuice — APPROVED** [review]

**Pull request merged**
