### PR TITLE
OGL: Rewrite POKE_Z with a draw call

### PR DESCRIPTION
**Pull request by degasus**
It's now also merged and it should be faster than the glClear way.
But untested as I don't have a game which do POKE_Z.

### CODE REVIEW

**Comment by JMC47** [comment]
Whoa, whoa, what's this tagging stuff.  Do we know of any games that use this?

**Comment by phire** [comment]
Mario Kart 64 does z pokes for the split screen videos once you finish the race.

**Comment by phire** [comment]
To find more, google for the term "Poke Z not implemented" 

Apparently Roadkill and BlowOut also use it.

**Comment by imirkin** [comment]
@degasus shouldn't it be possible to just write depth into gl_Position.z? Then you don't have to write depth explicitly in the pixel shader.

**Comment by JMC47** [comment]
Seems to be working fine in Mario Kart 64, not that there's a visual difference between OGL and D3D (which doesn't implement it at all.)

**Comment by degasus** [comment]
@imirkin Of course, but I want @Armada651 to use this feature to validate the 24bit depth buffer. So this is closer to the framebuffer and I hope it's easier to validate the full state in this way.

**Comment by imirkin** [comment]
The difference is probably minor anyway. But you're going from 4 to 5
registers, which could drop the parallelism by a factor of 2 in some
config. But it's probably not too important here.

**Comment by degasus** [comment]
JMC47> 20 -> 12860962

so broken right now :/

**Comment by Armada651** [comment]
@degasus That poke is supposed to fail on console. I haven't gotten around to make a version that succeeds the poke test on console.

**Comment by degasus** [comment]
Verified with Armada's hwtest, it's working again

**Pull request merged**
