### PR TITLE
Skip reading UTF-8 BOM at the beginning of INI files

### PR DESCRIPTION
**Pull request by JosJuice**
Hopefully fixes https://code.google.com/p/dolphin-emu/issues/detail?id=7739

### CODE REVIEW

**Comment by lioncash** [comment]
Pinging @JMC47 for testing.

**Comment by JMC47** [comment]
I can finally edit INI files in windows again.

**Comment by RisingFog** [comment]
In the Save function, change all instances of std::endl to "\n" to fix the formatting issues when saving ini files.

**Comment by JosJuice** [comment]
@RisingFog I don't understand what that solves, so I'm not comfortable with making a PR for it. Can you do it instead?

**Comment by mimimi085181** [comment]
The important question is where the 0D 0D 0A sequence comes from. It looks like one place adds unix style line endings and another one adds OS specific style line endings. I guess that std::endl adds the OS specific ones, which are correct.

Take a look at this:
[Gecko]..$Button activator P1 [ardemii]..2086E454 0000ZZZZ...$Button activator P2 [ardemii]..2086FFD0 000ZZZZ...*ZZZZ:...*Left=0001...*Right=0002...*Down=0004...*up=0008...*+=0010...*-=1000...*2=0100...*1=0200...*B=0400...*A=0800...*Z=2000...*c=4000...*Home=8000...$Time Control [Bully@Wiiplaza]..045817B8 38800000...2886E456 EFFF1000...045817B8 3C807FFF...E0000000 80008000...**Press - to finish*...

.. means proper windows style line ending, ... is the 0d0d0a sequence. So the problem cases are the lines that contain the actual codes and the ones that contain comments. So it's something like section.lines being hardcoded to have unix style line endings between each line.

**Comment by JosJuice** [comment]
Can this be discussed in an issue report instead? It has nothing to do with the BOM problem.

**Comment by RisingFog** [comment]
LGTM

**Pull request merged**
