### PR TITLE
WX: Add the ability to uninstall WADs from the game list

### PR DESCRIPTION
**Pull request by leoetlino**
Simple quality-of-life addition that allows "uninstalling" WADs (removing the corresponding installed title) from the NAND.

The option is only enabled when the WAD can be uninstalled

The motivation for this is actually to encourage proper usage of the WAD launch feature (installing it to the NAND first), so we can drop the "direct WAD title launch" hack.

### CODE REVIEW

**Comment by sepalani** [comment]
Can't we use the Nintendo terminology instead of the technical one, if we want to be more user-friendly?

That is to say, use Channel rather than WAD (I don't know if another way of dealing with channels exists and may/will be supported in the future) and Wii Menu/System Menu instead of NAND.

So it would sound similar to "Install channel on Wii Menu" and "Uninstall channel from Wii Menu". 

@leoetlino Is there a reason for using "NAND" instead of "Wii Menu"? I mean, sure, they're different and yours is more accurate but someone without a NAND dump doesn't have access to the Wii Menu as far as I know.

**Comment by JosJuice** [comment]
Using channel instead of WAD is a very good idea IMO. I suppose Wii Menu instead of NAND also makes sense, but I would prefer "to Wii Menu" instead of "on Wii Menu".

**Comment by leoetlino** [comment]
I didn't use both of these terms, because "Wii Menu" makes absolutely no sense technically, especially for things like DLCs and hidden channels, where you don't actually see anything in the Wii Menu main screen. Which is also why I did not use "channel".

Nintendo refers to the NAND as "Wii System Memory", fwiw.

**Comment by Helios747** [comment]
Cool! I'm apathetic about the use of "WAD" vs "channel", one could argue WAD is fine because The user has to handle that WAD file at some point, so ideally they would get it. OTOH, channel is of course, a nicer user facing term.

LGTM. Haven't tested yet

**Comment by JosJuice** [comment]
Good point about things like DLC. I'm fine with not changing it to channel, then.

**Comment by sepalani** [comment]
@leoetlino a "technical" user UI string is meaningless (as long as the user isn't supposed to be a technical person like devs) since the user might not be aware or care concerning the technical aspects. Aren't DLCs and hidden channels "channel" according to Nintendo wording? If so I don't see the problem.

The only issue I can see while using the term "WAD" is if we decide to list the Wii Menu's channels on the game list at some point (i.e. a user with a NAND dump who's never touched a WAD before but bought/downloaded stuff on the Wii Shop Channel). Or alternatively, if we support title installation by using another method (another file type? a directory?).

I also assume that users using hidden channels and DLCs know that these WADs are "special" channels whereas a lambda user might not even know what a WAD is. If the word "channel" is the issue we could just use "title" instead (unless it has another meaning, might sound a bit too formal though, I still prefer channel for its simplicity).

Otherwise, concerning the "Wii Menu" you have a point. "Wii System Memory" doesn't sound bad at all, IMO.

**Comment by JosJuice** [comment]
> Aren't DLCs and hidden channels "channel" according to Nintendo wording?

No.

>I also assume that users using hidden channels and DLCs know that these WADs are "special" channels

Unlikely.

> whereas a lambda user might not even know what a WAD is.

Even though they've managed to put a WAD in the game list?

**Comment by leoetlino** [comment]
>Aren't DLCs and hidden channels "channel" according to Nintendo wording? If so I don't see the problem.

No, channel has a very specific meaning, both according to Nintendo and the homebrew community. Channel is something you can see and select on the main screen, and both DLCs and "hidden channels" don't fit this definition.

Internally, they're only titles, and that's the term I'd have used, except we currently only support WADs in the game list and not anything else.

>Or alternatively, if we support title installation by using another method (another file type? a directory?).

Unlikely. WAD is pretty much the only container format for Wii titles.

>we could just use "title" instead (unless it has another meaning, might sound a bit too formal though, I still prefer channel for its simplicity).

I don't mind using "title".

**Comment by JMC47** [comment]
The whole "not using the correct terms as to not confuse users" crap is why we have users who become more misinformed with what things do.  Use the correct terminology, people will adjust to it over time.  It's not so esoteric to the point where you can't figure out what it's trying to do just by thinking.  Not saying everyone will get it.

I also think title is correct enough in this case, but, I defer to leoetlino on all of this stuff. Channel just isn't true, as there's Channels, Virtual Console Titles, Wiiware, and DLC all as separate things to Nintendo.

**Comment by sepalani** [comment]
@JosJuice 
>> whereas a lambda user might not even know what a WAD is.
>
> Even though they've managed to put a WAD in the game list?

I was referring to:
> The only issue I can see while using the term "WAD" is if we decide to list the Wii Menu's channels on the game list at some point

I won't be surprised if such a feature is requested for convenience sake. We're not any close to that yet, however.

**Pull request merged**
