### PR TITLE
JIT: discard values that will not be used again (Don't merge, please review)

### PR DESCRIPTION
**Pull request by FioraAeterna**
This dramatically reduces register pressure in long blocks, cutting instruction
count by 5% or more in some.

This is an "unsafe" optimization: an error in the optimizer could result in
incorrect code (e.g. necessary values thrown out), not merely suboptimal code
(as in the case of the other register-usage optimizations in PPCAnalyst).

Fix an interpreter_tables mistake in the definition of srawix: srawix does not
use RB as an input. Having interpreter_tables be precisely correct is doubly
important now, given that this optimization relies on its correctness.

Also clean up and comment more of PPCAnalyst and make it more consistent.
Make sure it accounts for every possible block exit point, even exception ones,
so that the optimization is correct in all cases.

**This is a moderately dangerous optimization, so it probably needs a decent amount of testing to make sure nothing explodes.** I was also thinking there might be some way to enforce the constraints of this optimization inside the register cache (e.g. by marking a physical register as valid, but discarded, then erroring if it gets bound and loaded) to make sure problems don't occur, but there are some subtleties: for example, falling back to interpreter flushes the register cache but does not require all the values in the register cache to be correct, just the ones the interpreter uses.

### CODE REVIEW

**Comment by skidau** [comment]
Agree that this change needs heavy testing.

@dolphin-emu-bot allowmerge

**Comment by FioraAeterna** [comment]
Rebased on top of forwardbranches because this required some changes to still be correct with that (and still, it's less tested than it was). Forwardbranches is, I think, the more useful patch, so I'm prioritizing that in terms of PR dependencies.

**Comment by DarthVitrial** [comment]
Since this likely won't be merged for a while, any chance you could split off the interpreter_table and PPCAnalyst fixes into separate PRs so we can at least get those fixes?

**Comment by lioncash** [comment]
The interpreter change is already fixed in master.

**Comment by DarthVitrial** [comment]
Ah, I was not aware of that, sorry. My request stands for the PPCAnalyst stuff, but I'm glad to know we do have the fix. Sorry to bother.

**Comment by delroth** [comment]
No activity on the PR and @FioraAeterna is not actively contributing anymore. Closing.

**Pull request closed without merging**
