### PR TITLE
Externals: Update libusb to version 1.0.21

### PR DESCRIPTION
**Pull request by leoetlino**
1.0.21 notably adds a usbdk backend on Windows, which may be helpful as it could be used in the future to work around the missing isochronous transfer support for WinUSB backends for #4408.

Here is the full changelog (from libusb).

2016-10-01: v1.0.21:
* Core: Refactor code related to transfer flags and timeout handling
* Darwin: Ignore root hub simulation devices
* Darwin: Improved support for OS X El Capitan
* Darwin: Work around devices with buggy endpoint descriptors
* Darwin: Do not use objc_registerThreadWithCollector after its deprecation
* Darwin: Use C11 atomics on 10.12+ as the OS atomics are now deprecated
* Linux: Support preallocating kernel memory for zerocopy USB
* Linux: Deal with receiving POLLERR before all transfers have completed
* Solaris: Add solaris backend
* Windows: Add Visual Studio 2015 support
* Windows: Add usbdk backend
* Prevent attempts to recursively handle events
* Fix race condition in handle_timeout()
* Allow transferred argument to be optional in bulk APIs
* Various other bug fixes and improvements

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4463)

### CODE REVIEW

**Comment by PEmu1** [comment]
You might want to edit the DOLPHIN file to add your update (at least the date if nothing else is any different).

**Comment by leoetlino** [comment]
Sure, I've updated the date.

**Comment by leoetlino** [comment]
https://github.com/libusb/libusb/issues/232 prevents us from switching to usbdk right now, but updating to 1.0.21 would still be helpful since it has bug fixes (1.0.20 was released one year ago) and it'd make testing usbdk slightly easier.

**Comment by lioncash** [comment]
Reviewed 82 of 82 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4463)*

**Pull request merged**
