### PR TITLE
Make reset button (Emulation -> Reset) work correctly for Wii games.

### PR DESCRIPTION
**Pull request by magumagu**
Fixes issue 8328.

As far as I know, this works the same way as console. Games will generally
react to the reset button the same way as Home->Reset, so this is
only marginally useful, but possibly nice to have in certain situations.

Note that if you try to use Reset, and you're running a WAD which isn't
installed, it will likely crash because WADs respond to the reset button
by launching themselves with ES_LAUNCH.  It might be a good idea to add some
sort of hack to make this work as expected.

It would be easy to extend this to support the power button, but it's
unclear how exactly that should be exposed in the UI. See also issue 8979.

Needs to be rebased once PR #3811 is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3825)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/Core/HW/ProcessorInterface.cpp, line 211 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3825#-KHCo6uj0i5tkjkktmFk:-KHCo6uj0i5tkjkktmFl:-539529565) ([raw file](https://github.com/dolphin-emu/dolphin/blob/bfb17ca0b5c16089d7a74b587986532dc7f610eb/Source/Core/Core/HW/ProcessorInterface.cpp#L211)):*
> ```cpp
> }
> 
> static void IOSNotifyResetButtonCallback(u64 userdata, s64 cyclesLate) {
> ```

Brace on new line

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_stm.h, line 28 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3825#-KHCo9awhYfUxix4gd3W:-KHCo9awhYfUxix4gd3X:-183292221) ([raw file](https://github.com/dolphin-emu/dolphin/blob/bfb17ca0b5c16089d7a74b587986532dc7f610eb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_stm.h#L28)):*
> ```objc
> };
> 
> enum {
> ```

brace on new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3825)*

**Comment by JMC47** [comment]
I think this will be useful for SNES/NES games, because may of them don't save unless you soft reset the game in Dolphin.  Closing the game window is akin to unplugging the console, which doesn't flush the save onto the NAND.  Since I play the games with a GameCube Controller, using the reset button like this is nice.

**Comment by mimimi085181** [comment]
That sounds like we want to add an option to reset vc/wiiware on close, so it saves.

**Comment by JMC47** [comment]
I'm pretty sure we'd rather emulate whatever the Wii does when it turns off, but that's completely unrelated to this Pull Request (I think?)

**Comment by magumagu** [comment]
> I'm pretty sure we'd rather emulate whatever the Wii does when it turns off, but that's completely unrelated to this Pull Request (I think?)

Well, it's vaguely related in the sense that one possible way of emulating turning off the Wii would be emulate pressing the console's power button, and that shares some code with the reset button.  (Probably the first step would be to get the power button on a real wiimote working correctly; I'm guessing it's just a matter of reacting to IOCTL_STM_SHUTDOWN correctly.)

**Comment by magumagu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Core/Core/HW/ProcessorInterface.cpp, line 211 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3825#-KHCo6uj0i5tkjkktmFk:-KHDsRUdNKzIIuIVjTqC:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/bfb17ca0b5c16089d7a74b587986532dc7f610eb/Source/Core/Core/HW/ProcessorInterface.cpp#L211)):*
<details><summary><i>Previously, lioncash (Mathew Maidment) wrote…</i></summary>
> Brace on new line</details>
Done.

---

*[Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_stm.h, line 28 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3825#-KHCo9awhYfUxix4gd3W:-KHDsUVuNHwLxJer9bH1:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/bfb17ca0b5c16089d7a74b587986532dc7f610eb/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_stm.h#L28)):*
<details><summary><i>Previously, lioncash (Mathew Maidment) wrote…</i></summary>
> brace on new line</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3825)*

**Comment by magumagu** [comment]
Rebased.

**Comment by magumagu** [comment]
Ping.

**Comment by phire** [comment]
Sorry, never saw this one. :lgtm:

---

Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3825#-:-KNB7gpF8qyEWnaKqnXe:-805612327)*

**Pull request merged**
