### PR TITLE
Fix banners on Android being the wrong color

### PR DESCRIPTION
**Pull request by JosJuice**
I noticed that the color of the banner of the only game I had on my phone (Animal Crossing) was wrong, so I tried to fix it and arrived at this PR by trial and error. Should this really be necessary, though?

@mahdihijazi, what do you think? Does it sound right that Picasso wants ABGR?

### CODE REVIEW

**Comment by mahdihijazi** [comment]
@JosJuice Picasso doesn't use ABGR actually, there are 2 issues here
1. Picass bitmap config was wrong, it was using Bitmap.Config.RGB_565 instead of Bitmap.Config.ARGB_8888 inside PicassoUtils but I think this is not the main problem.

2. The main problem is about Android expecting to see a [pre-multiplied bitmap colors](https://plus.google.com/+ChetHaase/posts/ef6Deey6xKA) which I don't expect that is coming from the native code. 

I switched the bitmap.copyPixelsFromBuffer() to bitmap.setPixels() but I still see a black background, is that expected?

**Comment by JosJuice** [comment]
> Picass bitmap config was wrong, it was using Bitmap.Config.RGB_565 instead of Bitmap.Config.ARGB_8888 inside PicassoUtils but I think this is not the main problem.

PicassoUtils doesn't use RGB_565 when we read the banner from the game (the case where GameBannerRequestHandler() is used), right? Or am I reading the code wrong?

> The main problem is about Android expecting to see a [pre-multiplied bitmap colors](https://plus.google.com/+ChetHaase/posts/ef6Deey6xKA) which I don't expect that is coming from the native code.

Thanks for the link about pre-multiplied colors – I didn't know that that was a thing. I don't think that can be the problem, though. The C++ code always returns images where the alpha component is 0xFF. (Images are stored with alpha inside the games, but ColorUtil drops the transparency by essentially putting the image on top of a solid black background.)

**Comment by degasus** [comment]
RGBA vs ABGR only applies for single bytes. As we use integers, the endiness most be handled, too.

**Comment by JosJuice** [comment]
PR #5331 fixed the colors (in some way I don't fully understand), so I'm closing this PR.

**Pull request closed without merging**
