### PR TITLE
cmake: Modernize SDL discovery

### PR DESCRIPTION
**Pull request by Orphis**

### CODE REVIEW

**Comment by Orphis** [comment]
I believe that the error on FreeBSD is caused by the old FindSDL2 module that would put libraries and compilation options in the SDL2_LIBRARY, which is stored in the cache. The new module also uses the same variable name and is now confused.
Clearing the variables SDL2_* from the cache on the FreeBSD build agent should fix the issue.
@endrift Could you help me there? :)

**Comment by Orphis** [comment]
And I temporarily fixed the FreeBSD issue by pushing a dummy commit in the PR that resets the variable.

**Comment by Orphis** [comment]
FindModules are for a specific library, if there's any extra logic, it should be in our code. I don't think we want a FindSDL2OrThenSDLAndDefineCustomPreprocessorVariable module.

The FreeBSD issue is fixed, it was a caching issue caused by the bad FindSDL2 we currently have that puts a list of variable in SDL2_LIBRARY instead of a single value.

**Comment by phire** [comment]
Note: The reason this only affected the FreeBSD buildbot, is because FreeBSD is the only operating system (with a buildbot) that enables the SDL input plugin.

**Comment by ligfx** [comment]
@Orphis Hmm okay I see what you're saying. Why the `Externals/cmake/` stuff, though, instead of putting it in `CMakeTests` with the rest of the CMake stuff?

**Comment by Orphis** [comment]
Instead of Externals/cmake/SDL we could put this one in Externals/SDL. There are some other libraries that need some support code around to search for a system version and then fallback to embedded sources that could be there. If the project doesn't have any CMakeLists.txt, I guess it's fine to put one there, otherwise, some separation is needed (which is why I put them in Externals/cmake).

Those modules should be used with add_subdirectory() though, not include or find_package().

I don't like CMakeTests because it should be renamed (probably to something like cmake/Modules instead).
This isn't a module for inclusion though, it's an actual implementation.

**Comment by ligfx** [comment]
Externals/SDL makes more sense to me.

**Comment by Orphis** [comment]
Ok, we'll figure out something when we have other CMake files that shadow the original one or have extra code around it.

**Comment by phire** [comment]
I'm not sure about putting search logic in externals.

**Comment by Orphis** [comment]
@phire Well, we do have custom code to build those libraries there. It's mostly boilerplate

**Comment by phire** [comment]
But the custom code in externals is only ever executed once CMakeLists.txt has decided that it's going to build a statically linked version of an external library. 

I can see the motivation for splitting code out of the main CMakeLists.txt, but I don't think externals is the correct place to put it.

**Comment by Orphis** [comment]
No, the main CMakeLists.txt doesn't decide to build anything, it just makes targets available or not.

Then, the rest of the code (in Source) is responsible for pulling those in the build when the right options are there (or just if the external library is available sometimes).

**Comment by Orphis** [comment]
@phire @ligfx Moved the code to InputCommon instead. Is this fine now?

**Comment by ligfx** [comment]
@Orphis I like it. What's the reasoning behind the `External::SDL` prefix?

**Comment by Orphis** [comment]
Naming is hard...
SDL::SDL1_OR_SDL2 ?

**Comment by phire** [comment]
Yeah, Input Common is fine.

**Pull request merged**
