### PR TITLE
PPCCache: Avoid Global System Accessor

### PR DESCRIPTION
**Pull request by mitaclaw**

### CODE REVIEW

**Comment by mitaclaw** [comment]
@dolphin-emu-bot rebuild

**Review by AdmiralCurtiss — COMMENTED** [review]
I'm unsure if it really makes sense that each Cache instance keeps its own references to the System/Memory stuff when it can just be passed in when needed, but ymmv. Otherwise this looks fine.

**Comment by mitaclaw** [comment]
@AdmiralCurtiss I have put together a second commit following your suggestion. If it is found to be preferable, I will move forward with a squash to resume the PR. Most places were able to pass in references like you said.

**Comment by AdmiralCurtiss** [comment]
Yeah, I do like this better, but it's definitely a personal preference thing so either way is probably fine.

**Comment by mitaclaw** [comment]
I'll trust your judgement.

**Pull request merged**
