### PR TITLE
Fix netplay desync when using wii-u adapter.

### PR DESCRIPTION
**Pull request by phire**
If the game sent a command to a disconnected controller, the
wii u adapter code would return a diffrent response.

This simply deletes the speclized version of RunBuffer for the
wii-u adapter as the only diffrence was the code which detected
disconnected controllers and returned a error.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3797)

### CODE REVIEW

**Comment by JMC47** [comment]
I tested this and it seemed to work on F-Zero GX, which would always desync without this.

**Comment by Jofzar** [comment]
Ill test this out later with some friends and get back to you, if I dont post in the coming few days someone ping me.

**Comment by E2xD** [comment]
Tested and it works as expected.

**Comment by Jofzar** [comment]
Works

**Comment by RisingFog** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3797#-:-KG_igCCie-A8iU-zk-A:1417088721)*

**Pull request merged**
