### PR TITLE
WIP -  WiimoteEmu/DolphinQt: Rename "Swing" to "Thrust" in the UI. 

### PR DESCRIPTION
**Pull request by jordan-woyak**
Based on PR #8016.

Rename "Swing" to "Thrust" for a more accurate description of the emulated actions.

Discussion is still being had on what is the best name.

### CODE REVIEW

**Comment by iwubcode** [comment]
While I liked the name change of "IR" to "Point", I'm personally not as excited about changing "Swing" to "Thrust".  For me I think '"Swing" fits perfectly because it mimics the terminology used in most games.

Also, unrelated question - does this (and the other PR) break existing users' profiles?

**Comment by jordan-woyak** [comment]
@iwubcode Configs remain unchanged. This only changes the UI text.
I am also fine with "Swing" but others find it less than perfect.

**Comment by Techjar** [comment]
The trouble is that a forward/back are really a "thrust" action as there is no angle, and up/down/left/right are only a "swing" if the angle is >0. Neither term is really ideal, but the concern is that, as "swing", users won't understand what they need to map for a push/pull or jabbing motion.

**Comment by iwubcode** [comment]
That's very true, however, I think thrust is a very specific action that is used in only a handful of games. compared to 'Swing' which is used in many games.  I do agree that neither term covers all scenarios.

Possibly dumb suggestion:  limit the angle on swing to be greater than 0, then add another section for 'Thrust' and have forward/backward/left/up/etc.  It'll bloat the UI a bit but be much clearer.

**Comment by jordan-woyak** [comment]
Like I'd said in IRC, I think "Swing" is "accurate enough" and has been the name of these actions since their inception. But I'm open to "Thrust" or whatever makes the most sense.

**Comment by Techjar** [comment]
@iwubcode It would bloat the UI a lot by having to duplicate all the parameters (besides angle) and the calibration widget.

**Comment by jordan-woyak** [comment]
We decided against this.

**Pull request closed without merging**
