### PR TITLE
Move the Wiimote connect code out of Host

### PR DESCRIPTION
**Pull request by leoetlino**
There's no good reason for the Wiimote connect code to be part of the Host interface, and have that called from both the UI code and the core. And then hack around it by having "force connect" events whenever Host_ConnectWiimote is called from the core...

This also makes Wiimote connections unnecessarily undeterministic and complicated, since calling Host_ConnectWiimote queues a connection on the host thread, which then has to call PauseAndLock. This is true even when Host_ConnectWiimote is called from the CPU thread.

This PR gets rid of that nonsense and replaces Host_ConnectWiimote with Wiimote::Connect, that does the actual connection/disconnection and should always be called from the CPU thread.

### CODE REVIEW

**Comment by JMC47** [comment]
Real Wii Remotes over emualted Bluetooth crash dolphin

**Comment by leoetlino** [comment]
That issue should be fixed now. Also removed a call to Wiimote::Connect() if it's useless.

**Comment by leoetlino** [comment]
@BhaaLseN yeah, I wasn't sure about the name... Qt has setEnabled, maybe we could call it SetConnected?

**Comment by BhaaLseN** [comment]
Possibly, but this still sounds too odd (to me) for disconnecting. Naming things is hard, so I'd rather leave it as-is before this PR dies by bikeshedding.

**Comment by mimimi085181** [comment]
So i finally got around to testing this, and everything seems to still work, emulated wiimotes, real wiimotes(using a Dolphinbar) and passthrough mode. Tested with the disconnect in the home screen and es_launch titles(MP3 in MPT).

Can't say anything about the code though, couldn't spot any problems, but i don't understand the code, so... Well, there's one thing that i don't understand, why did you move "g_wiimotes_mutex.unlock();" and does that impact anything?

Reminder for reviewers, https://github.com/dolphin-emu/dolphin/pull/4949 is blocked until this pr is merged, because it doesn't work without it.

**Comment by JMC47** [comment]
I was able to connect and disconnect a Real Wii Remote without it crashing.

**Comment by leoetlino** [comment]
@mimimi `Wiimote::Connect` locks the mutex itself, so we need to unlock before calling it to avoid a deadlock.

**Pull request merged**
