### PR TITLE
Qt: Deduplicate settings

### PR DESCRIPTION
**Pull request by spycrab**
Fixes [issue #11017](https://bugs.dolphin-emu.org/issues/11017).

### CODE REVIEW

**Comment by spycrab** [comment]
@MayImilae @JMC47

**Comment by JMC47** [comment]
Does anyone else have an opinion on Render ot Main?  I'd honestly prefer it in interface long-term.  I know people are used to it in graphics... but... it's more an interface thing.  If we don't change it, people will never get used to it being moved.  If we want it there so be it.

**Comment by MayImilae** [comment]
I proposed keeping render to main where it is since it is directly related to rendering so the location is accurate, and also because it's used a lot and I wanted to avoid confusing users. Also it does kind of impact the interface? But it's more rendering related, imo.

**Comment by JMC47** [comment]
I have to disagree with what you're saying.  It doesn't deal with rendering, but rather the interface.  It changes the window layout, more or less.

**Pull request merged**
