### PR TITLE
CMake: fix PolarSSL test

### PR DESCRIPTION
**Pull request by Tilka**
The compile test always failed :|

### CODE REVIEW

**Comment by phire** [comment]
Should this go into stable?

**Comment by Tilka** [comment]
It makes Dolphin use the shared version of PolarSSL if available instead of always falling back to the one in Externals, so... probably?

**Comment by phire** [comment]
Yeah, that's what I was thinking. No need to annoy the packagers.

**Comment by jcowgill** [comment]
This hasn't been forgotten for stable has it (since I will have to patch it if it doesn't go in)?

**Comment by JosJuice** [comment]
I'll make sure to bug Armada about it. I must admit that I didn't notice this PR before, though.

**Pull request merged**
