### PR TITLE
Update comments RenderWidget.cpp

### PR DESCRIPTION
**Pull request by luc-git**
This PR adds more infos on which functions to use to implement "Lock Mouse Cursor" on linux OS

### CODE REVIEW

**Comment by luc-git** [comment]
Is it good?

**Comment by AdmiralCurtiss** [comment]
I genuinely couldn't tell you, I don't know if we have any devs familiar with X or Wayland specifics.

**Comment by AdmiralCurtiss** [comment]
fwiw since this is just a comment there's probably no harm in merging it...

**Comment by AdmiralCurtiss** [comment]
Though for X it's probably easier to just use XGrabPointer as previously suggested: https://stackoverflow.com/a/36269507

**Comment by luc-git** [comment]
> Though for X it's probably easier to just use XGrabPointer as previously suggested: https://stackoverflow.com/a/36269507

Sdl also uses it https://github.com/libsdl-org/SDL/blob/9f7eb6c4c11b445da0fcadb357e1c7ed053b0084/src/video/x11/SDL_x11xfixes.c#L163

> The XGrabPointer() function actively grabs control of the pointer and returns GrabSuccess if the grab was successful.
 
https://tronche.com/gui/x/xlib/input/XGrabPointer.html

`XGrabPointer()` only grabs mouse inputs not the mouse cursor. There are some limitations with the `grabmouse()` function 

https://doc.qt.io/qt-6/qwidget.html#grabMouse but at least it's way easier to use the equivalent with Qt than just the X11 function

**Comment by luc-git** [comment]
Okay I reverted the `XGrabPointer` part and if it doesn't work or doesn't give the result we expect all commits will still be preserved

**Pull request merged**
