### PR TITLE
RetroAchievements - Default Badges

### PR DESCRIPTION
**Pull request by LillyJadeKatrin**
This PR covers the addition and use of default icons ("badges") for player, game, and achievements pertaining to the RetroAchievements integration. Badges are an optional setting on account of the quantity and size of the additional server calls needed to download them; previous versions of Dolphin simply omitted badges entirely if they weren't available. This, however, leads to changes in visual presentation and formatting, most notably pertaining to challenges, which when badges are available shows badges on screen to denote an active challenge, which was entirely missing when badges from the site were turned off. This PR resolves these issues by providing default sample badges that the system can use instead.

In the long term, the badges themselves, where they are located, and how they are loaded into Dolphin (presumably as part of a Theme) will be developed with assistance from Dolphin's GUI experts (e.g. MayImilae) so the first commit of this PR will change dramatically, but the remainder of the PR should be accurate and ready for a full critique.

### CODE REVIEW

**Comment by MayImilae** [comment]
One thing you may want to know even in this early phase is that we do not differentiate anything by colour. So to match the rest of Dolphin, "Trophy" and "Trophy Color" won't really work. But this is all just for now so I don't know if you want to correct that or not.

**Comment by LillyJadeKatrin** [comment]
Oh, all of this is getting renamed and reworked as soon as we have actual .pngs to use, I just used color because internally RetroAchievements tends to (but doesn't always) use grayscale vadges to mean locked and color badges to mean unlocked. They just needed two different files and I was lazy.

**Comment by AdmiralCurtiss** [comment]
I'll set this to draft until we have actual images.

**Comment by LillyJadeKatrin** [comment]
Closing due to deprioritizing. Will re-examine once #12639 is complete and merged.

**Pull request closed without merging**
