### PR TITLE
Fix Kirby's Adventure Wii Metafortress bypass patch

### PR DESCRIPTION
**Pull request by vaguerant**
The existing Metafortress patch for Kirby's Adventure Wii (Europe) has several incorrect offsets which must have crept in during the porting process, resulting in the game booting to a black screen when it is enabled.

As far as I know, the issue has not been formally reported, but it was noted in the Dolphin forums:
- [post 533193 by gabberhead in [Wii] Kirby's Return to Dream Land](https://forums.dolphin-emu.org/Thread-wii-kirby-s-return-to-dream-land?pid=533193#pid533193)

These offsets seem to have been calculated mathematically by comparing directly against the US version, but the deltas are not reliably the same across versions.

They were corrected by using Dolphin's disassembler to compare the relevant offsets in the USA and Europe region games against the Metafortress handling in USB Loader GX:
- [usbloadergx/source/patches/kirbypatch.c](https://github.com/wiidev/usbloadergx/blob/e25c4e96430524c080767679b0c4a0d7595412a8/source/patches/kirbypatch.c)

### CODE REVIEW

**Review by JosJuice — APPROVED** [review]
Confirmed working.

**Comment by OatmealDome** [comment]
Should we update the credit in the patch name?

**Comment by JosJuice** [comment]
I'd say @vaguerant can choose.

**Comment by vaguerant** [comment]
I'm fine not to be credited, I don't consider what I did to be significant relative to the contributions of crediar and RedStoneMatt.

**Review by OatmealDome — APPROVED** [review]
Alright. sounds good. Thanks for the PR!

**Pull request merged**
