### PR TITLE
Small cleanups of DSPAssembler and the free DSP ROM code

### PR DESCRIPTION
**Pull request by ligfx**
- DSPAssembler: Remove unnecessary usage of a temporary file.
- DSPAssembler: Fix `ORG` directive to seek forward past the current end-of-file, just like xkas.
- DSPAssembler: Add `WARNPC` directive from xkas/asar (to allow the seek-forward-only idiom `warnpc 0xXXXX; org 0xXXXX`).
- dsp_rom.ds: Fix all of the janky line endings/trailing whitespace.
- dsp_rom.ds: Replace runs of nops with WARNPC/ORG directives.

### CODE REVIEW

**Comment by ligfx** [comment]
@dolphin-emu-bot rebuild

**Comment by ligfx** [comment]
@BhaaLseN GitHub [displays commits chronologically, not topologically](https://help.github.com/articles/why-are-my-commits-in-the-wrong-order/). 😞  If you apply each commit in the correct order (i.e. following its parent), `WARNPC` is implemented before it's used.

**Comment by BhaaLseN** [comment]
Dang, that one always gets me :S

**Comment by ligfx** [comment]
Yeah, me too.

**Pull request merged**
