### PR TITLE
Externals: Update glslang to upstream commit 32d3ec3

### PR DESCRIPTION
**Pull request by stenzek**
The version we were using is over a year old at this point. I'm wondering if this is related to the "black screen" issues that some users are reporting, since apparently it was "fixed' when using the VK_nv_glsl extension, but regressed once we disabled it.

### CODE REVIEW

**Comment by degasus** [comment]
No differences on Mali, but having an updated driver is likely a good idea.

**Comment by stenzek** [comment]
Holding off on this PR for now, until NV releases a driver update. We can drop the second commit (location assignment workaround), then.

**Comment by aunali1** [comment]
@stenzek Now that NV has released an update. Any status on merging this PR?

**Comment by aunali1** [comment]
Causes various graphical defects on Pixel C when using Vulkan. Additionally causes ubershader compilation to fail with OpenGL.

**Comment by degasus** [comment]
I guess there has been an update meanwhile. Do you think we should reupdate the glslang version in this PR?

**Comment by stenzek** [comment]
Updated to the latest version, and removed the workaround for the NV driver, as that has been long fixed.

**Comment by Lithium64** [comment]
This PR fixed the issue below
https://bugs.dolphin-emu.org/issues/10908

**Comment by Sarkie** [comment]
After bisecting for ages, this creates a black screen on Adreno 505 devices

Obviously a driver issue

**Comment by stenzek** [comment]
Not much I can do, I don't have any a5xx devices, and we're not going to downgrade the glslang version, as it fixes issues in desktop drivers.

**Comment by Sarkie** [comment]
That's ok, totally understand. Mobile drivers are the worst.

Is it this repo?

https://github.com/KhronosGroup/glslang

I'll raise an issue there.

**Comment by stenzek** [comment]
You'll have to figure out which shader is broken in the new revision first. Furthermore, glslang is likely not the issue here, unless it's emitting invalid SPIR-V. The issue probably lies in qcom's driver.

**Pull request merged**
