### PR TITLE
Update Android UI Settings to have the most common used settings

### PR DESCRIPTION
**Pull request by mahdihijazi**
I will try to update the ui settings for Android to match the latest desktop version, please let me know if I missed any and you think it should be added.

- [x] Fix clock speed slider to use incremental values of 5% instead of 20%.
- [x] Move the Aspect Ration Settings from the Enhancements Section to the General section.
- [x] Add Force 24-Bit Color enhancement option.
- [x] Support Post Processing Shaders.
- [x] Dedicated GameCube Section + System Language.
- [x] Dedicated Wii Section + ~~System Language~~.
- [x] Speed Limit Setting.
- [x] WideScreen Hack.
- [x] Expose arbitrary mipmap detection toggle in UI.

Edit: Wii system language will be moved to separate PR since it require more work and I don't want to delay this PR any more.

### CODE REVIEW

**Comment by JMC47** [comment]
This all sounds good to me so far.  Based on where the UI is now, this would make most of the things I typically use in the desktop version of Dolphin available to me in Dolphin Android.

**Comment by Ebola16** [comment]
If you're looking for common UI options that I greatly miss on Android, here are some:
[Android: Add Panic Handles toggle to UI](https://bugs.dolphin-emu.org/issues/10787)
[Android: Add "Set as default ISO" to UI](https://bugs.dolphin-emu.org/issues/10781)
[Android: Add SD card setting to GUI](https://bugs.dolphin-emu.org/issues/10700)
[Android: Add "Install WAD" to UI](https://bugs.dolphin-emu.org/issues/10788)
[Android: Add recursive ISO and GCM paths to UI](https://bugs.dolphin-emu.org/issues/10806)

These may be a little harder to implement but I miss them too:
[Android: Add cheat code-related settings and tabs](https://bugs.dolphin-emu.org/issues/10701)
[Android: Add logging settings to GUI](https://bugs.dolphin-emu.org/issues/10709)
[Android: Display chosen setting under setting name](https://bugs.dolphin-emu.org/issues/10699)

**Comment by mahdihijazi** [comment]
@JosJuice @gwicks can you please have a look on this PR

**Comment by Techjar** [comment]
We just added Arbitrary Mipmap Detection toggle in #7177, so you should probably add it here too.

**Comment by mahdihijazi** [comment]
@Techjar done

**Pull request merged**
