### PR TITLE
VideoBackends: Merge backend initialization and shutdown.

### PR DESCRIPTION
**Pull request by degasus**
[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3510)

### CODE REVIEW

**Comment by lioncash** [comment]
LGTM

**Comment by JMC47** [comment]
D3D crashes on close in this PR.

**Comment by degasus** [comment]
Bad news, this PR triggers the bug fixed in PR #3530.

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by delroth** [comment]
I don't think we should merge that until 5.0 is released anyway. It doesn't address any of our regressions and it's slightly more dangerous than I like cleanups to be.

---

Review status: 0 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3510#-:-K8R4G-Wnu4kIkQLZzNr:1099676148)*

**Comment by Fallcrest** [comment]
@degasus 5.0 is out and three new video backends are on the horizon (Null, Vulkan, and Metal). Finishing cleaning up VideoCommons will be valuable for not just making those three, but simplifying work on all of them in the future.

**Comment by degasus** [comment]
On IRC:
Stenzek> LGTM for 3510

**Comment by degasus** [comment]
This PR needs https://github.com/dolphin-emu/fifoci/pull/17 first.

**Comment by phire** [comment]
LGTM as soon as fifoci is fixed.

---

Reviewed 37 of 40 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Core/VideoBackends/OGL/main.cpp, line 119 \[r4\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3510#-KLB5MP9VvJlhzaBeG-O:-KLB5MP9VvJlhzaBeG-P:-266768808) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f0d59a43f3889b0f008897d077bd73b3d035b052/Source/Core/VideoBackends/OGL/main.cpp#L119)):*
> ```cpp
>   g_Config.backend_info.bSupportsSSAA = true;
> 
>   // Overwritten in Render.cpp later
> ```

BTW, I have future plans to initialize opengl and collet correct information here, like we do in directx.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3510#-:-KLB60AOCoUAb7Iz27ob:456615570)*

**Comment by BigheadSMZ** [comment]
Both D3D backends crash Dolphin instantly when loading a game since this was merged, no problems with 5.0-72. Is this a problem on my end?

**Comment by JosJuice** [comment]
@BigheadSMZ There's a similar issue on the issue tracker. https://bugs.dolphin-emu.org/issues/9643

**Comment by akyryz** [comment]
all my games stopped working after this =(

**Comment by degasus** [comment]
@akyryz Are they fixed again by https://dolphin-emu.org/download/dev/a4f2f13c3d10e030cbd092bea97052f901e7bd70/ ?

**Comment by akyryz** [comment]
5.0-92 and still insta crash

**Comment by BigheadSMZ** [comment]
I never use render to main window and I'm not having any issues after the bbox fix. Still, tried it both checked/unchecked and no problems.

**Comment by akyryz** [comment]
are you using OpenGL or Direct3D 11?
just tested and OpenGL works fine in both with v5.0-94

**Comment by akyryz** [comment]
news: if i set Fullscreen to false (window mode) it works in Direct3D 11

**Comment by stenzek** [comment]
Can you provide any more information (driver/vendor/OS), or any chance you could get a crash dump or call stack? I'm also unable to reproduce with any combination of fullscreen/D3D11/D3D12/render-to-main-window settings.

**Comment by degasus** [comment]
stenzek: maybe exclusive fullscreen?

**Comment by akyryz** [comment]
[dolphin.log.txt](https://github.com/dolphin-emu/dolphin/files/337598/dolphin.log.txt)
[Dolphin.ini.txt](https://github.com/dolphin-emu/dolphin/files/337606/Dolphin.ini.txt)
[GFX.ini.txt](https://github.com/dolphin-emu/dolphin/files/337604/GFX.ini.txt)

**Comment by akyryz** [comment]
was this added somewhere else?
void VideoBackend::Video_Prepare() {
...
// Tell the host that the window is ready
Host_Message(WM_USER_CREATE);
}

**Comment by badkarma12** [comment]
@degasus 

This PR crashes all WII games when used on D3D 11 regular fullscreen mode. Just a blackscreen and full lockup that requires a force close with task manager. D3D 12 and Open GL work perfectly. It also works with render to main.

**Comment by akyryz** [comment]
i just want to point out that i debugged in visual studio and what happens is an infinite loop waiting for something, pity dev builds doesn't come with symbols to tell which method is causing the problem

**Comment by degasus** [comment]
@akyryz Where is the infinite loop?

**Pull request merged**
