### PR TITLE
Ubershader optimizations for NVIDIA

### PR DESCRIPTION
**Pull request by stenzek**
The switch statements in these functions appear to get transformed into an if..else chain on NVIDIA's OpenGL/Vulkan drivers (at least according to the IL asm), resulting in lower performance than the D3D counterparts. Transforming the switch into a binary tree of ifs can increase performance by up to 20%.

Marked WIP since it needs more testing, and we need to check the other vendors, as the switch may still be more efficient there.

I also have a version that uses shader subroutines instead of the switch statements, although this had similar performance with I'm guessing higher CPU overhead (as well as not working with Vulkan).

### CODE REVIEW

**Comment by mimimi085181** [comment]
After a quick test it seems to be fine on amd. Windows 7, Radeon HD 7790, Opengl + exclusive ubershaders, the pr is a bit faster compared to 5.0-4992, at least in new super mario bros. It's something around 60-70 fps vs 48-61 fps at 3xIR.

**Comment by JMC47** [comment]
Neat, if we can get both Radeon + NVIDIA faster it's a win/win

**Comment by orbea** [comment]
I tested this briefly with nouveau GL and exclusive ubershaders. It seems at least a little bit faster here too.

**Comment by tabnk** [comment]
Performance improved on GTX 960 with Vulkan :). Nice. Although DirectX 11 still look smoother on Mario kart Wii :).

**Comment by stenzek** [comment]
Now fifoci regression free against specialized shaders from master. Should be good to go.

**Pull request merged**
