### PR TITLE
Modernize Dolphin Logo

### PR DESCRIPTION
**Pull request by Scrumplex**
This PR replaces all occurrences of the dated logo with a newer modernized one. 
I removed the shadow to make it monochrome and replaced the gradient with a solid color. I also made the logo narrower and a bit taller. 

I tried to [balance](https://en.wikipedia.org/wiki/Visual_design_elements_and_principles#Balance) the logo in the square (1:1) icons, as we are working with an asymmetric logo.<sup>1</sup>

Screenshot of the About page with the new logo

The new logo asymmetrically balanced 2048x2048:
New Dolphin Logo

Comparison (left: new logo, right: old logo):
Logo Comparison

<sup>1</sup>: A good example of an asymmetrically balanced logo is the Nintendo Switch logo, as the right "joy-con" is narrower than the left "joy-con", because it would have more visual weight otherwise. See [this article](https://brandingbeard.com/lessons/symmetry-asymmetry-logo-design-nintendo-switch-way/)

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Ping @MayImilae

**Comment by Miksel12** [comment]
I like the new style, but I think the old dolphin design looks better. Personally I think the curve is to sharp and a bit uneven. 
Besides that, the buttons in the UI (open, refresh etc) should also be modernized to fit the new style, if this gets merged.

**Comment by MayImilae** [comment]
Hard against. Just making it flatter doesn't make a design better, and design trends are actually moving away from flatness now, making this PR logo look more dated than my original. Plus all the intent behind the curves symbolizing a Dolphin leaping out of water is being lost, not to mention they are improperly weighted so the curves have a lumpy appearance.

**Comment by jordan-woyak** [comment]
I don't particularly care for either logo and this PR is not enough of a change (let alone improvement) to warrant the hassle of changing the logo everywhere else its used: website, youtube, etc.

**Comment by Scrumplex** [comment]
I am open to criticism and can also understand the reasons to not accept this PR. It is up to the maintainers/contributors to decide here.

**Comment by DevBonBon** [comment]
I can't really see Maylmilaes criticisms, but then again I'm no design expert. Tbh I like the design, but do agree with jordan, only changing the logo is not really enough for the hassle it causes. The interface could benefit from a newer theme / icon set though

**Comment by Scrumplex** [comment]
I just tweaked the logo a bit and updated the screenshot in the PR

**Comment by JMC47** [comment]
So, regardless of my opinion of changing the logo for the next release, I don't believe this is the right way to go about submitting something like this.  As a big project, we don't just change the logo on a whim and I don't think this pull request will serve much of a purpose.

The current logo was something worked on by the whole team with @MayImilae providing the artistic background to actually create something that fit the direction of the project.  When we do a refresh of the art assets, it's not going to be something we just flip over in one day - there's going to be a lot of thought, designs, and iterations.  If you're serious about wanting to make a new logo for Dolphin as more than a pet project, it'd be best to actually be an active part of the community rather than someone outside of the project.

**Comment by MayImilae** [comment]
As the resident designer, I have some tips!

This was absolutely the wrong way to go about this. It doesn't matter how bad you think someone's logo is or how much better you think you can do, never ever approach someone with branding changes that no one has asked for! It needs to be something they approach you about, or you see interest in from within the community and propose to handle. Logo design and branding are big things - they are an extension and presentation of the identity of the group, so the whole group needs to be involved and committed. And yes, during rebranding, people other than you will have to put in work too, a logo is only a part of the branding effort! They need to be willing to commit to their share of the process, and trust you to be able to work well with them. Branding always has to start with the client wanting to do it in the first place. In my case, I was already a freelancer for years, and joined the Dolphin community as a hobby working on the wiki. When interest in a new logo was being talked about, I was an established member of several years, so everyone knew me already. So I raised my hand, showed my credentials, and offered to help. It was a lot of work, hundreds of hours of work, and everyone was involved, but we ended up with something everyone was happy with, and developed a symbol that represented the new mature Dolphin that we wanted to be going forward. Even though I had the ability to improve the branding before then, and the existing logo was (in my opinion) not a good fit for the project anymore, I never pushed for a fix. Lots of people were happy with it after all! Once there was interest in a new logo and branding, I wanted to do it, so I offered, and it went from there!

A project this big is a really bad place to cut your teeth in branding. Dolphin is a big project that's established with its own branding and identity which we members have spent years building and cultivating. It's not really a place where an outsider can just walk in and make big changes. If you want to jump in and learn, there are a lot, and I mean a LOT, of small communities on the internet getting by with some really bad art that would ADORE some help with their branding! The absolute best way to learn branding and design is to get into freelancing. There you will find a sea of people asking for help, and can pick and choose what you want to commit to!  I myself had nearly ten years (ooph, time!) of freelancing experience before I worked on the Dolphin's branding.

**Comment by Scrumplex** [comment]
Thanks for the tips @Maylmilae. 
I understand your decision @JMC47 and fully accept it. 

How would you react to a redesign of the current UI icons? As @Miksel12 already mentioned, they are in need of a refresh, especially because they are pretty low-res in a world that is slowly moving to HiDPI. I would be willing to work on them instead.

**Comment by JosJuice** [comment]
Most of the UI icons already have HiDPI versions. The exceptions are the debugger icons (which actually just are placeholders for now) and the ISOProperties icons.

**Pull request closed without merging**
