### PR TITLE
Android: Add cheat GUI

### PR DESCRIPTION
**Pull request by JosJuice**
This is one of the most requested features from Android users.

 

I would appreciate if this could be merged in mid-October at the latest, since that's when I'm planning to merge PR #9696. The new location for the User folder which that PR introduces is relatively hard to access on Android 11, and cheats are currently the main reason for the typical Android user to go digging around in the User folder.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/10092)

### CODE REVIEW

**Comment by JMC47** [comment]
Tested and verified everything to work correctly.

Creating new cheats works

image

Downloading Gecko Codes works

image
image

Enabling/Disabling cheats works, as well as the shortcut to the config panel to re-enable cheats globally if they are disabled.  There is one strange thing in my opinion.  There's no checkmark to "save" (even though I'm guessing INIs save as soon as I select an option?) you just have to hit back, which isn't really a problem as the other menus also do this.  It's just weird there isn't some checkmark/save icon in the upper right to save just like in the other menus I guess.

LGTM otherwise, all functionality works, and I'm not too hung up on this one tiny thing that probably has a reason behind it.

**Comment by BlueSwordM** [comment]
Everything seems to work correctly as well, including the creation of a new cheat, and downloading them if they exist.

I have the same "complaint" as JMC: a UI toggle switch to save or indicate "OK" to the user should be present to not be confusing.

https://slow.pics/c/OTKlcPWr

Really nice to see an RGB trail code working on Android(don't mind the missing model, this is a mod bug, not a Dolphin bug).

**Comment by JosJuice** [comment]
It saves as soon as you leave the activity (more specifically in `onStop`). I've felt that the save icon we have in the settings activity feels rather un-Android-like (it's actually a holdover from back when Dolphin didn't save the settings automatically and if you didn't hit the save button all your changes would be lost with no warning, which was pretty terrible) and was thinking of removing it, but if people would prefer to have one in the cheats activity, I suppose I could add one there instead.

For what it's worth, the game properties on desktop don't have a Save/OK button either, just a close button. Does it make sense anyway?

**Comment by JMC47** [comment]
Even just a checkmark to close to the menu in the upper right would be enough if you don't think the save is appropriate.  I don't care that much about it, obviously.  It's just one of the things I noticed while using it.

**Comment by JosJuice** [comment]
I've added a save button for now (like in the settings activity).

**Review by JMC47 — APPROVED** [review]

**Comment by JMC47** [comment]
Everything works as expected now.

**Review by leoetlino — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 19 of 19 files at r2, 3 of 3 files at r3, 12 of 12 files at r4, 9 of 9 files at r5, 4 of 4 files at r6, 14 of 14 files at r7, 5 of 5 files at r8, 12 of 12 files at r9, 11 of 11 files at r10, 1 of 1 files at r11, 8 of 8 files at r12, 14 of 14 files at r13, 5 of 5 files at r14, 6 of 6 files at r15, 7 of 7 files at r16, 13 of 13 files at r17, 1 of 1 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/10092)* status: all files reviewed, 6 unresolved discussions (waiting on @JosJuice)

___
*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/ARCheat.java, line 25 at r4](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjfcvVCAWn-6bZmYzj2:-MjfcvVCAWn-6bZmYzj3:b-ygxx91) ([raw file](https://github.com/dolphin-emu/dolphin/blob/31bc5ba3ee3b5a17850077017f273297ec0df13b/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/ARCheat.java#L25)):*
> ```Java
>   public native String getName();
> 
>   public native boolean getEnabled();
> ```

Not that it really matters, but would it make sense for this to be part of the AbstractCheat interface?
___
*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/CheatsViewModel.java, line 255 at r17](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjflwcPD-EOuRA_u2La:-MjflwcPD-EOuRA_u2Lb:b753uis) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aac5ab46167563371869e8f037185afd668d8bca/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/CheatsViewModel.java#L255)):*
> ```Java
>     for (GeckoCheat cheat : cheats)
>     {
>       if (!mGeckoCheats.contains(cheat))
> ```

How many cheats will mGeckoCheats typically contain? If `cheats` and `mGeckoCheats` have about the same size (or if they're equal because the user tried to re-download cheats and mGeckoCheats already contains all downloaded cheats), this has quadratic time complexity.
___
*[Source/Android/jni/Cheats/ARCheat.cpp, line 95 at r4](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjfhjxCDUqJNeH_29Ns:-MjfhjxCDUqJNeH_29Nt:b7yj4ue) ([raw file](https://github.com/dolphin-emu/dolphin/blob/31bc5ba3ee3b5a17850077017f273297ec0df13b/Source/Android/jni/Cheats/ARCheat.cpp#L95)):*
> ```cpp
> 
>   const std::string game_id = GetJString(env, jGameID);
>   const std::string ini_path = File::GetUserPath(D_GAMESETTINGS_IDX) + game_id + ".ini";
> ```

Not really an issue with your PR, but at some point we should probably add a "get game INI path" helper — this is duplicated dozens of times across the codebase :(
___
*[Source/Android/jni/Cheats/Cheats.h, line 6 at r7](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjfizjXECwu-J9M8k2Q:-MjfizjXECwu-J9M8k2R:b-bjghbm) ([raw file](https://github.com/dolphin-emu/dolphin/blob/eac06d9efb5ff12d0560626e0b42296800a985d8/Source/Android/jni/Cheats/Cheats.h#L6)):*
> ```objc
> #pragma once
> 
> constexpr int TRY_SET_FAIL_NO_NAME = -1;
> ```

Could we add a name prefix or put this in some namespace?
___
*[Source/Android/jni/Cheats/GeckoCheat.cpp, line 92 at r9](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjfjhjE8mTC9mpPNeLa:-MjfjhjE8mTC9mpPNeLb:b-ic9a42) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f45d685e85e8ad2e3ac309cbd8611789f195d720/Source/Android/jni/Cheats/GeckoCheat.cpp#L92)):*
> ```cpp
> 
>     if (std::optional<Gecko::GeckoCode::Code> c = Gecko::DeserializeLine(line))
>       entries.push_back(*c);
> ```

Consider moving the code into `entries`: `entries.emplace_back(*std::move(c))`
___
*[Source/Android/jni/Cheats/GeckoCheat.cpp, line 197 at r17](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjfmTBl-U4w-x5adPoT:-MjfmTBl-U4w-x5adPoU:btc4z5m) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aac5ab46167563371869e8f037185afd668d8bca/Source/Android/jni/Cheats/GeckoCheat.cpp#L197)):*
> ```cpp
>   const std::string gametdb_id = GetJString(env, jGameTdbId);
> 
>   bool success;
> ```

Could we set success to a sane value (false), just in case DownloadCodes does not do it (for whatever reason, including bad refactoring in the future)?
___
*[Source/Android/jni/Cheats/PatchCheat.cpp, line 91 at r9](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-Mjfk5rT8x3Ed6agTPTD:-Mjfk5rT8x3Ed6agTPTE:b-x3j718) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f45d685e85e8ad2e3ac309cbd8611789f195d720/Source/Android/jni/Cheats/PatchCheat.cpp#L91)):*
> ```cpp
> 
>     if (std::optional<PatchEngine::PatchEntry> entry = PatchEngine::DeserializeLine(line))
>       entries.push_back(*entry);
> ```

`entries.emplace_back(*std::move(entry))`

**Comment by JosJuice** [comment]
___
*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/ARCheat.java, line 25 at r4](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjfcvVCAWn-6bZmYzj2:-Mjj0Svp1PMgNV-EIVkS:bqp4r24) ([raw file](https://github.com/dolphin-emu/dolphin/blob/31bc5ba3ee3b5a17850077017f273297ec0df13b/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/ARCheat.java#L25)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Not that it really matters, but would it make sense for this to be part of the AbstractCheat interface?
</blockquote></details>

This is already part of the `Cheat` interface, which `AbstractCheat` implements.

**Review by JosJuice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/10092)* status: all files reviewed, 6 unresolved discussions (waiting on @leoetlino)

___
*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/CheatsViewModel.java, line 255 at r17](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjflwcPD-EOuRA_u2La:-Mjj0sc14nJyjSYdRlyk:b-hh7vfo) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aac5ab46167563371869e8f037185afd668d8bca/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/CheatsViewModel.java#L255)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

How many cheats will mGeckoCheats typically contain? If `cheats` and `mGeckoCheats` have about the same size (or if they're equal because the user tried to re-download cheats and mGeckoCheats already contains all downloaded cheats), this has quadratic time complexity.
</blockquote></details>

Perhaps a few hundred at worst, if the user has downloaded codes for a popular game. This is the same algorithm as in DolphinQt (GeckoCodeWidget.cpp).
___
*[Source/Android/jni/Cheats/Cheats.h, line 6 at r7](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjfizjXECwu-J9M8k2Q:-Mjj1hdw23RGFBXgxWhf:b-li518d) ([raw file](https://github.com/dolphin-emu/dolphin/blob/eac06d9efb5ff12d0560626e0b42296800a985d8/Source/Android/jni/Cheats/Cheats.h#L6)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Could we add a name prefix or put this in some namespace?
</blockquote></details>

Do you have a suggestion for a namespace name?
___
*[Source/Android/jni/Cheats/GeckoCheat.cpp, line 92 at r9](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjfjhjE8mTC9mpPNeLa:-Mjj36Tp4zj_hDTCn_Ds:bkaxluv) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f45d685e85e8ad2e3ac309cbd8611789f195d720/Source/Android/jni/Cheats/GeckoCheat.cpp#L92)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Consider moving the code into `entries`: `entries.emplace_back(*std::move(c))`
</blockquote></details>

Done (and I did it for ARCheat as well).
___
*[Source/Android/jni/Cheats/GeckoCheat.cpp, line 197 at r17](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjfmTBl-U4w-x5adPoT:-Mjj34Ya2D8g5u4XHuKz:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aac5ab46167563371869e8f037185afd668d8bca/Source/Android/jni/Cheats/GeckoCheat.cpp#L197)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Could we set success to a sane value (false), just in case DownloadCodes does not do it (for whatever reason, including bad refactoring in the future)?
</blockquote></details>

Done.
___
*[Source/Android/jni/Cheats/PatchCheat.cpp, line 91 at r9](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-Mjfk5rT8x3Ed6agTPTD:-Mjj3Hf-2sjx1o4DmeNB:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/f45d685e85e8ad2e3ac309cbd8611789f195d720/Source/Android/jni/Cheats/PatchCheat.cpp#L91)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`entries.emplace_back(*std::move(entry))`
</blockquote></details>

Done.

**Review by leoetlino — COMMENTED** [review]
> Reviewed 1 of 40 files at r20, 2 of 19 files at r21, 2 of 3 files at r22, 2 of 9 files at r24, 1 of 4 files at r25, 1 of 14 files at r26, 1 of 12 files at r28, 1 of 11 files at r29, 1 of 8 files at r31, 7 of 14 files at r32, 1 of 5 files at r33, 2 of 6 files at r34, 5 of 7 files at r35, 12 of 13 files at r36, 1 of 1 files at r37, 1 of 1 files at r38, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/10092)* status: all files reviewed, 2 unresolved discussions (waiting on @JosJuice)

___
*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/ARCheat.java, line 25 at r4](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjfcvVCAWn-6bZmYzj2:-MjjMogg8js4PqZAXQ0j:b-k15u7p) ([raw file](https://github.com/dolphin-emu/dolphin/blob/31bc5ba3ee3b5a17850077017f273297ec0df13b/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/ARCheat.java#L25)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary><blockquote>

This is already part of the `Cheat` interface, which `AbstractCheat` implements.
</blockquote></details>

Oh, my bad.
___
*[Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/CheatsViewModel.java, line 255 at r17](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjflwcPD-EOuRA_u2La:-MjjNceX4ZT6FazL991R:bgp10i8) ([raw file](https://github.com/dolphin-emu/dolphin/blob/aac5ab46167563371869e8f037185afd668d8bca/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/features/cheats/model/CheatsViewModel.java#L255)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary><blockquote>

Perhaps a few hundred at worst, if the user has downloaded codes for a popular game. This is the same algorithm as in DolphinQt (GeckoCodeWidget.cpp).
</blockquote></details>

OK, that's probably fine then.
___
*[Source/Android/jni/Cheats/ARCheat.cpp, line 104 at r38](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjjNv7J-UxnhUJ5FJlZ:-MjjNv7J-UxnhUJ5FJl_:bdxnyz7) ([raw file](https://github.com/dolphin-emu/dolphin/blob/821b24fabb1e0e514a8b69f808861b2a96672a6d/Source/Android/jni/Cheats/ARCheat.cpp#L104)):*
> ```cpp
> 
>     if (std::holds_alternative<ActionReplay::AREntry>(parse_result))
>       entries.emplace_back(std::get<ActionReplay::AREntry>(std::move(parse_result)));
> ```

The move won't do anything because `parse_result` is const.
___
*[Source/Android/jni/Cheats/Cheats.h, line 6 at r7](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjfizjXECwu-J9M8k2Q:-MjjO-A4CzJ9dvbBWAsb:b-x7jxjf) ([raw file](https://github.com/dolphin-emu/dolphin/blob/eac06d9efb5ff12d0560626e0b42296800a985d8/Source/Android/jni/Cheats/Cheats.h#L6)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary><blockquote>

Do you have a suggestion for a namespace name?
</blockquote></details>

`Cheats`, perhaps? Or `Cheat` since that's what the class is called (though that would be inconsistent with this file's name).

**Review by JosJuice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/10092)* status: all files reviewed, 2 unresolved discussions (waiting on @leoetlino)

___
*[Source/Android/jni/Cheats/ARCheat.cpp, line 104 at r38](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjjNv7J-UxnhUJ5FJlZ:-MjjVYam2hoQ8gL7lp95:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/821b24fabb1e0e514a8b69f808861b2a96672a6d/Source/Android/jni/Cheats/ARCheat.cpp#L104)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

The move won't do anything because `parse_result` is const.
</blockquote></details>

Done.
___
*[Source/Android/jni/Cheats/Cheats.h, line 6 at r7](https://reviewable.io/reviews/dolphin-emu/dolphin/10092#-MjfizjXECwu-J9M8k2Q:-MjjVXEP5J19ZwepcSoy:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/eac06d9efb5ff12d0560626e0b42296800a985d8/Source/Android/jni/Cheats/Cheats.h#L6)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`Cheats`, perhaps? Or `Cheat` since that's what the class is called (though that would be inconsistent with this file's name).
</blockquote></details>

Done.

**Review by leoetlino — APPROVED** [review]
> Reviewed 3 of 32 files at r39, 1 of 11 files at r40, 1 of 8 files at r42, 7 of 14 files at r43, 1 of 5 files at r44, 2 of 6 files at r45, 5 of 7 files at r46, 12 of 13 files at r47, 1 of 1 files at r48, 1 of 1 files at r49, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/10092)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JosJuice)

**Pull request merged**
