### PR TITLE
Fix improper SRAM RTC offset

### PR DESCRIPTION
**Pull request by RisingFog**
This should fix the roughly three minute inaccuracy of the time when looked at through the GC BIOS.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4076)

### CODE REVIEW

**Comment by RisingFog** [comment]
I made a bad assumption here, closing until I properly test this.

**Comment by RisingFog** [comment]
Tested it, it works fine with normal RTC, but I'm running into an issue with custom RTC.

@lioncash This wasn't tested on hardware, but it does show the correct time (at least with normal RTC). I checked the previous value and the new value by converting the hex into a unix timestamp, and noticing the offset was the same offset as seen if the date/time was viewed through the GC BIOS. I'm not exactly too sure where the original sram_dump came from, though.

**Comment by BhaaLseN** [comment]
[According to YAGCD](http://hitmen.c02.at/files/yagcd/yagcd/chap10.html#sec10.5.1), that 0x40 changed to 0xFF is the interresting part here (the rest is just a checksum), unless I missed something. But, that bias value doesn't really seem all too useful at 0xFFFFFFFF...at least it looks odd to me (why bother if it has that value?)

**Comment by RisingFog** [comment]
@BhaaLseN I'm not really too sure either of it's place in the SRAM, perhaps hardware does something different that doesn't need to be accounted for in Dolphin?

**Comment by lioncash** [comment]
> @lioncash This wasn't tested on hardware

You should probably dump the SRAM and verify then. It's better than changing values until they happen to work, at least.

**Comment by RisingFog** [comment]
@lioncash After I discussed this with Extrems, he believes that setting it to 00 instead of FF was better for Dolphin. Because Dolphin uses either system RTC or the custom RTC, there should be no bias in the SRAM.

**Comment by lioncash** [comment]
Yeah, I saw the discussion take place. I think that's fine.

**Comment by degasus** [comment]
Fog_TAS:
because we're pulling directly from system time or custom rtc, there is no bias needed
the change is for the system clock of Gamecube
if you look in the BIOS on master, it shows a roughly three minute difference in time
compared to regular system time
this is because the counter bias in the provided SRAM was not set to 0
presumably, the SRAM was dumped from a real console with those values
which makes sense on a console, but not in Dolphin

**Pull request merged**
