### PR TITLE
Socket: Set SO_NOSIGPIPE on macOS

### PR DESCRIPTION
**Pull request by sepalani**
This PR is an attempt to fix a crash when running tests for https://github.com/dolphin-emu/dolphin/pull/8758 on macOS.

Ready to be reviewed.

### CODE REVIEW

**Comment by JMC47** [comment]
@MayImilae @OatmealDome ^

**Comment by OatmealDome** [comment]
Can confirm the part 2 HW test for #8758 no longer crashes with this PR.

**Comment by sepalani** [comment]
Thanks for testing. I'm surprised that I can't find on the issue tracker any issue related to this but at least that seems fixed.

**Comment by JMC47** [comment]
Can anyone review the code so we can merge this?

**Comment by stenzek** [comment]
Typical macOS being rubbish and not following the standard..

**Pull request merged**
