### PR TITLE
Fix typos and code coding conventions

### PR DESCRIPTION
**Pull request by Filoppi**
and removed some unused includes.

### CODE REVIEW

**Review by Pokechu22 — APPROVED** [review]

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Review by jordan-woyak — CHANGES_REQUESTED** [review]
You have two typos in your commit messages. "convenctions" and "convections".

**Comment by Filoppi** [comment]
> You have two typos in your commit messages. "convenctions" and "convections".

Meta. It was a test.
Guess that doesn't matter though?

**Comment by jordan-woyak** [comment]
> 
> 
> > You have two typos in your commit messages. "convenctions" and "convections".
> 
> Meta. It was a test.
> Guess that doesn't matter though?

It matters as much as the typos you fixed. :/
Use `git rebase -i upstream/master`
then you can use "reword" to change the messages.

**Comment by Pokechu22** [comment]
@dolphin-emu-bot rebuild

**Comment by Filoppi** [comment]
Fixed

**Review by jordan-woyak — APPROVED** [review]

**Pull request merged**
