### PR TITLE
update libusb to v1.0.26

### PR DESCRIPTION
**Pull request by shuffle2**
moves libusb to a submodule and updates to latest release.

### CODE REVIEW

**Comment by shuffle2** [comment]
```
CMake Warning (dev) at /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/BundleUtilities.cmake:237 (message):
  Policy CMP0080 is not set: BundleUtilities cannot be included at configure
  time.  Run "cmake --help-policy CMP0080" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/BundleUtilities.cmake:246 (_warn_cmp0080)
  Source/Core/DolphinQt/CMakeLists.txt:503 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Configuring incomplete, errors occurred!
```
that cmake code is:
```cmake
  # Ask for an application bundle.
  set_target_properties(dolphin-emu PROPERTIES
    MACOSX_BUNDLE true
    MACOSX_BUNDLE_INFO_PLIST ${CMAKE_CURRENT_SOURCE_DIR}/Info.plist.in
    XCODE_ATTRIBUTE_CODE_SIGN_ENTITLEMENTS "${CMAKE_CURRENT_SOURCE_DIR}/DolphinEmu.entitlements"
    XCODE_ATTRIBUTE_OTHER_CODE_SIGN_FLAGS "--deep --options=runtime"
    OUTPUT_NAME Dolphin
    )
```
why did this PR cause it to fail

**Comment by shuffle2** [comment]
the build currently fails because the `config.h.in` in dolphin's libusb wasn't actually the one from mainline libusb, and instead was something dolphin-custom to facilitate building libusb with cmake instead of autotools. Since we no longer need to patch libusb, i'm going to try to move it to a submodule as well and just keep the dolphin build system stuff

**Comment by AdmiralCurtiss** [comment]
You need to rebase this.

**Comment by shuffle2** [comment]
Why? Git should handle the drop off common commit, and GitHub isn’t showing conflicts…and I’m interested to see if it just works as I expect 🙃

**Comment by AdmiralCurtiss** [comment]
Yes, this technically does work in git, but as part of a clean commit history I'd prefer to not have unrelated commits in PR merges.

**Comment by shuffle2** [comment]
I think it will be dropped and not part of the merge (would be interested to know if that’s not the case)

**Comment by shuffle2** [comment]
(i just reworded the commit msg, no other changes)

**Comment by dreamsyntax** [comment]
> (i just reworded the commit msg, no other changes)

build is failing

**Comment by shuffle2** [comment]
> > (i just reworded the commit msg, no other changes)
> 
> build is failing

hrm, odd since it builds fine locally. i'll check it out..

**Comment by JosJuice** [comment]
@dolphin-emu-bot rebuild

**Comment by AdmiralCurtiss** [comment]
Seems fine. I'm just gonna merge this before it gets stuck...

**Comment by pizuz** [comment]
Regression: This build breaks GCAdapter connection on macOS (“Error opening Adapter: Access denied (insufficient permissions)”). The previous version 5.0-16287 still recognizes it. Shall I file a separate bug report?

**Comment by shuffle2** [comment]
@pizuz I'm not familiar with GCAdapter on macos, but have you checked latest posts here? https://forums.dolphin-emu.org/Thread-os-x-gcn-adapter-kext-testers-wanted?page=12 It seems you need some support outside of dolphin as well, and someone semi-recently made a new version of that using DriverKit. Maybe (re)try that?

Otherwise: Dolphin didn't have any macos-specific changes to libusb, so it would seem any regression is either from libusb API changes (ie dolphin needs to make some extra libusb calls now), or it's a regression in libusb itself.

Please open an issue.

**Comment by pizuz** [comment]
I‘m already using the new driver which has been working fine just up to this particular version. I‘ll file a report.

**Comment by shuffle2** [comment]
have you tried running dolphin with sudo?
I wonder if it is just this issue: https://github.com/libusb/libusb/issues/1014 (see especially the linked FAQ at end)

**Comment by ryanmcgrath** [comment]
>“Error opening Adapter: Access denied (insufficient permissions)”

That bug isn't related to libusb, as far as I know. It usually just requires some dumb combination of unplugging and plugging the adapter back in enough times until macOS cooperates. We see the same thing in Slippi Dolphin, which uses a much older variant/fork of Dolphin.

(You shouldn't need to run with sudo or anything. I wrote the modern drivers.)

**Comment by pizuz** [comment]
> have you tried running dolphin with sudo?
> I wonder if it is just this issue: [libusb/libusb#1014](https://github.com/libusb/libusb/issues/1014) (see especially the linked FAQ at end)

If I‘m reading [the FAQ](https://github.com/libusb/libusb/wiki/FAQ#How_can_I_run_libusb_applications_under_Mac_OS_X_if_there_is_already_a_kernel_extension_installed_for_the_device_and_claim_exclusive_access) correctly, Dolphin needs to be build with the `com.apple.vm.device-access` entitlement, in order for this to work.

As a side effect, it looks like we won‘t need that codeless kernel extension anymore and Dolphin should support this out of the box. Which would be nice.

Anyway, one might consider reverting this version bump until this is resolved. @OatmealDome?

**Comment by ryanmcgrath** [comment]
(That entitlement isn't granted for non-virtual-machine apps, AFAIK)

**Comment by shuffle2** [comment]
@pizuz can you try commenting out this block of code https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/InputCommon/GCAdapter.cpp#L325-L331 and seeing if it works as before for you?

when you test, first use the old dolphin build and ensure it works, then try the dolphin build with that commented out directly after.

**Comment by pizuz** [comment]
Yup. Works again.

Screenshot 2022-04-22 at 12 26 46

Screenshot 2022-04-22 at 11 55 19

Screenshot 2022-04-22 at 12 20 03

**Comment by shuffle2** [comment]
@pizuz can you try https://github.com/dolphin-emu/dolphin/pull/10599 ? hopefully it fixes the hang-at-exit issue, and otherwise it enables libusb debug printing, and I'd like to see the logs of why `libusb_detach_kernel_driver` fails for you. (it's probably just the permissions thing, but I'm wondering if it's actually just detecting that you already have GCAdapterDriver installed)

**Pull request merged**
