### PR TITLE
VertexShaderManager: Get rid of float pointer casts.

### PR DESCRIPTION
**Pull request by lioncash**

### CODE REVIEW

**Comment by shuffle2** [comment]
ping

**Comment by degasus** [comment]
Nice patch, but I have to agree with flacs about the type of XFMemory::posMatrices

**Comment by lioncash** [comment]
I forgot about this PR, I'll amend it later tonight.

**Comment by nbohr1more** [comment]
@dolphin-emu-bot rebuild

**Comment by lioncash** [comment]
I lied I'll be doing it today sometime.

**Comment by Tilka** [comment]
Ping.

**Pull request merged**
