### PR TITLE
CMake: build PortAudio as static library

### PR DESCRIPTION
**Pull request by ligfx**
Due to issues raised in #4255.

---

This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4388)

### CODE REVIEW

**Comment by BhaaLseN** [comment]
Should those two really be in quotes? The others don't.

@dolphin-emu-bot rebuild

**Comment by BhaaLseN** [comment]
Looks like it fixed fifoci-ogl-lin-intel. Still not sure about the quotes, but apparently this also works. Maybe someone else that actually knows CMake can pitch in about them?

**Comment by ligfx** [comment]
You're right, similar lines in `CMakeLists.txt` don't use quotes. I removed them to be consistent.

In this instance, quotes make no difference. The word `portaudio` will be treated as a single string value no matter what, since it doesn't have spaces and it's not a reserved word. The common case for quotes is when using paths, where, for example, calling `set(MY_LIBRARY My Documents/My Project/build/mylibrary)` will end up resolving as the list `"My;Documents/My;Project/build/mylibrary"`.

**Comment by Armada651** [comment]
LGTM, if the build passes I'll merge it.

@dolphin-emu-bot rebuild

**Pull request merged**
