### PR TITLE
Flatpak: Upgrade kde runtime to 6.8

### PR DESCRIPTION
**Pull request by cpba**
This version bundles SDL2-2.30.6, the temporary measure of building the vendored version from exports is no longer necessary.

### CODE REVIEW

**Comment by cpba** [comment]
The workaround lasted less than two days 😆

**Comment by OatmealDome** [comment]
Thanks for letting me know! Looks like there is a problem with finding `libevdev`.

**Comment by cpba** [comment]
Could you please re-run it? I'd like to rule out some sort of transitory issue in the build system.

I've read through the log and libevdev is built without any issue just a few lines earlier. I've rebased it on current master and run `flatpak-builder` locally on my machine, it builds without issue. 

It's also the exact same libevdev version that's getting built on flathub, those also build fine.

I've rebased on latest master in case it was being caused by some silly merge problem.

**Comment by OatmealDome** [comment]
Odd, only the x86_64 builder failed. I'll do some poking around on the build worker.

**Comment by OatmealDome** [comment]
@dolphin-emu-bot rebuild

**Review by OatmealDome — APPROVED** [review]
Well, that's interesting. I pushed my changes to switch the build pipeline over to `org.flatpak.Builder` and now it succeeds.

Anyway, I tested the PR build and it works fine. Thank you!

**Pull request merged**
