### PR TITLE
WiimoteEmu: Expose mappings for lifted UDraw and Drawsome stylus.

### PR DESCRIPTION
**Pull request by jordan-woyak**
UDraw is confirmed working. Drawsome is untested, but probably working.

### CODE REVIEW

**Comment by Rumi-Larry** [comment]
Is this already the case for the Drawsome tablet?

**Comment by jordan-woyak** [comment]
> Is this already the case for the Drawsome tablet?

No, but I implemented that now too, but untested.

**Comment by JMC47** [comment]
Seems to work for me.  Tested the Spongebob game.  I don't have any drawsome games that seem to require this though.

**Comment by AdmiralCurtiss** [comment]
Seems fine, let's just merge it and see if anyone who actually has one of those games yells.

**Pull request merged**
