### PR TITLE
Externals: Update libpng to 1.6.20

### PR DESCRIPTION
**Pull request by ZephyrSurfer**
Update the png ibrary to the latest.
Update existing pngconf.h

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3374)

### CODE REVIEW

**Comment by delroth** [comment]
@dolphin-emu-bot rebuild

I'm curious if that fixes anything useful to us?

**Comment by Pringo** [comment]
This PR is out of date now. The latest libpng release is 1.6.23.

**Comment by RisingFog** [comment]
Echoing the comments above, does updating libpng provide any fixes for us? And if it does, would it be possible to update it to the latest libpng release?

**Comment by JamesKoenig** [comment]
Dolphin currently doesn't compile with the built-in external libpng as ImageWrite.cpp.o and libvideocommon.a both currently compile to reference png_set_longjmp_fn, [which wasn't introduced to libpng until version 1.4](https://github.com/glennrp/libpng/blob/libpng14/pngerror.c#L248).  The PR's suggested [1.6 also defines the function](https://github.com/glennrp/libpng/blob/libpng16/pngerror.c#L597), but 1.2.5 does not.

An example of the error from when I tried to compile earlier:
`Undefined symbols for architecture x86_64:
  "_png_set_longjmp_fn", referenced from:
      TextureToPng(unsigned char*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, bool) in libvideocommon.a(ImageWrite.cpp.o)
ld: symbol(s) not found for architecture x86_64
`
[a bunch of examples (via google) of other people encountering the same error](https://encrypted.google.com/search?hl=en&q=dolphin%20%22png_set_longjmp_fn%22%20error%20site%3Adolphin%2Demu.org#q=dolphin+%22png_set_longjmp_fn%22+error+site:dolphin-emu.org&safe=off&hl=en&filter=0)

[a specific example from the above google results if you don't want to click through](https://forums.dolphin-emu.org/Thread-linking-error-on-linux-mint)

As it currently stands, you have to compile against an external libpng ver 1.4 or later, so yes updating libpng would provide bugfixes.

**Comment by shuffle2** [comment]
PR is out of date and not maintained...if someone is interested to update libpng, just make a new one with current version.

**Pull request closed without merging**
