### PR TITLE
DolphinWX: move CPU Emulator Engine and NTSC-J to advanced tab

### PR DESCRIPTION
**Pull request by ligfx**
This has been pestering me. They're advanced settings, they should go under the advanced tab with the rest of them!

screen shot 2017-04-11 at 12 05 17 am screen shot 2017-04-11 at 12 09 33 am

### CODE REVIEW

**Comment by MayImilae** [comment]
I'm ok with this in concept, I mean, it's definitely needed, but it has some problems...

First is that the general tab is utterly empty. That's... not really good design. Considering all of the empty space, some things should be moved into it, like maybe the contents of the interface tab?

Second, this makes the config window size _even larger_! The size of the window (taking retina out of the equation) in this PR is 695 pixels high. That's _enormous_! And 20 pixels larger than the already large size of the window previously. Remember that lots of our users still have 1366x768 screens, and we're really pushing the limits of what's acceptable for them. So, the design of the items in the advanced tab definitely will need some adjustments to make them more compact. Less text, fewer paragraphs, different layout for the cpu emulator settings, etc.

**Comment by JosJuice** [comment]
That the CPU engine is something that you wouldn't want to change often doesn't mean that it's advanced. As for the NTSC-J override, it would probably be better to just remove it. And like May says, just cramming more things into the Advanced tab won't make for a good layout.

**Comment by JMC47** [comment]
We need more stuff for general if we do this.

I'm not entirely against it; but, I think that even for general users, being able to try cached interpreter/interpreter for "fixing" issues is common enough that I don't want to move it.

**Comment by ds84182** [comment]
The CPU engine settings could be made into a drop down instead of radio
buttons

**Comment by Helios747** [comment]
Against this.

Having large blank space in a landing page of UI isn't cool.

Options that users don't change much doesn't make it advanced, agreed with JosJuice. Besides, we have users test interpreter all the time.

>being able to try cached interpreter/interpreter for "fixing" issues is common enough that I don't want to move it.

^ Yep.

I have no opinion on moving NTSC-J

**Comment by myownfriend** [comment]
Whether or not CPU Emulation Engine settings gets moved or not, it doesn't look like there's any reason to have a separate tab for Interface settings.

By turning the CPU Emulation Engine settings into a dropdown instead of radio buttons, we can fit the Interface settings comfortably into the General Tab. 

http://imgur.com/BEA9oSH

And if we do move the CPU Emulation Engine dropdown into Advanced, we can just place it in CPU Options with Enable CPU Clock Override.

http://imgur.com/PGtR0Qj

And even though it's unrelated to the topic of this PR, the Audio settings can be cleaned up, too.

http://imgur.com/W5W9Dhp

**Comment by ligfx** [comment]
My thinking was that, even though changing the CPU Emulation Engine isn't difficult to understand and can be used for testing/repro-ing issues, it's not an option that has a large role in the main use-case of Dolphin: playing games.

Given that, I do agree that it doesn't really fit with the other options in Advanced right now. CPU Clock Override and Custom RTC are potentially part of playing games.

Closing for now, though @myownfriend I am a fan of the dropdowns!

**Pull request closed without merging**
