### PR TITLE
Update Windows ffmpeg to 3.2.4

### PR DESCRIPTION
**Pull request by RisingFog**
This updates the static libraries, along with the included header files to match the latest stable release of ffmpeg.

This also fixes an issue where with MPEG4 encoding, the bit-rate was not being taken into account.

### CODE REVIEW

**Comment by RisingFog** [comment]
@dolphin-emu-bot rebuild

**Comment by ligfx** [comment]
@dolphin-emu-bot rebuild

**Comment by RisingFog** [comment]
I'm still considering adding some additional formats and codecs, but that is contingent on #4944 being merged. Could either do that as a separate PR, or update this PR once that is done.

**Comment by RisingFog** [comment]
Closing this PR to attempt to fix buildbot issues

**Pull request closed without merging**
