### PR TITLE
ControllerInterface: Add synchronisation

### PR DESCRIPTION
**Pull request by leoetlino**
Needed for future hotplug support, as we'll need to access/add devices from different threads.

This was previously added in #3890 but doing it separately as it needed changes to other input backends (apart from evdev).

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3892)

### CODE REVIEW

**Comment by phire** [comment]
This looks good to me.

<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> #### ControllerInterface: Add synchronisation
> 
> Needed for future hotplug support, as we'll need to access/add devices from different threads.
> 
> 
> 
> This was previously added in #3890 but doing it separately as it needed changes to other input backends (apart from evdev).
> 
> 
> 
</details>


---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3892#-:-KK4dwIyZg7Wpf1ndKA2:652854571)*

**Comment by BhaaLseN** [comment]
:lgtm:

And btw, we already talked about a follow-up PR to switch it over to `unique_ptr` on IRC, which should make things a little neater.

<details><summary><i>Previously, phire (Scott Mansell) wrote…</i></summary>
> This looks good to me.
</details>


---

Reviewed 25 of 25 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3892#-:-KK4ea1j7yNBDfax96z-:526074128)*

**Comment by leoetlino** [comment]
On a closer look, it looks like DeviceContainer (which ControllerInterface inherits from) also uses m_devices for FindDevice() and FindInput(), so would it need locks as well?

**Comment by leoetlino** [comment]
Those do not seem very important, since they don't modify m_devices, so fixed those in the follow-up PR instead.

**Comment by Parlane** [comment]
Reviewed 24 of 25 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/InputCommon/ControllerInterface/Android/Android.cpp, line 15 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3892#-KL6MHBJKoNdGrOPn7j5:-KL6MHBJKoNdGrOPn7j6:-367007919) ([raw file](https://github.com/dolphin-emu/dolphin/blob/2fd272f79454301bb22a4d321caa1ad686127a6a/Source/Core/InputCommon/ControllerInterface/Android/Android.cpp#L15)):*
> ```cpp
> void Init()
> {
>   g_controller_interface.AddDevice(new Touchscreen(0));
> ```

Can we just chuck a for loop on this <_<

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3892)*

**Comment by leoetlino** [comment]
Review status: 24 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Core/InputCommon/ControllerInterface/Android/Android.cpp, line 15 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3892#-KL6MHBJKoNdGrOPn7j5:-KL6NgamRs0owPE_RDi9:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/2fd272f79454301bb22a4d321caa1ad686127a6a/Source/Core/InputCommon/ControllerInterface/Android/Android.cpp#L15)):*
<details><summary><i>Previously, Parlane (Matthew Parlane) wrote…</i></summary>
> Can we just chuck a for loop on this <_<
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3892)*

**Comment by Parlane** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3892)*

**Pull request merged**
