### PR TITLE
Implement IR passthrough for emulated Wiimotes

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
This allows the sensor bar to function mostly`*` correctly for emulated Wiimotes, allowing eg. Wiimotes to be used in Netplay while using an actual sensor bar without having to rely on Gyroscope-based pointer emulation.

`*` The IR Object size from an actual Wiimote is always reported as 2/15 because we only use Basic IR reports in our Wiimote-as-input-source code, since reports that include the size don't report Extension data. This could be improved by eg. using that mode when no Extension is connected, but I suspect very few if any games actually care about this data. Manually setting the IR object size as an expression works. If you set the report mode to Extended ([apply this diff](https://gist.github.com/AdmiralCurtiss/a1fa344a9299232a3f566dc6e9c9317a)) then the size is also reported correctly.

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
Testing notes: To enable this, reset an emulated Wiimote to defaults or load the stock Wiimote profile, then enable this checkbox:

grafik

**Comment by jordan-woyak** [comment]
FYI, I have a local "IR Passthrough" implementation that exposes mappings for just the center of all dots along with the rotation and distance. These pair up with existing wii remote `Input`s. The IR data is then recreated from those (IR dot center, distance, and rotation) within the existing emulated wii remote code. As long as the same math is used on each end (controller interface and emulated wii remote) roughly the same IR data is achieved in the end. Your solution is definitely more of a true "passthrough", but it does add a lot of mappings to the dialog that probably never really need to be user-configuration.

**Comment by AdmiralCurtiss** [comment]
I don't particularly care about the exact method, I just went for what seemed straightforward. If you want to PR your method as well or instead that's fine with me, I just know that someone asks about this every once in a while so I implemented it.

**Comment by jordan-woyak** [comment]
I got around to "finishing" my "fake" passthrough and I think it's too awkward. I think your solution here is cleaner. My only suggestion is that the "Visible" mappings be removed to reduce the UI clutter. "Invisible" objects can be identified with a size of zero. Real wii remotes do not produce a size of zero for visible objects so we shouldn't need both "Size" and "Visible".

**Comment by jordan-woyak** [comment]
Also, we should probably have a separate stock ini file for passthrough pointing, but that could be for another PR.

**Comment by jordan-woyak** [comment]
Should numbering be 0-3 or 1-4 ? It looks like there are some other PRs changing things to 1-based numbering.

**Comment by AdmiralCurtiss** [comment]
(no changes yet, just rebasing)

**Comment by AdmiralCurtiss** [comment]
> Should numbering be 0-3 or 1-4 ? It looks like there are some other PRs changing things to 1-based numbering.

You mean #12563? I'm not sure if we want to break configs but considering we're already inconsistent anyway, I suppose there's no harm in making all new things 1-4.

**Comment by AdmiralCurtiss** [comment]
I removed the Visible field and changed the numbering to 1-4.

**Review by jordan-woyak — APPROVED** [review]
Code looks good. Tested and working.

**Comment by AdmiralCurtiss** [comment]
Well, don't mind if I do then...

**Pull request merged**
