### PR TITLE
readme: Add '--recursive' to git submodule command

### PR DESCRIPTION
**Pull request by bemug**
Not doing so results in the following error :

CMake Error at Externals/cubeb/CMakeLists.txt:30 (message):
  Could not find sanitizers-cmake: run

  	git submodule update --init --recursive

  in base git checkout

As the advice is correct, update readme with the correct command.

### CODE REVIEW

**Comment by Florin9doi** [comment]
You may add a `-j $(nproc)` as well, where supported

**Comment by bemug** [comment]
# #
/

**Comment by bemug** [comment]
My fat fingers clicked the close button without my brain wanting to. I apologize for the noise.

@Florin9doi `-j$(nproc)` is already mentionned [further on the readme file](https://github.com/dolphin-emu/dolphin/blob/423c7c58cd8fe78eb89a3ab434cfbc958a4eef07/Readme.md?plain=1#L99).

**Comment by Florin9doi** [comment]
> @Florin9doi `-j$(nproc)` is already mentionned [further on the readme file](https://github.com/dolphin-emu/dolphin/blob/423c7c58cd8fe78eb89a3ab434cfbc958a4eef07/Readme.md?plain=1#L99).

Here it is used to compile using multiple jobs, but the `submodule update` process may also be speed up by running multiple jobs.

**Comment by bemug** [comment]
I was not aware that git submodule can take this argument, thanks.

The process was quite fast on my machine. Also as this is a readme I'd rather keep it simple. Thoughts ?

**Comment by AdmiralCurtiss** [comment]
Yeah, I think this is fine as-is, I don't know how much speedup you can even get by parallelizing submodule checkout.

**Comment by v1993** [comment]
FWIW, I get quite a bit of speedup with `-j4` option, but it probably should not be tied to thread count - the bottleneck of resulting processes is network and disk I/O and you probably don't want to open tons of actively used connections to github at once even if your CPU has a lot of (think 64+) threads.

**Pull request merged**
