### PR TITLE
Treat invalid aspect ratio setting values as Auto

### PR DESCRIPTION
**Pull request by JosJuice**

### CODE REVIEW

**Comment by degasus** [comment]
I wonder, as aspect_mode is an enum class, is the compiler allowed to optimize out the default case as all allowed values are handled?

**Comment by leoetlino** [comment]
Looks like the default case should be hit for invalid values, according to this [answer](https://stackoverflow.com/questions/18195312/what-happens-if-you-static-cast-invalid-value-to-enum-class)

**Comment by degasus** [comment]
Hm, I interpret the answer in the opposite way. And they link to: http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1766

**Comment by JosJuice** [comment]
The question is what the standard means by "the range of the enumeration values". The StackOverflow answer quotes:

> For an enumeration whose underlying type is fixed, the values of the enumeration are the values of the underlying type.

The text in the standard for what happens when there is no fixed underlying type is more complicated, but it basically seems to boil down to: The compiler might choose to represent the values of the enum using anything as small as 2 bits (since it only has four values in our case) up to the size of an `int`. So if the compiler chooses to represent the enum using for example 8 bits, we can get UB.

I've added a commit to explicitly give the enum the fixed underlying type `int`. That's the same type as the non-enum setting uses, so conversions will work fine even for unintended values.

**Pull request merged**
