### PR TITLE
IOS HLE: Refactor ExecuteCommand

### PR DESCRIPTION
**Pull request by leoetlino**
ExecuteCommand was becoming pretty confusing with unused variables for some commands, confusing names (device ID != IOS file descriptor), duplicated checks, not keeping the indentation level low, and having tons of things into a single function.

This commit gives more correct names to variables, deduplicates the device checking code, and splits some parts of ExecuteCommand out so that it's easier to read.

It's worth noting that some device checks have been forgotten in the past, which has caused a bug (which was recently fixed in 288e75f6).

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4607)

### CODE REVIEW

**Comment by Helios747** [comment]
LGTM

**Comment by Parlane** [comment]
@JMC47 can you test this against games that use/abuse a bit of IOS. USB/ES etc. Like pokemon for example. Or skylanders.

**Comment by leoetlino** [comment]
@Parlane I forgot to say, but this is actually split from #4408, which has been heavily tested by JMC47. There's no regression as far as we can see.

#4408 has already been including this commit for a month and that PR was tested in a lot of titles, including the Internet Channel and Skylanders.

>Tested:
ES_Launch
Four Wii Remotes
Balance Board
Emulated Bluetooth
Real Bluetooth
Launching Games
HBC
System Menu (no regressions)
USB HID

**Comment by JMC47** [comment]
I tested Skylanders on this cleanup.  When we were testing we did run into some issues a while back but it's long been fixed and works perfectly.

LGTM.

**Pull request merged**
