### PR TITLE
Combine InitMMIO and InitMMIOWii

### PR DESCRIPTION
**Pull request by Minty-Meeo**
This is an extract of a change I made in the cancelled PR #8778.

### CODE REVIEW

**Review by iwubcode — APPROVED** [review]
Untested.  Seems reasonable.

**Comment by Pokechu22** [comment]
Refactoring-wise, this seems reasonable.  It seems a bit strange that DVDInterface, SerialInterface, ExpansionInterface, and AudioInterface are all registered at `0x0C006X00` and `0x0D006X00` at the same time on the Wii, though.

**Comment by Minty-Meeo** [comment]
I was doing some hardware tests for a different PR, and DVDInterface does exist at both locations while in Wii mode.

**Comment by Pokechu22** [comment]
Are you able to access DVDInterface normally in Wii mode (without ahbprot, which is given automatically with `wiiload`?)  I would expect that Nintendo would only allow going through /dev/di, but maybe they don't restrict it.

If I recall correctly, IOS uses `0x0D806000` instead of `0x0D006000`, but [those are the same](https://github.com/dolphin-emu/dolphin/blob/ffdc8538a162b1ca56e3943c5a78c02358053b2a/Source/Core/Core/HW/MMIO.h#L51-L55) (or there's something where the powerpc core can only use one of them, but IOS can use both?)

**Review by AdmiralCurtiss — APPROVED** [review]
Regardless of questions about functionality, this PR doesn't change behavior and is a better design, so sure, why not.

**Pull request merged**
