### PR TITLE
Externals: Update fmt to 10.0.0 commit ef55d4f

### PR DESCRIPTION
**Pull request by Minty-Meeo**
This specific commit contains a fix for GCC warnings.  Prior downstream edits to {fmt} are no longer necessary, allowing {fmt} to be included as a submodule.

https://github.com/dolphin-emu/dolphin/commit/7b8e6c5b3643bb3ec09de3be5598d5e35caa3986 was fixed by https://github.com/fmtlib/fmt/commit/cfb34a06076d7d375f9f99daff60b5af05ba5c28
https://github.com/dolphin-emu/dolphin/commit/d033d92b0524c23e1274f07c9cbaa02ead770bbc was fixed by https://github.com/fmtlib/fmt/commit/3e28dc021cf38b14ac0e2b1a046f783e094bfffc
https://github.com/dolphin-emu/dolphin/pull/10652/commits/357dc72f97d812bf5d393d5f7216af8aa2d2c95a I could not reproduce...

### CODE REVIEW

**Comment by Minty-Meeo** [comment]
@dolphin-emu-bot rebuild

**Comment by AdmiralCurtiss** [comment]
I don't think it's a good idea to get rid of the shared fmt option. If those fix commits are really required, then I'd recommend waiting for the next official fmt release.

**Comment by AdmiralCurtiss** [comment]
Ah, okay, gotcha.

**Comment by Minty-Meeo** [comment]
@dolphin-emu-bot rebuild

**Comment by EpochFlame** [comment]
dolphin will not compile on the latest fmt and requires fmt9- merging this PR would have resolved the issue

**Comment by JosJuice** [comment]
Replacing with PR #12190.

**Pull request closed without merging**
