### PR TITLE
Android: Add disc image conversion

### PR DESCRIPTION
**Pull request by JosJuice**
Screenshot_20200627-125148

### CODE REVIEW

**Comment by JosJuice** [comment]
After coding this, I came to the conclusion that I don't like Android.

**Comment by JosJuice** [comment]
JMC wanted to see how the progress dialog is supposed to look.

Screenshot_20200912-124959694

**Comment by JMC47** [comment]
@Ebola16 Can you give this a quick look before I yolo merge it :)

**Comment by JMC47** [comment]
I've tested this thoroughly and it appears that no one wants to look into the java code.  Space is at a premium on phones and having this feature would be fantastic.  It's been sitting here for 3 months now.

**Comment by 7aychu23** [comment]
Can i Request Android can play DTM TAS REPLAY like PC :) Or Add Cheat Generator = Memory Viewer Like Citra

**Comment by Sanfe** [comment]
I tested this feature in last beta and have a bug. In RVZ format, the compression level only could be up to 9. If you put 10 or more crash. Also, a progress bar in notification bar is needed to could make the process in background. Batch multiple compression could be a good plus.

**Comment by JMC47** [comment]
The crash will be fixed tomorrow.

**Comment by JosJuice** [comment]
I only meant I would create the PR tomorrow, not that it will be merged tomorrow :P

But yeah, it should be a simple fix.

**Comment by faroukabd000** [comment]
How about the method that have been used in nkit it's fast and the size really small

**Comment by JosJuice** [comment]
It also breaks games in certain ways, while not really being faster or smaller than RVZ.

**Comment by faroukabd000** [comment]
The converting process doesn't appear in mi a3

**Pull request merged**
