### PR TITLE
Rename "Keyboard" to "Keyboard Controller"

### PR DESCRIPTION
**Pull request by jordan-woyak**
Some confused users choose "Keyboard" instead of "Standard Controller" when then intend to play with a keyboard.

This renames "Keyboard" to "Keyboard Controller" and adds some warning text to the mapping dialog.
image

### CODE REVIEW

**Comment by JosJuice** [comment]
I was considering renaming it in this way at one point, but then someone pointed out to me that this keyboard actually has two SKUs, one released by ASCII and one released by Sammy. That made me kind of indecisive. What do you think?

**Comment by jordan-woyak** [comment]
> I was considering renaming it in this way at one point, but then someone pointed out to me that this keyboard actually has two SKUs, one released by ASCII and one released by Sammy. That made me kind of indecisive. What do you think?

Ah, I wasn't aware of the Sammy version. I guess I can just remove "ASCII " and hopefully "Keyboard Controller" plus the warning will help?

**Comment by JosJuice** [comment]
Sure. The warning especially seems like a good idea. Maybe add the yellow warning icon that we're currently showing if you try to add a cheat without having turned on "Enable Cheats"?

**Comment by Rumi-Larry** [comment]
A checkmark to "never show this warning again" would be useful if you are a frequent Phantasy Star player

**Comment by jordan-woyak** [comment]
> A checkmark to "never show this warning again" would be useful if you are a frequent Phantasy Star player

I disagree. It's just text on the dialog. I think it should always be visible to deter the confused users.
Actual PSO players won't be bothered by it.

**Review by AdmiralCurtiss — APPROVED** [review]
Sounds good to me.

**Comment by Rumi-Larry** [comment]
The title of this PR should include "... and added warning"

**Comment by MayImilae** [comment]
Definitely a good idea. However, I'd suggest changing the warning slightly to: 

_You are configuring a keyboard controller, a unique controller exclusively supported by Phantasy Star Online. If you just want to use your keyboard to play games, turn back and configure a "Standard Controller"._

Btw I changed "Phantasy Star Online Episode I & II" to just "Phantasy Star Online" because there is an [Ep3](https://wiki.dolphin-emu.org/index.php?title=Phantasy_Star_Online_Episode_III:_C.A.R.D._Revolution) and it also supports the keyboard controller. Specifying the versions just gets weird.

**Comment by MayImilae** [comment]
Minimizing You language a bit gives this.

__This is the configuration page for the "Keyboard Controller", a unique controller exclusively supported by Phantasy Star Online. If you just want to use your keyboard to play games, turn back and configure a "Standard Controller".__

I'm not sure if it is better, and I can't totally eliminate yous in this. But it is good to avoid yous as much as we can.

**Comment by stblr** [comment]
> This device is exclusively for PSO.

Homebrew software can also make use of it (at least we do so in mkw-sp).

**Comment by MayImilae** [comment]
> Homebrew software can also make use of it (at least we do so in mkw-sp).

For brevity, it's best not to mention that. If you are bothered by this we could drop the word exclusively, but by adding that word helps people get the message "am I playing PSO? No? Then this is the wrong thing." I'd like to keep it.

**Comment by jordan-woyak** [comment]
Considering homebrew is why I originally said "exclusively for" PSO rather than "exclusively supported by" PSO, which is maybe more correct since the controller was really only designed for PSO, but other things can use it. I don't think we need to explicitly mention homebrew. Anyone who understands what this device is will not be confused. The warning just needs to scare users away that have no use for a "Keyboard Controller".

**Comment by MayImilae** [comment]
"Exclusively for" is perfectly fine.

**Comment by Dentomologist** [comment]
I made this mistake when I first started using Dolphin, but I think I would have interpreted "Keyboard Controller" as "Use your keyboard as the controller" which would have led me to make the same mistake. If the pulldown menu option were "Phantasy Star Online Keyboard" or something the intent would be more explicit.

The configuration warning is a partial fix, but still requires the user to select and try to configure the wrong option which isn't ideal.

The other half of the problem is more subjective and outside the scope of this PR but I think it's worth mentioning. When I saw Standard Controller my assumption was that referred to a physical GameCube controller plugged in via adapter, and likewise for the other options. The Wii U option does explicitly mention an adapter, but I figured that was a special adapter supporting Wii U peripherals instead of a more standard one.

I don't know what the best way to address that would be, but if the menu had been divided into "Physical Controller" and "Emulated Controller" sections I think that would have been much clearer to me, and probably other people making this mistake.

**Review by lioncash — APPROVED** [review]

**Pull request merged**
