### PR TITLE
Do not try to load strided efb copies or ones with wrong dimensions

### PR DESCRIPTION
**Pull request by mimimi085181**
And also keep those efb copies, so they can be used by a future Load() or by partial texture updates.

This fixes some issues in: Sonic Riders: Zero Gravity, Mario Kart Wii and Sonic the Fighters (inside Sonic Gems Collection).

### CODE REVIEW

**Comment by degasus** [comment]
LGTM

**Comment by DonelBueno** [comment]
What issue does this fix in Mario Kart Wii? Would it be the lens flare effect with "EFB Copies to Texture Only"?

**Comment by mimimi085181** [comment]
Sorry no, it's should be this issue: https://bugs.dolphin-emu.org/issues/9027
Everything being darker and strange dark textures in Mario Kart should be fixed. But i'm not sure about drift and trick textures, i don't even know how that is supposed to look.

**Comment by wtonberrios** [comment]
Español

Hola, desde esta compilacion detecte un error en Donkey Kong Country Returns, el personaje de donkey kong desaparece y aparece a cada rato, al descartivar "Copia de EFB a escala" vuelve a funcionar sin problemas, pero con menor calidad en las texturas del donkey kong, la compilacion dolphin-master-4.0-8008 funciona bien en comparacion con esta version dolphin-master-4.0-8010.

PD: se mantiene este error hasta la compilacion dolphin-master-4.0-8054.

Solo informaba, saludos
Wton.

English (Google traslator) (si no se entiende bien, alguna persona podría traducirla por favor, muchas gracias)

Hello, since this compilation detects an error in Donkey Kong Country Returns, Donkey Kong character disappears and all the time is displayed, descartivar "Copying EFB scale" run smoothly again, but with lower quality textures donkey kong, compilation dolphin-master-4.0-8008 works well with this version compared dolphin-master-4.0-8010.

PD: This error is held until compilation dolphin-master-4.0-8054.

Only reported, Greetings
Wton.

http://www.servimg.com/view/11866238/1205
sf8e01-1v3

**Comment by 7oxicshadow** [comment]
Just to confirm, I also see the same issue as wtonberrios on Linux.
This commit breaks DKCR. Character and enemy models either flicker or just dont show at all.

Fedora 22
Nvidia proprietary (355.11)
GTX 770
i7 @ 3.6Ghz
6 GB ram

**Pull request merged**
