### PR TITLE
Fix broken game INIs (comments starting in the middle of lines)

### PR DESCRIPTION
**Pull request by JosJuice**
290204e added comments that start in the middle of lines, which isn't allowed. I moved all such comments to EmulationIssues.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3827)

### CODE REVIEW

**Comment by JMC47** [comment]
Someone should review this: I don't want more issues like this cropping up that are near impossible to track down.

**Comment by JMC47** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Data/Sys/GameSettings/RMC.ini, line 9 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3827#-KHVDqBanqE2qAHm_nCI:-KHVDqBbcI01_Y7TfAkg:1033548677) ([raw file](https://github.com/dolphin-emu/dolphin/blob/02e811af50df3ca4cad621e6744eb8fd7cb00701/Data/Sys/GameSettings/RMC.ini#L9)):*
> ```INI
> # The Emulation State. 1 is worst, 5 is best, 0 is not set.
> EmulationStateId = 4
> EmulationIssues = There may be too much bloom when using anti-aliasing
> ```

If something is a "may" I wouldn't even put it in the ini.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3827)*

**Comment by JosJuice** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Data/Sys/GameSettings/RMC.ini, line 9 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3827#-KHVDqBanqE2qAHm_nCI:-KHVE8uiSBJXtcSjhOv6:203585777) ([raw file](https://github.com/dolphin-emu/dolphin/blob/02e811af50df3ca4cad621e6744eb8fd7cb00701/Data/Sys/GameSettings/RMC.ini#L9)):*
<details><summary><i>Previously, JMC47 wrote…</i></summary>
> If something is a "may" I wouldn't even put it in the ini.  </details>
I wrote it like that because I know nearly nothing, but I assume (and hope...) that the person who added the comment was sure about it. I'll change the wording of this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3827)*

**Comment by JosJuice** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[Data/Sys/GameSettings/RMC.ini, line 9 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3827#-KHVDqBanqE2qAHm_nCI:-KHVIQ95LJfIfKYj4iGj:-499146009) ([raw file](https://github.com/dolphin-emu/dolphin/blob/02e811af50df3ca4cad621e6744eb8fd7cb00701/Data/Sys/GameSettings/RMC.ini#L9)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary>
> I wrote it like that because I know nearly nothing, but I assume (and hope...) that the person who added the comment was sure about it. I'll change the wording of this.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3827)*

**Comment by JMC47** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/3827)*

**Comment by JMC47** [comment]
I'm happier with the language now.  LGTM.

**Pull request merged**
