### PR TITLE
DVDThread queue

### PR DESCRIPTION
**Pull request by JosJuice**
This PR adds a queue to DVDThread, for two reasons:

* It lets DTK read from the disc using the DVD thread instead of the CPU thread. ~~I intended that to be in this PR, but it's not done yet, hence the WIP.~~ It's now implemented in this PR.
* It will let PR #3701 have simpler code and better performance.

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4120)

### CODE REVIEW

**Comment by JosJuice** [comment]
Okay, so `DoState` currently isn't working because `ReadResult` doesn't work with `Do`. Would an acceptable workaround be to use `std::pair<ReadResult, std::vector<u8>>` instead, where `ReadResult` contains everything that `ReadResult` currently contains other than the `std::vector<u8> buffer`? I assume it would work, since `Do` supports both `std::pair` and `std::vector`, and the `std::vector` is the only part of `ReadResult` that isn't trivially copyable as far as I know. It's ugly, though.

**Comment by JosJuice** [comment]
By removing things from `ReadResult`, it became possible to replace it with `typedef std::pair<ReadRequest, std::vector<u8>> ReadResult;`. That solution isn't much uglier than `ReadResult` was originally in my opinion, so I've implemented it.

**Comment by lioncash** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[Source/Core/Core/HW/DVDInterface.h, line 98 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP4JzRRVwZWyub6GCN8:-KP4JzRRVwZWyub6GCN9:b7dfoaq) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7407be0c36e37985115a8e461c86300a2cc658e0/Source/Core/Core/HW/DVDInterface.h#L98)):*
> ```objc
> enum class ReplyType : u32
> {
>   INTERRUPT,
> ```

The general convention with strongly typed enums is to just treat them as regular names/initialisms, where applicable (e.g. Interrupt, IOS_HLE, DTK); since they're essentially namespaced now, there's no longer a need to upper-case everything.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 57 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP4L62_rwBJEH5x2mZ-:-KP4L62ae1JycF0LzeCx:b-mqbqro) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7407be0c36e37985115a8e461c86300a2cc658e0/Source/Core/Core/HW/DVDThread.cpp#L57)):*
> ```cpp
> };
> 
> typedef std::pair<ReadRequest, std::vector<u8>> ReadResult;
> ```

```cpp
using ReadResult = std::pair<ReadRequest, std::vector<u8>>;
```

---

*[Source/Core/Core/HW/DVDThread.cpp, line 120 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP4LPXIatppTuDnUN-5:-KP4LPXJZwMJe1XMYUt2:b-c2s2se) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7407be0c36e37985115a8e461c86300a2cc658e0/Source/Core/Core/HW/DVDThread.cpp#L120)):*
> ```cpp
>   {
>     u64 id = result.first.id;
>     s_result_map.insert(std::make_pair(id, std::move(result)));
> ```

```cpp
s_result_map.emplace(id, std::move(result));
```

---

*[Source/Core/Core/HW/DVDThread.cpp, line 205 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP4Kjd51ZZtrymY17UT:-KP4Kjd6X4DzuGvj4-p5:b-c2s2se) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7407be0c36e37985115a8e461c86300a2cc658e0/Source/Core/Core/HW/DVDThread.cpp#L205)):*
> ```cpp
>         break;
>       else
>         s_result_map.insert(std::make_pair(id, std::move(result)));
> ```

```cpp
s_result_map.emplace(id, std::move(result));
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120)*

**Comment by JosJuice** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[Source/Core/Core/HW/DVDInterface.h, line 98 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP4JzRRVwZWyub6GCN8:-KP4Pn7gx6VmOpSXTOTk:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7407be0c36e37985115a8e461c86300a2cc658e0/Source/Core/Core/HW/DVDInterface.h#L98)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> The general convention with strongly typed enums is to just treat them as regular names/initialisms, where applicable (e.g. Interrupt, IOS_HLE, DTK); since they're essentially namespaced now, there's no longer a need to upper-case everything.
</details>
Done.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 57 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP4L62_rwBJEH5x2mZ-:-KP4QCFlxBj-hP0FjKfs:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7407be0c36e37985115a8e461c86300a2cc658e0/Source/Core/Core/HW/DVDThread.cpp#L57)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> ```cpp
> using ReadResult = std::pair<ReadRequest, std::vector<u8>>;
> ```
</details>
Done.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 120 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP4LPXIatppTuDnUN-5:-KP4QD38x2Uog4MGh1AM:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7407be0c36e37985115a8e461c86300a2cc658e0/Source/Core/Core/HW/DVDThread.cpp#L120)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> ```cpp
> s_result_map.emplace(id, std::move(result));
> ```
</details>
Done.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 205 \[r1\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP4Kjd51ZZtrymY17UT:-KP4QDhc0ghuZY0yJMX-:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/7407be0c36e37985115a8e461c86300a2cc658e0/Source/Core/Core/HW/DVDThread.cpp#L205)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> ```cpp
> s_result_map.emplace(id, std::move(result));
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120)*

**Comment by JosJuice** [comment]
Reading DTK data on the DVD thread is now implemented.

@JMC47, please test that DTK and savestates are working properly. The only intended behavior change for DTK is 3.5 ms extra latency, so all games should work the same as before.

**Comment by lioncash** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[Source/Core/Core/HW/DVDInterface.cpp, line 307 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP8oPkyaY3Clem6M3mt:-KP8oPkyaY3Clem6M3mu:b-5ny56s) ([raw file](https://github.com/dolphin-emu/dolphin/blob/576ee284ab068df1e4c76310404cd3b8ed310e10/Source/Core/Core/HW/DVDInterface.cpp#L307)):*
> ```cpp
> static u32 ProcessDTKSamples(std::vector<s16>* temp_pcm, const std::vector<u8>& audio_data)
> {
>   u32 samples_processed = 0;
> ```

These should be `size_t`

---

*[Source/Core/Core/HW/DVDInterface.cpp, line 315 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP8oGvDuhka4wPXuDVI:-KP8oGvEkfLZeWwQY87N:b7flzq2) ([raw file](https://github.com/dolphin-emu/dolphin/blob/576ee284ab068df1e4c76310404cd3b8ed310e10/Source/Core/Core/HW/DVDInterface.cpp#L315)):*
> ```cpp
>     bytes_processed += StreamADPCM::ONE_BLOCK_SIZE;
>   }
>   for (unsigned i = 0; i < samples_processed * 2; ++i)
> ```

This should likely be a `size_t`

---

*[Source/Core/Core/HW/DVDThread.cpp, line 105 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP8nfFiwZuwmH_6frsL:-KP8nfFiwZuwmH_6frsM:bdbcego) ([raw file](https://github.com/dolphin-emu/dolphin/blob/576ee284ab068df1e4c76310404cd3b8ed310e10/Source/Core/Core/HW/DVDThread.cpp#L105)):*
> ```cpp
>   s_result_queue.Clear();
> 
>   // This isn't actually necessary, but it feels a bit cleaner to me
> ```

You should probably not include subjective descriptions in comments or phrase this a little better (i.e. anyone that comes along is going to wonder who `me` is)

---

*[Source/Core/Core/HW/DVDThread.cpp, line 118 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP8nN0tuFfe3rtwF8gx:-KP8nN0tuFfe3rtwF8gy:b-qhc3y9) ([raw file](https://github.com/dolphin-emu/dolphin/blob/576ee284ab068df1e4c76310404cd3b8ed310e10/Source/Core/Core/HW/DVDThread.cpp#L118)):*
> ```cpp
> 
>   // Move everything from s_result_queue to s_result_map because
>   // PointerWrap::Do supports std::map but not Common::FifoQueue.
> ```

Is there any particular reason you can't just add support for FifoQueue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120)*

**Comment by JosJuice** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[Source/Core/Core/HW/DVDInterface.cpp, line 307 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP8oPkyaY3Clem6M3mt:-KP8tQCVbOQexwyI3gM7:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/576ee284ab068df1e4c76310404cd3b8ed310e10/Source/Core/Core/HW/DVDInterface.cpp#L307)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> These should be `size_t`
</details>
Done.

---

*[Source/Core/Core/HW/DVDInterface.cpp, line 315 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP8oGvDuhka4wPXuDVI:-KP8tRoAnoUYr8gPlZ1T:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/576ee284ab068df1e4c76310404cd3b8ed310e10/Source/Core/Core/HW/DVDInterface.cpp#L315)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> This should likely be a `size_t`
</details>
Done.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 105 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP8nfFiwZuwmH_6frsL:-KP8tT4zj9YAjR_UiUVw:bhox8ih) ([raw file](https://github.com/dolphin-emu/dolphin/blob/576ee284ab068df1e4c76310404cd3b8ed310e10/Source/Core/Core/HW/DVDThread.cpp#L105)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> You should probably not include subjective descriptions in comments or phrase this a little better (i.e. anyone that comes along is going to wonder who `me` is)
</details>
I have rewritten this comment.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 118 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP8nN0tuFfe3rtwF8gx:-KP8tZPrWJuhiJiQf--p:b-170xiz) ([raw file](https://github.com/dolphin-emu/dolphin/blob/576ee284ab068df1e4c76310404cd3b8ed310e10/Source/Core/Core/HW/DVDThread.cpp#L118)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> Is there any particular reason you can't just add support for FifoQueue?
</details>
No, I can't think of any reason. I just thought the approach with moving everything to the map would be simpler, considering that FinishRead already has code for handling the map. Would you prefer the approach of calling Do on the FifoQueue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120)*

**Comment by JosJuice** [comment]
To anyone who knows about our audio code: To make up for this PR calling PushStreamingSamples 3.5 ms later than before, should I submit 3.5 ms of silent samples when emulation starts?

**Comment by JMC47** [comment]
DTK audio works a lot better with file monitor now.  Savestates still work.  Syncing still works.

**Comment by degasus** [comment]
No need to push silence, our mixer will do this for you.

About all of thise syncing stuff, what do you think about using https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Common/BlockingLoop.h ? But maybe you have to make the polling loop optional.

---

Reviewed 1 of 5 files at r1, 1 of 4 files at r2.
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 118 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP8nN0tuFfe3rtwF8gx:-KPmq_Bxm49ybUvMoNwF:bnyvzd4) ([raw file](https://github.com/dolphin-emu/dolphin/blob/576ee284ab068df1e4c76310404cd3b8ed310e10/Source/Core/Core/HW/DVDThread.cpp#L118)):*
<details><summary><i>Previously, JosJuice wrote…</i></summary>
> No, I can't think of any reason. I just thought the approach with moving everything to the map would be simpler, considering that FinishRead already has code for handling the map. Would you prefer the approach of calling Do on the FifoQueue?
</details>
You always need to synchronize the other thread, so just wait until it is ready is likely the best way to go. So I'm for the way how it is done now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-:-KPmpFleJSX7KR68mmQ4:bji6ayu)*

**Comment by JosJuice** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 118 \[r3\]](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KP8nN0tuFfe3rtwF8gx:-KPmvXELK-HuKGmQWTDB:b-2pc6b9) ([raw file](https://github.com/dolphin-emu/dolphin/blob/576ee284ab068df1e4c76310404cd3b8ed310e10/Source/Core/Core/HW/DVDThread.cpp#L118)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> You always need to synchronize the other thread, so just wait until it is ready is likely the best way to go. So I'm for the way how it is done now.
</details>
Both of the alternatives that we're talking about here would wait for the DVD thread in the same way. The difference is only whether we move things from the result queue to the map.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120)*

**Comment by degasus** [comment]
Reviewed 1 of 4 files at r2, 2 of 3 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[Source/Core/Core/HW/DVDInterface.cpp, line 333 at r6](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KU6rWGmLCNCSA--eKBs:-KU6rWGmLCNCSA--eKBt:b4godeu) ([raw file](https://github.com/dolphin-emu/dolphin/blob/28b1ac968b8c54e7c95488647517ead54f6e55af/Source/Core/Core/HW/DVDInterface.cpp#L333)):*
> ```cpp
>   {
>     // TODO: Fix the mixer so it can accept non-byte-swapped samples.
>     (*temp_pcm)[i] = Common::swap16((*temp_pcm)[i]);
> ```

please move this for loop into the while loop. So the memory will be used in order ;)

---

*[Source/Core/Core/HW/DVDThread.cpp, line 68 at r6](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KU6l7Ri4-2NLHAheZoW:-KU6l7RjZMVO5QGn_kAf:b-jg7u6t) ([raw file](https://github.com/dolphin-emu/dolphin/blob/28b1ac968b8c54e7c95488647517ead54f6e55af/Source/Core/Core/HW/DVDThread.cpp#L68)):*
> ```cpp
> static CoreTiming::EventType* s_finish_read;
> 
> static u32 s_next_id = 0;
> ```

As the id itself is u64, why is this variable only a u32?

---

*[Source/Core/Core/HW/DVDThread.cpp, line 100 at r6](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KU6pY1UbZcdXNQJ7uLS:-KU6pY1UbZcdXNQJ7uLT:bnsmwj6) ([raw file](https://github.com/dolphin-emu/dolphin/blob/28b1ac968b8c54e7c95488647517ead54f6e55af/Source/Core/Core/HW/DVDThread.cpp#L100)):*
> ```cpp
> 
>   s_dvd_thread_exiting.Clear();
>   s_request_queue_expanded.Reset();
> ```

Please clear at Start(), not at Stop().

There is also no need to reset Events. They might be triggered as often as they want to.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 193 at r6](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KU6mFOPWgKL_9RXa0YB:-KU6mFOPWgKL_9RXa0YC:b-cwce5y) ([raw file](https://github.com/dolphin-emu/dolphin/blob/28b1ac968b8c54e7c95488647517ead54f6e55af/Source/Core/Core/HW/DVDThread.cpp#L193)):*
> ```cpp
> }
> 
> static void FinishRead(u64 userdata, s64 cycles_late)
> ```

Please give "userdata" a better name, eg "id"

---

*[Source/Core/Core/HW/DVDThread.cpp, line 219 at r6](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KU6mXP9PXkhAc1PpIsa:-KU6mXP9PXkhAc1PpIsb:b-3xndh7) ([raw file](https://github.com/dolphin-emu/dolphin/blob/28b1ac968b8c54e7c95488647517ead54f6e55af/Source/Core/Core/HW/DVDThread.cpp#L219)):*
> ```cpp
>         s_result_queue_expanded.Wait();
> 
>       u64 id = result.first.id;
> ```

No need to create this local variable through.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 261 at r6](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KU6oXkkHhx97I5-h9AP:-KU6oXkkHhx97I5-h9AQ:bskriuq) ([raw file](https://github.com/dolphin-emu/dolphin/blob/28b1ac968b8c54e7c95488647517ead54f6e55af/Source/Core/Core/HW/DVDThread.cpp#L261)):*
> ```cpp
>   while (true)
>   {
>     s_dvd_thread_done_working.Set();
> ```

This might be a race condition. If the CPU pushes a new task while the DVD thread is closely to the start this loop. If the CPU wait for done directly afterwards, the DVD thread will set the done_working event, and starts running.
Is there a way without this Event at all? Maybe check if the last ID is executed. It's fine to use mutexes ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120)*

**Comment by JosJuice** [comment]
Review status: 3 of 5 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/HW/DVDInterface.cpp, line 333 at r6](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KU6rWGmLCNCSA--eKBs:-KU7SexFdDGNROVDutmD:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/28b1ac968b8c54e7c95488647517ead54f6e55af/Source/Core/Core/HW/DVDInterface.cpp#L333)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> please move this for loop into the while loop. So the memory will be used in order ;)
</details>
Done.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 68 at r6](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KU6l7Ri4-2NLHAheZoW:-KU7Sgs0_uIMvL_HwZeu:b-g5rzub) ([raw file](https://github.com/dolphin-emu/dolphin/blob/28b1ac968b8c54e7c95488647517ead54f6e55af/Source/Core/Core/HW/DVDThread.cpp#L68)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> As the id itself is u64, why is this variable only a u32?
</details>
I probably intended IDs to be u32 originally, but then I started using u64 because that's what CoreTiming event userdata is. I've changed this variable to u64 now.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 100 at r6](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KU6pY1UbZcdXNQJ7uLS:-KU7SvSdYtq72LEQkLGN:b1turi9) ([raw file](https://github.com/dolphin-emu/dolphin/blob/28b1ac968b8c54e7c95488647517ead54f6e55af/Source/Core/Core/HW/DVDThread.cpp#L100)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> Please clear at Start(), not at Stop().
> 
> There is also no need to reset Events. They might be triggered as often as they want to.
</details>
These are cleared at start now.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 193 at r6](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KU6mFOPWgKL_9RXa0YB:-KU7Sy02LzCwRPU7xTY3:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/28b1ac968b8c54e7c95488647517ead54f6e55af/Source/Core/Core/HW/DVDThread.cpp#L193)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> Please give "userdata" a better name, eg "id"
</details>
Done.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 219 at r6](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KU6mXP9PXkhAc1PpIsa:-KU7Syf_iMvDNmZKm6bE:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/28b1ac968b8c54e7c95488647517ead54f6e55af/Source/Core/Core/HW/DVDThread.cpp#L219)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> No need to create this local variable through.
</details>
Done.

---

*[Source/Core/Core/HW/DVDThread.cpp, line 261 at r6](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-KU6oXkkHhx97I5-h9AP:-KU7SzU-4mjBO-C6I3Kn:byrsho2) ([raw file](https://github.com/dolphin-emu/dolphin/blob/28b1ac968b8c54e7c95488647517ead54f6e55af/Source/Core/Core/HW/DVDThread.cpp#L261)):*
<details><summary><i>Previously, degasus (Markus Wick) wrote…</i></summary>
> This might be a race condition. If the CPU pushes a new task while the DVD thread is closely to the start this loop. If the CPU wait for done directly afterwards, the DVD thread will set the done_working event, and starts running.
> Is there a way without this Event at all? Maybe check if the last ID is executed. It's fine to use mutexes ;)
</details>
The event has been removed and the race condition should be fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120)*

**Comment by degasus** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4120#-:-KU7VBdFIAgCb6gerJYK:bnfp4nl)*

**Pull request merged**
