### PR TITLE
Core: Move SI source files to their own directory

### PR DESCRIPTION
**Pull request by lioncash**
Follow up to #4695

### CODE REVIEW

**Comment by iwubcode** [comment]
What are SI files?

**Comment by lioncash** [comment]
Files related to the [Serial Interface](http://wiibrew.org/wiki/Hardware/Serial_Interface)

**Comment by iwubcode** [comment]
Would it be possible to name the directory SerialInterface instead of SI?

**Comment by lioncash** [comment]
I'm following existing convention. e.g. EXI is shorthand for [External Interface](http://hitmen.c02.at/files/yagcd/yagcd/chap5.html#sec5.9) and that is already a directory.

**Pull request merged**
