### PR TITLE
Qt/GraphicsWindow: Decrease description box size

### PR DESCRIPTION
**Pull request by spycrab**
Before: Before
After: After

### CODE REVIEW

**Comment by spycrab** [comment]
@dolphin-emu-bot rebuild

**Comment by spycrab** [comment]
@dolphin-emu-bot rebuild

**Comment by spycrab** [comment]
@JMC47 @MayImilae

**Comment by MayImilae** [comment]
Looks fine on macOS!

descriptionsize

**Comment by spycrab** [comment]
> Looks fine on macOS!
Great! Also got confirmation by @JMC47 that it looks fine on HiDPI too!

**Pull request merged**
