### PR TITLE
Clean Orange theme

### PR DESCRIPTION
**Pull request by LekamDeveloper**
A modification of the Clean theme to the orange color.

### CODE REVIEW

**Comment by Dockolm** [comment]
Should look appropriate on Ubuntu.

**Comment by MayImilae** [comment]
I'm not really in favor of this. It doesn't match the rest of the themes Dolphin is providing. You can do whatever you want them with on your own for course, but asking for it to be merged into Dolphin...

**Comment by bb010g** [comment]
Could someone upload some screenshots?

**Comment by CesarAxe** [comment]
Screenshots on Windows 10
windows
windows2

**Pull request closed without merging**
