### PR TITLE
Update Installer to delete old Install directory

### PR DESCRIPTION
**Pull request by RisingFog**
Fixes issue 9389: https://bugs.dolphin-emu.org/issues/9389

[Review on Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/3715)

### CODE REVIEW

**Comment by mbc07** [comment]
Wouldn't be better to wipe the entire $INSTDIR folder instead of just Sys folder? Dolphin uses a global user directory for almost 3 years now so there's no worry about losing user settings (or if that's a concern, making the installer wiping the entire $INSTDIR except "User" folder if it exists inside $INSTDIR).

The point is that doing a 5.0 install on top of 4.0.2 would still leave some .dll from 4.0.2-era laying on the install folder just taking space since they're (probably) useless/outdated for 5.0...

**Comment by RisingFog** [comment]
@mbc07 we overwrite the files normally, but in this scenario, some of the old game settings and themes stick around.

**Comment by mbc07** [comment]
I understand that, but just like some old game settings and themes stick around, some old .DLLs also stick around useless if you install on top of 4.0.2 (msvcp120.dll, vcomp100.dll, etc). That's why I'm suggesting wiping the entire $INSTDIR, not only the Sys folder...

**Comment by RisingFog** [comment]
@mbc07 Makes sense, it'd be trivial to remove the entire $INSTDIR.

Would like to get some opinions if that is better than removing the Sys directory.

**Comment by JosJuice** [comment]
I don't see any reason to not delete the contents of the entire directory.

**Pull request merged**
