### PR TITLE
Added missing SoundStream files to Visual Studio solution

### PR DESCRIPTION
**Pull request by Stevoisiak**
I'm honestly not sure how this hasn't caused any issues before.

### CODE REVIEW

**Comment by lioncash** [comment]
Because those aren't usable, or set up for use on Windows. ALSA is a Linux kernel software framework; Core Audio is the low level audio API used on OSX/iOS; OpenSLES is used for Android. Pulse and libao *can* work on Windows (I think), however it isn't set up currently.

**Comment by Stevoisiak** [comment]
Even if we aren't compiling them on Windows, I don't think it would hurt to include the files in the solution files.
Maybe with a ClInclude unstead of ClCompile?

**Comment by lioncash** [comment]
CLInclude is for heder files. To exclude certain files from the build you add `<ExcludedFromBuild>true</ExcludedFromBuild>` to it.

ie. 
```
<ClCompile Include="SomeFile.cpp">
    <ExcludedFromBuild>true</ExcludedFromBuild>
</ClCompile>
```

**Comment by Stevoisiak** [comment]
Turns out excluding a file from the build also hides it from the solution explorer. So I guess this PR isn't really needed then.

**Pull request closed without merging**
