### PR TITLE
Don't read/store settings directly from/to SYSCONF (and fix config restore)

### PR DESCRIPTION
**Pull request by leoetlino**
Instead of directly reading/storing settings from/to the SYSCONF, we now store Wii settings to Dolphin's own configuration, and apply them on boot. This prevents issues with settings not being saved, being overridden and lost (if the user opens a dialog that writes to the SYSCONF while a game is running).

This also fixes restoring settings from the config cache after a graceful shutdown; for some reason, settings were only restored after a normal shutdown.

Fixes issue 9825 and 9826

---
This change is [Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/4319)

### CODE REVIEW

**Comment by lioncash** [comment]
Review status: 0 of 32 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/BootManager.h, line 14 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4319#-KTWAxZ1cxloWoXZ0L7Q:-KTWAxZ2bL8mSL4MLlQS:bumqzut) ([raw file](https://github.com/dolphin-emu/dolphin/blob/11bb25eb35243dc06d451bbf243f072e7babe430/Source/Core/Core/BootManager.h#L14)):*
> ```objc
> 
> void Stop();
> void RestoreConfig();
> ```

You should probably document what this actually does.

---

*[Source/Core/Core/Core.cpp, line 85 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4319#-KTWBRjAwYXlNpjaHcvW:-KTWBRjBRzeCkVcQKXIe:bwocgcc) ([raw file](https://github.com/dolphin-emu/dolphin/blob/11bb25eb35243dc06d451bbf243f072e7babe430/Source/Core/Core/Core.cpp#L85)):*
> ```cpp
> #endif
> 
> namespace BootManager
> ```

You can just include the header.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4319)*

**Comment by leoetlino** [comment]
Review status: 0 of 32 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Source/Core/Core/BootManager.h, line 14 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4319#-KTWAxZ1cxloWoXZ0L7Q:-KTWEIDuj9S1kv1del5L:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/11bb25eb35243dc06d451bbf243f072e7babe430/Source/Core/Core/BootManager.h#L14)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> You should probably document what this actually does.
</details>
Done.

---

*[Source/Core/Core/Core.cpp, line 85 at r1](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4319#-KTWBRjAwYXlNpjaHcvW:-KTWEIgTK4DT3qeO2MX9:b-896fix) ([raw file](https://github.com/dolphin-emu/dolphin/blob/11bb25eb35243dc06d451bbf243f072e7babe430/Source/Core/Core/Core.cpp#L85)):*
<details><summary><i>Previously, lioncash (Mat M.) wrote…</i></summary>
> You can just include the header.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dolphin-emu/dolphin/4319)*

**Comment by JMC47** [comment]
Can we please get some urgent review on this.  This is a critical bug that could corrupt people's configurations and lead to things like SyncGPU getting permanently enabled.

**Comment by shuffle2** [comment]
What about using the sysconf from nand dump scenario?

**Comment by leoetlino** [comment]
I pushed an update earlier today so that it reads settings from the SYSCONF on startup, so both the NAND dump and existing SYSCONF cases should be handled correctly.

**Comment by shuffle2** [comment]
why has msghandler.h been included in a lot of otherwise-unchanged files?

**Comment by leoetlino** [comment]
Indirect includes. They depended on ConfigManager to include SysConf.h to include MsgHandler.h, and removing the SysConf.h include in ConfigManager.h broke everything.

**Pull request merged**
