### PR TITLE
Aspect Ratio improvements from #2796.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
Since no one else apparently wanted to pick this up, here you go. I thought it would be nice to have these in 5.0.

This takes the Horizontal VI Scaling and Pixel Aspect Ratio Correction improvements from mirrorbender in #2796 without the Smart AR heuristics.

The Horizontal VI Scaling option is not in the GUI and just enabled by default. It's unlikely anyone actually wants to turn this off.

The Pixel Aspect Ratio Correction option is toggleable in the GUI.

See #2796 for more details.

### CODE REVIEW

**Comment by phire** [comment]
Did you have to bring this up right before feature freeze?

**Comment by AdmiralCurtiss** [comment]
Yes.

**Comment by lioncash** [comment]
Considering #2796 has a `[WIP]` text label on it, I'm skeptical of agreeing to including it in 5.0. If there's no regression tests done, or at least indication of it; it shouldn't be merged - definitely not this close to the feature freeze. It's also implied by the comments that JMC never got around to testing PAL games with this (particularly the comment `"I can test PAL games if you want"`)

**Comment by phire** [comment]
There is no sane reason for users to want (just) pixel aspect ratio correction disabled, there are other distortions that pixels go though before getting to the screen. The output with pixel aspect ratio correction disabled can't possibly be considered "correct" in any way.

What users actually want is one of two things: 

 * The pixel for pixel output of the EFB, without any scaling applied, so they can make screenshots. Dolphin has never offered this feature in the past.
 * No black bars on 16:9 monitors.

I will not merge this just because it just so happens to achieve these goals for a large subset of NTSC games.

**Comment by phire** [comment]
I should say, a large subset of "poorly coded" NTSC games.

**Comment by AdmiralCurtiss** [comment]
Fair enough.

**Comment by phire** [comment]
I would accept option(s) that try to minimize the amount of black bars though either cropping, stretching or a combination of both.

I would also accept a "Just show the raw EFB" option. It would be even more useful for debugging if that option always showed the full 640x528 pixels. 

And I would accept per-game options to tweak the aspect ratio (manually or potentially automatically). However we really want to fix up the config system before adding any more per-game options.

**Pull request closed without merging**
