### PR TITLE
Add Global Brawl Netplay Settings

### PR DESCRIPTION
**Pull request by jefflongo**
Creates an ini for Super Smash Bros. Brawl and adds a gecko code for standardized tournament play (unlock all characters and stages, set to a timed, stock battle, items off, ect.)

More info here: http://smashboards.com/threads/brawl-gets-an-optimized-netplay-codeset.397646/

### CODE REVIEW

**Comment by JosJuice** [comment]
The file should have the following at the top: `# RSBE01 - Super Smash Bros. Brawl`

**Comment by pauldacheez** [comment]
Whatever you did, the line you added disappeared along with the second commit. Might I recommend git commit --amend in this case instead of your current squashing method? http://git-scm.com/docs/git-commit
git rebase -i and marking a second commit as fixup (not squash, ironically) would work fine as well. http://git-scm.com/docs/git-rebase

**Comment by lioncash** [comment]
So is this all good now?

**Comment by neobrain** [comment]
I guess there should be *some* description in the ini as to what all that is actually about.

**Comment by jefflongo** [comment]
@neobrain I'm just following the naming of Global Melee Netplay Settings.  This code removes tripping, sets default items off, timed stock match, all stages/characters unlocked.  Basically tournament defaults.  Is there another way you'd like me to do it?  The idea is to have everything in one code.

**Comment by JosJuice** [comment]
Having all of that information in the name of the code probably wouldn't fit well, but I suppose you could put it in a comment (starting with `#`) between `[Gecko]` and `$Global Brawl Netplay Settings`. It won't be visible in the GUI, but everyone who opens the file will see it.

**Comment by jefflongo** [comment]
I will go ahead and do that then.

**Comment by Stevoisiak** [comment]
@dolphin-emu-bot rebuild

**Comment by neobrain** [comment]
Sorry if I was being unclear before. It's good that the patches are now described, but I actually meant to ask for comments on what Global Brawl actually is. That's not really self-evident without having to ask Google about that.

**Comment by jefflongo** [comment]
Is this better? Basically this code is just using default settings that a standard tournament would use.  I'm not sure how to make it clearer from there.

**Comment by JMC47** [comment]
lgtm now based on the description.  It says that it's more or less a tool to make netplay easier, but it's also pretty clear that it does other things that could be used offline for tournaments.  Any other complaints?

dolbuildbot:  rebuild

**Comment by jefflongo** [comment]
we're going to decide on whether or not tripping disabled should be included or not so please don't merge this yet.

**Comment by jefflongo** [comment]
Alright we're leaving it like this, this is good to go.

**Comment by JMC47** [comment]
@dolphin-emu-bot rebuild

**Comment by therandomizer85** [comment]
Why the hell was this added? This is breaking Brawl mods as I do a lot of hack testing for the game.

**Comment by Stevoisiak** [comment]
@therandomizer85 It was added as an optional cheat code. These settings are not enable by default

**Comment by therandomizer85** [comment]
Well, I can't disable it no matter what I do and it's breaking the Brawl modes. I can't remove it from the RSBE01.txt, I can't disable it as Dolphin re-enables it. This is bullshit,  I'm sorry, but it's screwing the game up as I dont' even go online.

**Comment by JMC47** [comment]
Who's the fucking genius who enabled it by default?

**Comment by therandomizer85** [comment]
@JMC47  See? I'm not the only one it's happening to. 

To the people of this discussion, I will personally make a video showing you all what's going on.

**Comment by JMC47** [comment]
Actually, could you record a video anyway?  Showing off the global settings bug would be useful for an issue report to get that fixed.

**Comment by therandomizer85** [comment]
Yes, doing so right now.

**Comment by Stevoisiak** [comment]
@therandomizer85 Sorry, my mistake. Thanks for noticing the issue.

**Comment by JMC47** [comment]
Actually it won't be useful, this Pull Request is just outright wrong.

**Comment by therandomizer85** [comment]
@Stevoisiak  So, what can be done about it? Should I post the video anyway?

**Comment by therandomizer85** [comment]
I really hope that this doesn't become a problem, I don't know why the fucking thing doesn't let me turn it off.

**Comment by JMC47** [comment]
Delete the whole file out of the root of your Dolphin.exe /sys/GameSettings/RSBE01.ini

**Comment by therandomizer85** [comment]
@JMC47  I have too many important codes that I can't find anywhere else and would hate to lose them.

**Comment by JMC47** [comment]
back it up, but I don't think your codes will be in that file.  They should be in My Documents/Dolphin Emulator/GameSettings/RSBE01.ini.  If they aren't, then, yeah, this is a problem.

Either way, this is a serious issue and we will look into it immediately.

**Comment by therandomizer85** [comment]
Isn't that there the Gecko/Ocarina codes are stored as well? And yes, the cheats are where they should be. 

And yes, I deleted the actual .ini and not where the cheats are, seemed to have worked.  Gonna test it, but yeah, it's a problem.

**Comment by JMC47** [comment]
Okay, here's a bigger problem.  This PR is fine.  It turns out the last Gecko Code in every file is being assumed on for some reason.  This is a huge problem.  Sorry @jefflongo for assuming it was this PR's fault; my lack of knowledge with gecko codes fueled that.

So, we need to find a big fix for this soon, thank you so much for bringing it to our attention.

**Comment by therandomizer85** [comment]
Dammit, I didn't mean to bring up what's going to be a royal pain in the ass to fix. Maybe I shouldn't have brought it up? I mean, you're welcome, you really are, but dayum, I didn't know it was gonna be such a PITA :(

**Comment by JMC47** [comment]
It's a serious issue that needs fixing!  An oversight like this could have caused worse issues.  There are other games having issues with this that we found when looking things up.  You saved us trouble overall.

**Comment by therandomizer85** [comment]
I really hope I did, but ugh, I wish I knew how to program, I mean, I didn't even know it was locking up games, like, at all, but yikes. Does a thread need to be made to get the other developers' attention?

**Comment by comex** [comment]
So nobody noticed this issue for 5 weeks?

I will look at it tomorrow.

probably.

**Comment by therandomizer85** [comment]
@comex  Hey, I just noticed it today, and yeah, maybe I shouldn't have played Brawl today, would that have been better? Hell, maybe I shouldn't have even bothered to report it -_- FML

**Comment by comex** [comment]
I'm glad you reported it, since otherwise it would probably stay unfixed for who knows how many more weeks. ;p

**Comment by therandomizer85** [comment]
Well, I guess it's about time I did something right for the Dolphin team for once then, heh :3

**Pull request merged**
