### PR TITLE
TitleDatabase: Let user files override sys files

### PR DESCRIPTION
**Pull request by JosJuice**
This seems like an oversight in the old code, because what's the point of loading user files if the titles in them are going to be ignored for nearly all games?

This PR fixes the issue by making the first `LoadMap` variant not overwrite entries and making the constructor do everything in the opposite order. An alternative solution would be to make the second `LoadMap` variant overwrite entries.

### CODE REVIEW

**Comment by leoetlino** [comment]
Oops, looks like a silly bug :(

Yeah, I intended to let the user overwrite the default database, but didn't notice that LoadMap doesn't overwrite (as it uses emplace, not operator []). I'm fine with either way of fixing it.

**Comment by leoetlino** [comment]
Hmm, would you be opposed to make it overwrite entries? That'd make the order more logical imo

**Comment by JosJuice** [comment]
I was thinking that `emplace` would be cleaner to use than `operator[]` because `operator[]` creates a default-initialized value before we assign something to it. Would you prefer that I change to `operator[]` anyway?

**Comment by Warepire** [comment]
If the code isn't going to be performance-critical, how about `lower_bound` / `upper_bound`, a small check, and if it matches, replace, otherwise `emplace_hint`?

**Comment by JosJuice** [comment]
I think that's too much trouble to be worth the "niceness" of having the constructor in a slightly more logical order.

**Pull request merged**
